import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { TWILIO_SMS_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  TWILIO_SMS_FULL_API_OPERATION_COUNT,
  TWILIO_SMS_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const twilioSmsProviderManifest = defineProviderPackage({
  id: "sms.twilio",
  name: "Twilio Programmable Messaging",
  packageName: "@cognidesk/integrations",
  provider: "twilio",
  category: "sms",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  credentialRequirements: [
    {
      id: "twilio-account",
      label: "Twilio Account SID and Auth Token",
      description: "Server-side Twilio account credentials used for Messaging REST API calls and webhook signature validation.",
      required: true,
    },
    {
      id: "twilio-sms-sender",
      label: "Twilio SMS/MMS-capable sender",
      description: "A Twilio SMS/MMS-capable phone number or Messaging Service configured by the SDK user.",
      required: true,
    },
  ],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for Twilio's official Messaging-domain OpenAPI surfaces: core Message/Media/Feedback/ShortCode resources, Messaging Services v1-v3, Conversations v1-v2, Content v1-v2, Verify v2-v3, and Studio v1-v2.",
      "The package keeps typed convenience helpers for common SMS/MMS support workflows, webhook signature validation, account readiness, and SMS-capable incoming-number readiness.",
      "The SDK user owns consent, opt-in/opt-out, quiet hours, campaign registration, template policy, retention, and provider-side permission design.",
    ],
    evidence: [
      { label: "Twilio Messaging API overview", url: "https://www.twilio.com/docs/messaging/api" },
      { label: "Twilio Message resource", url: "https://www.twilio.com/docs/messaging/api/message-resource" },
      { label: "Twilio Message Scheduling", url: "https://www.twilio.com/docs/messaging/features/message-scheduling" },
      { label: "Twilio Link Shortening", url: "https://www.twilio.com/docs/messaging/features/link-shortening" },
      { label: "Twilio webhook security", url: "https://www.twilio.com/docs/usage/webhooks/webhooks-security" },
      { label: "Twilio IncomingPhoneNumber resource", url: "https://www.twilio.com/docs/phone-numbers/api/incomingphonenumber-resource" },
    ],
  },
  capabilities: [
    {
      capability: "receive",
      label: "Receive inbound SMS/MMS",
      description: "Validates and parses Twilio Messaging webhooks for SDK-user-owned SMS/MMS handling.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send SMS/MMS messages",
      description: "Creates outbound SMS or MMS messages through the Twilio Messages REST resource; mediaUrl creates media messages where the sender, destination, and region support them.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "schedule",
      label: "Schedule SMS/MMS messages",
      description: "Schedules outbound messages through Twilio's Message Scheduling fields when a Messaging Service SID, SendAt, and ScheduleType are supplied.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Twilio messages",
      description: "Reads Twilio Message resources by Message SID.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "List Twilio messages",
      description: "Lists Twilio Message resources with SDK-user-supplied filters such as sender, recipient, or sent date.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Twilio message status",
      description: "Updates supported Twilio Message status fields, such as cancelling queued messages when Twilio permits it.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "twilio.webhook-signature",
      label: "Validate Twilio webhooks",
      description: "Validates X-Twilio-Signature for form-encoded Twilio Messaging webhooks and status callbacks.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "twilioWebhook", label: "Twilio Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "sms.message.receive",
      providerOperation: "parseTwilioSmsWebhook",
      capability: "receive",
      label: "Receive SMS",
      providerObject: "smsMessage",
      audiences: ["customer-facing"],
      exposesSensitiveData: true,
    },
    {
      alias: "sms.message.send",
      providerOperation: "createMessage",
      capability: "send",
      label: "Send SMS",
      providerObject: "smsMessage",
      audiences: ["customer-facing"],
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    },
    {
      alias: "sms.message.schedule",
      providerOperation: "createMessage",
      capability: "schedule",
      label: "Schedule SMS",
      providerObject: "smsMessage",
      audiences: ["customer-facing"],
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    },
    {
      alias: "sms.message.read",
      providerOperation: "fetchMessage",
      capability: "read-provider-object",
      label: "Read SMS",
      providerObject: "smsMessage",
      audiences: ["customer-facing", "internal-support"],
      exposesSensitiveData: true,
    },
    {
      alias: "sms.message.search",
      providerOperation: "listMessages",
      capability: "search-provider-object",
      label: "Search SMS",
      providerObject: "smsMessage",
      audiences: ["customer-facing", "internal-support"],
      exposesSensitiveData: true,
    },
    {
      alias: "sms.message.cancel",
      providerOperation: "updateMessage",
      capability: "update-provider-object",
      label: "Cancel SMS",
      providerObject: "smsMessage",
      audiences: ["internal-support"],
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "Phone numbers, message bodies, message metadata, webhook parameters, delivery status, and media URLs can contain customer data and are exchanged with Twilio.",
    "Twilio credentials stay server-side and are never issued to browsers by this package.",
    "Outbound SMS consent, opt-in/opt-out handling, quiet hours, campaign registration, content policy, retention, and regional compliance are SDK-user-owned responsibilities.",
  ],
  limitations: [
    "Live SMS readiness depends on the SDK user's Twilio account, SMS-capable sender, Messaging Service configuration, phone-number capabilities, regions, carrier registration, webhooks, and account permissions.",
    "This package does not provide product defaults for outbound-contact policy, consent enforcement, message templates, retry behavior, suppression lists, or compliance workflows.",
  ],
  metadata: {
    channelCoverage: {
      fullMessagingDomainApiOperations: "generated-per-operation-functions",
      smsMmsMessages: "typed-create-fetch-list-update-status-and-generated-full-core-surface",
      messagingWebhooks: "typed-parse-verify",
      accountReadiness: "typed-read",
      incomingPhoneNumbers: "typed-list",
      messagingServices: "generated-full-surface",
      mediaLifecycle: "generated-full-surface",
      conversations: "generated-full-surface",
      contentTemplates: "generated-full-surface",
      verify: "generated-full-surface",
      studio: "generated-full-surface",
    },
    fullProviderApiVerification: {
      provider: "twilio-messaging-domain",
      apiVersion: TWILIO_SMS_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-17",
      coverageArtifact: "docs/provider-coverage/twilio-sms-full-api-2026-06-17.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/twilio-sms-full-api-2026-06-17.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/twilio-sms-full-api-2026-06-17.functions.json",
      documentedOperationCount: TWILIO_SMS_FULL_API_OPERATION_COUNT,
      implementedOperationCount: TWILIO_SMS_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: TWILIO_SMS_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
