import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";

export const freshdeskTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.freshdesk",
  name: "Freshdesk Ticketing",
  packageName: "@cognidesk/integrations",
  provider: "freshdesk",
  category: "ticketing",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage is limited to Freshdesk v2 support primitives for tickets, contacts, ticket conversations, replies, notes, selected handoff updates, agent/group reads, current-agent readiness, and SDK-user shared-secret webhook validation.",
      "The official Freshdesk v2 HTML reference has no official public OpenAPI located in the checked docs; docs/provider-coverage/freshdesk-v2-api-2026-06-18.operations.json records 240 documented entries, 19 implemented entries, and 221 explicit gaps.",
      "This is not full Freshdesk API coverage for ticket bulk/merge/forward/archive/delete/restore flows, multipart attachments, companies, roles, SLAs, automations, skills, availability/load settings, custom objects, forums/solutions, customer satisfaction, mailboxes, canned responses, business hours, analytics, or broader admin mutation.",
    ],
    evidence: [
      { label: "Freshdesk API v2 reference", url: "https://developers.freshdesk.com/api/" },
      {
        label: "Freshdesk v2 checked endpoint inventory",
        url: "https://github.com/cognilabz/cognidesk/blob/main/docs/provider-coverage/freshdesk-v2-api-2026-06-18.operations.json",
      },
    ],
  },
  credentialRequirements: [
    {
      id: "freshdesk-domain",
      label: "Freshdesk domain",
      description: "The SDK user's Freshdesk support portal URL, for example https://example.freshdesk.com.",
      required: true,
    },
    {
      id: "freshdesk-api-key",
      label: "Freshdesk API key",
      description: "Server-side Freshdesk API key used with Freshdesk v2 API Basic authentication; effective access is governed by the authenticated agent's Freshdesk role and ticket permissions.",
      scopes: ["read", "write"],
      required: true,
      metadata: {
        scopeKind: "internal-capability-labels",
        privilegeGuidance: "Freshdesk API keys are not OAuth-scoped by these strings; read/write are Cognidesk capability labels for Studio display.",
      },
    },
    {
      id: "freshdesk-webhook-secret",
      label: "Freshdesk webhook shared secret",
      description: "SDK-user-configured secret expected in a Freshdesk automation custom header before webhook payloads are accepted.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Freshdesk automation webhooks",
      description: "Validates SDK-user-configured Freshdesk automation webhook headers and parses JSON ticket payloads.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "freshdeskWebhookEvent", label: "Freshdesk Webhook Event" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Freshdesk tickets and contacts",
      description: "Creates Freshdesk tickets or contacts from SDK-user-selected support and handoff workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "freshdeskTicket", label: "Freshdesk Ticket" },
        { kind: "freshdeskContact", label: "Freshdesk Contact" },
        { kind: "freshdeskConversation", label: "Freshdesk Ticket Conversation" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Freshdesk tickets and contacts",
      description: "Reads Freshdesk tickets, conversations, contacts, and the currently authenticated agent.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "freshdeskTicket", label: "Freshdesk Ticket" },
        { kind: "freshdeskContact", label: "Freshdesk Contact" },
        { kind: "freshdeskConversation", label: "Freshdesk Ticket Conversation" },
        { kind: "freshdeskAgent", label: "Freshdesk Agent" },
        { kind: "freshdeskGroup", label: "Freshdesk Group" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Freshdesk tickets and contacts",
      description: "Updates Freshdesk ticket fields, assignment, status, priority, tags, custom fields, or contact profile fields.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "freshdeskTicket", label: "Freshdesk Ticket" },
        { kind: "freshdeskContact", label: "Freshdesk Contact" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Freshdesk tickets and contacts",
      description: "Searches Freshdesk tickets and contacts with SDK-user-supplied Freshdesk query expressions and pagination.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "freshdeskTicket", label: "Freshdesk Ticket" },
        { kind: "freshdeskContact", label: "Freshdesk Contact" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Attach support handoff to Freshdesk",
      description: "Provides Freshdesk ticket reply, private note, assignment, and status operations for SDK-user-configured human handoff workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "freshdeskTicket", label: "Freshdesk Ticket" },
        { kind: "freshdeskConversation", label: "Freshdesk Ticket Conversation" },
        { kind: "freshdeskAgent", label: "Freshdesk Agent" },
        { kind: "freshdeskGroup", label: "Freshdesk Group" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "freshdesk.webhook-shared-secret",
      label: "Validate Freshdesk webhook shared secret",
      description: "Checks a configured Freshdesk automation custom header against the SDK user's shared secret before parsing request JSON.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "freshdeskWebhookRequest", label: "Freshdesk Webhook Request" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Freshdesk tickets, conversations, private notes, contacts, assignments, tags, custom fields, and automation webhook payloads can contain customer data and internal support context.",
    "Freshdesk API keys and webhook shared secrets stay server-side and are represented in Studio only as readiness and scope status.",
  ],
  limitations: [
    "Ticket forms, required fields, statuses, priorities, products, groups, SLAs, automations, and agent permissions are owned by the SDK user's Freshdesk account.",
    "Freshdesk automation webhooks support configurable custom headers; this package validates an SDK-user-provided shared secret header rather than assuming a universal Freshdesk HMAC signature.",
    "SDK users own human handoff timing, field mapping, requester identity, assignment rules, reply visibility, customer consent, notification policy, and data retention before calling Freshdesk APIs.",
  ],
  metadata: {
    channelCoverage: {
      tickets: "typed-crud-list-search",
      contacts: "typed-crud-search",
      conversations: "typed-list",
      replies: "typed-create",
      privateNotes: "typed-create",
      agents: "typed-read-list",
      groups: "typed-read-list",
      webhookParsing: "typed-verify-parse",
      publicOpenApiSpec: "not-covered",
      freshdeskV2Inventory: "typed-selected",
      multipartAttachments: "provider-supported-not-typed",
      ticketBulkMergeForwardDeleteRestore: "provider-supported-not-typed",
      companiesFieldsFormsForumsSolutionsMailboxes: "provider-supported-not-typed",
      slasAutomationsRolesSkills: "not-covered",
      customObjectsAnalytics: "not-covered",
    },
    coverageArtifacts: {
      freshdeskV2Inventory: {
        artifact: "docs/provider-coverage/freshdesk-v2-api-2026-06-18.operations.json",
        documentedEntries: 240,
        implementedEntries: 19,
        gapEntries: 221,
      },
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
