import {
  allAudiences,
  categoryProfilesCoreIntegrationNote,
  customerAudiences,
  defineIntegrationCategoryProfile,
  internalAudiences,
  operation,
} from "./shared.js";

export const contactCenterCategoryProfile = defineIntegrationCategoryProfile({
  id: "contact-center",
  category: "contact-center",
  label: "Contact Center",
  description: "Provider-neutral contact-center operations for queues, agents, routing, transfers, contacts, tasks, callbacks, monitoring, and artifacts.",
  providerObjects: [
    { kind: "contact", label: "Contact" },
    { kind: "queue", label: "Queue" },
    { kind: "agent", label: "Agent" },
    { kind: "routingProfile", label: "Routing Profile" },
    { kind: "contact-center-task", label: "Contact Center Task" },
    { kind: "contactTransfer", label: "Contact Transfer" },
    { kind: "callback", label: "Callback" },
    { kind: "contactTranscript", label: "Contact Transcript" },
    { kind: "recording", label: "Recording" },
    { kind: "queueMetric", label: "Queue Metric" },
  ],
  operations: [
    operation({
      alias: "contact-center.contact.read",
      label: "Read contact",
      description: "Fetch contact/session state, participant metadata, routing context, and provider IDs.",
      level: "required",
      capability: "read-provider-object",
      providerObject: "contact",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.queue.list",
      label: "List queues",
      description: "List available queues or routing destinations.",
      level: "required",
      capability: "read-provider-object",
      providerObject: "queue",
      audiences: internalAudiences,
    }),
    operation({
      alias: "contact-center.transfer.request",
      label: "Request transfer",
      description: "Transfer a contact to an agent, queue, flow, quick connect, or provider routing target.",
      level: "required",
      capability: "transfer",
      providerObject: "contactTransfer",
      audiences: allAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.handoff.request",
      label: "Request contact-center handoff",
      description: "Create or route a human handoff request through the contact-center provider.",
      level: "recommended",
      capability: "handoff",
      providerObject: "contactTransfer",
      audiences: allAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.contact.start",
      label: "Start contact",
      description: "Start a provider chat, task, email, voice, or outbound contact.",
      level: "recommended",
      capability: "send",
      providerObject: "contact",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.contact.end",
      label: "End contact",
      description: "End or stop an active provider contact.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "contact",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "contact-center.queue.status.read",
      label: "Read queue status",
      description: "Read queue availability, wait time, backlog, or provider queue state.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "queue",
      audiences: internalAudiences,
    }),
    operation({
      alias: "contact-center.agent.list",
      label: "List agents",
      description: "List agents or routable users.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "agent",
      audiences: internalAudiences,
    }),
    operation({
      alias: "contact-center.agent.status.update",
      label: "Update agent status",
      description: "Update agent presence, readiness, or availability state.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "agent",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "contact-center.task.create",
      label: "Create task",
      description: "Create a task/work item for an agent, queue, or routing flow.",
      level: "recommended",
      capability: "create-provider-object",
      providerObject: "contact-center-task",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.task.update",
      label: "Update task",
      description: "Update task attributes, routing target, status, or assignment.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "contact-center-task",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "contact-center.callback.schedule",
      label: "Schedule callback",
      description: "Schedule or request a contact-center callback.",
      level: "recommended",
      capability: "schedule",
      providerObject: "callback",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.handoff.status.read",
      label: "Read contact-center handoff status",
      description: "Read status for a human handoff, callback, or routed support contact.",
      level: "optional",
      capability: "handoff",
      providerObject: "contactTransfer",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.transcript.read",
      label: "Read transcript",
      description: "Fetch transcript or interaction transcript context.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "contactTranscript",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.recording.read",
      label: "Read recording",
      description: "Read recording metadata or artifact references.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "recording",
      audiences: internalAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.routingProfile.read",
      label: "Read routing profile",
      description: "Fetch routing profile or skill routing configuration.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "routingProfile",
      audiences: internalAudiences,
    }),
    operation({
      alias: "contact-center.conversation.monitor",
      label: "Monitor conversation",
      description: "Start supervisor monitoring where supported.",
      level: "optional",
      capability: "media",
      providerObject: "contact",
      audiences: internalAudiences,
      sideEffect: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.conversation.whisper",
      label: "Whisper to agent",
      description: "Send supervisor whisper/coaching media to an agent.",
      level: "optional",
      capability: "send",
      providerObject: "contact",
      audiences: internalAudiences,
      sideEffect: true,
      externallyVisible: false,
    }),
    operation({
      alias: "contact-center.conversation.barge",
      label: "Barge into conversation",
      description: "Join a live conversation as a supervisor participant.",
      level: "optional",
      capability: "transfer",
      providerObject: "contact",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "contact-center.analytics.queueMetrics.read",
      label: "Read queue metrics",
      description: "Read queue metrics, staffing, SLA, or wait-time data.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "queueMetric",
      audiences: internalAudiences,
    }),
  ],
  events: [
    { kind: "contact-center.contact.started", label: "Contact started", description: "A contact started.", direction: "inbound", capability: "receive", providerObject: "contact", operationAlias: "contact-center.contact.read" },
    { kind: "contact-center.contact.ended", label: "Contact ended", description: "A contact ended.", direction: "inbound", capability: "receive", providerObject: "contact", operationAlias: "contact-center.contact.end" },
    { kind: "contact-center.transfer.requested", label: "Transfer requested", description: "A transfer was requested.", direction: "internal", capability: "transfer", providerObject: "contactTransfer", operationAlias: "contact-center.transfer.request" },
    { kind: "contact-center.queue.updated", label: "Queue updated", description: "Queue availability or metrics changed.", direction: "inbound", capability: "receive", providerObject: "queue", operationAlias: "contact-center.queue.status.read" },
    { kind: "contact-center.agent.status.updated", label: "Agent status updated", description: "Agent presence/status changed.", direction: "inbound", capability: "receive", providerObject: "agent", operationAlias: "contact-center.agent.status.update" },
  ],
  outputs: [
    { intent: "contact-center.transfer", label: "Contact transfer", description: "Transfer a contact to another destination.", capability: "transfer", operationAlias: "contact-center.transfer.request", providerObject: "contactTransfer", externallyVisible: true, requiresApproval: true, changesWorkflow: true },
    { intent: "contact-center.task", label: "Contact-center task", description: "Create a task/work item.", capability: "create-provider-object", operationAlias: "contact-center.task.create", providerObject: "contact-center-task", changesWorkflow: true },
    { intent: "contact-center.callback", label: "Callback", description: "Schedule a callback.", capability: "schedule", operationAlias: "contact-center.callback.schedule", providerObject: "callback", externallyVisible: true, requiresApproval: true, changesWorkflow: true },
    { intent: "channel.handoff.requested", label: "Contact-center handoff", description: "Request a contact-center handoff.", capability: "handoff", operationAlias: "contact-center.transfer.request", providerObject: "contactTransfer", changesWorkflow: true },
  ],
  dataSources: [
    { id: "contact-center.contact", label: "Contact", description: "Fetch contact/session context.", capability: "read-provider-object", operationAlias: "contact-center.contact.read", providerObjects: ["contact"], exposesSensitiveData: true },
    { id: "contact-center.queues", label: "Queues", description: "Fetch available queues and status.", capability: "read-provider-object", operationAlias: "contact-center.queue.list", providerObjects: ["queue"] },
    { id: "contact-center.agents", label: "Agents", description: "Fetch available agents and status.", capability: "read-provider-object", operationAlias: "contact-center.agent.list", providerObjects: ["agent"] },
    { id: "contact-center.transcript", label: "Transcript", description: "Fetch contact transcripts.", capability: "read-provider-object", operationAlias: "contact-center.transcript.read", providerObjects: ["contactTranscript"], exposesSensitiveData: true },
    { id: "contact-center.queueMetrics", label: "Queue metrics", description: "Fetch queue metrics for routing decisions.", capability: "read-provider-object", operationAlias: "contact-center.analytics.queueMetrics.read", providerObjects: ["queueMetric"] },
  ],
  notes: [categoryProfilesCoreIntegrationNote],
});
