import {
  allAudiences,
  categoryProfilesCoreIntegrationNote,
  customerAudiences,
  defineIntegrationCategoryProfile,
  internalAudiences,
  operation,
} from "./shared.js";

export const ecommerceCategoryProfile = defineIntegrationCategoryProfile({
  id: "ecommerce",
  category: "ecommerce",
  label: "Ecommerce",
  description: "Provider-neutral commerce support operations for webhook events, orders, customers, products, payments, refunds, subscriptions, invoices, and draft orders.",
  providerObjects: [
    { kind: "commerceEvent", label: "Commerce Event" },
    { kind: "order", label: "Order" },
    { kind: "customer", label: "Customer" },
    { kind: "product", label: "Product" },
    { kind: "payment", label: "Payment" },
    { kind: "refund", label: "Refund" },
    { kind: "subscription", label: "Subscription" },
    { kind: "invoice", label: "Invoice" },
    { kind: "draftOrder", label: "Draft Order" },
    { kind: "webhookEndpoint", label: "Webhook Endpoint" },
  ],
  operations: [
    operation({
      alias: "ecommerce.event.receive",
      label: "Receive commerce event",
      description: "Validate and normalize provider commerce webhooks into channel events.",
      level: "required",
      capability: "receive",
      providerObject: "commerceEvent",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.order.read",
      label: "Read order",
      description: "Fetch an order, checkout, fulfillment, or provider commerce record by provider ID.",
      level: "required",
      capability: "read-provider-object",
      providerObject: "order",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.customer.read",
      label: "Read commerce customer",
      description: "Fetch customer identity, contact details, account metadata, and commerce profile fields.",
      level: "required",
      capability: "read-provider-object",
      providerObject: "customer",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.order.search",
      label: "Search orders",
      description: "Search orders, checkouts, or commerce records by customer, provider ID, date, status, or native query.",
      level: "recommended",
      capability: "search-provider-object",
      providerObject: "order",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.customer.search",
      label: "Search commerce customers",
      description: "Search customers by email, phone, provider ID, account, or provider-native filters.",
      level: "recommended",
      capability: "search-provider-object",
      providerObject: "customer",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.product.read",
      label: "Read product",
      description: "Fetch product, variant, price, or availability details for support context.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "product",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.product.search",
      label: "Search products",
      description: "Search products, variants, prices, or catalog entries.",
      level: "recommended",
      capability: "search-provider-object",
      providerObject: "product",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.draftOrder.create",
      label: "Create draft order",
      description: "Create a draft order, checkout, quote, or payment-support record when policy permits.",
      level: "recommended",
      capability: "create-provider-object",
      providerObject: "draftOrder",
      audiences: internalAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.payment.read",
      label: "Read payment",
      description: "Fetch a payment, payment intent, charge, transaction, or checkout payment state.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "payment",
      audiences: internalAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.refund.create",
      label: "Create refund",
      description: "Create or request a refund when SDK-user policy permits regulated commerce mutation.",
      level: "recommended",
      capability: "create-provider-object",
      providerObject: "refund",
      audiences: internalAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.subscription.read",
      label: "Read subscription",
      description: "Fetch subscription status, renewal, cancellation, entitlement, or plan context.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "subscription",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.invoice.read",
      label: "Read invoice",
      description: "Fetch invoice, receipt, balance, or billing-history context.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "invoice",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.order.update",
      label: "Update order",
      description: "Update provider order metadata, tags, notes, fulfillment support fields, or support-visible state.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "order",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.refund.read",
      label: "Read refund",
      description: "Fetch refund status, amount, reason, and provider metadata.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "refund",
      audiences: internalAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.subscription.update",
      label: "Update subscription",
      description: "Update, cancel, pause, or otherwise mutate subscription state when policy permits.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "subscription",
      audiences: internalAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ecommerce.webhookEndpoint.manage",
      label: "Manage webhook endpoint",
      description: "Create, update, delete, or list provider webhook endpoints when the provider supports endpoint management.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "webhookEndpoint",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
  ],
  events: [
    { kind: "ecommerce.event.received", label: "Commerce event received", description: "A commerce webhook event was received.", direction: "inbound", capability: "receive", providerObject: "commerceEvent", operationAlias: "ecommerce.event.receive" },
    { kind: "ecommerce.order.updated", label: "Order updated", description: "An order or checkout changed.", direction: "inbound", capability: "receive", providerObject: "order", operationAlias: "ecommerce.order.read" },
    { kind: "ecommerce.payment.updated", label: "Payment updated", description: "Payment, invoice, subscription, or refund status changed.", direction: "inbound", capability: "receive", providerObject: "payment", operationAlias: "ecommerce.payment.read" },
  ],
  outputs: [
    { intent: "commerce.draftOrder.create", label: "Draft order", description: "Create a draft order, quote, or checkout support record.", capability: "create-provider-object", operationAlias: "ecommerce.draftOrder.create", providerObject: "draftOrder", externallyVisible: true, requiresApproval: true, changesWorkflow: true },
    { intent: "commerce.refund.create", label: "Refund", description: "Create or request a refund.", capability: "create-provider-object", operationAlias: "ecommerce.refund.create", providerObject: "refund", externallyVisible: true, requiresApproval: true, changesWorkflow: true },
    { intent: "provider.object.update", label: "Commerce update", description: "Update order, subscription, or webhook endpoint state.", capability: "update-provider-object", operationAlias: "ecommerce.order.update", providerObject: "order", requiresApproval: true, changesWorkflow: true },
  ],
  dataSources: [
    { id: "ecommerce.order", label: "Commerce order", description: "Fetch order context.", capability: "read-provider-object", operationAlias: "ecommerce.order.read", providerObjects: ["order"], exposesSensitiveData: true },
    { id: "ecommerce.customer", label: "Commerce customer", description: "Fetch customer context.", capability: "read-provider-object", operationAlias: "ecommerce.customer.read", providerObjects: ["customer"], exposesSensitiveData: true },
    { id: "ecommerce.product", label: "Commerce product", description: "Fetch product context.", capability: "read-provider-object", operationAlias: "ecommerce.product.read", providerObjects: ["product"], exposesSensitiveData: true },
    { id: "ecommerce.payment", label: "Commerce payment", description: "Fetch payment context.", capability: "read-provider-object", operationAlias: "ecommerce.payment.read", providerObjects: ["payment"], exposesSensitiveData: true },
  ],
  notes: [categoryProfilesCoreIntegrationNote],
});
