import {
  allAudiences,
  categoryProfilesCoreIntegrationNote,
  customerAudiences,
  defineIntegrationCategoryProfile,
  internalAudiences,
  operation,
} from "./shared.js";

export const voiceCategoryProfile = defineIntegrationCategoryProfile({
  id: "voice",
  category: "voice",
  label: "Voice",
  description: "Provider-neutral voice sessions with inbound/outbound calls, call control, callbacks, transcripts, recordings, speech, and media operations.",
  providerObjects: [
    { kind: "voiceSession", label: "Voice Session" },
    { kind: "voiceCall", label: "Voice Call" },
    { kind: "voiceTurn", label: "Voice Turn" },
    { kind: "transcript", label: "Transcript" },
    { kind: "recording", label: "Recording" },
    { kind: "callback", label: "Callback" },
    { kind: "conference", label: "Conference" },
    { kind: "mediaStream", label: "Media Stream" },
  ],
  operations: [
    operation({
      alias: "voice.session.start",
      label: "Start voice session",
      description: "Open or normalize a voice session for SDK conversation handling.",
      level: "required",
      capability: "receive",
      providerObject: "voiceSession",
      audiences: customerAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "voice.turn.finalize",
      label: "Finalize voice turn",
      description: "Commit a completed user or assistant voice turn into the channel event stream.",
      level: "required",
      capability: "receive",
      providerObject: "voiceTurn",
      audiences: customerAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "voice.call.start",
      label: "Start outbound call",
      description: "Place or initiate an outbound call.",
      level: "recommended",
      capability: "send",
      providerObject: "voiceCall",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "voice.call.answer",
      label: "Answer call",
      description: "Answer or accept an inbound call.",
      level: "recommended",
      capability: "receive",
      providerObject: "voiceCall",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "voice.call.hangup",
      label: "Hang up call",
      description: "End an active voice call.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "voiceCall",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "voice.call.transfer",
      label: "Transfer call",
      description: "Transfer an active call to an agent, queue, phone number, SIP target, or provider routing target.",
      level: "recommended",
      capability: "transfer",
      providerObject: "voiceCall",
      audiences: allAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "voice.call.hold",
      label: "Hold call",
      description: "Place an active call on hold.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "voiceCall",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "voice.call.resume",
      label: "Resume call",
      description: "Resume an active call from hold.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "voiceCall",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "voice.callback.schedule",
      label: "Schedule callback",
      description: "Schedule a callback or provider-owned outbound voice contact.",
      level: "recommended",
      capability: "schedule",
      providerObject: "callback",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "voice.callback.cancel",
      label: "Cancel callback",
      description: "Cancel or mark a scheduled callback as no longer needed.",
      level: "recommended",
      capability: "cleanup",
      providerObject: "callback",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "voice.transcript.read",
      label: "Read transcript",
      description: "Read transcript segments or full voice transcript artifacts.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "transcript",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "voice.recording.read",
      label: "Read recording",
      description: "Read recording metadata or retrieve a recording reference.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "recording",
      audiences: internalAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "voice.speak",
      label: "Speak audio",
      description: "Send synthesized speech, prompt audio, or provider voice output into a call/session.",
      level: "recommended",
      capability: "send",
      providerObject: "voiceTurn",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
    }),
    operation({
      alias: "voice.dtmf.send",
      label: "Send DTMF",
      description: "Send DTMF tones into a call.",
      level: "optional",
      capability: "send",
      providerObject: "voiceCall",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
    }),
    operation({
      alias: "voice.recording.start",
      label: "Start recording",
      description: "Start recording an active call/session where legal and configured.",
      level: "optional",
      capability: "media",
      providerObject: "recording",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "voice.recording.stop",
      label: "Stop recording",
      description: "Stop an active call/session recording.",
      level: "optional",
      capability: "media",
      providerObject: "recording",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "voice.call.redirect",
      label: "Redirect call",
      description: "Redirect call control to a new provider URL, flow, or routing instruction.",
      level: "optional",
      capability: "transfer",
      providerObject: "voiceCall",
      audiences: internalAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "voice.conference.addParticipant",
      label: "Add conference participant",
      description: "Add an agent, phone number, SIP target, or participant to a conference.",
      level: "optional",
      capability: "transfer",
      providerObject: "conference",
      audiences: allAudiences,
      sideEffect: true,
      externallyVisible: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "voice.mediaStream.start",
      label: "Start media stream",
      description: "Start a realtime media stream for ASR, TTS, monitoring, or voice agent processing.",
      level: "optional",
      capability: "media",
      providerObject: "mediaStream",
      audiences: internalAudiences,
      sideEffect: true,
      exposesSensitiveData: true,
    }),
  ],
  events: [
    { kind: "voice.session.started", label: "Voice session started", description: "A provider voice session started.", direction: "inbound", capability: "receive", providerObject: "voiceSession", operationAlias: "voice.session.start" },
    { kind: "voice.call.answered", label: "Call answered", description: "A call was answered or accepted.", direction: "inbound", capability: "receive", providerObject: "voiceCall", operationAlias: "voice.call.answer" },
    { kind: "voice.turn.finalized", label: "Voice turn finalized", description: "A voice turn transcript segment was finalized.", direction: "inbound", capability: "receive", providerObject: "voiceTurn", operationAlias: "voice.turn.finalize" },
    { kind: "voice.call.ended", label: "Call ended", description: "A call ended or was hung up.", direction: "inbound", capability: "receive", providerObject: "voiceCall", operationAlias: "voice.call.hangup" },
    { kind: "voice.transcript.committed", label: "Transcript committed", description: "Transcript data became available or was committed.", direction: "inbound", capability: "receive", providerObject: "transcript", operationAlias: "voice.transcript.read" },
    { kind: "voice.recording.available", label: "Recording available", description: "A recording artifact became available.", direction: "inbound", capability: "receive", providerObject: "recording", operationAlias: "voice.recording.read" },
  ],
  outputs: [
    { intent: "voice.reply", label: "Voice reply", description: "Speak an assistant response into the active call.", capability: "send", operationAlias: "voice.speak", providerObject: "voiceTurn", externallyVisible: true },
    { intent: "voice.call.transfer", label: "Voice transfer", description: "Transfer an active voice call.", capability: "transfer", operationAlias: "voice.call.transfer", providerObject: "voiceCall", externallyVisible: true, requiresApproval: true, changesWorkflow: true },
    { intent: "voice.callback.schedule", label: "Voice callback", description: "Schedule or request a callback.", capability: "schedule", operationAlias: "voice.callback.schedule", providerObject: "callback", externallyVisible: true, requiresApproval: true, changesWorkflow: true },
    { intent: "channel.handoff.requested", label: "Voice handoff", description: "Request a handoff from voice into another human or provider workflow.", capability: "handoff", operationAlias: "voice.call.transfer", providerObject: "voiceCall", changesWorkflow: true },
  ],
  dataSources: [
    { id: "voice.transcript", label: "Voice transcript", description: "Fetch transcript context.", capability: "read-provider-object", operationAlias: "voice.transcript.read", providerObjects: ["transcript"], exposesSensitiveData: true },
    { id: "voice.recording", label: "Voice recording", description: "Fetch recording references.", capability: "read-provider-object", operationAlias: "voice.recording.read", providerObjects: ["recording"], exposesSensitiveData: true },
    { id: "voice.session", label: "Voice session", description: "Fetch session and call context.", capability: "read-provider-object", operationAlias: "voice.transcript.read", providerObjects: ["voiceSession", "voiceCall"], exposesSensitiveData: true },
  ],
  notes: [categoryProfilesCoreIntegrationNote],
});
