import {
  allAudiences,
  categoryProfilesCoreIntegrationNote,
  defineIntegrationCategoryProfile,
  internalAudiences,
  operation,
} from "./shared.js";

export const workplaceCategoryProfile = defineIntegrationCategoryProfile({
  id: "workplace",
  category: "workplace",
  label: "Workplace",
  description: "Provider-neutral internal workplace collaboration operations for messages, threads, channels, users, files, notifications, and workflow triggers.",
  providerObjects: [
    { kind: "workplaceMessage", label: "Workplace Message" },
    { kind: "workplaceThread", label: "Workplace Thread" },
    { kind: "workplaceChannel", label: "Workplace Channel" },
    { kind: "workplaceUser", label: "Workplace User" },
    { kind: "workplaceFile", label: "Workplace File" },
    { kind: "workplaceReaction", label: "Workplace Reaction" },
    { kind: "workplaceWorkflow", label: "Workplace Workflow" },
  ],
  operations: [
    operation({
      alias: "workplace.message.receive",
      label: "Receive workplace message",
      description: "Normalize an inbound workplace event, message, or interaction into a channel event.",
      level: "required",
      capability: "receive",
      providerObject: "workplaceMessage",
      audiences: internalAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "workplace.thread.read",
      label: "Read workplace thread",
      description: "Fetch a workplace thread, replies, participants, and provider metadata.",
      level: "required",
      capability: "read-provider-object",
      providerObject: "workplaceThread",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "workplace.message.send",
      label: "Send workplace message",
      description: "Post a workplace message to a channel, room, or direct conversation.",
      level: "required",
      capability: "send",
      providerObject: "workplaceMessage",
      audiences: internalAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "workplace.message.reply",
      label: "Reply in workplace thread",
      description: "Post a reply into an existing workplace thread.",
      level: "recommended",
      capability: "send",
      providerObject: "workplaceMessage",
      audiences: internalAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "workplace.message.update",
      label: "Update workplace message",
      description: "Update an existing provider message when policy permits mutation.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "workplaceMessage",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "workplace.channel.search",
      label: "Search workplace channels",
      description: "Search or list channels, rooms, teams, or spaces that can receive support messages.",
      level: "recommended",
      capability: "search-provider-object",
      providerObject: "workplaceChannel",
      audiences: internalAudiences,
    }),
    operation({
      alias: "workplace.user.read",
      label: "Read workplace user",
      description: "Fetch a workplace user profile, display name, or routable user identity.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "workplaceUser",
      audiences: internalAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "workplace.file.upload",
      label: "Upload workplace file",
      description: "Upload or attach a file to a workplace channel or thread.",
      level: "recommended",
      capability: "media",
      providerObject: "workplaceFile",
      audiences: internalAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "workplace.notification.send",
      label: "Send workplace notification",
      description: "Send a targeted internal notification such as an ephemeral message, mention, or agent-assist alert.",
      level: "recommended",
      capability: "notify",
      providerObject: "workplaceMessage",
      audiences: internalAudiences,
      sideEffect: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "workplace.message.delete",
      label: "Delete workplace message",
      description: "Delete or redact a provider message when supported and allowed.",
      level: "optional",
      capability: "delete-provider-object",
      providerObject: "workplaceMessage",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "workplace.reaction.add",
      label: "Add workplace reaction",
      description: "Add a reaction, acknowledgment, or lightweight status marker to a workplace message.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "workplaceReaction",
      audiences: internalAudiences,
      sideEffect: true,
    }),
    operation({
      alias: "workplace.channel.join",
      label: "Join workplace channel",
      description: "Join or make the integration available in a channel, room, team, or space.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "workplaceChannel",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "workplace.workflow.trigger",
      label: "Trigger workplace workflow",
      description: "Trigger a provider workflow, shortcut, or automation from a support action.",
      level: "optional",
      capability: "create-provider-object",
      providerObject: "workplaceWorkflow",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
  ],
  events: [
    { kind: "workplace.message.received", label: "Workplace message received", description: "A workplace message or interaction was received.", direction: "inbound", capability: "receive", providerObject: "workplaceMessage", operationAlias: "workplace.message.receive" },
    { kind: "workplace.thread.updated", label: "Workplace thread updated", description: "A workplace thread changed.", direction: "inbound", capability: "receive", providerObject: "workplaceThread", operationAlias: "workplace.thread.read" },
    { kind: "workplace.notification.sent", label: "Workplace notification sent", description: "A targeted workplace notification was sent.", direction: "outbound", capability: "notify", providerObject: "workplaceMessage", operationAlias: "workplace.notification.send" },
  ],
  outputs: [
    { intent: "message.send", label: "Workplace message", description: "Post a workplace message.", capability: "send", operationAlias: "workplace.message.send", providerObject: "workplaceMessage", externallyVisible: true, requiresApproval: true },
    { intent: "message.reply", label: "Workplace reply", description: "Reply in a workplace thread.", capability: "send", operationAlias: "workplace.message.reply", providerObject: "workplaceMessage", externallyVisible: true, requiresApproval: true },
    { intent: "notification.send", label: "Workplace notification", description: "Send an internal workplace notification.", capability: "notify", operationAlias: "workplace.notification.send", providerObject: "workplaceMessage" },
  ],
  dataSources: [
    { id: "workplace.thread", label: "Workplace thread", description: "Fetch thread context.", capability: "read-provider-object", operationAlias: "workplace.thread.read", providerObjects: ["workplaceThread", "workplaceMessage"], exposesSensitiveData: true },
    { id: "workplace.channel", label: "Workplace channel search", description: "Search routable channels.", capability: "search-provider-object", operationAlias: "workplace.channel.search", providerObjects: ["workplaceChannel"] },
    { id: "workplace.user", label: "Workplace user", description: "Fetch a workplace user.", capability: "read-provider-object", operationAlias: "workplace.user.read", providerObjects: ["workplaceUser"], exposesSensitiveData: true },
  ],
  notes: [categoryProfilesCoreIntegrationNote],
});
