import { defineIntegrationProviderPackage, type ProviderManifestInput } from "@cognidesk/integration-kit";

export const freshdeskTicketingProviderManifestInput = {
  id: "ticketing.freshdesk",
  name: "Freshdesk Ticketing",
  packageName: "@cognidesk/integration-ticketing-freshdesk",
  provider: "freshdesk",
  category: "ticketing",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    { id: "freshdesk-domain", label: "Freshdesk domain", required: true },
    {
      id: "freshdesk-api-key",
      label: "Freshdesk API key",
      scopes: ["read", "write"],
      required: true,
      metadata: {
        scopeKind: "internal-capability-labels",
        privilegeGuidance: "Freshdesk API keys are governed by the authenticated agent's Freshdesk role and ticket permissions.",
      },
    },
    { id: "freshdesk-webhook-secret", label: "Freshdesk webhook shared secret", required: false },
  ],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Implementation uses the official @freshworks/freshdesk JavaScript SDK by default when domain and apiKey are configured.",
      "A constrained Freshdesk v2 REST fallback remains only for SDK gaps such as agents, groups, readiness, and explicit low-level host controls like custom fetch, retry, timeout, headers, or apiBaseUrl.",
      "Coverage is limited to Freshdesk v2 tickets, contacts, conversations, replies, notes, handoff updates, agents, groups, current-agent readiness, and SDK-user shared-secret webhook validation.",
    ],
    evidence: [
      { label: "Freshdesk API v2 reference", url: "https://developers.freshdesk.com/api/" },
      { label: "Freshworks Freshdesk SDK", url: "https://www.npmjs.com/package/@freshworks/freshdesk" },
      { label: "Freshworks API SDK", url: "https://www.npmjs.com/package/@freshworks/api-sdk" },
      { label: "Freshworks API SDK repository", url: "https://github.com/freshworks/freshworks-api-sdk" },
      { label: "Freshworks API SDK announcement", url: "https://community.freshworks.dev/t/freshworks-api-sdk-for-node-js/5232" },
    ],
  },
  capabilities: [
    { capability: "receive", providerObjects: [{ kind: "freshdeskWebhookEvent", label: "Freshdesk Webhook Event" }], requiresCredential: true, exposesSensitiveData: true },
    { capability: "create-provider-object", providerObjects: [{ kind: "freshdeskTicket", label: "Freshdesk Ticket" }, { kind: "freshdeskContact", label: "Freshdesk Contact" }, { kind: "freshdeskConversation", label: "Freshdesk Ticket Conversation" }], requiresCredential: true, sideEffect: true, exposesSensitiveData: true, changesWorkflow: true },
    { capability: "read-provider-object", providerObjects: [{ kind: "freshdeskTicket", label: "Freshdesk Ticket" }, { kind: "freshdeskContact", label: "Freshdesk Contact" }, { kind: "freshdeskAgent", label: "Freshdesk Agent" }, { kind: "freshdeskGroup", label: "Freshdesk Group" }], requiresCredential: true, exposesSensitiveData: true },
    { capability: "update-provider-object", providerObjects: [{ kind: "freshdeskTicket", label: "Freshdesk Ticket" }, { kind: "freshdeskContact", label: "Freshdesk Contact" }], requiresCredential: true, sideEffect: true, exposesSensitiveData: true, changesWorkflow: true },
    { capability: "search-provider-object", providerObjects: [{ kind: "freshdeskTicket", label: "Freshdesk Ticket" }, { kind: "freshdeskContact", label: "Freshdesk Contact" }], requiresCredential: true, exposesSensitiveData: true },
    { capability: "handoff", providerObjects: [{ kind: "freshdeskTicket", label: "Freshdesk Ticket" }, { kind: "freshdeskConversation", label: "Freshdesk Ticket Conversation" }], requiresCredential: true, sideEffect: true, exposesSensitiveData: true, changesWorkflow: true },
  ],
  operations: [
    { alias: "ticket.create", capability: "create-provider-object", providerOperation: "POST /api/v2/tickets", providerObject: "ticket", sideEffect: true, exposesSensitiveData: true, changesWorkflow: true },
    { alias: "ticket.read", capability: "read-provider-object", providerOperation: "GET /api/v2/tickets/{ticket_id}", providerObject: "ticket", exposesSensitiveData: true },
    { alias: "ticket.update", capability: "update-provider-object", providerOperation: "PUT /api/v2/tickets/{ticket_id}", providerObject: "ticket", sideEffect: true, exposesSensitiveData: true, changesWorkflow: true },
    { alias: "ticket.search", capability: "search-provider-object", providerOperation: "GET /api/v2/search/tickets", providerObject: "ticket", exposesSensitiveData: true },
    { alias: "ticket.comment.create", capability: "send", providerOperation: "POST /api/v2/tickets/{ticket_id}/reply", providerObject: "ticketComment", sideEffect: true, externallyVisible: true, exposesSensitiveData: true },
    { alias: "ticket.internalNote.create", capability: "draft", providerOperation: "POST /api/v2/tickets/{ticket_id}/notes", providerObject: "internalNote", sideEffect: true, exposesSensitiveData: true },
    { alias: "customer.read", capability: "read-provider-object", providerOperation: "GET /api/v2/contacts/{contact_id}", providerObject: "customer", exposesSensitiveData: true },
    { alias: "customer.search", capability: "search-provider-object", providerOperation: "GET /api/v2/search/contacts", providerObject: "customer", exposesSensitiveData: true },
    { alias: "freshdesk.agent.read", capability: "read-provider-object", providerOperation: "GET /api/v2/agents/{agent_id}", providerObject: "freshdeskAgent", extension: true, exposesSensitiveData: true },
    { alias: "freshdesk.group.read", capability: "read-provider-object", providerOperation: "GET /api/v2/groups/{group_id}", providerObject: "freshdeskGroup", extension: true },
    { alias: "freshdesk.readiness", capability: "read-provider-object", providerOperation: "GET /api/v2/agents/me", providerObject: "freshdeskAgent", extension: true, exposesSensitiveData: true },
    { alias: "freshdesk.webhook.parse", capability: "receive", providerOperation: "SDK-user configured automation webhook", providerObject: "freshdeskWebhookEvent", extension: true, exposesSensitiveData: true },
  ],
  privacyNotes: ["Freshdesk tickets, conversations, notes, contacts, assignments, tags, custom fields, and automation webhook payloads can contain customer data."],
  limitations: ["Ticket forms, required fields, statuses, products, groups, SLAs, automations, and agent permissions are SDK-user configuration."],
  metadata: {
    issue: 35,
    implementation: {
      strategy: "provider-sdk-adapter",
      runtimePackage: "@cognidesk/integration-ticketing-freshdesk",
      providerClient: "FreshdeskTicketingProviderClient",
      providerClientInterface: "FreshdeskTicketingProviderClient",
      rawClientEscapeHatch: "FreshdeskTicketingClient.providerClient",
      providerSdkPackage: "@freshworks/freshdesk",
      defaultClientPolicy: "use-official-freshworks-freshdesk-sdk-when-domain-and-apiKey-are-configured",
      packageOwnedRestClient: false,
      packageOwnedRestFallback: true,
      providerClientOverride: true,
      rawClientOverride: true,
      sdkDecision: {
        checkedAt: "2026-06-25",
        package: "@freshworks/freshdesk",
        checkedVersion: "0.0.1",
        license: "freshdesk",
        result: "accepted-runtime-sdk",
        reason: "@freshworks/freshdesk exposes Freshdesk tickets, contacts, and conversations runtime clients. Agents, groups, and current-agent readiness are not exposed by that package and stay behind the narrow REST fallback.",
        packageChecked: "@freshworks/freshdesk",
        notes: [
          "@freshworks/freshdesk 0.0.1 exposes tickets.createTicket/getTicket/updateTicket/searchTicket/replyTicket/addNotes and contacts.getContact/searchContacts.",
          "The package does not expose agents/groups/readiness helpers; those remain REST fallback operations.",
        ],
      },
      delegatedOperationTarget: "official Freshdesk SDK, REST fallback for SDK gaps, or injected Freshdesk provider client",
    },
    sdkDecision: {
      checkedAt: "2026-06-25",
      package: "@freshworks/freshdesk",
      checkedVersion: "0.0.1",
      license: "freshdesk",
      result: "accepted-runtime-sdk",
      reason: "@freshworks/freshdesk is the official Freshdesk JavaScript SDK and is used for the ticket/contact operations it exposes.",
    },
    freshdeskV2Coverage: {
      source: "Freshdesk API v2",
      allowlistedOperations: ["tickets.create", "tickets.read", "tickets.update", "tickets.search", "reply.create", "note.create", "contacts.read", "contacts.search", "agents.read", "groups.read", "agents.me", "automation_webhook.parse"],
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
} as const satisfies ProviderManifestInput;

export const freshdeskTicketingProviderManifest = defineIntegrationProviderPackage(freshdeskTicketingProviderManifestInput);
