import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import {
  INTERCOM_FULL_API_GENERATED_FUNCTION_COUNT,
} from "./full-api-client.generated.js";
import {
  INTERCOM_FULL_API_OPERATION_COUNT,
  INTERCOM_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const intercomTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.intercom",
  name: "Intercom",
  packageName: "@cognidesk/integrations",
  provider: "intercom",
  category: "ticketing",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    {
      id: "intercom-access-token",
      label: "Intercom access token",
      description: "Server-side Intercom access token or OAuth bearer token for REST API calls.",
      scopes: ["read_conversations", "write_conversations", "read_tickets", "write_tickets"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "intercom-webhook-secret",
      label: "Intercom webhook secret",
      description: "Server-side app client secret used to validate Intercom X-Hub-Signature webhooks.",
      required: false,
    },
  ],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Intercom's official stable REST API 2.15 OpenAPI file.",
      "Typed convenience helpers remain limited to selected Intercom conversation, ticket, /me identity, and X-Hub-Signature webhook primitives for Cognidesk support workflows.",
      "SDK users still own Intercom app scopes, workspace ticket schemas, teammate/team assignment policy, webhook subscriptions, and API version rollout policy.",
    ],
    evidence: [
      { label: "Intercom official OpenAPI specs", url: "https://github.com/intercom/Intercom-OpenAPI" },
      { label: "Intercom REST API 2.15 OpenAPI YAML", url: "https://raw.githubusercontent.com/intercom/Intercom-OpenAPI/main/descriptions/2.15/api.intercom.io.yaml" },
      { label: "Intercom REST API reference", url: "https://developers.intercom.com/docs/references/rest-api/api.intercom.io" },
      { label: "Intercom Conversations API", url: "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/conversations" },
      { label: "Intercom Tickets API", url: "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/tickets" },
      { label: "Intercom identify admin", url: "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/admins/identifyadmin" },
      { label: "Intercom Webhook Topics and signed notifications", url: "https://developers.intercom.com/docs/references/webhooks/webhook-models" },
    ],
  },
  capabilities: [
    {
      capability: "receive",
      label: "Receive Intercom webhooks",
      description: "Validates and parses Intercom webhook notifications for SDK-user-owned support workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "intercomWebhookNotification", label: "Intercom Webhook Notification" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Intercom conversations and tickets",
      description: "Creates Intercom contact-initiated conversations or tickets from SDK-user-selected support workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "intercomConversation", label: "Intercom Conversation" },
        { kind: "intercomTicket", label: "Intercom Ticket" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Intercom conversations and tickets",
      description: "Reads Intercom conversations or tickets by API id.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "intercomConversation", label: "Intercom Conversation" },
        { kind: "intercomTicket", label: "Intercom Ticket" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Intercom conversations and tickets",
      description: "Updates Intercom conversation metadata, read state, ticket attributes, sharing, snooze, assignment, and state fields when SDK-user policy permits.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "intercomConversation", label: "Intercom Conversation" },
        { kind: "intercomTicket", label: "Intercom Ticket" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Intercom conversations and tickets",
      description: "Searches Intercom conversations or tickets with SDK-user-supplied Intercom query objects and pagination.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "intercomConversation", label: "Intercom Conversation" },
        { kind: "intercomTicket", label: "Intercom Ticket" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Attach support handoff to Intercom",
      description: "Provides conversation and ticket operations for SDK-user-configured human handoff workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "intercomConversation", label: "Intercom Conversation" },
        { kind: "intercomTicket", label: "Intercom Ticket" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "intercom.request-signature",
      label: "Validate Intercom request signatures",
      description: "Validates Intercom X-Hub-Signature values before parsing webhook notification JSON.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "intercomSignedRequest", label: "Intercom Signed Request" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Intercom conversations, conversation parts, tickets, ticket parts, contacts, admins, teams, tags, custom attributes, webhook payloads, and assignment metadata can contain customer data and internal support context.",
    "Intercom access tokens and webhook secrets stay server-side and are represented in Studio only as readiness and scope status.",
  ],
  limitations: [
    "Ticket types, ticket attributes, ticket states, conversation search fields, Inbox assignment targets, teammate availability, and API scopes are owned by the SDK user's Intercom workspace.",
    "SDK users own human handoff timing, assignment rules, reply visibility, customer consent, notification suppression, data retention, redaction, and workspace policy decisions before calling Intercom APIs.",
    "Public replies, internal notes, shared ticket visibility, and customer-facing ticket state labels must be mapped by the SDK user to their Intercom workspace policy.",
  ],
  metadata: {
    fullProviderApiVerification: {
      provider: "intercom",
      apiVersion: INTERCOM_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/intercom-rest-api-2.15-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/intercom-rest-api-2.15-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/intercom-rest-api-2.15-2026-06-18.functions.json",
      documentedOperationCount: INTERCOM_FULL_API_OPERATION_COUNT,
      implementedOperationCount: INTERCOM_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: INTERCOM_FULL_API_GENERATED_FUNCTION_COUNT,
    },
    channelCoverage: {
      fullIntercomRestApi215Operations: "generated-per-operation-functions",
      conversations: "typed-create-read-update-reply-search-and-generated-full-surface",
      tickets: "typed-create-read-update-search-and-generated-full-surface",
      webhooks: "typed-verify-parse-only",
      adminIdentity: "typed-readiness-read-and-generated-full-surface",
      contactsCompaniesAdminsTeamsTags: "generated-full-surface",
      helpCenterArticlesFinWhatsApp: "generated-full-surface",
      webhookSubscriptionManagement: "generated-full-surface",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
