import {
  defineIntegrationProviderPackage,
  type ProviderManifestInput,
} from "@cognidesk/integration-kit";

export const slackWorkplaceOperationAliases = [
  "workplace.message.receive",
  "workplace.thread.read",
  "workplace.message.send",
  "workplace.message.reply",
  "workplace.message.update",
  "workplace.file.upload",
  "workplace.notification.send",
  "slack.request-signature",
] as const;

export const slackWorkplaceManifestInput = {
  id: "workplace.slack",
  name: "Slack",
  packageName: "@cognidesk/workplace-slack",
  provider: "slack",
  category: "workplace",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["internal-support", "mixed"],
  credentialRequirements: [
    {
      id: "slack-bot-token",
      label: "Slack bot token",
      description: "Server-side bot token used by @slack/web-api for Web API calls.",
      scopes: [
        "chat:write",
        "chat:write.public",
        "channels:history",
        "groups:history",
        "im:history",
        "mpim:history",
        "files:write",
      ],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "slack-signing-secret",
      label: "Slack signing secret",
      description: "Server-side signing secret used to validate Slack Events API and interactivity requests.",
      required: true,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Slack events",
      description: "Validates and parses Slack Events API and interactivity payloads for SDK-user-owned support flows.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "slackEvent", label: "Slack Event" },
        { kind: "workplaceMessage", label: "Workplace Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Post Slack messages",
      description: "Posts channel-visible support messages through @slack/web-api chat.postMessage.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "workplaceMessage", label: "Workplace Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "notify",
      label: "Post Slack agent-assist notifications",
      description: "Posts Slack ephemeral messages for internal agent-assist workflows when Slack provides a target user.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "workplaceMessage", label: "Workplace Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Slack threads",
      description: "Associates messages with Slack thread timestamps and reads thread replies.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "workplaceMessage", label: "Workplace Message" },
        { kind: "workplaceThread", label: "Workplace Thread" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Upload Slack files",
      description: "Runs Slack's external upload URL and complete-upload sequence for SDK-user-selected file sharing.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "workplaceFile", label: "Workplace File" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Slack conversation history",
      description: "Reads Slack conversation history or thread replies for SDK-user-selected channels and windows.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "workplaceThread", label: "Workplace Thread" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Slack messages",
      description: "Updates Slack messages through chat.update when SDK-user policy permits mutation.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "workplaceMessage", label: "Workplace Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "slack.request-signature",
      label: "Validate Slack request signatures",
      description: "Validates Slack X-Slack-Signature and X-Slack-Request-Timestamp values.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "slackSignedRequest", label: "Slack Signed Request" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "workplace.message.receive",
      capability: "receive",
      providerObject: "workplaceMessage",
      inputSchemaName: "ParseSlackSignedRequestInput",
      outputSchemaName: "SlackSignedRequest",
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "workplace.thread.read",
      capability: "read-provider-object",
      providerObject: "workplaceThread",
      providerOperation: "conversations.replies",
      inputSchemaName: "SlackConversationsRepliesInput",
      outputSchemaName: "SlackConversationsRepliesResponse",
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "workplace.message.send",
      capability: "send",
      providerObject: "workplaceMessage",
      providerOperation: "chat.postMessage",
      inputSchemaName: "SlackPostMessageInput",
      outputSchemaName: "SlackPostMessageResponse",
      requiresCredential: true,
      sideEffect: true,
      externallyVisible: true,
      exposesSensitiveData: true,
    },
    {
      alias: "workplace.message.reply",
      capability: "send",
      providerObject: "workplaceMessage",
      providerOperation: "chat.postMessage",
      inputSchemaName: "SlackPostMessageInput",
      outputSchemaName: "SlackPostMessageResponse",
      requiresCredential: true,
      sideEffect: true,
      externallyVisible: true,
      exposesSensitiveData: true,
    },
    {
      alias: "workplace.message.update",
      capability: "update-provider-object",
      providerObject: "workplaceMessage",
      providerOperation: "chat.update",
      inputSchemaName: "SlackUpdateMessageInput",
      outputSchemaName: "SlackUpdateMessageResponse",
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    },
    {
      alias: "workplace.file.upload",
      capability: "media",
      providerObject: "workplaceFile",
      providerOperation: "files.getUploadURLExternal/files.completeUploadExternal",
      inputSchemaName: "SlackUploadExternalFileInput",
      outputSchemaName: "SlackCompleteUploadExternalResponse",
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      alias: "workplace.notification.send",
      capability: "notify",
      providerObject: "workplaceMessage",
      providerOperation: "chat.postEphemeral",
      inputSchemaName: "SlackPostEphemeralInput",
      outputSchemaName: "SlackPostEphemeralResponse",
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      alias: "slack.request-signature",
      capability: "slack.request-signature",
      providerObject: "slackSignedRequest",
      inputSchemaName: "ValidateSlackRequestSignatureInput",
      outputSchemaName: "WebhookVerificationResult",
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is a Cognidesk support workflow adapter backed by Slack's official @slack/web-api package.",
      "Typed operations cover Slack Events API/interactivity request parsing, signed request validation, chat.postMessage, chat.postEphemeral, chat.update, conversations.replies, the external file upload sequence, and auth.test readiness.",
      "This package intentionally does not clone Slack's archived generated Web API spec and does not claim full Slack platform coverage.",
      "Slack Socket Mode, OAuth installation flows, incoming webhook delivery, SCIM, Audit Logs, Legal Holds, workflow runtime behavior, and broad admin APIs are separate extension surfaces or future packages.",
    ],
    evidence: [
      { label: "Slack Web API package", url: "https://www.npmjs.com/package/@slack/web-api" },
      { label: "Slack Web API methods", url: "https://docs.slack.dev/reference/methods/" },
      { label: "Slack chat.postMessage", url: "https://docs.slack.dev/reference/methods/chat.postMessage/" },
      { label: "Slack chat.update", url: "https://docs.slack.dev/reference/methods/chat.update/" },
      { label: "Slack conversations.replies", url: "https://docs.slack.dev/reference/methods/conversations.replies/" },
      { label: "Slack files.getUploadURLExternal", url: "https://docs.slack.dev/reference/methods/files.getUploadURLExternal/" },
      { label: "Slack external file upload flow", url: "https://docs.slack.dev/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay/" },
      { label: "Slack Events API", url: "https://docs.slack.dev/apis/events-api/" },
      { label: "Slack request verification", url: "https://docs.slack.dev/authentication/verifying-requests-from-slack/" },
      { label: "Slack Web API rate limits", url: "https://docs.slack.dev/apis/web-api/rate-limits" },
    ],
  },
  privacyNotes: [
    "Slack messages, channel identifiers, user identifiers, event payloads, interaction payloads, files, and workspace metadata can contain internal support context and customer data.",
    "Slack bot tokens and signing secrets stay server-side and are represented in Studio only as credential readiness.",
  ],
  limitations: [
    "Available Slack operations depend on the SDK user's app scopes, workspace policy, channel membership, Enterprise Grid policy, and user targets for ephemeral messages.",
    "Slack rate limits vary by method, workspace, Marketplace approval, commercial distribution, and install date; SDK users own pagination, Retry-After handling, retry, and backoff policy.",
    "Customer visibility, agent-assist routing, approval, retention, redaction, and escalation behavior remain SDK-user configuration.",
  ],
  metadata: {
    channelCoverage: {
      chatMessages: "sdk-owned-post-update",
      ephemeralMessages: "sdk-owned-post",
      threadReplies: "sdk-owned-read",
      externalFileUpload: "sdk-owned-upload",
      authReadiness: "sdk-owned-read",
      eventsInteractivity: "typed-parse-verify",
      socketMode: "not-covered",
      oauth: "not-covered",
      incomingWebhooks: "not-covered",
    },
    providerClient: {
      package: "@slack/web-api",
      versionRange: "^7.17.0",
      importPolicy: "runtime-entrypoint-only",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
} as const satisfies ProviderManifestInput;

export const slackWorkplaceProviderManifest = defineIntegrationProviderPackage(
  slackWorkplaceManifestInput,
);
