import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const whatsappMessagingProviderManifest = defineProviderPackage({
  id: "messaging.whatsapp",
  name: "WhatsApp Business Platform",
  packageName: "@cognidesk/integration-messaging-whatsapp",
  provider: "whatsapp",
  category: "messaging",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is typed for selected WhatsApp Business Platform support workflows: provider REST adapter message sends, template payload construction, media upload/get/download, phone-number readiness, business profile get/update, webhook challenge handling, and X-Hub-Signature-256 validation.",
      "This is not full WhatsApp Business Platform coverage; template CRUD/listing, Flows, commerce, Calling API, groups, phone-number registration and management, WABA account management, analytics, and broader Business Management APIs remain outside this adapter.",
    ],
    evidence: [
      { label: "WhatsApp Cloud API get started", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/get-started" },
      { label: "WhatsApp template fundamentals", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/templates/overview" },
      { label: "WhatsApp media", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/business-phone-numbers/media/" },
      { label: "WhatsApp business profiles", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/business-phone-numbers/business-profiles" },
      { label: "WhatsApp business phone numbers", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/business-phone-numbers/phone-numbers" },
      { label: "WhatsApp webhooks", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/webhooks/overview/" },
      { label: "WhatsApp permissions", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/permissions/" },
    ],
  },
  credentialRequirements: [
    {
      id: "whatsapp-access-token",
      label: "WhatsApp Business access token",
      description: "Server-side Meta access token used by the built-in Graph API adapter or an injected WhatsApp/Meta provider client.",
      scopes: ["whatsapp_business_messaging", "whatsapp_business_management"],
      required: true,
      metadata: { scopeKind: "provider-permission-labels" },
    },
    {
      id: "whatsapp-phone-number-id",
      label: "WhatsApp Business phone number ID",
      description: "Meta phone_number_id used by the built-in Graph API adapter or an injected WhatsApp/Meta provider client.",
      required: true,
    },
    {
      id: "whatsapp-app-secret",
      label: "Meta app secret",
      description: "Server-side app secret used to validate X-Hub-Signature-256 webhook deliveries.",
      required: true,
    },
    {
      id: "whatsapp-webhook-verify-token",
      label: "Webhook verify token",
      description: "SDK-user-owned token checked during Meta webhook endpoint verification.",
      required: false,
    },
    {
      id: "whatsapp-waba-webhook-subscription",
      label: "WhatsApp WABA messages webhook subscription",
      description: "SDK-user-confirmed Meta app subscription to the WhatsApp Business Account messages webhook field.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive WhatsApp webhooks",
      description: "Validates and parses WhatsApp Business Platform webhook payloads after the SDK user's Meta app is subscribed to the WABA messages webhook.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "whatsappWebhook", label: "WhatsApp Webhook" },
        { kind: "whatsappMessage", label: "WhatsApp Message" },
        { kind: "whatsappStatus", label: "WhatsApp Message Status" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send WhatsApp messages",
      description: "Sends WhatsApp messages through the configured Graph API adapter or provider client when SDK-user policy permits outbound contact: free-form service messages inside the customer service window or approved templates outside it.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "whatsappMessage", label: "WhatsApp Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Build WhatsApp message payloads",
      description: "Builds Cloud API message request payloads for SDK-user-configured approval workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "whatsappMessageDraft", label: "WhatsApp Message Draft" }],
      requiresCredential: false,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Use WhatsApp media",
      description: "Uploads media, reads media metadata, and downloads media bytes through the configured Graph API adapter or provider client.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "whatsappMedia", label: "WhatsApp Media" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "attach",
      label: "Attach WhatsApp media",
      description: "References uploaded WhatsApp media IDs in outbound messages selected by SDK configuration.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "whatsappMedia", label: "WhatsApp Media" },
        { kind: "whatsappMessage", label: "WhatsApp Message" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read WhatsApp phone number and profile",
      description: "Reads WhatsApp Business phone-number readiness and business profile resources through the configured Graph API adapter or provider client for Studio-visible configuration and support diagnostics.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "whatsappPhoneNumber", label: "WhatsApp Business Phone Number" },
        { kind: "whatsappBusinessProfile", label: "WhatsApp Business Profile" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update WhatsApp business profile",
      description: "Updates WhatsApp Business profile fields through the configured Graph API adapter or provider client when SDK-user configuration permits profile changes.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "whatsappBusinessProfile", label: "WhatsApp Business Profile" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "whatsapp.webhook-signature",
      label: "Validate WhatsApp webhook signatures",
      description: "Validates Meta X-Hub-Signature-256 webhook signatures with the SDK user's app secret.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "whatsappSignedWebhook", label: "WhatsApp Signed Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "messaging.message.receive",
      providerOperation: "parseWhatsAppWebhook",
      capability: "receive",
      providerObject: "messagingMessage",
      label: "Normalize inbound WhatsApp webhook",
      description: "Validate and parse an inbound WhatsApp Business Platform webhook request.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "messaging.message.send",
      providerOperation: "sendMessage",
      capability: "send",
      providerObject: "messagingMessage",
      label: "Send WhatsApp message",
      description: "Send a WhatsApp message through the configured Graph API adapter or provider client.",
      audiences: ["customer-facing"],
      requiresCredential: true,
      requiresApproval: true,
      externallyVisible: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      alias: "messaging.template.send",
      providerOperation: "sendMessage",
      capability: "send",
      providerObject: "messagingTemplate",
      label: "Send WhatsApp template",
      description: "Send an SDK-user-selected approved WhatsApp message template.",
      audiences: ["customer-facing"],
      requiresCredential: true,
      requiresApproval: true,
      externallyVisible: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      alias: "messaging.draft.create",
      providerOperation: "buildMessagePayload",
      capability: "draft",
      providerObject: "messagingMessage",
      label: "Build WhatsApp message payload",
      description: "Build a WhatsApp Cloud API message payload for review or later send.",
      audiences: ["customer-facing", "mixed"],
      exposesSensitiveData: true,
    },
    {
      alias: "messaging.media.send",
      providerOperation: "uploadMedia",
      capability: "attach",
      providerObject: "mediaAttachment",
      label: "Upload WhatsApp media",
      description: "Upload media for use in WhatsApp messages through the configured Graph API adapter or provider client.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      requiresApproval: true,
      externallyVisible: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      alias: "whatsapp.phoneNumber.read",
      providerOperation: "getPhoneNumber",
      capability: "read-provider-object",
      providerObject: "whatsappPhoneNumber",
      label: "Read WhatsApp phone number",
      description: "Read WhatsApp Business phone-number readiness metadata through the configured Graph API adapter or provider client.",
      audiences: ["internal-support", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "whatsapp.businessProfile.read",
      providerOperation: "getBusinessProfile",
      capability: "read-provider-object",
      providerObject: "whatsappBusinessProfile",
      label: "Read WhatsApp business profile",
      description: "Read WhatsApp Business profile fields for support diagnostics through the configured Graph API adapter or provider client.",
      audiences: ["internal-support", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "whatsapp.businessProfile.update",
      providerOperation: "updateBusinessProfile",
      capability: "update-provider-object",
      providerObject: "whatsappBusinessProfile",
      label: "Update WhatsApp business profile",
      description: "Update WhatsApp Business profile fields through the configured Graph API adapter or provider client when SDK-user policy permits.",
      audiences: ["internal-support"],
      requiresCredential: true,
      requiresApproval: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
      extension: true,
    },
    {
      alias: "whatsapp.webhook-signature",
      providerOperation: "validateWhatsAppWebhookSignature",
      capability: "whatsapp.webhook-signature",
      providerObject: "whatsappSignedWebhook",
      label: "Validate WhatsApp webhook signature",
      description: "Validate Meta X-Hub-Signature-256 for WhatsApp webhook delivery.",
      audiences: ["internal-support"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "WhatsApp messages, contact identifiers, phone numbers, profile names, media metadata, message statuses, and webhook payloads can contain customer data.",
    "Meta access tokens, app secrets, and webhook verify tokens stay server-side and are represented in Studio only as credential readiness.",
  ],
  limitations: [
    "Available operations depend on the SDK user's Meta app, WhatsApp Business Account, phone number registration, WABA messages webhook subscription, access token scopes, business verification, templates, quality limits, and messaging windows.",
    "Free-form WhatsApp service messages are for the customer service window; SDK users must select approved templates for outbound contact outside that window.",
    "Opt-in, outbound-contact policy, template selection, human escalation, media retention, redaction, and deletion behavior are SDK-user configuration.",
    "This package provides a built-in Graph API REST adapter when accessToken and phoneNumberId are configured; hosts may still inject an approved WhatsApp/Meta provider client and own automation, promotional messaging, consent, retry, and rate-limit policies.",
  ],
  metadata: {
    providerClient: {
      package: "built-in-or-host-provided",
      interface: "WhatsAppMessagingProviderClient",
      importPolicy: "provider-client-override-supported",
      defaultClientPolicy: "provider-rest-adapter-when-configured",
      sdkDecision: {
        checkedAt: "2026-06-25",
        result: "no-maintained-official-sdk-rest-adapter-selected",
        notes: [
          "facebook-nodejs-business-sdk is Marketing API oriented rather than a WhatsApp Cloud API messaging client.",
          "Meta's WhatsApp Node.js SDK documentation now marks the project archived, so this package uses a built-in Graph API REST adapter instead of adding that dependency.",
          "Hosts may wrap an approved maintained SDK behind WhatsAppMessagingProviderClient when desired.",
        ],
      },
    },
    channelCoverage: {
      cloudApiMessages: "provider-rest-adapter-send",
      templatePayloads: "typed-build-only",
      media: "provider-rest-adapter-upload-get-download",
      phoneNumberReadiness: "provider-rest-adapter-read",
      businessProfile: "provider-rest-adapter-read-update",
      webhooks: "typed-challenge-verify-parse",
      templateCrud: "provider-supported-not-typed",
      flowsCommerceCallingGroups: "provider-supported-not-typed",
    },
    apiCoverage: {
      checkedAt: "2026-06-18",
      operationCatalog: "docs/provider-coverage/whatsapp-business-messaging-openapi-v23-selected-api-2026-06-18.operations.json",
      sourceSpec: "https://raw.githubusercontent.com/facebook/openapi/main/business-messaging-api_v23.0.yaml",
      generatedFromOfficialSpec: true,
      sourcePathCount: 78,
      sourceOperationCount: 113,
      selectedOperationCount: 7,
      implementedOperationCount: 7,
      fullProviderApi: false,
      fullMetaGraphCoverage: false,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
