import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { STRIPE_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  STRIPE_FULL_API_OPERATION_COUNT,
  STRIPE_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";
import { defaultStripeApiVersion } from "./constants.js";

export const stripeEcommerceProviderManifest = defineProviderPackage({
  id: "ecommerce.stripe",
  name: "Stripe",
  packageName: "@cognidesk/integrations",
  provider: "stripe",
  category: "ecommerce",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes a generated operation catalog for every operation in the official Stripe OpenAPI spec for this API version, exposed through requestOperation(operationId, ...).",
      "The package also keeps typed convenience helpers for selected commerce support primitives: account, customer, PaymentIntent, Checkout Session, subscription, invoice, refund, dispute, webhook endpoint, Connect account header, and webhook-signature helpers.",
      "The SDK user owns restricted-key scope selection, checkout and refund policy, dispute evidence policy, Connect account routing, webhook subscriptions, consent, and retention decisions.",
    ],
    evidence: [
      { label: "Stripe API reference", url: "https://docs.stripe.com/api" },
      { label: "Stripe PaymentIntents API", url: "https://docs.stripe.com/api/payment_intents" },
      { label: "Stripe Checkout Sessions API", url: "https://docs.stripe.com/api/checkout/sessions" },
      { label: "Stripe Subscriptions update API", url: "https://docs.stripe.com/api/subscriptions/update" },
      { label: "Stripe Webhook Endpoints API", url: "https://docs.stripe.com/api/webhook_endpoints" },
      { label: "Stripe webhook signature verification", url: "https://docs.stripe.com/webhooks/signature" },
    ],
  },
  credentialRequirements: [
    {
      id: "stripe-secret-key",
      label: "Stripe secret key",
      description: "Server-side Stripe secret key or restricted key selected and owned by the SDK user.",
      scopes: [
        "customers:read",
        "payment_intents:read",
        "checkout_sessions:read",
        "subscriptions:read",
        "invoices:read",
        "refunds:read",
        "disputes:read",
        "subscriptions:write",
        "webhook_endpoints:read",
        "webhook_endpoints:write",
      ],
      required: true,
      metadata: {
        scopeKind: "provider-permission-labels",
        privilegeGuidance: "These strings represent Stripe restricted-key permission families for Studio review, not OAuth scopes.",
      },
    },
    {
      id: "stripe-publishable-key",
      label: "Stripe publishable key",
      description: "Optional publishable key surfaced only when the SDK user exposes Stripe-hosted or embedded payment UI.",
      required: false,
    },
    {
      id: "stripe-webhook-signing-secret",
      label: "Stripe webhook signing secret",
      description: "Endpoint signing secret used to validate Stripe-Signature headers against the raw request body.",
      required: true,
    },
    {
      id: "stripe-connect-mode",
      label: "Stripe Connect mode",
      description: "SDK-user-selected account context for platform, connected-account, or organization event handling.",
      required: false,
    },
    {
      id: "stripe-restricted-key-scopes",
      label: "Stripe restricted key scopes",
      description: "SDK-user-declared restricted-key permissions used for Studio readiness and policy review.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Stripe events",
      description: "Validates and parses Stripe webhook events for SDK-user-owned commerce and payment support workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "stripeEvent", label: "Stripe Event" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Stripe commerce records",
      description: "Reads Stripe customers, payment intents, Checkout Sessions, subscriptions, invoices, refunds, disputes, and account details.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "stripeCustomer", label: "Stripe Customer" },
        { kind: "stripePaymentIntent", label: "Stripe PaymentIntent" },
        { kind: "stripeCheckoutSession", label: "Stripe Checkout Session" },
        { kind: "stripeSubscription", label: "Stripe Subscription" },
        { kind: "stripeInvoice", label: "Stripe Invoice" },
        { kind: "stripeRefund", label: "Stripe Refund" },
        { kind: "stripeDispute", label: "Stripe Dispute" },
        { kind: "stripeWebhookEndpoint", label: "Stripe Webhook Endpoint" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Stripe commerce records",
      description: "Lists and searches support-relevant Stripe objects with SDK-user-supplied filters.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "stripeCustomer", label: "Stripe Customer" },
        { kind: "stripePaymentIntent", label: "Stripe PaymentIntent" },
        { kind: "stripeCheckoutSession", label: "Stripe Checkout Session" },
        { kind: "stripeInvoice", label: "Stripe Invoice" },
        { kind: "stripeDispute", label: "Stripe Dispute" },
        { kind: "stripeWebhookEndpoint", label: "Stripe Webhook Endpoint" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Stripe payment support actions",
      description: "Creates Checkout Sessions, PaymentIntents, and refunds only when SDK-user policy permits externally visible commerce mutations.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "stripeCheckoutSession", label: "Stripe Checkout Session" },
        { kind: "stripePaymentIntent", label: "Stripe PaymentIntent" },
        { kind: "stripeRefund", label: "Stripe Refund" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Stripe support records",
      description: "Updates subscriptions, disputes, and webhook endpoints, and closes disputes or cancels subscriptions when SDK-user policy permits regulated payment support actions.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "stripeSubscription", label: "Stripe Subscription" },
        { kind: "stripeDispute", label: "Stripe Dispute" },
        { kind: "stripeWebhookEndpoint", label: "Stripe Webhook Endpoint" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "ecommerce.payments",
      label: "Stripe payment API foundation",
      description: "Exposes Stripe support-workflow primitives without deciding checkout, refund, dispute, retention, or consent policy.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "stripeApiResult", label: "Stripe API Result" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Stripe records can include customer contact data, billing/shipping addresses, payment state, subscription terms, invoice history, refund reasons, dispute evidence, and account metadata.",
    "Secret keys, restricted keys, Connect account routing, and webhook signing secrets stay server-side; Studio receives only readiness state and policy-visible metadata.",
  ],
  limitations: [
    "The SDK user chooses Stripe account mode, restricted-key permissions, event destinations, webhook subscriptions, checkout UI, refund policy, dispute evidence policy, consent, and retention.",
    "This package provides API foundations and raw-body signature verification; it does not decide when to charge, refund, cancel, submit evidence, or expose payment data to an operator.",
    "Available records and mutations depend on the SDK user's Stripe account, restricted key, Connect configuration, API version, product access, and provider-side permissions.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    defaultApiVersion: defaultStripeApiVersion,
    docs: "https://docs.stripe.com/api",
    fullProviderApiVerification: {
      provider: "stripe",
      apiVersion: STRIPE_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-17",
      coverageArtifact: `docs/provider-coverage/stripe-${STRIPE_FULL_API_SPEC_VERSION}.operations.json`,
      operationCatalogArtifact: `docs/provider-coverage/stripe-${STRIPE_FULL_API_SPEC_VERSION}.operations.json`,
      functionCatalogArtifact: `docs/provider-coverage/stripe-${STRIPE_FULL_API_SPEC_VERSION}.functions.json`,
      documentedOperationCount: STRIPE_FULL_API_OPERATION_COUNT,
      implementedOperationCount: STRIPE_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: STRIPE_FULL_API_GENERATED_FUNCTION_COUNT,
    },
    channelCoverage: {
      fullRestApiOperations: "typed-operation-catalog",
      account: "typed-read",
      customers: "typed-read-list-search",
      paymentIntents: "typed-create-read-list",
      checkoutSessions: "typed-create-read-list",
      checkoutSessionLineItems: "typed-list",
      subscriptions: "typed-read-list-update-cancel",
      invoices: "typed-read-list",
      refunds: "typed-create-read-list",
      disputes: "typed-read-list-update-close",
      webhookEndpoints: "typed-create-read-list-update-delete",
      webhooks: "typed-validate-parse",
      connectAccountHeader: "typed-request-context",
      taxTerminalTreasuryIssuingIdentityFilesReporting: "provider-supported-not-typed",
    },
  },
});
