import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";

export const cognideskCobrowsingProviderManifest = defineProviderPackage({
  id: "cobrowsing.cognidesk",
  name: "Cognidesk Cobrowsing",
  packageName: "@cognidesk/integrations",
  provider: "cognidesk",
  category: "cobrowsing",
  trustLevel: "official",
  directions: ["bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "local-protocol",
    notes: [
      "Coverage is limited to Cognidesk-owned local cobrowsing protocol primitives: SDK-user session store lifecycle, signed session tokens, event normalization, and HMAC signed-event parsing.",
      "The package does not implement an external cobrowsing provider API, browser remoting, DOM capture/replay, cursor or screen-control transport, hosted relay infrastructure, storage persistence, or third-party cobrowsing administration.",
      "The SDK user owns allowed origins, consent capture, recording/redaction policy, data storage, transport, and relay/runtime implementation decisions.",
    ],
    evidence: [
      { label: "Cognidesk cobrowsing local protocol module", url: "https://github.com/cognilabz/cognidesk/tree/main/packages/integrations/src/cobrowsing/cognidesk" },
      { label: "CONTEXT.md Built-In Adapter definition" },
    ],
  },
  credentialRequirements: [
    {
      id: "cobrowsing-session-store",
      label: "Cobrowsing session store",
      description: "SDK-user-owned durable or ephemeral store used to create, join, read, and end cobrowsing sessions.",
      required: true,
    },
    {
      id: "cobrowsing-session-token-signing",
      label: "Signed session token configuration",
      description: "SDK-user-owned HMAC signing material and token lifetime policy for session access tokens.",
      required: true,
    },
    {
      id: "cobrowsing-consent-policy",
      label: "Cobrowsing consent policy",
      description: "SDK-user-owned policy describing when customer consent is required, captured, and retained.",
      required: true,
    },
    {
      id: "cobrowsing-recording-redaction-policy",
      label: "Recording and redaction policy",
      description: "SDK-user-owned policy for recording eligibility, sensitive element masking, field redaction, and retention.",
      required: true,
    },
    {
      id: "cobrowsing-allowed-origins",
      label: "Allowed browser origins",
      description: "SDK-user-owned allowlist of origins where cobrowsing sessions and signed session tokens are valid.",
      required: true,
    },
    {
      id: "cobrowsing-webhook-shared-secret",
      label: "Webhook shared secret",
      description: "SDK-user-owned HMAC shared secret used to verify cobrowsing webhook or session-event requests.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "create-provider-object",
      label: "Create cobrowsing sessions",
      description: "Creates SDK-user-owned cobrowsing session records without implementing browser remoting.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "cobrowsingSession", label: "Cobrowsing Session" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read cobrowsing sessions",
      description: "Reads SDK-user-owned cobrowsing session records and readiness state.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "cobrowsingSession", label: "Cobrowsing Session" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Join or end cobrowsing sessions",
      description: "Updates SDK-user-owned cobrowsing session lifecycle for join and end operations.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "cobrowsingSession", label: "Cobrowsing Session" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "receive",
      label: "Receive cobrowsing session events",
      description: "Validates, parses, and normalizes signed cobrowsing webhook or session-event requests.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "cobrowsingSessionEvent", label: "Cobrowsing Session Event" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "cobrowsing.validate-session-token",
      label: "Validate cobrowsing session tokens",
      description: "Validates SDK-user-signed HMAC session tokens with expiration, audience, session, and origin checks.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "cobrowsingSessionToken", label: "Cobrowsing Session Token" }],
      requiresCredential: true,
      extension: true,
      exposesSensitiveData: true,
    },
    {
      capability: "cobrowsing.verify-signed-event",
      label: "Verify signed cobrowsing events",
      description: "Verifies HMAC signed webhook/session-event payloads with timestamp replay protection.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "cobrowsingSignedEvent", label: "Cobrowsing Signed Event" }],
      requiresCredential: true,
      extension: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Cobrowsing session IDs, customer identifiers, agent identifiers, page origins, consent records, recording metadata, redaction selectors, and event payloads can contain customer or support data.",
    "Session token signing material and webhook shared secrets stay server-side and are represented in Studio only as readiness metadata.",
    "Consent, recording, redaction, allowed-origin, retention, and transport eligibility decisions remain SDK-user-owned configuration.",
  ],
  limitations: [
    "This package provides the SDK adapter contract, readiness helpers, session lifecycle primitives, token validation, event normalization, and signed-event parsing only.",
    "It does not implement browser remoting, DOM capture, cursor transport, screen control, storage persistence, or a hosted cobrowsing relay.",
    "Studio can surface this package's configuration state later, but SDK user configuration remains the authority for behavior.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://github.com/cognilabz/cognidesk/tree/main/packages/integrations/src/cobrowsing/cognidesk",
    channelCoverage: {
      sessions: "typed-create-read-update",
      sessionTokens: "typed-create-validate",
      signedEvents: "typed-verify-parse",
      browserRemotingDomCaptureCursorScreenControlHostedRelay: "not-covered",
    },
  },
});
