import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const dynamics365TicketingProviderManifest = defineProviderPackage({
  id: "ticketing.dynamics365",
  name: "Microsoft Dynamics 365 Customer Service",
  packageName: "@cognidesk/ticketing-dynamics365",
  provider: "dynamics365",
  category: "ticketing",
  trustLevel: "official",
  directions: ["bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is limited to Dataverse incident CRUD/search, selected metadata/readiness helpers, incident notes via annotations, queue AddToQueue, and queue/activity reads used by Cognidesk support workflows.",
      "Annotation note creation supports bounded inline annotation document fields (`filename`, `documentbody`, `mimetype`) on the Dataverse annotation record; this is not a complete file/attachment lifecycle.",
      "This is not full Microsoft Dataverse, Dynamics 365 Customer Service, activity, annotation attachment, relationship metadata, broader queue routing, or custom action API coverage.",
    ],
    evidence: [
      { label: "Microsoft Dataverse Web API overview", url: "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/overview" },
      { label: "Dynamics 365 Customer Service incident table reference", url: "https://learn.microsoft.com/en-us/dynamics365/customer-service/develop/reference/entities/incident" },
      { label: "Dataverse EntityDefinitions metadata queries", url: "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/query-metadata-web-api" },
      { label: "Dataverse WhoAmI Function", url: "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/whoami?view=dataverse-latest" },
      { label: "Dataverse Note/Annotation table reference", url: "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/annotation" },
      { label: "Dataverse ActivityPointer table reference", url: "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/activitypointer" },
      { label: "Dataverse queue EntityType reference", url: "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/queue" },
      { label: "Dataverse AddToQueue Action", url: "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/addtoqueue?view=dataverse-latest" },
      { label: "Dynamics 365 Omnichannel JavaScript API", url: "https://learn.microsoft.com/en-us/dynamics365/customer-service/develop/omnichannel-api-reference" },
      { label: "Dynamics 365 custom messaging channel table", url: "https://learn.microsoft.com/en-us/dynamics365/customer-service/develop/reference/entities/msdyn_occustommessagingchannel" },
      { label: "Dynamics 365 getConversations Omnichannel API", url: "https://learn.microsoft.com/en-us/dynamics365/customer-service/develop/reference/methods/getconversations" },
    ],
  },
  credentialRequirements: [
    { id: "dynamics365-instance", label: "Dynamics 365 Dataverse environment URL", required: true },
    {
      id: "dynamics365-api-access",
      label: "Dynamics 365 OAuth access",
      scopes: ["user_impersonation"],
      required: true,
      metadata: {
        scopeKind: "provider-oauth-scopes",
        privilegeGuidance: "Delegated clients request <environment-url>/user_impersonation; confidential clients commonly request <environment-url>/.default. Dataverse security roles still govern incident, annotation, queue, activity, and AddToQueue access.",
      },
    },
  ],
  capabilities: [
    {
      capability: "create-provider-object",
      label: "Create Dynamics cases",
      description: "Creates Dataverse incident records for SDK-user-configured customer-service handoff.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "dynamics365Incident", label: "Dynamics 365 Case", schemaName: "incident" }, { kind: "dynamics365Annotation", label: "Dynamics 365 Annotation", schemaName: "annotation" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Dynamics cases",
      description: "Reads Dataverse incident records and readiness metadata.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "dynamics365Incident", label: "Dynamics 365 Case", schemaName: "incident" }, { kind: "dynamics365Annotation", label: "Dynamics 365 Annotation", schemaName: "annotation" }, { kind: "dynamics365Queue", label: "Dynamics 365 Queue", schemaName: "queue" }, { kind: "dynamics365Activity", label: "Dynamics 365 Activity", schemaName: "activitypointer" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Dynamics cases",
      description: "Updates Dataverse incident records such as status, title, description, owner, or custom fields.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "dynamics365Incident", label: "Dynamics 365 Case", schemaName: "incident" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Dynamics cases",
      description: "Queries Dataverse incident records with SDK-user-supplied OData options.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "dynamics365Incident", label: "Dynamics 365 Case", schemaName: "incident" }, { kind: "dynamics365Annotation", label: "Dynamics 365 Annotation", schemaName: "annotation" }, { kind: "dynamics365Queue", label: "Dynamics 365 Queue", schemaName: "queue" }, { kind: "dynamics365Activity", label: "Dynamics 365 Activity", schemaName: "activitypointer" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Attach handoff to Dynamics",
      description: "Uses Dataverse incident, annotation, and selected queue operations in SDK-user-configured record handoff workflows; this does not imply native Omnichannel conversation transfer or live-work-item mutation.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "dynamics365Incident", label: "Dynamics 365 Case", schemaName: "incident" }, { kind: "dynamics365Annotation", label: "Dynamics 365 Annotation", schemaName: "annotation" }, { kind: "dynamics365Queue", label: "Dynamics 365 Queue", schemaName: "queue" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "Dynamics cases can contain customer identity, support summaries, entitlements, queue and owner metadata, and internal notes.",
    "Dynamics OAuth credentials stay server-side and Studio receives only readiness.",
  ],
  limitations: [
    "Dataverse table customizations, required fields, queues, owners, security roles, and routing rules are SDK-user configuration.",
    "Unified Routing live-work-item mutation is provider-sensitive and must not be inferred from typed AddToQueue support.",
  ],
  metadata: {
    implementation: {
      strategy: "direct-http-support-slice",
      runtimePackage: "@cognidesk/ticketing-dynamics365",
      manifestImport: "no-sdk-client-initialization",
    },
    checkedProviderApiCoverage: {
      verifiedAt: "2026-06-18",
      sourceKind: "checked-endpoint-family-inventory",
      coverageArtifact: "docs/provider-coverage/dynamics365-checked-dataverse-customer-service-2026-06-18.inventory.json",
      familyCount: 4,
      implementedFamilyCount: 3,
      gapFamilyCount: 1,
      implementedOperationCount: 11,
      fullCoverageExportRequirement: "Full environment-specific Dataverse/Dynamics coverage requires the SDK user's $metadata/CSDL, EntityDefinitions, solution customizations, enabled Dynamics 365 Customer Service products, security roles, and custom action/function export.",
    },
    channelCoverage: {
      incidents: "typed-crud-search",
      annotationsCaseNotes: "typed-create-list",
      annotationInlineDocumentFields: "typed-selected",
      queueRouting: "typed-selected",
      queues: "typed-list",
      activities: "typed-list",
      metadataReadiness: "typed-selected",
      messagingApis: "provider-supported-not-typed",
      customMessagingChannels: "provider-supported-not-typed",
      omnichannelLiveChatWidget: "provider-supported-client-sdk-not-typed",
      linkToConversation: "provider-supported-client-sdk-not-typed",
      conversationsLiveWorkItems: "provider-supported-not-typed",
      transcriptAnnotations: "provider-supported-not-typed",
      ccaasConversationActions: "provider-supported-not-typed",
      unifiedRoutingLiveWorkItemMutation: "provider-supported-not-typed",
      annotationAttachmentLifecycle: "provider-supported-not-typed",
      relationshipMetadata: "not-covered",
      customActions: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
