import type { ProviderOperationDeclarationInput } from "@cognidesk/core";

export const dynamics365TicketingProviderOperations: ProviderOperationDeclarationInput[] = [
  {
    alias: "ticket.create",
    providerOperation: "create(incidents)",
    capability: "create-provider-object",
    label: "Create Dynamics 365 case",
    providerObject: "ticket",
    sideEffect: true,
    changesWorkflow: true,
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.read",
    providerOperation: "retrieve(incidents)",
    capability: "read-provider-object",
    label: "Read Dynamics 365 case",
    providerObject: "ticket",
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.update",
    providerOperation: "update(incidents)",
    capability: "update-provider-object",
    label: "Update Dynamics 365 case",
    providerObject: "ticket",
    sideEffect: true,
    changesWorkflow: true,
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.search",
    providerOperation: "retrieveMultiple(incidents)",
    capability: "search-provider-object",
    label: "Search Dynamics 365 cases",
    providerObject: "ticket",
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.internalNote.create",
    providerOperation: "create(annotations)",
    capability: "draft",
    label: "Create Dynamics 365 internal case note",
    providerObject: "internalNote",
    sideEffect: true,
    externallyVisible: false,
    exposesSensitiveData: true,
  },
  {
    alias: "dynamics365.entity-definition.read",
    providerOperation: "retrieveEntity(EntityDefinitions)",
    capability: "read-provider-object",
    label: "Read Dynamics 365 entity definition",
    providerObject: "dynamics365EntityDefinition",
    exposesSensitiveData: true,
    extension: true,
  },
  {
    alias: "dynamics365.case-note.create",
    providerOperation: "create(annotations)",
    capability: "handoff",
    label: "Create Dynamics 365 case annotation",
    providerObject: "dynamics365Annotation",
    sideEffect: true,
    exposesSensitiveData: true,
    extension: true,
  },
  {
    alias: "dynamics365.case-notes.list",
    providerOperation: "retrieveMultiple(annotations)",
    capability: "search-provider-object",
    label: "List Dynamics 365 case annotations",
    providerObject: "dynamics365Annotation",
    exposesSensitiveData: true,
    extension: true,
  },
  {
    alias: "dynamics365.queue.addToQueue",
    providerOperation: "callAction(Microsoft.Dynamics.CRM.AddToQueue)",
    capability: "handoff",
    label: "Add Dynamics 365 case to queue",
    providerObject: "dynamics365Queue",
    sideEffect: true,
    changesWorkflow: true,
    exposesSensitiveData: true,
    extension: true,
  },
  {
    alias: "dynamics365.queues.list",
    providerOperation: "retrieveMultiple(queues)",
    capability: "search-provider-object",
    label: "List Dynamics 365 queues",
    providerObject: "dynamics365Queue",
    exposesSensitiveData: true,
    extension: true,
  },
  {
    alias: "dynamics365.activities.list",
    providerOperation: "retrieveMultiple(activitypointers)",
    capability: "search-provider-object",
    label: "List Dynamics 365 activities",
    providerObject: "dynamics365Activity",
    exposesSensitiveData: true,
    extension: true,
  },
  {
    alias: "dynamics365.whoami",
    providerOperation: "callFunction(WhoAmI)",
    capability: "read-provider-object",
    label: "Run Dynamics 365 WhoAmI readiness check",
    providerObject: "dynamics365Readiness",
    exposesSensitiveData: true,
    extension: true,
  },
] satisfies ProviderOperationDeclarationInput[];

export type Dynamics365TicketingOperationAlias = string;
