import {
  allAudiences,
  categoryProfilesCoreIntegrationNote,
  customerAudiences,
  defineIntegrationCategoryProfile,
  internalAudiences,
  operation,
} from "./shared.js";

export const emailCategoryProfile = defineIntegrationCategoryProfile({
  id: "email",
  category: "email",
  label: "Email",
  description: "Provider-neutral mailbox and thread handling with receive, reply, draft, send, archive, label, attachment, and delivery-status workflows.",
  providerObjects: [
    { kind: "emailThread", label: "Email Thread" },
    { kind: "emailMessage", label: "Email Message" },
    { kind: "emailDraft", label: "Email Draft" },
    { kind: "mailbox", label: "Mailbox" },
    { kind: "mailFolder", label: "Mail Folder" },
    { kind: "mailLabel", label: "Mail Label" },
    { kind: "attachment", label: "Attachment" },
    { kind: "deliveryStatus", label: "Delivery Status" },
  ],
  operations: [
    operation({
      alias: "email.receive",
      label: "Receive email",
      description: "Normalize a newly received email or mailbox webhook into a channel event.",
      level: "required",
      capability: "receive",
      providerObject: "emailMessage",
      audiences: customerAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "email.thread.read",
      label: "Read email thread",
      description: "Fetch a full email thread with messages, recipients, headers, and attachment references.",
      level: "required",
      capability: "read-provider-object",
      providerObject: "emailThread",
      audiences: customerAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "email.reply.send",
      label: "Send email reply",
      description: "Send a reply in an existing email thread.",
      level: "required",
      capability: "send",
      providerObject: "emailMessage",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "email.send",
      label: "Send email",
      description: "Send a new outbound email message.",
      level: "recommended",
      capability: "send",
      providerObject: "emailMessage",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "email.draft.create",
      label: "Create email draft",
      description: "Create a provider draft for review before sending.",
      level: "recommended",
      capability: "draft",
      providerObject: "emailDraft",
      audiences: customerAudiences,
      sideEffect: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "email.draft.update",
      label: "Update email draft",
      description: "Update draft recipients, subject, body, attachments, or provider metadata.",
      level: "recommended",
      capability: "draft",
      providerObject: "emailDraft",
      audiences: customerAudiences,
      sideEffect: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "email.draft.send",
      label: "Send email draft",
      description: "Send an existing provider draft.",
      level: "recommended",
      capability: "send",
      providerObject: "emailDraft",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "email.thread.search",
      label: "Search email threads",
      description: "Search mailbox threads using provider-native query capabilities.",
      level: "recommended",
      capability: "search-provider-object",
      providerObject: "emailThread",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "email.archive",
      label: "Archive email thread",
      description: "Archive a thread or move it out of the active inbox.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "emailThread",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "email.label.apply",
      label: "Apply email label",
      description: "Apply a folder, category, or label to an email message or thread.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "mailLabel",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "email.forward",
      label: "Forward email",
      description: "Forward a message or thread to another recipient.",
      level: "optional",
      capability: "send",
      providerObject: "emailMessage",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "email.draft.delete",
      label: "Delete email draft",
      description: "Discard a provider draft.",
      level: "optional",
      capability: "delete-provider-object",
      providerObject: "emailDraft",
      audiences: internalAudiences,
      sideEffect: true,
    }),
    operation({
      alias: "email.attachments.read",
      label: "Read email attachments",
      description: "Fetch attachment metadata or content references for a message.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "attachment",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "email.deliveryStatus.read",
      label: "Read delivery status",
      description: "Read bounce, complaint, delivery, or provider tracking status for a sent message.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "deliveryStatus",
      audiences: internalAudiences,
    }),
    operation({
      alias: "email.markRead",
      label: "Mark email read",
      description: "Mark a message or thread as read.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "emailMessage",
      audiences: internalAudiences,
      sideEffect: true,
    }),
    operation({
      alias: "email.markUnread",
      label: "Mark email unread",
      description: "Mark a message or thread as unread for follow-up.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "emailMessage",
      audiences: internalAudiences,
      sideEffect: true,
    }),
    operation({
      alias: "email.move",
      label: "Move email",
      description: "Move a message or thread to another folder or mailbox container.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "mailFolder",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "mailbox.watch",
      label: "Watch mailbox changes",
      description: "Create or maintain a provider change notification subscription for mailbox events.",
      level: "optional",
      capability: "receive",
      providerObject: "mailbox",
      audiences: internalAudiences,
      sideEffect: true,
    }),
  ],
  events: [
    { kind: "email.received", label: "Email received", description: "A new inbound email was received.", direction: "inbound", capability: "receive", providerObject: "emailMessage", operationAlias: "email.receive" },
    { kind: "email.thread.updated", label: "Thread updated", description: "Thread messages, labels, folders, or metadata changed.", direction: "inbound", capability: "receive", providerObject: "emailThread", operationAlias: "email.thread.read" },
    { kind: "email.draft.updated", label: "Draft updated", description: "A provider draft changed.", direction: "internal", capability: "draft", providerObject: "emailDraft", operationAlias: "email.draft.update" },
    { kind: "email.delivery.updated", label: "Delivery updated", description: "Delivery, bounce, complaint, or tracking status changed.", direction: "inbound", capability: "receive", providerObject: "deliveryStatus", operationAlias: "email.deliveryStatus.read" },
  ],
  outputs: [
    { intent: "message.reply", label: "Email reply", description: "Send a reply in the active email thread.", capability: "send", operationAlias: "email.reply.send", providerObject: "emailMessage", externallyVisible: true, requiresApproval: true },
    { intent: "message.send", label: "New email", description: "Send a new outbound email.", capability: "send", operationAlias: "email.send", providerObject: "emailMessage", externallyVisible: true, requiresApproval: true },
    { intent: "message.draft", label: "Email draft", description: "Create or update a provider draft.", capability: "draft", operationAlias: "email.draft.create", providerObject: "emailDraft" },
    { intent: "provider.object.update", label: "Mailbox update", description: "Archive, label, move, or mark a thread.", capability: "update-provider-object", operationAlias: "email.label.apply", providerObject: "emailThread", changesWorkflow: true },
  ],
  dataSources: [
    { id: "email.thread", label: "Email thread", description: "Fetch full thread context.", capability: "read-provider-object", operationAlias: "email.thread.read", providerObjects: ["emailThread", "emailMessage"], exposesSensitiveData: true },
    { id: "email.search", label: "Mailbox search", description: "Search messages and threads.", capability: "search-provider-object", operationAlias: "email.thread.search", providerObjects: ["emailThread", "emailMessage"], exposesSensitiveData: true },
    { id: "email.attachments", label: "Email attachments", description: "Fetch attachment references for context gathering.", capability: "read-provider-object", operationAlias: "email.attachments.read", providerObjects: ["attachment"], exposesSensitiveData: true },
    { id: "email.deliveryStatus", label: "Delivery status", description: "Fetch delivery and bounce context.", capability: "read-provider-object", operationAlias: "email.deliveryStatus.read", providerObjects: ["deliveryStatus"] },
  ],
  notes: [categoryProfilesCoreIntegrationNote],
});
