import {
  allAudiences,
  categoryProfilesCoreIntegrationNote,
  defineIntegrationCategoryProfile,
  internalAudiences,
  operation,
} from "./shared.js";

export const handoffCategoryProfile = defineIntegrationCategoryProfile({
  id: "handoff",
  category: "handoff",
  label: "Handoff",
  description: "Provider-neutral handoff lifecycle for destinations, requests, review, acceptance, completion, cancellation, assignment, notes, and audit.",
  providerObjects: [
    { kind: "handoffTarget", label: "Handoff Target" },
    { kind: "handoffRequest", label: "Handoff Request" },
    { kind: "handoffReview", label: "Handoff Review" },
    { kind: "handoffAssignment", label: "Handoff Assignment" },
    { kind: "handoffNote", label: "Handoff Note" },
    { kind: "handoffAuditEntry", label: "Handoff Audit Entry" },
    { kind: "conversationLink", label: "Conversation Link" },
  ],
  operations: [
    operation({
      alias: "handoff.target.list",
      label: "List handoff targets",
      description: "List available handoff targets such as queues, agents, teams, external providers, or workflows.",
      level: "required",
      capability: "handoff",
      providerObject: "handoffTarget",
      audiences: internalAudiences,
    }),
    operation({
      alias: "handoff.request.create",
      label: "Create handoff request",
      description: "Create a handoff request without hardcoding the business reason.",
      level: "required",
      capability: "handoff",
      providerObject: "handoffRequest",
      audiences: allAudiences,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "handoff.status.read",
      label: "Read handoff status",
      description: "Read handoff request state, ownership, destination, and workflow metadata.",
      level: "required",
      capability: "read-provider-object",
      providerObject: "handoffRequest",
      audiences: internalAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "handoff.review.request",
      label: "Request handoff review",
      description: "Ask a human or provider workflow to review whether/how a handoff should proceed.",
      level: "recommended",
      capability: "handoff",
      providerObject: "handoffReview",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "handoff.accept",
      label: "Accept handoff",
      description: "Accept ownership of a handoff request.",
      level: "recommended",
      capability: "handoff",
      providerObject: "handoffAssignment",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "handoff.complete",
      label: "Complete handoff",
      description: "Mark a handoff as completed and record completion metadata.",
      level: "recommended",
      capability: "handoff",
      providerObject: "handoffRequest",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "handoff.cancel",
      label: "Cancel handoff",
      description: "Cancel a pending or active handoff request.",
      level: "recommended",
      capability: "handoff",
      providerObject: "handoffRequest",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "handoff.assign",
      label: "Assign handoff",
      description: "Assign a handoff request to a specific agent, queue, team, or external target.",
      level: "recommended",
      capability: "handoff",
      providerObject: "handoffAssignment",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "handoff.note.create",
      label: "Create handoff note",
      description: "Attach internal context, summary, or operator instructions to a handoff.",
      level: "recommended",
      capability: "draft",
      providerObject: "handoffNote",
      audiences: internalAudiences,
      sideEffect: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "handoff.linkConversation",
      label: "Link conversation",
      description: "Link the handoff request to a Cognidesk conversation, provider thread, ticket, or contact.",
      level: "recommended",
      capability: "link-provider-object",
      providerObject: "conversationLink",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "handoff.escalate",
      label: "Escalate handoff",
      description: "Escalate a handoff to a higher-priority target, supervisor, queue, or external workflow.",
      level: "optional",
      capability: "handoff",
      providerObject: "handoffRequest",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "handoff.resumeAutomation",
      label: "Resume automation",
      description: "Return control from a handoff to SDK automation when policy allows it.",
      level: "optional",
      capability: "handoff",
      providerObject: "handoffRequest",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "handoff.destination.resolve",
      label: "Resolve handoff destination",
      description: "Resolve the final handoff destination from a policy-selected target, provider route, queue, or agent.",
      level: "optional",
      capability: "handoff",
      providerObject: "handoffTarget",
      audiences: internalAudiences,
    }),
    operation({
      alias: "handoff.auditTrail.read",
      label: "Read handoff audit trail",
      description: "Read handoff lifecycle events for audit, support, or compliance review.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "handoffAuditEntry",
      audiences: internalAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "handoff.priority.update",
      label: "Update handoff priority",
      description: "Update priority, severity, SLA state, or routing weight.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "handoffRequest",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "handoff.reopen",
      label: "Reopen handoff",
      description: "Reopen a completed or canceled handoff request for more work.",
      level: "optional",
      capability: "handoff",
      providerObject: "handoffRequest",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
  ],
  events: [
    { kind: "handoff.requested", label: "Handoff requested", description: "A handoff request was created.", direction: "internal", capability: "handoff", providerObject: "handoffRequest", operationAlias: "handoff.request.create" },
    { kind: "handoff.review.requested", label: "Handoff review requested", description: "Review of a possible handoff was requested.", direction: "internal", capability: "handoff", providerObject: "handoffReview", operationAlias: "handoff.review.request" },
    { kind: "handoff.accepted", label: "Handoff accepted", description: "A handoff was accepted.", direction: "internal", capability: "handoff", providerObject: "handoffAssignment", operationAlias: "handoff.accept" },
    { kind: "handoff.completed", label: "Handoff completed", description: "A handoff was completed.", direction: "internal", capability: "handoff", providerObject: "handoffRequest", operationAlias: "handoff.complete" },
    { kind: "handoff.canceled", label: "Handoff canceled", description: "A handoff was canceled.", direction: "internal", capability: "handoff", providerObject: "handoffRequest", operationAlias: "handoff.cancel" },
  ],
  outputs: [
    { intent: "channel.handoff.requested", label: "Request handoff", description: "Create a channel handoff request.", capability: "handoff", operationAlias: "handoff.request.create", providerObject: "handoffRequest", changesWorkflow: true },
    { intent: "handoff.review", label: "Request review", description: "Request a handoff review.", capability: "handoff", operationAlias: "handoff.review.request", providerObject: "handoffReview", changesWorkflow: true },
    { intent: "handoff.complete", label: "Complete handoff", description: "Complete a handoff lifecycle.", capability: "handoff", operationAlias: "handoff.complete", providerObject: "handoffRequest", requiresApproval: true, changesWorkflow: true },
    { intent: "handoff.note", label: "Handoff note", description: "Create an internal handoff note.", capability: "draft", operationAlias: "handoff.note.create", providerObject: "handoffNote" },
  ],
  dataSources: [
    { id: "handoff.targets", label: "Handoff targets", description: "Fetch available handoff targets.", capability: "handoff", operationAlias: "handoff.target.list", providerObjects: ["handoffTarget"] },
    { id: "handoff.status", label: "Handoff status", description: "Fetch handoff state and ownership.", capability: "read-provider-object", operationAlias: "handoff.status.read", providerObjects: ["handoffRequest"], exposesSensitiveData: true },
    { id: "handoff.auditTrail", label: "Handoff audit trail", description: "Fetch lifecycle/audit events.", capability: "read-provider-object", operationAlias: "handoff.auditTrail.read", providerObjects: ["handoffAuditEntry"], exposesSensitiveData: true },
  ],
  notes: [categoryProfilesCoreIntegrationNote],
});
