import {
  allAudiences,
  categoryProfilesCoreIntegrationNote,
  customerAudiences,
  defineIntegrationCategoryProfile,
  internalAudiences,
  operation,
} from "./shared.js";

export const messagingCategoryProfile = defineIntegrationCategoryProfile({
  id: "messaging",
  category: "messaging",
  label: "Messaging",
  description: "Provider-neutral asynchronous messaging channels with threads, messages, templates, media, reactions, delivery status, opt-in, and messaging-window handling.",
  providerObjects: [
    { kind: "messagingThread", label: "Messaging Thread" },
    { kind: "messagingMessage", label: "Messaging Message" },
    { kind: "messagingTemplate", label: "Messaging Template" },
    { kind: "messagingContact", label: "Messaging Contact" },
    { kind: "mediaAttachment", label: "Media Attachment" },
    { kind: "deliveryStatus", label: "Delivery Status" },
    { kind: "optInState", label: "Opt-in State" },
  ],
  operations: [
    operation({
      alias: "messaging.message.receive",
      label: "Receive message",
      description: "Normalize an inbound messaging webhook/message into a channel event.",
      level: "required",
      capability: "receive",
      providerObject: "messagingMessage",
      audiences: customerAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.message.send",
      label: "Send message",
      description: "Send a customer-visible messaging response.",
      level: "required",
      capability: "send",
      providerObject: "messagingMessage",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.thread.read",
      label: "Read messaging thread",
      description: "Fetch a thread, conversation, chat, or conversation history.",
      level: "required",
      capability: "read-provider-object",
      providerObject: "messagingThread",
      audiences: customerAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.message.reply",
      label: "Reply to message",
      description: "Send a reply that is associated with an existing thread/message.",
      level: "recommended",
      capability: "send",
      providerObject: "messagingMessage",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.draft.create",
      label: "Create messaging draft",
      description: "Create a proposed messaging response for human review.",
      level: "recommended",
      capability: "draft",
      providerObject: "messagingMessage",
      audiences: customerAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.thread.search",
      label: "Search messaging threads",
      description: "Search messaging threads by participant, provider ID, text, tag, or date range.",
      level: "recommended",
      capability: "search-provider-object",
      providerObject: "messagingThread",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.thread.create",
      label: "Create messaging thread",
      description: "Start a new provider conversation where the channel supports outbound initiation.",
      level: "recommended",
      capability: "create-provider-object",
      providerObject: "messagingThread",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.template.list",
      label: "List message templates",
      description: "List provider message templates or approved canned messages.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "messagingTemplate",
      audiences: internalAudiences,
    }),
    operation({
      alias: "messaging.template.send",
      label: "Send message template",
      description: "Send an approved provider template message.",
      level: "recommended",
      capability: "send",
      providerObject: "messagingTemplate",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.media.send",
      label: "Send media message",
      description: "Send images, documents, audio, video, or provider media references.",
      level: "recommended",
      capability: "attach",
      providerObject: "mediaAttachment",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.deliveryStatus.read",
      label: "Read delivery status",
      description: "Read sent, delivered, read, failed, or provider delivery status.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "deliveryStatus",
      audiences: internalAudiences,
    }),
    operation({
      alias: "messaging.typingIndicator.send",
      label: "Send typing indicator",
      description: "Send provider typing or composing indicators where supported.",
      level: "optional",
      capability: "send",
      providerObject: "messagingThread",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
    }),
    operation({
      alias: "messaging.reaction.send",
      label: "Send reaction",
      description: "Send or update a message reaction.",
      level: "optional",
      capability: "send",
      providerObject: "messagingMessage",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
    }),
    operation({
      alias: "messaging.message.retract",
      label: "Retract message",
      description: "Delete, unsend, hide, or retract a message where provider policy allows it.",
      level: "optional",
      capability: "delete-provider-object",
      providerObject: "messagingMessage",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "messaging.template.submitForApproval",
      label: "Submit template for approval",
      description: "Create or submit a message template to a provider approval workflow.",
      level: "optional",
      capability: "create-provider-object",
      providerObject: "messagingTemplate",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "messaging.optIn.status.read",
      label: "Read opt-in status",
      description: "Read consent, subscription, messaging-window, or opt-in status.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "optInState",
      audiences: internalAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.optIn.status.update",
      label: "Update opt-in status",
      description: "Update provider opt-in or subscription state when legally authorized.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "optInState",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "messaging.thread.assign",
      label: "Assign messaging thread",
      description: "Assign a messaging thread to an agent, queue, team, or provider inbox.",
      level: "optional",
      capability: "handoff",
      providerObject: "messagingThread",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
  ],
  events: [
    { kind: "messaging.message.received", label: "Message received", description: "An inbound message was received.", direction: "inbound", capability: "receive", providerObject: "messagingMessage", operationAlias: "messaging.message.receive" },
    { kind: "messaging.message.sent", label: "Message sent", description: "An outbound message was sent.", direction: "outbound", capability: "send", providerObject: "messagingMessage", operationAlias: "messaging.message.send" },
    { kind: "messaging.delivery.updated", label: "Delivery updated", description: "Delivery, read, or failure status changed.", direction: "inbound", capability: "receive", providerObject: "deliveryStatus", operationAlias: "messaging.deliveryStatus.read" },
    { kind: "messaging.template.updated", label: "Template updated", description: "Template approval or metadata changed.", direction: "inbound", capability: "receive", providerObject: "messagingTemplate", operationAlias: "messaging.template.list" },
    { kind: "messaging.optIn.updated", label: "Opt-in updated", description: "Consent or opt-in status changed.", direction: "inbound", capability: "receive", providerObject: "optInState", operationAlias: "messaging.optIn.status.read" },
  ],
  outputs: [
    { intent: "message.reply", label: "Messaging reply", description: "Send a thread reply.", capability: "send", operationAlias: "messaging.message.reply", providerObject: "messagingMessage", externallyVisible: true, requiresApproval: true },
    { intent: "message.template", label: "Template message", description: "Send an approved provider template.", capability: "send", operationAlias: "messaging.template.send", providerObject: "messagingTemplate", externallyVisible: true, requiresApproval: true },
    { intent: "message.media", label: "Media message", description: "Send media through the provider.", capability: "attach", operationAlias: "messaging.media.send", providerObject: "mediaAttachment", externallyVisible: true, requiresApproval: true },
    { intent: "message.draft", label: "Messaging draft", description: "Create a draft messaging response.", capability: "draft", operationAlias: "messaging.draft.create", providerObject: "messagingMessage" },
  ],
  dataSources: [
    { id: "messaging.thread", label: "Messaging thread", description: "Fetch conversation context.", capability: "read-provider-object", operationAlias: "messaging.thread.read", providerObjects: ["messagingThread", "messagingMessage"], exposesSensitiveData: true },
    { id: "messaging.search", label: "Messaging search", description: "Search conversations and messages.", capability: "search-provider-object", operationAlias: "messaging.thread.search", providerObjects: ["messagingThread", "messagingMessage"], exposesSensitiveData: true },
    { id: "messaging.templates", label: "Messaging templates", description: "Fetch provider templates for safe outbound messaging.", capability: "read-provider-object", operationAlias: "messaging.template.list", providerObjects: ["messagingTemplate"] },
    { id: "messaging.optIn", label: "Opt-in state", description: "Fetch consent and messaging-window state.", capability: "read-provider-object", operationAlias: "messaging.optIn.status.read", providerObjects: ["optInState"], exposesSensitiveData: true },
  ],
  notes: [categoryProfilesCoreIntegrationNote],
});
