import {
  allAudiences,
  categoryProfilesCoreIntegrationNote,
  customerAudiences,
  defineIntegrationCategoryProfile,
  internalAudiences,
  operation,
} from "./shared.js";

export const smsCategoryProfile = defineIntegrationCategoryProfile({
  id: "sms",
  category: "sms",
  label: "SMS",
  description: "Provider-neutral SMS/MMS handling with inbound messages, outbound messages, replies, scheduled sends, media messages, delivery status, sender resources, and provider message lookup.",
  providerObjects: [
    { kind: "smsMessage", label: "SMS Message" },
    { kind: "smsThread", label: "SMS Thread" },
    { kind: "smsSender", label: "SMS Sender" },
    { kind: "smsTemplate", label: "SMS Template" },
    { kind: "mediaAttachment", label: "Media Attachment" },
    { kind: "deliveryStatus", label: "Delivery Status" },
  ],
  operations: [
    operation({
      alias: "sms.message.receive",
      label: "Receive SMS",
      description: "Normalize an inbound SMS/MMS webhook into a channel event.",
      level: "required",
      capability: "receive",
      providerObject: "smsMessage",
      audiences: customerAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "sms.message.send",
      label: "Send SMS",
      description: "Send a customer-visible SMS/MMS message.",
      level: "required",
      capability: "send",
      providerObject: "smsMessage",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "sms.message.reply",
      label: "Reply by SMS",
      description: "Send a customer-visible SMS/MMS reply associated with an existing customer contact or thread.",
      level: "recommended",
      capability: "send",
      providerObject: "smsMessage",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "sms.message.schedule",
      label: "Schedule SMS",
      description: "Schedule an outbound SMS/MMS message for provider-side delivery.",
      level: "recommended",
      capability: "schedule",
      providerObject: "smsMessage",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "sms.message.read",
      label: "Read SMS",
      description: "Fetch a provider SMS/MMS message by provider ID.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "smsMessage",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "sms.message.search",
      label: "Search SMS",
      description: "Search SMS/MMS messages by participant, provider ID, date, status, or provider-native filters.",
      level: "recommended",
      capability: "search-provider-object",
      providerObject: "smsMessage",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "sms.deliveryStatus.read",
      label: "Read SMS delivery status",
      description: "Read provider delivery status for a sent SMS/MMS message.",
      level: "recommended",
      capability: "read-provider-object",
      providerObject: "deliveryStatus",
      audiences: internalAudiences,
    }),
    operation({
      alias: "sms.media.send",
      label: "Send MMS media",
      description: "Send media URLs or provider media references through an SMS/MMS-capable sender.",
      level: "optional",
      capability: "send",
      providerObject: "mediaAttachment",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "sms.template.send",
      label: "Send SMS template",
      description: "Send an approved provider content template or templated SMS/MMS message.",
      level: "optional",
      capability: "send",
      providerObject: "smsTemplate",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "sms.message.cancel",
      label: "Cancel SMS",
      description: "Cancel a queued or scheduled SMS/MMS message when the provider supports it.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "smsMessage",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "sms.sender.read",
      label: "Read SMS sender",
      description: "Fetch sender number, messaging service, shortcode, or sender-capability metadata.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "smsSender",
      audiences: internalAudiences,
    }),
    operation({
      alias: "sms.sender.search",
      label: "Search SMS senders",
      description: "List or search provider senders that can originate SMS/MMS messages.",
      level: "optional",
      capability: "search-provider-object",
      providerObject: "smsSender",
      audiences: internalAudiences,
    }),
  ],
  events: [
    { kind: "sms.message.received", label: "SMS received", description: "An inbound SMS/MMS message was received.", direction: "inbound", capability: "receive", providerObject: "smsMessage", operationAlias: "sms.message.receive" },
    { kind: "sms.message.sent", label: "SMS sent", description: "An outbound SMS/MMS message was accepted for sending.", direction: "outbound", capability: "send", providerObject: "smsMessage", operationAlias: "sms.message.send" },
    { kind: "sms.delivery.updated", label: "SMS delivery updated", description: "Delivery, failure, or cancellation status changed.", direction: "inbound", capability: "receive", providerObject: "deliveryStatus", operationAlias: "sms.deliveryStatus.read" },
  ],
  outputs: [
    { intent: "message.send", label: "SMS", description: "Send a new SMS/MMS message.", capability: "send", operationAlias: "sms.message.send", providerObject: "smsMessage", externallyVisible: true, requiresApproval: true },
    { intent: "message.reply", label: "SMS reply", description: "Send an SMS/MMS reply.", capability: "send", operationAlias: "sms.message.reply", providerObject: "smsMessage", externallyVisible: true, requiresApproval: true },
    { intent: "message.schedule", label: "Scheduled SMS", description: "Schedule an SMS/MMS message.", capability: "schedule", operationAlias: "sms.message.schedule", providerObject: "smsMessage", externallyVisible: true, requiresApproval: true, changesWorkflow: true },
    { intent: "message.media", label: "MMS media", description: "Send media through an SMS/MMS-capable provider.", capability: "send", operationAlias: "sms.media.send", providerObject: "mediaAttachment", externallyVisible: true, requiresApproval: true },
  ],
  dataSources: [
    { id: "sms.message", label: "SMS message", description: "Fetch a provider SMS/MMS message.", capability: "read-provider-object", operationAlias: "sms.message.read", providerObjects: ["smsMessage"], exposesSensitiveData: true },
    { id: "sms.search", label: "SMS search", description: "Search SMS/MMS messages.", capability: "search-provider-object", operationAlias: "sms.message.search", providerObjects: ["smsMessage"], exposesSensitiveData: true },
    { id: "sms.deliveryStatus", label: "SMS delivery status", description: "Fetch sent, delivered, failed, or cancelled status.", capability: "read-provider-object", operationAlias: "sms.deliveryStatus.read", providerObjects: ["deliveryStatus"] },
    { id: "sms.sender", label: "SMS sender", description: "Fetch SMS/MMS sender metadata.", capability: "read-provider-object", operationAlias: "sms.sender.read", providerObjects: ["smsSender"] },
  ],
  notes: [categoryProfilesCoreIntegrationNote],
});
