import {
  allAudiences,
  categoryProfilesCoreIntegrationNote,
  customerAudiences,
  defineIntegrationCategoryProfile,
  internalAudiences,
  operation,
} from "./shared.js";

export const ticketingCategoryProfile = defineIntegrationCategoryProfile({
  id: "ticketing",
  category: "ticketing",
  label: "Ticketing",
  description: "Provider-neutral support ticket systems with public replies, internal notes, workflow fields, assignment, and customer history.",
  providerObjects: [
    { kind: "ticket", label: "Ticket" },
    { kind: "ticketComment", label: "Ticket Comment" },
    { kind: "internalNote", label: "Internal Note" },
    { kind: "customer", label: "Customer" },
    { kind: "organization", label: "Organization" },
    { kind: "agent", label: "Agent" },
    { kind: "team", label: "Team or Group" },
    { kind: "attachment", label: "Attachment" },
    { kind: "tag", label: "Tag" },
    { kind: "macro", label: "Macro" },
    { kind: "slaPolicy", label: "SLA Policy" },
    { kind: "conversationLink", label: "Conversation Link" },
  ],
  operations: [
    operation({
      alias: "ticket.read",
      label: "Read ticket",
      description: "Fetch a ticket, including requester, status, priority, custom fields, and provider metadata where available.",
      level: "required",
      capability: "read-provider-object",
      providerObject: "ticket",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ticket.comment.create",
      label: "Create public ticket comment",
      description: "Add a customer-visible public reply/comment to an existing ticket.",
      level: "required",
      capability: "send",
      providerObject: "ticketComment",
      audiences: customerAudiences,
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ticket.create",
      label: "Create ticket",
      description: "Create a new support ticket from a channel event, handoff, form, or operator workflow.",
      level: "recommended",
      capability: "create-provider-object",
      providerObject: "ticket",
      audiences: allAudiences,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ticket.update",
      label: "Update ticket fields",
      description: "Patch title, description, custom fields, requester context, or provider-owned ticket metadata.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "ticket",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ticket.search",
      label: "Search tickets",
      description: "Search tickets using provider-native filters or query syntax.",
      level: "recommended",
      capability: "search-provider-object",
      providerObject: "ticket",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ticket.listByCustomer",
      label: "List customer tickets",
      description: "List recent or matching tickets for a requester, account, or external customer identity.",
      level: "recommended",
      capability: "search-provider-object",
      providerObject: "ticket",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ticket.internalNote.create",
      label: "Create internal note",
      description: "Add a private support note that is visible to operators but not to the customer.",
      level: "recommended",
      capability: "draft",
      providerObject: "internalNote",
      audiences: internalAudiences,
      sideEffect: true,
      externallyVisible: false,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ticket.status.update",
      label: "Update ticket status",
      description: "Move a ticket through provider status values such as open, pending, solved, closed, or custom workflow states.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "ticket",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "ticket.priority.update",
      label: "Update ticket priority",
      description: "Set or change urgency, priority, severity, or comparable provider workflow fields.",
      level: "recommended",
      capability: "update-provider-object",
      providerObject: "ticket",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "ticket.assign",
      label: "Assign ticket",
      description: "Assign a ticket to an agent, group, team, queue, or provider routing target.",
      level: "recommended",
      capability: "handoff",
      providerObject: "ticket",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "ticket.linkConversation",
      label: "Link conversation to ticket",
      description: "Attach or cross-reference a Cognidesk conversation, channel thread, or handoff record to a provider ticket.",
      level: "recommended",
      capability: "link-provider-object",
      providerObject: "conversationLink",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "ticket.close",
      label: "Close ticket",
      description: "Close, solve, or otherwise complete a ticket according to provider workflow semantics.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "ticket",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "ticket.reopen",
      label: "Reopen ticket",
      description: "Reopen or unsolve a ticket for follow-up work.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "ticket",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "ticket.tags.update",
      label: "Update ticket tags",
      description: "Add, remove, or replace tags and labels on a ticket.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "tag",
      audiences: internalAudiences,
      sideEffect: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "ticket.attachments.add",
      label: "Add ticket attachment",
      description: "Attach files, images, uploads, or provider file references to a ticket or comment.",
      level: "optional",
      capability: "attach",
      providerObject: "attachment",
      audiences: allAudiences,
      sideEffect: true,
      externallyVisible: true,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ticket.attachments.list",
      label: "List ticket attachments",
      description: "List file references already attached to a ticket or ticket comment.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "attachment",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "ticket.merge",
      label: "Merge tickets",
      description: "Merge duplicate tickets or link duplicate provider cases according to provider semantics.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "ticket",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "ticket.macro.list",
      label: "List ticket macros",
      description: "List reusable ticket macros, snippets, or provider response templates.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "macro",
      audiences: internalAudiences,
    }),
    operation({
      alias: "ticket.macro.apply",
      label: "Apply ticket macro",
      description: "Apply a provider macro to a ticket draft or workflow update.",
      level: "optional",
      capability: "update-provider-object",
      providerObject: "macro",
      audiences: internalAudiences,
      sideEffect: true,
      requiresApproval: true,
      changesWorkflow: true,
    }),
    operation({
      alias: "customer.read",
      label: "Read customer",
      description: "Fetch customer identity, contact details, account metadata, and provider profile fields.",
      level: "optional",
      capability: "read-provider-object",
      providerObject: "customer",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
    operation({
      alias: "customer.search",
      label: "Search customers",
      description: "Search requester, customer, contact, or account records.",
      level: "optional",
      capability: "search-provider-object",
      providerObject: "customer",
      audiences: allAudiences,
      exposesSensitiveData: true,
    }),
  ],
  events: [
    { kind: "ticket.created", label: "Ticket created", description: "A ticket was created in the provider.", direction: "inbound", capability: "receive", providerObject: "ticket", operationAlias: "ticket.read" },
    { kind: "ticket.updated", label: "Ticket updated", description: "Ticket fields or workflow state changed.", direction: "inbound", capability: "receive", providerObject: "ticket", operationAlias: "ticket.read" },
    { kind: "ticket.comment.created", label: "Ticket comment created", description: "A public ticket comment was added.", direction: "inbound", capability: "receive", providerObject: "ticketComment", operationAlias: "ticket.comment.create" },
    { kind: "ticket.internalNote.created", label: "Internal note created", description: "A private/internal ticket note was added.", direction: "inbound", capability: "receive", providerObject: "internalNote", operationAlias: "ticket.internalNote.create" },
    { kind: "ticket.status.changed", label: "Ticket status changed", description: "Ticket status moved through provider workflow.", direction: "inbound", capability: "receive", providerObject: "ticket", operationAlias: "ticket.status.update" },
    { kind: "ticket.assigned", label: "Ticket assigned", description: "Ticket ownership or routing target changed.", direction: "inbound", capability: "receive", providerObject: "ticket", operationAlias: "ticket.assign" },
  ],
  outputs: [
    { intent: "message.reply", label: "Public reply", description: "Send a customer-visible ticket reply.", capability: "send", operationAlias: "ticket.comment.create", providerObject: "ticketComment", externallyVisible: true, requiresApproval: true },
    { intent: "message.draft", label: "Draft reply", description: "Create a proposed public ticket reply for review.", capability: "draft", providerObject: "ticketComment" },
    { intent: "internal.note", label: "Internal note", description: "Create an internal support note.", capability: "draft", operationAlias: "ticket.internalNote.create", providerObject: "internalNote" },
    { intent: "provider.object.update", label: "Ticket update", description: "Update a ticket workflow field.", capability: "update-provider-object", operationAlias: "ticket.update", providerObject: "ticket", changesWorkflow: true },
    { intent: "handoff.review", label: "Handoff review", description: "Ask a human operator to review a ticketing handoff.", capability: "handoff", operationAlias: "ticket.assign", providerObject: "ticket", changesWorkflow: true },
  ],
  dataSources: [
    { id: "ticket.read", label: "Ticket", description: "Fetch a ticket for context gathering.", capability: "read-provider-object", operationAlias: "ticket.read", providerObjects: ["ticket"], exposesSensitiveData: true },
    { id: "ticket.history", label: "Ticket history", description: "Fetch comments, internal notes, and workflow changes for a ticket.", capability: "read-provider-object", operationAlias: "ticket.read", providerObjects: ["ticket", "ticketComment", "internalNote"], exposesSensitiveData: true },
    { id: "customer.tickets", label: "Customer tickets", description: "Fetch recent tickets for the same customer or account.", capability: "search-provider-object", operationAlias: "ticket.listByCustomer", providerObjects: ["ticket", "customer"], exposesSensitiveData: true },
    { id: "ticket.search", label: "Ticket search", description: "Search provider tickets for similar issues or references.", capability: "search-provider-object", operationAlias: "ticket.search", providerObjects: ["ticket"], exposesSensitiveData: true },
  ],
  notes: [categoryProfilesCoreIntegrationNote],
});
