// Generated from the RingCentral Engage Digital OpenAPI spec (https://raw.githubusercontent.com/ringcentral/engage-digital-api-docs/master/specs/engage-digital_openapi3.yaml).
// Do not edit by hand; run scripts/generate-ringcentral-digital-api.mjs after checking upstream docs.

export const RINGCENTRAL_DIGITAL_API_GENERATED_AT = "2026-06-18";
export const RINGCENTRAL_DIGITAL_API_SPEC_SOURCE = "https://raw.githubusercontent.com/ringcentral/engage-digital-api-docs/master/specs/engage-digital_openapi3.yaml";
export const RINGCENTRAL_DIGITAL_API_DOCS_SOURCE = "https://developers.ringcentral.com/engage-digital-api";
export const RINGCENTRAL_DIGITAL_API_REPO_SOURCE = "https://github.com/ringcentral/engage-digital-api-docs";
export const RINGCENTRAL_DIGITAL_API_SPEC_VERSION = "1.0.1";
export const RINGCENTRAL_DIGITAL_API_OPENAPI_VERSION = "3.0.0";
export const RINGCENTRAL_DIGITAL_API_PATH_COUNT = 90;
export const RINGCENTRAL_DIGITAL_API_OPERATION_COUNT = 149;

export interface RingCentralDigitalApiOperation {
  uid: string;
  operationId: string;
  functionName: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
  path: string;
  summary: string;
  tags: readonly string[];
}

export const RINGCENTRAL_DIGITAL_API_OPERATIONS = JSON.parse("[{\"uid\":\"PUT /topologies/{topologyId}/activate\",\"operationId\":\"activateTopology\",\"functionName\":\"ActivateTopology\",\"method\":\"PUT\",\"path\":\"/topologies/{topologyId}/activate\",\"summary\":\"Activating a topology\",\"tags\":[\"Topologies\"]},{\"uid\":\"PUT /topologies/{topologyId}\",\"operationId\":\"updateTopology\",\"functionName\":\"UpdateTopology\",\"method\":\"PUT\",\"path\":\"/topologies/{topologyId}\",\"summary\":\"Updating a topology\",\"tags\":[\"Topologies\"]},{\"uid\":\"DELETE /topologies/{topologyId}\",\"operationId\":\"deleteTopology\",\"functionName\":\"DeleteTopology\",\"method\":\"DELETE\",\"path\":\"/topologies/{topologyId}\",\"summary\":\"Deleting a topology\",\"tags\":[\"Topologies\"]},{\"uid\":\"GET /topologies/{topologyId}\",\"operationId\":\"getTopology\",\"functionName\":\"GetTopology\",\"method\":\"GET\",\"path\":\"/topologies/{topologyId}\",\"summary\":\"Getting a topology from its id\",\"tags\":[\"Topologies\"]},{\"uid\":\"POST /topologies\",\"operationId\":\"createTopology\",\"functionName\":\"CreateTopology\",\"method\":\"POST\",\"path\":\"/topologies\",\"summary\":\"Creating a topology\",\"tags\":[\"Topologies\"]},{\"uid\":\"GET /topologies\",\"operationId\":\"getAllTopologies\",\"functionName\":\"GetAllTopologies\",\"method\":\"GET\",\"path\":\"/topologies\",\"summary\":\"Getting all topologies\",\"tags\":[\"Topologies\"]},{\"uid\":\"GET /attachments\",\"operationId\":\"getAllAttachments\",\"functionName\":\"GetAllAttachments\",\"method\":\"GET\",\"path\":\"/attachments\",\"summary\":\"Getting all attachments\",\"tags\":[\"Attachments\"]},{\"uid\":\"POST /attachments\",\"operationId\":\"createAttachment\",\"functionName\":\"CreateAttachment\",\"method\":\"POST\",\"path\":\"/attachments\",\"summary\":\"Creating an attachment\",\"tags\":[\"Attachments\"]},{\"uid\":\"GET /attachments/{attachmentId}\",\"operationId\":\"getAttachment\",\"functionName\":\"GetAttachment\",\"method\":\"GET\",\"path\":\"/attachments/{attachmentId}\",\"summary\":\"Getting an attachment from its id\",\"tags\":[\"Attachments\"]},{\"uid\":\"POST /bots/engage\",\"operationId\":\"botEngage\",\"functionName\":\"BotEngage\",\"method\":\"POST\",\"path\":\"/bots/engage\",\"summary\":\"Bot engage\",\"tags\":[\"Bots\"]},{\"uid\":\"POST /bots/complete\",\"operationId\":\"botComplete\",\"functionName\":\"BotComplete\",\"method\":\"POST\",\"path\":\"/bots/complete\",\"summary\":\"Bot complete\",\"tags\":[\"Bots\"]},{\"uid\":\"POST /bots/handover\",\"operationId\":\"handoverFromBotToAgent\",\"functionName\":\"HandoverFromBotToAgent\",\"method\":\"POST\",\"path\":\"/bots/handover\",\"summary\":\"Bot handover\",\"tags\":[\"Bots\"]},{\"uid\":\"GET /categories\",\"operationId\":\"getAllCategories\",\"functionName\":\"GetAllCategories\",\"method\":\"GET\",\"path\":\"/categories\",\"summary\":\"Getting all categories\",\"tags\":[\"Categories\"]},{\"uid\":\"POST /categories\",\"operationId\":\"createCategory\",\"functionName\":\"CreateCategory\",\"method\":\"POST\",\"path\":\"/categories\",\"summary\":\"Creating a category\",\"tags\":[\"Categories\"]},{\"uid\":\"DELETE /categories/{categoryId}\",\"operationId\":\"deleteCategory\",\"functionName\":\"DeleteCategory\",\"method\":\"DELETE\",\"path\":\"/categories/{categoryId}\",\"summary\":\"Deleting a category\",\"tags\":[\"Categories\"]},{\"uid\":\"GET /categories/{categoryId}\",\"operationId\":\"getCategory\",\"functionName\":\"GetCategory\",\"method\":\"GET\",\"path\":\"/categories/{categoryId}\",\"summary\":\"Getting a category from its id\",\"tags\":[\"Categories\"]},{\"uid\":\"PUT /categories/{categoryId}\",\"operationId\":\"updateCategory\",\"functionName\":\"UpdateCategory\",\"method\":\"PUT\",\"path\":\"/categories/{categoryId}\",\"summary\":\"Updating a category\",\"tags\":[\"Categories\"]},{\"uid\":\"GET /channels\",\"operationId\":\"getAllChannels\",\"functionName\":\"GetAllChannels\",\"method\":\"GET\",\"path\":\"/channels\",\"summary\":\"Getting all channels\",\"tags\":[\"Channels\"]},{\"uid\":\"GET /channels/{channelId}\",\"operationId\":\"getChannel\",\"functionName\":\"GetChannel\",\"method\":\"GET\",\"path\":\"/channels/{channelId}\",\"summary\":\"Getting a channel from its id\",\"tags\":[\"Channels\"]},{\"uid\":\"PUT /channels/{channelId}\",\"operationId\":\"updateChannel\",\"functionName\":\"UpdateChannel\",\"method\":\"PUT\",\"path\":\"/channels/{channelId}\",\"summary\":\"Updating a channel\",\"tags\":[\"Channels\"]},{\"uid\":\"GET /communities\",\"operationId\":\"getAllCommunities\",\"functionName\":\"GetAllCommunities\",\"method\":\"GET\",\"path\":\"/communities\",\"summary\":\"Getting all communities\",\"tags\":[\"Communities\"]},{\"uid\":\"GET /communities/{communityId}\",\"operationId\":\"getCommunity\",\"functionName\":\"GetCommunity\",\"method\":\"GET\",\"path\":\"/communities/{communityId}\",\"summary\":\"Getting a community from its id\",\"tags\":[\"Communities\"]},{\"uid\":\"GET /content_sources\",\"operationId\":\"getAllSources\",\"functionName\":\"GetAllSources\",\"method\":\"GET\",\"path\":\"/content_sources\",\"summary\":\"Getting all sources\",\"tags\":[\"Sources\"]},{\"uid\":\"GET /content_sources/{sourceId}\",\"operationId\":\"getSource\",\"functionName\":\"GetSource\",\"method\":\"GET\",\"path\":\"/content_sources/{sourceId}\",\"summary\":\"Getting a source from its id\",\"tags\":[\"Sources\"]},{\"uid\":\"PUT /content_sources/{sourceId}\",\"operationId\":\"updateSource\",\"functionName\":\"UpdateSource\",\"method\":\"PUT\",\"path\":\"/content_sources/{sourceId}\",\"summary\":\"Updating a source\",\"tags\":[\"Sources\"]},{\"uid\":\"PUT /content_sources/{sourceId}/email_credentials\",\"operationId\":\"updateSourceEmailCredentials\",\"functionName\":\"UpdateSourceEmailCredentials\",\"method\":\"PUT\",\"path\":\"/content_sources/{sourceId}/email_credentials\",\"summary\":\"Updating source credentials\",\"tags\":[\"Sources\"]},{\"uid\":\"GET /content_threads\",\"operationId\":\"getAllThreads\",\"functionName\":\"GetAllThreads\",\"method\":\"GET\",\"path\":\"/content_threads\",\"summary\":\"Getting all threads\",\"tags\":[\"Threads\"]},{\"uid\":\"GET /content_threads/{threadId}\",\"operationId\":\"getThread\",\"functionName\":\"GetThread\",\"method\":\"GET\",\"path\":\"/content_threads/{threadId}\",\"summary\":\"Getting a thread from its id\",\"tags\":[\"Threads\"]},{\"uid\":\"PUT /content_threads/{threadId}/close\",\"operationId\":\"closeThread\",\"functionName\":\"CloseThread\",\"method\":\"PUT\",\"path\":\"/content_threads/{threadId}/close\",\"summary\":\"Close a thread\",\"tags\":[\"Threads\"]},{\"uid\":\"PUT /content_threads/{threadId}/ignore\",\"operationId\":\"archiveThread\",\"functionName\":\"ArchiveThread\",\"method\":\"PUT\",\"path\":\"/content_threads/{threadId}/ignore\",\"summary\":\"Archiving a thread\",\"tags\":[\"Threads\"]},{\"uid\":\"GET /content_threads/{threadId}/open\",\"operationId\":\"openThread\",\"functionName\":\"OpenThread\",\"method\":\"GET\",\"path\":\"/content_threads/{threadId}/open\",\"summary\":\"Open a thread\",\"tags\":[\"Threads\"]},{\"uid\":\"PUT /content_threads/{threadId}/update_categories\",\"operationId\":\"categorizeThread\",\"functionName\":\"CategorizeThread\",\"method\":\"PUT\",\"path\":\"/content_threads/{threadId}/update_categories\",\"summary\":\"Categorizing a thread\",\"tags\":[\"Threads\"]},{\"uid\":\"PUT /content_threads/{threadId}/disable_text_input\",\"operationId\":\"disableThreadTextInput\",\"functionName\":\"DisableThreadTextInput\",\"method\":\"PUT\",\"path\":\"/content_threads/{threadId}/disable_text_input\",\"summary\":\"Disabling text input on a thread\",\"tags\":[\"Threads\"]},{\"uid\":\"PUT /content_threads/{threadId}/enable_text_input\",\"operationId\":\"enableThreadTextInput\",\"functionName\":\"EnableThreadTextInput\",\"method\":\"PUT\",\"path\":\"/content_threads/{threadId}/enable_text_input\",\"summary\":\"Enabling text input on a thread\",\"tags\":[\"Threads\"]},{\"uid\":\"GET /contents\",\"operationId\":\"getAllContents\",\"functionName\":\"GetAllContents\",\"method\":\"GET\",\"path\":\"/contents\",\"summary\":\"Contents\",\"tags\":[\"Contents\"]},{\"uid\":\"POST /contents\",\"operationId\":\"createContent\",\"functionName\":\"CreateContent\",\"method\":\"POST\",\"path\":\"/contents\",\"summary\":\"Creating content\",\"tags\":[\"Contents\"]},{\"uid\":\"GET /contents/{contentId}\",\"operationId\":\"getContent\",\"functionName\":\"GetContent\",\"method\":\"GET\",\"path\":\"/contents/{contentId}\",\"summary\":\"Getting a content from its id\",\"tags\":[\"Contents\"]},{\"uid\":\"PUT /contents/{contentId}/ignore\",\"operationId\":\"ignoreContent\",\"functionName\":\"IgnoreContent\",\"method\":\"PUT\",\"path\":\"/contents/{contentId}/ignore\",\"summary\":\"Ignoring a content\",\"tags\":[\"Contents\"]},{\"uid\":\"PUT /contents/{contentId}/update_categories\",\"operationId\":\"categorizeContent\",\"functionName\":\"CategorizeContent\",\"method\":\"PUT\",\"path\":\"/contents/{contentId}/update_categories\",\"summary\":\"Categorizing a content\",\"tags\":[\"Contents\"]},{\"uid\":\"PUT /contents/{contentId}/update_custom_score\",\"operationId\":\"updateCustomScore\",\"functionName\":\"UpdateCustomScore\",\"method\":\"PUT\",\"path\":\"/contents/{contentId}/update_custom_score\",\"summary\":\"Updating a content's custom score\",\"tags\":[\"Contents\"]},{\"uid\":\"GET /custom_fields\",\"operationId\":\"getAllCustomFields\",\"functionName\":\"GetAllCustomFields\",\"method\":\"GET\",\"path\":\"/custom_fields\",\"summary\":\"Getting all custom fields\",\"tags\":[\"CustomFields\"]},{\"uid\":\"POST /custom_fields\",\"operationId\":\"createCustomField\",\"functionName\":\"CreateCustomField\",\"method\":\"POST\",\"path\":\"/custom_fields\",\"summary\":\"Creating a custom field\",\"tags\":[\"CustomFields\"]},{\"uid\":\"DELETE /custom_fields/{customFieldId}\",\"operationId\":\"deleteCustomField\",\"functionName\":\"DeleteCustomField\",\"method\":\"DELETE\",\"path\":\"/custom_fields/{customFieldId}\",\"summary\":\"Deleting a custom field\",\"tags\":[\"CustomFields\"]},{\"uid\":\"GET /custom_fields/{customFieldId}\",\"operationId\":\"getCustomField\",\"functionName\":\"GetCustomField\",\"method\":\"GET\",\"path\":\"/custom_fields/{customFieldId}\",\"summary\":\"Getting a custom field from its id\",\"tags\":[\"CustomFields\"]},{\"uid\":\"PUT /custom_fields/{customFieldId}\",\"operationId\":\"updateCustomField\",\"functionName\":\"UpdateCustomField\",\"method\":\"PUT\",\"path\":\"/custom_fields/{customFieldId}\",\"summary\":\"Updating a custom field\",\"tags\":[\"CustomFields\"]},{\"uid\":\"GET /events\",\"operationId\":\"getAllEvents\",\"functionName\":\"GetAllEvents\",\"method\":\"GET\",\"path\":\"/events\",\"summary\":\"Getting all events\",\"tags\":[\"Events\"]},{\"uid\":\"GET /events/{eventId}\",\"operationId\":\"getEvent\",\"functionName\":\"GetEvent\",\"method\":\"GET\",\"path\":\"/events/{eventId}\",\"summary\":\"Getting an event from its id\",\"tags\":[\"Events\"]},{\"uid\":\"GET /folders\",\"operationId\":\"getAllFolders\",\"functionName\":\"GetAllFolders\",\"method\":\"GET\",\"path\":\"/folders\",\"summary\":\"Getting all folders\",\"tags\":[\"Folders\"]},{\"uid\":\"POST /folders\",\"operationId\":\"createFolder\",\"functionName\":\"CreateFolder\",\"method\":\"POST\",\"path\":\"/folders\",\"summary\":\"Creating a folder\",\"tags\":[\"Folders\"]},{\"uid\":\"DELETE /folders/{folderId}\",\"operationId\":\"deleteFolder\",\"functionName\":\"DeleteFolder\",\"method\":\"DELETE\",\"path\":\"/folders/{folderId}\",\"summary\":\"Deleting a folder\",\"tags\":[\"Folders\"]},{\"uid\":\"GET /folders/{folderId}\",\"operationId\":\"getFolder\",\"functionName\":\"GetFolder\",\"method\":\"GET\",\"path\":\"/folders/{folderId}\",\"summary\":\"Getting a folder from its id\",\"tags\":[\"Folders\"]},{\"uid\":\"PUT /folders/{folderId}\",\"operationId\":\"updateFolder\",\"functionName\":\"UpdateFolder\",\"method\":\"PUT\",\"path\":\"/folders/{folderId}\",\"summary\":\"Updating a folder\",\"tags\":[\"Folders\"]},{\"uid\":\"GET /identities\",\"operationId\":\"getAllIdentities\",\"functionName\":\"GetAllIdentities\",\"method\":\"GET\",\"path\":\"/identities\",\"summary\":\"Getting all identities\",\"tags\":[\"Identities\"]},{\"uid\":\"GET /identities/{identityId}\",\"operationId\":\"getIdentity\",\"functionName\":\"GetIdentity\",\"method\":\"GET\",\"path\":\"/identities/{identityId}\",\"summary\":\"Getting an identity from its id\",\"tags\":[\"Identities\"]},{\"uid\":\"POST /identities/import\",\"operationId\":\"importIdentity\",\"functionName\":\"ImportIdentity\",\"method\":\"POST\",\"path\":\"/identities/import\",\"summary\":\"Importing an identity\",\"tags\":[\"Identities\"]},{\"uid\":\"GET /identity_groups\",\"operationId\":\"getAllIdentityGroups\",\"functionName\":\"GetAllIdentityGroups\",\"method\":\"GET\",\"path\":\"/identity_groups\",\"summary\":\"Getting all identity groups\",\"tags\":[\"Identity Groups\"]},{\"uid\":\"GET /identity_groups/{identityGroupId}\",\"operationId\":\"getIdentityGroup\",\"functionName\":\"GetIdentityGroup\",\"method\":\"GET\",\"path\":\"/identity_groups/{identityGroupId}\",\"summary\":\"Getting an identity group from its id\",\"tags\":[\"Identity Groups\"]},{\"uid\":\"PUT /identity_groups/{identityGroupId}\",\"operationId\":\"updateIdentityGroup\",\"functionName\":\"UpdateIdentityGroup\",\"method\":\"PUT\",\"path\":\"/identity_groups/{identityGroupId}\",\"summary\":\"Updating an identity group\",\"tags\":[\"Identity Groups\"]},{\"uid\":\"PUT /identity_groups/{identityGroupId}/merge\",\"operationId\":\"mergeIdentityGroup\",\"functionName\":\"MergeIdentityGroup\",\"method\":\"PUT\",\"path\":\"/identity_groups/{identityGroupId}/merge\",\"summary\":\"Merging an identity into an identity group\",\"tags\":[\"Identity Groups\"]},{\"uid\":\"GET /interface_locales\",\"operationId\":\"getAllUiLocales\",\"functionName\":\"GetAllUiLocales\",\"method\":\"GET\",\"path\":\"/interface_locales\",\"summary\":\"Getting all user interface locales\",\"tags\":[\"Locales\"]},{\"uid\":\"GET /intervention_comments\",\"operationId\":\"getAllInterventionComments\",\"functionName\":\"GetAllInterventionComments\",\"method\":\"GET\",\"path\":\"/intervention_comments\",\"summary\":\"Getting all intervention comments\",\"tags\":[\"Intervention Comments\"]},{\"uid\":\"POST /intervention_comments\",\"operationId\":\"createInterventionComment\",\"functionName\":\"CreateInterventionComment\",\"method\":\"POST\",\"path\":\"/intervention_comments\",\"summary\":\"Creating an intervention comment\",\"tags\":[\"Intervention Comments\"]},{\"uid\":\"DELETE /intervention_comments/{interventionCommentId}\",\"operationId\":\"deleteInterventionComment\",\"functionName\":\"DeleteInterventionComment\",\"method\":\"DELETE\",\"path\":\"/intervention_comments/{interventionCommentId}\",\"summary\":\"Deleting an intervention comment\",\"tags\":[\"Intervention Comments\"]},{\"uid\":\"GET /intervention_comments/{interventionCommentId}\",\"operationId\":\"getInterventionComment\",\"functionName\":\"GetInterventionComment\",\"method\":\"GET\",\"path\":\"/intervention_comments/{interventionCommentId}\",\"summary\":\"Getting an intervention comment from its id\",\"tags\":[\"Intervention Comments\"]},{\"uid\":\"GET /interventions\",\"operationId\":\"getAllInterventions\",\"functionName\":\"GetAllInterventions\",\"method\":\"GET\",\"path\":\"/interventions\",\"summary\":\"Getting all interventions\",\"tags\":[\"Interventions\"]},{\"uid\":\"POST /interventions\",\"operationId\":\"createIntervention\",\"functionName\":\"CreateIntervention\",\"method\":\"POST\",\"path\":\"/interventions\",\"summary\":\"Creating an intervention\",\"tags\":[\"Interventions\"]},{\"uid\":\"GET /interventions/{interventionId}\",\"operationId\":\"getIntervention\",\"functionName\":\"GetIntervention\",\"method\":\"GET\",\"path\":\"/interventions/{interventionId}\",\"summary\":\"Getting an intervention from its id\",\"tags\":[\"Interventions\"]},{\"uid\":\"PUT /interventions/{interventionId}\",\"operationId\":\"updateIntervention\",\"functionName\":\"UpdateIntervention\",\"method\":\"PUT\",\"path\":\"/interventions/{interventionId}\",\"summary\":\"Updating an intervention from its id\",\"tags\":[\"Interventions\"]},{\"uid\":\"DELETE /interventions/{interventionId}/cancel\",\"operationId\":\"cancelIntervention\",\"functionName\":\"CancelIntervention\",\"method\":\"DELETE\",\"path\":\"/interventions/{interventionId}/cancel\",\"summary\":\"Cancelling an intervention\",\"tags\":[\"Interventions\"]},{\"uid\":\"PUT /interventions/{interventionId}/close\",\"operationId\":\"closeIntervention\",\"functionName\":\"CloseIntervention\",\"method\":\"PUT\",\"path\":\"/interventions/{interventionId}/close\",\"summary\":\"Closing an intervention\",\"tags\":[\"Interventions\"]},{\"uid\":\"PUT /interventions/{interventionId}/reassign\",\"operationId\":\"reassignIntervention\",\"functionName\":\"ReassignIntervention\",\"method\":\"PUT\",\"path\":\"/interventions/{interventionId}/reassign\",\"summary\":\"Reassigning an intervention\",\"tags\":[\"Interventions\"]},{\"uid\":\"PUT /interventions/{interventionId}/update_categories\",\"operationId\":\"categorizeIntervention\",\"functionName\":\"CategorizeIntervention\",\"method\":\"PUT\",\"path\":\"/interventions/{interventionId}/update_categories\",\"summary\":\"Categorizing an intervention\",\"tags\":[\"Interventions\"]},{\"uid\":\"GET /locales\",\"operationId\":\"getAllLocales\",\"functionName\":\"GetAllLocales\",\"method\":\"GET\",\"path\":\"/locales\",\"summary\":\"Getting all content locales\",\"tags\":[\"Locales\"]},{\"uid\":\"GET /presence_status\",\"operationId\":\"getAllPresenceStatus\",\"functionName\":\"GetAllPresenceStatus\",\"method\":\"GET\",\"path\":\"/presence_status\",\"summary\":\"Getting all presence statuses\",\"tags\":[\"Presence Status\"]},{\"uid\":\"POST /presence_status\",\"operationId\":\"createPresenceStatus\",\"functionName\":\"CreatePresenceStatus\",\"method\":\"POST\",\"path\":\"/presence_status\",\"summary\":\"Creating a presence status\",\"tags\":[\"Presence Status\"]},{\"uid\":\"DELETE /presence_status/{presenceStatusId}\",\"operationId\":\"deletePresenceStatus\",\"functionName\":\"DeletePresenceStatus\",\"method\":\"DELETE\",\"path\":\"/presence_status/{presenceStatusId}\",\"summary\":\"Deleting a presence status\",\"tags\":[\"Presence Status\"]},{\"uid\":\"GET /presence_status/{presenceStatusId}\",\"operationId\":\"getPresenceStatus\",\"functionName\":\"GetPresenceStatus\",\"method\":\"GET\",\"path\":\"/presence_status/{presenceStatusId}\",\"summary\":\"Getting a presence status from its id\",\"tags\":[\"Presence Status\"]},{\"uid\":\"PUT /presence_status/{presenceStatusId}\",\"operationId\":\"updatePresenceStatus\",\"functionName\":\"UpdatePresenceStatus\",\"method\":\"PUT\",\"path\":\"/presence_status/{presenceStatusId}\",\"summary\":\"Updating a presence status\",\"tags\":[\"Presence Status\"]},{\"uid\":\"GET /reply_assistant/entries\",\"operationId\":\"getAllReplyAssistantEntries\",\"functionName\":\"GetAllReplyAssistantEntries\",\"method\":\"GET\",\"path\":\"/reply_assistant/entries\",\"summary\":\"Getting​ a​ll​ reply assistant e​ntries\",\"tags\":[\"Reply Assistant Entries\"]},{\"uid\":\"POST /reply_assistant/entries\",\"operationId\":\"createReplyAssistantEntry\",\"functionName\":\"CreateReplyAssistantEntry\",\"method\":\"POST\",\"path\":\"/reply_assistant/entries\",\"summary\":\"Creating an entry\",\"tags\":[\"Reply Assistant Entries\"]},{\"uid\":\"DELETE /reply_assistant/entries/{replyAssistantEntryId}\",\"operationId\":\"deleteReplyAssistantEntry\",\"functionName\":\"DeleteReplyAssistantEntry\",\"method\":\"DELETE\",\"path\":\"/reply_assistant/entries/{replyAssistantEntryId}\",\"summary\":\"Deleting a reply assistant entry\",\"tags\":[\"Reply Assistant Entries\"]},{\"uid\":\"GET /reply_assistant/entries/{replyAssistantEntryId}\",\"operationId\":\"getReplyAssistantEntry\",\"functionName\":\"GetReplyAssistantEntry\",\"method\":\"GET\",\"path\":\"/reply_assistant/entries/{replyAssistantEntryId}\",\"summary\":\"Getting a reply assistant entry from its id\",\"tags\":[\"Reply Assistant Entries\"]},{\"uid\":\"PUT /reply_assistant/entries/{replyAssistantEntryId}\",\"operationId\":\"updateReplyAssistantEntry\",\"functionName\":\"UpdateReplyAssistantEntry\",\"method\":\"PUT\",\"path\":\"/reply_assistant/entries/{replyAssistantEntryId}\",\"summary\":\"Updating a reply assistant entry\",\"tags\":[\"Reply Assistant Entries\"]},{\"uid\":\"GET /reply_assistant/groups\",\"operationId\":\"getAllReplyAssistantGroups\",\"functionName\":\"GetAllReplyAssistantGroups\",\"method\":\"GET\",\"path\":\"/reply_assistant/groups\",\"summary\":\"Getting​ a​ll​ reply assistant groups\",\"tags\":[\"Reply Assistant Groups\"]},{\"uid\":\"POST /reply_assistant/groups\",\"operationId\":\"createReplyAssistantGroup\",\"functionName\":\"CreateReplyAssistantGroup\",\"method\":\"POST\",\"path\":\"/reply_assistant/groups\",\"summary\":\"Creating a reply assistant group\",\"tags\":[\"Reply Assistant Groups\"]},{\"uid\":\"DELETE /reply_assistant/groups/{replyAssistantGroupId}\",\"operationId\":\"deleteReplyAssistantGroup\",\"functionName\":\"DeleteReplyAssistantGroup\",\"method\":\"DELETE\",\"path\":\"/reply_assistant/groups/{replyAssistantGroupId}\",\"summary\":\"Deleting a reply assistant group\",\"tags\":[\"Reply Assistant Groups\"]},{\"uid\":\"GET /reply_assistant/groups/{replyAssistantGroupId}\",\"operationId\":\"getReplyAssistantGroup\",\"functionName\":\"GetReplyAssistantGroup\",\"method\":\"GET\",\"path\":\"/reply_assistant/groups/{replyAssistantGroupId}\",\"summary\":\"Getting a reply assistant group from its id\",\"tags\":[\"Reply Assistant Groups\"]},{\"uid\":\"PUT /reply_assistant/groups/{replyAssistantGroupId}\",\"operationId\":\"updateReplyAssistantGroup\",\"functionName\":\"UpdateReplyAssistantGroup\",\"method\":\"PUT\",\"path\":\"/reply_assistant/groups/{replyAssistantGroupId}\",\"summary\":\"Updating a reply assistant group\",\"tags\":[\"Reply Assistant Groups\"]},{\"uid\":\"GET /reply_assistant/versions\",\"operationId\":\"getAllReplyAssistantVersions\",\"functionName\":\"GetAllReplyAssistantVersions\",\"method\":\"GET\",\"path\":\"/reply_assistant/versions\",\"summary\":\"Getting​ a​ll​ reply assistant versions\",\"tags\":[\"Reply Assistant Versions\"]},{\"uid\":\"POST /reply_assistant/versions\",\"operationId\":\"createReplyAssistantVersion\",\"functionName\":\"CreateReplyAssistantVersion\",\"method\":\"POST\",\"path\":\"/reply_assistant/versions\",\"summary\":\"Creating a reply assistant version\",\"tags\":[\"Reply Assistant Versions\"]},{\"uid\":\"DELETE /reply_assistant/versions/{replyAssistantVersionId}\",\"operationId\":\"deleteReplyAssistantVersion\",\"functionName\":\"DeleteReplyAssistantVersion\",\"method\":\"DELETE\",\"path\":\"/reply_assistant/versions/{replyAssistantVersionId}\",\"summary\":\"Deleting a reply assistant version\",\"tags\":[\"Reply Assistant Versions\"]},{\"uid\":\"GET /reply_assistant/versions/{replyAssistantVersionId}\",\"operationId\":\"getReplyAssistantVersion\",\"functionName\":\"GetReplyAssistantVersion\",\"method\":\"GET\",\"path\":\"/reply_assistant/versions/{replyAssistantVersionId}\",\"summary\":\"Getting a reply assistant version from its id\",\"tags\":[\"Reply Assistant Versions\"]},{\"uid\":\"PUT /reply_assistant/versions/{replyAssistantVersionId}\",\"operationId\":\"updateReplyAssistantVersion\",\"functionName\":\"UpdateReplyAssistantVersion\",\"method\":\"PUT\",\"path\":\"/reply_assistant/versions/{replyAssistantVersionId}\",\"summary\":\"Updating a reply assistant version\",\"tags\":[\"Reply Assistant Versions\"]},{\"uid\":\"GET /roles\",\"operationId\":\"getAllRoles\",\"functionName\":\"GetAllRoles\",\"method\":\"GET\",\"path\":\"/roles\",\"summary\":\"Getting all roles\",\"tags\":[\"Roles\"]},{\"uid\":\"POST /roles\",\"operationId\":\"createRole\",\"functionName\":\"CreateRole\",\"method\":\"POST\",\"path\":\"/roles\",\"summary\":\"Creating a role\",\"tags\":[\"Roles\"]},{\"uid\":\"GET /roles/{roleId}\",\"operationId\":\"getRole\",\"functionName\":\"GetRole\",\"method\":\"GET\",\"path\":\"/roles/{roleId}\",\"summary\":\"Getting a role from its id\",\"tags\":[\"Roles\"]},{\"uid\":\"PUT /roles/{roleId}\",\"operationId\":\"updateRole\",\"functionName\":\"UpdateRole\",\"method\":\"PUT\",\"path\":\"/roles/{roleId}\",\"summary\":\"Updating a role\",\"tags\":[\"Roles\"]},{\"uid\":\"GET /settings\",\"operationId\":\"getAllSettings\",\"functionName\":\"GetAllSettings\",\"method\":\"GET\",\"path\":\"/settings\",\"summary\":\"Getting all settings\",\"tags\":[\"Settings\"]},{\"uid\":\"PUT /settings\",\"operationId\":\"updateSettings\",\"functionName\":\"UpdateSettings\",\"method\":\"PUT\",\"path\":\"/settings\",\"summary\":\"Updating settings\",\"tags\":[\"Settings\"]},{\"uid\":\"GET /status\",\"operationId\":\"getAllAgentStatus\",\"functionName\":\"GetAllAgentStatus\",\"method\":\"GET\",\"path\":\"/status\",\"summary\":\"Get all connected agents status\",\"tags\":[\"Agent Status\"]},{\"uid\":\"GET /surveys\",\"operationId\":\"getAllSurveys\",\"functionName\":\"GetAllSurveys\",\"method\":\"GET\",\"path\":\"/surveys\",\"summary\":\"Getting all surveys\",\"tags\":[\"Surveys\"]},{\"uid\":\"GET /surveys/{surveyId}\",\"operationId\":\"getSurvey\",\"functionName\":\"GetSurvey\",\"method\":\"GET\",\"path\":\"/surveys/{surveyId}\",\"summary\":\"Getting a survey from its id\",\"tags\":[\"Surveys\"]},{\"uid\":\"GET /survey_responses/{surveyResponseId}\",\"operationId\":\"getSurveyResponse\",\"functionName\":\"GetSurveyResponse\",\"method\":\"GET\",\"path\":\"/survey_responses/{surveyResponseId}\",\"summary\":\"Get a survey response\",\"tags\":[\"Survey Responses\"]},{\"uid\":\"GET /status/{agentId}\",\"operationId\":\"getAgentStatus\",\"functionName\":\"GetAgentStatus\",\"method\":\"GET\",\"path\":\"/status/{agentId}\",\"summary\":\"Get a connected agent status\",\"tags\":[\"Agent Status\"]},{\"uid\":\"PUT /status/{agentId}\",\"operationId\":\"changeAgentStatus\",\"functionName\":\"ChangeAgentStatus\",\"method\":\"PUT\",\"path\":\"/status/{agentId}\",\"summary\":\"Changing an agent's status\",\"tags\":[\"Agent Status\"]},{\"uid\":\"GET /tags\",\"operationId\":\"getAllTags\",\"functionName\":\"GetAllTags\",\"method\":\"GET\",\"path\":\"/tags\",\"summary\":\"Getting all tags\",\"tags\":[\"Tags\"]},{\"uid\":\"POST /tags\",\"operationId\":\"createTag\",\"functionName\":\"CreateTag\",\"method\":\"POST\",\"path\":\"/tags\",\"summary\":\"Creating a tag\",\"tags\":[\"Tags\"]},{\"uid\":\"DELETE /tags/{tagId}\",\"operationId\":\"deleteTag\",\"functionName\":\"DeleteTag\",\"method\":\"DELETE\",\"path\":\"/tags/{tagId}\",\"summary\":\"Deleting a tag\",\"tags\":[\"Tags\"]},{\"uid\":\"GET /tags/{tagId}\",\"operationId\":\"getTag\",\"functionName\":\"GetTag\",\"method\":\"GET\",\"path\":\"/tags/{tagId}\",\"summary\":\"Getting a tag from its id\",\"tags\":[\"Tags\"]},{\"uid\":\"PUT /tags/{tagId}\",\"operationId\":\"updateTag\",\"functionName\":\"UpdateTag\",\"method\":\"PUT\",\"path\":\"/tags/{tagId}\",\"summary\":\"Updating a tag\",\"tags\":[\"Tags\"]},{\"uid\":\"GET /tasks\",\"operationId\":\"getAllTasks\",\"functionName\":\"GetAllTasks\",\"method\":\"GET\",\"path\":\"/tasks\",\"summary\":\"Getting all tasks\",\"tags\":[\"Tasks\"]},{\"uid\":\"GET /tasks/{taskId}\",\"operationId\":\"getTask\",\"functionName\":\"GetTask\",\"method\":\"GET\",\"path\":\"/tasks/{taskId}\",\"summary\":\"Getting a task from its id\",\"tags\":[\"Tasks\"]},{\"uid\":\"POST /tasks/{taskId}/move\",\"operationId\":\"moveTask\",\"functionName\":\"MoveTask\",\"method\":\"POST\",\"path\":\"/tasks/{taskId}/move\",\"summary\":\"Move a task to another queue\",\"tags\":[\"Tasks\"]},{\"uid\":\"POST /tasks/{taskId}/complete\",\"operationId\":\"completeTask\",\"functionName\":\"CompleteTask\",\"method\":\"POST\",\"path\":\"/tasks/{taskId}/complete\",\"summary\":\"Complete a task\",\"tags\":[\"Tasks\"]},{\"uid\":\"POST /tasks/{taskId}/transfer\",\"operationId\":\"transferTask\",\"functionName\":\"TransferTask\",\"method\":\"POST\",\"path\":\"/tasks/{taskId}/transfer\",\"summary\":\"Transferring a task\",\"tags\":[\"Tasks\"]},{\"uid\":\"GET /teams\",\"operationId\":\"getAllTeams\",\"functionName\":\"GetAllTeams\",\"method\":\"GET\",\"path\":\"/teams\",\"summary\":\"Getting all teams\",\"tags\":[\"Teams\"]},{\"uid\":\"POST /teams\",\"operationId\":\"createTeam\",\"functionName\":\"CreateTeam\",\"method\":\"POST\",\"path\":\"/teams\",\"summary\":\"Creating a team\",\"tags\":[\"Teams\"]},{\"uid\":\"DELETE /teams/{teamId}\",\"operationId\":\"deleteTeam\",\"functionName\":\"DeleteTeam\",\"method\":\"DELETE\",\"path\":\"/teams/{teamId}\",\"summary\":\"Deleting a team\",\"tags\":[\"Teams\"]},{\"uid\":\"GET /teams/{teamId}\",\"operationId\":\"getTeam\",\"functionName\":\"GetTeam\",\"method\":\"GET\",\"path\":\"/teams/{teamId}\",\"summary\":\"Getting a team from its id\",\"tags\":[\"Teams\"]},{\"uid\":\"PUT /teams/{teamId}\",\"operationId\":\"updateTeam\",\"functionName\":\"UpdateTeam\",\"method\":\"PUT\",\"path\":\"/teams/{teamId}\",\"summary\":\"Updating a team\",\"tags\":[\"Teams\"]},{\"uid\":\"GET /time_sheets\",\"operationId\":\"getAllTimeSheets\",\"functionName\":\"GetAllTimeSheets\",\"method\":\"GET\",\"path\":\"/time_sheets\",\"summary\":\"Getting all time sheets\",\"tags\":[\"Time Sheets\"]},{\"uid\":\"POST /time_sheets\",\"operationId\":\"createTimeSheet\",\"functionName\":\"CreateTimeSheet\",\"method\":\"POST\",\"path\":\"/time_sheets\",\"summary\":\"Creating a time sheet\",\"tags\":[\"Time Sheets\"]},{\"uid\":\"DELETE /time_sheets/{timeSheetId}\",\"operationId\":\"deleteTimeSheet\",\"functionName\":\"DeleteTimeSheet\",\"method\":\"DELETE\",\"path\":\"/time_sheets/{timeSheetId}\",\"summary\":\"Deleting a time sheet\",\"tags\":[\"Time Sheets\"]},{\"uid\":\"GET /time_sheets/{timeSheetId}\",\"operationId\":\"getTimeSheet\",\"functionName\":\"GetTimeSheet\",\"method\":\"GET\",\"path\":\"/time_sheets/{timeSheetId}\",\"summary\":\"Getting a time sheet from its id\",\"tags\":[\"Time Sheets\"]},{\"uid\":\"PUT /time_sheets/{timeSheetId}\",\"operationId\":\"updateTimeSheet\",\"functionName\":\"UpdateTimeSheet\",\"method\":\"PUT\",\"path\":\"/time_sheets/{timeSheetId}\",\"summary\":\"Updating a time sheet\",\"tags\":[\"Time Sheets\"]},{\"uid\":\"GET /timezones\",\"operationId\":\"getAllTimezones\",\"functionName\":\"GetAllTimezones\",\"method\":\"GET\",\"path\":\"/timezones\",\"summary\":\"Getting all timezones\",\"tags\":[\"Timezones\"]},{\"uid\":\"GET /user_capacities\",\"operationId\":\"getAllUserCapacities\",\"functionName\":\"GetAllUserCapacities\",\"method\":\"GET\",\"path\":\"/user_capacities\",\"summary\":\"Getting all User Capacities\",\"tags\":[\"User Capacities\"]},{\"uid\":\"POST /user_capacities\",\"operationId\":\"createUserCapacity\",\"functionName\":\"CreateUserCapacity\",\"method\":\"POST\",\"path\":\"/user_capacities\",\"summary\":\"Creating a user capacity\",\"tags\":[\"User Capacities\"]},{\"uid\":\"DELETE /user_capacities/{userCapacityId}\",\"operationId\":\"deleteUserCapacity\",\"functionName\":\"DeleteUserCapacity\",\"method\":\"DELETE\",\"path\":\"/user_capacities/{userCapacityId}\",\"summary\":\"Deleting a user capacity\",\"tags\":[\"User Capacities\"]},{\"uid\":\"GET /user_capacities/{userCapacityId}\",\"operationId\":\"getUserCapacity\",\"functionName\":\"GetUserCapacity\",\"method\":\"GET\",\"path\":\"/user_capacities/{userCapacityId}\",\"summary\":\"Getting a user capacity from its id\",\"tags\":[\"User Capacities\"]},{\"uid\":\"PUT /user_capacities/{userCapacityId}\",\"operationId\":\"updateUserCapacity\",\"functionName\":\"UpdateUserCapacity\",\"method\":\"PUT\",\"path\":\"/user_capacities/{userCapacityId}\",\"summary\":\"Updating a user capacity\",\"tags\":[\"User Capacities\"]},{\"uid\":\"GET /users\",\"operationId\":\"getAllUsers\",\"functionName\":\"GetAllUsers\",\"method\":\"GET\",\"path\":\"/users\",\"summary\":\"Getting all users\",\"tags\":[\"Users\"]},{\"uid\":\"POST /users\",\"operationId\":\"createUser\",\"functionName\":\"CreateUser\",\"method\":\"POST\",\"path\":\"/users\",\"summary\":\"Creating a user\",\"tags\":[\"Users\"]},{\"uid\":\"POST /users/invite\",\"operationId\":\"inviteUser\",\"functionName\":\"InviteUser\",\"method\":\"POST\",\"path\":\"/users/invite\",\"summary\":\"Inviting a user\",\"tags\":[\"Users\"]},{\"uid\":\"DELETE /users/{userId}\",\"operationId\":\"deleteUser\",\"functionName\":\"DeleteUser\",\"method\":\"DELETE\",\"path\":\"/users/{userId}\",\"summary\":\"Deleting a user\",\"tags\":[\"Users\"]},{\"uid\":\"GET /users/{userId}\",\"operationId\":\"getUser\",\"functionName\":\"GetUser\",\"method\":\"GET\",\"path\":\"/users/{userId}\",\"summary\":\"Getting a user from its id\",\"tags\":[\"Users\"]},{\"uid\":\"PUT /users/{userId}\",\"operationId\":\"updateUser\",\"functionName\":\"UpdateUser\",\"method\":\"PUT\",\"path\":\"/users/{userId}\",\"summary\":\"Updating a user\",\"tags\":[\"Users\"]},{\"uid\":\"GET /users/{userId}/sources_permissions\",\"operationId\":\"getUserSourcesPermissions\",\"functionName\":\"GetUserSourcesPermissions\",\"method\":\"GET\",\"path\":\"/users/{userId}/sources_permissions\",\"summary\":\"Getting a user's permissions on sources\",\"tags\":[\"Users Sources Permissions\"]},{\"uid\":\"PUT /users/{userId}/sources_permissions\",\"operationId\":\"updateUserSourcesPermissions\",\"functionName\":\"UpdateUserSourcesPermissions\",\"method\":\"PUT\",\"path\":\"/users/{userId}/sources_permissions\",\"summary\":\"Updating a user's permissions on sources\",\"tags\":[\"Users Sources Permissions\"]},{\"uid\":\"GET /users/{userId}/signatures\",\"operationId\":\"getAllUserSignatures\",\"functionName\":\"GetAllUserSignatures\",\"method\":\"GET\",\"path\":\"/users/{userId}/signatures\",\"summary\":\"Getting all user's signatures\",\"tags\":[\"User Signatures\"]},{\"uid\":\"POST /users/{userId}/signatures\",\"operationId\":\"createUserSignature\",\"functionName\":\"CreateUserSignature\",\"method\":\"POST\",\"path\":\"/users/{userId}/signatures\",\"summary\":\"Creating a user's signature\",\"tags\":[\"User Signatures\"]},{\"uid\":\"DELETE /users/{userId}/signatures/{signatureId}\",\"operationId\":\"deleteUserSignature\",\"functionName\":\"DeleteUserSignature\",\"method\":\"DELETE\",\"path\":\"/users/{userId}/signatures/{signatureId}\",\"summary\":\"Deleting a user's signature\",\"tags\":[\"User Signatures\"]},{\"uid\":\"GET /users/{userId}/signatures/{signatureId}\",\"operationId\":\"getUserSignature\",\"functionName\":\"GetUserSignature\",\"method\":\"GET\",\"path\":\"/users/{userId}/signatures/{signatureId}\",\"summary\":\"Getting a user's signature from its id\",\"tags\":[\"User Signatures\"]},{\"uid\":\"PUT /users/{userId}/signatures/{signatureId}\",\"operationId\":\"updateUserSignature\",\"functionName\":\"UpdateUserSignature\",\"method\":\"PUT\",\"path\":\"/users/{userId}/signatures/{signatureId}\",\"summary\":\"Updating a user's signature\",\"tags\":[\"User Signatures\"]},{\"uid\":\"GET /webhooks\",\"operationId\":\"getAllWebhooks\",\"functionName\":\"GetAllWebhooks\",\"method\":\"GET\",\"path\":\"/webhooks\",\"summary\":\"Getting all webhooks\",\"tags\":[\"Webhooks\"]},{\"uid\":\"POST /webhooks\",\"operationId\":\"createWebhook\",\"functionName\":\"CreateWebhook\",\"method\":\"POST\",\"path\":\"/webhooks\",\"summary\":\"Creating a webhook\",\"tags\":[\"Webhooks\"]},{\"uid\":\"DELETE /webhooks/{webhookId}\",\"operationId\":\"deleteWebhook\",\"functionName\":\"DeleteWebhook\",\"method\":\"DELETE\",\"path\":\"/webhooks/{webhookId}\",\"summary\":\"Deleting a webhook\",\"tags\":[\"Webhooks\"]},{\"uid\":\"GET /webhooks/{webhookId}\",\"operationId\":\"getWebhook\",\"functionName\":\"GetWebhook\",\"method\":\"GET\",\"path\":\"/webhooks/{webhookId}\",\"summary\":\"Getting a webhook from its id\",\"tags\":[\"Webhooks\"]},{\"uid\":\"PUT /webhooks/{webhookId}\",\"operationId\":\"updateWebhook\",\"functionName\":\"UpdateWebhook\",\"method\":\"PUT\",\"path\":\"/webhooks/{webhookId}\",\"summary\":\"Updating a webhook\",\"tags\":[\"Webhooks\"]}]") as readonly RingCentralDigitalApiOperation[];
export const RINGCENTRAL_DIGITAL_API_OPERATION_BY_ID = new Map(RINGCENTRAL_DIGITAL_API_OPERATIONS.map((operation) => [operation.operationId, operation]));
export const RINGCENTRAL_DIGITAL_API_OPERATION_BY_UID = new Map(RINGCENTRAL_DIGITAL_API_OPERATIONS.map((operation) => [operation.uid, operation]));

// Hardened literal operation keys for generated SDK typing.
export const RINGCENTRAL_DIGITAL_API_OPERATION_IDS = [
  "activateTopology",
  "updateTopology",
  "deleteTopology",
  "getTopology",
  "createTopology",
  "getAllTopologies",
  "getAllAttachments",
  "createAttachment",
  "getAttachment",
  "botEngage",
  "botComplete",
  "handoverFromBotToAgent",
  "getAllCategories",
  "createCategory",
  "deleteCategory",
  "getCategory",
  "updateCategory",
  "getAllChannels",
  "getChannel",
  "updateChannel",
  "getAllCommunities",
  "getCommunity",
  "getAllSources",
  "getSource",
  "updateSource",
  "updateSourceEmailCredentials",
  "getAllThreads",
  "getThread",
  "closeThread",
  "archiveThread",
  "openThread",
  "categorizeThread",
  "disableThreadTextInput",
  "enableThreadTextInput",
  "getAllContents",
  "createContent",
  "getContent",
  "ignoreContent",
  "categorizeContent",
  "updateCustomScore",
  "getAllCustomFields",
  "createCustomField",
  "deleteCustomField",
  "getCustomField",
  "updateCustomField",
  "getAllEvents",
  "getEvent",
  "getAllFolders",
  "createFolder",
  "deleteFolder",
  "getFolder",
  "updateFolder",
  "getAllIdentities",
  "getIdentity",
  "importIdentity",
  "getAllIdentityGroups",
  "getIdentityGroup",
  "updateIdentityGroup",
  "mergeIdentityGroup",
  "getAllUiLocales",
  "getAllInterventionComments",
  "createInterventionComment",
  "deleteInterventionComment",
  "getInterventionComment",
  "getAllInterventions",
  "createIntervention",
  "getIntervention",
  "updateIntervention",
  "cancelIntervention",
  "closeIntervention",
  "reassignIntervention",
  "categorizeIntervention",
  "getAllLocales",
  "getAllPresenceStatus",
  "createPresenceStatus",
  "deletePresenceStatus",
  "getPresenceStatus",
  "updatePresenceStatus",
  "getAllReplyAssistantEntries",
  "createReplyAssistantEntry",
  "deleteReplyAssistantEntry",
  "getReplyAssistantEntry",
  "updateReplyAssistantEntry",
  "getAllReplyAssistantGroups",
  "createReplyAssistantGroup",
  "deleteReplyAssistantGroup",
  "getReplyAssistantGroup",
  "updateReplyAssistantGroup",
  "getAllReplyAssistantVersions",
  "createReplyAssistantVersion",
  "deleteReplyAssistantVersion",
  "getReplyAssistantVersion",
  "updateReplyAssistantVersion",
  "getAllRoles",
  "createRole",
  "getRole",
  "updateRole",
  "getAllSettings",
  "updateSettings",
  "getAllAgentStatus",
  "getAllSurveys",
  "getSurvey",
  "getSurveyResponse",
  "getAgentStatus",
  "changeAgentStatus",
  "getAllTags",
  "createTag",
  "deleteTag",
  "getTag",
  "updateTag",
  "getAllTasks",
  "getTask",
  "moveTask",
  "completeTask",
  "transferTask",
  "getAllTeams",
  "createTeam",
  "deleteTeam",
  "getTeam",
  "updateTeam",
  "getAllTimeSheets",
  "createTimeSheet",
  "deleteTimeSheet",
  "getTimeSheet",
  "updateTimeSheet",
  "getAllTimezones",
  "getAllUserCapacities",
  "createUserCapacity",
  "deleteUserCapacity",
  "getUserCapacity",
  "updateUserCapacity",
  "getAllUsers",
  "createUser",
  "inviteUser",
  "deleteUser",
  "getUser",
  "updateUser",
  "getUserSourcesPermissions",
  "updateUserSourcesPermissions",
  "getAllUserSignatures",
  "createUserSignature",
  "deleteUserSignature",
  "getUserSignature",
  "updateUserSignature",
  "getAllWebhooks",
  "createWebhook",
  "deleteWebhook",
  "getWebhook",
  "updateWebhook"
] as const;
export const RINGCENTRAL_DIGITAL_API_OPERATION_OPERATION_IDS = [
  "activateTopology",
  "updateTopology",
  "deleteTopology",
  "getTopology",
  "createTopology",
  "getAllTopologies",
  "getAllAttachments",
  "createAttachment",
  "getAttachment",
  "botEngage",
  "botComplete",
  "handoverFromBotToAgent",
  "getAllCategories",
  "createCategory",
  "deleteCategory",
  "getCategory",
  "updateCategory",
  "getAllChannels",
  "getChannel",
  "updateChannel",
  "getAllCommunities",
  "getCommunity",
  "getAllSources",
  "getSource",
  "updateSource",
  "updateSourceEmailCredentials",
  "getAllThreads",
  "getThread",
  "closeThread",
  "archiveThread",
  "openThread",
  "categorizeThread",
  "disableThreadTextInput",
  "enableThreadTextInput",
  "getAllContents",
  "createContent",
  "getContent",
  "ignoreContent",
  "categorizeContent",
  "updateCustomScore",
  "getAllCustomFields",
  "createCustomField",
  "deleteCustomField",
  "getCustomField",
  "updateCustomField",
  "getAllEvents",
  "getEvent",
  "getAllFolders",
  "createFolder",
  "deleteFolder",
  "getFolder",
  "updateFolder",
  "getAllIdentities",
  "getIdentity",
  "importIdentity",
  "getAllIdentityGroups",
  "getIdentityGroup",
  "updateIdentityGroup",
  "mergeIdentityGroup",
  "getAllUiLocales",
  "getAllInterventionComments",
  "createInterventionComment",
  "deleteInterventionComment",
  "getInterventionComment",
  "getAllInterventions",
  "createIntervention",
  "getIntervention",
  "updateIntervention",
  "cancelIntervention",
  "closeIntervention",
  "reassignIntervention",
  "categorizeIntervention",
  "getAllLocales",
  "getAllPresenceStatus",
  "createPresenceStatus",
  "deletePresenceStatus",
  "getPresenceStatus",
  "updatePresenceStatus",
  "getAllReplyAssistantEntries",
  "createReplyAssistantEntry",
  "deleteReplyAssistantEntry",
  "getReplyAssistantEntry",
  "updateReplyAssistantEntry",
  "getAllReplyAssistantGroups",
  "createReplyAssistantGroup",
  "deleteReplyAssistantGroup",
  "getReplyAssistantGroup",
  "updateReplyAssistantGroup",
  "getAllReplyAssistantVersions",
  "createReplyAssistantVersion",
  "deleteReplyAssistantVersion",
  "getReplyAssistantVersion",
  "updateReplyAssistantVersion",
  "getAllRoles",
  "createRole",
  "getRole",
  "updateRole",
  "getAllSettings",
  "updateSettings",
  "getAllAgentStatus",
  "getAllSurveys",
  "getSurvey",
  "getSurveyResponse",
  "getAgentStatus",
  "changeAgentStatus",
  "getAllTags",
  "createTag",
  "deleteTag",
  "getTag",
  "updateTag",
  "getAllTasks",
  "getTask",
  "moveTask",
  "completeTask",
  "transferTask",
  "getAllTeams",
  "createTeam",
  "deleteTeam",
  "getTeam",
  "updateTeam",
  "getAllTimeSheets",
  "createTimeSheet",
  "deleteTimeSheet",
  "getTimeSheet",
  "updateTimeSheet",
  "getAllTimezones",
  "getAllUserCapacities",
  "createUserCapacity",
  "deleteUserCapacity",
  "getUserCapacity",
  "updateUserCapacity",
  "getAllUsers",
  "createUser",
  "inviteUser",
  "deleteUser",
  "getUser",
  "updateUser",
  "getUserSourcesPermissions",
  "updateUserSourcesPermissions",
  "getAllUserSignatures",
  "createUserSignature",
  "deleteUserSignature",
  "getUserSignature",
  "updateUserSignature",
  "getAllWebhooks",
  "createWebhook",
  "deleteWebhook",
  "getWebhook",
  "updateWebhook"
] as const;
export const RINGCENTRAL_DIGITAL_API_OPERATION_UIDS = [
  "PUT /topologies/{topologyId}/activate",
  "PUT /topologies/{topologyId}",
  "DELETE /topologies/{topologyId}",
  "GET /topologies/{topologyId}",
  "POST /topologies",
  "GET /topologies",
  "GET /attachments",
  "POST /attachments",
  "GET /attachments/{attachmentId}",
  "POST /bots/engage",
  "POST /bots/complete",
  "POST /bots/handover",
  "GET /categories",
  "POST /categories",
  "DELETE /categories/{categoryId}",
  "GET /categories/{categoryId}",
  "PUT /categories/{categoryId}",
  "GET /channels",
  "GET /channels/{channelId}",
  "PUT /channels/{channelId}",
  "GET /communities",
  "GET /communities/{communityId}",
  "GET /content_sources",
  "GET /content_sources/{sourceId}",
  "PUT /content_sources/{sourceId}",
  "PUT /content_sources/{sourceId}/email_credentials",
  "GET /content_threads",
  "GET /content_threads/{threadId}",
  "PUT /content_threads/{threadId}/close",
  "PUT /content_threads/{threadId}/ignore",
  "GET /content_threads/{threadId}/open",
  "PUT /content_threads/{threadId}/update_categories",
  "PUT /content_threads/{threadId}/disable_text_input",
  "PUT /content_threads/{threadId}/enable_text_input",
  "GET /contents",
  "POST /contents",
  "GET /contents/{contentId}",
  "PUT /contents/{contentId}/ignore",
  "PUT /contents/{contentId}/update_categories",
  "PUT /contents/{contentId}/update_custom_score",
  "GET /custom_fields",
  "POST /custom_fields",
  "DELETE /custom_fields/{customFieldId}",
  "GET /custom_fields/{customFieldId}",
  "PUT /custom_fields/{customFieldId}",
  "GET /events",
  "GET /events/{eventId}",
  "GET /folders",
  "POST /folders",
  "DELETE /folders/{folderId}",
  "GET /folders/{folderId}",
  "PUT /folders/{folderId}",
  "GET /identities",
  "GET /identities/{identityId}",
  "POST /identities/import",
  "GET /identity_groups",
  "GET /identity_groups/{identityGroupId}",
  "PUT /identity_groups/{identityGroupId}",
  "PUT /identity_groups/{identityGroupId}/merge",
  "GET /interface_locales",
  "GET /intervention_comments",
  "POST /intervention_comments",
  "DELETE /intervention_comments/{interventionCommentId}",
  "GET /intervention_comments/{interventionCommentId}",
  "GET /interventions",
  "POST /interventions",
  "GET /interventions/{interventionId}",
  "PUT /interventions/{interventionId}",
  "DELETE /interventions/{interventionId}/cancel",
  "PUT /interventions/{interventionId}/close",
  "PUT /interventions/{interventionId}/reassign",
  "PUT /interventions/{interventionId}/update_categories",
  "GET /locales",
  "GET /presence_status",
  "POST /presence_status",
  "DELETE /presence_status/{presenceStatusId}",
  "GET /presence_status/{presenceStatusId}",
  "PUT /presence_status/{presenceStatusId}",
  "GET /reply_assistant/entries",
  "POST /reply_assistant/entries",
  "DELETE /reply_assistant/entries/{replyAssistantEntryId}",
  "GET /reply_assistant/entries/{replyAssistantEntryId}",
  "PUT /reply_assistant/entries/{replyAssistantEntryId}",
  "GET /reply_assistant/groups",
  "POST /reply_assistant/groups",
  "DELETE /reply_assistant/groups/{replyAssistantGroupId}",
  "GET /reply_assistant/groups/{replyAssistantGroupId}",
  "PUT /reply_assistant/groups/{replyAssistantGroupId}",
  "GET /reply_assistant/versions",
  "POST /reply_assistant/versions",
  "DELETE /reply_assistant/versions/{replyAssistantVersionId}",
  "GET /reply_assistant/versions/{replyAssistantVersionId}",
  "PUT /reply_assistant/versions/{replyAssistantVersionId}",
  "GET /roles",
  "POST /roles",
  "GET /roles/{roleId}",
  "PUT /roles/{roleId}",
  "GET /settings",
  "PUT /settings",
  "GET /status",
  "GET /surveys",
  "GET /surveys/{surveyId}",
  "GET /survey_responses/{surveyResponseId}",
  "GET /status/{agentId}",
  "PUT /status/{agentId}",
  "GET /tags",
  "POST /tags",
  "DELETE /tags/{tagId}",
  "GET /tags/{tagId}",
  "PUT /tags/{tagId}",
  "GET /tasks",
  "GET /tasks/{taskId}",
  "POST /tasks/{taskId}/move",
  "POST /tasks/{taskId}/complete",
  "POST /tasks/{taskId}/transfer",
  "GET /teams",
  "POST /teams",
  "DELETE /teams/{teamId}",
  "GET /teams/{teamId}",
  "PUT /teams/{teamId}",
  "GET /time_sheets",
  "POST /time_sheets",
  "DELETE /time_sheets/{timeSheetId}",
  "GET /time_sheets/{timeSheetId}",
  "PUT /time_sheets/{timeSheetId}",
  "GET /timezones",
  "GET /user_capacities",
  "POST /user_capacities",
  "DELETE /user_capacities/{userCapacityId}",
  "GET /user_capacities/{userCapacityId}",
  "PUT /user_capacities/{userCapacityId}",
  "GET /users",
  "POST /users",
  "POST /users/invite",
  "DELETE /users/{userId}",
  "GET /users/{userId}",
  "PUT /users/{userId}",
  "GET /users/{userId}/sources_permissions",
  "PUT /users/{userId}/sources_permissions",
  "GET /users/{userId}/signatures",
  "POST /users/{userId}/signatures",
  "DELETE /users/{userId}/signatures/{signatureId}",
  "GET /users/{userId}/signatures/{signatureId}",
  "PUT /users/{userId}/signatures/{signatureId}",
  "GET /webhooks",
  "POST /webhooks",
  "DELETE /webhooks/{webhookId}",
  "GET /webhooks/{webhookId}",
  "PUT /webhooks/{webhookId}"
] as const;
// End hardened literal operation keys.

export type RingCentralDigitalApiOperationId = typeof RINGCENTRAL_DIGITAL_API_OPERATION_OPERATION_IDS[number];
export type RingCentralDigitalApiOperationUid = typeof RINGCENTRAL_DIGITAL_API_OPERATION_UIDS[number];
