// Generated from the RingCentral RingCX Voice OpenAPI spec (https://raw.githubusercontent.com/ringcentral/engage-voice-api-docs/main/specs/engage-voice_openapi3.json).
// Do not edit by hand; run scripts/generate-ringcentral-voice-api.mjs after checking upstream docs.

export const RINGCENTRAL_VOICE_API_GENERATED_AT = "2026-06-18";
export const RINGCENTRAL_VOICE_API_SPEC_SOURCE = "https://raw.githubusercontent.com/ringcentral/engage-voice-api-docs/main/specs/engage-voice_openapi3.json";
export const RINGCENTRAL_VOICE_API_DOCS_SOURCE = "https://developers.ringcentral.com/engage-voice-api";
export const RINGCENTRAL_VOICE_API_REPO_SOURCE = "https://github.com/ringcentral/engage-voice-api-docs";
export const RINGCENTRAL_VOICE_API_SPEC_VERSION = "1.0.0";
export const RINGCENTRAL_VOICE_API_OPENAPI_VERSION = "3.0.0";
export const RINGCENTRAL_VOICE_API_PATH_COUNT = 87;
export const RINGCENTRAL_VOICE_API_OPERATION_COUNT = 138;

export interface RingCentralVoiceApiOperation {
  uid: string;
  operationId: string;
  functionName: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
  path: string;
  summary: string;
  tags: readonly string[];
}

export const RINGCENTRAL_VOICE_API_OPERATIONS = JSON.parse("[{\"uid\":\"POST /api/auth/login/rc/accesstoken\",\"operationId\":\"loginWithRcAccessToken\",\"functionName\":\"LoginWithRcAccessToken\",\"method\":\"POST\",\"path\":\"/api/auth/login/rc/accesstoken\",\"summary\":\"Logs in an RC user via their access token issued by the RC API server. Returns Engage access token and user details\",\"tags\":[\"RingCentral Auth\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/createManualAgentCall\",\"operationId\":\"createManualAgentCall\",\"functionName\":\"CreateManualAgentCall\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/activeCalls/createManualAgentCall\",\"summary\":\"Creates a manual agent call\",\"tags\":[\"Active Calls\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/activeCalls/list\",\"operationId\":\"getProductActiveCallsListRequest\",\"functionName\":\"GetProductActiveCallsListRequest\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/activeCalls/list\",\"summary\":\"Returns a listing of current active calls for a given product OR externalId, on an account\",\"tags\":[\"Active Calls\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/activeCalls/prerouteChecks/checkQueueStatus\",\"operationId\":\"checkQueueStatus\",\"functionName\":\"CheckQueueStatus\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/activeCalls/prerouteChecks/checkQueueStatus\",\"summary\":\"Check queue status\",\"tags\":[\"Active Calls\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/activeCalls/prerouteChecks/checkQueueThreshold\",\"operationId\":\"checkQueueThreshold\",\"functionName\":\"CheckQueueThreshold\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/activeCalls/prerouteChecks/checkQueueThreshold\",\"summary\":\"Check queue threshold\",\"tags\":[\"Active Calls\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/addSessionToCall\",\"operationId\":\"addSessionToCall\",\"functionName\":\"AddSessionToCall\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/addSessionToCall\",\"summary\":\"Provides support for adding sessions to an active call\",\"tags\":[\"Active Calls\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/dispositionCall\",\"operationId\":\"dispositionCall\",\"functionName\":\"DispositionCall\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/dispositionCall\",\"summary\":\"Sets the call disposition for either INBOUND or OUTBOUND calls and releases the agent from PD state\",\"tags\":[\"Active Calls\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/hangupCall\",\"operationId\":\"hangupCall\",\"functionName\":\"HangupCall\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/hangupCall\",\"summary\":\"Terminates an active call\",\"tags\":[\"Active Calls\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/hangupSession\",\"operationId\":\"hangupSession\",\"functionName\":\"HangupSession\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/hangupSession\",\"summary\":\"Terminates an active session\",\"tags\":[\"Active Calls\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/toggleCallRecording\",\"operationId\":\"toggleCallRecording\",\"functionName\":\"ToggleCallRecording\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/toggleCallRecording\",\"summary\":\"Provides support for toggling call recording on/off for an active call\",\"tags\":[\"Active Calls\"]},{\"uid\":\"GET /voice/api/v1/admin/auditLogs/auditable\",\"operationId\":\"getAuditableEntities\",\"functionName\":\"GetAuditableEntities\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/auditLogs/auditable\",\"summary\":\"Identify system entities eligible for auditing\",\"tags\":[\"Audit Logs\"]},{\"uid\":\"PUT /voice/api/v1/admin/auditLogs/search\",\"operationId\":\"searchAuditLogs\",\"functionName\":\"SearchAuditLogs\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/auditLogs/search\",\"summary\":\"Search administrative audit records\",\"tags\":[\"Audit Logs\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/agentGroups\",\"operationId\":\"getAgentGroupList\",\"functionName\":\"GetAgentGroupList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups\",\"summary\":\"Returns a listing of agent groups for an account\",\"tags\":[\"Agent Groups\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/agentGroups\",\"operationId\":\"createAgentGroup\",\"functionName\":\"CreateAgentGroup\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups\",\"summary\":\"Creates a single new agent group for an account\",\"tags\":[\"Agent Groups\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}\",\"operationId\":\"deleteAgentGroup\",\"functionName\":\"DeleteAgentGroup\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}\",\"summary\":\"Deletes an agent group for an account\",\"tags\":[\"Agent Groups\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}\",\"operationId\":\"getAgentGroup\",\"functionName\":\"GetAgentGroup\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}\",\"summary\":\"Returns a listing of agent groups for an account\",\"tags\":[\"Agent Groups\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}\",\"operationId\":\"updateAgentGroup\",\"functionName\":\"UpdateAgentGroup\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}\",\"summary\":\"Updates an agent group for an account\",\"tags\":[\"Agent Groups\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents\",\"operationId\":\"getAgentList\",\"functionName\":\"GetAgentList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents\",\"summary\":\"Returns a listing of agents for an agent group\",\"tags\":[\"Agents\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents\",\"operationId\":\"createAgent\",\"functionName\":\"CreateAgent\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents\",\"summary\":\"Creates a single agent for an agent group\",\"tags\":[\"Agents\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents\",\"operationId\":\"updateAgents\",\"functionName\":\"UpdateAgents\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents\",\"summary\":\"Updates a listing of agents for an agent group\",\"tags\":[\"Agents\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents/{agentId}\",\"operationId\":\"deleteAgent\",\"functionName\":\"DeleteAgent\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents/{agentId}\",\"summary\":\"Deletes an agent for an agent group\",\"tags\":[\"Agents\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents/{agentId}\",\"operationId\":\"getAgent\",\"functionName\":\"GetAgent\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents/{agentId}\",\"summary\":\"Returns a single agent for an agent group\",\"tags\":[\"Agents\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents/{agentId}\",\"operationId\":\"updateAgent\",\"functionName\":\"UpdateAgent\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents/{agentId}\",\"summary\":\"Updates a single agent for an agent group\",\"tags\":[\"Agents\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/gateGroups/{gateGroupId}/gates/{gateId}\",\"operationId\":\"getLoggedInAgentsByAgentGroupPerQueue\",\"functionName\":\"GetLoggedInAgentsByAgentGroupPerQueue\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/gateGroups/{gateGroupId}/gates/{gateId}\",\"summary\":\"Returns the count of agents in an agentGroup logged into a Queue \",\"tags\":[\"Agent Access\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/campaignLeads/actions\",\"operationId\":\"performLeadAction\",\"functionName\":\"PerformLeadAction\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/campaignLeads/actions\",\"summary\":\"Performs a lead action against the matching campaign leads found for the given the search criteria\",\"tags\":[\"Campaigns\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/campaignLeads/leadSearch\",\"operationId\":\"searchForCampaignLeads\",\"functionName\":\"SearchForCampaignLeads\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/campaignLeads/leadSearch\",\"summary\":\"Allows searching of campaign leads for a single campaign\",\"tags\":[\"Leads\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/campaignLeads/leadSearchByPhoneList\",\"operationId\":\"uploadSearchCriteriaForCampaignLeads\",\"functionName\":\"UploadSearchCriteriaForCampaignLeads\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/campaignLeads/leadSearchByPhoneList\",\"summary\":\"Allows searching of campaign leads for a single campaign\",\"tags\":[\"Campaigns\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/campaignLeads/leadStates\",\"operationId\":\"getLeadStates\",\"functionName\":\"GetLeadStates\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/campaignLeads/leadStates\",\"summary\":\"Returns a listing of all lead states for an account\",\"tags\":[\"Leads\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/campaignLeads/systemDispositions\",\"operationId\":\"getSystemDispositions\",\"functionName\":\"GetSystemDispositions\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/campaignLeads/systemDispositions\",\"summary\":\"Returns a listing of all system dispositions for an account\",\"tags\":[\"Leads\"]},{\"uid\":\"PATCH /voice/api/v1/admin/accounts/{accountId}/campaignLeads/{leadId}\",\"operationId\":\"patchCampaignLead\",\"functionName\":\"PatchCampaignLead\",\"method\":\"PATCH\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/campaignLeads/{leadId}\",\"summary\":\"Allows updating of a campaign lead, only updating those fields passed in\",\"tags\":[\"Leads\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/campaignLeads/{leadId}\",\"operationId\":\"updateCampaignLead\",\"functionName\":\"UpdateCampaignLead\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/campaignLeads/{leadId}\",\"summary\":\"Allows updating of a campaign lead, updating entire lead including fields not passed in\",\"tags\":[\"Leads\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/campaigns/{campaignId}/leadLoader/direct\",\"operationId\":\"loadDirectLeads\",\"functionName\":\"LoadDirectLeads\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/campaigns/{campaignId}/leadLoader/direct\",\"summary\":\"Uploads a single lead or list of leads to a new or existing list\",\"tags\":[\"Leads\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/campaigns/{campaignId}/leadLoader/preview\",\"operationId\":\"previewLeadList\",\"functionName\":\"PreviewLeadList\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/campaigns/{campaignId}/leadLoader/preview\",\"summary\":\"Upload new leads to a new or existing list\",\"tags\":[\"Outbound\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/campaigns/{campaignId}/leadLoader/process\",\"operationId\":\"loadList\",\"functionName\":\"LoadList\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/campaigns/{campaignId}/leadLoader/process\",\"summary\":\"Upload new leads to a new or existing list\",\"tags\":[\"Outbound\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/countries/available\",\"operationId\":\"getCountryList\",\"functionName\":\"GetCountryList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/countries/available\",\"summary\":\"Returns a listing of all country codes available on the system\",\"tags\":[\"Countries\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/dialGroups\",\"operationId\":\"getDialGroupListByAccount\",\"functionName\":\"GetDialGroupListByAccount\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups\",\"summary\":\"Returns a listing of dial groups for an account\",\"tags\":[\"Dial Groups\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/dialGroups\",\"operationId\":\"createDialGroup\",\"functionName\":\"CreateDialGroup\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups\",\"summary\":\"Creates a dial group for an account\",\"tags\":[\"Dial Groups\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/dialGroups/withChildren\",\"operationId\":\"getDialGroupListWithChildren\",\"functionName\":\"GetDialGroupListWithChildren\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/withChildren\",\"summary\":\"Returns a listing of dial groups with associated campaigns for an account\",\"tags\":[\"Dial Groups\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}\",\"operationId\":\"deleteDialGroup\",\"functionName\":\"DeleteDialGroup\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}\",\"summary\":\"Deletes a dial group for an account\",\"tags\":[\"Dial Groups\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}\",\"operationId\":\"getDialGroup\",\"functionName\":\"GetDialGroup\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}\",\"summary\":\"Returns a dial group for an account\",\"tags\":[\"Dial Groups\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}\",\"operationId\":\"updateDialGroup\",\"functionName\":\"UpdateDialGroup\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}\",\"summary\":\"Updates a dial group for an account\",\"tags\":[\"Dial Groups\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/assignAgents\",\"operationId\":\"assignAgentsToDialGroups\",\"functionName\":\"AssignAgentsToDialGroups\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/assignAgents\",\"summary\":\"Assigns a listing of agents to a dial group\",\"tags\":[\"Dial Groups\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/assignedAgents\",\"operationId\":\"getAgentsFromDialGroup\",\"functionName\":\"GetAgentsFromDialGroup\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/assignedAgents\",\"summary\":\"Returns a listing of all agents assigned to a dial group\",\"tags\":[\"Dial Groups\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns\",\"operationId\":\"getCampaignList\",\"functionName\":\"GetCampaignList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns\",\"summary\":\"Returns a listing of campaigns for a dial group\",\"tags\":[\"Campaigns\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns\",\"operationId\":\"createCampaign\",\"functionName\":\"CreateCampaign\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns\",\"summary\":\"Returns a campaign for a dial group\",\"tags\":[\"Campaigns\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}\",\"operationId\":\"deleteCampaign\",\"functionName\":\"DeleteCampaign\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}\",\"summary\":\"Deletes a campaign for a dial group\",\"tags\":[\"Campaigns\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}\",\"operationId\":\"getCampaign\",\"functionName\":\"GetCampaign\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}\",\"summary\":\"Returns a campaign for a dial group\",\"tags\":[\"Campaigns\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}\",\"operationId\":\"updateCampaign\",\"functionName\":\"UpdateCampaign\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}\",\"summary\":\"Updates a campaign for a dial group\",\"tags\":[\"Campaigns\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}/clearCache\",\"operationId\":\"forceDialerRefresh\",\"functionName\":\"ForceDialerRefresh\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}/clearCache\",\"summary\":\"Clears the cache for a campaign\",\"tags\":[\"Campaigns\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/withChildren\",\"operationId\":\"getGateGroupListWithChildren\",\"functionName\":\"GetGateGroupListWithChildren\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/withChildren\",\"summary\":\"Returns a listing of queue groups (AKA gate groups) with related data for an account\",\"tags\":[\"Queue Groups\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/withChildren/additionalData\",\"operationId\":\"getGateGroupListWithChildrenAdditionalData\",\"functionName\":\"GetGateGroupListWithChildrenAdditionalData\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/withChildren/additionalData\",\"summary\":\"Returns a listing of queue groups (AKA gate groups) with related and additional data for an account\",\"tags\":[\"Queue Groups\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}\",\"operationId\":\"deleteGateGroup\",\"functionName\":\"DeleteGateGroup\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}\",\"summary\":\"Deletes a single queue group (AKA gate group)\",\"tags\":[\"Queue Groups\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}\",\"operationId\":\"getGateGroup\",\"functionName\":\"GetGateGroup\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}\",\"summary\":\"Returns a single queue group (AKA gate group) for an account\",\"tags\":[\"Queue Groups\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}\",\"operationId\":\"updateGateGroup\",\"functionName\":\"UpdateGateGroup\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}\",\"summary\":\"Updates a single queue group (AKA gate group) for an account\",\"tags\":[\"Queue Groups\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates\",\"operationId\":\"getGateList\",\"functionName\":\"GetGateList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates\",\"summary\":\"Returns a listing of all queues (AKA gates) for a queue group\",\"tags\":[\"Queues\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates\",\"operationId\":\"createGate\",\"functionName\":\"CreateGate\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates\",\"summary\":\"Creates a new queue (AKA gate) for a queue group\",\"tags\":[\"Queues\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}\",\"operationId\":\"deleteGate\",\"functionName\":\"DeleteGate\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}\",\"summary\":\"Deletes a queue (AKA gate) for a queue group\",\"tags\":[\"Queues\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}\",\"operationId\":\"getGate\",\"functionName\":\"GetGate\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}\",\"summary\":\"Returns a single queue (AKA gate) for a queue group\",\"tags\":[\"Queues\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}\",\"operationId\":\"updateGate\",\"functionName\":\"UpdateGate\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}\",\"summary\":\"Updates a queue (AKA gate) for a queue group\",\"tags\":[\"Queues\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/assignAgents\",\"operationId\":\"assignAgentsToGate\",\"functionName\":\"AssignAgentsToGate\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/assignAgents\",\"summary\":\"Assigns a listing of agents to a queue (AKA gate)\",\"tags\":[\"Agents\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/assignGateToPriorityGroup\",\"operationId\":\"assignGateToPriorityGroup\",\"functionName\":\"AssignGateToPriorityGroup\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/assignGateToPriorityGroup\",\"summary\":\"Assigns a queue (AKA gate) to a queue priority group for an account\",\"tags\":[\"Queues\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/assignedAgents\",\"operationId\":\"getAssignedAgentsForGate\",\"functionName\":\"GetAssignedAgentsForGate\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/assignedAgents\",\"summary\":\"Returns a listing of assigned agents for a queue (AKA gate) \",\"tags\":[\"Agents\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/clone\",\"operationId\":\"cloneGate\",\"functionName\":\"CloneGate\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/clone\",\"summary\":\"Creates a clone of a queue (AKA gate) for a queue group\",\"tags\":[\"Queues\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions\",\"operationId\":\"getGateDispositionList\",\"functionName\":\"GetGateDispositionList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions\",\"summary\":\"Returns a listing of dispositions for a queue (AKA gate)\",\"tags\":[\"Queue Dispositions\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions\",\"operationId\":\"createGateDisposition\",\"functionName\":\"CreateGateDisposition\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions\",\"summary\":\"Creates a disposition for a queue (AKA gate)\",\"tags\":[\"Queue Dispositions\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions\",\"operationId\":\"saveGateDispositionList\",\"functionName\":\"SaveGateDispositionList\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions\",\"summary\":\"Saves a list of dispositions for a queue (AKA gate)\",\"tags\":[\"Queue Dispositions\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions/{gateDispositionId}\",\"operationId\":\"deleteGateDisposition\",\"functionName\":\"DeleteGateDisposition\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions/{gateDispositionId}\",\"summary\":\"Deletes a disposition for a queue (AKA gate)\",\"tags\":[\"Queue Dispositions\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions/{gateDispositionId}\",\"operationId\":\"getGateDisposition\",\"functionName\":\"GetGateDisposition\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions/{gateDispositionId}\",\"summary\":\"Returns a single disposition for a queue (AKA gate)\",\"tags\":[\"Queue Dispositions\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions/{gateDispositionId}\",\"operationId\":\"updateGateDisposition\",\"functionName\":\"UpdateGateDisposition\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions/{gateDispositionId}\",\"summary\":\"Updates a single disposition for a queue (AKA gate)\",\"tags\":[\"Queue Dispositions\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateAgentAccessLogin\",\"operationId\":\"getGatesAgentsLoggedInto\",\"functionName\":\"GetGatesAgentsLoggedInto\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateAgentAccessLogin\",\"summary\":\"Returns a listing of all agents that have access to the queue (AKA gate) - this includes data to indicate if an agent is currently logged into the queue\",\"tags\":[\"Agent Access\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents\",\"operationId\":\"getGateQueueEventList\",\"functionName\":\"GetGateQueueEventList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents\",\"summary\":\"Returns a listing of gate queue events for a queue\",\"tags\":[\"Queue Events\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents\",\"operationId\":\"createGateQueueEvent\",\"functionName\":\"CreateGateQueueEvent\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents\",\"summary\":\"createGateQueueEvent\",\"tags\":[\"Queue Events\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents\",\"operationId\":\"saveGateQueueEventList\",\"functionName\":\"SaveGateQueueEventList\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents\",\"summary\":\"Saves a list of gate queue events for a queue\",\"tags\":[\"Queue Events\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}\",\"operationId\":\"deleteGateQueueEvent\",\"functionName\":\"DeleteGateQueueEvent\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}\",\"summary\":\"Deletes a gate queue event for a queue\",\"tags\":[\"Queue Events\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}\",\"operationId\":\"getGateQueueEvent\",\"functionName\":\"GetGateQueueEvent\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}\",\"summary\":\"Returns a single gate queue event for a queue\",\"tags\":[\"Queue Events\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}\",\"operationId\":\"updateGateQueueEvent\",\"functionName\":\"UpdateGateQueueEvent\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}\",\"summary\":\"Updates a single gate queue event for a queue\",\"tags\":[\"Queue Events\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents\",\"operationId\":\"getGateQueueDtmfEventList\",\"functionName\":\"GetGateQueueDtmfEventList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents\",\"summary\":\"Returns a listing of Gate Queue Dtmp Events for a Queue\",\"tags\":[\"Queue Events\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents\",\"operationId\":\"createGateQueueDtmfEvent\",\"functionName\":\"CreateGateQueueDtmfEvent\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents\",\"summary\":\"Creates a new Gate Queue Dtmp Event\",\"tags\":[\"Queue Events\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents\",\"operationId\":\"saveGateQueueDtmfEventList\",\"functionName\":\"SaveGateQueueDtmfEventList\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents\",\"summary\":\"Updates a listing of Gate Queue Dtmp Events\",\"tags\":[\"Queue Events\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents/{dtmfEventId}\",\"operationId\":\"deleteGateQueueDtmfEvent\",\"functionName\":\"DeleteGateQueueDtmfEvent\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents/{dtmfEventId}\",\"summary\":\"Deletes a Gate Queue Dtmp Event\",\"tags\":[\"Queue Events\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents/{dtmfEventId}\",\"operationId\":\"getGateQueueDtmfEvent\",\"functionName\":\"GetGateQueueDtmfEvent\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents/{dtmfEventId}\",\"summary\":\"Returns a single Gate Queue Dtmp Event\",\"tags\":[\"Queue Events\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents/{dtmfEventId}\",\"operationId\":\"updateGateQueueDtmfEvent\",\"functionName\":\"UpdateGateQueueDtmfEvent\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents/{dtmfEventId}\",\"summary\":\"Updates a single Gate Queue Dtmp Event\",\"tags\":[\"Queue Events\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/moveToGroup\",\"operationId\":\"moveGateToGroup\",\"functionName\":\"MoveGateToGroup\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/moveToGroup\",\"summary\":\"Move an existing queue (AKA gate) to a new existing queue group\",\"tags\":[\"Queues\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries\",\"operationId\":\"getGatePhoneBookEntries\",\"functionName\":\"GetGatePhoneBookEntries\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries\",\"summary\":\"Returns all phone book entries for a queue (AKA gate)\",\"tags\":[\"Queue Phone Book\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries\",\"operationId\":\"create\",\"functionName\":\"Create\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries\",\"summary\":\"Creates a phone book entry for a queue (AKA gate)\",\"tags\":[\"Queue Phone Book\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries\",\"operationId\":\"updateGatePhoneBookEntries\",\"functionName\":\"UpdateGatePhoneBookEntries\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries\",\"summary\":\"Updates a listing of phone book entries for a queue (AKA gate)\",\"tags\":[\"Queue Phone Book\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries/{entryId}\",\"operationId\":\"delete\",\"functionName\":\"Delete\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries/{entryId}\",\"summary\":\"Deletes a single phone book entry for a queue (AKA gate)\",\"tags\":[\"Queue Phone Book\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries/{entryId}\",\"operationId\":\"updatePhoneBookEntry\",\"functionName\":\"UpdatePhoneBookEntry\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries/{entryId}\",\"summary\":\"Updates a phone book entry for a queue (AKA gate)\",\"tags\":[\"Queue Phone Book\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts\",\"operationId\":\"getGateRequeueShortcutList\",\"functionName\":\"GetGateRequeueShortcutList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts\",\"summary\":\"Returns a listing of requeue shortcuts for a queue (AKA gate)\",\"tags\":[\"Requeue Shortcuts\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts\",\"operationId\":\"createGateRequeueShortcut\",\"functionName\":\"CreateGateRequeueShortcut\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts\",\"summary\":\"Updates a requeue shortcut for a queue (AKA gate)\",\"tags\":[\"Requeue Shortcuts\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts\",\"operationId\":\"createGateRequeueShortcuts\",\"functionName\":\"CreateGateRequeueShortcuts\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts\",\"summary\":\"Creates a list of requeue shortcuts for a queue (AKA gate)\",\"tags\":[\"Requeue Shortcuts\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts/{requeueShortcutId}\",\"operationId\":\"deleteGateRequeueShortcut\",\"functionName\":\"DeleteGateRequeueShortcut\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts/{requeueShortcutId}\",\"summary\":\"Returns a listing of requeue shortcuts for a queue (AKA gate)\",\"tags\":[\"Requeue Shortcuts\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts/{requeueShortcutId}\",\"operationId\":\"getGateRequeueShortcut\",\"functionName\":\"GetGateRequeueShortcut\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts/{requeueShortcutId}\",\"summary\":\"Returns a requeue shortcut for a queue (AKA gate)\",\"tags\":[\"Requeue Shortcuts\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts/{requeueShortcutId}\",\"operationId\":\"updateGateRequeueShortcut\",\"functionName\":\"UpdateGateRequeueShortcut\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts/{requeueShortcutId}\",\"summary\":\"Updates a requeue shortcut for a queue (AKA gate)\",\"tags\":[\"Requeue Shortcuts\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides\",\"operationId\":\"getOverridesForGate\",\"functionName\":\"GetOverridesForGate\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides\",\"summary\":\"Returns a listing of schedule overrides for a queue (AKA gate)\",\"tags\":[\"Queue Schedule\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides\",\"operationId\":\"createGateScheduledOverride\",\"functionName\":\"CreateGateScheduledOverride\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides\",\"summary\":\"Creates a schedule override for a queue (AKA gate)\",\"tags\":[\"Queue Schedule\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides\",\"operationId\":\"saveList\",\"functionName\":\"SaveList\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides\",\"summary\":\"Saves a listing of schedule overrides for a queue (AKA gate)\",\"tags\":[\"Queue Schedule\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides/{scheduleOverrideId}\",\"operationId\":\"deleteGateScheduledOverride\",\"functionName\":\"DeleteGateScheduledOverride\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides/{scheduleOverrideId}\",\"summary\":\"Deletes a schedule override for a queue (AKA gate)\",\"tags\":[\"Queue Schedule\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides/{scheduleOverrideId}\",\"operationId\":\"updateGateScheduledOverride\",\"functionName\":\"UpdateGateScheduledOverride\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides/{scheduleOverrideId}\",\"summary\":\"Updates a schedule override for a queue (AKA gate)\",\"tags\":[\"Queue Schedule\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/setIsActive\",\"operationId\":\"setGateIsActive\",\"functionName\":\"SetGateIsActive\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/setIsActive\",\"summary\":\"Set queue (AKA gate) active state\",\"tags\":[\"Queues\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis\",\"operationId\":\"deleteSpecialAni\",\"functionName\":\"DeleteSpecialAni\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis\",\"summary\":\"Deletes a special ani for a queue (AKA gate)\",\"tags\":[\"Queue Special ANI\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis\",\"operationId\":\"getGateSpecialAniList\",\"functionName\":\"GetGateSpecialAniList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis\",\"summary\":\"Returns a listing of special anis for a queue (AKA gate)\",\"tags\":[\"Queue Special ANI\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis\",\"operationId\":\"createGateSpecialAni\",\"functionName\":\"CreateGateSpecialAni\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis\",\"summary\":\"Creates a special ani for a queue (AKA gate)\",\"tags\":[\"Queue Special ANI\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis/upload\",\"operationId\":\"uploadSpecialAniList\",\"functionName\":\"UploadSpecialAniList\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis/upload\",\"summary\":\"Uploads a special ani for a queue (AKA gate)\",\"tags\":[\"Queue Special ANI\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/unassignAgent/{agentId}\",\"operationId\":\"unassignAgentFromGate\",\"functionName\":\"UnassignAgentFromGate\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/unassignAgent/{agentId}\",\"summary\":\"Unassigns a single agent from a queue (AKA gate)\",\"tags\":[\"Agents\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills\",\"operationId\":\"getList\",\"functionName\":\"GetList\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills\",\"summary\":\"Returns a listing of skills for a queue group (AKA gate group)\",\"tags\":[\"Queue Skills\"]},{\"uid\":\"POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills\",\"operationId\":\"createGateGroupSkill\",\"functionName\":\"CreateGateGroupSkill\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills\",\"summary\":\"Creates a skill for a queue group (AKA gate group)\",\"tags\":[\"Queue Skills\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills\",\"operationId\":\"saveGateGroupSkillList\",\"functionName\":\"SaveGateGroupSkillList\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills\",\"summary\":\"Updates an existing list of skills for a queue group (AKA gate group)\",\"tags\":[\"Queue Skills\"]},{\"uid\":\"DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills/{skillId}\",\"operationId\":\"deleteGateGroupSkill\",\"functionName\":\"DeleteGateGroupSkill\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills/{skillId}\",\"summary\":\"Deletes a skill for a queue group (AKA gate group)\",\"tags\":[\"Queue Skills\"]},{\"uid\":\"GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills/{skillId}\",\"operationId\":\"getDetail\",\"functionName\":\"GetDetail\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills/{skillId}\",\"summary\":\"Returns a skill for a queue group (AKA gate group)\",\"tags\":[\"Queue Skills\"]},{\"uid\":\"PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills/{skillId}\",\"operationId\":\"updateGateGroupSkill\",\"functionName\":\"UpdateGateGroupSkill\",\"method\":\"PUT\",\"path\":\"/voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills/{skillId}\",\"summary\":\"Updates a skill for a queue group (AKA gate group)\",\"tags\":[\"Queue Skills\"]},{\"uid\":\"GET /voice/api/v1/admin/reports/{reportType}\",\"operationId\":\"getReportCriteriaTemplate\",\"functionName\":\"GetReportCriteriaTemplate\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/reports/{reportType}\",\"summary\":\"Returns a report criteria definition for a report type\",\"tags\":[\"Reporting\"]},{\"uid\":\"GET /voice/api/v1/admin/token\",\"operationId\":\"getApiTokensForLoggedInUser\",\"functionName\":\"GetApiTokensForLoggedInUser\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/token\",\"summary\":\"Retrieves all Api Tokens for AuthenticatedUser\",\"tags\":[\"Legacy Auth\"]},{\"uid\":\"POST /voice/api/v1/admin/token\",\"operationId\":\"createApiTokenForLoggedInUser\",\"functionName\":\"CreateApiTokenForLoggedInUser\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/token\",\"summary\":\"Creates a new 'Api Token' based AuthenticatedUser that does not expire\",\"tags\":[\"Legacy Auth\"]},{\"uid\":\"DELETE /voice/api/v1/admin/token/{token}\",\"operationId\":\"removeApiToken\",\"functionName\":\"RemoveApiToken\",\"method\":\"DELETE\",\"path\":\"/voice/api/v1/admin/token/{token}\",\"summary\":\"Removes an api token\",\"tags\":[\"Legacy Auth\"]},{\"uid\":\"GET /voice/api/v1/admin/users\",\"operationId\":\"listAllUsers\",\"functionName\":\"ListAllUsers\",\"method\":\"GET\",\"path\":\"/voice/api/v1/admin/users\",\"summary\":\"Returns a listing of all users that a user has access to\",\"tags\":[\"Users\"]},{\"uid\":\"POST /voice/api/v1/admin/users\",\"operationId\":\"createUser\",\"functionName\":\"CreateUser\",\"method\":\"POST\",\"path\":\"/voice/api/v1/admin/users\",\"summary\":\"Creates a single new user\",\"tags\":[\"Users\"]},{\"uid\":\"POST /voice/api/v1/auth/login\",\"operationId\":\"doLogin\",\"functionName\":\"DoLogin\",\"method\":\"POST\",\"path\":\"/voice/api/v1/auth/login\",\"summary\":\"Application login to authenticate and receive an X-Auth-Token\",\"tags\":[\"Legacy Auth\"]},{\"uid\":\"GET /voice/api/integration/v1/admin/users/{mainAccountId}\",\"operationId\":\"getUserList\",\"functionName\":\"GetUserList\",\"method\":\"GET\",\"path\":\"/voice/api/integration/v1/admin/users/{mainAccountId}\",\"summary\":\"Returns a listing of all users that a user has access to\",\"tags\":[\"Integration User Controller\"]},{\"uid\":\"GET /voice/api/integration/v1/admin/accounts/{mainAccountId}/subaccounts\",\"operationId\":\"getSubAccountsByMainAccountId\",\"functionName\":\"GetSubAccountsByMainAccountId\",\"method\":\"GET\",\"path\":\"/voice/api/integration/v1/admin/accounts/{mainAccountId}/subaccounts\",\"summary\":\"Returns a listing of sub accounts by Engage Voice Main account identifier\",\"tags\":[\"Integration Account Controller\"]},{\"uid\":\"GET /voice/api/integration/v1/admin/accounts/{subAccountId}/agentGroups/{agentGroupId}/agents\",\"operationId\":\"getAgentList\",\"functionName\":\"GetAgentList2\",\"method\":\"GET\",\"path\":\"/voice/api/integration/v1/admin/accounts/{subAccountId}/agentGroups/{agentGroupId}/agents\",\"summary\":\"Returns a list of read only agents for an agent group\",\"tags\":[\"Integration Agent Controller\"]},{\"uid\":\"GET /voice/api/integration/v1/admin/accounts/{subAccountId}/agentGroups\",\"operationId\":\"getAgentGroups\",\"functionName\":\"GetAgentGroups\",\"method\":\"GET\",\"path\":\"/voice/api/integration/v1/admin/accounts/{subAccountId}/agentGroups\",\"summary\":\"Returns a list of agent groups for a sub-account\",\"tags\":[\"Integration Agent Group Controller\"]},{\"uid\":\"GET /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/recordings/dialogs/{dialogId}/segments/{segmentId}\",\"operationId\":\"getRecordingSegmentData\",\"functionName\":\"GetRecordingSegmentData\",\"method\":\"GET\",\"path\":\"/voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/recordings/dialogs/{dialogId}/segments/{segmentId}\",\"summary\":\"Fetches recordings data\",\"tags\":[\"Public Integration API\"]},{\"uid\":\"POST /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/interaction-metadata\",\"operationId\":\"getInteractionMetadata\",\"functionName\":\"GetInteractionMetadata\",\"method\":\"POST\",\"path\":\"/voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/interaction-metadata\",\"summary\":\"Returns Interaction Segment Metadata\",\"tags\":[\"Public Integration API\"]},{\"uid\":\"GET /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/transcripts/dialogs/{dialogId}/segments/{segmentId}\",\"operationId\":\"getTranscriptSegmentData\",\"functionName\":\"GetTranscriptSegmentData\",\"method\":\"GET\",\"path\":\"/voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/transcripts/dialogs/{dialogId}/segments/{segmentId}\",\"summary\":\"Fetches Transcript data for both voice and digital\",\"tags\":[\"Public Integration API\"]},{\"uid\":\"GET /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/queue-groups\",\"operationId\":\"getQueueGroups\",\"functionName\":\"GetQueueGroups\",\"method\":\"GET\",\"path\":\"/voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/queue-groups\",\"summary\":\"Returns a list of queue groups\",\"tags\":[\"Public Integration API\"]},{\"uid\":\"GET /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/queue-groups/{queueGroupId}/with-agents\",\"operationId\":\"getQueuesWithAgents\",\"functionName\":\"GetQueuesWithAgents\",\"method\":\"GET\",\"path\":\"/voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/queue-groups/{queueGroupId}/with-agents\",\"summary\":\"Returns a list of agent ids of the queue group.\",\"tags\":[\"Public Integration API\"]},{\"uid\":\"POST /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/agg-queue-stats\",\"operationId\":\"buildAggQueueStats\",\"functionName\":\"BuildAggQueueStats\",\"method\":\"POST\",\"path\":\"/voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/agg-queue-stats\",\"summary\":\"Builds queue statistics\",\"tags\":[\"Public Integration API\"]},{\"uid\":\"POST /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/agg-agent-extended-stats\",\"operationId\":\"buildExtendedAggAgentStats\",\"functionName\":\"BuildExtendedAggAgentStats\",\"method\":\"POST\",\"path\":\"/voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/agg-agent-extended-stats\",\"summary\":\"Builds extended agent queue statistics\",\"tags\":[\"Public Integration API\"]},{\"uid\":\"POST /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/agg-agent-stats\",\"operationId\":\"buildAggAgentStats\",\"functionName\":\"BuildAggAgentStats\",\"method\":\"POST\",\"path\":\"/voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/agg-agent-stats\",\"summary\":\"Builds agent statistics\",\"tags\":[\"Public Integration API\"]},{\"uid\":\"PUT /v1/admin/utilities/tnManager/updateCustomerDnisBulk\",\"operationId\":\"updateCustomerDnisBulkUsingPUT\",\"functionName\":\"UpdateCustomerDnisBulkUsingPUT\",\"method\":\"PUT\",\"path\":\"/v1/admin/utilities/tnManager/updateCustomerDnisBulk\",\"summary\":\"Update Dnis Records in Bulk\",\"tags\":[\"Number Management\"]},{\"uid\":\"POST /v1/admin/utilities/tnManager/searchDnis\",\"operationId\":\"getCustomerDnisPoolListUsingPOST\",\"functionName\":\"GetCustomerDnisPoolListUsingPOST\",\"method\":\"POST\",\"path\":\"/v1/admin/utilities/tnManager/searchDnis\",\"summary\":\"Returns all dnis pools for Customer\",\"tags\":[\"Number Management\"]},{\"uid\":\"PUT /v1/admin/utilities/tnManager/updateBulkDnisPool\",\"operationId\":\"updateBulkDnisPoolListUsingPUT\",\"functionName\":\"UpdateBulkDnisPoolListUsingPUT\",\"method\":\"PUT\",\"path\":\"/v1/admin/utilities/tnManager/updateBulkDnisPool\",\"summary\":\"Updates for bulk csv data dnis pool, will update assignments too\",\"tags\":[\"Number Management\"]},{\"uid\":\"POST /v1/admin/utilities/tnManager/uploadDnisPool\",\"operationId\":\"previewDnisListUsingPOST\",\"functionName\":\"PreviewDnisListUsingPOST\",\"method\":\"POST\",\"path\":\"/v1/admin/utilities/tnManager/uploadDnisPool\",\"summary\":\"Creates a list of dnis pools from upload file\",\"tags\":[\"Number Management\"]},{\"uid\":\"PUT /platform/api/media/product\",\"operationId\":\"updateProduct\",\"functionName\":\"UpdateProduct\",\"method\":\"PUT\",\"path\":\"/platform/api/media/product\",\"summary\":\"Update streaming profile\",\"tags\":[\"Audio Streaming\"]},{\"uid\":\"POST /platform/api/media/product\",\"operationId\":\"createProduct\",\"functionName\":\"CreateProduct\",\"method\":\"POST\",\"path\":\"/platform/api/media/product\",\"summary\":\"Create streaming profile\",\"tags\":[\"Audio Streaming\"]},{\"uid\":\"GET /platform/api/media/product/account/{subAccountId}/type/{productTypeString}/id/{productId}\",\"operationId\":\"getProduct\",\"functionName\":\"GetProduct\",\"method\":\"GET\",\"path\":\"/platform/api/media/product/account/{subAccountId}/type/{productTypeString}/id/{productId}\",\"summary\":\"Get streaming profile\",\"tags\":[\"Audio Streaming\"]},{\"uid\":\"DELETE /platform/api/media/product/account/{subAccountId}/type/{productTypeString}/id/{productId}\",\"operationId\":\"deleteProduct\",\"functionName\":\"DeleteProduct\",\"method\":\"DELETE\",\"path\":\"/platform/api/media/product/account/{subAccountId}/type/{productTypeString}/id/{productId}\",\"summary\":\"Delete streaming profile\",\"tags\":[\"Audio Streaming\"]}]") as readonly RingCentralVoiceApiOperation[];
export const RINGCENTRAL_VOICE_API_OPERATION_BY_ID = new Map(RINGCENTRAL_VOICE_API_OPERATIONS.map((operation) => [operation.operationId, operation]));
export const RINGCENTRAL_VOICE_API_OPERATION_BY_UID = new Map(RINGCENTRAL_VOICE_API_OPERATIONS.map((operation) => [operation.uid, operation]));

// Hardened literal operation keys for generated SDK typing.
export const RINGCENTRAL_VOICE_API_OPERATION_IDS = [
  "loginWithRcAccessToken",
  "createManualAgentCall",
  "getProductActiveCallsListRequest",
  "checkQueueStatus",
  "checkQueueThreshold",
  "addSessionToCall",
  "dispositionCall",
  "hangupCall",
  "hangupSession",
  "toggleCallRecording",
  "getAuditableEntities",
  "searchAuditLogs",
  "getAgentGroupList",
  "createAgentGroup",
  "deleteAgentGroup",
  "getAgentGroup",
  "updateAgentGroup",
  "getAgentList",
  "createAgent",
  "updateAgents",
  "deleteAgent",
  "getAgent",
  "updateAgent",
  "getLoggedInAgentsByAgentGroupPerQueue",
  "performLeadAction",
  "searchForCampaignLeads",
  "uploadSearchCriteriaForCampaignLeads",
  "getLeadStates",
  "getSystemDispositions",
  "patchCampaignLead",
  "updateCampaignLead",
  "loadDirectLeads",
  "previewLeadList",
  "loadList",
  "getCountryList",
  "getDialGroupListByAccount",
  "createDialGroup",
  "getDialGroupListWithChildren",
  "deleteDialGroup",
  "getDialGroup",
  "updateDialGroup",
  "assignAgentsToDialGroups",
  "getAgentsFromDialGroup",
  "getCampaignList",
  "createCampaign",
  "deleteCampaign",
  "getCampaign",
  "updateCampaign",
  "forceDialerRefresh",
  "getGateGroupListWithChildren",
  "getGateGroupListWithChildrenAdditionalData",
  "deleteGateGroup",
  "getGateGroup",
  "updateGateGroup",
  "getGateList",
  "createGate",
  "deleteGate",
  "getGate",
  "updateGate",
  "assignAgentsToGate",
  "assignGateToPriorityGroup",
  "getAssignedAgentsForGate",
  "cloneGate",
  "getGateDispositionList",
  "createGateDisposition",
  "saveGateDispositionList",
  "deleteGateDisposition",
  "getGateDisposition",
  "updateGateDisposition",
  "getGatesAgentsLoggedInto",
  "getGateQueueEventList",
  "createGateQueueEvent",
  "saveGateQueueEventList",
  "deleteGateQueueEvent",
  "getGateQueueEvent",
  "updateGateQueueEvent",
  "getGateQueueDtmfEventList",
  "createGateQueueDtmfEvent",
  "saveGateQueueDtmfEventList",
  "deleteGateQueueDtmfEvent",
  "getGateQueueDtmfEvent",
  "updateGateQueueDtmfEvent",
  "moveGateToGroup",
  "getGatePhoneBookEntries",
  "create",
  "updateGatePhoneBookEntries",
  "delete",
  "updatePhoneBookEntry",
  "getGateRequeueShortcutList",
  "createGateRequeueShortcut",
  "createGateRequeueShortcuts",
  "deleteGateRequeueShortcut",
  "getGateRequeueShortcut",
  "updateGateRequeueShortcut",
  "getOverridesForGate",
  "createGateScheduledOverride",
  "saveList",
  "deleteGateScheduledOverride",
  "updateGateScheduledOverride",
  "setGateIsActive",
  "deleteSpecialAni",
  "getGateSpecialAniList",
  "createGateSpecialAni",
  "uploadSpecialAniList",
  "unassignAgentFromGate",
  "getList",
  "createGateGroupSkill",
  "saveGateGroupSkillList",
  "deleteGateGroupSkill",
  "getDetail",
  "updateGateGroupSkill",
  "getReportCriteriaTemplate",
  "getApiTokensForLoggedInUser",
  "createApiTokenForLoggedInUser",
  "removeApiToken",
  "listAllUsers",
  "createUser",
  "doLogin",
  "getUserList",
  "getSubAccountsByMainAccountId",
  "getAgentGroups",
  "getRecordingSegmentData",
  "getInteractionMetadata",
  "getTranscriptSegmentData",
  "getQueueGroups",
  "getQueuesWithAgents",
  "buildAggQueueStats",
  "buildExtendedAggAgentStats",
  "buildAggAgentStats",
  "updateCustomerDnisBulkUsingPUT",
  "getCustomerDnisPoolListUsingPOST",
  "updateBulkDnisPoolListUsingPUT",
  "previewDnisListUsingPOST",
  "updateProduct",
  "createProduct",
  "getProduct",
  "deleteProduct"
] as const;
export const RINGCENTRAL_VOICE_API_OPERATION_OPERATION_IDS = [
  "loginWithRcAccessToken",
  "createManualAgentCall",
  "getProductActiveCallsListRequest",
  "checkQueueStatus",
  "checkQueueThreshold",
  "addSessionToCall",
  "dispositionCall",
  "hangupCall",
  "hangupSession",
  "toggleCallRecording",
  "getAuditableEntities",
  "searchAuditLogs",
  "getAgentGroupList",
  "createAgentGroup",
  "deleteAgentGroup",
  "getAgentGroup",
  "updateAgentGroup",
  "getAgentList",
  "createAgent",
  "updateAgents",
  "deleteAgent",
  "getAgent",
  "updateAgent",
  "getLoggedInAgentsByAgentGroupPerQueue",
  "performLeadAction",
  "searchForCampaignLeads",
  "uploadSearchCriteriaForCampaignLeads",
  "getLeadStates",
  "getSystemDispositions",
  "patchCampaignLead",
  "updateCampaignLead",
  "loadDirectLeads",
  "previewLeadList",
  "loadList",
  "getCountryList",
  "getDialGroupListByAccount",
  "createDialGroup",
  "getDialGroupListWithChildren",
  "deleteDialGroup",
  "getDialGroup",
  "updateDialGroup",
  "assignAgentsToDialGroups",
  "getAgentsFromDialGroup",
  "getCampaignList",
  "createCampaign",
  "deleteCampaign",
  "getCampaign",
  "updateCampaign",
  "forceDialerRefresh",
  "getGateGroupListWithChildren",
  "getGateGroupListWithChildrenAdditionalData",
  "deleteGateGroup",
  "getGateGroup",
  "updateGateGroup",
  "getGateList",
  "createGate",
  "deleteGate",
  "getGate",
  "updateGate",
  "assignAgentsToGate",
  "assignGateToPriorityGroup",
  "getAssignedAgentsForGate",
  "cloneGate",
  "getGateDispositionList",
  "createGateDisposition",
  "saveGateDispositionList",
  "deleteGateDisposition",
  "getGateDisposition",
  "updateGateDisposition",
  "getGatesAgentsLoggedInto",
  "getGateQueueEventList",
  "createGateQueueEvent",
  "saveGateQueueEventList",
  "deleteGateQueueEvent",
  "getGateQueueEvent",
  "updateGateQueueEvent",
  "getGateQueueDtmfEventList",
  "createGateQueueDtmfEvent",
  "saveGateQueueDtmfEventList",
  "deleteGateQueueDtmfEvent",
  "getGateQueueDtmfEvent",
  "updateGateQueueDtmfEvent",
  "moveGateToGroup",
  "getGatePhoneBookEntries",
  "create",
  "updateGatePhoneBookEntries",
  "delete",
  "updatePhoneBookEntry",
  "getGateRequeueShortcutList",
  "createGateRequeueShortcut",
  "createGateRequeueShortcuts",
  "deleteGateRequeueShortcut",
  "getGateRequeueShortcut",
  "updateGateRequeueShortcut",
  "getOverridesForGate",
  "createGateScheduledOverride",
  "saveList",
  "deleteGateScheduledOverride",
  "updateGateScheduledOverride",
  "setGateIsActive",
  "deleteSpecialAni",
  "getGateSpecialAniList",
  "createGateSpecialAni",
  "uploadSpecialAniList",
  "unassignAgentFromGate",
  "getList",
  "createGateGroupSkill",
  "saveGateGroupSkillList",
  "deleteGateGroupSkill",
  "getDetail",
  "updateGateGroupSkill",
  "getReportCriteriaTemplate",
  "getApiTokensForLoggedInUser",
  "createApiTokenForLoggedInUser",
  "removeApiToken",
  "listAllUsers",
  "createUser",
  "doLogin",
  "getUserList",
  "getSubAccountsByMainAccountId",
  "getAgentGroups",
  "getRecordingSegmentData",
  "getInteractionMetadata",
  "getTranscriptSegmentData",
  "getQueueGroups",
  "getQueuesWithAgents",
  "buildAggQueueStats",
  "buildExtendedAggAgentStats",
  "buildAggAgentStats",
  "updateCustomerDnisBulkUsingPUT",
  "getCustomerDnisPoolListUsingPOST",
  "updateBulkDnisPoolListUsingPUT",
  "previewDnisListUsingPOST",
  "updateProduct",
  "createProduct",
  "getProduct",
  "deleteProduct"
] as const;
export const RINGCENTRAL_VOICE_API_OPERATION_UIDS = [
  "POST /api/auth/login/rc/accesstoken",
  "POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/createManualAgentCall",
  "GET /voice/api/v1/admin/accounts/{accountId}/activeCalls/list",
  "GET /voice/api/v1/admin/accounts/{accountId}/activeCalls/prerouteChecks/checkQueueStatus",
  "GET /voice/api/v1/admin/accounts/{accountId}/activeCalls/prerouteChecks/checkQueueThreshold",
  "POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/addSessionToCall",
  "POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/dispositionCall",
  "POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/hangupCall",
  "POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/hangupSession",
  "POST /voice/api/v1/admin/accounts/{accountId}/activeCalls/{uii}/toggleCallRecording",
  "GET /voice/api/v1/admin/auditLogs/auditable",
  "PUT /voice/api/v1/admin/auditLogs/search",
  "GET /voice/api/v1/admin/accounts/{accountId}/agentGroups",
  "POST /voice/api/v1/admin/accounts/{accountId}/agentGroups",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents",
  "POST /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents",
  "PUT /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents/{agentId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents/{agentId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/agents/{agentId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/agentGroups/{agentGroupId}/gateGroups/{gateGroupId}/gates/{gateId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/campaignLeads/actions",
  "POST /voice/api/v1/admin/accounts/{accountId}/campaignLeads/leadSearch",
  "POST /voice/api/v1/admin/accounts/{accountId}/campaignLeads/leadSearchByPhoneList",
  "GET /voice/api/v1/admin/accounts/{accountId}/campaignLeads/leadStates",
  "GET /voice/api/v1/admin/accounts/{accountId}/campaignLeads/systemDispositions",
  "PATCH /voice/api/v1/admin/accounts/{accountId}/campaignLeads/{leadId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/campaignLeads/{leadId}",
  "POST /voice/api/v1/admin/accounts/{accountId}/campaigns/{campaignId}/leadLoader/direct",
  "POST /voice/api/v1/admin/accounts/{accountId}/campaigns/{campaignId}/leadLoader/preview",
  "POST /voice/api/v1/admin/accounts/{accountId}/campaigns/{campaignId}/leadLoader/process",
  "GET /voice/api/v1/admin/accounts/{accountId}/countries/available",
  "GET /voice/api/v1/admin/accounts/{accountId}/dialGroups",
  "POST /voice/api/v1/admin/accounts/{accountId}/dialGroups",
  "GET /voice/api/v1/admin/accounts/{accountId}/dialGroups/withChildren",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/assignAgents",
  "GET /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/assignedAgents",
  "GET /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns",
  "POST /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}",
  "POST /voice/api/v1/admin/accounts/{accountId}/dialGroups/{dialGroupId}/campaigns/{campaignId}/clearCache",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/withChildren",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/withChildren/additionalData",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/assignAgents",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/assignGateToPriorityGroup",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/assignedAgents",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/clone",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions/{gateDispositionId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions/{gateDispositionId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/dispositions/{gateDispositionId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateAgentAccessLogin",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents/{dtmfEventId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents/{dtmfEventId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/gateQueueEvents/{eventId}/gateQueueDtmfEvents/{dtmfEventId}",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/moveToGroup",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries/{entryId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/phoneBookEntries/{entryId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts/{requeueShortcutId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts/{requeueShortcutId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/requeueShortcuts/{requeueShortcutId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides/{scheduleOverrideId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/scheduleOverrides/{scheduleOverrideId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/setIsActive",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/specialAnis/upload",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/gates/{gateId}/unassignAgent/{agentId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills",
  "POST /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills",
  "DELETE /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills/{skillId}",
  "GET /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills/{skillId}",
  "PUT /voice/api/v1/admin/accounts/{accountId}/gateGroups/{gateGroupId}/skills/{skillId}",
  "GET /voice/api/v1/admin/reports/{reportType}",
  "GET /voice/api/v1/admin/token",
  "POST /voice/api/v1/admin/token",
  "DELETE /voice/api/v1/admin/token/{token}",
  "GET /voice/api/v1/admin/users",
  "POST /voice/api/v1/admin/users",
  "POST /voice/api/v1/auth/login",
  "GET /voice/api/integration/v1/admin/users/{mainAccountId}",
  "GET /voice/api/integration/v1/admin/accounts/{mainAccountId}/subaccounts",
  "GET /voice/api/integration/v1/admin/accounts/{subAccountId}/agentGroups/{agentGroupId}/agents",
  "GET /voice/api/integration/v1/admin/accounts/{subAccountId}/agentGroups",
  "GET /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/recordings/dialogs/{dialogId}/segments/{segmentId}",
  "POST /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/interaction-metadata",
  "GET /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/transcripts/dialogs/{dialogId}/segments/{segmentId}",
  "GET /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/queue-groups",
  "GET /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/queue-groups/{queueGroupId}/with-agents",
  "POST /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/agg-queue-stats",
  "POST /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/agg-agent-extended-stats",
  "POST /voice/api/cx/integration/v1/accounts/{rcAccountId}/sub-accounts/{subAccountId}/agg-agent-stats",
  "PUT /v1/admin/utilities/tnManager/updateCustomerDnisBulk",
  "POST /v1/admin/utilities/tnManager/searchDnis",
  "PUT /v1/admin/utilities/tnManager/updateBulkDnisPool",
  "POST /v1/admin/utilities/tnManager/uploadDnisPool",
  "PUT /platform/api/media/product",
  "POST /platform/api/media/product",
  "GET /platform/api/media/product/account/{subAccountId}/type/{productTypeString}/id/{productId}",
  "DELETE /platform/api/media/product/account/{subAccountId}/type/{productTypeString}/id/{productId}"
] as const;
// End hardened literal operation keys.

export type RingCentralVoiceApiOperationId = typeof RINGCENTRAL_VOICE_API_OPERATION_OPERATION_IDS[number];
export type RingCentralVoiceApiOperationUid = typeof RINGCENTRAL_VOICE_API_OPERATION_UIDS[number];
