import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";

export const whatsappMessagingProviderManifest = defineProviderPackage({
  id: "messaging.whatsapp",
  name: "WhatsApp Business Platform",
  packageName: "@cognidesk/integrations",
  provider: "whatsapp",
  category: "messaging",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is typed for selected WhatsApp Business Platform support workflows: Cloud API message sends, template payload construction, media upload/get/download helpers, phone-number readiness, business profile get/update, webhook challenge handling, and X-Hub-Signature-256 validation.",
      "This is not full WhatsApp Business Platform coverage; template CRUD/listing, Flows, commerce, Calling API, groups, phone-number registration and management, WABA account management, analytics, and broader Business Management APIs remain outside this adapter.",
    ],
    evidence: [
      { label: "WhatsApp Cloud API get started", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/get-started" },
      { label: "WhatsApp template fundamentals", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/templates/overview" },
      { label: "WhatsApp media", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/business-phone-numbers/media/" },
      { label: "WhatsApp business profiles", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/business-phone-numbers/business-profiles" },
      { label: "WhatsApp business phone numbers", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/business-phone-numbers/phone-numbers" },
      { label: "WhatsApp webhooks", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/webhooks/overview/" },
      { label: "WhatsApp permissions", url: "https://developers.facebook.com/documentation/business-messaging/whatsapp/permissions/" },
    ],
  },
  credentialRequirements: [
    {
      id: "whatsapp-access-token",
      label: "WhatsApp Business access token",
      description: "Server-side Meta Graph API access token for WhatsApp Business Platform calls.",
      scopes: ["whatsapp_business_messaging", "whatsapp_business_management"],
      required: true,
      metadata: { scopeKind: "provider-permission-labels" },
    },
    {
      id: "whatsapp-phone-number-id",
      label: "WhatsApp Business phone number ID",
      description: "Meta Graph API phone_number_id used for Cloud API message and media endpoints.",
      required: true,
    },
    {
      id: "whatsapp-app-secret",
      label: "Meta app secret",
      description: "Server-side app secret used to validate X-Hub-Signature-256 webhook deliveries.",
      required: true,
    },
    {
      id: "whatsapp-webhook-verify-token",
      label: "Webhook verify token",
      description: "SDK-user-owned token checked during Meta webhook endpoint verification.",
      required: false,
    },
    {
      id: "whatsapp-waba-webhook-subscription",
      label: "WhatsApp WABA messages webhook subscription",
      description: "SDK-user-confirmed Meta app subscription to the WhatsApp Business Account messages webhook field.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive WhatsApp webhooks",
      description: "Validates and parses WhatsApp Business Platform webhook payloads after the SDK user's Meta app is subscribed to the WABA messages webhook.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "whatsappWebhook", label: "WhatsApp Webhook" },
        { kind: "whatsappMessage", label: "WhatsApp Message" },
        { kind: "whatsappStatus", label: "WhatsApp Message Status" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send WhatsApp messages",
      description: "Sends WhatsApp Cloud API messages when SDK-user policy permits outbound contact: free-form service messages inside the customer service window or approved templates outside it.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "whatsappMessage", label: "WhatsApp Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Build WhatsApp message payloads",
      description: "Builds Cloud API message request payloads for SDK-user-configured approval workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "whatsappMessageDraft", label: "WhatsApp Message Draft" }],
      requiresCredential: false,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Use WhatsApp media",
      description: "Uploads media, fetches media metadata, and downloads media bytes through SDK-user-governed handling.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "whatsappMedia", label: "WhatsApp Media" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "attach",
      label: "Attach WhatsApp media",
      description: "References uploaded WhatsApp media IDs in outbound messages selected by SDK configuration.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "whatsappMedia", label: "WhatsApp Media" },
        { kind: "whatsappMessage", label: "WhatsApp Message" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read WhatsApp phone number and profile",
      description: "Reads WhatsApp Business phone-number readiness and business profile resources for Studio-visible configuration and support diagnostics.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "whatsappPhoneNumber", label: "WhatsApp Business Phone Number" },
        { kind: "whatsappBusinessProfile", label: "WhatsApp Business Profile" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update WhatsApp business profile",
      description: "Updates WhatsApp Business profile fields when SDK-user configuration permits profile changes.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "whatsappBusinessProfile", label: "WhatsApp Business Profile" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "whatsapp.webhook-signature",
      label: "Validate WhatsApp webhook signatures",
      description: "Validates Meta X-Hub-Signature-256 webhook signatures with the SDK user's app secret.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "whatsappSignedWebhook", label: "WhatsApp Signed Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "WhatsApp messages, contact identifiers, phone numbers, profile names, media metadata, message statuses, and webhook payloads can contain customer data.",
    "Meta access tokens, app secrets, and webhook verify tokens stay server-side and are represented in Studio only as credential readiness.",
  ],
  limitations: [
    "Available operations depend on the SDK user's Meta app, WhatsApp Business Account, phone number registration, WABA messages webhook subscription, access token scopes, business verification, templates, quality limits, and messaging windows.",
    "Free-form WhatsApp service messages are for the customer service window; SDK users must select approved templates for outbound contact outside that window.",
    "Opt-in, outbound-contact policy, template selection, human escalation, media retention, redaction, and deletion behavior are SDK-user configuration.",
    "This package provides transport helpers and does not choose default automation, promotional messaging, consent, retry, or rate-limit policies.",
  ],
  metadata: {
    channelCoverage: {
      cloudApiMessages: "typed-send",
      templatePayloads: "typed-build-only",
      media: "typed-upload-get-download",
      phoneNumberReadiness: "typed-read",
      businessProfile: "typed-read-update",
      webhooks: "typed-challenge-verify-parse",
      templateCrud: "provider-supported-not-typed",
      flowsCommerceCallingGroups: "provider-supported-not-typed",
    },
    apiCoverage: {
      checkedAt: "2026-06-18",
      operationCatalog: "docs/provider-coverage/whatsapp-business-messaging-openapi-v23-selected-api-2026-06-18.operations.json",
      sourceSpec: "https://raw.githubusercontent.com/facebook/openapi/main/business-messaging-api_v23.0.yaml",
      generatedFromOfficialSpec: true,
      sourcePathCount: 78,
      sourceOperationCount: 113,
      selectedOperationCount: 7,
      implementedOperationCount: 7,
      fullProviderApi: false,
      fullMetaGraphCoverage: false,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
