import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

const ZOOM_MEETINGS_API_SPEC_VERSION = "2";
const ZOOM_MEETINGS_API_PATH_COUNT = 129;
const ZOOM_MEETINGS_API_OPERATION_COUNT = 184;
const ZOOM_MEETINGS_API_GENERATED_FUNCTION_COUNT = 184;
const ZOOM_RIVET_MEETINGS_SDK_OPERATION_COUNT = 182;
const ZOOM_RIVET_MEETINGS_REST_EXCEPTION_OPERATION_UIDS = [
  "GET /report/disclaimer",
  "GET /report/remote_support",
] as const;

export const zoomVideoProviderManifest = defineProviderPackage({
  id: "video.zoom",
  name: "Zoom Meetings",
  packageName: "@cognidesk/integration-video-zoom",
  provider: "zoom",
  category: "video",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Zoom's official Meetings API Hub OpenAPI spec. Runtime uses Zoom's official @zoom/rivet Meetings SDK for mapped SDK operations when accessToken/getAccessToken/account OAuth credentials are provided.",
      "Typed convenience helpers remain available for meetings create/list/read/update/delete through @zoom/rivet, current-user readiness through @zoom/rivet/users, webhook URL-validation handling, and x-zm-signature verification; providerClient remains available as a host override.",
      "The built-in typed REST adapter remains only for explicit REST exceptions: @zoom/rivet 0.4.0 does not expose GET /report/disclaimer or GET /report/remote_support, and low-level fetch/signal/retry/oauthBaseUrl options intentionally request the package-owned REST transport.",
      "This package is a generated Zoom Meetings API domain slice, not full Zoom platform coverage. Zoom Phone, Contact Center, Team Chat, Rooms, Marketplace app management outside the Meetings API Hub, account administration beyond this spec, and full webhook/event catalogs remain separate Zoom surfaces.",
      "The SDK user owns OAuth scopes, host delegation, account plan/admin settings, meeting lifecycle policy, recording/transcript consent, retention, deletion, and participant disclosure decisions.",
    ],
    evidence: [
      { label: "Zoom Rivet for JavaScript", url: "https://developers.zoom.us/docs/rivet/javascript/" },
      { label: "Zoom Rivet JavaScript repository", url: "https://github.com/zoom/rivet-javascript" },
      { label: "Zoom Meetings API Hub OpenAPI", url: "https://developers.zoom.us/api-hub/meetings/methods/endpoints.json" },
      { label: "Zoom Meetings API reference", url: "https://developers.zoom.us/docs/api/meetings/" },
      { label: "Zoom webhooks reference", url: "https://developers.zoom.us/docs/api/rest/webhook-reference/" },
      { label: "Zoom webhook validation", url: "https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint" },
    ],
  },
  credentialRequirements: [
    {
      id: "zoom-video-provider-client",
      label: "Optional Zoom video provider client override",
      description: "Optional host-managed Zoom provider client backed by an approved SDK, provider package, or host-owned transport when overriding the built-in @zoom/rivet runtime.",
      required: false,
      metadata: {
        injectionInterface: "ZoomVideoProviderClient",
        credentialOwnership: "sdk-user-or-host-managed",
        defaultClientPolicy: "official-rivet-sdk-with-reviewed-rest-exceptions",
      },
    },
    {
      id: "zoom-oauth-access-token",
      label: "Zoom OAuth access token",
      description: "Server-side OAuth access token used by @zoom/rivet, the reviewed REST exceptions, or a host provider client for meeting and user endpoints.",
      scopes: [
        "meeting:write",
        "meeting:read",
        "user:read",
        "meeting:write:meeting",
        "meeting:read:list_meetings",
        "meeting:read:meeting",
        "meeting:update:meeting",
        "meeting:delete:meeting",
        "user:read:user",
      ],
      required: true,
      metadata: {
        scopeKind: "provider-oauth-scopes",
        credentialOwnership: "sdk-user-or-host-managed",
      },
    },
    {
      id: "zoom-webhook-secret-token",
      label: "Zoom webhook secret token",
      description: "Server-side secret token used to validate Zoom webhook request signatures.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "schedule",
      label: "Schedule Zoom meetings",
      description: "Creates Zoom meetings through SDK-user-selected scheduling or escalation workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "zoomMeeting", label: "Zoom Meeting" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Zoom meetings",
      description: "Creates Zoom meeting resources with SDK-user-supplied topic, timing, recurrence, and settings.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "zoomMeeting", label: "Zoom Meeting" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Zoom meetings",
      description: "Lists Zoom meetings and reads meeting details by meeting ID.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "zoomMeeting", label: "Zoom Meeting" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "delete-provider-object",
      label: "Delete Zoom meetings",
      description: "Deletes Zoom meetings when SDK-user lifecycle or retention policy permits deletion.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "zoomMeeting", label: "Zoom Meeting" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Zoom meetings",
      description: "Updates Zoom meeting fields, recurrence, tracking fields, or settings when SDK-user policy permits mutation.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "zoomMeeting", label: "Zoom Meeting" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "receive",
      label: "Receive Zoom webhooks",
      description: "Validates and parses Zoom webhook payloads for SDK-user-owned meeting lifecycle workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "zoomWebhookEvent", label: "Zoom Webhook Event" },
        { kind: "zoomMeeting", label: "Zoom Meeting" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "zoom.request-signature",
      label: "Validate Zoom webhook signatures",
      description: "Validates Zoom x-zm-signature and x-zm-request-timestamp values and supports endpoint URL validation challenges.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "zoomSignedRequest", label: "Zoom Signed Request" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "video.meeting.create",
      capability: "create-provider-object",
      providerObject: "zoomMeeting",
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "video.meeting.list",
      capability: "read-provider-object",
      providerObject: "zoomMeeting",
      exposesSensitiveData: true,
    },
    {
      alias: "video.meeting.read",
      capability: "read-provider-object",
      providerObject: "zoomMeeting",
      exposesSensitiveData: true,
    },
    {
      alias: "video.meeting.update",
      capability: "update-provider-object",
      providerObject: "zoomMeeting",
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "video.meeting.delete",
      capability: "delete-provider-object",
      providerObject: "zoomMeeting",
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "video.user.current.read",
      capability: "read-provider-object",
      providerObject: "zoomUser",
      exposesSensitiveData: true,
    },
    {
      alias: "zoom.meetings.request",
      capability: "read-provider-object",
      providerObject: "zoomMeetingsApiOperation",
      extension: true,
      metadata: {
        supportSliceEscapeHatch: true,
        execution: "official-rivet-sdk-or-reviewed-rest-exception-or-host-provider-client",
      },
    },
    {
      alias: "zoom.webhook.parse",
      capability: "receive",
      providerObject: "zoomWebhookEvent",
      extension: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Zoom meetings and webhooks can contain participant identifiers, host details, invite links, meeting metadata, chat-capable workflow context, and recording-related event metadata.",
    "Zoom OAuth access tokens and webhook secret tokens stay server-side and are represented in Studio only as credential readiness.",
    "User consent, meeting disclosure, recording enablement, transcript use, retention, and deletion are owned by the SDK user's Zoom account configuration and application policy.",
  ],
  limitations: [
    "Runtime provider API calls use Zoom's official @zoom/rivet SDK when OAuth credentials are supplied, except for documented REST exceptions or explicit low-level REST transport options.",
    "Missing OAuth credentials and missing providerClient fail closed; SDK users own token lifecycle, retry policy, and account authorization policy.",
    "Available meeting operations depend on the SDK user's Zoom OAuth scopes, account plan, account-level settings, admin policy, and delegated host permissions.",
    "This package does not choose whether a video workflow is inbound, outbound, customer-facing, internal, recorded, retained, or escalated; those decisions remain SDK-user configuration.",
    "Live meeting media transport, captions, cloud recording retrieval, and telephony dial-out are outside this package's delegated SDK/provider-client and webhook foundation.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    channelCoverage: {
      meetingsApiHub: "generated-constrained-support-slice",
      meetings: "typed-create-list-read-update-delete",
      meetingsRecordingsRegistrantsReportsDevicesTspWebinars: "generated-full-surface-where-present-in-meetings-api-hub",
      currentUser: "typed-read",
      webhooks: "typed-validate-parse",
      webhookUrlValidation: "typed-response",
      zoomPhoneContactCenterTeamChatRoomsCalendar: "provider-supported-not-typed-separate-surface",
    },
    generatedProviderSliceVerification: {
      provider: "zoom-meetings-api-hub",
      apiVersion: ZOOM_MEETINGS_API_SPEC_VERSION,
      verifiedAt: "2026-06-21",
      sourceChecksumSha256: "07acb50f2a3f070b161ed57fbd9ca9ae83db42a6c1fa538f36b7e1c8300b6b06",
      coverageArtifact: "docs/provider-coverage/zoom-meetings-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/zoom-meetings-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/zoom-meetings-api-2026-06-18.functions.json",
      operationCatalogChecksumSha256: "d32cdc0636126fef0491cfd13f95219359be167d339a57b4b4322f7be1146392",
      functionCatalogChecksumSha256: "8934aa5f43e3a15d5a087dcf663854d41bb013d38aee8d65171b967bcc43202b",
      documentedPathCount: ZOOM_MEETINGS_API_PATH_COUNT,
      documentedOperationCount: ZOOM_MEETINGS_API_OPERATION_COUNT,
      implementedOperationCount: ZOOM_MEETINGS_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: ZOOM_MEETINGS_API_GENERATED_FUNCTION_COUNT,
      allowlist: [
        "Archiving",
        "Cloud Recording",
        "Devices",
        "H323 Devices",
        "In-Meeting Apps",
        "In-Meeting Features",
        "Invitation & Registration",
        "Live streaming",
        "Meetings",
        "PAC",
        "Polls",
        "Reports",
        "SIP Phone",
        "Summaries",
        "Surveys",
        "Templates",
        "Tracking Field",
        "TSP",
        "Webinars",
      ],
    },
    implementationStrategy: "official-sdk-with-reviewed-rest-exceptions",
    implementation: {
      strategy: "official-sdk-with-reviewed-rest-exceptions",
      officialSdk: {
        packageName: "@zoom/rivet",
        checkedVersion: "0.4.0",
        meetingsModule: "@zoom/rivet/meetings",
        usersModule: "@zoom/rivet/users",
        mappedMeetingsOperationCount: ZOOM_RIVET_MEETINGS_SDK_OPERATION_COUNT,
      },
      providerClientInterface: "ZoomVideoProviderClient",
      defaultClient: "official-zoom-rivet-sdk",
      restAdapterException: {
        adapterKind: "reviewed-rest-exception",
        operationUids: ZOOM_RIVET_MEETINGS_REST_EXCEPTION_OPERATION_UIDS,
        transportOptions: ["fetch", "signal", "retry", "oauthBaseUrl"],
      },
      failClosedWithoutProviderClientOrOAuthCredentials: true,
      failClosedWithoutOAuthCredentials: true,
      manifestImport: "no-client-initialization",
      generatedMeetingsApiRuntime: "zoom-rivet-operation-dispatch-with-reviewed-rest-exception-fallback-and-host-provider-client-override",
    },
    providerClient: {
      interface: "ZoomVideoProviderClient",
      injectionPolicy: "optional-runtime-override",
      importPolicy: "optional-host-override",
      defaultClient: "official-zoom-rivet-sdk",
    },
    sdkViability: {
      decision: "official-provider-sdk-selected",
      checkedAt: "2026-06-25",
      selectedSdkPackage: {
        packageName: "@zoom/rivet",
        checkedVersion: "0.4.0",
        reason: "Official Zoom Node.js toolkit with Meetings API wrappers, server-to-server OAuth support, and webhook/event tooling.",
        source: "https://developers.zoom.us/docs/rivet/javascript/",
      },
      rejectedSdkPackages: [
        {
          packageName: "@zoom/meetingsdk",
          reason: "Official browser Meeting SDK for embedding/joining meetings, not a server REST API client.",
        },
        {
          packageName: "@zoom/videosdk",
          reason: "Official browser Video SDK for custom video experiences, not the Zoom Meetings REST API.",
        },
        {
          packageName: "@zoom/rtms",
          reason: "Official Node real-time media streams SDK, not scheduling/resource REST management.",
        },
      ],
    },
    providerRestAdapterException: {
      status: "accepted",
      reviewedAt: "2026-06-25",
      adapterKind: "reviewed-rest-exception",
      reason: "@zoom/rivet 0.4.0 covers 182 of this package's 184 generated Zoom Meetings API operations; the package-owned typed REST adapter is retained for the two missing report endpoints and explicit low-level transport options the SDK cannot honor.",
      operationUids: ZOOM_RIVET_MEETINGS_REST_EXCEPTION_OPERATION_UIDS,
      allowedDefaultRuntime: "official-zoom-rivet-sdk",
      fallbackRuntime: "built-in-typed-rest-adapter",
      hostSdkPath: "ZoomVideoProviderClient",
      failClosed: true,
      guardrails: [
        "Keep generated operation IDs resolved against the local Zoom Meetings API catalog before SDK dispatch or REST fallback.",
        "Use @zoom/rivet for mapped operations whenever fetch/signal/retry/oauthBaseUrl are not explicitly requested.",
        "Only use the REST adapter for documented @zoom/rivet gaps, per-request headers, or transport options the SDK cannot represent.",
      ],
    },
  },
});
