// Generated from the Zoom Meetings API Hub OpenAPI spec (https://developers.zoom.us/api-hub/meetings/methods/endpoints.json).
// Do not edit by hand; regenerate from the Zoom Meetings API Hub OpenAPI source after checking upstream docs.

export const ZOOM_MEETINGS_API_GENERATED_AT = "2026-06-18";
export const ZOOM_MEETINGS_API_SPEC_SOURCE = "https://developers.zoom.us/api-hub/meetings/methods/endpoints.json";
export const ZOOM_MEETINGS_API_DOCS_SOURCE = "https://developers.zoom.us/docs/api/meetings/";
export const ZOOM_MEETINGS_API_SPEC_VERSION = "2";
export const ZOOM_MEETINGS_API_OPENAPI_VERSION = "3.0.0";
export const ZOOM_MEETINGS_API_PATH_COUNT = 129;
export const ZOOM_MEETINGS_API_OPERATION_COUNT = 184;

export interface ZoomMeetingsApiOperation {
  uid: string;
  operationId: string;
  functionName: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  summary: string;
  tags: readonly string[];
}

export const ZOOM_MEETINGS_API_OPERATIONS = JSON.parse("[{\"uid\":\"GET /archive_files\",\"operationId\":\"listArchivedFiles\",\"functionName\":\"ListArchivedFiles\",\"method\":\"GET\",\"path\":\"/archive_files\",\"summary\":\"List archived files\",\"tags\":[\"Archiving\"]},{\"uid\":\"GET /archive_files/statistics\",\"operationId\":\"getArchivedFileStatistics\",\"functionName\":\"GetArchivedFileStatistics\",\"method\":\"GET\",\"path\":\"/archive_files/statistics\",\"summary\":\"Get archived file statistics\",\"tags\":[\"Archiving\"]},{\"uid\":\"PATCH /archive_files/{fileId}\",\"operationId\":\"updateArchivedFile\",\"functionName\":\"UpdateArchivedFile\",\"method\":\"PATCH\",\"path\":\"/archive_files/{fileId}\",\"summary\":\"Update an archived file's auto-delete status\",\"tags\":[\"Archiving\"]},{\"uid\":\"GET /meetings/{meetingId}/jointoken/local_archiving\",\"operationId\":\"meetingLocalArchivingArchiveToken\",\"functionName\":\"MeetingLocalArchivingArchiveToken\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/jointoken/local_archiving\",\"summary\":\"Get a meeting's archive token for local archiving\",\"tags\":[\"Archiving\"]},{\"uid\":\"GET /past_meetings/{meetingUUID}/archive_files\",\"operationId\":\"getArchivedFiles\",\"functionName\":\"GetArchivedFiles\",\"method\":\"GET\",\"path\":\"/past_meetings/{meetingUUID}/archive_files\",\"summary\":\"Get a meeting's archived files\",\"tags\":[\"Archiving\"]},{\"uid\":\"DELETE /past_meetings/{meetingUUID}/archive_files\",\"operationId\":\"deleteArchivedFiles\",\"functionName\":\"DeleteArchivedFiles\",\"method\":\"DELETE\",\"path\":\"/past_meetings/{meetingUUID}/archive_files\",\"summary\":\"Delete a meeting's archived files\",\"tags\":[\"Archiving\"]},{\"uid\":\"GET /meetings/{meetingId}/recordings\",\"operationId\":\"recordingGet\",\"functionName\":\"RecordingGet\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/recordings\",\"summary\":\"Get meeting recordings\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"DELETE /meetings/{meetingId}/recordings\",\"operationId\":\"recordingDelete\",\"functionName\":\"RecordingDelete\",\"method\":\"DELETE\",\"path\":\"/meetings/{meetingId}/recordings\",\"summary\":\"Delete meeting or webinar recordings\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"GET /meetings/{meetingId}/recordings/analytics_details\",\"operationId\":\"analytics_details\",\"functionName\":\"AnalyticsDetails\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/recordings/analytics_details\",\"summary\":\"Get a meeting or webinar recording's analytics details\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"GET /meetings/{meetingId}/recordings/analytics_summary\",\"operationId\":\"analytics_summary\",\"functionName\":\"AnalyticsSummary\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/recordings/analytics_summary\",\"summary\":\"Get a meeting or webinar recording's analytics summary\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"GET /meetings/{meetingId}/recordings/registrants\",\"operationId\":\"meetingRecordingRegistrants\",\"functionName\":\"MeetingRecordingRegistrants\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/recordings/registrants\",\"summary\":\"List recording registrants\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"POST /meetings/{meetingId}/recordings/registrants\",\"operationId\":\"meetingRecordingRegistrantCreate\",\"functionName\":\"MeetingRecordingRegistrantCreate\",\"method\":\"POST\",\"path\":\"/meetings/{meetingId}/recordings/registrants\",\"summary\":\"Create a recording registrant\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"GET /meetings/{meetingId}/recordings/registrants/questions\",\"operationId\":\"recordingRegistrantsQuestionsGet\",\"functionName\":\"RecordingRegistrantsQuestionsGet\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/recordings/registrants/questions\",\"summary\":\"Get registration questions\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"PATCH /meetings/{meetingId}/recordings/registrants/questions\",\"operationId\":\"recordingRegistrantQuestionUpdate\",\"functionName\":\"RecordingRegistrantQuestionUpdate\",\"method\":\"PATCH\",\"path\":\"/meetings/{meetingId}/recordings/registrants/questions\",\"summary\":\"Update registration questions\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"PUT /meetings/{meetingId}/recordings/registrants/status\",\"operationId\":\"meetingRecordingRegistrantStatus\",\"functionName\":\"MeetingRecordingRegistrantStatus\",\"method\":\"PUT\",\"path\":\"/meetings/{meetingId}/recordings/registrants/status\",\"summary\":\"Update a registrant's status\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"GET /meetings/{meetingId}/recordings/settings\",\"operationId\":\"recordingSettingUpdate\",\"functionName\":\"RecordingSettingUpdate\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/recordings/settings\",\"summary\":\"Get meeting recording settings\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"PATCH /meetings/{meetingId}/recordings/settings\",\"operationId\":\"recordingSettingsUpdate\",\"functionName\":\"RecordingSettingsUpdate\",\"method\":\"PATCH\",\"path\":\"/meetings/{meetingId}/recordings/settings\",\"summary\":\"Update meeting recording settings\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"DELETE /meetings/{meetingId}/recordings/{recordingId}\",\"operationId\":\"recordingDeleteOne\",\"functionName\":\"RecordingDeleteOne\",\"method\":\"DELETE\",\"path\":\"/meetings/{meetingId}/recordings/{recordingId}\",\"summary\":\"Delete a recording file for a meeting or webinar\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"PUT /meetings/{meetingId}/recordings/{recordingId}/status\",\"operationId\":\"recordingStatusUpdateOne\",\"functionName\":\"RecordingStatusUpdateOne\",\"method\":\"PUT\",\"path\":\"/meetings/{meetingId}/recordings/{recordingId}/status\",\"summary\":\"Recover a single recording\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"GET /meetings/{meetingId}/transcript\",\"operationId\":\"GetMeetingTranscript\",\"functionName\":\"GetMeetingTranscript\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/transcript\",\"summary\":\"Get a meeting transcript\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"DELETE /meetings/{meetingId}/transcript\",\"operationId\":\"DeleteMeetingTranscript\",\"functionName\":\"DeleteMeetingTranscript\",\"method\":\"DELETE\",\"path\":\"/meetings/{meetingId}/transcript\",\"summary\":\"Delete a meeting or webinar transcript\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"PUT /meetings/{meetingUUID}/recordings/status\",\"operationId\":\"recordingStatusUpdate\",\"functionName\":\"RecordingStatusUpdate\",\"method\":\"PUT\",\"path\":\"/meetings/{meetingUUID}/recordings/status\",\"summary\":\"Recover meeting recordings\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"GET /users/{userId}/recordings\",\"operationId\":\"recordingsList\",\"functionName\":\"RecordingsList\",\"method\":\"GET\",\"path\":\"/users/{userId}/recordings\",\"summary\":\"List all recordings\",\"tags\":[\"Cloud Recording\"]},{\"uid\":\"GET /devices\",\"operationId\":\"listDevices\",\"functionName\":\"ListDevices\",\"method\":\"GET\",\"path\":\"/devices\",\"summary\":\"List devices\",\"tags\":[\"Devices\"]},{\"uid\":\"POST /devices\",\"operationId\":\"addDevice\",\"functionName\":\"AddDevice\",\"method\":\"POST\",\"path\":\"/devices\",\"summary\":\"Add a new device\",\"tags\":[\"Devices\"]},{\"uid\":\"GET /devices/groups\",\"operationId\":\"Getzdmgroupinfo\",\"functionName\":\"Getzdmgroupinfo\",\"method\":\"GET\",\"path\":\"/devices/groups\",\"summary\":\"Get ZDM group info\",\"tags\":[\"Devices\"]},{\"uid\":\"POST /devices/zpa/assignment\",\"operationId\":\"Assigndevicetoauser/commonarea\",\"functionName\":\"AssigndevicetoauserCommonarea\",\"method\":\"POST\",\"path\":\"/devices/zpa/assignment\",\"summary\":\"Assign a device to a user or commonarea\",\"tags\":[\"Devices\"]},{\"uid\":\"GET /devices/zpa/settings\",\"operationId\":\"GetZpaDeviceListProfileSettingOfaUser\",\"functionName\":\"GetZpaDeviceListProfileSettingOfaUser\",\"method\":\"GET\",\"path\":\"/devices/zpa/settings\",\"summary\":\"Get Zoom Phone Appliance settings by user ID\",\"tags\":[\"Devices\"]},{\"uid\":\"POST /devices/zpa/upgrade\",\"operationId\":\"UpgradeZpas/app\",\"functionName\":\"UpgradeZpasApp\",\"method\":\"POST\",\"path\":\"/devices/zpa/upgrade\",\"summary\":\"Upgrade ZPA firmware or app\",\"tags\":[\"Devices\"]},{\"uid\":\"DELETE /devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}\",\"operationId\":\"DeleteZpaDeviceByVendorAndMacAddress\",\"functionName\":\"DeleteZpaDeviceByVendorAndMacAddress\",\"method\":\"DELETE\",\"path\":\"/devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}\",\"summary\":\"Delete ZPA device by vendor and mac address\",\"tags\":[\"Devices\"]},{\"uid\":\"GET /devices/zpa/zdm_groups/{zdmGroupId}/versions\",\"operationId\":\"GetZpaVersioninfo\",\"functionName\":\"GetZpaVersioninfo\",\"method\":\"GET\",\"path\":\"/devices/zpa/zdm_groups/{zdmGroupId}/versions\",\"summary\":\"Get ZPA version info\",\"tags\":[\"Devices\"]},{\"uid\":\"GET /devices/{deviceId}\",\"operationId\":\"getDevice\",\"functionName\":\"GetDevice\",\"method\":\"GET\",\"path\":\"/devices/{deviceId}\",\"summary\":\"Get device detail\",\"tags\":[\"Devices\"]},{\"uid\":\"DELETE /devices/{deviceId}\",\"operationId\":\"deleteDevice\",\"functionName\":\"DeleteDevice\",\"method\":\"DELETE\",\"path\":\"/devices/{deviceId}\",\"summary\":\"Delete device\",\"tags\":[\"Devices\"]},{\"uid\":\"PATCH /devices/{deviceId}\",\"operationId\":\"updateDevice\",\"functionName\":\"UpdateDevice\",\"method\":\"PATCH\",\"path\":\"/devices/{deviceId}\",\"summary\":\"Change device \",\"tags\":[\"Devices\"]},{\"uid\":\"PATCH /devices/{deviceId}/assign_group\",\"operationId\":\"assginGroup\",\"functionName\":\"AssginGroup\",\"method\":\"PATCH\",\"path\":\"/devices/{deviceId}/assign_group\",\"summary\":\"Assign a device to a group\",\"tags\":[\"Devices\"]},{\"uid\":\"PATCH /devices/{deviceId}/assignment\",\"operationId\":\"changeDeviceAssociation\",\"functionName\":\"ChangeDeviceAssociation\",\"method\":\"PATCH\",\"path\":\"/devices/{deviceId}/assignment\",\"summary\":\"Change device association\",\"tags\":[\"Devices\"]},{\"uid\":\"GET /h323/devices\",\"operationId\":\"deviceList\",\"functionName\":\"DeviceList\",\"method\":\"GET\",\"path\":\"/h323/devices\",\"summary\":\"List H.323/SIP devices\",\"tags\":[\"H323 Devices\"]},{\"uid\":\"POST /h323/devices\",\"operationId\":\"deviceCreate\",\"functionName\":\"DeviceCreate\",\"method\":\"POST\",\"path\":\"/h323/devices\",\"summary\":\"Create a H.323/SIP device\",\"tags\":[\"H323 Devices\"]},{\"uid\":\"DELETE /h323/devices/{deviceId}\",\"operationId\":\"deviceDelete\",\"functionName\":\"DeviceDelete\",\"method\":\"DELETE\",\"path\":\"/h323/devices/{deviceId}\",\"summary\":\"Delete a H.323/SIP device\",\"tags\":[\"H323 Devices\"]},{\"uid\":\"PATCH /h323/devices/{deviceId}\",\"operationId\":\"deviceUpdate\",\"functionName\":\"DeviceUpdate\",\"method\":\"PATCH\",\"path\":\"/h323/devices/{deviceId}\",\"summary\":\"Update a H.323/SIP device\",\"tags\":[\"H323 Devices\"]},{\"uid\":\"POST /meetings/{meetingId}/open_apps\",\"operationId\":\"meetingAppAdd\",\"functionName\":\"MeetingAppAdd\",\"method\":\"POST\",\"path\":\"/meetings/{meetingId}/open_apps\",\"summary\":\"Add a meeting app\",\"tags\":[\"In-Meeting Apps\"]},{\"uid\":\"DELETE /meetings/{meetingId}/open_apps\",\"operationId\":\"meetingAppDelete\",\"functionName\":\"MeetingAppDelete\",\"method\":\"DELETE\",\"path\":\"/meetings/{meetingId}/open_apps\",\"summary\":\"Delete a meeting app\",\"tags\":[\"In-Meeting Apps\"]},{\"uid\":\"DELETE /live_meetings/{meetingId}/chat/messages/{messageId}\",\"operationId\":\"deleteMeetingChatMessageById\",\"functionName\":\"DeleteMeetingChatMessageById\",\"method\":\"DELETE\",\"path\":\"/live_meetings/{meetingId}/chat/messages/{messageId}\",\"summary\":\"Delete a live meeting message\",\"tags\":[\"In-Meeting Features\"]},{\"uid\":\"PATCH /live_meetings/{meetingId}/chat/messages/{messageId}\",\"operationId\":\"updateMeetingChatMessageById\",\"functionName\":\"UpdateMeetingChatMessageById\",\"method\":\"PATCH\",\"path\":\"/live_meetings/{meetingId}/chat/messages/{messageId}\",\"summary\":\"Update a live meeting message\",\"tags\":[\"In-Meeting Features\"]},{\"uid\":\"PATCH /live_meetings/{meetingId}/events\",\"operationId\":\"inMeetingControl\",\"functionName\":\"InMeetingControl\",\"method\":\"PATCH\",\"path\":\"/live_meetings/{meetingId}/events\",\"summary\":\"In-meeting controls\",\"tags\":[\"In-Meeting Features\"]},{\"uid\":\"GET /meetings/{meetingId}/jointoken/local_recording\",\"operationId\":\"meetingLocalRecordingJoinToken\",\"functionName\":\"MeetingLocalRecordingJoinToken\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/jointoken/local_recording\",\"summary\":\"Get a meeting's join token for local recording\",\"tags\":[\"In-Meeting Features\"]},{\"uid\":\"GET /meetings/{meetingId}/token\",\"operationId\":\"meetingToken\",\"functionName\":\"MeetingToken\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/token\",\"summary\":\"Get meeting's token\",\"tags\":[\"In-Meeting Features\"]},{\"uid\":\"POST /meetings/{meetingId}/batch_registrants\",\"operationId\":\"addBatchRegistrants\",\"functionName\":\"AddBatchRegistrants\",\"method\":\"POST\",\"path\":\"/meetings/{meetingId}/batch_registrants\",\"summary\":\"Perform batch registration\",\"tags\":[\"Invitation & Registration\"]},{\"uid\":\"GET /meetings/{meetingId}/invitation\",\"operationId\":\"meetingInvitation\",\"functionName\":\"MeetingInvitation\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/invitation\",\"summary\":\"Get meeting invitation\",\"tags\":[\"Invitation & Registration\"]},{\"uid\":\"POST /meetings/{meetingId}/invite_links\",\"operationId\":\"meetingInviteLinksCreate\",\"functionName\":\"MeetingInviteLinksCreate\",\"method\":\"POST\",\"path\":\"/meetings/{meetingId}/invite_links\",\"summary\":\"Create a meeting's invite links\",\"tags\":[\"Invitation & Registration\"]},{\"uid\":\"GET /meetings/{meetingId}/registrants\",\"operationId\":\"meetingRegistrants\",\"functionName\":\"MeetingRegistrants\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/registrants\",\"summary\":\"List meeting registrants\",\"tags\":[\"Invitation & Registration\"]},{\"uid\":\"POST /meetings/{meetingId}/registrants\",\"operationId\":\"meetingRegistrantCreate\",\"functionName\":\"MeetingRegistrantCreate\",\"method\":\"POST\",\"path\":\"/meetings/{meetingId}/registrants\",\"summary\":\"Add a meeting registrant\",\"tags\":[\"Invitation & Registration\"]},{\"uid\":\"GET /meetings/{meetingId}/registrants/questions\",\"operationId\":\"meetingRegistrantsQuestionsGet\",\"functionName\":\"MeetingRegistrantsQuestionsGet\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/registrants/questions\",\"summary\":\"List registration questions \",\"tags\":[\"Invitation & Registration\"]},{\"uid\":\"PATCH /meetings/{meetingId}/registrants/questions\",\"operationId\":\"meetingRegistrantQuestionUpdate\",\"functionName\":\"MeetingRegistrantQuestionUpdate\",\"method\":\"PATCH\",\"path\":\"/meetings/{meetingId}/registrants/questions\",\"summary\":\"Update registration questions\",\"tags\":[\"Invitation & Registration\"]},{\"uid\":\"PUT /meetings/{meetingId}/registrants/status\",\"operationId\":\"meetingRegistrantStatus\",\"functionName\":\"MeetingRegistrantStatus\",\"method\":\"PUT\",\"path\":\"/meetings/{meetingId}/registrants/status\",\"summary\":\"Update registrant's status\",\"tags\":[\"Invitation & Registration\"]},{\"uid\":\"GET /meetings/{meetingId}/registrants/{registrantId}\",\"operationId\":\"meetingRegistrantGet\",\"functionName\":\"MeetingRegistrantGet\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/registrants/{registrantId}\",\"summary\":\"Get a meeting registrant\",\"tags\":[\"Invitation & Registration\"]},{\"uid\":\"DELETE /meetings/{meetingId}/registrants/{registrantId}\",\"operationId\":\"meetingregistrantdelete\",\"functionName\":\"Meetingregistrantdelete\",\"method\":\"DELETE\",\"path\":\"/meetings/{meetingId}/registrants/{registrantId}\",\"summary\":\"Delete a meeting registrant\",\"tags\":[\"Invitation & Registration\"]},{\"uid\":\"GET /meetings/{meetingId}/jointoken/live_streaming\",\"operationId\":\"meetingLiveStreamingJoinToken\",\"functionName\":\"MeetingLiveStreamingJoinToken\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/jointoken/live_streaming\",\"summary\":\"Get a meeting's join token for live streaming\",\"tags\":[\"Live streaming\"]},{\"uid\":\"GET /meetings/{meetingId}/livestream\",\"operationId\":\"getMeetingLiveStreamDetails\",\"functionName\":\"GetMeetingLiveStreamDetails\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/livestream\",\"summary\":\"Get livestream details\",\"tags\":[\"Live streaming\"]},{\"uid\":\"PATCH /meetings/{meetingId}/livestream\",\"operationId\":\"meetingLiveStreamUpdate\",\"functionName\":\"MeetingLiveStreamUpdate\",\"method\":\"PATCH\",\"path\":\"/meetings/{meetingId}/livestream\",\"summary\":\"Update a livestream\",\"tags\":[\"Live streaming\"]},{\"uid\":\"PATCH /meetings/{meetingId}/livestream/status\",\"operationId\":\"meetingLiveStreamStatusUpdate\",\"functionName\":\"MeetingLiveStreamStatusUpdate\",\"method\":\"PATCH\",\"path\":\"/meetings/{meetingId}/livestream/status\",\"summary\":\"Update livestream status\",\"tags\":[\"Live streaming\"]},{\"uid\":\"PATCH /live_meetings/{meetingId}/rtms_app/status\",\"operationId\":\"meetingRTMSStatusUpdate\",\"functionName\":\"MeetingRTMSStatusUpdate\",\"method\":\"PATCH\",\"path\":\"/live_meetings/{meetingId}/rtms_app/status\",\"summary\":\"Update participant Real-Time Media Streams (RTMS) app status\",\"tags\":[\"Meetings\"]},{\"uid\":\"GET /meetings/{meetingId}\",\"operationId\":\"meeting\",\"functionName\":\"Meeting\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}\",\"summary\":\"Get a meeting\",\"tags\":[\"Meetings\"]},{\"uid\":\"DELETE /meetings/{meetingId}\",\"operationId\":\"meetingDelete\",\"functionName\":\"MeetingDelete\",\"method\":\"DELETE\",\"path\":\"/meetings/{meetingId}\",\"summary\":\"Delete a meeting\",\"tags\":[\"Meetings\"]},{\"uid\":\"PATCH /meetings/{meetingId}\",\"operationId\":\"meetingUpdate\",\"functionName\":\"MeetingUpdate\",\"method\":\"PATCH\",\"path\":\"/meetings/{meetingId}\",\"summary\":\"Update a meeting\",\"tags\":[\"Meetings\"]},{\"uid\":\"POST /meetings/{meetingId}/sip_dialing\",\"operationId\":\"getSipDialingWithPasscode\",\"functionName\":\"GetSipDialingWithPasscode\",\"method\":\"POST\",\"path\":\"/meetings/{meetingId}/sip_dialing\",\"summary\":\"Get a meeting SIP URI with passcode\",\"tags\":[\"Meetings\"]},{\"uid\":\"PUT /meetings/{meetingId}/status\",\"operationId\":\"meetingStatus\",\"functionName\":\"MeetingStatus\",\"method\":\"PUT\",\"path\":\"/meetings/{meetingId}/status\",\"summary\":\"Update meeting status\",\"tags\":[\"Meetings\"]},{\"uid\":\"GET /past_meetings/{meetingId}\",\"operationId\":\"pastMeetingDetails\",\"functionName\":\"PastMeetingDetails\",\"method\":\"GET\",\"path\":\"/past_meetings/{meetingId}\",\"summary\":\"Get past meeting details\",\"tags\":[\"Meetings\"]},{\"uid\":\"GET /past_meetings/{meetingId}/instances\",\"operationId\":\"pastMeetings\",\"functionName\":\"PastMeetings\",\"method\":\"GET\",\"path\":\"/past_meetings/{meetingId}/instances\",\"summary\":\"List past meeting instances\",\"tags\":[\"Meetings\"]},{\"uid\":\"GET /past_meetings/{meetingId}/participants\",\"operationId\":\"pastMeetingParticipants\",\"functionName\":\"PastMeetingParticipants\",\"method\":\"GET\",\"path\":\"/past_meetings/{meetingId}/participants\",\"summary\":\"Get past meeting participants\",\"tags\":[\"Meetings\"]},{\"uid\":\"GET /past_meetings/{meetingId}/qa\",\"operationId\":\"listPastMeetingQA\",\"functionName\":\"ListPastMeetingQA\",\"method\":\"GET\",\"path\":\"/past_meetings/{meetingId}/qa\",\"summary\":\"List past meetings' Q&A\",\"tags\":[\"Meetings\"]},{\"uid\":\"GET /users/{userId}/meetings\",\"operationId\":\"meetings\",\"functionName\":\"Meetings\",\"method\":\"GET\",\"path\":\"/users/{userId}/meetings\",\"summary\":\"List meetings\",\"tags\":[\"Meetings\"]},{\"uid\":\"POST /users/{userId}/meetings\",\"operationId\":\"meetingCreate\",\"functionName\":\"MeetingCreate\",\"method\":\"POST\",\"path\":\"/users/{userId}/meetings\",\"summary\":\"Create a meeting\",\"tags\":[\"Meetings\"]},{\"uid\":\"GET /users/{userId}/upcoming_meetings\",\"operationId\":\"listUpcomingMeeting\",\"functionName\":\"ListUpcomingMeeting\",\"method\":\"GET\",\"path\":\"/users/{userId}/upcoming_meetings\",\"summary\":\"List upcoming meetings\",\"tags\":[\"Meetings\"]},{\"uid\":\"GET /users/{userId}/pac\",\"operationId\":\"userPACs\",\"functionName\":\"UserPACs\",\"method\":\"GET\",\"path\":\"/users/{userId}/pac\",\"summary\":\"List a user's PAC accounts\",\"tags\":[\"PAC\"]},{\"uid\":\"POST /meetings/{meetingId}/batch_polls\",\"operationId\":\"createBatchPolls\",\"functionName\":\"CreateBatchPolls\",\"method\":\"POST\",\"path\":\"/meetings/{meetingId}/batch_polls\",\"summary\":\"Perform batch poll creation\",\"tags\":[\"Polls\"]},{\"uid\":\"GET /meetings/{meetingId}/polls\",\"operationId\":\"meetingPolls\",\"functionName\":\"MeetingPolls\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/polls\",\"summary\":\"List meeting polls\",\"tags\":[\"Polls\"]},{\"uid\":\"POST /meetings/{meetingId}/polls\",\"operationId\":\"meetingPollCreate\",\"functionName\":\"MeetingPollCreate\",\"method\":\"POST\",\"path\":\"/meetings/{meetingId}/polls\",\"summary\":\"Create a meeting poll\",\"tags\":[\"Polls\"]},{\"uid\":\"GET /meetings/{meetingId}/polls/{pollId}\",\"operationId\":\"meetingPollGet\",\"functionName\":\"MeetingPollGet\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/polls/{pollId}\",\"summary\":\"Get a meeting poll\",\"tags\":[\"Polls\"]},{\"uid\":\"PUT /meetings/{meetingId}/polls/{pollId}\",\"operationId\":\"meetingPollUpdate\",\"functionName\":\"MeetingPollUpdate\",\"method\":\"PUT\",\"path\":\"/meetings/{meetingId}/polls/{pollId}\",\"summary\":\"Update a meeting poll\",\"tags\":[\"Polls\"]},{\"uid\":\"DELETE /meetings/{meetingId}/polls/{pollId}\",\"operationId\":\"meetingPollDelete\",\"functionName\":\"MeetingPollDelete\",\"method\":\"DELETE\",\"path\":\"/meetings/{meetingId}/polls/{pollId}\",\"summary\":\"Delete a meeting poll\",\"tags\":[\"Polls\"]},{\"uid\":\"GET /past_meetings/{meetingId}/polls\",\"operationId\":\"listPastMeetingPolls\",\"functionName\":\"ListPastMeetingPolls\",\"method\":\"GET\",\"path\":\"/past_meetings/{meetingId}/polls\",\"summary\":\"List past meeting's poll results\",\"tags\":[\"Polls\"]},{\"uid\":\"GET /report/activities\",\"operationId\":\"reportSignInSignOutActivities\",\"functionName\":\"ReportSignInSignOutActivities\",\"method\":\"GET\",\"path\":\"/report/activities\",\"summary\":\"Get sign In / sign out activity report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/billing\",\"operationId\":\"getBillingReport\",\"functionName\":\"GetBillingReport\",\"method\":\"GET\",\"path\":\"/report/billing\",\"summary\":\"Get billing reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/billing/invoices\",\"operationId\":\"getBillingInvoicesReports\",\"functionName\":\"GetBillingInvoicesReports\",\"method\":\"GET\",\"path\":\"/report/billing/invoices\",\"summary\":\"Get billing invoice reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/cloud_recording\",\"operationId\":\"reportCloudRecording\",\"functionName\":\"ReportCloudRecording\",\"method\":\"GET\",\"path\":\"/report/cloud_recording\",\"summary\":\"Get cloud recording usage report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/daily\",\"operationId\":\"reportDaily\",\"functionName\":\"ReportDaily\",\"method\":\"GET\",\"path\":\"/report/daily\",\"summary\":\"Get daily usage report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/disclaimer\",\"operationId\":\"Getdisclaimerreport\",\"functionName\":\"Getdisclaimerreport\",\"method\":\"GET\",\"path\":\"/report/disclaimer\",\"summary\":\"Get disclaimer report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/history_meetings\",\"operationId\":\"Gethistorymeetingandwebinarlist\",\"functionName\":\"Gethistorymeetingandwebinarlist\",\"method\":\"GET\",\"path\":\"/report/history_meetings\",\"summary\":\"Get history meeting and webinar list\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/meeting_activities\",\"operationId\":\"reportMeetingactivitylogs\",\"functionName\":\"ReportMeetingactivitylogs\",\"method\":\"GET\",\"path\":\"/report/meeting_activities\",\"summary\":\"Get a meeting activities report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/meetings/{meetingId}\",\"operationId\":\"reportMeetingDetails\",\"functionName\":\"ReportMeetingDetails\",\"method\":\"GET\",\"path\":\"/report/meetings/{meetingId}\",\"summary\":\"Get meeting detail reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/meetings/{meetingId}/participants\",\"operationId\":\"reportMeetingParticipants\",\"functionName\":\"ReportMeetingParticipants\",\"method\":\"GET\",\"path\":\"/report/meetings/{meetingId}/participants\",\"summary\":\"Get meeting participant reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/meetings/{meetingId}/polls\",\"operationId\":\"reportMeetingPolls\",\"functionName\":\"ReportMeetingPolls\",\"method\":\"GET\",\"path\":\"/report/meetings/{meetingId}/polls\",\"summary\":\"Get meeting poll reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/meetings/{meetingId}/qa\",\"operationId\":\"reportMeetingQA\",\"functionName\":\"ReportMeetingQA\",\"method\":\"GET\",\"path\":\"/report/meetings/{meetingId}/qa\",\"summary\":\"Get meeting Q&A report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/meetings/{meetingId}/survey\",\"operationId\":\"reportMeetingSurvey\",\"functionName\":\"ReportMeetingSurvey\",\"method\":\"GET\",\"path\":\"/report/meetings/{meetingId}/survey\",\"summary\":\"Get meeting survey report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/operationlogs\",\"operationId\":\"reportOperationLogs\",\"functionName\":\"ReportOperationLogs\",\"method\":\"GET\",\"path\":\"/report/operationlogs\",\"summary\":\"Get operation logs report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/remote_support\",\"operationId\":\"Getremotesupportreport\",\"functionName\":\"Getremotesupportreport\",\"method\":\"GET\",\"path\":\"/report/remote_support\",\"summary\":\"Get remote support report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/telephone\",\"operationId\":\"reportTelephone\",\"functionName\":\"ReportTelephone\",\"method\":\"GET\",\"path\":\"/report/telephone\",\"summary\":\"Get telephone reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/upcoming_events\",\"operationId\":\"reportUpcomingEvents\",\"functionName\":\"ReportUpcomingEvents\",\"method\":\"GET\",\"path\":\"/report/upcoming_events\",\"summary\":\"Get upcoming events report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/users\",\"operationId\":\"reportUsers\",\"functionName\":\"ReportUsers\",\"method\":\"GET\",\"path\":\"/report/users\",\"summary\":\"Get active or inactive host reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/users/{userId}/meetings\",\"operationId\":\"reportMeetings\",\"functionName\":\"ReportMeetings\",\"method\":\"GET\",\"path\":\"/report/users/{userId}/meetings\",\"summary\":\"Get meeting reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/webinars/{webinarId}\",\"operationId\":\"reportWebinarDetails\",\"functionName\":\"ReportWebinarDetails\",\"method\":\"GET\",\"path\":\"/report/webinars/{webinarId}\",\"summary\":\"Get webinar detail reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/webinars/{webinarId}/participants\",\"operationId\":\"reportWebinarParticipants\",\"functionName\":\"ReportWebinarParticipants\",\"method\":\"GET\",\"path\":\"/report/webinars/{webinarId}/participants\",\"summary\":\"Get webinar participant reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/webinars/{webinarId}/polls\",\"operationId\":\"reportWebinarPolls\",\"functionName\":\"ReportWebinarPolls\",\"method\":\"GET\",\"path\":\"/report/webinars/{webinarId}/polls\",\"summary\":\"Get webinar poll reports\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/webinars/{webinarId}/qa\",\"operationId\":\"reportWebinarQA\",\"functionName\":\"ReportWebinarQA\",\"method\":\"GET\",\"path\":\"/report/webinars/{webinarId}/qa\",\"summary\":\"Get webinar Q&A report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /report/webinars/{webinarId}/survey\",\"operationId\":\"reportWebinarSurvey\",\"functionName\":\"ReportWebinarSurvey\",\"method\":\"GET\",\"path\":\"/report/webinars/{webinarId}/survey\",\"summary\":\"Get webinar survey report\",\"tags\":[\"Reports\"]},{\"uid\":\"GET /sip_phones/phones\",\"operationId\":\"ListSIPPhonePhones\",\"functionName\":\"ListSIPPhonePhones\",\"method\":\"GET\",\"path\":\"/sip_phones/phones\",\"summary\":\"List SIP phones\",\"tags\":[\"SIP Phone\"]},{\"uid\":\"POST /sip_phones/phones\",\"operationId\":\"EnableSIPPhonePhones\",\"functionName\":\"EnableSIPPhonePhones\",\"method\":\"POST\",\"path\":\"/sip_phones/phones\",\"summary\":\"Enable SIP phone\",\"tags\":[\"SIP Phone\"]},{\"uid\":\"DELETE /sip_phones/phones/{phoneId}\",\"operationId\":\"deleteSIPPhonePhones\",\"functionName\":\"DeleteSIPPhonePhones\",\"method\":\"DELETE\",\"path\":\"/sip_phones/phones/{phoneId}\",\"summary\":\"Delete SIP phone\",\"tags\":[\"SIP Phone\"]},{\"uid\":\"PATCH /sip_phones/phones/{phoneId}\",\"operationId\":\"UpdateSIPPhonePhones\",\"functionName\":\"UpdateSIPPhonePhones\",\"method\":\"PATCH\",\"path\":\"/sip_phones/phones/{phoneId}\",\"summary\":\"Update SIP phone\",\"tags\":[\"SIP Phone\"]},{\"uid\":\"GET /meetings/meeting_summaries\",\"operationId\":\"Listmeetingsummaries\",\"functionName\":\"Listmeetingsummaries\",\"method\":\"GET\",\"path\":\"/meetings/meeting_summaries\",\"summary\":\"List an account's meeting or webinar summaries\",\"tags\":[\"Summaries\"]},{\"uid\":\"GET /meetings/{meetingId}/meeting_summary\",\"operationId\":\"Getameetingsummary\",\"functionName\":\"Getameetingsummary\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/meeting_summary\",\"summary\":\"Get a meeting or webinar summary\",\"tags\":[\"Summaries\"]},{\"uid\":\"DELETE /meetings/{meetingId}/meeting_summary\",\"operationId\":\"Deletemeetingorwebinarsummary\",\"functionName\":\"Deletemeetingorwebinarsummary\",\"method\":\"DELETE\",\"path\":\"/meetings/{meetingId}/meeting_summary\",\"summary\":\"Delete a meeting or webinar summary\",\"tags\":[\"Summaries\"]},{\"uid\":\"GET /meetings/{meetingId}/survey\",\"operationId\":\"meetingSurveyGet\",\"functionName\":\"MeetingSurveyGet\",\"method\":\"GET\",\"path\":\"/meetings/{meetingId}/survey\",\"summary\":\"Get a meeting survey\",\"tags\":[\"Surveys\"]},{\"uid\":\"DELETE /meetings/{meetingId}/survey\",\"operationId\":\"meetingSurveyDelete\",\"functionName\":\"MeetingSurveyDelete\",\"method\":\"DELETE\",\"path\":\"/meetings/{meetingId}/survey\",\"summary\":\"Delete a meeting survey\",\"tags\":[\"Surveys\"]},{\"uid\":\"PATCH /meetings/{meetingId}/survey\",\"operationId\":\"meetingSurveyUpdate\",\"functionName\":\"MeetingSurveyUpdate\",\"method\":\"PATCH\",\"path\":\"/meetings/{meetingId}/survey\",\"summary\":\"Update a meeting survey\",\"tags\":[\"Surveys\"]},{\"uid\":\"GET /tsp\",\"operationId\":\"tsp\",\"functionName\":\"Tsp\",\"method\":\"GET\",\"path\":\"/tsp\",\"summary\":\"Get account's TSP information\",\"tags\":[\"TSP\"]},{\"uid\":\"PATCH /tsp\",\"operationId\":\"tspUpdate\",\"functionName\":\"TspUpdate\",\"method\":\"PATCH\",\"path\":\"/tsp\",\"summary\":\"Update an account's TSP information\",\"tags\":[\"TSP\"]},{\"uid\":\"GET /users/{userId}/tsp\",\"operationId\":\"userTSPs\",\"functionName\":\"UserTSPs\",\"method\":\"GET\",\"path\":\"/users/{userId}/tsp\",\"summary\":\"List user's TSP accounts\",\"tags\":[\"TSP\"]},{\"uid\":\"POST /users/{userId}/tsp\",\"operationId\":\"userTSPCreate\",\"functionName\":\"UserTSPCreate\",\"method\":\"POST\",\"path\":\"/users/{userId}/tsp\",\"summary\":\"Add a user's TSP account\",\"tags\":[\"TSP\"]},{\"uid\":\"PATCH /users/{userId}/tsp/settings\",\"operationId\":\"tspUrlUpdate\",\"functionName\":\"TspUrlUpdate\",\"method\":\"PATCH\",\"path\":\"/users/{userId}/tsp/settings\",\"summary\":\"Set global dial-in URL for a TSP user\",\"tags\":[\"TSP\"]},{\"uid\":\"GET /users/{userId}/tsp/{tspId}\",\"operationId\":\"userTSP\",\"functionName\":\"UserTSP\",\"method\":\"GET\",\"path\":\"/users/{userId}/tsp/{tspId}\",\"summary\":\"Get a user's TSP account\",\"tags\":[\"TSP\"]},{\"uid\":\"DELETE /users/{userId}/tsp/{tspId}\",\"operationId\":\"userTSPDelete\",\"functionName\":\"UserTSPDelete\",\"method\":\"DELETE\",\"path\":\"/users/{userId}/tsp/{tspId}\",\"summary\":\"Delete a user's TSP account\",\"tags\":[\"TSP\"]},{\"uid\":\"PATCH /users/{userId}/tsp/{tspId}\",\"operationId\":\"userTSPUpdate\",\"functionName\":\"UserTSPUpdate\",\"method\":\"PATCH\",\"path\":\"/users/{userId}/tsp/{tspId}\",\"summary\":\"Update a TSP account\",\"tags\":[\"TSP\"]},{\"uid\":\"GET /users/{userId}/meeting_templates\",\"operationId\":\"listMeetingTemplates\",\"functionName\":\"ListMeetingTemplates\",\"method\":\"GET\",\"path\":\"/users/{userId}/meeting_templates\",\"summary\":\"List meeting templates\",\"tags\":[\"Templates\"]},{\"uid\":\"POST /users/{userId}/meeting_templates\",\"operationId\":\"meetingTemplateCreate\",\"functionName\":\"MeetingTemplateCreate\",\"method\":\"POST\",\"path\":\"/users/{userId}/meeting_templates\",\"summary\":\"Create a meeting template from an existing meeting\",\"tags\":[\"Templates\"]},{\"uid\":\"GET /tracking_fields\",\"operationId\":\"trackingfieldList\",\"functionName\":\"TrackingfieldList\",\"method\":\"GET\",\"path\":\"/tracking_fields\",\"summary\":\"List tracking fields\",\"tags\":[\"Tracking Field\"]},{\"uid\":\"POST /tracking_fields\",\"operationId\":\"trackingfieldCreate\",\"functionName\":\"TrackingfieldCreate\",\"method\":\"POST\",\"path\":\"/tracking_fields\",\"summary\":\"Create a tracking field\",\"tags\":[\"Tracking Field\"]},{\"uid\":\"GET /tracking_fields/{fieldId}\",\"operationId\":\"trackingfieldGet\",\"functionName\":\"TrackingfieldGet\",\"method\":\"GET\",\"path\":\"/tracking_fields/{fieldId}\",\"summary\":\"Get a tracking field\",\"tags\":[\"Tracking Field\"]},{\"uid\":\"DELETE /tracking_fields/{fieldId}\",\"operationId\":\"trackingfieldDelete\",\"functionName\":\"TrackingfieldDelete\",\"method\":\"DELETE\",\"path\":\"/tracking_fields/{fieldId}\",\"summary\":\"Delete a tracking field\",\"tags\":[\"Tracking Field\"]},{\"uid\":\"PATCH /tracking_fields/{fieldId}\",\"operationId\":\"trackingfieldUpdate\",\"functionName\":\"TrackingfieldUpdate\",\"method\":\"PATCH\",\"path\":\"/tracking_fields/{fieldId}\",\"summary\":\"Update a tracking field\",\"tags\":[\"Tracking Field\"]},{\"uid\":\"DELETE /live_webinars/{webinarId}/chat/messages/{messageId}\",\"operationId\":\"deleteWebinarChatMessageById\",\"functionName\":\"DeleteWebinarChatMessageById\",\"method\":\"DELETE\",\"path\":\"/live_webinars/{webinarId}/chat/messages/{messageId}\",\"summary\":\"Delete a live webinar message\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /past_webinars/{webinarId}/absentees\",\"operationId\":\"webinarAbsentees\",\"functionName\":\"WebinarAbsentees\",\"method\":\"GET\",\"path\":\"/past_webinars/{webinarId}/absentees\",\"summary\":\"Get webinar absentees\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /past_webinars/{webinarId}/instances\",\"operationId\":\"pastWebinars\",\"functionName\":\"PastWebinars\",\"method\":\"GET\",\"path\":\"/past_webinars/{webinarId}/instances\",\"summary\":\"List past webinar instances\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /past_webinars/{webinarId}/participants\",\"operationId\":\"listWebinarParticipants\",\"functionName\":\"ListWebinarParticipants\",\"method\":\"GET\",\"path\":\"/past_webinars/{webinarId}/participants\",\"summary\":\"List webinar participants\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /past_webinars/{webinarId}/polls\",\"operationId\":\"listPastWebinarPollResults\",\"functionName\":\"ListPastWebinarPollResults\",\"method\":\"GET\",\"path\":\"/past_webinars/{webinarId}/polls\",\"summary\":\"List past webinar poll results\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /past_webinars/{webinarId}/qa\",\"operationId\":\"listPastWebinarQA\",\"functionName\":\"ListPastWebinarQA\",\"method\":\"GET\",\"path\":\"/past_webinars/{webinarId}/qa\",\"summary\":\"List Q&As of a past webinar\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /users/{userId}/webinar_templates\",\"operationId\":\"listWebinarTemplates\",\"functionName\":\"ListWebinarTemplates\",\"method\":\"GET\",\"path\":\"/users/{userId}/webinar_templates\",\"summary\":\"List webinar templates\",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /users/{userId}/webinar_templates\",\"operationId\":\"webinarTemplateCreate\",\"functionName\":\"WebinarTemplateCreate\",\"method\":\"POST\",\"path\":\"/users/{userId}/webinar_templates\",\"summary\":\"Create a webinar template\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /users/{userId}/webinars\",\"operationId\":\"webinars\",\"functionName\":\"Webinars\",\"method\":\"GET\",\"path\":\"/users/{userId}/webinars\",\"summary\":\"List webinars\",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /users/{userId}/webinars\",\"operationId\":\"webinarCreate\",\"functionName\":\"WebinarCreate\",\"method\":\"POST\",\"path\":\"/users/{userId}/webinars\",\"summary\":\"Create a webinar\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}\",\"operationId\":\"webinar\",\"functionName\":\"Webinar\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}\",\"summary\":\"Get a webinar\",\"tags\":[\"Webinars\"]},{\"uid\":\"DELETE /webinars/{webinarId}\",\"operationId\":\"webinarDelete\",\"functionName\":\"WebinarDelete\",\"method\":\"DELETE\",\"path\":\"/webinars/{webinarId}\",\"summary\":\"Delete a webinar\",\"tags\":[\"Webinars\"]},{\"uid\":\"PATCH /webinars/{webinarId}\",\"operationId\":\"webinarUpdate\",\"functionName\":\"WebinarUpdate\",\"method\":\"PATCH\",\"path\":\"/webinars/{webinarId}\",\"summary\":\"Update a webinar\",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /webinars/{webinarId}/batch_registrants\",\"operationId\":\"addBatchWebinarRegistrants\",\"functionName\":\"AddBatchWebinarRegistrants\",\"method\":\"POST\",\"path\":\"/webinars/{webinarId}/batch_registrants\",\"summary\":\"Perform batch registration\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/branding\",\"operationId\":\"getWebinarBranding\",\"functionName\":\"GetWebinarBranding\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/branding\",\"summary\":\"Get webinar's session branding\",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /webinars/{webinarId}/branding/name_tags\",\"operationId\":\"createWebinarBrandingNameTag\",\"functionName\":\"CreateWebinarBrandingNameTag\",\"method\":\"POST\",\"path\":\"/webinars/{webinarId}/branding/name_tags\",\"summary\":\"Create a webinar's branding name tag\",\"tags\":[\"Webinars\"]},{\"uid\":\"DELETE /webinars/{webinarId}/branding/name_tags\",\"operationId\":\"deleteWebinarBrandingNameTag\",\"functionName\":\"DeleteWebinarBrandingNameTag\",\"method\":\"DELETE\",\"path\":\"/webinars/{webinarId}/branding/name_tags\",\"summary\":\"Delete a webinar's branding name tag\",\"tags\":[\"Webinars\"]},{\"uid\":\"PATCH /webinars/{webinarId}/branding/name_tags/{nameTagId}\",\"operationId\":\"updateWebinarBrandingNameTag\",\"functionName\":\"UpdateWebinarBrandingNameTag\",\"method\":\"PATCH\",\"path\":\"/webinars/{webinarId}/branding/name_tags/{nameTagId}\",\"summary\":\"Update a webinar's branding name tag\",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /webinars/{webinarId}/branding/virtual_backgrounds\",\"operationId\":\"uploadWebinarBrandingVB\",\"functionName\":\"UploadWebinarBrandingVB\",\"method\":\"POST\",\"path\":\"/webinars/{webinarId}/branding/virtual_backgrounds\",\"summary\":\"Upload a webinar's branding virtual background\",\"tags\":[\"Webinars\"]},{\"uid\":\"DELETE /webinars/{webinarId}/branding/virtual_backgrounds\",\"operationId\":\"deleteWebinarBrandingVB\",\"functionName\":\"DeleteWebinarBrandingVB\",\"method\":\"DELETE\",\"path\":\"/webinars/{webinarId}/branding/virtual_backgrounds\",\"summary\":\"Delete a webinar's branding virtual backgrounds\",\"tags\":[\"Webinars\"]},{\"uid\":\"PATCH /webinars/{webinarId}/branding/virtual_backgrounds\",\"operationId\":\"setWebinarBrandingVB\",\"functionName\":\"SetWebinarBrandingVB\",\"method\":\"PATCH\",\"path\":\"/webinars/{webinarId}/branding/virtual_backgrounds\",\"summary\":\"Set webinar's default branding virtual background\",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /webinars/{webinarId}/branding/wallpaper\",\"operationId\":\"uploadWebinarBrandingWallpaper\",\"functionName\":\"UploadWebinarBrandingWallpaper\",\"method\":\"POST\",\"path\":\"/webinars/{webinarId}/branding/wallpaper\",\"summary\":\"Upload a webinar's branding wallpaper\",\"tags\":[\"Webinars\"]},{\"uid\":\"DELETE /webinars/{webinarId}/branding/wallpaper\",\"operationId\":\"deleteWebinarBrandingWallpaper\",\"functionName\":\"DeleteWebinarBrandingWallpaper\",\"method\":\"DELETE\",\"path\":\"/webinars/{webinarId}/branding/wallpaper\",\"summary\":\"Delete a webinar's branding wallpaper\",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /webinars/{webinarId}/invite_links\",\"operationId\":\"webinarInviteLinksCreate\",\"functionName\":\"WebinarInviteLinksCreate\",\"method\":\"POST\",\"path\":\"/webinars/{webinarId}/invite_links\",\"summary\":\"Create webinar's invite links\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/jointoken/live_streaming\",\"operationId\":\"webinarLiveStreamingJoinToken\",\"functionName\":\"WebinarLiveStreamingJoinToken\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/jointoken/live_streaming\",\"summary\":\"Get a webinar's join token for live streaming\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/jointoken/local_archiving\",\"operationId\":\"webinarLocalArchivingArchiveToken\",\"functionName\":\"WebinarLocalArchivingArchiveToken\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/jointoken/local_archiving\",\"summary\":\"Get a webinar's archive token for local archiving\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/jointoken/local_recording\",\"operationId\":\"webinarLocalRecordingJoinToken\",\"functionName\":\"WebinarLocalRecordingJoinToken\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/jointoken/local_recording\",\"summary\":\"Get a webinar's join token for local recording\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/livestream\",\"operationId\":\"getWebinarLiveStreamDetails\",\"functionName\":\"GetWebinarLiveStreamDetails\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/livestream\",\"summary\":\"Get live stream details\",\"tags\":[\"Webinars\"]},{\"uid\":\"PATCH /webinars/{webinarId}/livestream\",\"operationId\":\"webinarLiveStreamUpdate\",\"functionName\":\"WebinarLiveStreamUpdate\",\"method\":\"PATCH\",\"path\":\"/webinars/{webinarId}/livestream\",\"summary\":\"Update a live stream\",\"tags\":[\"Webinars\"]},{\"uid\":\"PATCH /webinars/{webinarId}/livestream/status\",\"operationId\":\"webinarLiveStreamStatusUpdate\",\"functionName\":\"WebinarLiveStreamStatusUpdate\",\"method\":\"PATCH\",\"path\":\"/webinars/{webinarId}/livestream/status\",\"summary\":\"Update live stream status\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/panelists\",\"operationId\":\"webinarPanelists\",\"functionName\":\"WebinarPanelists\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/panelists\",\"summary\":\"List panelists\",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /webinars/{webinarId}/panelists\",\"operationId\":\"webinarPanelistCreate\",\"functionName\":\"WebinarPanelistCreate\",\"method\":\"POST\",\"path\":\"/webinars/{webinarId}/panelists\",\"summary\":\"Add panelists\",\"tags\":[\"Webinars\"]},{\"uid\":\"DELETE /webinars/{webinarId}/panelists\",\"operationId\":\"webinarPanelistsDelete\",\"functionName\":\"WebinarPanelistsDelete\",\"method\":\"DELETE\",\"path\":\"/webinars/{webinarId}/panelists\",\"summary\":\"Remove all panelists\",\"tags\":[\"Webinars\"]},{\"uid\":\"DELETE /webinars/{webinarId}/panelists/{panelistId}\",\"operationId\":\"webinarPanelistDelete\",\"functionName\":\"WebinarPanelistDelete\",\"method\":\"DELETE\",\"path\":\"/webinars/{webinarId}/panelists/{panelistId}\",\"summary\":\"Remove a panelist\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/polls\",\"operationId\":\"webinarPolls\",\"functionName\":\"WebinarPolls\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/polls\",\"summary\":\"List a webinar's polls \",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /webinars/{webinarId}/polls\",\"operationId\":\"webinarPollCreate\",\"functionName\":\"WebinarPollCreate\",\"method\":\"POST\",\"path\":\"/webinars/{webinarId}/polls\",\"summary\":\"Create a webinar's poll\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/polls/{pollId}\",\"operationId\":\"webinarPollGet\",\"functionName\":\"WebinarPollGet\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/polls/{pollId}\",\"summary\":\"Get a webinar poll\",\"tags\":[\"Webinars\"]},{\"uid\":\"PUT /webinars/{webinarId}/polls/{pollId}\",\"operationId\":\"webinarPollUpdate\",\"functionName\":\"WebinarPollUpdate\",\"method\":\"PUT\",\"path\":\"/webinars/{webinarId}/polls/{pollId}\",\"summary\":\"Update a webinar poll\",\"tags\":[\"Webinars\"]},{\"uid\":\"DELETE /webinars/{webinarId}/polls/{pollId}\",\"operationId\":\"webinarPollDelete\",\"functionName\":\"WebinarPollDelete\",\"method\":\"DELETE\",\"path\":\"/webinars/{webinarId}/polls/{pollId}\",\"summary\":\"Delete a webinar poll\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/registrants\",\"operationId\":\"webinarRegistrants\",\"functionName\":\"WebinarRegistrants\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/registrants\",\"summary\":\"List webinar registrants\",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /webinars/{webinarId}/registrants\",\"operationId\":\"webinarRegistrantCreate\",\"functionName\":\"WebinarRegistrantCreate\",\"method\":\"POST\",\"path\":\"/webinars/{webinarId}/registrants\",\"summary\":\"Add a webinar registrant\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/registrants/questions\",\"operationId\":\"webinarRegistrantsQuestionsGet\",\"functionName\":\"WebinarRegistrantsQuestionsGet\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/registrants/questions\",\"summary\":\"List registration questions\",\"tags\":[\"Webinars\"]},{\"uid\":\"PATCH /webinars/{webinarId}/registrants/questions\",\"operationId\":\"webinarRegistrantQuestionUpdate\",\"functionName\":\"WebinarRegistrantQuestionUpdate\",\"method\":\"PATCH\",\"path\":\"/webinars/{webinarId}/registrants/questions\",\"summary\":\"Update registration questions\",\"tags\":[\"Webinars\"]},{\"uid\":\"PUT /webinars/{webinarId}/registrants/status\",\"operationId\":\"webinarRegistrantStatus\",\"functionName\":\"WebinarRegistrantStatus\",\"method\":\"PUT\",\"path\":\"/webinars/{webinarId}/registrants/status\",\"summary\":\"Update registrant's status\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/registrants/{registrantId}\",\"operationId\":\"webinarRegistrantGet\",\"functionName\":\"WebinarRegistrantGet\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/registrants/{registrantId}\",\"summary\":\"Get a webinar registrant\",\"tags\":[\"Webinars\"]},{\"uid\":\"DELETE /webinars/{webinarId}/registrants/{registrantId}\",\"operationId\":\"deleteWebinarRegistrant\",\"functionName\":\"DeleteWebinarRegistrant\",\"method\":\"DELETE\",\"path\":\"/webinars/{webinarId}/registrants/{registrantId}\",\"summary\":\"Delete a webinar registrant\",\"tags\":[\"Webinars\"]},{\"uid\":\"POST /webinars/{webinarId}/sip_dialing\",\"operationId\":\"getWebinarSipDialingWithPasscode\",\"functionName\":\"GetWebinarSipDialingWithPasscode\",\"method\":\"POST\",\"path\":\"/webinars/{webinarId}/sip_dialing\",\"summary\":\"Get a webinar SIP URI with passcode\",\"tags\":[\"Webinars\"]},{\"uid\":\"PUT /webinars/{webinarId}/status\",\"operationId\":\"webinarStatus\",\"functionName\":\"WebinarStatus\",\"method\":\"PUT\",\"path\":\"/webinars/{webinarId}/status\",\"summary\":\"Update webinar status\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/survey\",\"operationId\":\"webinarSurveyGet\",\"functionName\":\"WebinarSurveyGet\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/survey\",\"summary\":\"Get a webinar survey\",\"tags\":[\"Webinars\"]},{\"uid\":\"DELETE /webinars/{webinarId}/survey\",\"operationId\":\"webinarSurveyDelete\",\"functionName\":\"WebinarSurveyDelete\",\"method\":\"DELETE\",\"path\":\"/webinars/{webinarId}/survey\",\"summary\":\"Delete a webinar survey\",\"tags\":[\"Webinars\"]},{\"uid\":\"PATCH /webinars/{webinarId}/survey\",\"operationId\":\"webinarSurveyUpdate\",\"functionName\":\"WebinarSurveyUpdate\",\"method\":\"PATCH\",\"path\":\"/webinars/{webinarId}/survey\",\"summary\":\"Update a webinar survey\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/token\",\"operationId\":\"webinarToken\",\"functionName\":\"WebinarToken\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/token\",\"summary\":\"Get webinar's token\",\"tags\":[\"Webinars\"]},{\"uid\":\"GET /webinars/{webinarId}/tracking_sources\",\"operationId\":\"getTrackingSources\",\"functionName\":\"GetTrackingSources\",\"method\":\"GET\",\"path\":\"/webinars/{webinarId}/tracking_sources\",\"summary\":\"Get webinar tracking sources\",\"tags\":[\"Webinars\"]}]") as readonly ZoomMeetingsApiOperation[];

// Hardened literal operation keys for generated SDK typing.
export const ZOOM_MEETINGS_API_OPERATION_IDS = [
  "listArchivedFiles",
  "getArchivedFileStatistics",
  "updateArchivedFile",
  "meetingLocalArchivingArchiveToken",
  "getArchivedFiles",
  "deleteArchivedFiles",
  "recordingGet",
  "recordingDelete",
  "analytics_details",
  "analytics_summary",
  "meetingRecordingRegistrants",
  "meetingRecordingRegistrantCreate",
  "recordingRegistrantsQuestionsGet",
  "recordingRegistrantQuestionUpdate",
  "meetingRecordingRegistrantStatus",
  "recordingSettingUpdate",
  "recordingSettingsUpdate",
  "recordingDeleteOne",
  "recordingStatusUpdateOne",
  "GetMeetingTranscript",
  "DeleteMeetingTranscript",
  "recordingStatusUpdate",
  "recordingsList",
  "listDevices",
  "addDevice",
  "Getzdmgroupinfo",
  "Assigndevicetoauser/commonarea",
  "GetZpaDeviceListProfileSettingOfaUser",
  "UpgradeZpas/app",
  "DeleteZpaDeviceByVendorAndMacAddress",
  "GetZpaVersioninfo",
  "getDevice",
  "deleteDevice",
  "updateDevice",
  "assginGroup",
  "changeDeviceAssociation",
  "deviceList",
  "deviceCreate",
  "deviceDelete",
  "deviceUpdate",
  "meetingAppAdd",
  "meetingAppDelete",
  "deleteMeetingChatMessageById",
  "updateMeetingChatMessageById",
  "inMeetingControl",
  "meetingLocalRecordingJoinToken",
  "meetingToken",
  "addBatchRegistrants",
  "meetingInvitation",
  "meetingInviteLinksCreate",
  "meetingRegistrants",
  "meetingRegistrantCreate",
  "meetingRegistrantsQuestionsGet",
  "meetingRegistrantQuestionUpdate",
  "meetingRegistrantStatus",
  "meetingRegistrantGet",
  "meetingregistrantdelete",
  "meetingLiveStreamingJoinToken",
  "getMeetingLiveStreamDetails",
  "meetingLiveStreamUpdate",
  "meetingLiveStreamStatusUpdate",
  "meetingRTMSStatusUpdate",
  "meeting",
  "meetingDelete",
  "meetingUpdate",
  "getSipDialingWithPasscode",
  "meetingStatus",
  "pastMeetingDetails",
  "pastMeetings",
  "pastMeetingParticipants",
  "listPastMeetingQA",
  "meetings",
  "meetingCreate",
  "listUpcomingMeeting",
  "userPACs",
  "createBatchPolls",
  "meetingPolls",
  "meetingPollCreate",
  "meetingPollGet",
  "meetingPollUpdate",
  "meetingPollDelete",
  "listPastMeetingPolls",
  "reportSignInSignOutActivities",
  "getBillingReport",
  "getBillingInvoicesReports",
  "reportCloudRecording",
  "reportDaily",
  "Getdisclaimerreport",
  "Gethistorymeetingandwebinarlist",
  "reportMeetingactivitylogs",
  "reportMeetingDetails",
  "reportMeetingParticipants",
  "reportMeetingPolls",
  "reportMeetingQA",
  "reportMeetingSurvey",
  "reportOperationLogs",
  "Getremotesupportreport",
  "reportTelephone",
  "reportUpcomingEvents",
  "reportUsers",
  "reportMeetings",
  "reportWebinarDetails",
  "reportWebinarParticipants",
  "reportWebinarPolls",
  "reportWebinarQA",
  "reportWebinarSurvey",
  "ListSIPPhonePhones",
  "EnableSIPPhonePhones",
  "deleteSIPPhonePhones",
  "UpdateSIPPhonePhones",
  "Listmeetingsummaries",
  "Getameetingsummary",
  "Deletemeetingorwebinarsummary",
  "meetingSurveyGet",
  "meetingSurveyDelete",
  "meetingSurveyUpdate",
  "tsp",
  "tspUpdate",
  "userTSPs",
  "userTSPCreate",
  "tspUrlUpdate",
  "userTSP",
  "userTSPDelete",
  "userTSPUpdate",
  "listMeetingTemplates",
  "meetingTemplateCreate",
  "trackingfieldList",
  "trackingfieldCreate",
  "trackingfieldGet",
  "trackingfieldDelete",
  "trackingfieldUpdate",
  "deleteWebinarChatMessageById",
  "webinarAbsentees",
  "pastWebinars",
  "listWebinarParticipants",
  "listPastWebinarPollResults",
  "listPastWebinarQA",
  "listWebinarTemplates",
  "webinarTemplateCreate",
  "webinars",
  "webinarCreate",
  "webinar",
  "webinarDelete",
  "webinarUpdate",
  "addBatchWebinarRegistrants",
  "getWebinarBranding",
  "createWebinarBrandingNameTag",
  "deleteWebinarBrandingNameTag",
  "updateWebinarBrandingNameTag",
  "uploadWebinarBrandingVB",
  "deleteWebinarBrandingVB",
  "setWebinarBrandingVB",
  "uploadWebinarBrandingWallpaper",
  "deleteWebinarBrandingWallpaper",
  "webinarInviteLinksCreate",
  "webinarLiveStreamingJoinToken",
  "webinarLocalArchivingArchiveToken",
  "webinarLocalRecordingJoinToken",
  "getWebinarLiveStreamDetails",
  "webinarLiveStreamUpdate",
  "webinarLiveStreamStatusUpdate",
  "webinarPanelists",
  "webinarPanelistCreate",
  "webinarPanelistsDelete",
  "webinarPanelistDelete",
  "webinarPolls",
  "webinarPollCreate",
  "webinarPollGet",
  "webinarPollUpdate",
  "webinarPollDelete",
  "webinarRegistrants",
  "webinarRegistrantCreate",
  "webinarRegistrantsQuestionsGet",
  "webinarRegistrantQuestionUpdate",
  "webinarRegistrantStatus",
  "webinarRegistrantGet",
  "deleteWebinarRegistrant",
  "getWebinarSipDialingWithPasscode",
  "webinarStatus",
  "webinarSurveyGet",
  "webinarSurveyDelete",
  "webinarSurveyUpdate",
  "webinarToken",
  "getTrackingSources"
] as const;
export const ZOOM_MEETINGS_API_OPERATION_OPERATION_IDS = [
  "listArchivedFiles",
  "getArchivedFileStatistics",
  "updateArchivedFile",
  "meetingLocalArchivingArchiveToken",
  "getArchivedFiles",
  "deleteArchivedFiles",
  "recordingGet",
  "recordingDelete",
  "analytics_details",
  "analytics_summary",
  "meetingRecordingRegistrants",
  "meetingRecordingRegistrantCreate",
  "recordingRegistrantsQuestionsGet",
  "recordingRegistrantQuestionUpdate",
  "meetingRecordingRegistrantStatus",
  "recordingSettingUpdate",
  "recordingSettingsUpdate",
  "recordingDeleteOne",
  "recordingStatusUpdateOne",
  "GetMeetingTranscript",
  "DeleteMeetingTranscript",
  "recordingStatusUpdate",
  "recordingsList",
  "listDevices",
  "addDevice",
  "Getzdmgroupinfo",
  "Assigndevicetoauser/commonarea",
  "GetZpaDeviceListProfileSettingOfaUser",
  "UpgradeZpas/app",
  "DeleteZpaDeviceByVendorAndMacAddress",
  "GetZpaVersioninfo",
  "getDevice",
  "deleteDevice",
  "updateDevice",
  "assginGroup",
  "changeDeviceAssociation",
  "deviceList",
  "deviceCreate",
  "deviceDelete",
  "deviceUpdate",
  "meetingAppAdd",
  "meetingAppDelete",
  "deleteMeetingChatMessageById",
  "updateMeetingChatMessageById",
  "inMeetingControl",
  "meetingLocalRecordingJoinToken",
  "meetingToken",
  "addBatchRegistrants",
  "meetingInvitation",
  "meetingInviteLinksCreate",
  "meetingRegistrants",
  "meetingRegistrantCreate",
  "meetingRegistrantsQuestionsGet",
  "meetingRegistrantQuestionUpdate",
  "meetingRegistrantStatus",
  "meetingRegistrantGet",
  "meetingregistrantdelete",
  "meetingLiveStreamingJoinToken",
  "getMeetingLiveStreamDetails",
  "meetingLiveStreamUpdate",
  "meetingLiveStreamStatusUpdate",
  "meetingRTMSStatusUpdate",
  "meeting",
  "meetingDelete",
  "meetingUpdate",
  "getSipDialingWithPasscode",
  "meetingStatus",
  "pastMeetingDetails",
  "pastMeetings",
  "pastMeetingParticipants",
  "listPastMeetingQA",
  "meetings",
  "meetingCreate",
  "listUpcomingMeeting",
  "userPACs",
  "createBatchPolls",
  "meetingPolls",
  "meetingPollCreate",
  "meetingPollGet",
  "meetingPollUpdate",
  "meetingPollDelete",
  "listPastMeetingPolls",
  "reportSignInSignOutActivities",
  "getBillingReport",
  "getBillingInvoicesReports",
  "reportCloudRecording",
  "reportDaily",
  "Getdisclaimerreport",
  "Gethistorymeetingandwebinarlist",
  "reportMeetingactivitylogs",
  "reportMeetingDetails",
  "reportMeetingParticipants",
  "reportMeetingPolls",
  "reportMeetingQA",
  "reportMeetingSurvey",
  "reportOperationLogs",
  "Getremotesupportreport",
  "reportTelephone",
  "reportUpcomingEvents",
  "reportUsers",
  "reportMeetings",
  "reportWebinarDetails",
  "reportWebinarParticipants",
  "reportWebinarPolls",
  "reportWebinarQA",
  "reportWebinarSurvey",
  "ListSIPPhonePhones",
  "EnableSIPPhonePhones",
  "deleteSIPPhonePhones",
  "UpdateSIPPhonePhones",
  "Listmeetingsummaries",
  "Getameetingsummary",
  "Deletemeetingorwebinarsummary",
  "meetingSurveyGet",
  "meetingSurveyDelete",
  "meetingSurveyUpdate",
  "tsp",
  "tspUpdate",
  "userTSPs",
  "userTSPCreate",
  "tspUrlUpdate",
  "userTSP",
  "userTSPDelete",
  "userTSPUpdate",
  "listMeetingTemplates",
  "meetingTemplateCreate",
  "trackingfieldList",
  "trackingfieldCreate",
  "trackingfieldGet",
  "trackingfieldDelete",
  "trackingfieldUpdate",
  "deleteWebinarChatMessageById",
  "webinarAbsentees",
  "pastWebinars",
  "listWebinarParticipants",
  "listPastWebinarPollResults",
  "listPastWebinarQA",
  "listWebinarTemplates",
  "webinarTemplateCreate",
  "webinars",
  "webinarCreate",
  "webinar",
  "webinarDelete",
  "webinarUpdate",
  "addBatchWebinarRegistrants",
  "getWebinarBranding",
  "createWebinarBrandingNameTag",
  "deleteWebinarBrandingNameTag",
  "updateWebinarBrandingNameTag",
  "uploadWebinarBrandingVB",
  "deleteWebinarBrandingVB",
  "setWebinarBrandingVB",
  "uploadWebinarBrandingWallpaper",
  "deleteWebinarBrandingWallpaper",
  "webinarInviteLinksCreate",
  "webinarLiveStreamingJoinToken",
  "webinarLocalArchivingArchiveToken",
  "webinarLocalRecordingJoinToken",
  "getWebinarLiveStreamDetails",
  "webinarLiveStreamUpdate",
  "webinarLiveStreamStatusUpdate",
  "webinarPanelists",
  "webinarPanelistCreate",
  "webinarPanelistsDelete",
  "webinarPanelistDelete",
  "webinarPolls",
  "webinarPollCreate",
  "webinarPollGet",
  "webinarPollUpdate",
  "webinarPollDelete",
  "webinarRegistrants",
  "webinarRegistrantCreate",
  "webinarRegistrantsQuestionsGet",
  "webinarRegistrantQuestionUpdate",
  "webinarRegistrantStatus",
  "webinarRegistrantGet",
  "deleteWebinarRegistrant",
  "getWebinarSipDialingWithPasscode",
  "webinarStatus",
  "webinarSurveyGet",
  "webinarSurveyDelete",
  "webinarSurveyUpdate",
  "webinarToken",
  "getTrackingSources"
] as const;
export const ZOOM_MEETINGS_API_OPERATION_UIDS = [
  "GET /archive_files",
  "GET /archive_files/statistics",
  "PATCH /archive_files/{fileId}",
  "GET /meetings/{meetingId}/jointoken/local_archiving",
  "GET /past_meetings/{meetingUUID}/archive_files",
  "DELETE /past_meetings/{meetingUUID}/archive_files",
  "GET /meetings/{meetingId}/recordings",
  "DELETE /meetings/{meetingId}/recordings",
  "GET /meetings/{meetingId}/recordings/analytics_details",
  "GET /meetings/{meetingId}/recordings/analytics_summary",
  "GET /meetings/{meetingId}/recordings/registrants",
  "POST /meetings/{meetingId}/recordings/registrants",
  "GET /meetings/{meetingId}/recordings/registrants/questions",
  "PATCH /meetings/{meetingId}/recordings/registrants/questions",
  "PUT /meetings/{meetingId}/recordings/registrants/status",
  "GET /meetings/{meetingId}/recordings/settings",
  "PATCH /meetings/{meetingId}/recordings/settings",
  "DELETE /meetings/{meetingId}/recordings/{recordingId}",
  "PUT /meetings/{meetingId}/recordings/{recordingId}/status",
  "GET /meetings/{meetingId}/transcript",
  "DELETE /meetings/{meetingId}/transcript",
  "PUT /meetings/{meetingUUID}/recordings/status",
  "GET /users/{userId}/recordings",
  "GET /devices",
  "POST /devices",
  "GET /devices/groups",
  "POST /devices/zpa/assignment",
  "GET /devices/zpa/settings",
  "POST /devices/zpa/upgrade",
  "DELETE /devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}",
  "GET /devices/zpa/zdm_groups/{zdmGroupId}/versions",
  "GET /devices/{deviceId}",
  "DELETE /devices/{deviceId}",
  "PATCH /devices/{deviceId}",
  "PATCH /devices/{deviceId}/assign_group",
  "PATCH /devices/{deviceId}/assignment",
  "GET /h323/devices",
  "POST /h323/devices",
  "DELETE /h323/devices/{deviceId}",
  "PATCH /h323/devices/{deviceId}",
  "POST /meetings/{meetingId}/open_apps",
  "DELETE /meetings/{meetingId}/open_apps",
  "DELETE /live_meetings/{meetingId}/chat/messages/{messageId}",
  "PATCH /live_meetings/{meetingId}/chat/messages/{messageId}",
  "PATCH /live_meetings/{meetingId}/events",
  "GET /meetings/{meetingId}/jointoken/local_recording",
  "GET /meetings/{meetingId}/token",
  "POST /meetings/{meetingId}/batch_registrants",
  "GET /meetings/{meetingId}/invitation",
  "POST /meetings/{meetingId}/invite_links",
  "GET /meetings/{meetingId}/registrants",
  "POST /meetings/{meetingId}/registrants",
  "GET /meetings/{meetingId}/registrants/questions",
  "PATCH /meetings/{meetingId}/registrants/questions",
  "PUT /meetings/{meetingId}/registrants/status",
  "GET /meetings/{meetingId}/registrants/{registrantId}",
  "DELETE /meetings/{meetingId}/registrants/{registrantId}",
  "GET /meetings/{meetingId}/jointoken/live_streaming",
  "GET /meetings/{meetingId}/livestream",
  "PATCH /meetings/{meetingId}/livestream",
  "PATCH /meetings/{meetingId}/livestream/status",
  "PATCH /live_meetings/{meetingId}/rtms_app/status",
  "GET /meetings/{meetingId}",
  "DELETE /meetings/{meetingId}",
  "PATCH /meetings/{meetingId}",
  "POST /meetings/{meetingId}/sip_dialing",
  "PUT /meetings/{meetingId}/status",
  "GET /past_meetings/{meetingId}",
  "GET /past_meetings/{meetingId}/instances",
  "GET /past_meetings/{meetingId}/participants",
  "GET /past_meetings/{meetingId}/qa",
  "GET /users/{userId}/meetings",
  "POST /users/{userId}/meetings",
  "GET /users/{userId}/upcoming_meetings",
  "GET /users/{userId}/pac",
  "POST /meetings/{meetingId}/batch_polls",
  "GET /meetings/{meetingId}/polls",
  "POST /meetings/{meetingId}/polls",
  "GET /meetings/{meetingId}/polls/{pollId}",
  "PUT /meetings/{meetingId}/polls/{pollId}",
  "DELETE /meetings/{meetingId}/polls/{pollId}",
  "GET /past_meetings/{meetingId}/polls",
  "GET /report/activities",
  "GET /report/billing",
  "GET /report/billing/invoices",
  "GET /report/cloud_recording",
  "GET /report/daily",
  "GET /report/disclaimer",
  "GET /report/history_meetings",
  "GET /report/meeting_activities",
  "GET /report/meetings/{meetingId}",
  "GET /report/meetings/{meetingId}/participants",
  "GET /report/meetings/{meetingId}/polls",
  "GET /report/meetings/{meetingId}/qa",
  "GET /report/meetings/{meetingId}/survey",
  "GET /report/operationlogs",
  "GET /report/remote_support",
  "GET /report/telephone",
  "GET /report/upcoming_events",
  "GET /report/users",
  "GET /report/users/{userId}/meetings",
  "GET /report/webinars/{webinarId}",
  "GET /report/webinars/{webinarId}/participants",
  "GET /report/webinars/{webinarId}/polls",
  "GET /report/webinars/{webinarId}/qa",
  "GET /report/webinars/{webinarId}/survey",
  "GET /sip_phones/phones",
  "POST /sip_phones/phones",
  "DELETE /sip_phones/phones/{phoneId}",
  "PATCH /sip_phones/phones/{phoneId}",
  "GET /meetings/meeting_summaries",
  "GET /meetings/{meetingId}/meeting_summary",
  "DELETE /meetings/{meetingId}/meeting_summary",
  "GET /meetings/{meetingId}/survey",
  "DELETE /meetings/{meetingId}/survey",
  "PATCH /meetings/{meetingId}/survey",
  "GET /tsp",
  "PATCH /tsp",
  "GET /users/{userId}/tsp",
  "POST /users/{userId}/tsp",
  "PATCH /users/{userId}/tsp/settings",
  "GET /users/{userId}/tsp/{tspId}",
  "DELETE /users/{userId}/tsp/{tspId}",
  "PATCH /users/{userId}/tsp/{tspId}",
  "GET /users/{userId}/meeting_templates",
  "POST /users/{userId}/meeting_templates",
  "GET /tracking_fields",
  "POST /tracking_fields",
  "GET /tracking_fields/{fieldId}",
  "DELETE /tracking_fields/{fieldId}",
  "PATCH /tracking_fields/{fieldId}",
  "DELETE /live_webinars/{webinarId}/chat/messages/{messageId}",
  "GET /past_webinars/{webinarId}/absentees",
  "GET /past_webinars/{webinarId}/instances",
  "GET /past_webinars/{webinarId}/participants",
  "GET /past_webinars/{webinarId}/polls",
  "GET /past_webinars/{webinarId}/qa",
  "GET /users/{userId}/webinar_templates",
  "POST /users/{userId}/webinar_templates",
  "GET /users/{userId}/webinars",
  "POST /users/{userId}/webinars",
  "GET /webinars/{webinarId}",
  "DELETE /webinars/{webinarId}",
  "PATCH /webinars/{webinarId}",
  "POST /webinars/{webinarId}/batch_registrants",
  "GET /webinars/{webinarId}/branding",
  "POST /webinars/{webinarId}/branding/name_tags",
  "DELETE /webinars/{webinarId}/branding/name_tags",
  "PATCH /webinars/{webinarId}/branding/name_tags/{nameTagId}",
  "POST /webinars/{webinarId}/branding/virtual_backgrounds",
  "DELETE /webinars/{webinarId}/branding/virtual_backgrounds",
  "PATCH /webinars/{webinarId}/branding/virtual_backgrounds",
  "POST /webinars/{webinarId}/branding/wallpaper",
  "DELETE /webinars/{webinarId}/branding/wallpaper",
  "POST /webinars/{webinarId}/invite_links",
  "GET /webinars/{webinarId}/jointoken/live_streaming",
  "GET /webinars/{webinarId}/jointoken/local_archiving",
  "GET /webinars/{webinarId}/jointoken/local_recording",
  "GET /webinars/{webinarId}/livestream",
  "PATCH /webinars/{webinarId}/livestream",
  "PATCH /webinars/{webinarId}/livestream/status",
  "GET /webinars/{webinarId}/panelists",
  "POST /webinars/{webinarId}/panelists",
  "DELETE /webinars/{webinarId}/panelists",
  "DELETE /webinars/{webinarId}/panelists/{panelistId}",
  "GET /webinars/{webinarId}/polls",
  "POST /webinars/{webinarId}/polls",
  "GET /webinars/{webinarId}/polls/{pollId}",
  "PUT /webinars/{webinarId}/polls/{pollId}",
  "DELETE /webinars/{webinarId}/polls/{pollId}",
  "GET /webinars/{webinarId}/registrants",
  "POST /webinars/{webinarId}/registrants",
  "GET /webinars/{webinarId}/registrants/questions",
  "PATCH /webinars/{webinarId}/registrants/questions",
  "PUT /webinars/{webinarId}/registrants/status",
  "GET /webinars/{webinarId}/registrants/{registrantId}",
  "DELETE /webinars/{webinarId}/registrants/{registrantId}",
  "POST /webinars/{webinarId}/sip_dialing",
  "PUT /webinars/{webinarId}/status",
  "GET /webinars/{webinarId}/survey",
  "DELETE /webinars/{webinarId}/survey",
  "PATCH /webinars/{webinarId}/survey",
  "GET /webinars/{webinarId}/token",
  "GET /webinars/{webinarId}/tracking_sources"
] as const;
// End hardened literal operation keys.
export const ZOOM_MEETINGS_API_OPERATION_BY_UID = new Map(ZOOM_MEETINGS_API_OPERATIONS.map((operation) => [operation.uid, operation]));
export const ZOOM_MEETINGS_API_OPERATION_BY_ID = new Map<string, ZoomMeetingsApiOperation>();
for (const operation of ZOOM_MEETINGS_API_OPERATIONS) {
  if (!ZOOM_MEETINGS_API_OPERATION_BY_ID.has(operation.operationId)) {
    ZOOM_MEETINGS_API_OPERATION_BY_ID.set(operation.operationId, operation);
  }
}

export type ZoomMeetingsApiOperationUid = typeof ZOOM_MEETINGS_API_OPERATION_UIDS[number];
