import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { VONAGE_VOICE_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  VONAGE_VOICE_FULL_API_OPERATION_COUNT,
  VONAGE_VOICE_FULL_API_PATH_COUNT,
  VONAGE_VOICE_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const vonageVoiceProviderManifest = defineProviderPackage({
  id: "voice.vonage",
  name: "Vonage Voice API",
  packageName: "@cognidesk/integrations",
  provider: "vonage",
  category: "voice",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in the official Vonage Voice v1, Voice v2, Application v2, Conversation v1, and Numbers OpenAPI specs used by this voice package.",
      "Typed convenience helpers remain available for Cognidesk support workflows: outbound calls, call fetch, documented transfer call update, NCCO helpers, and signed Voice webhook parsing.",
      "Generated functions cover Voice v1 call list/create/get/update, stream audio, TTS, DTMF, Voice v2 outbound app/IP calls, Application CRUD, Application users, Conversation CRUD/members/events/talk/stream/record, and Numbers list/search/buy/cancel/update.",
      "This full-provider claim is limited to this package's Vonage voice REST bundle; broader Vonage platform products outside these official specs remain separate package/surface decisions.",
      "Application answer, event, fallback, signed-callback, phone-number ownership, regional endpoint selection, recording consent, and conversation lifecycle policy remain SDK-user/provider configuration.",
    ],
    evidence: [
      { label: "Vonage Voice API v1 OpenAPI", url: "https://developer.vonage.com/api/v1/developer/api/file/voice?format=json&vendorId=vonage" },
      { label: "Vonage Voice API v2 OpenAPI", url: "https://developer.vonage.com/api/v1/developer/api/file/voice.v2?format=json&vendorId=vonage" },
      { label: "Vonage Application API v2 OpenAPI", url: "https://developer.vonage.com/api/v1/developer/api/file/application.v2?format=json&vendorId=vonage" },
      { label: "Vonage Conversation API v1 OpenAPI", url: "https://developer.vonage.com/api/v1/developer/api/file/conversation?format=json&vendorId=vonage" },
      { label: "Vonage Numbers API OpenAPI", url: "https://developer.vonage.com/api/v1/developer/api/file/numbers?format=json&vendorId=vonage" },
      { label: "Vonage Voice API reference", url: "https://developer.vonage.com/en/api/voice" },
      { label: "Vonage Voice API v2 reference", url: "https://developer.vonage.com/en/api/voice.v2" },
      { label: "Vonage NCCO reference", url: "https://developer.vonage.com/en/voice/voice-api/ncco-reference" },
      { label: "Vonage Voice webhooks reference", url: "https://developer.vonage.com/en/voice/voice-api/webhook-reference" },
      { label: "Vonage Application technical details", url: "https://developer.vonage.com/en/application/technical-details" },
      { label: "Vonage Voice call flow", url: "https://developer.vonage.com/en/voice/voice-api/concepts/call-flow" },
      { label: "Vonage Voice endpoints", url: "https://developer.vonage.com/en/voice/voice-api/concepts/endpoints" },
      { label: "Vonage Application API reference", url: "https://developer.vonage.com/en/api/application.v2" },
      { label: "Vonage Conversation API reference", url: "https://developer.vonage.com/en/api/conversation" },
      { label: "Vonage Numbers API reference", url: "https://developer.vonage.com/en/api/numbers" },
    ],
  },
  credentialRequirements: [
    {
      id: "vonage-application",
      label: "Vonage application credentials",
      description: "Vonage Application ID and private key used to mint backend JWTs for Voice API calls.",
      required: true,
    },
    {
      id: "vonage-api-key-secret",
      label: "Vonage API key and secret",
      description: "Vonage API key/secret used for Basic-authenticated Application CRUD and Numbers API operations.",
      required: false,
    },
    {
      id: "vonage-voice-number",
      label: "Vonage voice-capable number",
      description: "SDK-user-selected Vonage number or verified caller identity used for outbound voice.",
      required: false,
    },
    {
      id: "vonage-webhook-signature-secret",
      label: "Vonage webhook signature secret",
      description: "Signature secret used to verify signed Voice API answer and event webhooks.",
      required: false,
    },
    {
      id: "vonage-voice-application-webhooks",
      label: "Vonage Voice answer and event webhooks",
      description: "Configured Voice application answer_url and event_url endpoints, or outbound-call URL policy, required for receiving NCCO requests and call events.",
      required: true,
    },
    {
      id: "vonage-fallback-answer-url",
      label: "Vonage fallback answer URL",
      description: "Optional but recommended fallback_answer_url configured for Voice application webhook failures.",
      required: false,
    },
    {
      id: "vonage-signed-callbacks",
      label: "Vonage signed callbacks",
      description: "Voice application signed_callbacks setting aligned with SDK webhook signature verification policy.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive inbound calls",
      description: "Parses Vonage Voice answer, event, and fallback webhooks and returns SDK-user-defined NCCO call flow responses.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "vonageCall", label: "Vonage Call" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Place outbound calls",
      description: "Creates outbound calls through the Vonage Voice API when SDK-user policy permits outbound contact.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "vonageCall", label: "Vonage Call" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Connect calls to WebSocket media",
      description: "Builds NCCO connect actions for SDK-user-owned phone, SIP, or WebSocket voice bridges; generated fullApi functions expose the separate Voice v2 app/IP outbound-call endpoint.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "vonageNcco", label: "Vonage NCCO" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "transfer",
      label: "Call control and transfer",
      description: "Transfers active calls through the documented Vonage Voice API modify-call transfer action.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "vonageCall", label: "Vonage Call" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      capability: "voice.webhook-signature",
      label: "Validate Vonage signed webhooks",
      description: "Validates signed Vonage webhook JWTs from the Authorization header using the SDK user's signature secret.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "vonageWebhook", label: "Vonage Webhook" }],
      requiresCredential: true,
      extension: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Phone numbers, call UUIDs, call state, recording metadata, speech callbacks, and webhook payloads can contain customer data.",
    "Vonage private keys and webhook signature secrets stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "The SDK user configures application answer/event/fallback webhooks, signed callbacks, phone numbers, regions, recording consent, outbound eligibility, and handoff policy.",
    "This package provides Voice API call-control and webhook primitives; it does not decide when an outbound call, recording, transfer, or callback should happen.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://developer.vonage.com/en/voice/voice-api",
    channelCoverage: {
      fullVoiceRestBundleOperations: "generated-per-operation-functions",
      inboundAnswerEventFallbackWebhooks: "typed-parse",
      outboundCall: "typed-create",
      callFetch: "typed-read",
      callTransfer: "typed-transfer",
      ncco: "typed-generate",
      websocketEndpoint: "typed-ncco-connect",
      sipEndpoint: "typed-ncco-connect",
      appEndpointV2Outbound: "generated-per-operation-functions",
      conversationApi: "generated-per-operation-functions",
      applicationApi: "generated-per-operation-functions",
      numbersApi: "generated-per-operation-functions",
      recordings: "generated-per-operation-functions",
    },
    fullProviderApiVerification: {
      provider: "vonage-voice-rest-bundle",
      apiVersion: VONAGE_VOICE_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/vonage-voice-full-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/vonage-voice-full-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/vonage-voice-full-api-2026-06-18.functions.json",
      documentedPathCount: VONAGE_VOICE_FULL_API_PATH_COUNT,
      documentedOperationCount: VONAGE_VOICE_FULL_API_OPERATION_COUNT,
      implementedOperationCount: VONAGE_VOICE_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: VONAGE_VOICE_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
});
