import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { TWILIO_VOICE_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  TWILIO_VOICE_FULL_API_OPERATION_COUNT,
  TWILIO_VOICE_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const twilioVoiceProviderManifest = defineProviderPackage({
  id: "voice.twilio",
  name: "Twilio Programmable Voice",
  packageName: "@cognidesk/integrations",
  provider: "twilio",
  category: "voice",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for Twilio's official Voice-domain OpenAPI surfaces: core Voice call/conference/queue/recording/transcription/stream/SIP resources, Voice v1/v3, Trunking v1, and Insights v1-v3.",
      "The package keeps typed convenience helpers for common voice support workflows: outbound call create/fetch/update/redirect/end, account readiness, Media Stream TwiML generation, and form webhook signature validation.",
      "Phone-number ownership, regions/edges, recording consent, queue/conference design, call routing policy, and live media service operation remain SDK-user/provider configuration.",
    ],
    evidence: [
      { label: "Twilio Programmable Voice API overview", url: "https://www.twilio.com/docs/voice/api" },
      { label: "Twilio Call resource", url: "https://www.twilio.com/docs/voice/api/call-resource" },
      { label: "Twilio Stream TwiML", url: "https://www.twilio.com/docs/voice/twiml/stream" },
      { label: "Twilio request signature validation", url: "https://www.twilio.com/docs/usage/security" },
      { label: "Twilio Conferences resource", url: "https://www.twilio.com/docs/voice/api/conference-resource" },
      { label: "Twilio Recordings resource", url: "https://www.twilio.com/docs/voice/api/recording" },
      { label: "Twilio real-time Transcriptions subresource", url: "https://www.twilio.com/docs/voice/api/realtime-transcription-resource" },
    ],
  },
  credentialRequirements: [
    {
      id: "twilio-account",
      label: "Twilio Account SID",
      description: "Twilio Account SID used to address Voice REST API resources.",
      required: true,
    },
    {
      id: "twilio-rest-api-credentials",
      label: "Twilio REST API credentials",
      description: "Server-side Twilio Auth Token or API Key SID/secret used for Voice REST API calls. API keys are preferred for production REST access.",
      required: true,
      metadata: {
        scopeModel: "twilio-restricted-api-key-permissions",
        minimumPermissionArea: "Voice",
        requiredResources: ["Calls read/create/update", "Account read for readiness"],
        unrestrictedAuthTokenFallback: true,
      },
    },
    {
      id: "twilio-webhook-auth-token",
      label: "Twilio webhook Auth Token",
      description: "Primary Twilio Auth Token used to validate X-Twilio-Signature webhook requests.",
      required: false,
    },
    {
      id: "twilio-voice-number",
      label: "Twilio voice-capable phone number",
      description: "A Twilio phone number or caller ID that supports outbound voice.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive inbound calls",
      description: "Accepts Twilio Voice webhooks and routes calls to SDK-user-owned Cognidesk voice handling.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "twilioCall", label: "Twilio Call" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Place outbound calls",
      description: "Creates outbound calls through the Twilio Calls REST resource.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "twilioCall", label: "Twilio Call" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Twilio Media Streams",
      description: "Builds TwiML that connects a Twilio call to a WebSocket Media Stream.",
      audiences: ["customer-facing"],
      providerObjects: [
        { kind: "twilioCall", label: "Twilio Call" },
        { kind: "twilioMediaStream", label: "Twilio Media Stream" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "transfer",
      label: "Call transfer",
      description: "Supports SDK-user-configured call control workflows through Twilio Voice call objects.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "twilioCall", label: "Twilio Call" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      capability: "twilio.webhook-signature",
      label: "Validate Twilio webhooks",
      description: "Validates X-Twilio-Signature for form-encoded Twilio Voice webhooks.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "twilioWebhook", label: "Twilio Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Phone numbers, call metadata, webhook parameters, and Media Stream audio metadata are exchanged with Twilio.",
    "Twilio credentials stay server-side and are never issued to browsers by this package.",
  ],
  limitations: [
    "Live call readiness depends on the SDK user's Twilio account, voice-capable numbers, regions, webhooks, and account permissions.",
    "Conversation routing, consent, recording, retention, and handoff behavior remain SDK-user configuration.",
  ],
  metadata: {
    channelCoverage: {
      fullVoiceDomainApiOperations: "generated-per-operation-functions",
      inboundCallWebhook: "typed-parse",
      outboundCall: "typed-create",
      callFetchUpdateRedirectEnd: "typed-selected",
      mediaStreamsTwiML: "typed-generate",
      webhookSignature: "typed-verify",
      conferences: "generated-full-surface",
      queues: "generated-full-surface",
      recordings: "generated-full-surface",
      realtimeTranscriptions: "generated-full-surface",
      sipDomainsTrunks: "generated-full-surface",
      voiceInsights: "generated-full-surface",
    },
    fullProviderApiVerification: {
      provider: "twilio-voice-domain",
      apiVersion: TWILIO_VOICE_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-17",
      coverageArtifact: "docs/provider-coverage/twilio-voice-full-api-2026-06-17.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/twilio-voice-full-api-2026-06-17.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/twilio-voice-full-api-2026-06-17.functions.json",
      documentedOperationCount: TWILIO_VOICE_FULL_API_OPERATION_COUNT,
      implementedOperationCount: TWILIO_VOICE_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: TWILIO_VOICE_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
