import { defineIntegrationProviderPackage } from "@cognidesk/integration-kit";

export const postmarkEmailProviderManifest = defineIntegrationProviderPackage({
  id: "email.postmark",
  name: "Postmark",
  packageName: "@cognidesk/integration-email-postmark",
  provider: "postmark",
  category: "email",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is the Cognidesk normalized support-email adapter surface backed by the official Postmark Node client.",
      "The raw Postmark clients are exposed for SDK-user controlled advanced provider operations; Cognidesk does not re-export a generated full Postmark API clone.",
    ],
    evidence: [
      { label: "Postmark Node.js library", url: "https://github.com/ActiveCampaign/postmark.js" },
      { label: "Postmark Email API", url: "https://postmarkapp.com/developer/api/email-api" },
      { label: "Postmark Messages API", url: "https://postmarkapp.com/developer/api/messages-api" },
      { label: "Postmark inbound webhooks", url: "https://postmarkapp.com/developer/webhooks/inbound-webhook" },
    ],
  },
  credentialRequirements: [
    {
      id: "postmark-server-token",
      label: "Postmark server token",
      description: "Server token used by the official Postmark ServerClient.",
      required: true,
    },
    {
      id: "postmark-account-token",
      label: "Postmark account token",
      description: "Optional account token for explicitly retained account-scoped support operations.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Postmark inbound webhooks",
      description: "Parses inbound email webhooks into support email events.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "emailMessage", label: "Email Message" },
        { kind: "postmarkInboundMessage", label: "Postmark Inbound Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Postmark email",
      description: "Sends support email through the official Postmark ServerClient.",
      audiences: ["customer-facing"],
      providerObjects: [
        { kind: "emailMessage", label: "Email Message" },
        { kind: "postmarkMessage", label: "Postmark Message" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Postmark messages and streams",
      description: "Reads message details, delivery status, message streams, webhooks, and suppression state.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "postmarkMessage", label: "Postmark Message" },
        { kind: "postmarkMessageStream", label: "Postmark Message Stream" },
        { kind: "postmarkSuppression", label: "Postmark Suppression" },
        { kind: "deliveryStatus", label: "Delivery Status" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Manage Postmark suppressions",
      description: "Adds or deletes suppressions when SDK-user policy permits.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "postmarkSuppression", label: "Postmark Suppression" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
  ],
  operations: [
    { alias: "email.receive", capability: "receive", providerObject: "emailMessage", exposesSensitiveData: true },
    { alias: "email.send", capability: "send", providerObject: "emailMessage", sideEffect: true, exposesSensitiveData: true },
    { alias: "email.reply.send", capability: "send", providerObject: "emailMessage", sideEffect: true, exposesSensitiveData: true },
    { alias: "email.deliveryStatus.read", capability: "read-provider-object", providerObject: "deliveryStatus", exposesSensitiveData: true },
    { alias: "postmark.messageStreams.list", capability: "read-provider-object", providerObject: "postmarkMessageStream", extension: true },
    { alias: "postmark.suppressions.create", capability: "update-provider-object", providerObject: "postmarkSuppression", extension: true, sideEffect: true, changesWorkflow: true },
    { alias: "postmark.suppressions.delete", capability: "update-provider-object", providerObject: "postmarkSuppression", extension: true, sideEffect: true, changesWorkflow: true },
  ],
  privacyNotes: [
    "Postmark email bodies, recipients, sender addresses, headers, attachments, metadata, and webhook payloads can contain customer data.",
    "Postmark tokens stay server-side and are represented only as readiness state.",
  ],
  limitations: [
    "The SDK user owns message stream selection, webhook auth policy, retention, redaction, outbound approval, and rate limiting.",
    "Advanced provider operations remain available through raw Postmark clients, not as Cognidesk-owned generated operations.",
  ],
  metadata: {
    implementation: {
      strategy: "official-sdk",
      sdkPackage: "postmark",
      sdkVersionRange: "^4.0.7",
      verifiedPackageVersion: "4.0.7",
      verifiedAt: "2026-06-21",
      manifestImport: "no-sdk-client-initialization",
      integrationKitStatus: "implemented",
    },
    channelCoverage: {
      inboundWebhook: "typed-parse",
      sendEmail: "provider-supported-via-official-sdk",
      templateSend: "provider-supported-via-official-sdk",
      messageDetails: "provider-supported-via-official-sdk",
      messageStreams: "provider-supported-via-official-sdk",
      suppressions: "provider-supported-via-official-sdk",
      fullProviderApiClone: "not-covered",
    },
    rawClientEscapeHatch: "Postmark ServerClient and optional AccountClient exposed from createPostmarkEmailClient().rawClients",
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
