import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { GENESYS_CLOUD_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  GENESYS_CLOUD_FULL_API_OPERATION_COUNT,
  GENESYS_CLOUD_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const genesysCloudContactCenterProviderManifest = defineProviderPackage({
  id: "contactCenter.genesys-cloud",
  name: "Genesys Cloud CX",
  packageName: "@cognidesk/integrations",
  provider: "genesys-cloud",
  category: "contactCenter",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    { id: "genesys-cloud-region", label: "Genesys Cloud API region/base URL", required: true },
    {
      id: "genesys-cloud-api-access",
      label: "Genesys Cloud OAuth access",
      scopes: ["conversation:callback:create", "routing:queue:view", "user:me:view"],
      required: true,
      metadata: {
        scopeKind: "provider-permission-labels",
        privilegeGuidance: "Genesys Cloud OAuth clients require roles/permissions such as conversation:callback:create, routing:queue:view, and user:me:view; these are permission labels for the org configuration.",
      },
    },
    {
      id: "genesys-cloud-routing",
      label: "Genesys Cloud queue, callback, or digital messaging routing configuration",
      required: false,
    },
    {
      id: "genesys-cloud-open-messaging",
      label: "Genesys Cloud Open Messaging integration and webhook secret",
      description: "Requires an Open Messaging integration, Messaging > Integration > All permission, and the optional webhook signature secret when outbound webhooks are enabled.",
      scopes: ["Messaging > Integration > All"],
      required: false,
      metadata: {
        scopeKind: "provider-permission-labels",
        privilegeGuidance: "This is a Genesys Cloud permission label, not an OAuth scope string.",
      },
    },
  ],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in the current official Genesys Cloud Platform API Swagger exposed at /api/v2/docs/swagger.",
      "The package keeps typed support helpers for callback creation, Open Messaging inbound API message/event/receipt requests, Open Messaging outbound webhook signature validation, conversation read, queue listing, and current-user readiness.",
      "Genesys Cloud handoff is not limited to voice or callback: this package types Open Messaging digital ingress for chat-like third-party messaging handoff into Genesys ACD.",
      "Native Genesys Cloud Messenger customer-site JavaScript behavior is not a server-side REST endpoint, but all REST configuration/deployment endpoints in the Swagger are exposed through generated functions.",
    ],
    evidence: [
      { label: "Genesys Cloud Platform API Swagger", url: "https://api.mypurecloud.com/api/v2/docs/swagger" },
      { label: "Genesys APIs by Service", url: "https://all.docs.genesys.com/Developer/APIbyService" },
      { label: "Genesys Cloud Developer Center", url: "https://developer.genesys.cloud/" },
      { label: "Genesys Cloud API Explorer Create Callback", url: "https://developer.genesys.cloud/devapps/api-explorer#post-api-v2-conversations-callbacks" },
      { label: "Genesys Cloud Open Messaging inbound endpoint deprecation", url: "https://help.genesys.cloud/announcements/deprecation-current-open-messaging-inbound-endpoint/" },
      { label: "Genesys Cloud Configure Open Messaging", url: "https://help.genesys.cloud/articles/configure-an-open-messaging-integration/" },
      { label: "Genesys Cloud Web Chat widgets", url: "https://help.genesys.cloud/articles/about-widgets-for-web-chat/" },
      { label: "Genesys Cloud Web Messaging overview", url: "https://help.genesys.cloud/articles/web-messaging-overview/" },
      { label: "Genesys Cloud Conversations API overview", url: "https://developer.genesys.cloud/api/rest/v2/conversations/overview.html" },
      { label: "Genesys Cloud Routing APIs", url: "https://developer.genesys.cloud/api/rest/v2/routing/" },
    ],
  },
  capabilities: [
    {
      capability: "handoff",
      label: "Create Genesys Cloud callback or Open Messaging ingress",
      description: "Creates SDK-configured Genesys Cloud support-workflow requests and typed callback/Open Messaging deliveries; native transfer, chat, Web Messaging, and Messenger REST operations are available through generated fullApi functions rather than this generic handoff capability.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "genesysCloudCallback", label: "Genesys Cloud Callback" },
        { kind: "genesysCloudOpenMessage", label: "Genesys Cloud Open Messaging inbound message/event/receipt" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "contact-center.open-messaging-ingress",
      label: "Deliver Genesys Cloud Open Messaging ingress",
      description: "Delivers customer-originated messages, events, and receipts into a configured Genesys Cloud Open Messaging integration; this is not native Web Messaging, Messenger, or human-transfer coverage.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "genesysCloudOpenMessage", label: "Genesys Cloud Open Messaging inbound message/event/receipt" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
      extension: true,
    },
    {
      capability: "send",
      label: "Create outbound callback",
      description: "Supports outbound callback creation only when the SDK configuration enables it and the Genesys org supports it.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "genesysCloudCallback", label: "Genesys Cloud Callback" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Genesys handoffs can include customer phone numbers, callback windows, summaries, and queue/agent routing metadata.",
    "Open Messaging ingress can include customer identity, message content, channel metadata, and third-party conversation identifiers.",
    "OAuth credentials stay server-side and Studio only receives readiness status.",
  ],
  limitations: [
    "Genesys regions, OAuth scopes/permissions, queues, callback eligibility, Architect flows, digital integrations, and outbound policy are SDK-user configuration.",
    "Generated fullApi/requestOperation functions expose documented Genesys Cloud REST operations; configured handoff paths remain limited to SDK-owned workflow wiring.",
    "Genesys Cloud Messenger JavaScript SDK usage is a separate customer-site implementation surface; REST web chat, Web Messaging, Messenger deployment, transfer, routing, conversation, and messaging operations are exposed through generated fullApi functions.",
  ],
  metadata: {
    channelCoverage: {
      fullPlatformRestApiOperations: "generated-per-operation-functions",
      voiceCall: "generated-full-surface",
      callback: "typed-create-and-generated-full-surface",
      callbackHandoff: "typed-create-and-generated-full-surface",
      nativeVoiceHandoff: "generated-full-surface",
      nativeChatHandoff: "generated-full-surface",
      webMessagingGuestApi: "generated-full-platform-admin-surface",
      messengerJavascriptSdk: "provider-supported-customer-site-not-typed",
      openMessagingAcdHandoff: "typed-digital-ingress-message-event-receipt-and-generated-full-surface",
      openMessagingInboundApi: "typed-digital-ingress-message-event-receipt-and-generated-full-surface",
      openMessagingOutboundWebhookSignature: "typed-verify-only",
      openMessagingWebhookParser: "not-covered",
      nativeWebMessaging: "generated-full-platform-admin-surface",
      webMessagingMessenger: "generated-full-platform-admin-surface",
      webChatWidget: "legacy-provider-supported-customer-site-not-typed",
      transfer: "generated-full-surface",
    },
    fullProviderApiVerification: {
      provider: "genesys-cloud",
      apiVersion: GENESYS_CLOUD_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-17",
      coverageArtifact: "docs/provider-coverage/genesys-cloud-full-api-2026-06-17.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/genesys-cloud-full-api-2026-06-17.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/genesys-cloud-full-api-2026-06-17.functions.json",
      documentedOperationCount: GENESYS_CLOUD_FULL_API_OPERATION_COUNT,
      implementedOperationCount: GENESYS_CLOUD_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: GENESYS_CLOUD_FULL_API_GENERATED_FUNCTION_COUNT,
    },
    deploymentModes: {
      cloud: "supported",
      engageOnPremises: "separate-package-supported",
      pureConnectOnPremises: "separate-package-supported",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
