import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

const WHEREBY_FULL_API_SPEC_VERSION = "v1";
const WHEREBY_FULL_API_PATH_COUNT = 20;
const WHEREBY_FULL_API_OPERATION_COUNT = 27;
const WHEREBY_FULL_API_GENERATED_FUNCTION_COUNT = 27;

export const wherebyVideoProviderManifest = defineProviderPackage({
  id: "video.whereby",
  name: "Whereby Embedded",
  packageName: "@cognidesk/integration-video-whereby",
  provider: "whereby",
  category: "video",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Whereby's official public REST OpenAPI spec.",
      "Typed convenience helpers remain available for meetings, room theme tokens/media, recordings, transcriptions, beta summaries, insights, signed webhook parsing, and live readiness checks.",
      "This support slice is limited to the Whereby REST API surface; browser/mobile SDK behavior, live media transport, embedded UI control, assistants, web-component APIs, React/React Native SDKs, camera effects, customer S3 policy, and webhook event catalogs are separate Whereby surfaces.",
      "The SDK user owns consent, recording/transcription/summarization eligibility, data retention, host/viewer URL distribution, room branding policy, and feature-gated beta availability decisions.",
    ],
    evidence: [
      { label: "Whereby REST OpenAPI spec", url: "https://raw.githubusercontent.com/whereby/docs/main/.gitbook/assets/_api-reference-docs-openapi.json" },
      { label: "Whereby REST meetings API", url: "https://docs.whereby.com/reference/whereby-rest-api-reference/meetings" },
      { label: "Whereby REST recordings API", url: "https://docs.whereby.com/reference/whereby-rest-api-reference/recordings" },
      { label: "Whereby REST transcriptions API", url: "https://docs.whereby.com/reference/whereby-rest-api-reference/transcriptions" },
      { label: "Whereby REST summaries API", url: "https://docs.whereby.com/reference/whereby-rest-api-reference/summaries" },
      { label: "Whereby webhooks reference", url: "https://docs.whereby.com/reference/webhooks-reference" },
    ],
  },
  credentialRequirements: [
    {
      id: "whereby-api-key",
      label: "Whereby API key",
      description: "Server-side API key used as a bearer token for Whereby Embedded REST API calls.",
      required: true,
    },
    {
      id: "whereby-organization",
      label: "Whereby organization/subdomain",
      description: "SDK-user-selected Embedded organization or subdomain used for readiness display and room URL policy.",
      required: false,
    },
    {
      id: "whereby-room-template",
      label: "Whereby room template policy",
      description: "SDK-user-owned room mode, room-name prefix, template type, host/viewer URL exposure, recording, transcription, and streaming policy.",
      required: false,
    },
    {
      id: "whereby-webhook-signing-secret",
      label: "Whereby webhook signing secret",
      description: "Endpoint signing secret from the Whereby Embedded dashboard used to validate Whereby-Signature HMAC headers.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "schedule",
      label: "Schedule Whereby video rooms",
      description: "Creates transient Whereby Embedded meeting rooms from SDK-user-owned scheduling and escalation policy.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "wherebyMeeting", label: "Whereby Meeting" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Whereby meetings",
      description: "Creates Whereby transient meeting rooms, transcription jobs, and summary jobs with SDK-user-provided recording, transcription, and retention policy.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "wherebyMeeting", label: "Whereby Meeting" },
        { kind: "wherebyTranscription", label: "Whereby Transcription" },
        { kind: "wherebySummary", label: "Whereby Summary" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Whereby meetings",
      description: "Lists and reads Whereby transient meetings, recordings, transcription metadata/access links, and beta summaries for SDK-user-selected support workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "wherebyMeeting", label: "Whereby Meeting" },
        { kind: "wherebyRecording", label: "Whereby Recording" },
        { kind: "wherebyTranscription", label: "Whereby Transcription" },
        { kind: "wherebySummary", label: "Whereby Summary" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "delete-provider-object",
      label: "Delete Whereby meetings",
      description: "Deletes Whereby transient meetings, recordings, transcriptions, and beta summaries when SDK-user lifecycle or retention policy permits deletion.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "wherebyMeeting", label: "Whereby Meeting" },
        { kind: "wherebyRecording", label: "Whereby Recording" },
        { kind: "wherebyTranscription", label: "Whereby Transcription" },
        { kind: "wherebySummary", label: "Whereby Summary" },
      ],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Whereby room theme",
      description: "Updates supported Whereby room configuration such as theme color tokens for SDK-user-owned branded room experiences.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "wherebyRoomTheme", label: "Whereby Room Theme" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      capability: "receive",
      label: "Receive Whereby webhooks",
      description: "Validates and parses Whereby room, session, recording, transcription, and assistant webhook events.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "wherebyWebhookEvent", label: "Whereby Webhook Event" },
        { kind: "wherebyMeeting", label: "Whereby Meeting" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "whereby.request-signature",
      label: "Validate Whereby webhook signatures",
      description: "Validates Whereby-Signature timestamp and v1 HMAC values with replay protection.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "wherebySignedRequest", label: "Whereby Signed Request" }],
      requiresCredential: true,
      extension: true,
      exposesSensitiveData: true,
    },
  ],
  operations: [
    {
      alias: "video.meeting.create",
      capability: "create-provider-object",
      providerObject: "wherebyMeeting",
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "video.meeting.list",
      capability: "read-provider-object",
      providerObject: "wherebyMeeting",
      exposesSensitiveData: true,
    },
    {
      alias: "video.meeting.read",
      capability: "read-provider-object",
      providerObject: "wherebyMeeting",
      exposesSensitiveData: true,
    },
    {
      alias: "video.meeting.delete",
      capability: "delete-provider-object",
      providerObject: "wherebyMeeting",
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "whereby.room-theme.update",
      capability: "update-provider-object",
      providerObject: "wherebyRoomTheme",
      extension: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      alias: "whereby.rest.request",
      capability: "read-provider-object",
      providerObject: "wherebyRestOperation",
      extension: true,
      metadata: { supportSliceEscapeHatch: true },
    },
    {
      alias: "whereby.webhook.parse",
      capability: "receive",
      providerObject: "wherebyWebhookEvent",
      extension: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Whereby meeting URLs, host URLs, viewer URLs, room names, session IDs, participant identifiers, display names, metadata, external IDs, recording metadata, and transcription metadata can contain customer or support data.",
    "Whereby API keys and webhook signing secrets stay server-side and are represented in Studio only as readiness metadata.",
    "Consent for video, recording, transcription, streaming, assistant usage, outbound scheduling, retention, and deletion remains SDK-user-owned configuration.",
  ],
  limitations: [
    "Whereby meetings are transient rooms controlled by the SDK user's Embedded account, API key, plan, dashboard configuration, and current Whereby feature availability.",
    "Whereby's documented meeting API supports create, list, get, and delete; meeting mutation is limited by Whereby to the documented room theme endpoints.",
    "This package provides REST and webhook primitives only; it does not decide channel eligibility, consent, recording/transcription policy, handoff timing, or which users receive host/viewer URLs.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://docs.whereby.com/reference/whereby-rest-api-reference/meetings",
    channelCoverage: {
      meetings: "typed-create-list-read-delete",
      roomTheme: "typed-update",
      recordings: "typed-list-read-access-link-delete",
      transcriptions: "typed-create-list-read-access-link-delete",
      summaries: "typed-create-list-read-delete",
      insights: "typed-list-read",
      webhooks: "typed-validate-parse",
      restApiOperations: "generated-constrained-support-slice",
      browserSdkLiveMediaEmbeddedUiAssistants: "provider-supported-not-typed-separate-surface",
    },
    generatedSupportSliceVerification: {
      provider: "whereby-rest",
      apiVersion: WHEREBY_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-21",
      sourceChecksumSha256: "3d9aec0774ff42f149cfc67e94ae9b70c617957e278a5e89920807274d8cd77d",
      coverageArtifact: "docs/provider-coverage/whereby-full-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/whereby-full-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/whereby-full-api-2026-06-18.functions.json",
      operationCatalogChecksumSha256: "690fac858b8041598c7297147e5635e227f86b1fd1545e047182839d5fd2803a",
      functionCatalogChecksumSha256: "d33fa387bc6cd105db3e21b743e68102d483b7e3dacd0b4c1bedd85be5bc07ef",
      documentedPathCount: WHEREBY_FULL_API_PATH_COUNT,
      documentedOperationCount: WHEREBY_FULL_API_OPERATION_COUNT,
      implementedOperationCount: WHEREBY_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: WHEREBY_FULL_API_GENERATED_FUNCTION_COUNT,
      allowlist: [
        "POST /meetings",
        "GET /meetings",
        "GET /meetings/{meetingId}",
        "DELETE /meetings/{meetingId}",
        "GET /recordings",
        "GET /recordings/{recordingId}",
        "GET /recordings/{recordingId}/access-link",
        "POST /recordings/bulk-delete",
        "DELETE /recordings/{recordingId}",
        "POST /transcriptions",
        "GET /transcriptions",
        "GET /transcriptions/{transcriptionId}",
        "GET /transcriptions/{transcriptionId}/access-link",
        "POST /transcriptions/bulk-delete",
        "DELETE /transcriptions/{transcriptionId}",
        "POST /summaries",
        "GET /summaries",
        "GET /summaries/{summaryId}",
        "DELETE /summaries/{summaryId}",
        "PUT /rooms/{roomName}/theme/tokens",
        "PUT /rooms/{roomName}/theme/logo",
        "PUT /rooms/{roomName}/theme/room-background",
        "PUT /rooms/{roomName}/theme/room-knock-page-background",
        "GET /insights/rooms",
        "GET /insights/room-sessions",
        "GET /insights/participants",
        "GET /insights/participant",
      ],
    },
    sdkViability: {
      decision: "no-official-maintained-server-rest-sdk-found",
      checkedAt: "2026-06-21",
      rejectedSdkPackages: [
        {
          packageName: "@whereby.com/browser-sdk",
          reason: "Official browser SDK for custom video UI, not a server REST API client.",
        },
        {
          packageName: "@whereby.com/core",
          reason: "Official media/core SDK requiring browser or WebRTC polyfills, not a REST client.",
        },
        {
          packageName: "@whereby.com/assistant-sdk",
          reason: "Official Node assistant/media SDK with beta/plan constraints, not REST resource management.",
        },
      ],
    },
  },
});
