import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const instagramSocialProviderManifest = defineProviderPackage({
  id: "social.instagram",
  name: "Instagram Direct Messages",
  packageName: "@cognidesk/social-instagram",
  provider: "instagram",
  category: "social",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  credentialRequirements: [
    {
      id: "instagram-page-access-token",
      label: "Meta Page access token",
      description: "Server-side Page access token used for Instagram Messaging and Graph API calls.",
      scopes: [
        "instagram_manage_messages",
        "instagram_basic",
        "pages_messaging",
        "pages_show_list",
        "pages_read_engagement",
        "pages_manage_metadata",
      ],
      required: true,
      metadata: { scopeKind: "provider-permission-labels" },
    },
    {
      id: "instagram-page-id",
      label: "Facebook Page ID",
      description: "Facebook Page connected to the SDK user's Instagram professional account.",
      required: true,
    },
    {
      id: "instagram-business-account-id",
      label: "Instagram business account ID",
      description: "Instagram professional account ID used for conversations, profile, and webhook ownership checks.",
      required: true,
    },
    {
      id: "instagram-app-secret",
      label: "Meta app secret",
      description: "Server-side app secret used to validate X-Hub-Signature-256 webhook deliveries.",
      required: true,
    },
    {
      id: "instagram-webhook-verify-token",
      label: "Webhook verify token",
      description: "SDK-user-owned token checked during Meta webhook endpoint verification.",
      required: false,
    },
    {
      id: "instagram-page-webhook-subscription",
      label: "Instagram messaging webhook subscription",
      description: "SDK-user-confirmed Page/app subscription to Instagram messaging webhook fields.",
      required: false,
    },
    {
      id: "instagram-permissions",
      label: "Instagram Graph permissions",
      description: "SDK-user-reviewed permissions granted to the Meta app for messaging and account access.",
      scopes: [
        "instagram_manage_messages",
        "instagram_basic",
        "pages_messaging",
        "pages_read_engagement",
        "pages_manage_metadata",
      ],
      required: true,
      metadata: { scopeKind: "provider-permission-labels" },
    },
  ],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is limited to Instagram Messaging send payloads, conversations/messages reads, account/page reads, webhook challenge handling, and X-Hub-Signature-256 validation for SDK-user-owned support messaging.",
      "This package uses the Meta Business Messaging / Page access token model for Instagram Messaging; it does not implement the separate Instagram API with Instagram Login messaging surface.",
      "The package does not implement the broader Instagram Platform for media publishing, comments/moderation, mentions, insights, content discovery, account management, or full Graph API coverage.",
    ],
    evidence: [
      { label: "Instagram Messaging overview", url: "https://developers.facebook.com/documentation/business-messaging/instagram-messaging/overview" },
      { label: "Instagram Messaging send message", url: "https://developers.facebook.com/documentation/business-messaging/instagram-messaging/features/send-message" },
      { label: "Instagram Messaging webhooks", url: "https://developers.facebook.com/documentation/business-messaging/instagram-messaging/webhooks" },
      { label: "Instagram Messaging app review", url: "https://developers.facebook.com/documentation/business-messaging/instagram-messaging/app-review" },
    ],
  },
  capabilities: [
    {
      capability: "receive",
      label: "Receive Instagram DM webhooks",
      description: "Validates and parses Meta webhook payloads after the SDK user's Page/app is subscribed to Instagram messaging webhook fields.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "instagramWebhook", label: "Instagram Webhook" },
        { kind: "instagramDirectMessage", label: "Instagram Direct Message" },
        { kind: "instagramConversation", label: "Instagram Conversation" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Instagram DM messages",
      description: "Sends Instagram direct messages through Meta Graph API inside the 24-hour response window, or with HUMAN_AGENT human-support review where Meta permits up to 7 days.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "instagramDirectMessage", label: "Instagram Direct Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Build Instagram DM payloads",
      description: "Builds Instagram messaging payloads for SDK-user-configured approval and routing workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "instagramMessageDraft", label: "Instagram Message Draft" }],
      requiresCredential: false,
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Instagram conversations",
      description: "Associates provider conversation and message IDs with Cognidesk conversation policy selected by SDK users.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "instagramConversation", label: "Instagram Conversation" },
        { kind: "instagramDirectMessage", label: "Instagram Direct Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Instagram account and messages",
      description: "Reads Instagram professional account, page, conversations, messages, and message details where Graph APIs support it.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "instagramAccount", label: "Instagram Account" },
        { kind: "instagramPage", label: "Facebook Page" },
        { kind: "instagramConversation", label: "Instagram Conversation" },
        { kind: "instagramDirectMessage", label: "Instagram Direct Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "List Instagram conversations",
      description: "Lists Instagram conversations with SDK-user-supplied fields, pagination, and Graph API limits.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "instagramConversation", label: "Instagram Conversation" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "social.webhook-signature",
      label: "Validate Meta webhook signatures",
      description: "Validates X-Hub-Signature-256 using the SDK user's Meta app secret before parsing webhook JSON.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "instagramSignedWebhook", label: "Instagram Signed Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "instagram.webhook.parse",
      providerOperation: "parseInstagramWebhook",
      capability: "receive",
      providerObject: "instagramWebhook",
      label: "Parse Instagram webhook",
      description: "Validate and parse an inbound Instagram Messaging webhook request.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "instagram.message.send",
      providerOperation: "sendMessage",
      capability: "send",
      providerObject: "instagramDirectMessage",
      label: "Send Instagram message",
      description: "Send an Instagram Messaging direct message through the configured Page.",
      audiences: ["customer-facing"],
      requiresCredential: true,
      requiresApproval: true,
      externallyVisible: true,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "instagram.draft.create",
      providerOperation: "createInstagramTextMessage",
      capability: "draft",
      providerObject: "instagramMessageDraft",
      label: "Build Instagram message payload",
      description: "Build an Instagram Messaging payload for SDK-user approval workflows.",
      audiences: ["customer-facing", "mixed"],
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "instagram.conversations.list",
      providerOperation: "listConversations",
      capability: "search-provider-object",
      providerObject: "instagramConversation",
      label: "List Instagram conversations",
      description: "List Instagram conversations with SDK-user-supplied fields and pagination.",
      audiences: ["internal-support", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "instagram.conversationMessages.list",
      providerOperation: "listConversationMessages",
      capability: "read-provider-object",
      providerObject: "instagramDirectMessage",
      label: "Read Instagram conversation messages",
      description: "Read messages for an Instagram conversation.",
      audiences: ["internal-support", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "instagram.message.read",
      providerOperation: "getMessage",
      capability: "read-provider-object",
      providerObject: "instagramDirectMessage",
      label: "Read Instagram message",
      description: "Read an Instagram message by provider message ID.",
      audiences: ["internal-support", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "instagram.account.read",
      providerOperation: "getInstagramBusinessAccount",
      capability: "read-provider-object",
      providerObject: "instagramAccount",
      label: "Read Instagram account",
      description: "Read configured Instagram professional account metadata.",
      audiences: ["internal-support", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "instagram.page.read",
      providerOperation: "getPage",
      capability: "read-provider-object",
      providerObject: "instagramPage",
      label: "Read connected Facebook Page",
      description: "Read the Facebook Page connected to the Instagram professional account.",
      audiences: ["internal-support", "mixed"],
      requiresCredential: true,
      extension: true,
    },
    {
      alias: "instagram.webhook-signature",
      providerOperation: "validateInstagramWebhookSignature",
      capability: "social.webhook-signature",
      providerObject: "instagramSignedWebhook",
      label: "Validate Instagram webhook signature",
      description: "Validate Meta X-Hub-Signature-256 for Instagram webhook delivery.",
      audiences: ["internal-support"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Instagram profile identifiers, usernames, message text, attachments, reactions, read events, conversation IDs, and webhook payloads can contain customer data.",
    "Meta Page access tokens, app secrets, and webhook verify tokens stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "Available operations depend on the SDK user's Meta app review, Page ownership, Instagram professional account link, granted permissions, webhook field subscriptions, messaging windows, HUMAN_AGENT review, rate limits, and regional policy.",
    "Instagram does not inherit general Messenger message tags as safe defaults; SDK users must configure Instagram-specific outbound policy and HUMAN_AGENT review where needed.",
    "Consent, outbound-contact policy, conversation continuity across channels, human escalation, retention, redaction, and deletion behavior are SDK-user configuration.",
    "This package provides Graph API and webhook primitives; it does not decide when to auto-reply, start outbound outreach, join chats across channels, or expose social content to operators.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    channelCoverage: {
      directMessages: "typed-send",
      conversations: "typed-list-read",
      messageDetails: "typed-read",
      accountPageReadiness: "typed-read",
      webhooks: "typed-challenge-verify-parse",
      humanAgentWindow: "sdk-owned-policy",
      commentsPublishingInsights: "not-covered",
    },
    docs: [
      "https://developers.facebook.com/documentation/business-messaging/instagram-messaging/features/send-message",
      "https://developers.facebook.com/documentation/business-messaging/instagram-messaging/overview",
      "https://developers.facebook.com/documentation/business-messaging/instagram-messaging/webhooks",
    ],
    apiCoverage: {
      checkedAt: "2026-06-18",
      operationCatalog: "docs/provider-coverage/instagram-messaging-graph-selected-api-2026-06-18.operations.json",
      generatedFromOfficialSpec: false,
      machineReadableSpecStatus: "No official public complete Instagram Messaging/Graph OpenAPI spec was found in facebook/openapi during this audit.",
      selectedOperationCount: 6,
      implementedOperationCount: 6,
      fullProviderApi: false,
      fullMetaGraphCoverage: false,
    },
  },
});
