import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";

export const genesysEngageContactCenterProviderManifest = defineProviderPackage({
  id: "contactCenter.genesys-engage",
  name: "Genesys Engage / GMS",
  packageName: "@cognidesk/integrations",
  provider: "genesys-engage",
  category: "contactCenter",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    { id: "genesys-engage-gms-base-url", label: "Genesys Mobile Services base URL", required: true },
    { id: "genesys-engage-auth", label: "Genesys Engage/GMS authentication", required: false },
    { id: "genesys-engage-routing", label: "Genesys Engage callback, chat, and routing configuration", required: false },
  ],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage includes typed Genesys Mobile Services callback creation only, typed GMS Chat API v2 customer chat lifecycle/file operations, and SDK-configured REST handoff paths for deployment-specific Genesys Engage on-premises services.",
      "The package does not type the broader GMS Callback Services cancel, delete, reschedule, availability, query, queue-position, watermark, export, or callback-record operations.",
      "GMS Chat API v2 methods cover the documented customer-facing request/send/typing/refresh/disconnect/push URL/nickname/custom notice/update data/read receipt/file endpoints. WebChatService, CometD, agent desktop participation, widget behavior, and broader on-premises APIs remain outside this typed surface.",
      "The checked endpoint inventory is `docs/provider-coverage/genesys-engage-gms-api-2026-06-18.checked-inventory.json`; transfer and event delivery are provider-supported but not typed, while no GMS/WebChatService webhook subscription endpoint catalog was found in the checked official docs.",
      "Genesys Engage on-premises exposes separate GMS Callback, Chat API, WebChatService, WebRTC, Interaction SDK, and Web Services surfaces; this package does not claim full on-prem API coverage.",
    ],
    evidence: [
      { label: "Genesys APIs by Service", url: "https://all.docs.genesys.com/Developer/APIbyService" },
      { label: "Genesys GMS Callback Services API", url: "https://docs.genesys.com/Documentation/GMS/latest/API/CallbackServicesAPI" },
      { label: "Genesys GMS Chat API v2", url: "https://docs.genesys.com/Documentation/GMS/latest/API/ChatAPIv2" },
      { label: "Genesys WebChatService", url: "https://all.docs.genesys.com/WID/Current/GCAPI/WebChatService" },
    ],
  },
  capabilities: [
    {
      capability: "handoff",
      label: "Create Genesys Engage handoff",
      description: "Creates SDK-configured Genesys Engage/GMS callback, chat, or on-premises handoff requests.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "genesysEngageCallback", label: "Genesys Engage/GMS Callback" },
        { kind: "genesysEngageGmsChatV2", label: "Genesys Engage GMS Chat API v2 session" },
        { kind: "genesysEngageConfiguredChatHandoff", label: "Genesys Engage configured chat handoff" },
        { kind: "genesysEngageConfiguredCallbackHandoff", label: "Genesys Engage configured callback handoff" },
        { kind: "genesysEngageConfiguredHandoff", label: "Genesys Engage configured HTTP handoff" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "contact-center.on-prem-configured-handoff",
      label: "Create Genesys Engage configured on-prem handoff",
      description: "Creates SDK-configured Genesys Engage/GMS chat-adjacent, WebChatService-adjacent, or deployment-specific handoff requests without claiming typed chat session lifecycle coverage.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "genesysEngageConfiguredChatHandoff", label: "Genesys Engage configured chat handoff" },
        { kind: "genesysEngageConfiguredCallbackHandoff", label: "Genesys Engage configured callback handoff" },
        { kind: "genesysEngageConfiguredHandoff", label: "Genesys Engage configured HTTP handoff" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
      extension: true,
    },
    {
      capability: "send",
      label: "Create on-prem callback request",
      description: "Submits a callback creation request to a configured Genesys Mobile Services callback service; broader callback lifecycle operations are not typed in this package.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "genesysEngageCallback", label: "Genesys Engage/GMS Callback" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Genesys Engage handoffs can include phone numbers, chat-adjacent context or transcripts, routing targets, callback times, and user data configured by the SDK app.",
    "On-premises credentials and network details stay server-side; Studio receives only configuration/readiness state.",
  ],
  limitations: [
    "Genesys Engage deployment topology, service names, chat version, routing targets, and authentication are SDK-user configuration.",
    "The generic handoff helper requires an explicit configured path because on-premises deployments commonly expose different GMS, Web Services, and widget integration endpoints.",
    "WebChatService start/end/transcript/polling, GMS CometD, agent desktop participation, and widget behavior require deployment-specific typed support beyond the GMS Chat API v2 customer HTTP lifecycle exposed here.",
  ],
  metadata: {
    deploymentMode: "genesys-engage-on-premises",
    checkedInventoryArtifact: "docs/provider-coverage/genesys-engage-gms-api-2026-06-18.checked-inventory.json",
    checkedEndpointEntries: 27,
    officialMachineReadableSpec: "not-found",
    checkedWebhookCatalog: "not-found-in-checked-gms-webchatservice-docs",
    channelCoverage: {
      callback: "typed-create-only",
      callbackLifecycle: "provider-supported-not-typed",
      configuredHttpHandoff: "supported",
      gmsChatV2: "typed-customer-lifecycle",
      gmsChatV2CometD: "provider-supported-not-typed",
      gmsChatV2Lifecycle: "typed-request-send-refresh-disconnect-read-receipt",
      gmsChatV2FileManagement: "typed-limits-upload-download-delete",
      webChatService: "provider-supported-configured-http-only",
      webChatServiceLifecycle: "provider-supported-not-typed",
      webChatServiceEvents: "provider-supported-not-typed",
      events: "provider-supported-not-typed",
      transfer: "provider-supported-not-typed",
      webhooks: "not-covered",
      webRtc: "not-covered",
      interactionSdk: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
