import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const zohoDeskTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.zoho-desk",
  name: "Zoho Desk",
  packageName: "@cognidesk/integration-ticketing-zoho-desk",
  provider: "zoho-desk",
  category: "ticketing",
  trustLevel: "official",
  directions: ["bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is typed for Zoho Desk REST-backed ticket create, read, patch, ticket listing/search query passthrough, ticket comments, ticket threads, send-reply, organization readiness, and credential status used by Cognidesk support workflows.",
      "A host-injected ZohoDeskProviderClient remains available as an override for SDK-user-owned provider adapters, retry policy, or token refresh plumbing.",
      "This is not full Zoho Desk API coverage; contacts, accounts, departments, agents, teams, attachments, layouts, blueprints, assignment/skills actions, spam/trash lifecycle, webhooks, help center, analytics, and broader settings APIs remain outside this adapter.",
    ],
    evidence: [
      { label: "Zoho Desk API documentation", url: "https://desk.zoho.com/DeskAPIDocument" },
      { label: "Zoho Desk create ticket", url: "https://desk.zoho.com/DeskAPIDocument#Tickets#Tickets_Createaticket" },
      { label: "Zoho Desk list all tickets", url: "https://desk.zoho.com/DeskAPIDocument#Tickets#Tickets_Listalltickets" },
      { label: "Zoho Desk update ticket", url: "https://desk.zoho.com/DeskAPIDocument#Tickets#Tickets_Updateaticket" },
      { label: "Zoho Desk list ticket comments", url: "https://desk.zoho.com/DeskAPIDocument#TicketsComments#TicketsComments_Listallticketcomments" },
      { label: "Zoho Desk create ticket comment", url: "https://desk.zoho.com/DeskAPIDocument#TicketsComments#TicketsComments_Createticketcomment" },
      { label: "Zoho Desk list ticket threads", url: "https://desk.zoho.com/DeskAPIDocument#Threads#Threads_Listallthreads" },
      { label: "Zoho Desk send email reply", url: "https://desk.zoho.com/DeskAPIDocument#Threads#Threads_SendEmailReply" },
      { label: "Zoho Desk organizations", url: "https://desk.zoho.com/DeskAPIDocument#Organizations" },
    ],
  },
  credentialRequirements: [
    { id: "zoho-desk-org", label: "Zoho Desk organization ID", required: true },
    {
      id: "zoho-desk-api-access",
      label: "Zoho Desk OAuth access",
      scopes: ["Desk.tickets.CREATE", "Desk.tickets.READ", "Desk.tickets.UPDATE", "Desk.basic.READ"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
  ],
  capabilities: [
    { capability: "create-provider-object", label: "Create Zoho tickets", providerObjects: [{ kind: "zohoDeskTicket", label: "Zoho Desk Ticket" }], audiences: ["customer-facing", "mixed"], requiresCredential: true, sideEffect: true, exposesSensitiveData: true, changesWorkflow: true },
    { capability: "read-provider-object", label: "Read Zoho tickets", providerObjects: [
      { kind: "zohoDeskTicket", label: "Zoho Desk Ticket" },
      { kind: "zohoDeskTicketComment", label: "Zoho Desk Ticket Comment" },
      { kind: "zohoDeskThread", label: "Zoho Desk Thread" },
    ], audiences: ["internal-support", "mixed"], requiresCredential: true, exposesSensitiveData: true },
    { capability: "update-provider-object", label: "Update Zoho tickets", providerObjects: [{ kind: "zohoDeskTicket", label: "Zoho Desk Ticket" }], audiences: ["internal-support", "mixed"], requiresCredential: true, sideEffect: true, exposesSensitiveData: true, changesWorkflow: true },
    { capability: "search-provider-object", label: "Search Zoho tickets", providerObjects: [{ kind: "zohoDeskTicket", label: "Zoho Desk Ticket" }], audiences: ["internal-support", "mixed"], requiresCredential: true, exposesSensitiveData: true },
    { capability: "handoff", label: "Attach handoff to Zoho Desk", providerObjects: [
      { kind: "zohoDeskTicket", label: "Zoho Desk Ticket" },
      { kind: "zohoDeskTicketComment", label: "Zoho Desk Ticket Comment" },
      { kind: "zohoDeskThread", label: "Zoho Desk Thread" },
      { kind: "zohoDeskReply", label: "Zoho Desk Reply" },
    ], audiences: ["customer-facing", "internal-support", "mixed"], requiresCredential: true, sideEffect: true, exposesSensitiveData: true, changesWorkflow: true },
  ],
  privacyNotes: ["Zoho Desk tickets can contain customer messages, contact details, SLA state, assignments, and internal comments."],
  limitations: [
    "Departments, layouts, mandatory fields, assignment rules, blueprints, and visibility are SDK-user configuration.",
    "This package provides a constrained Zoho Desk REST/fetch transport for the declared support workflow operations; SDK users still own retry, rate-limit, OAuth token refresh, and regional endpoint policy beyond dataCenter/apiBaseUrl selection.",
  ],
  metadata: {
    implementation: {
      strategy: "provider-rest-adapter",
      adapterKind: "no-official-sdk-rest-adapter",
      runtimePackage: "@cognidesk/integration-ticketing-zoho-desk",
      providerClientInterface: "ZohoDeskProviderClient",
      defaultClientPolicy: "use-built-in-rest-adapter-when-orgId-and-accessToken-are-configured",
      providerClientOverride: true,
      packageOwnedRestClient: true,
      officialRuntimeSdkAvailable: false,
      manifestImport: "no-client-initialization",
    },
    implementationStrategy: "no-official-sdk-rest-adapter",
    providerClient: {
      package: "built-in-provider-rest-adapter",
      interface: "ZohoDeskProviderClient",
      importPolicy: "runtime-entrypoint-only",
      defaultClientPolicy: "configured-rest-default-with-host-client-override",
      sdkDecision: {
        checkedAt: "2026-06-25",
        result: "no-official-sdk-rest-adapter",
        notes: [
          "Zoho's official Desk developer resources document REST APIs and a Java SDK; the Java SDK is not suitable as a Node/TypeScript package dependency for this adapter.",
          "@zohodesk/js-api-creator is a generic JavaScript API builder, not a dedicated official Zoho Desk ticketing provider client for this support workflow slice.",
          "Zoho Desk ASAP/Web SDK documentation targets embedded help-center or extension widgets, not backend ticketing provider operations.",
        ],
      },
    },
    providerRestAdapterException: {
      status: "accepted",
      reviewedAt: "2026-06-25",
      adapterKind: "no-official-sdk-rest-adapter",
      reason: "No maintained official Zoho Desk Node/TypeScript runtime SDK was verified for backend ticketing operations; Zoho's official Desk SDK documentation is Java- or browser/widget-oriented for the surfaces checked.",
      allowedDefaultRuntime: "built-in-rest-adapter",
      hostSdkPath: "ZohoDeskProviderClient",
      guardrails: [
        "Keep backend ticketing calls behind ZohoDeskProviderClient and the built-in REST adapter until an official maintained Node/TypeScript Zoho Desk runtime SDK exists.",
        "Do not add @zohodesk/js-api-creator as the default provider SDK; it is a generic API builder, not a typed Zoho Desk ticketing client.",
        "If an official maintained runtime SDK is adopted later, switch implementation.strategy away from provider-rest-adapter and add a normal package.json runtime dependency.",
      ],
    },
    checkedProviderSdk: {
      checkedAt: "2026-06-25",
      verdict: "no-official-sdk-rest-adapter",
      officialRuntimeSdkAvailable: false,
      candidates: [
        {
          package: "Zoho Desk Java SDK",
          result: "not-node-typescript-runtime",
          reason: "Official SDK for Java applications; it is not a runtime package this Node/TypeScript provider package can import.",
          source: "https://www.zoho.com/desk/developers/javasdk/",
        },
        {
          package: "@zohodesk/js-api-creator",
          checkedVersion: "1.0.25",
          result: "not-provider-ticketing-sdk",
          reason: "Maintained JavaScript package, but its README describes a generic API builder rather than a dedicated Zoho Desk typed raw client.",
          source: "https://www.npmjs.com/package/@zohodesk/js-api-creator",
        },
        {
          package: "Zoho Desk extension JS SDK bundle",
          result: "not-backend-runtime-sdk",
          reason: "Extension widget SDK loaded from Zoho-hosted browser script after ZOHODESK.extension.onload(); it is not a server-side REST client dependency.",
          source: "https://help.zoho.com/portal/en/community/topic/building-extensions-8-create-widgets-using-the-js-sdk-bundle-in-the-zoho-desk-platform-part-1",
        },
        {
          package: "Zoho Desk ASAP JavaScript APIs",
          result: "not-backend-runtime-sdk",
          reason: "ASAP JavaScript APIs target embedded help-widget behavior in website pages, not backend ticket create/read/update/reply operations.",
          source: "https://www.zoho.com/desk/developers/asap/",
        },
      ],
      sources: [
        "https://www.zoho.com/desk/developers/",
        "https://www.zoho.com/desk/developers/javasdk/",
        "https://www.npmjs.com/package/@zohodesk/js-api-creator",
        "https://help.zoho.com/portal/en/community/topic/building-extensions-8-create-widgets-using-the-js-sdk-bundle-in-the-zoho-desk-platform-part-1",
        "https://www.zoho.com/desk/developers/asap/",
      ],
    },
    checkedProviderApiCoverage: {
      verifiedAt: "2026-06-18",
      sourceKind: "checked-endpoint-family-inventory",
      coverageArtifact: "docs/provider-coverage/zoho-desk-checked-rest-api-2026-06-18.inventory.json",
      checkedFamilyCount: 5,
      delegatedFamilyCount: 0,
      gapFamilyCount: 1,
      delegatedOperationCount: 0,
      packageOwnedProviderOperationCount: 9,
    },
    channelCoverage: {
      tickets: "typed-rest-create-read-update-list",
      comments: "typed-rest-create-list",
      threads: "typed-rest-list",
      replies: "typed-rest-send",
      organizationsReadiness: "typed-rest-read",
      contactsAccountsAgentsDepartments: "provider-supported-not-typed",
      attachmentsBlueprintsWebhooks: "provider-supported-not-typed",
      slasAssignmentsSkills: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
