import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { OUTLOOK_GRAPH_API_GENERATED_FUNCTION_COUNT } from "./graph-api-client.generated.js";
import {
  OUTLOOK_GRAPH_API_OPERATION_COUNT,
  OUTLOOK_GRAPH_API_PATH_COUNT,
  OUTLOOK_GRAPH_API_SPEC_VERSION,
} from "./graph-api-operations.generated.js";

export const outlookEmailProviderManifest = defineProviderPackage({
  id: "email.outlook",
  name: "Microsoft Outlook",
  packageName: "@cognidesk/integrations",
  provider: "outlook",
  category: "email",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage includes generated per-operation functions for the Microsoft Graph v1.0 Outlook mailbox slice used by this package: /me and /users/{user-id}, messages, mailFolders, message attachments, sendMail, subscriptions, and Outlook category paths.",
      "Typed convenience helpers remain available for selected Microsoft Graph Outlook mail workflows: message list/get, draft creation, sendMail, message update, folder delta sync, attachment list/get/raw-value reads, mailbox-user readiness, webhook clientState validation, and subscription creation.",
      "This is not full Microsoft Graph coverage; the complete Graph v1.0 OpenAPI currently has tens of thousands of operations across many Microsoft 365 services. Calendar, contacts, Teams, files/Drive, identity, admin, security, and broader Graph resources remain outside this Outlook adapter unless represented in the mailbox slice.",
    ],
    evidence: [
      { label: "Microsoft Graph OpenAPI registry", url: "https://github.com/microsoftgraph/msgraph-metadata/blob/master/apis.yaml" },
      { label: "Microsoft Graph v1.0 OpenAPI", url: "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml" },
      { label: "Microsoft Graph create message", url: "https://learn.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0" },
      { label: "Microsoft Graph sendMail", url: "https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0" },
      { label: "Microsoft Graph update message", url: "https://learn.microsoft.com/en-us/graph/api/message-update?view=graph-rest-1.0" },
      { label: "Microsoft Graph message delta", url: "https://learn.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0" },
      { label: "Microsoft Graph list attachments", url: "https://learn.microsoft.com/en-us/graph/api/message-list-attachments?view=graph-rest-1.0" },
      { label: "Microsoft Graph get attachment", url: "https://learn.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0" },
      { label: "Microsoft Graph create subscription", url: "https://learn.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0" },
      { label: "Microsoft Graph webhook subscription lifecycle", url: "https://learn.microsoft.com/en-us/graph/change-notifications-delivery-webhooks" },
    ],
  },
  credentialRequirements: [
    {
      id: "microsoft-graph-oauth-access-token",
      label: "Microsoft Graph OAuth access token",
      description: "Server-side OAuth access token for Microsoft Graph mail APIs. Required permissions are operation-specific; sendMail can use Mail.Send while delta/subscription reads can use read permissions.",
      scopes: ["Mail.Read", "Mail.ReadWrite", "Mail.Send", "User.Read"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "microsoft-graph-mailbox-user",
      label: "Mailbox user",
      description: "Delegated /me mailbox access or a configured Microsoft Graph user ID/userPrincipalName.",
      required: false,
    },
    {
      id: "microsoft-graph-webhook-client-state",
      label: "Webhook clientState secret",
      description: "SDK-user-owned clientState value used to validate Microsoft Graph change notifications.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Read Outlook messages",
      description: "Lists and reads Microsoft Graph message resources from the configured Outlook mailbox.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "outlookMailboxUser", label: "Outlook Mailbox User" },
        { kind: "outlookMessage", label: "Outlook Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Create Outlook drafts",
      description: "Creates Microsoft Graph draft message resources for SDK-user-configured approval workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "outlookMessage", label: "Outlook Draft Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Outlook mail",
      description: "Calls Microsoft Graph sendMail when SDK-user policy permits outbound contact.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "outlookMessage", label: "Outlook Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Outlook conversations",
      description: "Associates messages with Microsoft Graph conversation IDs and internet message headers.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "outlookConversation", label: "Outlook Conversation" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "attach",
      label: "Read Outlook attachment content",
      description: "Reads Microsoft Graph attachment metadata and raw attachment contents for SDK-user-governed attachment handling.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "outlookAttachment", label: "Outlook Attachment" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Outlook messages",
      description: "Updates Microsoft Graph message fields such as categories, importance, read state, or draft content when SDK-user policy permits mutation.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "outlookMessage", label: "Outlook Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "outlook.webhook-client-state",
      label: "Validate Outlook webhook clientState",
      description: "Validates Microsoft Graph change notification clientState values with the SDK user's configured secret.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "outlookChangeNotification", label: "Outlook Change Notification" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Outlook messages can contain customer content, attachments, addresses, recipients, categories, internet headers, calendar-style metadata, and conversation history.",
    "Microsoft Graph OAuth access tokens and webhook clientState secrets stay server-side and are represented in Studio only as credential readiness.",
    "SDK users own outbound approval, auto-send controls, contact consent, tenant/admin policy review, retention, redaction, attachment retrieval, and deletion behavior.",
  ],
  limitations: [
    "Available operations depend on Microsoft Graph permissions, OAuth grant type, tenant admin consent, conditional access, mailbox licensing, Exchange Online policy, and delegated or application user selection.",
    "This package provides transport and webhook foundations; it does not choose default automation, retention, consent, promotional messaging, tenant-wide access, retry, or rate-limit policies.",
    "Webhook validation is based on Microsoft Graph clientState matching. The generated mailbox slice exposes subscription renewal/delete/reauthorize operations, while encrypted resource data decryption, expiration monitoring policy, retry, and reauthorization timing are SDK-user integration responsibilities.",
  ],
  metadata: {
    channelCoverage: {
      messages: "typed-list-get-delta-update",
      drafts: "typed-create",
      sendMail: "typed-send",
      attachments: "typed-list-get-download",
      subscriptions: "typed-create",
      webhookClientState: "typed-validate",
      mailboxUser: "typed-read",
      graphMailboxSlice: "generated-per-operation-functions",
      subscriptionRenewDelete: "generated-full-slice",
      mailFolderRulesCategoriesUploadSessions: "generated-full-slice",
    },
    generatedProviderApiVerification: {
      provider: "microsoft-graph-outlook-mailbox-slice",
      apiVersion: OUTLOOK_GRAPH_API_SPEC_VERSION,
      verifiedAt: "2026-06-17",
      coverageArtifact: "docs/provider-coverage/outlook-graph-api-2026-06-17.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/outlook-graph-api-2026-06-17.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/outlook-graph-api-2026-06-17.functions.json",
      documentedPathCount: OUTLOOK_GRAPH_API_PATH_COUNT,
      documentedOperationCount: OUTLOOK_GRAPH_API_OPERATION_COUNT,
      implementedOperationCount: OUTLOOK_GRAPH_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: OUTLOOK_GRAPH_API_GENERATED_FUNCTION_COUNT,
      slice: "Microsoft Graph v1.0 Outlook mailbox paths only; not full Microsoft Graph.",
    },
    permissionAlternatives: {
      sendMail: {
        delegated: ["Mail.Send"],
        application: ["Mail.Send"],
      },
      messageDelta: {
        delegatedLeastPrivileged: ["Mail.ReadBasic"],
        delegatedHigherPrivileged: ["Mail.Read", "Mail.ReadWrite"],
        applicationLeastPrivileged: ["Mail.ReadBasic.All"],
        applicationHigherPrivileged: ["Mail.Read", "Mail.ReadWrite"],
      },
      subscriptionCreate: {
        rule: "Microsoft Graph requires read permission for the subscribed resource; typed helpers create subscriptions while the generated mailbox slice also exposes subscription update/delete/reauthorize operations.",
      },
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
