import type { ProviderManifestInput } from "@cognidesk/integration-kit";
import { defineIntegrationProviderPackage } from "../../provider-manifest.js";

// Metadata-only legacy catalog input. The executable Outlook adapter lives in
// integrations/email/outlook and is not re-exported from @cognidesk/integrations.

export const outlookEmailOperationAliases = {
  receive: "email.receive",
  send: "email.send",
  draftCreate: "email.draft.create",
  attachmentsRead: "email.attachments.read",
  mailboxWatch: "mailbox.watch",
  messageList: "outlook.message.list",
  messageGet: "outlook.message.get",
  messageDelta: "outlook.message.delta",
  messageUpdate: "outlook.message.update",
  mailboxUserGet: "outlook.mailboxUser.get",
  webhookParse: "outlook.webhook.parse",
  rawGraphRequest: "outlook.rawGraph.request",
} as const;

export const outlookEmailManifestInput = {
  id: "email.outlook",
  name: "Microsoft Outlook",
  packageName: "@cognidesk/integration-email-outlook",
  provider: "outlook",
  category: "email",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  operations: [
    {
      alias: outlookEmailOperationAliases.receive,
      capability: "receive",
      label: "Receive Outlook change notifications",
      providerObject: "emailMessage",
      exposesSensitiveData: true,
    },
    {
      alias: outlookEmailOperationAliases.send,
      capability: "send",
      label: "Send Outlook mail",
      providerObject: "emailMessage",
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    },
    {
      alias: outlookEmailOperationAliases.draftCreate,
      capability: "draft",
      label: "Create Outlook draft",
      providerObject: "emailDraft",
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      alias: outlookEmailOperationAliases.attachmentsRead,
      capability: "read-provider-object",
      label: "Read Outlook attachments",
      providerObject: "attachment",
      exposesSensitiveData: true,
    },
    {
      alias: outlookEmailOperationAliases.mailboxWatch,
      capability: "receive",
      label: "Create Microsoft Graph mailbox subscription",
      providerObject: "mailbox",
      sideEffect: true,
    },
    {
      alias: outlookEmailOperationAliases.messageList,
      capability: "read-provider-object",
      label: "List Outlook messages",
      providerObject: "emailMessage",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: outlookEmailOperationAliases.messageGet,
      capability: "read-provider-object",
      label: "Get Outlook message",
      providerObject: "emailMessage",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: outlookEmailOperationAliases.messageDelta,
      capability: "receive",
      label: "Read Outlook message delta page",
      providerObject: "emailMessage",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: outlookEmailOperationAliases.messageUpdate,
      capability: "update-provider-object",
      label: "Update Outlook message",
      providerObject: "emailMessage",
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: outlookEmailOperationAliases.mailboxUserGet,
      capability: "read-provider-object",
      label: "Get Outlook mailbox user",
      providerObject: "mailbox",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: outlookEmailOperationAliases.webhookParse,
      capability: "receive",
      label: "Parse Outlook webhook",
      providerObject: "emailMessage",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: outlookEmailOperationAliases.rawGraphRequest,
      capability: "read-provider-object",
      label: "Run raw Microsoft Graph request",
      providerObject: "mailbox",
      exposesSensitiveData: true,
      extension: true,
      metadata: { rawClientEscapeHatch: true },
    },
  ],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage includes SDK-backed Microsoft Graph Outlook mailbox support workflows: messages, mailFolders, attachments, sendMail, subscriptions, mailbox user readiness, and change notifications.",
      "The package uses @microsoft/microsoft-graph-client for Graph calls and keeps Cognidesk-normalized helper methods and operation handlers.",
      "This is not full Microsoft Graph coverage. Calendar, contacts, files/Drive, identity, admin, security, and broader Graph resources remain outside this Outlook adapter.",
    ],
    evidence: [
      { label: "Microsoft Graph JavaScript client", url: "https://www.npmjs.com/package/@microsoft/microsoft-graph-client" },
      { label: "Microsoft Graph create message", url: "https://learn.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0" },
      { label: "Microsoft Graph sendMail", url: "https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0" },
      { label: "Microsoft Graph message delta", url: "https://learn.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0" },
      { label: "Microsoft Graph list attachments", url: "https://learn.microsoft.com/en-us/graph/api/message-list-attachments?view=graph-rest-1.0" },
      { label: "Microsoft Graph create subscription", url: "https://learn.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0" },
      { label: "Microsoft Graph webhook subscription lifecycle", url: "https://learn.microsoft.com/en-us/graph/change-notifications-delivery-webhooks" },
    ],
  },
  credentialRequirements: [
    {
      id: "microsoft-graph-oauth-access-token",
      label: "Microsoft Graph OAuth access token",
      description: "Server-side OAuth access token for Microsoft Graph mail APIs. Required permissions are operation-specific.",
      scopes: ["Mail.Read", "Mail.ReadWrite", "Mail.Send", "User.Read"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "microsoft-graph-mailbox-user",
      label: "Mailbox user",
      description: "Delegated /me mailbox access or a configured Microsoft Graph user ID/userPrincipalName.",
      required: false,
    },
    {
      id: "microsoft-graph-webhook-client-state",
      label: "Webhook clientState secret",
      description: "SDK-user-owned clientState value used to validate Microsoft Graph change notifications.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Read Outlook messages and notifications",
      description: "Reads Microsoft Graph message resources and validates Outlook change notifications.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "outlookMailboxUser", label: "Outlook Mailbox User" },
        { kind: "outlookMessage", label: "Outlook Message" },
        { kind: "outlookChangeNotification", label: "Outlook Change Notification" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Create Outlook drafts",
      description: "Creates Microsoft Graph draft message resources for SDK-user-configured approval workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "outlookMessage", label: "Outlook Draft Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Outlook mail",
      description: "Calls Microsoft Graph sendMail when SDK-user policy permits outbound contact.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "outlookMessage", label: "Outlook Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Outlook mailbox objects",
      description: "Reads messages, attachments, mailbox users, and raw Graph resources needed by support workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "outlookMessage", label: "Outlook Message" },
        { kind: "outlookAttachment", label: "Outlook Attachment" },
        { kind: "outlookMailboxUser", label: "Outlook Mailbox User" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Outlook messages",
      description: "Updates Microsoft Graph message fields such as categories, importance, read state, or draft content.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "outlookMessage", label: "Outlook Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "Outlook messages can contain customer content, attachments, addresses, recipients, categories, internet headers, and conversation history.",
    "Microsoft Graph OAuth access tokens and webhook clientState secrets stay server-side and are represented in Studio only as credential readiness.",
    "SDK users own outbound approval, auto-send controls, contact consent, tenant/admin policy review, retention, redaction, attachment retrieval, and deletion behavior.",
  ],
  limitations: [
    "Available operations depend on Microsoft Graph permissions, OAuth grant type, tenant admin consent, conditional access, mailbox licensing, Exchange Online policy, and delegated or application user selection.",
    "This package provides transport and webhook foundations; it does not choose default automation, retention, consent, retry, or rate-limit policies.",
    "Webhook validation is based on Microsoft Graph clientState matching. Subscription renewal/delete/reauthorize policy remains SDK-user-owned.",
  ],
  metadata: {
    implementation: {
      strategy: "official-sdk",
      sdkPackage: "@microsoft/microsoft-graph-client",
      rawClientEscapeHatch: "rawClient",
      manifestOnlyExport: "@cognidesk/integration-email-outlook/manifest",
    },
    channelCoverage: {
      messages: "sdk-owned-list-get-delta-update",
      drafts: "sdk-owned-create",
      sendMail: "sdk-owned-send",
      attachments: "sdk-owned-list-get-download",
      subscriptions: "sdk-owned-create",
      webhookClientState: "typed-validate",
      mailboxUser: "sdk-owned-read",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
} as const satisfies ProviderManifestInput;

export const outlookEmailProviderManifest = defineIntegrationProviderPackage(outlookEmailManifestInput);
