import { defineIntegrationProviderPackage } from "@cognidesk/integration-kit";
import type { ProviderManifestInput } from "@cognidesk/core";

export const defaultStripeApiVersion = "2026-05-28.basil";

export const stripeEcommerceProviderManifestInput = {
  id: "ecommerce.stripe",
  name: "Stripe",
  packageName: "@cognidesk/ecommerce-stripe",
  provider: "stripe",
  category: "ecommerce",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is limited to Cognidesk-normalized Stripe commerce support operations backed by the official Stripe SDK.",
      "The official Stripe SDK remains available as an explicit raw-client escape hatch; raw SDK coverage is not Cognidesk adapter coverage.",
      "Generated Stripe full-provider API clones are intentionally not part of this package.",
    ],
    evidence: [
      { label: "Stripe API reference", url: "https://docs.stripe.com/api" },
      { label: "Stripe Node SDK", url: "https://github.com/stripe/stripe-node" },
      { label: "Stripe webhook signature verification", url: "https://docs.stripe.com/webhooks/signature" },
    ],
  },
  credentialRequirements: [
    {
      id: "stripe-secret-key",
      label: "Stripe secret key",
      description: "Server-side Stripe secret or restricted key selected and owned by the SDK user.",
      scopes: [
        "customers:read",
        "payment_intents:read",
        "checkout_sessions:read",
        "subscriptions:read",
        "invoices:read",
        "refunds:read",
        "disputes:read",
        "subscriptions:write",
        "webhook_endpoints:read",
        "webhook_endpoints:write",
      ],
      required: true,
      metadata: { scopeKind: "provider-permission-labels" },
    },
    {
      id: "stripe-webhook-signing-secret",
      label: "Stripe webhook signing secret",
      description: "Endpoint signing secret used to validate Stripe-Signature headers against the raw request body.",
      required: true,
    },
    {
      id: "stripe-connect-mode",
      label: "Stripe Connect mode",
      description: "SDK-user-selected account context for platform or connected-account routing.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Stripe events",
      description: "Validates and parses Stripe webhook events for SDK-user-owned commerce and payment support workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "stripeEvent", label: "Stripe Event" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Stripe commerce records",
      description: "Reads customers, Checkout Sessions, PaymentIntents, subscriptions, invoices, refunds, and disputes.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "stripeCustomer", label: "Stripe Customer" },
        { kind: "stripeCheckoutSession", label: "Stripe Checkout Session" },
        { kind: "stripePaymentIntent", label: "Stripe PaymentIntent" },
        { kind: "stripeSubscription", label: "Stripe Subscription" },
        { kind: "stripeInvoice", label: "Stripe Invoice" },
        { kind: "stripeRefund", label: "Stripe Refund" },
        { kind: "stripeDispute", label: "Stripe Dispute" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Stripe commerce records",
      description: "Lists and searches support-relevant Stripe objects with SDK-user-supplied filters.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "stripeCustomer", label: "Stripe Customer" },
        { kind: "stripeCheckoutSession", label: "Stripe Checkout Session" },
        { kind: "stripePaymentIntent", label: "Stripe PaymentIntent" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Stripe payment support actions",
      description: "Creates Checkout Sessions, PaymentIntents, and refunds when SDK-user policy permits.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "stripeCheckoutSession", label: "Stripe Checkout Session" },
        { kind: "stripePaymentIntent", label: "Stripe PaymentIntent" },
        { kind: "stripeRefund", label: "Stripe Refund" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Stripe support records",
      description: "Updates subscriptions and manages webhook endpoints when SDK-user policy permits.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "stripeSubscription", label: "Stripe Subscription" },
        { kind: "stripeWebhookEndpoint", label: "Stripe Webhook Endpoint" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "ecommerce.payments",
      label: "Stripe raw SDK escape hatch",
      description: "Exposes the configured official Stripe SDK client for SDK-user-owned advanced operations.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "stripeRawClient", label: "Stripe SDK Client" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    { alias: "ecommerce.event.receive", capability: "receive", providerObjects: [{ kind: "stripeEvent" }], exposesSensitiveData: true },
    { alias: "ecommerce.order.read", capability: "read-provider-object", providerOperation: "checkout.sessions.retrieve", providerObjects: [{ kind: "stripeCheckoutSession" }], exposesSensitiveData: true },
    { alias: "ecommerce.order.search", capability: "search-provider-object", providerOperation: "checkout.sessions.list", providerObjects: [{ kind: "stripeCheckoutSession" }], exposesSensitiveData: true },
    { alias: "ecommerce.customer.read", capability: "read-provider-object", providerOperation: "customers.retrieve", providerObjects: [{ kind: "stripeCustomer" }], exposesSensitiveData: true },
    { alias: "ecommerce.customer.search", capability: "search-provider-object", providerOperation: "customers.search", providerObjects: [{ kind: "stripeCustomer" }], exposesSensitiveData: true },
    { alias: "ecommerce.payment.read", capability: "read-provider-object", providerOperation: "paymentIntents.retrieve", providerObjects: [{ kind: "stripePaymentIntent" }], exposesSensitiveData: true },
    { alias: "ecommerce.refund.create", capability: "create-provider-object", providerOperation: "refunds.create", providerObjects: [{ kind: "stripeRefund" }], sideEffect: true, externallyVisible: true, requiresApproval: true, changesWorkflow: true, exposesSensitiveData: true },
    { alias: "ecommerce.refund.read", capability: "read-provider-object", providerOperation: "refunds.retrieve", providerObjects: [{ kind: "stripeRefund" }], exposesSensitiveData: true },
    { alias: "ecommerce.subscription.read", capability: "read-provider-object", providerOperation: "subscriptions.retrieve", providerObjects: [{ kind: "stripeSubscription" }], exposesSensitiveData: true },
    { alias: "ecommerce.subscription.update", capability: "update-provider-object", providerOperation: "subscriptions.update", providerObjects: [{ kind: "stripeSubscription" }], sideEffect: true, externallyVisible: true, requiresApproval: true, changesWorkflow: true, exposesSensitiveData: true },
    { alias: "ecommerce.invoice.read", capability: "read-provider-object", providerOperation: "invoices.retrieve", providerObjects: [{ kind: "stripeInvoice" }], exposesSensitiveData: true },
    { alias: "ecommerce.webhookEndpoint.manage", capability: "update-provider-object", providerOperation: "webhookEndpoints", providerObjects: [{ kind: "stripeWebhookEndpoint" }], sideEffect: true, changesWorkflow: true },
    { alias: "stripe.rawClient", capability: "ecommerce.payments", providerObjects: [{ kind: "stripeRawClient" }], extension: true, exposesSensitiveData: true },
  ],
  privacyNotes: [
    "Stripe records can include customer contact data, billing/shipping addresses, payment state, subscription terms, invoice history, refund reasons, dispute evidence, and account metadata.",
    "Secret keys, Connect account routing, and webhook signing secrets stay server-side; Studio receives only readiness state and policy-visible metadata.",
  ],
  limitations: [
    "The SDK user chooses Stripe account mode, restricted-key permissions, event destinations, webhook subscriptions, checkout UI, refund policy, dispute evidence policy, consent, and retention.",
    "This package provides normalized support-operation foundations and raw-client access; it does not decide when to charge, refund, cancel, submit evidence, or expose payment data to an operator.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    defaultApiVersion: defaultStripeApiVersion,
    docs: "https://docs.stripe.com/api",
    sdkPackage: "stripe",
    implementation: {
      strategy: "official-sdk",
      sdkPackage: "stripe",
      generatedFullProviderApiClone: false,
      rawClientEscapeHatch: true,
    },
    rawProviderRequest: {
      capability: "ecommerce.payments",
      acknowledgementRequired: true,
      coverage: "escape-hatch-not-full-provider-api",
    },
  },
} as const satisfies ProviderManifestInput;

export const stripeEcommerceProviderManifest = defineIntegrationProviderPackage(stripeEcommerceProviderManifestInput);
