import {
  defineIntegrationProviderPackage,
  type ProviderManifestInput,
} from "@cognidesk/integration-kit";

export const discordMessagingOperationAliases = [
  "discord.interaction.receive",
  "discord.message.send",
  "discord.thread.create",
  "discord.forum-post.create",
  "discord.webhook.execute",
  "discord.bot.read",
  "discord.application.read",
  "discord.guild.read",
  "discord.channel.read",
  "discord.channel-messages.list",
  "discord.interaction-signature.verify",
] as const;

export const discordMessagingManifestInput = {
  id: "messaging.discord",
  name: "Discord Messaging Support",
  packageName: "@cognidesk/integration-messaging-discord",
  provider: "discord",
  category: "messaging",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  credentialRequirements: [
    {
      id: "discord-bot-token",
      label: "Discord bot token",
      description: "Server-side Discord bot token used by discord.js REST and Routes SDK helpers for channel, guild, bot, and application calls.",
      scopes: ["bot", "applications.commands"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "discord-application-id",
      label: "Discord application ID",
      description: "SDK-user-owned Discord application ID used to identify commands, interactions, and installation readiness.",
      required: true,
    },
    {
      id: "discord-public-key",
      label: "Discord interaction public key",
      description: "Ed25519 public key from the Discord Developer Portal for validating interaction endpoint requests.",
      required: true,
    },
    {
      id: "discord-guild-id",
      label: "Discord guild ID",
      description: "Guild/server ID selected by SDK configuration for messaging support routing and live checks.",
      required: false,
    },
    {
      id: "discord-channel-id",
      label: "Discord channel or forum ID",
      description: "Channel, forum, or media channel ID selected by SDK configuration for message and thread operations.",
      required: false,
    },
    {
      id: "discord-webhook-url",
      label: "Discord webhook URL",
      description: "Optional SDK-user-owned webhook URL for Discord webhook delivery or webhook-based outbound messages.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Discord interactions",
      description: "Validates Ed25519-signed Discord outgoing-webhook interaction requests.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "discordInteraction", label: "Discord Interaction" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Discord channel messages",
      description: "Sends bot-token-authenticated Discord channel messages through discord.js REST.post(Routes.channelMessages).",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "discordMessage", label: "Discord Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Create Discord support threads",
      description: "Creates Discord text-channel threads or forum/media channel posts selected by SDK configuration.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "discordThread", label: "Discord Thread" },
        { kind: "discordForumPost", label: "Discord Forum Post" },
        { kind: "discordMediaPost", label: "Discord Media Channel Post" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Discord channels and messages",
      description: "Reads Discord bot, application, guild, channel, and recent channel message records where bot permissions allow access.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "discordBot", label: "Discord Bot" },
        { kind: "discordApplication", label: "Discord Application" },
        { kind: "discordGuild", label: "Discord Guild" },
        { kind: "discordChannel", label: "Discord Channel" },
        { kind: "discordMessage", label: "Discord Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "notify",
      label: "Notify Discord moderators",
      description: "Uses SDK-user-selected Discord channels, threads, or validated Discord webhook URLs through discord.js REST dispatch.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "discordMessage", label: "Discord Message" },
        { kind: "discordWebhookMessage", label: "Discord Webhook Message" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "discord.interaction-signature",
      label: "Validate Discord interaction signatures",
      description: "Validates X-Signature-Ed25519 and X-Signature-Timestamp headers with the SDK user's Discord application public key.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "discordSignedInteraction", label: "Discord Signed Interaction" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "discord.interaction.receive",
      capability: "receive",
      providerObject: "discordInteraction",
      inputSchemaName: "ParseDiscordInteractionRequestInput",
      outputSchemaName: "DiscordParsedInteractionRequest",
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "discord.message.send",
      capability: "send",
      providerObject: "discordMessage",
      providerOperation: "REST.post(Routes.channelMessages)",
      inputSchemaName: "DiscordSendChannelMessageInput",
      outputSchemaName: "DiscordMessageResource",
      requiresCredential: true,
      sideEffect: true,
      externallyVisible: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "discord.thread.create",
      capability: "thread",
      providerObject: "discordThread",
      providerOperation: "REST.post(Routes.threads)",
      inputSchemaName: "DiscordCreateThreadInput",
      outputSchemaName: "DiscordChannelResource",
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "discord.forum-post.create",
      capability: "thread",
      providerObject: "discordForumPost",
      providerOperation: "REST.post(Routes.threads)",
      inputSchemaName: "DiscordCreateForumPostInput",
      outputSchemaName: "DiscordChannelResource",
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "discord.webhook.execute",
      capability: "notify",
      providerObject: "discordWebhookMessage",
      providerOperation: "REST.post(Routes.webhook)",
      inputSchemaName: "DiscordExecuteWebhookInput",
      outputSchemaName: "DiscordMessageResource",
      requiresCredential: false,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "discord.bot.read",
      capability: "read-provider-object",
      providerObject: "discordBot",
      providerOperation: "REST.get(Routes.user)",
      outputSchemaName: "DiscordUserResource",
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "discord.application.read",
      capability: "read-provider-object",
      providerObject: "discordApplication",
      providerOperation: "REST.get(Routes.oauth2CurrentApplication)",
      outputSchemaName: "DiscordApplicationResource",
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "discord.guild.read",
      capability: "read-provider-object",
      providerObject: "discordGuild",
      providerOperation: "REST.get(Routes.guild)",
      inputSchemaName: "DiscordGetGuildInput",
      outputSchemaName: "DiscordGuildResource",
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "discord.channel.read",
      capability: "read-provider-object",
      providerObject: "discordChannel",
      providerOperation: "REST.get(Routes.channel)",
      inputSchemaName: "DiscordGetChannelInput",
      outputSchemaName: "DiscordChannelResource",
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "discord.channel-messages.list",
      capability: "read-provider-object",
      providerObject: "discordMessage",
      providerOperation: "REST.get(Routes.channelMessages)",
      inputSchemaName: "DiscordListMessagesInput",
      outputSchemaName: "DiscordMessageResource[]",
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "discord.interaction-signature.verify",
      capability: "discord.interaction-signature",
      providerObject: "discordSignedInteraction",
      inputSchemaName: "ValidateDiscordInteractionSignatureInput",
      outputSchemaName: "boolean",
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is a Cognidesk support workflow adapter backed by discord.js REST, discord.js Routes helpers, and an optional discord.js Gateway service for live support-thread handoff.",
      "Typed operations cover channel messages, text/forum/media-channel threads, webhook execution with strict Discord webhook URL validation, selected bot/application/guild/channel reads, channel message listing, and Ed25519 interaction signature verification.",
      "The runtime export includes a Discord Gateway service that creates or reuses Discord threads, ingests customer messages through messageCreate events, mirrors Cognidesk runtime messages into threads, and records idempotency state through the bundled SQLite store.",
      "This package intentionally removes the generated Discord HTTP API clone and does not claim full Discord platform coverage.",
      "Discord bot installation, Gateway intents policy, channel permissions, moderation policy, retention, deletion, command registration lifecycle, voice/media transport, broad moderation/admin APIs, and Discord Webhook Events subscriptions remain SDK-user-owned configuration or future package surfaces.",
    ],
    evidence: [
      { label: "discord.js package", url: "https://www.npmjs.com/package/discord.js" },
      { label: "Discord API reference", url: "https://docs.discord.com/developers/reference" },
      { label: "Discord message resource", url: "https://docs.discord.com/developers/resources/message" },
      { label: "Discord channel/thread endpoints", url: "https://docs.discord.com/developers/resources/channel" },
      { label: "Discord threads topic", url: "https://docs.discord.com/developers/topics/threads" },
      { label: "Discord receiving and responding to interactions", url: "https://docs.discord.com/developers/interactions/receiving-and-responding" },
      { label: "Discord Gateway events", url: "https://docs.discord.com/developers/events/gateway" },
      { label: "Discord Voice connections", url: "https://docs.discord.com/developers/topics/voice-connections" },
      { label: "Discord Webhook Events", url: "https://docs.discord.com/developers/events/webhook-events" },
      { label: "Discord rate limits", url: "https://docs.discord.com/developers/topics/rate-limits" },
    ],
  },
  privacyNotes: [
    "Discord messages, user IDs, guild IDs, channel IDs, thread IDs, usernames, attachments, embeds, interaction payloads, and mirrored runtime transcripts can contain customer and moderator data.",
    "Discord bot tokens, public keys, application IDs, guild/channel routing, webhook URLs, consent, moderation, retention, and transcript policy stay SDK-user-owned configuration.",
  ],
  limitations: [
    "Available Discord operations depend on the SDK user's Discord application, bot installation, OAuth scopes, role permissions, channel permissions, forum settings, and rate limits.",
    "The optional Gateway service requires Discord Gateway access with Message Content Intent enabled when message text is mirrored into Cognidesk.",
    "Discord Webhook Events subscriptions, slash command registration, broader REST administration, voice, and local RPC/IPC remain outside this package.",
    "Discord interaction endpoint requests must fail closed when signature verification is required but the public key or signature headers are missing or invalid.",
  ],
  metadata: {
    integrationName: "Discord Integration",
    integrationPackageName: "@cognidesk/integration-messaging-discord",
    integrationEntryPoints: {
      manifest: "@cognidesk/integration-messaging-discord/manifest",
      runtime: "@cognidesk/integration-messaging-discord/runtime",
    },
    apiBaseUrl: "https://discord.com/api",
    defaultApiVersion: "10",
    interactionSignatureHeaders: ["x-signature-ed25519", "x-signature-timestamp"],
    channelCoverage: {
      channelMessages: "sdk-owned-rest-send-list",
      threads: "sdk-owned-rest-create",
      forumPosts: "sdk-owned-rest-create",
      webhookExecution: "sdk-owned-rest-webhook-execute",
      interactionsEndpoint: "typed-verify-parse",
      botApplicationGuildChannelReads: "sdk-owned-rest-read",
      gatewayEvents: "sdk-owned-discord-js-gateway-service",
      webhookEventsSubscriptions: "not-covered",
      voiceGatewayAndRpc: "not-covered",
    },
    gatewayService: {
      sourceId: "discord-gateway",
      store: "bundled-libsql-sqlite-binding-store",
      messageIngress: "discord-js-messageCreate",
      runtimeMirror: "cognidesk-runtime-event-list",
    },
    providerClient: {
      package: "discord.js",
      versionRange: "^14.26.4",
      importPolicy: "runtime-entrypoint-only",
    },
    implementation: {
      strategy: "official-sdk-support-slice",
      sdkPackage: "discord.js",
      sdkVersionRange: "^14.26.4",
      sdkRuntimeSurface: "REST + Routes + Client gateway",
      operationMethodMap: {
        "discord.message.send": "REST.post(Routes.channelMessages)",
        "discord.thread.create": "REST.post(Routes.threads)",
        "discord.forum-post.create": "REST.post(Routes.threads)",
        "discord.webhook.execute": "REST.post(Routes.webhook)",
        "discord.bot.read": "REST.get(Routes.user)",
        "discord.application.read": "REST.get(Routes.oauth2CurrentApplication)",
        "discord.guild.read": "REST.get(Routes.guild)",
        "discord.channel.read": "REST.get(Routes.channel)",
        "discord.channel-messages.list": "REST.get(Routes.channelMessages)",
        "discord.interaction.receive": "parseDiscordInteractionRequest",
        "discord.interaction-signature.verify": "validateDiscordInteractionSignature",
      },
      strictExceptions: {
        "discord.webhook.execute": "Webhook URLs are validated against the configured Discord API origin, parsed into webhook id/token, dispatched through discord.js REST with auth disabled, and rejected before dispatch when the URL is not a Discord webhook execution URL.",
        "discord.interaction.receive": "Interaction parsing and Ed25519 signature verification are local protocol handling, not outbound provider SDK calls.",
        "discord.interaction-signature.verify": "Signature verification is local Ed25519 protocol handling, not an outbound provider SDK call.",
      },
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
} as const satisfies ProviderManifestInput;

export const discordMessagingProviderManifest = defineIntegrationProviderPackage(
  discordMessagingManifestInput,
);
