import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

const discourseForumProviderSdkDecision = {
  strategy: "no-official-js-ts-sdk-rest-adapter",
  defaultClientPolicy: "provider-rest-adapter-when-configured",
  officialJsSdkAvailable: false,
  packageOwnedRestClient: true,
  verifiedAt: "2026-06-25",
  runtimePackage: "@cognidesk/integration-community-forum/runtime",
  providerClient: "ForumCommunityProviderClient",
  sdkDecision: {
    checkedAt: "2026-06-25",
    result: "no-applicable-official-js-ts-sdk",
    rejectedSdkPackages: [
      {
        packageName: "discourse_api",
        ecosystem: "ruby",
        reason: "Discourse documentation recommends the official discourse_api Ruby gem for Ruby consumers; it is not a JavaScript or TypeScript runtime SDK for this provider package.",
      },
      {
        packageName: "discourse-api-sdk",
        ecosystem: "npm",
        reason: "Third-party npm publisher and repository; not published by the Discourse npm organization, despite package description text.",
      },
      {
        packageName: "@discourse/mcp",
        ecosystem: "npm",
        reason: "Official Discourse MCP CLI server, not an in-process JavaScript or TypeScript provider API client for this runtime package.",
      },
      {
        packageName: "discourse-sdk",
        ecosystem: "npm",
        reason: "Unofficial, old, and untyped npm package surface; unsuitable as the strict provider SDK dependency for this package.",
      },
    ],
  },
} as const;

export const forumCommunityProviderManifest = defineProviderPackage({
  id: "community.forum",
  name: "Discourse Forum",
  packageName: "@cognidesk/integration-community-forum",
  provider: "forum",
  category: "community",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    {
      id: "forum-base-url",
      label: "Forum base URL",
      description: "Forum origin used by the built-in Discourse-compatible REST adapter or a provider client override.",
      required: true,
    },
    {
      id: "forum-api-key",
      label: "Forum API key",
      description: "Server-side forum credential used by the built-in REST adapter or encapsulated in a provider client override.",
      required: true,
    },
    {
      id: "forum-api-username",
      label: "Forum API username",
      description: "Forum API username used by the built-in REST adapter or represented by a provider client override.",
      required: true,
    },
    {
      id: "forum-webhook-secret",
      label: "Forum webhook secret",
      description: "Shared secret used to verify signed forum webhooks before accepting public community events.",
      required: false,
    },
  ],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is limited to a built-in Discourse-compatible REST adapter for forum topic/post/search/current-user workflows, optional provider client overrides, and X-Discourse-Event-Signature webhook validation.",
      "No applicable official JavaScript or TypeScript Discourse provider SDK was verified on 2026-06-25; Discourse's documented client-library path is the discourse_api Ruby gem, so this package uses a constrained REST adapter.",
      "The package does not implement broader Discourse administration for categories, tags, users/groups, moderation actions, uploads, badges, notifications, private messages, plugin endpoints, site settings, or non-Discourse forum APIs.",
    ],
    evidence: [
      { label: "Discourse API docs", url: "https://docs.discourse.org/" },
      { label: "Discourse webhook configuration and signature", url: "https://meta.discourse.org/t/configure-webhooks-that-trigger-on-discourse-events-to-integrate-with-external-services/49045" },
    ],
  },
  capabilities: [
    {
      capability: "receive",
      label: "Receive forum webhooks",
      description: "Validates and parses forum webhook events for SDK-user-owned public community support workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "forumWebhook", label: "Forum Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Create forum replies",
      description: "Creates public forum replies through the configured Discourse-compatible REST adapter or provider client when SDK-user policy permits public response automation.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "forumPost", label: "Forum Post" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "draft",
      label: "Draft forum posts",
      description: "Builds topic and reply payloads for SDK-user approval workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "forumPostDraft", label: "Forum Post Draft" }],
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use forum topics",
      description: "Reads forum topics, posts, latest topics, and search results through the configured Discourse-compatible REST adapter or provider client.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "forumTopic", label: "Forum Topic" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create forum topics",
      description: "Creates SDK-user-approved forum topics through the configured Discourse-compatible REST adapter or provider client.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "forumTopic", label: "Forum Topic" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read forum topics and posts",
      description: "Reads forum topics, posts, and the current API user readiness record through the configured Discourse-compatible REST adapter or provider client.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "forumTopic", label: "Forum Topic" },
        { kind: "forumPost", label: "Forum Post" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search forum content",
      description: "Searches forum topics and posts through the configured Discourse-compatible REST adapter or provider client with SDK-user-selected query and pagination controls.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "forumSearchResult", label: "Forum Search Result" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "community.webhook-signature",
      label: "Validate forum webhook signatures",
      description: "Validates Discourse-style X-Discourse-Event-Signature HMAC-SHA256 webhook signatures.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "forumSignedWebhook", label: "Forum Signed Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "forum.topic.create",
      capability: "create-provider-object",
      label: "Create forum topic",
      providerObject: "forumTopic",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "forum.reply.create",
      capability: "send",
      label: "Create forum reply",
      providerObject: "forumPost",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "forum.topic.read",
      capability: "read-provider-object",
      label: "Read forum topic",
      providerObject: "forumTopic",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "forum.post.read",
      capability: "read-provider-object",
      label: "Read forum post",
      providerObject: "forumPost",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "forum.search",
      capability: "search-provider-object",
      label: "Search forum",
      providerObject: "forumSearchResult",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "forum.webhook.parse",
      capability: "community.webhook-signature",
      label: "Parse forum webhook",
      providerObject: "forumSignedWebhook",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Forum posts, topic titles, usernames, and category/tag labels present in returned topics, posts, search results, or webhook payloads can contain customer data.",
    "Forum API keys and webhook secrets stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "The SDK user chooses which forum implementation, categories, tags, moderation actions, public reply approval, and retention policies are active.",
    "Provider operations require baseUrl, apiKey, and apiUsername for the built-in REST adapter, or a ForumCommunityProviderClient override; without either, operation handlers fail closed.",
    "Forum rate limits and throttling are provider-specific; the configured adapter or host boundary owns 429 handling, retry, and backoff policy.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://docs.discourse.org/",
    implementation: discourseForumProviderSdkDecision,
    implementationStrategy: "provider-rest-adapter",
    concreteProvider: "discourse-compatible-rest-adapter-or-provider-client",
    supportedForumApi: "built-in-discourse-rest-adapter-and-discourse-webhooks",
    providerClient: {
      package: "built-in-or-host-provided",
      interface: "ForumCommunityProviderClient",
      importPolicy: "provider-client-override-supported",
      defaultClientPolicy: "provider-rest-adapter-when-configured",
      sdkDecision: discourseForumProviderSdkDecision.sdkDecision,
    },
    apiCoverage: {
      operationCatalog: "docs/provider-coverage/discourse-selected-api-2026-06-18.operations.json",
      generatedFromOfficialSpec: false,
      officialSpec: "https://docs.discourse.org/openapi.json",
      sourcePathCount: 79,
      sourceOperationCount: 93,
      selectedOperationCount: 5,
      docsOnlyOperationCount: 1,
      implementedOperationCount: 6,
      packageImplementedProviderRestOperationCount: 5,
      providerOperationImplementation: "built-in-provider-rest-adapter",
      fullProviderApi: false,
    },
    channelCoverage: {
      topics: "provider-rest-adapter-create-read-latest",
      posts: "provider-rest-adapter-create-read",
      search: "provider-rest-adapter-search",
      currentUser: "provider-rest-adapter-read",
      webhooks: "typed-validate-parse",
      categoriesTagsUsersGroupsModerationUploadsBadgesPrivateMessages: "provider-supported-not-typed",
      nonDiscourseForumApis: "not-covered",
    },
  },
});
