import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const forumCommunityProviderManifest = defineProviderPackage({
  id: "community.forum",
  name: "Discourse Forum",
  packageName: "@cognidesk/integration-community-forum",
  provider: "forum",
  category: "community",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    {
      id: "forum-base-url",
      label: "Forum base URL",
      description: "SDK-user-selected forum origin, such as a Discourse community URL.",
      required: true,
    },
    {
      id: "forum-api-key",
      label: "Forum API key",
      description: "Server-side forum API key used for topic, post, search, and user readiness calls.",
      required: true,
    },
    {
      id: "forum-api-username",
      label: "Forum API username",
      description: "Forum API username that owns SDK-user-selected moderation and posting permissions.",
      required: true,
    },
    {
      id: "forum-webhook-secret",
      label: "Forum webhook secret",
      description: "Shared secret used to verify signed forum webhooks before accepting public community events.",
      required: false,
    },
  ],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is limited to Discourse-compatible topic/reply creation through posts, topic/post reads, search/latest/current-user reads, and X-Discourse-Event-Signature webhook validation.",
      "The package does not implement broader Discourse administration for categories, tags, users/groups, moderation actions, uploads, badges, notifications, private messages, plugin endpoints, site settings, or non-Discourse forum APIs.",
    ],
    evidence: [
      { label: "Discourse API docs", url: "https://docs.discourse.org/" },
      { label: "Discourse webhook configuration and signature", url: "https://meta.discourse.org/t/configure-webhooks-that-trigger-on-discourse-events-to-integrate-with-external-services/49045" },
    ],
  },
  capabilities: [
    {
      capability: "receive",
      label: "Receive forum webhooks",
      description: "Validates and parses forum webhook events for SDK-user-owned public community support workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "forumWebhook", label: "Forum Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Create forum replies",
      description: "Creates public forum replies when SDK-user policy permits public response automation.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "forumPost", label: "Forum Post" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "draft",
      label: "Draft forum posts",
      description: "Builds topic and reply payloads for SDK-user approval workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "forumPostDraft", label: "Forum Post Draft" }],
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use forum topics",
      description: "Reads forum topics, posts, latest topics, and search results as community support threads.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "forumTopic", label: "Forum Topic" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create forum topics",
      description: "Creates SDK-user-approved forum topics for support announcements or escalated community cases.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "forumTopic", label: "Forum Topic" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read forum topics and posts",
      description: "Reads forum topics, posts, and the current API user readiness record through the configured forum API.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "forumTopic", label: "Forum Topic" },
        { kind: "forumPost", label: "Forum Post" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search forum content",
      description: "Searches forum topics and posts with SDK-user-selected query and pagination controls.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "forumSearchResult", label: "Forum Search Result" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "community.webhook-signature",
      label: "Validate forum webhook signatures",
      description: "Validates Discourse-style X-Discourse-Event-Signature HMAC-SHA256 webhook signatures.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "forumSignedWebhook", label: "Forum Signed Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "forum.topic.create",
      capability: "create-provider-object",
      label: "Create forum topic",
      providerObject: "forumTopic",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "forum.reply.create",
      capability: "send",
      label: "Create forum reply",
      providerObject: "forumPost",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "forum.topic.read",
      capability: "read-provider-object",
      label: "Read forum topic",
      providerObject: "forumTopic",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "forum.post.read",
      capability: "read-provider-object",
      label: "Read forum post",
      providerObject: "forumPost",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "forum.search",
      capability: "search-provider-object",
      label: "Search forum",
      providerObject: "forumSearchResult",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "forum.webhook.parse",
      capability: "community.webhook-signature",
      label: "Parse forum webhook",
      providerObject: "forumSignedWebhook",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Forum posts, topic titles, usernames, and category/tag labels present in returned topics, posts, search results, or webhook payloads can contain customer data.",
    "Forum API keys and webhook secrets stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "The SDK user chooses which forum implementation, categories, tags, moderation actions, public reply approval, and retention policies are active.",
    "This package uses Discourse-compatible REST and webhook conventions as the concrete forum foundation; other forum implementations can wrap the same manifest pattern.",
    "Discourse rate limits and throttling are configurable by site administrators; SDK users own 429 handling, retry, and backoff policy.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://docs.discourse.org/",
    concreteProvider: "discourse",
    supportedForumApi: "discourse-compatible-rest-and-webhooks",
    apiCoverage: {
      operationCatalog: "docs/provider-coverage/discourse-selected-api-2026-06-18.operations.json",
      generatedFromOfficialSpec: false,
      officialSpec: "https://docs.discourse.org/openapi.json",
      sourcePathCount: 79,
      sourceOperationCount: 93,
      selectedOperationCount: 5,
      docsOnlyOperationCount: 1,
      implementedOperationCount: 6,
      fullProviderApi: false,
    },
    channelCoverage: {
      topics: "typed-create-read-latest",
      posts: "typed-create-read",
      search: "typed-search",
      currentUser: "typed-read",
      webhooks: "typed-validate-parse",
      categoriesTagsUsersGroupsModerationUploadsBadgesPrivateMessages: "provider-supported-not-typed",
      nonDiscourseForumApis: "not-covered",
    },
  },
});
