import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const sipVoiceProviderManifest = defineProviderPackage({
  id: "voice.sip",
  name: "Generic SIP Voice Connection",
  packageName: "@cognidesk/integration-voice-sip",
  provider: "sip",
  category: "voice",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "local-protocol",
    notes: [
      "Defines a Cognidesk SIP stack gateway contract and callback normalizer for SDK-user-owned SIP/SBC/BYOC infrastructure.",
      "Ships a drachtio-srf-backed gateway adapter for outbound UAC and dialog-level BYE, REFER, INFO DTMF, and re-INVITE media update operations when a drachtio Srf instance or server connection is configured.",
      "Does not implement a registrar, SBC, RTP/SRTP media engine, recording/transcription media services, or any specific provider's SIP/Voice REST API.",
      "Provider-specific SIP registration, inbound request/response acceptance, media anchoring, recording, transcription, routing, consent, and retention remain SDK-user/provider gateway responsibilities.",
    ],
    evidence: [
      { label: "drachtio-srf npm package", url: "https://www.npmjs.com/package/drachtio-srf" },
      { label: "drachtio-srf repository", url: "https://github.com/drachtio/drachtio-srf" },
    ],
  },
  credentialRequirements: [
    {
      id: "sip-registrar",
      label: "SIP registrar",
      description: "Registrar URI used by the SDK user's SIP stack to register or authenticate the endpoint.",
      required: true,
    },
    {
      id: "sip-proxy",
      label: "SIP proxy",
      description: "Outbound proxy URI or SBC target used for INVITE, transfer, and call-control signaling.",
      required: false,
    },
    {
      id: "sip-domain",
      label: "SIP domain",
      description: "SIP realm/domain used to construct and validate address-of-record values.",
      required: true,
    },
    {
      id: "sip-auth",
      label: "SIP authentication",
      description: "Auth username and password/secret supplied to the SDK user's chosen SIP stack.",
      required: true,
    },
    {
      id: "sip-tls",
      label: "SIP over TLS",
      description: "TLS must be enabled when the deployment requires encrypted SIP signaling.",
      required: true,
    },
    {
      id: "sip-srtp",
      label: "SRTP media",
      description: "SRTP must be enabled when the deployment requires encrypted RTP media.",
      required: true,
    },
    {
      id: "sip-webhook-callback",
      label: "SIP event callback",
      description: "Public callback URL plus shared-secret or HMAC validation for call, transfer, recording, and transcription events.",
      required: true,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive SIP calls",
      description: "Accepts inbound SIP call events bridged from the SDK user's SIP stack into Cognidesk voice handling.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "sipCall", label: "SIP Call" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Place SIP calls",
      description: "Defines outbound INVITE contracts for BYOC SIP providers and SDK-user-owned SIP stacks.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "sipInvite", label: "SIP INVITE" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "SDP media negotiation",
      description: "Carries SDP offer/answer data and TLS/SRTP readiness metadata for the SDK user's SIP/RTP bridge.",
      audiences: ["customer-facing"],
      providerObjects: [
        { kind: "sipDialog", label: "SIP Dialog" },
        { kind: "sdpSessionDescription", label: "SDP Session Description" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "transfer",
      label: "SIP call transfer",
      description: "Exposes REFER/re-INVITE style transfer contracts while leaving transfer policy to SDK configuration.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "sipTransfer", label: "SIP Transfer" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      capability: "recording",
      label: "Recording callbacks",
      description: "Normalizes recording lifecycle callbacks emitted by the SDK user's SIP media stack.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "sipRecording", label: "SIP Recording" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "transcription",
      label: "Transcription callbacks",
      description: "Normalizes transcription callbacks emitted by the SDK user's SIP media or ASR stack.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "sipTranscription", label: "SIP Transcription" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "sip.webhook-signature",
      label: "Validate SIP callbacks",
      description: "Validates configurable shared-secret and HMAC headers before parsing generic SIP callback payloads.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "sipWebhook", label: "SIP Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "sip.call.start",
      capability: "send",
      label: "Place SIP call",
      providerObject: "sipInvite",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "sip.call.answer",
      capability: "receive",
      label: "Answer SIP call",
      providerObject: "sipCall",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      alias: "sip.call.hangup",
      capability: "send",
      label: "Hang up SIP call",
      providerObject: "sipCall",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      alias: "sip.call.transfer",
      capability: "transfer",
      label: "Transfer SIP call",
      providerObject: "sipTransfer",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      alias: "sip.recording.start",
      capability: "recording",
      label: "Start SIP recording",
      providerObject: "sipRecording",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "sip.recording.stop",
      capability: "recording",
      label: "Stop SIP recording",
      providerObject: "sipRecording",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      alias: "sip.dtmf.send",
      capability: "send",
      label: "Send SIP DTMF",
      providerObject: "sipCall",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
    },
    {
      alias: "sip.media.update",
      capability: "media",
      label: "Update SIP media session",
      providerObject: "sipDialog",
      extension: true,
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      alias: "sip.webhook.parse",
      capability: "sip.webhook-signature",
      label: "Parse SIP callback",
      providerObject: "sipWebhook",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "SIP addresses, call metadata, SDP media descriptions, recordings, and transcripts can contain personal data.",
    "This package does not implement a SIP stack or expose SIP credentials to browsers; SDK users supply and operate the SIP/SBC bridge.",
  ],
  limitations: [
    "A full SIP platform, registrar, SBC, and RTP/SRTP media engine are intentionally out of scope for this package.",
    "The drachtio-srf gateway adapter requires a configured drachtio Srf instance or reachable drachtio server for live SIP signaling.",
    "SDK users can still bridge these contracts to their chosen SIP stack, SBC, PBX, or BYOC voice provider through SipStackGateway.",
    "Conversation routing, consent, recording policy, retention, and handoff remain SDK-user configuration.",
  ],
  metadata: {
    implementation: {
      strategy: "protocol-runtime-sdk-gateway",
      providerSdkDecision: "provider-protocol-lib/drachtio-srf",
      checkedAt: "2026-06-25",
      checkedSurface: "npm view drachtio-srf/sip.js/jssip and package runtime imports",
      runtime: "createDrachtioSipStackGateway backed by drachtio-srf Srf, createUAC, and Dialog call-control methods",
      selectedSdkPackage: "drachtio-srf",
      reason: "drachtio-srf is a maintained, typed, server-side SIP signaling resource framework suitable for this package's outbound UAC and dialog-level call-control gateway operations.",
      defaultClientPolicy: "drachtio-srf-gateway-when-configured-or-host-injected-SipStackGateway",
      typedClientOverride: "SipStackGateway",
      rejectedSdkPackages: [
        {
          packageName: "sip.js",
          ecosystem: "npm",
          reason: "Typed SIP library, but the current package surface needs server-side SIP gateway/dialog control rather than a browser/WebRTC User-Agent-first stack.",
        },
        {
          packageName: "jssip",
          ecosystem: "npm",
          reason: "Typed and maintained SIP library, but its browser/User-Agent-oriented runtime surface is not the best fit for server-side BYOC SIP gateway operations.",
        },
      ],
      guardrails: [
        "Keep inbound SIP request/response acceptance behind host-provided gateway code until the operation surface carries concrete drachtio request/response objects.",
        "Do not report live SIP readiness as healthy unless a drachtio Srf instance/server connection or host gateway readiness implementation is configured.",
        "Keep media, recording, transcription, routing, consent, and retention decisions outside the drachtio signaling adapter.",
      ],
    },
    checkedProviderSdk: {
      checkedAt: "2026-06-25",
      verdict: "provider-protocol-lib-selected",
      packageSurfaceRuntimeSdkAvailable: true,
      selectedPackage: {
        packageName: "drachtio-srf",
        ecosystem: "npm",
        versionChecked: "5.0.24",
        reason: "Maintained typed server-side SIP signaling resource framework with Srf.createUAC and Dialog methods.",
      },
      candidates: [
        {
          package: "drachtio-srf",
          result: "selected-runtime-protocol-lib",
        },
        {
          package: "sip.js",
          result: "rejected-browser-user-agent-oriented-for-this-server-gateway-surface",
        },
        {
          package: "jssip",
          result: "rejected-browser-user-agent-oriented-for-this-server-gateway-surface",
        },
      ],
    },
    bridgeContract: "sip-stack-gateway",
    secureMedia: ["tls", "srtp"],
    webhookEvents: ["call.status", "call.transfer", "recording", "transcription"],
    channelCoverage: {
      sipGatewayContract: "drachtio-srf-gateway-or-host-gateway",
      inboundInviteEvents: "host-gateway-contract",
      outboundInvite: "drachtio-srf-createUAC-or-host-gateway",
      sdpMedia: "drachtio-srf-dialog-modify-or-host-gateway",
      transfer: "drachtio-srf-dialog-REFER-or-host-gateway",
      recordingCallbacks: "sdk-owned-bridge-contract",
      transcriptionCallbacks: "sdk-owned-bridge-contract",
      sipStack: "drachtio-srf-signaling-adapter-for-selected-dialog-operations",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
