import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const sapServiceCloudProviderClientOperations = [
  { alias: "ticket.create", providerClientMethod: "createServiceRequest" },
  { alias: "ticket.read", providerClientMethod: "getServiceRequest" },
  { alias: "ticket.update", providerClientMethod: "updateServiceRequest" },
  { alias: "ticket.search", providerClientMethod: "searchServiceRequests" },
] as const;

export const sapServiceCloudTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.sap-service-cloud",
  name: "SAP Service Cloud",
  packageName: "@cognidesk/integration-ticketing-sap-service-cloud",
  provider: "sap-service-cloud",
  category: "ticketing",
  trustLevel: "official",
  directions: ["bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Runtime coverage uses the built-in SAP Service Cloud OData adapter backed by the official SAP Cloud SDK HTTP client for selected ServiceRequestCollection create, read by ObjectID, update, search, and readiness workflows when baseUrl plus access credentials are provided.",
      "A host-injected SapServiceCloudTicketingProviderClient remains available as an override for SDK-user-owned generated clients, destination handling, authentication, retries, or endpoint policy.",
      "This is not full SAP Service Cloud API coverage; notes, descriptions, attachments, involved parties, service categories, code-list discovery, custom OData services, communication arrangements, workflow actions, v2 migration policy, and broader SAP Cloud for Customer APIs remain outside this adapter.",
    ],
    evidence: [
      { label: "SAP Cloud for Customer OData API", url: "https://help.sap.com/docs/sap-cloud-for-customer/odata-services/sap-cloud-for-customer-odata-api" },
      { label: "SAP Cloud for Customer OData API overview", url: "https://help.sap.com/docs/sap-cloud-for-customer/1364b70b9cbb417ea5e2d80e966d4f49/6c0a463cc9ca450cbd01a9a5057ce682.html" },
      { label: "SAP Cloud for Customer OData API v2 Reference", url: "https://help.sap.com/docs/r/1364b70b9cbb417ea5e2d80e966d4f49/LATEST/en-US/6cb5cd1ebe1c49d8b99c22afa29aa5d4.html" },
      { label: "SAP Cloud for Customer OData Services PDF", url: "https://help.sap.com/doc/77979cd206da4b7f9bd264b390d373fc/CLOUD/en-US/OData_Services.pdf" },
    ],
  },
  credentialRequirements: [
    {
      id: "sap-service-cloud-provider-client",
      label: "Optional SAP Service Cloud provider client override",
      description: "Optional SapServiceCloudTicketingProviderClient override that encapsulates SAP Service Cloud tenant routing, generated SDK/provider runtime, authentication, retries, and endpoint policy.",
      required: false,
      metadata: {
        injectionInterface: "SapServiceCloudTicketingProviderClient",
        credentialOwnership: "host-managed-override",
        defaultClientPolicy: "built-in-odata-adapter-backed-by-sap-cloud-sdk-http-client",
      },
    },
    {
      id: "sap-service-cloud-instance",
      label: "SAP Service Cloud base URL",
      description: "SAP Service Cloud tenant base URL used by the built-in OData adapter, or supplied by a host provider client override.",
      required: false,
      metadata: {
        requiredWhen: "built-in-odata-adapter-backed-by-sap-cloud-sdk-http-client",
      },
    },
    {
      id: "sap-service-cloud-api-access",
      label: "SAP Service Cloud API access",
      description: "Server-side SAP Service Cloud access supplied as accessToken, basic auth, auth headers, or encapsulated in a host provider client override.",
      scopes: ["ServiceRequestCollection:read", "ServiceRequestCollection:write"],
      required: false,
      metadata: {
        requiredWhen: "built-in-odata-adapter-backed-by-sap-cloud-sdk-http-client",
        scopeKind: "internal-capability-labels",
        privilegeGuidance: "These strings are Cognidesk capability labels for ServiceRequestCollection access, not official SAP OAuth scope names. SAP authorization depends on the host client's communication arrangements, destination/auth configuration, business user permissions, and exposed services.",
      },
    },
  ],
  capabilities: [
    {
      capability: "handoff",
      label: "Create SAP Service Cloud handoff",
      description: "Creates or updates SAP Service Cloud ServiceRequestCollection records through the built-in OData adapter or host provider client as SDK-configured support handoff targets.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "sapServiceRequest", label: "SAP Service Request", schemaName: "ServiceRequestCollection" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "create-provider-object",
      label: "Create SAP service requests",
      description: "Creates SAP Service Cloud ServiceRequestCollection tickets through the built-in OData adapter or host provider client from SDK-user-selected workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "sapServiceRequest", label: "SAP Service Request", schemaName: "ServiceRequestCollection" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read SAP service requests",
      description: "Reads SAP Service Cloud service requests by ObjectID.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "sapServiceRequest", label: "SAP Service Request", schemaName: "ServiceRequestCollection" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update SAP service requests",
      description: "Updates SAP Service Cloud ticket fields, statuses, priorities, or SDK-user custom fields through the built-in OData adapter or host provider client.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "sapServiceRequest", label: "SAP Service Request", schemaName: "ServiceRequestCollection" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search SAP service requests",
      description: "Queries SAP Service Cloud ServiceRequestCollection with SDK-user-supplied OData query controls.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "sapServiceRequest", label: "SAP Service Request", schemaName: "ServiceRequestCollection" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
  ],
  operations: [
    {
      alias: "ticket.create",
      capability: "create-provider-object",
      providerObject: "sapServiceRequest",
      audiences: ["customer-facing", "internal-support", "mixed"],
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.read",
      capability: "read-provider-object",
      providerObject: "sapServiceRequest",
      audiences: ["customer-facing", "internal-support", "mixed"],
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.update",
      capability: "update-provider-object",
      providerObject: "sapServiceRequest",
      audiences: ["internal-support", "mixed"],
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.search",
      capability: "search-provider-object",
      providerObject: "sapServiceRequest",
      audiences: ["customer-facing", "internal-support", "mixed"],
      exposesSensitiveData: true,
      requiresCredential: true,
    },
  ],
  privacyNotes: [
    "SAP service requests can contain customer account/contact details, ticket descriptions, categories, priorities, involved parties, notes, and internal routing data.",
    "SAP API credentials stay server-side and Studio receives only readiness and scope status.",
  ],
  limitations: [
    "SAP tenant exposure, communication arrangements, required fields, statuses, code lists, workflow rules, and extensions are SDK-user host-client configuration.",
    "The built-in adapter covers selected ServiceRequestCollection OData operations only; hosts can still inject a SapServiceCloudTicketingProviderClient for generated clients, destinations, custom auth, CSRF preflights, or retry policy.",
    "SDK users own escalation timing, customer matching, field mapping, reply visibility, retention, and notification policy before calling SAP APIs.",
  ],
  metadata: {
    implementation: {
      strategy: "provider-sdk-http-client-odata-adapter",
      adapterKind: "sap-cloud-sdk-http-client-odata-adapter",
      providerClientInterface: "SapServiceCloudTicketingProviderClient",
      providerSdkPackage: "@sap-cloud-sdk/http-client",
      defaultHttpClient: "executeHttpRequest",
      defaultFetchClient: "none-provider-client-override-only",
      packageOwnedRestClient: false,
      packageOwnedODataMapping: true,
      providerClientOverride: true,
      manifestImport: "no-client-initialization",
    },
    implementationStrategy: "sap-cloud-sdk-http-client-odata-adapter",
    providerClient: {
      interface: "SapServiceCloudTicketingProviderClient",
      injectionPolicy: "optional-runtime-override",
      importPolicy: "optional-host-override",
      defaultClient: "built-in-odata-adapter-backed-by-sap-cloud-sdk-http-client",
    },
    providerSdkRuntime: {
      package: "@sap-cloud-sdk/http-client",
      checkedVersion: "4.7.0",
      license: "Apache-2.0",
      importedRuntimeFunction: "executeHttpRequest",
      importedRuntimeTypes: ["HttpRequestConfig", "HttpResponse", "Method"],
      defaultRuntime: "SAP Cloud SDK HTTP client executes the package-owned ServiceRequestCollection OData mapping.",
      compatibilityFallback: "Explicit host fetch or retry options keep the legacy integration-kit JSON transport for callers that require fetch injection or integration-kit retry semantics.",
    },
    checkedProviderSdk: {
      checkedAt: "2026-06-25",
      verdict: "sdk-backed-generic-odata-http-client",
      reason: "SAP Cloud SDK for JavaScript is official and current. No generated ServiceRequestCollection client is bundled here, so this package owns the typed OData path/body mapping while delegating runtime HTTP execution to @sap-cloud-sdk/http-client.",
      candidates: [
        {
          package: "@sap-cloud-sdk/http-client",
          checkedVersion: "4.7.0",
          license: "Apache-2.0",
          result: "accepted-runtime-http-client",
          reason: "Official SAP Cloud SDK HTTP client provides executeHttpRequest and typed request/response surfaces suitable for the package's existing ServiceRequestCollection OData mapping.",
        },
        {
          package: "@sap-cloud-sdk/odata-v2",
          checkedVersion: "4.7.0",
          license: "Apache-2.0",
          result: "not-generated-client-in-this-package",
          reason: "Official generic SAP Cloud SDK OData v2 runtime; requires generated service client metadata and host destination/auth setup rather than providing a SAP Service Cloud ServiceRequestCollection client.",
        },
        {
          package: "@sap-cloud-sdk/generator",
          checkedVersion: "4.7.0",
          license: "Apache-2.0",
          result: "not-runtime-client",
          reason: "Official generator for EDMX-based clients; this package does not own or redistribute tenant/version-specific SAP Service Cloud metadata.",
        },
      ],
      sources: [
        "https://sap.github.io/cloud-sdk/docs/js/overview",
        "https://sap.github.io/cloud-sdk/docs/js/features/odata/overview",
        "https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client",
        "https://www.npmjs.com/package/@sap-cloud-sdk/http-client",
        "https://www.npmjs.com/package/@sap-cloud-sdk/odata-v2",
      ],
    },
    providerRestAdapterSupportSurface: {
      source: "Built-in SAP Service Cloud OData mapping executed through SAP Cloud SDK HTTP client",
      adapterKind: "sap-cloud-sdk-http-client-odata-adapter",
      operations: sapServiceCloudProviderClientOperations,
    },
    checkedProviderApiCoverage: {
      verifiedAt: "2026-06-18",
      sourceKind: "checked-endpoint-family-inventory",
      coverageArtifact: "docs/provider-coverage/sap-service-cloud-checked-c4c-odata-2026-06-18.inventory.json",
      checkedFamilyCount: 3,
      implementedFamilyCount: 2,
      gapFamilyCount: 1,
      implementedOperationCount: 4,
    },
    channelCoverage: {
      serviceRequests: "typed-odata-adapter-create-read-update-search",
      csrfToken: "typed-optional-header-supported-host-owned-prefetch",
      readinessSearch: "typed-odata-adapter-readiness",
      attachmentFolder: "provider-supported-not-typed",
      notesInvolvedPartiesCodeLists: "provider-supported-not-typed",
      workflowRulesCommunicationArrangements: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
