import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { SLACK_WEB_API_GENERATED_FUNCTION_COUNT } from "./web-api-client.generated.js";
import {
  SLACK_WEB_API_OPERATION_COUNT,
  SLACK_WEB_API_PATH_COUNT,
  SLACK_WEB_API_SPEC_VERSION,
} from "./web-api-operations.generated.js";

export const slackWorkplaceProviderManifest = defineProviderPackage({
  id: "workplace.slack",
  name: "Slack",
  packageName: "@cognidesk/integrations",
  provider: "slack",
  category: "workplace",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["internal-support", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Slack's archived official Web API Swagger 2.0 spec.",
      "Typed convenience helpers remain available for selected Slack workplace support workflows: chat.postMessage, chat.postEphemeral, chat.update, conversations.history, conversations.replies, the current external file upload sequence, auth.test readiness, Events API/interactivity parsing, and signed request validation.",
      "Receive coverage is HTTP Events API/interactivity parsing only; this package does not configure Slack app subscriptions, apps.connections.open, xapp tokens, WebSocket reconnects, Socket Mode ingestion, or Socket Mode payload acknowledgements.",
      "This is not full current Slack platform coverage; Slack's official specs repository was archived on 2024-03-27, and Events subscriptions, Socket Mode protocol, SCIM, Audit Logs, Legal Holds, Status API, workflow runtime behavior, and current docs-only methods remain separate surfaces.",
    ],
    evidence: [
      {
        label: "Slack archived official Web API Swagger",
        url: "https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json",
      },
      { label: "Slack official API specs repository", url: "https://github.com/slackapi/slack-api-specs" },
      { label: "Slack Web API methods", url: "https://docs.slack.dev/reference/methods/" },
      { label: "Slack chat.postMessage", url: "https://docs.slack.dev/reference/methods/chat.postMessage/" },
      { label: "Slack chat.update", url: "https://docs.slack.dev/reference/methods/chat.update/" },
      { label: "Slack conversations.history", url: "https://docs.slack.dev/reference/methods/conversations.history/" },
      { label: "Slack conversations.replies", url: "https://docs.slack.dev/reference/methods/conversations.replies/" },
      {
        label: "Slack files.getUploadURLExternal",
        url: "https://docs.slack.dev/reference/methods/files.getUploadURLExternal/",
      },
      {
        label: "Slack external file upload flow",
        url: "https://docs.slack.dev/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay/",
      },
      { label: "Slack Events API", url: "https://docs.slack.dev/apis/events-api/" },
      {
        label: "Slack request verification",
        url: "https://docs.slack.dev/authentication/verifying-requests-from-slack/",
      },
      { label: "Slack Web API rate limits", url: "https://docs.slack.dev/apis/web-api/rate-limits" },
      {
        label: "Slack conversations.history/replies rate-limit changes",
        url: "https://docs.slack.dev/changelog/2025/05/29/rate-limit-changes-for-non-marketplace-apps",
      },
    ],
  },
  credentialRequirements: [
    {
      id: "slack-bot-token",
      label: "Slack bot token",
      description: "Server-side bot token used for Slack Web API calls such as chat.postMessage and auth.test.",
      scopes: [
        "chat:write",
        "chat:write.public",
        "channels:history",
        "groups:history",
        "im:history",
        "mpim:history",
        "files:write",
      ],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "slack-signing-secret",
      label: "Slack signing secret",
      description: "Server-side signing secret used to validate Slack Events API and interactivity requests.",
      required: true,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Slack events",
      description: "Validates and parses Slack Events API and interactivity payloads for SDK-user-owned support flows.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "slackEvent", label: "Slack Event" },
        { kind: "slackInteraction", label: "Slack Interaction" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Post Slack messages",
      description: "Posts customer-visible or channel-visible support messages through Slack chat.postMessage.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "slackMessage", label: "Slack Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "notify",
      label: "Post agent-assist messages",
      description: "Posts Slack ephemeral messages for internal agent-assist workflows when Slack provides a target user.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "slackEphemeralMessage", label: "Slack Ephemeral Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Slack threads",
      description: "Associates messages with Slack thread timestamps and reads channel history for thread-aware support.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "slackMessage", label: "Slack Message" },
        { kind: "slackThread", label: "Slack Thread" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Upload Slack files",
      description: "Runs Slack's external upload URL and complete-upload sequence for SDK-user-selected file sharing.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "slackFile", label: "Slack File" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Slack conversation history",
      description: "Reads Slack conversations.history for SDK-user-selected channels and history windows.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "slackConversationHistory", label: "Slack Conversation History" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Slack messages",
      description: "Updates Slack messages through chat.update when SDK-user policy permits mutation.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "slackMessage", label: "Slack Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "slack.request-signature",
      label: "Validate Slack request signatures",
      description: "Validates Slack X-Slack-Signature and X-Slack-Request-Timestamp values for Events API and interactivity.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "slackSignedRequest", label: "Slack Signed Request" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Slack messages, channel identifiers, user identifiers, event payloads, interaction payloads, and workspace metadata can contain internal support context and customer data.",
    "Slack bot tokens and signing secrets stay server-side and are represented in Studio only as credential readiness.",
  ],
  limitations: [
    "Available Slack operations depend on the SDK user's app scopes, workspace policy, channel membership, Enterprise Grid policy, and user targets for ephemeral messages.",
    "Slack conversations.history and conversations.replies rate limits vary by Marketplace approval, commercial distribution, and install date; SDK users own pagination, Retry-After handling, retry, and backoff policy. Slack recommends designing message posting around roughly one request per second per channel.",
    "Customer visibility, agent-assist routing, approval, retention, redaction, and escalation behavior remain SDK-user configuration.",
  ],
  metadata: {
    channelCoverage: {
      archivedWebApi: "generated-per-operation-functions",
      chatMessages: "typed-post-update",
      ephemeralMessages: "typed-post",
      conversationsHistoryReplies: "typed-read",
      externalFileUpload: "typed-upload",
      authReadiness: "typed-read",
      eventsInteractivity: "typed-parse-verify",
      socketMode: "provider-supported-not-typed",
      viewsWorkflowsAdminAudit: "provider-supported-not-typed",
    },
    generatedProviderSliceVerification: {
      provider: "slack-web-api-archived-swagger",
      apiVersion: SLACK_WEB_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/slack-web-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/slack-web-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/slack-web-api-2026-06-18.functions.json",
      documentedPathCount: SLACK_WEB_API_PATH_COUNT,
      documentedOperationCount: SLACK_WEB_API_OPERATION_COUNT,
      implementedOperationCount: SLACK_WEB_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: SLACK_WEB_API_GENERATED_FUNCTION_COUNT,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
