// Generated from the archived official Slack Web API Swagger spec (https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json).
// Do not edit by hand; run scripts/generate-slack-web-api.mjs after checking upstream docs.

export const SLACK_WEB_API_GENERATED_AT = "2026-06-18";
export const SLACK_WEB_API_SPEC_SOURCE = "https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json";
export const SLACK_WEB_API_DOCS_SOURCE = "https://docs.slack.dev/reference/methods/";
export const SLACK_WEB_API_SPEC_REPOSITORY = "https://github.com/slackapi/slack-api-specs";
export const SLACK_WEB_API_SPEC_VERSION = "1.7.0";
export const SLACK_WEB_API_SWAGGER_VERSION = "2.0";
export const SLACK_WEB_API_PATH_COUNT = 174;
export const SLACK_WEB_API_OPERATION_COUNT = 174;

export interface SlackWebApiOperation {
  uid: string;
  operationId: string;
  functionName: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  summary: string;
  tags: readonly string[];
}

export const SLACK_WEB_API_OPERATIONS = JSON.parse("[{\"uid\":\"POST /admin.apps.approve\",\"operationId\":\"admin_apps_approve\",\"functionName\":\"AdminAppsApprove\",\"method\":\"POST\",\"path\":\"/admin.apps.approve\",\"summary\":\"\",\"tags\":[\"admin.apps\",\"admin\"]},{\"uid\":\"GET /admin.apps.approved.list\",\"operationId\":\"admin_apps_approved_list\",\"functionName\":\"AdminAppsApprovedList\",\"method\":\"GET\",\"path\":\"/admin.apps.approved.list\",\"summary\":\"\",\"tags\":[\"admin.apps.approved\",\"admin\"]},{\"uid\":\"GET /admin.apps.requests.list\",\"operationId\":\"admin_apps_requests_list\",\"functionName\":\"AdminAppsRequestsList\",\"method\":\"GET\",\"path\":\"/admin.apps.requests.list\",\"summary\":\"\",\"tags\":[\"admin.apps.requests\",\"admin\"]},{\"uid\":\"POST /admin.apps.restrict\",\"operationId\":\"admin_apps_restrict\",\"functionName\":\"AdminAppsRestrict\",\"method\":\"POST\",\"path\":\"/admin.apps.restrict\",\"summary\":\"\",\"tags\":[\"admin.apps\",\"admin\"]},{\"uid\":\"GET /admin.apps.restricted.list\",\"operationId\":\"admin_apps_restricted_list\",\"functionName\":\"AdminAppsRestrictedList\",\"method\":\"GET\",\"path\":\"/admin.apps.restricted.list\",\"summary\":\"\",\"tags\":[\"admin.apps.restricted\",\"admin\"]},{\"uid\":\"POST /admin.conversations.archive\",\"operationId\":\"admin_conversations_archive\",\"functionName\":\"AdminConversationsArchive\",\"method\":\"POST\",\"path\":\"/admin.conversations.archive\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.conversations.convertToPrivate\",\"operationId\":\"admin_conversations_convertToPrivate\",\"functionName\":\"AdminConversationsConvertToPrivate\",\"method\":\"POST\",\"path\":\"/admin.conversations.convertToPrivate\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.conversations.create\",\"operationId\":\"admin_conversations_create\",\"functionName\":\"AdminConversationsCreate\",\"method\":\"POST\",\"path\":\"/admin.conversations.create\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.conversations.delete\",\"operationId\":\"admin_conversations_delete\",\"functionName\":\"AdminConversationsDelete\",\"method\":\"POST\",\"path\":\"/admin.conversations.delete\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.conversations.disconnectShared\",\"operationId\":\"admin_conversations_disconnectShared\",\"functionName\":\"AdminConversationsDisconnectShared\",\"method\":\"POST\",\"path\":\"/admin.conversations.disconnectShared\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"GET /admin.conversations.ekm.listOriginalConnectedChannelInfo\",\"operationId\":\"admin_conversations_ekm_listOriginalConnectedChannelInfo\",\"functionName\":\"AdminConversationsEkmListOriginalConnectedChannelInfo\",\"method\":\"GET\",\"path\":\"/admin.conversations.ekm.listOriginalConnectedChannelInfo\",\"summary\":\"\",\"tags\":[\"admin.conversations.ekm\",\"admin\"]},{\"uid\":\"GET /admin.conversations.getConversationPrefs\",\"operationId\":\"admin_conversations_getConversationPrefs\",\"functionName\":\"AdminConversationsGetConversationPrefs\",\"method\":\"GET\",\"path\":\"/admin.conversations.getConversationPrefs\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"GET /admin.conversations.getTeams\",\"operationId\":\"admin_conversations_getTeams\",\"functionName\":\"AdminConversationsGetTeams\",\"method\":\"GET\",\"path\":\"/admin.conversations.getTeams\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.conversations.invite\",\"operationId\":\"admin_conversations_invite\",\"functionName\":\"AdminConversationsInvite\",\"method\":\"POST\",\"path\":\"/admin.conversations.invite\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.conversations.rename\",\"operationId\":\"admin_conversations_rename\",\"functionName\":\"AdminConversationsRename\",\"method\":\"POST\",\"path\":\"/admin.conversations.rename\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.conversations.restrictAccess.addGroup\",\"operationId\":\"admin_conversations_restrictAccess_addGroup\",\"functionName\":\"AdminConversationsRestrictAccessAddGroup\",\"method\":\"POST\",\"path\":\"/admin.conversations.restrictAccess.addGroup\",\"summary\":\"\",\"tags\":[\"admin.conversations.restrictAccess\",\"admin\"]},{\"uid\":\"GET /admin.conversations.restrictAccess.listGroups\",\"operationId\":\"admin_conversations_restrictAccess_listGroups\",\"functionName\":\"AdminConversationsRestrictAccessListGroups\",\"method\":\"GET\",\"path\":\"/admin.conversations.restrictAccess.listGroups\",\"summary\":\"\",\"tags\":[\"admin.conversations.restrictAccess\",\"admin\"]},{\"uid\":\"POST /admin.conversations.restrictAccess.removeGroup\",\"operationId\":\"admin_conversations_restrictAccess_removeGroup\",\"functionName\":\"AdminConversationsRestrictAccessRemoveGroup\",\"method\":\"POST\",\"path\":\"/admin.conversations.restrictAccess.removeGroup\",\"summary\":\"\",\"tags\":[\"admin.conversations.restrictAccess\",\"admin\"]},{\"uid\":\"GET /admin.conversations.search\",\"operationId\":\"admin_conversations_search\",\"functionName\":\"AdminConversationsSearch\",\"method\":\"GET\",\"path\":\"/admin.conversations.search\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.conversations.setConversationPrefs\",\"operationId\":\"admin_conversations_setConversationPrefs\",\"functionName\":\"AdminConversationsSetConversationPrefs\",\"method\":\"POST\",\"path\":\"/admin.conversations.setConversationPrefs\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.conversations.setTeams\",\"operationId\":\"admin_conversations_setTeams\",\"functionName\":\"AdminConversationsSetTeams\",\"method\":\"POST\",\"path\":\"/admin.conversations.setTeams\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.conversations.unarchive\",\"operationId\":\"admin_conversations_unarchive\",\"functionName\":\"AdminConversationsUnarchive\",\"method\":\"POST\",\"path\":\"/admin.conversations.unarchive\",\"summary\":\"\",\"tags\":[\"admin.conversations\",\"admin\"]},{\"uid\":\"POST /admin.emoji.add\",\"operationId\":\"admin_emoji_add\",\"functionName\":\"AdminEmojiAdd\",\"method\":\"POST\",\"path\":\"/admin.emoji.add\",\"summary\":\"\",\"tags\":[\"admin.emoji\",\"admin\"]},{\"uid\":\"POST /admin.emoji.addAlias\",\"operationId\":\"admin_emoji_addAlias\",\"functionName\":\"AdminEmojiAddAlias\",\"method\":\"POST\",\"path\":\"/admin.emoji.addAlias\",\"summary\":\"\",\"tags\":[\"admin.emoji\",\"admin\"]},{\"uid\":\"GET /admin.emoji.list\",\"operationId\":\"admin_emoji_list\",\"functionName\":\"AdminEmojiList\",\"method\":\"GET\",\"path\":\"/admin.emoji.list\",\"summary\":\"\",\"tags\":[\"admin.emoji\",\"admin\"]},{\"uid\":\"POST /admin.emoji.remove\",\"operationId\":\"admin_emoji_remove\",\"functionName\":\"AdminEmojiRemove\",\"method\":\"POST\",\"path\":\"/admin.emoji.remove\",\"summary\":\"\",\"tags\":[\"admin.emoji\",\"admin\"]},{\"uid\":\"POST /admin.emoji.rename\",\"operationId\":\"admin_emoji_rename\",\"functionName\":\"AdminEmojiRename\",\"method\":\"POST\",\"path\":\"/admin.emoji.rename\",\"summary\":\"\",\"tags\":[\"admin.emoji\",\"admin\"]},{\"uid\":\"POST /admin.inviteRequests.approve\",\"operationId\":\"admin_inviteRequests_approve\",\"functionName\":\"AdminInviteRequestsApprove\",\"method\":\"POST\",\"path\":\"/admin.inviteRequests.approve\",\"summary\":\"\",\"tags\":[\"admin.inviteRequests\",\"admin\"]},{\"uid\":\"GET /admin.inviteRequests.approved.list\",\"operationId\":\"admin_inviteRequests_approved_list\",\"functionName\":\"AdminInviteRequestsApprovedList\",\"method\":\"GET\",\"path\":\"/admin.inviteRequests.approved.list\",\"summary\":\"\",\"tags\":[\"admin.inviteRequests.approved\",\"admin\"]},{\"uid\":\"GET /admin.inviteRequests.denied.list\",\"operationId\":\"admin_inviteRequests_denied_list\",\"functionName\":\"AdminInviteRequestsDeniedList\",\"method\":\"GET\",\"path\":\"/admin.inviteRequests.denied.list\",\"summary\":\"\",\"tags\":[\"admin.inviteRequests.denied\",\"admin\"]},{\"uid\":\"POST /admin.inviteRequests.deny\",\"operationId\":\"admin_inviteRequests_deny\",\"functionName\":\"AdminInviteRequestsDeny\",\"method\":\"POST\",\"path\":\"/admin.inviteRequests.deny\",\"summary\":\"\",\"tags\":[\"admin.inviteRequests\",\"admin\"]},{\"uid\":\"GET /admin.inviteRequests.list\",\"operationId\":\"admin_inviteRequests_list\",\"functionName\":\"AdminInviteRequestsList\",\"method\":\"GET\",\"path\":\"/admin.inviteRequests.list\",\"summary\":\"\",\"tags\":[\"admin.inviteRequests\",\"admin\"]},{\"uid\":\"GET /admin.teams.admins.list\",\"operationId\":\"admin_teams_admins_list\",\"functionName\":\"AdminTeamsAdminsList\",\"method\":\"GET\",\"path\":\"/admin.teams.admins.list\",\"summary\":\"\",\"tags\":[\"admin.teams.admins\",\"admin\"]},{\"uid\":\"POST /admin.teams.create\",\"operationId\":\"admin_teams_create\",\"functionName\":\"AdminTeamsCreate\",\"method\":\"POST\",\"path\":\"/admin.teams.create\",\"summary\":\"\",\"tags\":[\"admin.teams\",\"admin\"]},{\"uid\":\"GET /admin.teams.list\",\"operationId\":\"admin_teams_list\",\"functionName\":\"AdminTeamsList\",\"method\":\"GET\",\"path\":\"/admin.teams.list\",\"summary\":\"\",\"tags\":[\"admin.teams\",\"admin\"]},{\"uid\":\"GET /admin.teams.owners.list\",\"operationId\":\"admin_teams_owners_list\",\"functionName\":\"AdminTeamsOwnersList\",\"method\":\"GET\",\"path\":\"/admin.teams.owners.list\",\"summary\":\"\",\"tags\":[\"admin.teams.owners\",\"admin\"]},{\"uid\":\"GET /admin.teams.settings.info\",\"operationId\":\"admin_teams_settings_info\",\"functionName\":\"AdminTeamsSettingsInfo\",\"method\":\"GET\",\"path\":\"/admin.teams.settings.info\",\"summary\":\"\",\"tags\":[\"admin.teams.settings\",\"admin\"]},{\"uid\":\"POST /admin.teams.settings.setDefaultChannels\",\"operationId\":\"admin_teams_settings_setDefaultChannels\",\"functionName\":\"AdminTeamsSettingsSetDefaultChannels\",\"method\":\"POST\",\"path\":\"/admin.teams.settings.setDefaultChannels\",\"summary\":\"\",\"tags\":[\"admin.teams.settings\",\"admin\"]},{\"uid\":\"POST /admin.teams.settings.setDescription\",\"operationId\":\"admin_teams_settings_setDescription\",\"functionName\":\"AdminTeamsSettingsSetDescription\",\"method\":\"POST\",\"path\":\"/admin.teams.settings.setDescription\",\"summary\":\"\",\"tags\":[\"admin.teams.settings\",\"admin\"]},{\"uid\":\"POST /admin.teams.settings.setDiscoverability\",\"operationId\":\"admin_teams_settings_setDiscoverability\",\"functionName\":\"AdminTeamsSettingsSetDiscoverability\",\"method\":\"POST\",\"path\":\"/admin.teams.settings.setDiscoverability\",\"summary\":\"\",\"tags\":[\"admin.teams.settings\",\"admin\"]},{\"uid\":\"POST /admin.teams.settings.setIcon\",\"operationId\":\"admin_teams_settings_setIcon\",\"functionName\":\"AdminTeamsSettingsSetIcon\",\"method\":\"POST\",\"path\":\"/admin.teams.settings.setIcon\",\"summary\":\"\",\"tags\":[\"admin.teams.settings\",\"admin\"]},{\"uid\":\"POST /admin.teams.settings.setName\",\"operationId\":\"admin_teams_settings_setName\",\"functionName\":\"AdminTeamsSettingsSetName\",\"method\":\"POST\",\"path\":\"/admin.teams.settings.setName\",\"summary\":\"\",\"tags\":[\"admin.teams.settings\",\"admin\"]},{\"uid\":\"POST /admin.usergroups.addChannels\",\"operationId\":\"admin_usergroups_addChannels\",\"functionName\":\"AdminUsergroupsAddChannels\",\"method\":\"POST\",\"path\":\"/admin.usergroups.addChannels\",\"summary\":\"\",\"tags\":[\"admin.usergroups\",\"admin\"]},{\"uid\":\"POST /admin.usergroups.addTeams\",\"operationId\":\"admin_usergroups_addTeams\",\"functionName\":\"AdminUsergroupsAddTeams\",\"method\":\"POST\",\"path\":\"/admin.usergroups.addTeams\",\"summary\":\"\",\"tags\":[\"admin.usergroups\",\"admin\"]},{\"uid\":\"GET /admin.usergroups.listChannels\",\"operationId\":\"admin_usergroups_listChannels\",\"functionName\":\"AdminUsergroupsListChannels\",\"method\":\"GET\",\"path\":\"/admin.usergroups.listChannels\",\"summary\":\"\",\"tags\":[\"admin.usergroups\",\"admin\"]},{\"uid\":\"POST /admin.usergroups.removeChannels\",\"operationId\":\"admin_usergroups_removeChannels\",\"functionName\":\"AdminUsergroupsRemoveChannels\",\"method\":\"POST\",\"path\":\"/admin.usergroups.removeChannels\",\"summary\":\"\",\"tags\":[\"admin.usergroups\",\"admin\"]},{\"uid\":\"POST /admin.users.assign\",\"operationId\":\"admin_users_assign\",\"functionName\":\"AdminUsersAssign\",\"method\":\"POST\",\"path\":\"/admin.users.assign\",\"summary\":\"\",\"tags\":[\"admin.users\",\"admin\"]},{\"uid\":\"POST /admin.users.invite\",\"operationId\":\"admin_users_invite\",\"functionName\":\"AdminUsersInvite\",\"method\":\"POST\",\"path\":\"/admin.users.invite\",\"summary\":\"\",\"tags\":[\"admin.users\",\"admin\"]},{\"uid\":\"GET /admin.users.list\",\"operationId\":\"admin_users_list\",\"functionName\":\"AdminUsersList\",\"method\":\"GET\",\"path\":\"/admin.users.list\",\"summary\":\"\",\"tags\":[\"admin.users\",\"admin\"]},{\"uid\":\"POST /admin.users.remove\",\"operationId\":\"admin_users_remove\",\"functionName\":\"AdminUsersRemove\",\"method\":\"POST\",\"path\":\"/admin.users.remove\",\"summary\":\"\",\"tags\":[\"admin.users\",\"admin\"]},{\"uid\":\"POST /admin.users.session.invalidate\",\"operationId\":\"admin_users_session_invalidate\",\"functionName\":\"AdminUsersSessionInvalidate\",\"method\":\"POST\",\"path\":\"/admin.users.session.invalidate\",\"summary\":\"\",\"tags\":[\"admin.users.session\",\"admin\"]},{\"uid\":\"POST /admin.users.session.reset\",\"operationId\":\"admin_users_session_reset\",\"functionName\":\"AdminUsersSessionReset\",\"method\":\"POST\",\"path\":\"/admin.users.session.reset\",\"summary\":\"\",\"tags\":[\"admin.users.session\",\"admin\"]},{\"uid\":\"POST /admin.users.setAdmin\",\"operationId\":\"admin_users_setAdmin\",\"functionName\":\"AdminUsersSetAdmin\",\"method\":\"POST\",\"path\":\"/admin.users.setAdmin\",\"summary\":\"\",\"tags\":[\"admin.users\",\"admin\"]},{\"uid\":\"POST /admin.users.setExpiration\",\"operationId\":\"admin_users_setExpiration\",\"functionName\":\"AdminUsersSetExpiration\",\"method\":\"POST\",\"path\":\"/admin.users.setExpiration\",\"summary\":\"\",\"tags\":[\"admin.users\",\"admin\"]},{\"uid\":\"POST /admin.users.setOwner\",\"operationId\":\"admin_users_setOwner\",\"functionName\":\"AdminUsersSetOwner\",\"method\":\"POST\",\"path\":\"/admin.users.setOwner\",\"summary\":\"\",\"tags\":[\"admin.users\",\"admin\"]},{\"uid\":\"POST /admin.users.setRegular\",\"operationId\":\"admin_users_setRegular\",\"functionName\":\"AdminUsersSetRegular\",\"method\":\"POST\",\"path\":\"/admin.users.setRegular\",\"summary\":\"\",\"tags\":[\"admin.users\",\"admin\"]},{\"uid\":\"GET /api.test\",\"operationId\":\"api_test\",\"functionName\":\"ApiTest\",\"method\":\"GET\",\"path\":\"/api.test\",\"summary\":\"\",\"tags\":[\"api\"]},{\"uid\":\"GET /apps.event.authorizations.list\",\"operationId\":\"apps_event_authorizations_list\",\"functionName\":\"AppsEventAuthorizationsList\",\"method\":\"GET\",\"path\":\"/apps.event.authorizations.list\",\"summary\":\"\",\"tags\":[\"apps.event.authorizations\",\"apps\"]},{\"uid\":\"GET /apps.permissions.info\",\"operationId\":\"apps_permissions_info\",\"functionName\":\"AppsPermissionsInfo\",\"method\":\"GET\",\"path\":\"/apps.permissions.info\",\"summary\":\"\",\"tags\":[\"apps.permissions\",\"apps\"]},{\"uid\":\"GET /apps.permissions.request\",\"operationId\":\"apps_permissions_request\",\"functionName\":\"AppsPermissionsRequest\",\"method\":\"GET\",\"path\":\"/apps.permissions.request\",\"summary\":\"\",\"tags\":[\"apps.permissions\",\"apps\"]},{\"uid\":\"GET /apps.permissions.resources.list\",\"operationId\":\"apps_permissions_resources_list\",\"functionName\":\"AppsPermissionsResourcesList\",\"method\":\"GET\",\"path\":\"/apps.permissions.resources.list\",\"summary\":\"\",\"tags\":[\"apps.permissions.resources\",\"apps\"]},{\"uid\":\"GET /apps.permissions.scopes.list\",\"operationId\":\"apps_permissions_scopes_list\",\"functionName\":\"AppsPermissionsScopesList\",\"method\":\"GET\",\"path\":\"/apps.permissions.scopes.list\",\"summary\":\"\",\"tags\":[\"apps.permissions.scopes\",\"apps\"]},{\"uid\":\"GET /apps.permissions.users.list\",\"operationId\":\"apps_permissions_users_list\",\"functionName\":\"AppsPermissionsUsersList\",\"method\":\"GET\",\"path\":\"/apps.permissions.users.list\",\"summary\":\"\",\"tags\":[\"apps.permissions.users\",\"apps\"]},{\"uid\":\"GET /apps.permissions.users.request\",\"operationId\":\"apps_permissions_users_request\",\"functionName\":\"AppsPermissionsUsersRequest\",\"method\":\"GET\",\"path\":\"/apps.permissions.users.request\",\"summary\":\"\",\"tags\":[\"apps.permissions.users\",\"apps\"]},{\"uid\":\"GET /apps.uninstall\",\"operationId\":\"apps_uninstall\",\"functionName\":\"AppsUninstall\",\"method\":\"GET\",\"path\":\"/apps.uninstall\",\"summary\":\"\",\"tags\":[\"apps\"]},{\"uid\":\"GET /auth.revoke\",\"operationId\":\"auth_revoke\",\"functionName\":\"AuthRevoke\",\"method\":\"GET\",\"path\":\"/auth.revoke\",\"summary\":\"\",\"tags\":[\"auth\"]},{\"uid\":\"GET /auth.test\",\"operationId\":\"auth_test\",\"functionName\":\"AuthTest\",\"method\":\"GET\",\"path\":\"/auth.test\",\"summary\":\"\",\"tags\":[\"auth\"]},{\"uid\":\"GET /bots.info\",\"operationId\":\"bots_info\",\"functionName\":\"BotsInfo\",\"method\":\"GET\",\"path\":\"/bots.info\",\"summary\":\"\",\"tags\":[\"bots\"]},{\"uid\":\"POST /calls.add\",\"operationId\":\"calls_add\",\"functionName\":\"CallsAdd\",\"method\":\"POST\",\"path\":\"/calls.add\",\"summary\":\"\",\"tags\":[\"calls\"]},{\"uid\":\"POST /calls.end\",\"operationId\":\"calls_end\",\"functionName\":\"CallsEnd\",\"method\":\"POST\",\"path\":\"/calls.end\",\"summary\":\"\",\"tags\":[\"calls\"]},{\"uid\":\"GET /calls.info\",\"operationId\":\"calls_info\",\"functionName\":\"CallsInfo\",\"method\":\"GET\",\"path\":\"/calls.info\",\"summary\":\"\",\"tags\":[\"calls\"]},{\"uid\":\"POST /calls.participants.add\",\"operationId\":\"calls_participants_add\",\"functionName\":\"CallsParticipantsAdd\",\"method\":\"POST\",\"path\":\"/calls.participants.add\",\"summary\":\"\",\"tags\":[\"calls.participants\",\"calls\"]},{\"uid\":\"POST /calls.participants.remove\",\"operationId\":\"calls_participants_remove\",\"functionName\":\"CallsParticipantsRemove\",\"method\":\"POST\",\"path\":\"/calls.participants.remove\",\"summary\":\"\",\"tags\":[\"calls.participants\",\"calls\"]},{\"uid\":\"POST /calls.update\",\"operationId\":\"calls_update\",\"functionName\":\"CallsUpdate\",\"method\":\"POST\",\"path\":\"/calls.update\",\"summary\":\"\",\"tags\":[\"calls\"]},{\"uid\":\"POST /chat.delete\",\"operationId\":\"chat_delete\",\"functionName\":\"ChatDelete\",\"method\":\"POST\",\"path\":\"/chat.delete\",\"summary\":\"\",\"tags\":[\"chat\"]},{\"uid\":\"POST /chat.deleteScheduledMessage\",\"operationId\":\"chat_deleteScheduledMessage\",\"functionName\":\"ChatDeleteScheduledMessage\",\"method\":\"POST\",\"path\":\"/chat.deleteScheduledMessage\",\"summary\":\"\",\"tags\":[\"chat\"]},{\"uid\":\"GET /chat.getPermalink\",\"operationId\":\"chat_getPermalink\",\"functionName\":\"ChatGetPermalink\",\"method\":\"GET\",\"path\":\"/chat.getPermalink\",\"summary\":\"\",\"tags\":[\"chat\"]},{\"uid\":\"POST /chat.meMessage\",\"operationId\":\"chat_meMessage\",\"functionName\":\"ChatMeMessage\",\"method\":\"POST\",\"path\":\"/chat.meMessage\",\"summary\":\"\",\"tags\":[\"chat\"]},{\"uid\":\"POST /chat.postEphemeral\",\"operationId\":\"chat_postEphemeral\",\"functionName\":\"ChatPostEphemeral\",\"method\":\"POST\",\"path\":\"/chat.postEphemeral\",\"summary\":\"\",\"tags\":[\"chat\"]},{\"uid\":\"POST /chat.postMessage\",\"operationId\":\"chat_postMessage\",\"functionName\":\"ChatPostMessage\",\"method\":\"POST\",\"path\":\"/chat.postMessage\",\"summary\":\"\",\"tags\":[\"chat\"]},{\"uid\":\"POST /chat.scheduleMessage\",\"operationId\":\"chat_scheduleMessage\",\"functionName\":\"ChatScheduleMessage\",\"method\":\"POST\",\"path\":\"/chat.scheduleMessage\",\"summary\":\"\",\"tags\":[\"chat\"]},{\"uid\":\"GET /chat.scheduledMessages.list\",\"operationId\":\"chat_scheduledMessages_list\",\"functionName\":\"ChatScheduledMessagesList\",\"method\":\"GET\",\"path\":\"/chat.scheduledMessages.list\",\"summary\":\"\",\"tags\":[\"chat.scheduledMessages\",\"chat\"]},{\"uid\":\"POST /chat.unfurl\",\"operationId\":\"chat_unfurl\",\"functionName\":\"ChatUnfurl\",\"method\":\"POST\",\"path\":\"/chat.unfurl\",\"summary\":\"\",\"tags\":[\"chat\"]},{\"uid\":\"POST /chat.update\",\"operationId\":\"chat_update\",\"functionName\":\"ChatUpdate\",\"method\":\"POST\",\"path\":\"/chat.update\",\"summary\":\"\",\"tags\":[\"chat\"]},{\"uid\":\"POST /conversations.archive\",\"operationId\":\"conversations_archive\",\"functionName\":\"ConversationsArchive\",\"method\":\"POST\",\"path\":\"/conversations.archive\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.close\",\"operationId\":\"conversations_close\",\"functionName\":\"ConversationsClose\",\"method\":\"POST\",\"path\":\"/conversations.close\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.create\",\"operationId\":\"conversations_create\",\"functionName\":\"ConversationsCreate\",\"method\":\"POST\",\"path\":\"/conversations.create\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"GET /conversations.history\",\"operationId\":\"conversations_history\",\"functionName\":\"ConversationsHistory\",\"method\":\"GET\",\"path\":\"/conversations.history\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"GET /conversations.info\",\"operationId\":\"conversations_info\",\"functionName\":\"ConversationsInfo\",\"method\":\"GET\",\"path\":\"/conversations.info\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.invite\",\"operationId\":\"conversations_invite\",\"functionName\":\"ConversationsInvite\",\"method\":\"POST\",\"path\":\"/conversations.invite\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.join\",\"operationId\":\"conversations_join\",\"functionName\":\"ConversationsJoin\",\"method\":\"POST\",\"path\":\"/conversations.join\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.kick\",\"operationId\":\"conversations_kick\",\"functionName\":\"ConversationsKick\",\"method\":\"POST\",\"path\":\"/conversations.kick\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.leave\",\"operationId\":\"conversations_leave\",\"functionName\":\"ConversationsLeave\",\"method\":\"POST\",\"path\":\"/conversations.leave\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"GET /conversations.list\",\"operationId\":\"conversations_list\",\"functionName\":\"ConversationsList\",\"method\":\"GET\",\"path\":\"/conversations.list\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.mark\",\"operationId\":\"conversations_mark\",\"functionName\":\"ConversationsMark\",\"method\":\"POST\",\"path\":\"/conversations.mark\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"GET /conversations.members\",\"operationId\":\"conversations_members\",\"functionName\":\"ConversationsMembers\",\"method\":\"GET\",\"path\":\"/conversations.members\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.open\",\"operationId\":\"conversations_open\",\"functionName\":\"ConversationsOpen\",\"method\":\"POST\",\"path\":\"/conversations.open\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.rename\",\"operationId\":\"conversations_rename\",\"functionName\":\"ConversationsRename\",\"method\":\"POST\",\"path\":\"/conversations.rename\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"GET /conversations.replies\",\"operationId\":\"conversations_replies\",\"functionName\":\"ConversationsReplies\",\"method\":\"GET\",\"path\":\"/conversations.replies\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.setPurpose\",\"operationId\":\"conversations_setPurpose\",\"functionName\":\"ConversationsSetPurpose\",\"method\":\"POST\",\"path\":\"/conversations.setPurpose\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.setTopic\",\"operationId\":\"conversations_setTopic\",\"functionName\":\"ConversationsSetTopic\",\"method\":\"POST\",\"path\":\"/conversations.setTopic\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"POST /conversations.unarchive\",\"operationId\":\"conversations_unarchive\",\"functionName\":\"ConversationsUnarchive\",\"method\":\"POST\",\"path\":\"/conversations.unarchive\",\"summary\":\"\",\"tags\":[\"conversations\"]},{\"uid\":\"GET /dialog.open\",\"operationId\":\"dialog_open\",\"functionName\":\"DialogOpen\",\"method\":\"GET\",\"path\":\"/dialog.open\",\"summary\":\"\",\"tags\":[\"dialog\"]},{\"uid\":\"POST /dnd.endDnd\",\"operationId\":\"dnd_endDnd\",\"functionName\":\"DndEndDnd\",\"method\":\"POST\",\"path\":\"/dnd.endDnd\",\"summary\":\"\",\"tags\":[\"dnd\"]},{\"uid\":\"POST /dnd.endSnooze\",\"operationId\":\"dnd_endSnooze\",\"functionName\":\"DndEndSnooze\",\"method\":\"POST\",\"path\":\"/dnd.endSnooze\",\"summary\":\"\",\"tags\":[\"dnd\"]},{\"uid\":\"GET /dnd.info\",\"operationId\":\"dnd_info\",\"functionName\":\"DndInfo\",\"method\":\"GET\",\"path\":\"/dnd.info\",\"summary\":\"\",\"tags\":[\"dnd\"]},{\"uid\":\"POST /dnd.setSnooze\",\"operationId\":\"dnd_setSnooze\",\"functionName\":\"DndSetSnooze\",\"method\":\"POST\",\"path\":\"/dnd.setSnooze\",\"summary\":\"\",\"tags\":[\"dnd\"]},{\"uid\":\"GET /dnd.teamInfo\",\"operationId\":\"dnd_teamInfo\",\"functionName\":\"DndTeamInfo\",\"method\":\"GET\",\"path\":\"/dnd.teamInfo\",\"summary\":\"\",\"tags\":[\"dnd\"]},{\"uid\":\"GET /emoji.list\",\"operationId\":\"emoji_list\",\"functionName\":\"EmojiList\",\"method\":\"GET\",\"path\":\"/emoji.list\",\"summary\":\"\",\"tags\":[\"emoji\"]},{\"uid\":\"POST /files.comments.delete\",\"operationId\":\"files_comments_delete\",\"functionName\":\"FilesCommentsDelete\",\"method\":\"POST\",\"path\":\"/files.comments.delete\",\"summary\":\"\",\"tags\":[\"files.comments\",\"files\"]},{\"uid\":\"POST /files.delete\",\"operationId\":\"files_delete\",\"functionName\":\"FilesDelete\",\"method\":\"POST\",\"path\":\"/files.delete\",\"summary\":\"\",\"tags\":[\"files\"]},{\"uid\":\"GET /files.info\",\"operationId\":\"files_info\",\"functionName\":\"FilesInfo\",\"method\":\"GET\",\"path\":\"/files.info\",\"summary\":\"\",\"tags\":[\"files\"]},{\"uid\":\"GET /files.list\",\"operationId\":\"files_list\",\"functionName\":\"FilesList\",\"method\":\"GET\",\"path\":\"/files.list\",\"summary\":\"\",\"tags\":[\"files\"]},{\"uid\":\"POST /files.remote.add\",\"operationId\":\"files_remote_add\",\"functionName\":\"FilesRemoteAdd\",\"method\":\"POST\",\"path\":\"/files.remote.add\",\"summary\":\"\",\"tags\":[\"files.remote\",\"files\"]},{\"uid\":\"GET /files.remote.info\",\"operationId\":\"files_remote_info\",\"functionName\":\"FilesRemoteInfo\",\"method\":\"GET\",\"path\":\"/files.remote.info\",\"summary\":\"\",\"tags\":[\"files.remote\",\"files\"]},{\"uid\":\"GET /files.remote.list\",\"operationId\":\"files_remote_list\",\"functionName\":\"FilesRemoteList\",\"method\":\"GET\",\"path\":\"/files.remote.list\",\"summary\":\"\",\"tags\":[\"files.remote\",\"files\"]},{\"uid\":\"POST /files.remote.remove\",\"operationId\":\"files_remote_remove\",\"functionName\":\"FilesRemoteRemove\",\"method\":\"POST\",\"path\":\"/files.remote.remove\",\"summary\":\"\",\"tags\":[\"files.remote\",\"files\"]},{\"uid\":\"GET /files.remote.share\",\"operationId\":\"files_remote_share\",\"functionName\":\"FilesRemoteShare\",\"method\":\"GET\",\"path\":\"/files.remote.share\",\"summary\":\"\",\"tags\":[\"files.remote\",\"files\"]},{\"uid\":\"POST /files.remote.update\",\"operationId\":\"files_remote_update\",\"functionName\":\"FilesRemoteUpdate\",\"method\":\"POST\",\"path\":\"/files.remote.update\",\"summary\":\"\",\"tags\":[\"files.remote\",\"files\"]},{\"uid\":\"POST /files.revokePublicURL\",\"operationId\":\"files_revokePublicURL\",\"functionName\":\"FilesRevokePublicURL\",\"method\":\"POST\",\"path\":\"/files.revokePublicURL\",\"summary\":\"\",\"tags\":[\"files\"]},{\"uid\":\"POST /files.sharedPublicURL\",\"operationId\":\"files_sharedPublicURL\",\"functionName\":\"FilesSharedPublicURL\",\"method\":\"POST\",\"path\":\"/files.sharedPublicURL\",\"summary\":\"\",\"tags\":[\"files\"]},{\"uid\":\"POST /files.upload\",\"operationId\":\"files_upload\",\"functionName\":\"FilesUpload\",\"method\":\"POST\",\"path\":\"/files.upload\",\"summary\":\"\",\"tags\":[\"files\"]},{\"uid\":\"GET /migration.exchange\",\"operationId\":\"migration_exchange\",\"functionName\":\"MigrationExchange\",\"method\":\"GET\",\"path\":\"/migration.exchange\",\"summary\":\"\",\"tags\":[\"migration\"]},{\"uid\":\"GET /oauth.access\",\"operationId\":\"oauth_access\",\"functionName\":\"OauthAccess\",\"method\":\"GET\",\"path\":\"/oauth.access\",\"summary\":\"\",\"tags\":[\"oauth\"]},{\"uid\":\"GET /oauth.token\",\"operationId\":\"oauth_token\",\"functionName\":\"OauthToken\",\"method\":\"GET\",\"path\":\"/oauth.token\",\"summary\":\"\",\"tags\":[\"oauth\"]},{\"uid\":\"GET /oauth.v2.access\",\"operationId\":\"oauth_v2_access\",\"functionName\":\"OauthV2Access\",\"method\":\"GET\",\"path\":\"/oauth.v2.access\",\"summary\":\"\",\"tags\":[\"oauth.v2\",\"oauth\"]},{\"uid\":\"POST /pins.add\",\"operationId\":\"pins_add\",\"functionName\":\"PinsAdd\",\"method\":\"POST\",\"path\":\"/pins.add\",\"summary\":\"\",\"tags\":[\"pins\"]},{\"uid\":\"GET /pins.list\",\"operationId\":\"pins_list\",\"functionName\":\"PinsList\",\"method\":\"GET\",\"path\":\"/pins.list\",\"summary\":\"\",\"tags\":[\"pins\"]},{\"uid\":\"POST /pins.remove\",\"operationId\":\"pins_remove\",\"functionName\":\"PinsRemove\",\"method\":\"POST\",\"path\":\"/pins.remove\",\"summary\":\"\",\"tags\":[\"pins\"]},{\"uid\":\"POST /reactions.add\",\"operationId\":\"reactions_add\",\"functionName\":\"ReactionsAdd\",\"method\":\"POST\",\"path\":\"/reactions.add\",\"summary\":\"\",\"tags\":[\"reactions\"]},{\"uid\":\"GET /reactions.get\",\"operationId\":\"reactions_get\",\"functionName\":\"ReactionsGet\",\"method\":\"GET\",\"path\":\"/reactions.get\",\"summary\":\"\",\"tags\":[\"reactions\"]},{\"uid\":\"GET /reactions.list\",\"operationId\":\"reactions_list\",\"functionName\":\"ReactionsList\",\"method\":\"GET\",\"path\":\"/reactions.list\",\"summary\":\"\",\"tags\":[\"reactions\"]},{\"uid\":\"POST /reactions.remove\",\"operationId\":\"reactions_remove\",\"functionName\":\"ReactionsRemove\",\"method\":\"POST\",\"path\":\"/reactions.remove\",\"summary\":\"\",\"tags\":[\"reactions\"]},{\"uid\":\"POST /reminders.add\",\"operationId\":\"reminders_add\",\"functionName\":\"RemindersAdd\",\"method\":\"POST\",\"path\":\"/reminders.add\",\"summary\":\"\",\"tags\":[\"reminders\"]},{\"uid\":\"POST /reminders.complete\",\"operationId\":\"reminders_complete\",\"functionName\":\"RemindersComplete\",\"method\":\"POST\",\"path\":\"/reminders.complete\",\"summary\":\"\",\"tags\":[\"reminders\"]},{\"uid\":\"POST /reminders.delete\",\"operationId\":\"reminders_delete\",\"functionName\":\"RemindersDelete\",\"method\":\"POST\",\"path\":\"/reminders.delete\",\"summary\":\"\",\"tags\":[\"reminders\"]},{\"uid\":\"GET /reminders.info\",\"operationId\":\"reminders_info\",\"functionName\":\"RemindersInfo\",\"method\":\"GET\",\"path\":\"/reminders.info\",\"summary\":\"\",\"tags\":[\"reminders\"]},{\"uid\":\"GET /reminders.list\",\"operationId\":\"reminders_list\",\"functionName\":\"RemindersList\",\"method\":\"GET\",\"path\":\"/reminders.list\",\"summary\":\"\",\"tags\":[\"reminders\"]},{\"uid\":\"GET /rtm.connect\",\"operationId\":\"rtm_connect\",\"functionName\":\"RtmConnect\",\"method\":\"GET\",\"path\":\"/rtm.connect\",\"summary\":\"\",\"tags\":[\"rtm\"]},{\"uid\":\"GET /search.messages\",\"operationId\":\"search_messages\",\"functionName\":\"SearchMessages\",\"method\":\"GET\",\"path\":\"/search.messages\",\"summary\":\"\",\"tags\":[\"search\"]},{\"uid\":\"POST /stars.add\",\"operationId\":\"stars_add\",\"functionName\":\"StarsAdd\",\"method\":\"POST\",\"path\":\"/stars.add\",\"summary\":\"\",\"tags\":[\"stars\"]},{\"uid\":\"GET /stars.list\",\"operationId\":\"stars_list\",\"functionName\":\"StarsList\",\"method\":\"GET\",\"path\":\"/stars.list\",\"summary\":\"\",\"tags\":[\"stars\"]},{\"uid\":\"POST /stars.remove\",\"operationId\":\"stars_remove\",\"functionName\":\"StarsRemove\",\"method\":\"POST\",\"path\":\"/stars.remove\",\"summary\":\"\",\"tags\":[\"stars\"]},{\"uid\":\"GET /team.accessLogs\",\"operationId\":\"team_accessLogs\",\"functionName\":\"TeamAccessLogs\",\"method\":\"GET\",\"path\":\"/team.accessLogs\",\"summary\":\"\",\"tags\":[\"team\"]},{\"uid\":\"GET /team.billableInfo\",\"operationId\":\"team_billableInfo\",\"functionName\":\"TeamBillableInfo\",\"method\":\"GET\",\"path\":\"/team.billableInfo\",\"summary\":\"\",\"tags\":[\"team\"]},{\"uid\":\"GET /team.info\",\"operationId\":\"team_info\",\"functionName\":\"TeamInfo\",\"method\":\"GET\",\"path\":\"/team.info\",\"summary\":\"\",\"tags\":[\"team\"]},{\"uid\":\"GET /team.integrationLogs\",\"operationId\":\"team_integrationLogs\",\"functionName\":\"TeamIntegrationLogs\",\"method\":\"GET\",\"path\":\"/team.integrationLogs\",\"summary\":\"\",\"tags\":[\"team\"]},{\"uid\":\"GET /team.profile.get\",\"operationId\":\"team_profile_get\",\"functionName\":\"TeamProfileGet\",\"method\":\"GET\",\"path\":\"/team.profile.get\",\"summary\":\"\",\"tags\":[\"team.profile\",\"team\"]},{\"uid\":\"POST /usergroups.create\",\"operationId\":\"usergroups_create\",\"functionName\":\"UsergroupsCreate\",\"method\":\"POST\",\"path\":\"/usergroups.create\",\"summary\":\"\",\"tags\":[\"usergroups\"]},{\"uid\":\"POST /usergroups.disable\",\"operationId\":\"usergroups_disable\",\"functionName\":\"UsergroupsDisable\",\"method\":\"POST\",\"path\":\"/usergroups.disable\",\"summary\":\"\",\"tags\":[\"usergroups\"]},{\"uid\":\"POST /usergroups.enable\",\"operationId\":\"usergroups_enable\",\"functionName\":\"UsergroupsEnable\",\"method\":\"POST\",\"path\":\"/usergroups.enable\",\"summary\":\"\",\"tags\":[\"usergroups\"]},{\"uid\":\"GET /usergroups.list\",\"operationId\":\"usergroups_list\",\"functionName\":\"UsergroupsList\",\"method\":\"GET\",\"path\":\"/usergroups.list\",\"summary\":\"\",\"tags\":[\"usergroups\"]},{\"uid\":\"POST /usergroups.update\",\"operationId\":\"usergroups_update\",\"functionName\":\"UsergroupsUpdate\",\"method\":\"POST\",\"path\":\"/usergroups.update\",\"summary\":\"\",\"tags\":[\"usergroups\"]},{\"uid\":\"GET /usergroups.users.list\",\"operationId\":\"usergroups_users_list\",\"functionName\":\"UsergroupsUsersList\",\"method\":\"GET\",\"path\":\"/usergroups.users.list\",\"summary\":\"\",\"tags\":[\"usergroups.users\",\"usergroups\"]},{\"uid\":\"POST /usergroups.users.update\",\"operationId\":\"usergroups_users_update\",\"functionName\":\"UsergroupsUsersUpdate\",\"method\":\"POST\",\"path\":\"/usergroups.users.update\",\"summary\":\"\",\"tags\":[\"usergroups.users\",\"usergroups\"]},{\"uid\":\"GET /users.conversations\",\"operationId\":\"users_conversations\",\"functionName\":\"UsersConversations\",\"method\":\"GET\",\"path\":\"/users.conversations\",\"summary\":\"\",\"tags\":[\"users\"]},{\"uid\":\"POST /users.deletePhoto\",\"operationId\":\"users_deletePhoto\",\"functionName\":\"UsersDeletePhoto\",\"method\":\"POST\",\"path\":\"/users.deletePhoto\",\"summary\":\"\",\"tags\":[\"users\"]},{\"uid\":\"GET /users.getPresence\",\"operationId\":\"users_getPresence\",\"functionName\":\"UsersGetPresence\",\"method\":\"GET\",\"path\":\"/users.getPresence\",\"summary\":\"\",\"tags\":[\"users\"]},{\"uid\":\"GET /users.identity\",\"operationId\":\"users_identity\",\"functionName\":\"UsersIdentity\",\"method\":\"GET\",\"path\":\"/users.identity\",\"summary\":\"\",\"tags\":[\"users\"]},{\"uid\":\"GET /users.info\",\"operationId\":\"users_info\",\"functionName\":\"UsersInfo\",\"method\":\"GET\",\"path\":\"/users.info\",\"summary\":\"\",\"tags\":[\"users\"]},{\"uid\":\"GET /users.list\",\"operationId\":\"users_list\",\"functionName\":\"UsersList\",\"method\":\"GET\",\"path\":\"/users.list\",\"summary\":\"\",\"tags\":[\"users\"]},{\"uid\":\"GET /users.lookupByEmail\",\"operationId\":\"users_lookupByEmail\",\"functionName\":\"UsersLookupByEmail\",\"method\":\"GET\",\"path\":\"/users.lookupByEmail\",\"summary\":\"\",\"tags\":[\"users\"]},{\"uid\":\"GET /users.profile.get\",\"operationId\":\"users_profile_get\",\"functionName\":\"UsersProfileGet\",\"method\":\"GET\",\"path\":\"/users.profile.get\",\"summary\":\"\",\"tags\":[\"users.profile\",\"users\"]},{\"uid\":\"POST /users.profile.set\",\"operationId\":\"users_profile_set\",\"functionName\":\"UsersProfileSet\",\"method\":\"POST\",\"path\":\"/users.profile.set\",\"summary\":\"\",\"tags\":[\"users.profile\",\"users\"]},{\"uid\":\"POST /users.setActive\",\"operationId\":\"users_setActive\",\"functionName\":\"UsersSetActive\",\"method\":\"POST\",\"path\":\"/users.setActive\",\"summary\":\"\",\"tags\":[\"users\"]},{\"uid\":\"POST /users.setPhoto\",\"operationId\":\"users_setPhoto\",\"functionName\":\"UsersSetPhoto\",\"method\":\"POST\",\"path\":\"/users.setPhoto\",\"summary\":\"\",\"tags\":[\"users\"]},{\"uid\":\"POST /users.setPresence\",\"operationId\":\"users_setPresence\",\"functionName\":\"UsersSetPresence\",\"method\":\"POST\",\"path\":\"/users.setPresence\",\"summary\":\"\",\"tags\":[\"users\"]},{\"uid\":\"GET /views.open\",\"operationId\":\"views_open\",\"functionName\":\"ViewsOpen\",\"method\":\"GET\",\"path\":\"/views.open\",\"summary\":\"\",\"tags\":[\"views\"]},{\"uid\":\"GET /views.publish\",\"operationId\":\"views_publish\",\"functionName\":\"ViewsPublish\",\"method\":\"GET\",\"path\":\"/views.publish\",\"summary\":\"\",\"tags\":[\"views\"]},{\"uid\":\"GET /views.push\",\"operationId\":\"views_push\",\"functionName\":\"ViewsPush\",\"method\":\"GET\",\"path\":\"/views.push\",\"summary\":\"\",\"tags\":[\"views\"]},{\"uid\":\"GET /views.update\",\"operationId\":\"views_update\",\"functionName\":\"ViewsUpdate\",\"method\":\"GET\",\"path\":\"/views.update\",\"summary\":\"\",\"tags\":[\"views\"]},{\"uid\":\"GET /workflows.stepCompleted\",\"operationId\":\"workflows_stepCompleted\",\"functionName\":\"WorkflowsStepCompleted\",\"method\":\"GET\",\"path\":\"/workflows.stepCompleted\",\"summary\":\"\",\"tags\":[\"workflows\"]},{\"uid\":\"GET /workflows.stepFailed\",\"operationId\":\"workflows_stepFailed\",\"functionName\":\"WorkflowsStepFailed\",\"method\":\"GET\",\"path\":\"/workflows.stepFailed\",\"summary\":\"\",\"tags\":[\"workflows\"]},{\"uid\":\"GET /workflows.updateStep\",\"operationId\":\"workflows_updateStep\",\"functionName\":\"WorkflowsUpdateStep\",\"method\":\"GET\",\"path\":\"/workflows.updateStep\",\"summary\":\"\",\"tags\":[\"workflows\"]}]") as readonly SlackWebApiOperation[];

// Hardened literal operation keys for generated SDK typing.
export const SLACK_WEB_API_OPERATION_IDS = [
  "admin_apps_approve",
  "admin_apps_approved_list",
  "admin_apps_requests_list",
  "admin_apps_restrict",
  "admin_apps_restricted_list",
  "admin_conversations_archive",
  "admin_conversations_convertToPrivate",
  "admin_conversations_create",
  "admin_conversations_delete",
  "admin_conversations_disconnectShared",
  "admin_conversations_ekm_listOriginalConnectedChannelInfo",
  "admin_conversations_getConversationPrefs",
  "admin_conversations_getTeams",
  "admin_conversations_invite",
  "admin_conversations_rename",
  "admin_conversations_restrictAccess_addGroup",
  "admin_conversations_restrictAccess_listGroups",
  "admin_conversations_restrictAccess_removeGroup",
  "admin_conversations_search",
  "admin_conversations_setConversationPrefs",
  "admin_conversations_setTeams",
  "admin_conversations_unarchive",
  "admin_emoji_add",
  "admin_emoji_addAlias",
  "admin_emoji_list",
  "admin_emoji_remove",
  "admin_emoji_rename",
  "admin_inviteRequests_approve",
  "admin_inviteRequests_approved_list",
  "admin_inviteRequests_denied_list",
  "admin_inviteRequests_deny",
  "admin_inviteRequests_list",
  "admin_teams_admins_list",
  "admin_teams_create",
  "admin_teams_list",
  "admin_teams_owners_list",
  "admin_teams_settings_info",
  "admin_teams_settings_setDefaultChannels",
  "admin_teams_settings_setDescription",
  "admin_teams_settings_setDiscoverability",
  "admin_teams_settings_setIcon",
  "admin_teams_settings_setName",
  "admin_usergroups_addChannels",
  "admin_usergroups_addTeams",
  "admin_usergroups_listChannels",
  "admin_usergroups_removeChannels",
  "admin_users_assign",
  "admin_users_invite",
  "admin_users_list",
  "admin_users_remove",
  "admin_users_session_invalidate",
  "admin_users_session_reset",
  "admin_users_setAdmin",
  "admin_users_setExpiration",
  "admin_users_setOwner",
  "admin_users_setRegular",
  "api_test",
  "apps_event_authorizations_list",
  "apps_permissions_info",
  "apps_permissions_request",
  "apps_permissions_resources_list",
  "apps_permissions_scopes_list",
  "apps_permissions_users_list",
  "apps_permissions_users_request",
  "apps_uninstall",
  "auth_revoke",
  "auth_test",
  "bots_info",
  "calls_add",
  "calls_end",
  "calls_info",
  "calls_participants_add",
  "calls_participants_remove",
  "calls_update",
  "chat_delete",
  "chat_deleteScheduledMessage",
  "chat_getPermalink",
  "chat_meMessage",
  "chat_postEphemeral",
  "chat_postMessage",
  "chat_scheduleMessage",
  "chat_scheduledMessages_list",
  "chat_unfurl",
  "chat_update",
  "conversations_archive",
  "conversations_close",
  "conversations_create",
  "conversations_history",
  "conversations_info",
  "conversations_invite",
  "conversations_join",
  "conversations_kick",
  "conversations_leave",
  "conversations_list",
  "conversations_mark",
  "conversations_members",
  "conversations_open",
  "conversations_rename",
  "conversations_replies",
  "conversations_setPurpose",
  "conversations_setTopic",
  "conversations_unarchive",
  "dialog_open",
  "dnd_endDnd",
  "dnd_endSnooze",
  "dnd_info",
  "dnd_setSnooze",
  "dnd_teamInfo",
  "emoji_list",
  "files_comments_delete",
  "files_delete",
  "files_info",
  "files_list",
  "files_remote_add",
  "files_remote_info",
  "files_remote_list",
  "files_remote_remove",
  "files_remote_share",
  "files_remote_update",
  "files_revokePublicURL",
  "files_sharedPublicURL",
  "files_upload",
  "migration_exchange",
  "oauth_access",
  "oauth_token",
  "oauth_v2_access",
  "pins_add",
  "pins_list",
  "pins_remove",
  "reactions_add",
  "reactions_get",
  "reactions_list",
  "reactions_remove",
  "reminders_add",
  "reminders_complete",
  "reminders_delete",
  "reminders_info",
  "reminders_list",
  "rtm_connect",
  "search_messages",
  "stars_add",
  "stars_list",
  "stars_remove",
  "team_accessLogs",
  "team_billableInfo",
  "team_info",
  "team_integrationLogs",
  "team_profile_get",
  "usergroups_create",
  "usergroups_disable",
  "usergroups_enable",
  "usergroups_list",
  "usergroups_update",
  "usergroups_users_list",
  "usergroups_users_update",
  "users_conversations",
  "users_deletePhoto",
  "users_getPresence",
  "users_identity",
  "users_info",
  "users_list",
  "users_lookupByEmail",
  "users_profile_get",
  "users_profile_set",
  "users_setActive",
  "users_setPhoto",
  "users_setPresence",
  "views_open",
  "views_publish",
  "views_push",
  "views_update",
  "workflows_stepCompleted",
  "workflows_stepFailed",
  "workflows_updateStep"
] as const;
export const SLACK_WEB_API_OPERATION_OPERATION_IDS = [
  "admin_apps_approve",
  "admin_apps_approved_list",
  "admin_apps_requests_list",
  "admin_apps_restrict",
  "admin_apps_restricted_list",
  "admin_conversations_archive",
  "admin_conversations_convertToPrivate",
  "admin_conversations_create",
  "admin_conversations_delete",
  "admin_conversations_disconnectShared",
  "admin_conversations_ekm_listOriginalConnectedChannelInfo",
  "admin_conversations_getConversationPrefs",
  "admin_conversations_getTeams",
  "admin_conversations_invite",
  "admin_conversations_rename",
  "admin_conversations_restrictAccess_addGroup",
  "admin_conversations_restrictAccess_listGroups",
  "admin_conversations_restrictAccess_removeGroup",
  "admin_conversations_search",
  "admin_conversations_setConversationPrefs",
  "admin_conversations_setTeams",
  "admin_conversations_unarchive",
  "admin_emoji_add",
  "admin_emoji_addAlias",
  "admin_emoji_list",
  "admin_emoji_remove",
  "admin_emoji_rename",
  "admin_inviteRequests_approve",
  "admin_inviteRequests_approved_list",
  "admin_inviteRequests_denied_list",
  "admin_inviteRequests_deny",
  "admin_inviteRequests_list",
  "admin_teams_admins_list",
  "admin_teams_create",
  "admin_teams_list",
  "admin_teams_owners_list",
  "admin_teams_settings_info",
  "admin_teams_settings_setDefaultChannels",
  "admin_teams_settings_setDescription",
  "admin_teams_settings_setDiscoverability",
  "admin_teams_settings_setIcon",
  "admin_teams_settings_setName",
  "admin_usergroups_addChannels",
  "admin_usergroups_addTeams",
  "admin_usergroups_listChannels",
  "admin_usergroups_removeChannels",
  "admin_users_assign",
  "admin_users_invite",
  "admin_users_list",
  "admin_users_remove",
  "admin_users_session_invalidate",
  "admin_users_session_reset",
  "admin_users_setAdmin",
  "admin_users_setExpiration",
  "admin_users_setOwner",
  "admin_users_setRegular",
  "api_test",
  "apps_event_authorizations_list",
  "apps_permissions_info",
  "apps_permissions_request",
  "apps_permissions_resources_list",
  "apps_permissions_scopes_list",
  "apps_permissions_users_list",
  "apps_permissions_users_request",
  "apps_uninstall",
  "auth_revoke",
  "auth_test",
  "bots_info",
  "calls_add",
  "calls_end",
  "calls_info",
  "calls_participants_add",
  "calls_participants_remove",
  "calls_update",
  "chat_delete",
  "chat_deleteScheduledMessage",
  "chat_getPermalink",
  "chat_meMessage",
  "chat_postEphemeral",
  "chat_postMessage",
  "chat_scheduleMessage",
  "chat_scheduledMessages_list",
  "chat_unfurl",
  "chat_update",
  "conversations_archive",
  "conversations_close",
  "conversations_create",
  "conversations_history",
  "conversations_info",
  "conversations_invite",
  "conversations_join",
  "conversations_kick",
  "conversations_leave",
  "conversations_list",
  "conversations_mark",
  "conversations_members",
  "conversations_open",
  "conversations_rename",
  "conversations_replies",
  "conversations_setPurpose",
  "conversations_setTopic",
  "conversations_unarchive",
  "dialog_open",
  "dnd_endDnd",
  "dnd_endSnooze",
  "dnd_info",
  "dnd_setSnooze",
  "dnd_teamInfo",
  "emoji_list",
  "files_comments_delete",
  "files_delete",
  "files_info",
  "files_list",
  "files_remote_add",
  "files_remote_info",
  "files_remote_list",
  "files_remote_remove",
  "files_remote_share",
  "files_remote_update",
  "files_revokePublicURL",
  "files_sharedPublicURL",
  "files_upload",
  "migration_exchange",
  "oauth_access",
  "oauth_token",
  "oauth_v2_access",
  "pins_add",
  "pins_list",
  "pins_remove",
  "reactions_add",
  "reactions_get",
  "reactions_list",
  "reactions_remove",
  "reminders_add",
  "reminders_complete",
  "reminders_delete",
  "reminders_info",
  "reminders_list",
  "rtm_connect",
  "search_messages",
  "stars_add",
  "stars_list",
  "stars_remove",
  "team_accessLogs",
  "team_billableInfo",
  "team_info",
  "team_integrationLogs",
  "team_profile_get",
  "usergroups_create",
  "usergroups_disable",
  "usergroups_enable",
  "usergroups_list",
  "usergroups_update",
  "usergroups_users_list",
  "usergroups_users_update",
  "users_conversations",
  "users_deletePhoto",
  "users_getPresence",
  "users_identity",
  "users_info",
  "users_list",
  "users_lookupByEmail",
  "users_profile_get",
  "users_profile_set",
  "users_setActive",
  "users_setPhoto",
  "users_setPresence",
  "views_open",
  "views_publish",
  "views_push",
  "views_update",
  "workflows_stepCompleted",
  "workflows_stepFailed",
  "workflows_updateStep"
] as const;
export const SLACK_WEB_API_OPERATION_UIDS = [
  "POST /admin.apps.approve",
  "GET /admin.apps.approved.list",
  "GET /admin.apps.requests.list",
  "POST /admin.apps.restrict",
  "GET /admin.apps.restricted.list",
  "POST /admin.conversations.archive",
  "POST /admin.conversations.convertToPrivate",
  "POST /admin.conversations.create",
  "POST /admin.conversations.delete",
  "POST /admin.conversations.disconnectShared",
  "GET /admin.conversations.ekm.listOriginalConnectedChannelInfo",
  "GET /admin.conversations.getConversationPrefs",
  "GET /admin.conversations.getTeams",
  "POST /admin.conversations.invite",
  "POST /admin.conversations.rename",
  "POST /admin.conversations.restrictAccess.addGroup",
  "GET /admin.conversations.restrictAccess.listGroups",
  "POST /admin.conversations.restrictAccess.removeGroup",
  "GET /admin.conversations.search",
  "POST /admin.conversations.setConversationPrefs",
  "POST /admin.conversations.setTeams",
  "POST /admin.conversations.unarchive",
  "POST /admin.emoji.add",
  "POST /admin.emoji.addAlias",
  "GET /admin.emoji.list",
  "POST /admin.emoji.remove",
  "POST /admin.emoji.rename",
  "POST /admin.inviteRequests.approve",
  "GET /admin.inviteRequests.approved.list",
  "GET /admin.inviteRequests.denied.list",
  "POST /admin.inviteRequests.deny",
  "GET /admin.inviteRequests.list",
  "GET /admin.teams.admins.list",
  "POST /admin.teams.create",
  "GET /admin.teams.list",
  "GET /admin.teams.owners.list",
  "GET /admin.teams.settings.info",
  "POST /admin.teams.settings.setDefaultChannels",
  "POST /admin.teams.settings.setDescription",
  "POST /admin.teams.settings.setDiscoverability",
  "POST /admin.teams.settings.setIcon",
  "POST /admin.teams.settings.setName",
  "POST /admin.usergroups.addChannels",
  "POST /admin.usergroups.addTeams",
  "GET /admin.usergroups.listChannels",
  "POST /admin.usergroups.removeChannels",
  "POST /admin.users.assign",
  "POST /admin.users.invite",
  "GET /admin.users.list",
  "POST /admin.users.remove",
  "POST /admin.users.session.invalidate",
  "POST /admin.users.session.reset",
  "POST /admin.users.setAdmin",
  "POST /admin.users.setExpiration",
  "POST /admin.users.setOwner",
  "POST /admin.users.setRegular",
  "GET /api.test",
  "GET /apps.event.authorizations.list",
  "GET /apps.permissions.info",
  "GET /apps.permissions.request",
  "GET /apps.permissions.resources.list",
  "GET /apps.permissions.scopes.list",
  "GET /apps.permissions.users.list",
  "GET /apps.permissions.users.request",
  "GET /apps.uninstall",
  "GET /auth.revoke",
  "GET /auth.test",
  "GET /bots.info",
  "POST /calls.add",
  "POST /calls.end",
  "GET /calls.info",
  "POST /calls.participants.add",
  "POST /calls.participants.remove",
  "POST /calls.update",
  "POST /chat.delete",
  "POST /chat.deleteScheduledMessage",
  "GET /chat.getPermalink",
  "POST /chat.meMessage",
  "POST /chat.postEphemeral",
  "POST /chat.postMessage",
  "POST /chat.scheduleMessage",
  "GET /chat.scheduledMessages.list",
  "POST /chat.unfurl",
  "POST /chat.update",
  "POST /conversations.archive",
  "POST /conversations.close",
  "POST /conversations.create",
  "GET /conversations.history",
  "GET /conversations.info",
  "POST /conversations.invite",
  "POST /conversations.join",
  "POST /conversations.kick",
  "POST /conversations.leave",
  "GET /conversations.list",
  "POST /conversations.mark",
  "GET /conversations.members",
  "POST /conversations.open",
  "POST /conversations.rename",
  "GET /conversations.replies",
  "POST /conversations.setPurpose",
  "POST /conversations.setTopic",
  "POST /conversations.unarchive",
  "GET /dialog.open",
  "POST /dnd.endDnd",
  "POST /dnd.endSnooze",
  "GET /dnd.info",
  "POST /dnd.setSnooze",
  "GET /dnd.teamInfo",
  "GET /emoji.list",
  "POST /files.comments.delete",
  "POST /files.delete",
  "GET /files.info",
  "GET /files.list",
  "POST /files.remote.add",
  "GET /files.remote.info",
  "GET /files.remote.list",
  "POST /files.remote.remove",
  "GET /files.remote.share",
  "POST /files.remote.update",
  "POST /files.revokePublicURL",
  "POST /files.sharedPublicURL",
  "POST /files.upload",
  "GET /migration.exchange",
  "GET /oauth.access",
  "GET /oauth.token",
  "GET /oauth.v2.access",
  "POST /pins.add",
  "GET /pins.list",
  "POST /pins.remove",
  "POST /reactions.add",
  "GET /reactions.get",
  "GET /reactions.list",
  "POST /reactions.remove",
  "POST /reminders.add",
  "POST /reminders.complete",
  "POST /reminders.delete",
  "GET /reminders.info",
  "GET /reminders.list",
  "GET /rtm.connect",
  "GET /search.messages",
  "POST /stars.add",
  "GET /stars.list",
  "POST /stars.remove",
  "GET /team.accessLogs",
  "GET /team.billableInfo",
  "GET /team.info",
  "GET /team.integrationLogs",
  "GET /team.profile.get",
  "POST /usergroups.create",
  "POST /usergroups.disable",
  "POST /usergroups.enable",
  "GET /usergroups.list",
  "POST /usergroups.update",
  "GET /usergroups.users.list",
  "POST /usergroups.users.update",
  "GET /users.conversations",
  "POST /users.deletePhoto",
  "GET /users.getPresence",
  "GET /users.identity",
  "GET /users.info",
  "GET /users.list",
  "GET /users.lookupByEmail",
  "GET /users.profile.get",
  "POST /users.profile.set",
  "POST /users.setActive",
  "POST /users.setPhoto",
  "POST /users.setPresence",
  "GET /views.open",
  "GET /views.publish",
  "GET /views.push",
  "GET /views.update",
  "GET /workflows.stepCompleted",
  "GET /workflows.stepFailed",
  "GET /workflows.updateStep"
] as const;
// End hardened literal operation keys.
export const SLACK_WEB_API_OPERATION_BY_UID = new Map(SLACK_WEB_API_OPERATIONS.map((operation) => [operation.uid, operation]));
export const SLACK_WEB_API_OPERATION_BY_ID = new Map<string, SlackWebApiOperation>();
for (const operation of SLACK_WEB_API_OPERATIONS) {
  if (!SLACK_WEB_API_OPERATION_BY_ID.has(operation.operationId)) {
    SLACK_WEB_API_OPERATION_BY_ID.set(operation.operationId, operation);
  }
}

export type SlackWebApiOperationUid = typeof SLACK_WEB_API_OPERATION_UIDS[number];
