import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const messengerSocialOperationAliases = [
  "messenger.webhook.parse",
  "messenger.message.send",
  "messenger.senderAction.send",
  "messenger.attachment.upload",
  "messenger.conversations.list",
  "messenger.conversationMessages.list",
  "messenger.page.read",
  "messenger.webhook-signature",
] as const;

export const messengerSocialProviderClientSupportSlice = {
  implementationStrategy: "no-official-sdk-rest-adapter",
  sdkDecision: "No viable official Messenger Platform server-side JavaScript SDK was verified for this support workflow slice. The Meta Business SDK is Business/Marketing/Pages oriented, so this package ships a built-in Graph API REST adapter and still accepts a host-provided Messenger/Meta provider client override.",
  verifiedAt: "2026-06-25",
  allowedOperations: [
    {
      id: "parseMessengerWebhook",
      alias: "messenger.webhook.parse",
      target: "package.webhooks.parseMessengerWebhook",
      source: "local-webhook-parser",
      checksum: "not-applicable-local-helper",
    },
    {
      id: "sendMessage",
      alias: "messenger.message.send",
      target: "providerRestAdapter.sendMessage",
      source: "provider-rest-adapter",
      checksum: "not-applicable-rest-adapter",
    },
    {
      id: "sendSenderAction",
      alias: "messenger.senderAction.send",
      target: "providerRestAdapter.sendMessage",
      source: "provider-rest-adapter",
      checksum: "not-applicable-rest-adapter",
    },
    {
      id: "uploadAttachment",
      alias: "messenger.attachment.upload",
      target: "providerRestAdapter.uploadAttachment",
      source: "provider-rest-adapter",
      checksum: "not-applicable-rest-adapter",
    },
    {
      id: "listConversations",
      alias: "messenger.conversations.list",
      target: "providerRestAdapter.listConversations",
      source: "provider-rest-adapter",
      checksum: "not-applicable-rest-adapter",
    },
    {
      id: "getConversationMessages",
      alias: "messenger.conversationMessages.list",
      target: "providerRestAdapter.getConversationMessages",
      source: "provider-rest-adapter",
      checksum: "not-applicable-rest-adapter",
    },
    {
      id: "getPage",
      alias: "messenger.page.read",
      target: "providerRestAdapter.getPage",
      source: "provider-rest-adapter",
      checksum: "not-applicable-rest-adapter",
    },
    {
      id: "validateMessengerWebhookSignature",
      alias: "messenger.webhook-signature",
      target: "package.webhooks.validateMessengerWebhookSignature",
      source: "local-signature-helper",
      checksum: "not-applicable-local-helper",
    },
  ],
} as const;

export const messengerSocialSupportSlice = messengerSocialProviderClientSupportSlice;

export const messengerSocialProviderManifest = defineProviderPackage({
  id: "social.messenger",
  name: "Facebook Messenger",
  packageName: "@cognidesk/integration-social-messenger",
  provider: "messenger",
  category: "social",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is typed for selected Messenger Platform support workflows: Page messages send, text payloads, sender actions, attachment payload/upload helpers, conversation/message reads, Page readiness, webhook challenge handling, and X-Hub-Signature-256 validation.",
      "Runtime provider operations use the built-in Graph API REST adapter when credentials are configured; hosts may inject a Messenger/Meta provider client override.",
      "Meta's current Messenger routing surface is Conversation Routing; deprecated Handover Protocol thread-control helpers are not advertised as a current handoff capability by this package.",
      "This is not full Messenger Platform coverage; Messenger profile, persistent menu, personas, discovery and engagement tools, account linking, NLP, analytics, marketing messages, conversation routing configuration, and broader Page/Graph administration remain outside this adapter.",
    ],
    evidence: [
      { label: "Messenger webhooks", url: "https://developers.facebook.com/documentation/business-messaging/messenger-platform/webhooks" },
      { label: "Page subscribed apps", url: "https://developers.facebook.com/docs/graph-api/reference/page/subscribed_apps/" },
      { label: "Messenger Send API", url: "https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags" },
      { label: "Messenger sender actions", url: "https://developers.facebook.com/docs/messenger-platform/send-messages/sender-actions" },
      { label: "Messenger attachment upload", url: "https://developers.facebook.com/docs/messenger-platform/reference/attachment-upload-api" },
      { label: "Messenger conversation routing", url: "https://developers.facebook.com/documentation/business-messaging/messenger-platform/conversation-routing" },
    ],
  },
  credentialRequirements: [
    {
      id: "messenger-provider-client",
      label: "Messenger/Meta provider client override",
      description: "Optional SDK-user-owned provider client implementing MessengerSocialProviderClient for Messenger Platform and selected Meta Graph operations.",
      required: false,
      metadata: {
        interface: "MessengerSocialProviderClient",
        importPolicy: "provider-client-override-supported",
        defaultClientPolicy: "provider-rest-adapter-when-configured",
      },
    },
    {
      id: "messenger-page-access-token",
      label: "Messenger Page access token",
      description: "Server-side Meta Page access token used by the built-in Graph API adapter or an injected Messenger/Meta provider client.",
      scopes: ["pages_messaging", "pages_show_list", "pages_read_engagement", "pages_manage_metadata"],
      required: true,
      metadata: { scopeKind: "provider-permission-labels" },
    },
    {
      id: "messenger-page-id",
      label: "Facebook Page ID",
      description: "Page ID that owns the Messenger inbox and conversation graph.",
      required: true,
    },
    {
      id: "messenger-app-secret",
      label: "Meta app secret",
      description: "Server-side app secret used to validate X-Hub-Signature-256 webhook deliveries.",
      required: true,
    },
    {
      id: "messenger-webhook-verify-token",
      label: "Webhook verify token",
      description: "SDK-user-owned token checked during Meta webhook endpoint verification.",
      required: false,
    },
    {
      id: "messenger-page-webhook-subscription",
      label: "Messenger Page messages webhook subscription",
      description: "SDK-user-confirmed Page subscribed_apps configuration for Messenger messages webhooks.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Messenger webhooks",
      description: "Validates and parses Messenger Platform webhook payloads after the SDK user's Page is subscribed to the messages webhook.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "messengerWebhook", label: "Messenger Webhook" },
        { kind: "messengerMessage", label: "Messenger Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Messenger messages",
      description: "Sends Messenger Platform messages inside Meta's 24-hour standard messaging window or with SDK-user-approved MESSAGE_TAG non-promotional policy where permitted.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "messengerMessage", label: "Messenger Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Build Messenger payloads",
      description: "Builds text, attachment, quick reply, sender action, and tag payloads for SDK-user approval workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "messengerDraft", label: "Messenger Draft" }],
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Messenger conversations",
      description: "Reads Messenger conversation and message metadata through the configured Graph API adapter or provider client with SDK-user-governed access and retention.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "messengerConversation", label: "Messenger Conversation" },
        { kind: "messengerMessage", label: "Messenger Message" },
        { kind: "messengerPage", label: "Messenger Page" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Messenger conversations",
      description: "Reads Messenger conversation messages and metadata through the configured Graph API adapter or provider client.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "messengerConversation", label: "Messenger Conversation" },
        { kind: "messengerMessage", label: "Messenger Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "List Messenger conversations",
      description: "Lists Messenger Page conversations through the configured Graph API adapter or provider client with SDK-user-supplied filters such as user ID, fields, limits, and cursors.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "messengerConversation", label: "Messenger Conversation" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Use Messenger attachments",
      description: "Sends attachment payloads and exposes inbound attachment metadata under SDK-user media policy.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "messengerAttachment", label: "Messenger Attachment" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "social.webhook-signature",
      label: "Validate Meta webhook signatures",
      description: "Validates X-Hub-Signature-256 webhook signatures with the SDK user's Meta app secret.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "messengerSignedWebhook", label: "Messenger Signed Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "messenger.webhook.parse",
      providerOperation: "parseMessengerWebhook",
      capability: "receive",
      providerObject: "messengerWebhook",
      label: "Parse Messenger webhook",
      description: "Validate and parse an inbound Messenger webhook request.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "messenger.message.send",
      providerOperation: "sendMessage",
      capability: "send",
      providerObject: "messengerMessage",
      label: "Send Messenger message",
      description: "Send a Messenger Platform message through the configured Page.",
      audiences: ["customer-facing"],
      requiresCredential: true,
      requiresApproval: true,
      externallyVisible: true,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "messenger.senderAction.send",
      providerOperation: "sendSenderAction",
      capability: "send",
      providerObject: "messengerConversation",
      label: "Send Messenger sender action",
      description: "Send Messenger sender actions such as typing indicators or mark-seen.",
      audiences: ["customer-facing"],
      requiresCredential: true,
      externallyVisible: true,
      sideEffect: true,
      extension: true,
    },
    {
      alias: "messenger.attachment.upload",
      providerOperation: "uploadAttachment",
      capability: "media",
      providerObject: "messengerAttachment",
      label: "Upload Messenger attachment",
      description: "Upload reusable attachment payloads for Messenger sends.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      requiresApproval: true,
      externallyVisible: true,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "messenger.conversations.list",
      providerOperation: "listConversations",
      capability: "search-provider-object",
      providerObject: "messengerConversation",
      label: "List Messenger conversations",
      description: "List Messenger Page conversations with SDK-user-supplied filters.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "messenger.conversationMessages.list",
      providerOperation: "getConversationMessages",
      capability: "read-provider-object",
      providerObject: "messengerMessage",
      label: "Read Messenger conversation messages",
      description: "Read messages for a Messenger conversation.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "messenger.page.read",
      providerOperation: "getPage",
      capability: "read-provider-object",
      providerObject: "messengerPage",
      label: "Read Messenger Page",
      description: "Read configured Facebook Page metadata for readiness diagnostics.",
      audiences: ["internal-support", "mixed"],
      requiresCredential: true,
      extension: true,
    },
    {
      alias: "messenger.webhook-signature",
      providerOperation: "validateMessengerWebhookSignature",
      capability: "social.webhook-signature",
      providerObject: "messengerSignedWebhook",
      label: "Validate Messenger webhook signature",
      description: "Validate Meta X-Hub-Signature-256 for Messenger webhook delivery.",
      audiences: ["internal-support"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Messenger PSIDs, profile names, message text, attachments, conversation metadata, and webhook payloads can contain customer data.",
    "Meta Page access tokens, app secrets, and webhook verify tokens stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "Available operations depend on the SDK user's Meta app mode, Page connection, permissions, Page access token, webhook subscriptions, and messaging window rules.",
    "Meta no longer supports Handover Protocol as the normal Messenger routing model; SDK users should configure Conversation Routing outside this adapter, and the thread-control client methods are deprecated provider escape hatches only.",
    "Consent, outbound-contact policy, human escalation, attachment retention, redaction, and deletion behavior remain SDK-user configuration.",
    "This package provides Messenger payload/webhook helpers and does not choose default automation, promotional messaging, retry, HTTP transport, or rate-limit policy.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    implementation: messengerSocialSupportSlice,
    manifestOnlySafe: true,
    providerClient: {
      package: "built-in-or-host-provided",
      interface: "MessengerSocialProviderClient",
      importPolicy: "provider-client-override-supported",
      defaultClientPolicy: "provider-rest-adapter-when-configured",
    },
    channelCoverage: {
      messages: "provider-rest-adapter-send",
      senderActions: "provider-rest-adapter-send",
      attachments: "provider-rest-adapter-upload-send",
      conversations: "provider-rest-adapter-list-read",
      pageReadiness: "provider-rest-adapter-read",
      webhooks: "typed-challenge-verify-parse",
      handoverProtocolThreadControl: "provider-supported-deprecated-typed-thread-control",
      conversationRouting: "provider-supported-not-typed",
    },
    docs: "https://developers.facebook.com/docs/messenger-platform",
    apiCoverage: {
      checkedAt: "2026-06-25",
      operationCatalog: "docs/provider-coverage/messenger-platform-graph-selected-api-2026-06-18.operations.json",
      generatedFromOfficialSpec: false,
      machineReadableSpecStatus: "No official public complete Messenger Platform/Graph OpenAPI spec was found in facebook/openapi during this audit.",
      selectedOperationCount: 8,
      implementedOperationCount: 8,
      fullProviderApi: false,
      fullMetaGraphCoverage: false,
    },
  },
});
