import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const messengerSocialProviderManifest = defineProviderPackage({
  id: "social.messenger",
  name: "Facebook Messenger",
  packageName: "@cognidesk/integration-social-messenger",
  provider: "messenger",
  category: "social",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is typed for selected Messenger Platform support workflows: Page messages send, text payloads, sender actions, attachment payload/upload helpers, conversation/message reads, Page readiness, webhook challenge handling, and X-Hub-Signature-256 validation.",
      "Meta's current Messenger routing surface is Conversation Routing; legacy Handover Protocol thread-control helpers are not advertised as a current handoff capability by this package.",
      "This is not full Messenger Platform coverage; Messenger profile, persistent menu, personas, discovery and engagement tools, account linking, NLP, analytics, marketing messages, conversation routing configuration, and broader Page/Graph administration remain outside this adapter.",
    ],
    evidence: [
      { label: "Messenger webhooks", url: "https://developers.facebook.com/documentation/business-messaging/messenger-platform/webhooks" },
      { label: "Page subscribed apps", url: "https://developers.facebook.com/docs/graph-api/reference/page/subscribed_apps/" },
      { label: "Messenger Send API", url: "https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags" },
      { label: "Messenger sender actions", url: "https://developers.facebook.com/docs/messenger-platform/send-messages/sender-actions" },
      { label: "Messenger attachment upload", url: "https://developers.facebook.com/docs/messenger-platform/reference/attachment-upload-api" },
      { label: "Messenger conversation routing", url: "https://developers.facebook.com/documentation/business-messaging/messenger-platform/conversation-routing" },
    ],
  },
  credentialRequirements: [
    {
      id: "messenger-page-access-token",
      label: "Messenger Page access token",
      description: "Server-side Meta Page access token used for Messenger Platform Send and Conversations APIs.",
      scopes: ["pages_messaging", "pages_show_list", "pages_read_engagement", "pages_manage_metadata"],
      required: true,
      metadata: { scopeKind: "provider-permission-labels" },
    },
    {
      id: "messenger-page-id",
      label: "Facebook Page ID",
      description: "Page ID that owns the Messenger inbox and conversation graph.",
      required: true,
    },
    {
      id: "messenger-app-secret",
      label: "Meta app secret",
      description: "Server-side app secret used to validate X-Hub-Signature-256 webhook deliveries.",
      required: true,
    },
    {
      id: "messenger-webhook-verify-token",
      label: "Webhook verify token",
      description: "SDK-user-owned token checked during Meta webhook endpoint verification.",
      required: false,
    },
    {
      id: "messenger-page-webhook-subscription",
      label: "Messenger Page messages webhook subscription",
      description: "SDK-user-confirmed Page subscribed_apps configuration for Messenger messages webhooks.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Messenger webhooks",
      description: "Validates and parses Messenger Platform webhook payloads after the SDK user's Page is subscribed to the messages webhook.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "messengerWebhook", label: "Messenger Webhook" },
        { kind: "messengerMessage", label: "Messenger Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Messenger messages",
      description: "Sends Messenger Platform messages inside Meta's 24-hour standard messaging window or with SDK-user-approved MESSAGE_TAG non-promotional policy where permitted.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "messengerMessage", label: "Messenger Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Build Messenger payloads",
      description: "Builds text, attachment, quick reply, sender action, and tag payloads for SDK-user approval workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "messengerDraft", label: "Messenger Draft" }],
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Messenger conversations",
      description: "Reads Messenger conversation and message metadata with SDK-user-governed access and retention.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "messengerConversation", label: "Messenger Conversation" },
        { kind: "messengerMessage", label: "Messenger Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Messenger conversations",
      description: "Reads Messenger conversation messages and metadata through the Page Conversations graph selected by SDK configuration.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "messengerConversation", label: "Messenger Conversation" },
        { kind: "messengerMessage", label: "Messenger Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "List Messenger conversations",
      description: "Lists Messenger Page conversations with SDK-user-supplied filters such as user ID, fields, limits, and cursors.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "messengerConversation", label: "Messenger Conversation" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Use Messenger attachments",
      description: "Sends attachment payloads and exposes inbound attachment metadata under SDK-user media policy.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "messengerAttachment", label: "Messenger Attachment" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "social.webhook-signature",
      label: "Validate Meta webhook signatures",
      description: "Validates X-Hub-Signature-256 webhook signatures with the SDK user's Meta app secret.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "messengerSignedWebhook", label: "Messenger Signed Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "messenger.webhook.parse",
      providerOperation: "parseMessengerWebhook",
      capability: "receive",
      providerObject: "messengerWebhook",
      label: "Parse Messenger webhook",
      description: "Validate and parse an inbound Messenger webhook request.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "messenger.message.send",
      providerOperation: "sendMessage",
      capability: "send",
      providerObject: "messengerMessage",
      label: "Send Messenger message",
      description: "Send a Messenger Platform message through the configured Page.",
      audiences: ["customer-facing"],
      requiresCredential: true,
      requiresApproval: true,
      externallyVisible: true,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "messenger.senderAction.send",
      providerOperation: "sendSenderAction",
      capability: "send",
      providerObject: "messengerConversation",
      label: "Send Messenger sender action",
      description: "Send Messenger sender actions such as typing indicators or mark-seen.",
      audiences: ["customer-facing"],
      requiresCredential: true,
      externallyVisible: true,
      sideEffect: true,
      extension: true,
    },
    {
      alias: "messenger.attachment.upload",
      providerOperation: "uploadAttachment",
      capability: "media",
      providerObject: "messengerAttachment",
      label: "Upload Messenger attachment",
      description: "Upload reusable attachment payloads for Messenger sends.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      requiresApproval: true,
      externallyVisible: true,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "messenger.conversations.list",
      providerOperation: "listConversations",
      capability: "search-provider-object",
      providerObject: "messengerConversation",
      label: "List Messenger conversations",
      description: "List Messenger Page conversations with SDK-user-supplied filters.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "messenger.conversationMessages.list",
      providerOperation: "getConversationMessages",
      capability: "read-provider-object",
      providerObject: "messengerMessage",
      label: "Read Messenger conversation messages",
      description: "Read messages for a Messenger conversation.",
      audiences: ["customer-facing", "mixed"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: "messenger.page.read",
      providerOperation: "getPage",
      capability: "read-provider-object",
      providerObject: "messengerPage",
      label: "Read Messenger Page",
      description: "Read configured Facebook Page metadata for readiness diagnostics.",
      audiences: ["internal-support", "mixed"],
      requiresCredential: true,
      extension: true,
    },
    {
      alias: "messenger.webhook-signature",
      providerOperation: "validateMessengerWebhookSignature",
      capability: "social.webhook-signature",
      providerObject: "messengerSignedWebhook",
      label: "Validate Messenger webhook signature",
      description: "Validate Meta X-Hub-Signature-256 for Messenger webhook delivery.",
      audiences: ["internal-support"],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Messenger PSIDs, profile names, message text, attachments, conversation metadata, and webhook payloads can contain customer data.",
    "Meta Page access tokens, app secrets, and webhook verify tokens stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "Available operations depend on the SDK user's Meta app mode, Page connection, permissions, Page access token, webhook subscriptions, and messaging window rules.",
    "Meta no longer supports Handover Protocol as the normal Messenger routing model; SDK users should configure Conversation Routing outside this adapter, and the thread-control client methods are legacy escape hatches only.",
    "Consent, outbound-contact policy, human escalation, attachment retention, redaction, and deletion behavior remain SDK-user configuration.",
    "This package provides Messenger transport helpers and does not choose default automation, promotional messaging, retry, or rate-limit policy.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    channelCoverage: {
      messages: "typed-send",
      senderActions: "typed-send",
      attachments: "typed-upload-send",
      conversations: "typed-list-read",
      pageReadiness: "typed-read",
      webhooks: "typed-challenge-verify-parse",
      legacyHandoverProtocol: "legacy-provider-supported-typed-thread-control",
      conversationRouting: "provider-supported-not-typed",
    },
    docs: "https://developers.facebook.com/docs/messenger-platform",
    apiCoverage: {
      checkedAt: "2026-06-18",
      operationCatalog: "docs/provider-coverage/messenger-platform-graph-selected-api-2026-06-18.operations.json",
      generatedFromOfficialSpec: false,
      machineReadableSpecStatus: "No official public complete Messenger Platform/Graph OpenAPI spec was found in facebook/openapi during this audit.",
      selectedOperationCount: 8,
      implementedOperationCount: 8,
      fullProviderApi: false,
      fullMetaGraphCoverage: false,
    },
  },
});
