import { defineIntegrationProviderPackage } from "@cognidesk/integration-kit";
import { gmailEmailProviderOperations } from "./operations.js";

export const gmailEmailProviderManifest = defineIntegrationProviderPackage({
  id: "email.gmail",
  name: "Gmail",
  packageName: "@cognidesk/integration-email-gmail",
  provider: "gmail",
  category: "email",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  operations: gmailEmailProviderOperations,
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is intentionally scoped to normalized Cognidesk email support workflows implemented by typed handlers.",
      "Implementation uses the official service-specific @googleapis/gmail SDK. Broader Gmail methods remain accessible through GmailEmailClient.rawClient instead of generated Cognidesk-owned full API functions.",
      "Operation handlers are bound through @cognidesk/integration-kit so manifest operations and executable handlers must stay in exact parity.",
      "Receive coverage is Gmail watch/history foundation plus Google Cloud Pub/Sub push notification parsing; Pub/Sub topic/subscription hosting, authentication, retry, and history synchronization policy are SDK-user responsibilities.",
    ],
    evidence: [
      { label: "@googleapis/gmail package", url: "https://www.npmjs.com/package/@googleapis/gmail" },
      { label: "Gmail API Node.js quickstart", url: "https://developers.google.com/workspace/gmail/api/quickstart/nodejs" },
      { label: "Gmail users.threads.get", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.threads/get" },
      { label: "Gmail users.messages.send", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/send" },
      { label: "Gmail users.drafts.create", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.drafts/create" },
      { label: "Gmail users.threads.modify", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.threads/modify" },
      { label: "Gmail users.watch", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users/watch" },
      { label: "Gmail push notifications", url: "https://developers.google.com/workspace/gmail/api/guides/push" },
    ],
  },
  credentialRequirements: [
    {
      id: "google-oauth-access-token",
      label: "Google OAuth access token",
      description: "Server-side OAuth access token or injected official Gmail SDK auth client.",
      scopes: [
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.send",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.metadata",
      ],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Gmail mailbox changes",
      description: "Parses Gmail Pub/Sub notifications and reads Gmail watch/history cursors.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "mailbox", label: "Gmail Mailbox" },
        { kind: "gmailHistory", label: "Gmail History" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Gmail threads and attachments",
      description: "Reads Gmail threads, messages, labels, and attachment bodies through the official SDK.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "emailThread", label: "Email Thread" },
        { kind: "emailMessage", label: "Email Message" },
        { kind: "attachment", label: "Attachment" },
        { kind: "mailLabel", label: "Mail Label" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Create Gmail drafts",
      description: "Creates Gmail draft messages for SDK-user-configured approval workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "emailDraft", label: "Email Draft" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Gmail messages",
      description: "Sends Gmail replies, new messages, or existing drafts when SDK-user policy permits outbound contact.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "emailMessage", label: "Email Message" },
        { kind: "emailDraft", label: "Email Draft" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Archive Gmail threads",
      description: "Removes active inbox labels from Gmail threads when SDK-user policy permits mutation.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "emailThread", label: "Email Thread" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "Gmail messages can contain customer content, attachments, addresses, labels, and thread history.",
    "OAuth tokens stay server-side and are represented in Studio only as credential readiness.",
  ],
  limitations: [
    "Available operations depend on OAuth scopes, Google Workspace policy, delegated user, and mailbox state configured by the SDK user.",
    "Gmail watch notifications require an SDK-user-managed Google Cloud Pub/Sub topic, subscription, webhook/worker, and history synchronization strategy.",
    "Draft approval, auto-send, retention, redaction, and outbound-contact policy are SDK-user configuration.",
    "This package does not claim full Gmail API coverage; use rawClient for advanced official SDK methods.",
  ],
  metadata: {
    implementation: {
      strategy: "official-sdk",
      sdkPackage: "@googleapis/gmail",
      sdkVersionRange: "^17.0.0",
      rawClientEscapeHatch: "GmailEmailClient.rawClient",
      manifestImport: "no-sdk-client-initialization",
      integrationKitStatus: "implemented",
    },
    channelCoverage: {
      gmailThreads: "typed-read-and-archive",
      gmailMessages: "typed-send-and-reply",
      gmailDrafts: "typed-create-and-send",
      gmailAttachments: "typed-read-body",
      gmailLabels: "typed-list",
      gmailWatchHistory: "typed-watch-history-foundation",
      pubSubPushDelivery: "typed-parse-only-sdk-owned-hosting",
      broaderGmailApi: "provider-supported-raw-client",
    },
    scopeAlternatives: {
      profile: [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.metadata",
      ],
      watch: [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.metadata",
      ],
      send: [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.send",
      ],
      metadataOnlyCaveat: "Gmail metadata-only scopes support profile/watch/read metadata surfaces, but SDK users must avoid query-dependent listing where the Gmail API disallows q with gmail.metadata.",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
