import type { ProviderOperationDeclarationInput } from "@cognidesk/integration-kit";

export const GMAIL_EMAIL_OPERATION_ALIASES = [
  "email.receive",
  "email.thread.read",
  "email.reply.send",
  "email.send",
  "email.draft.create",
  "email.draft.send",
  "email.archive",
  "mailbox.watch",
  "gmail.history.list",
  "gmail.attachment.get",
  "gmail.labels.list",
] as const;

export type GmailEmailOperationAlias = typeof GMAIL_EMAIL_OPERATION_ALIASES[number];

export const gmailEmailProviderOperations: ProviderOperationDeclarationInput[] = [
  {
    alias: "email.receive",
    providerOperation: "pubsub.push.parse",
    capability: "receive",
    label: "Receive Gmail Pub/Sub notification",
    description: "Parse a Google Cloud Pub/Sub push envelope for Gmail watch/history synchronization.",
    providerObject: "emailMessage",
    exposesSensitiveData: true,
    outputSchemaName: "GmailPubSubNotification",
  },
  {
    alias: "email.thread.read",
    providerOperation: "users.threads.get",
    capability: "read-provider-object",
    label: "Read Gmail thread",
    description: "Fetch a Gmail thread through the official Gmail SDK and normalize its messages.",
    providerObject: "emailThread",
    exposesSensitiveData: true,
    inputSchemaName: "GmailReadThreadInput",
    outputSchemaName: "GmailEmailThread",
  },
  {
    alias: "email.reply.send",
    providerOperation: "users.messages.send",
    capability: "send",
    label: "Send Gmail reply",
    description: "Send a reply in an existing Gmail thread.",
    providerObject: "emailMessage",
    sideEffect: true,
    externallyVisible: true,
    requiresApproval: true,
    exposesSensitiveData: true,
    inputSchemaName: "GmailReplySendInput",
    outputSchemaName: "GmailEmailMessage",
  },
  {
    alias: "email.send",
    providerOperation: "users.messages.send",
    capability: "send",
    label: "Send Gmail message",
    description: "Send a new Gmail message.",
    providerObject: "emailMessage",
    sideEffect: true,
    externallyVisible: true,
    requiresApproval: true,
    exposesSensitiveData: true,
    inputSchemaName: "GmailSendEmailInput",
    outputSchemaName: "GmailEmailMessage",
  },
  {
    alias: "email.draft.create",
    providerOperation: "users.drafts.create",
    capability: "draft",
    label: "Create Gmail draft",
    description: "Create a Gmail draft for approval workflows.",
    providerObject: "emailDraft",
    sideEffect: true,
    exposesSensitiveData: true,
    inputSchemaName: "GmailCreateDraftInput",
    outputSchemaName: "GmailEmailDraft",
  },
  {
    alias: "email.draft.send",
    providerOperation: "users.drafts.send",
    capability: "send",
    label: "Send Gmail draft",
    description: "Send an existing Gmail draft.",
    providerObject: "emailDraft",
    sideEffect: true,
    externallyVisible: true,
    requiresApproval: true,
    exposesSensitiveData: true,
    inputSchemaName: "GmailSendDraftInput",
    outputSchemaName: "GmailEmailMessage",
  },
  {
    alias: "email.archive",
    providerOperation: "users.threads.modify",
    capability: "update-provider-object",
    label: "Archive Gmail thread",
    description: "Archive a Gmail thread by removing it from INBOX unless alternate labels are supplied.",
    providerObject: "emailThread",
    sideEffect: true,
    changesWorkflow: true,
    exposesSensitiveData: true,
    inputSchemaName: "GmailArchiveThreadInput",
    outputSchemaName: "GmailEmailThread",
  },
  {
    alias: "mailbox.watch",
    providerOperation: "users.watch",
    capability: "receive",
    label: "Watch Gmail mailbox",
    description: "Create or renew a Gmail watch registration for an SDK-user-managed Pub/Sub topic.",
    providerObject: "mailbox",
    sideEffect: true,
    inputSchemaName: "GmailWatchInput",
    outputSchemaName: "GmailWatchResponse",
  },
  {
    alias: "gmail.history.list",
    providerOperation: "users.history.list",
    capability: "receive",
    label: "List Gmail history",
    description: "Read Gmail mailbox history records after a known history cursor.",
    providerObject: "mailbox",
    exposesSensitiveData: true,
    extension: true,
    inputSchemaName: "GmailListHistoryInput",
    outputSchemaName: "GmailHistoryListResponse",
  },
  {
    alias: "gmail.attachment.get",
    providerOperation: "users.messages.attachments.get",
    capability: "read-provider-object",
    label: "Get Gmail attachment body",
    description: "Fetch a Gmail attachment body through the official Gmail SDK.",
    providerObject: "attachment",
    exposesSensitiveData: true,
    extension: true,
    inputSchemaName: "GmailGetAttachmentInput",
    outputSchemaName: "GmailAttachmentBody",
  },
  {
    alias: "gmail.labels.list",
    providerOperation: "users.labels.list",
    capability: "read-provider-object",
    label: "List Gmail labels",
    description: "List labels in the configured Gmail mailbox.",
    providerObject: "mailLabel",
    extension: true,
    inputSchemaName: "GmailProviderRequestOptions",
    outputSchemaName: "GmailLabelListResponse",
  },
];
