import type { IntegrationProviderRuntimeLoaderRegistration } from "./loader.js";

// Generated by scripts/generate-integration-catalog.ts. Do not edit by hand.
export const integrationProviderRuntimeLoaders = [
  { id: "cobrowsing.cognidesk", load: () => import("../cobrowsing/cognidesk/index.js") },
  { id: "community.forum", load: () => import("../community/forum/index.js") },
  { id: "form.cognidesk", load: () => import("../form/cognidesk/index.js") },
  { id: "helpcenter.cognidesk", load: () => import("../help-center/cognidesk/index.js") },
  { id: "sms.twilio", load: () => import("../sms/twilio/index.js") },
  { id: "video.whereby", load: () => import("../video/whereby/index.js") },
  { id: "video.zoom", load: () => import("../video/zoom/index.js") },
  { id: "voice.deepgram", load: () => import("../voice/deepgram/index.js") },
  { id: "voice.elevenlabs", load: () => import("../voice/elevenlabs/index.js") },
  { id: "voice.sip", load: () => import("../voice/sip/index.js") },
  { id: "voice.twilio", load: () => import("../voice/twilio/index.js") },
  { id: "voice.vonage", load: () => import("../voice/vonage/index.js") },
] as const satisfies readonly IntegrationProviderRuntimeLoaderRegistration[];
