import type { IntegrationProviderRuntimeLoaderRegistration } from "./loader.js";

// Generated by scripts/generate-integration-catalog.ts. Do not edit by hand.
export const integrationProviderRuntimeLoaders = [
] as const satisfies readonly IntegrationProviderRuntimeLoaderRegistration[];
