import type { IntegrationProviderRuntimeLoaderRegistration } from "./loader.js";

// Generated by scripts/generate-integration-catalog.ts. Do not edit by hand.
export const integrationProviderRuntimeLoaders = [
  { id: "cobrowsing.cognidesk", load: () => import("../cobrowsing/cognidesk/index.js") },
  { id: "community.forum", load: () => import("../community/forum/index.js") },
  { id: "form.cognidesk", load: () => import("../form/cognidesk/index.js") },
  { id: "helpcenter.cognidesk", load: () => import("../help-center/cognidesk/index.js") },
  { id: "voice.sip", load: () => import("../voice/sip/index.js") },
] as const satisfies readonly IntegrationProviderRuntimeLoaderRegistration[];
