import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { POSTMARK_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  POSTMARK_FULL_API_OPERATION_COUNT,
  POSTMARK_FULL_API_PATH_COUNT,
  POSTMARK_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const postmarkEmailProviderManifest = defineProviderPackage({
  id: "email.postmark",
  name: "Postmark",
  packageName: "@cognidesk/integrations",
  provider: "postmark",
  category: "email",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Postmark's official server and account Swagger files.",
      "Typed convenience helpers remain available for support email workflows: single email send, template send, inbound/outbound message detail and search, webhook listing, message-stream listing, inbound webhook parsing, and suppression dump/create/delete.",
      "The generated full API surface covers Postmark send/batch/template, bounces, stats, opens/clicks, inbound rules, server configuration, account servers, domains, sender signatures, and template push operations from the official Swagger artifacts.",
      "The SDK user still owns stream/sender/template selection, inbound domain and webhook hosting, webhook authentication, retention, redaction, outbound approval, rate limiting, pagination, and which generated operations are exposed to operators.",
    ],
    evidence: [
      { label: "Postmark Server API Swagger", url: "https://postmarkapp.com/swagger/server.yml" },
      { label: "Postmark Account API Swagger", url: "https://postmarkapp.com/swagger/account.yml" },
      { label: "Postmark API Explorer", url: "https://postmarkapp.com/api-explorer" },
      { label: "Postmark Email API", url: "https://postmarkapp.com/developer/user-guide/send-email-with-api" },
      { label: "Postmark Messages API", url: "https://postmarkapp.com/developer/api/messages-api" },
      { label: "Postmark inbound webhook", url: "https://postmarkapp.com/developer/webhooks/inbound-webhook" },
      { label: "Postmark Webhooks API", url: "https://postmarkapp.com/developer/api/webhooks-api" },
      { label: "Postmark Message Streams API", url: "https://postmarkapp.com/developer/api/message-streams-api" },
      { label: "Postmark Suppressions API", url: "https://postmarkapp.com/developer/api/suppressions-api" },
    ],
  },
  credentialRequirements: [
    {
      id: "postmark-server-token",
      label: "Postmark server token",
      description: "Server-side Postmark Server API token used for server-level generated operations and typed Email, Messages, Webhooks, Streams, and Suppressions API calls.",
      scopes: ["Postmark Server API"],
      metadata: {
        scopeKind: "provider-permission-labels",
        privilegeGuidance: "Postmark uses token classes rather than OAuth scopes; this label identifies the Server API token authority.",
      },
      required: true,
    },
    {
      id: "postmark-account-token",
      label: "Postmark account token",
      description: "Server-side Postmark Account API token used for generated account-level server, domain, sender-signature, and template-push operations.",
      scopes: ["Postmark Account API"],
      metadata: {
        scopeKind: "provider-permission-labels",
        privilegeGuidance: "Postmark uses token classes rather than OAuth scopes; this label identifies the Account API token authority.",
      },
      required: true,
    },
    {
      id: "postmark-message-stream",
      label: "Postmark message stream",
      description: "SDK-user-selected Postmark message stream for outbound or inbound processing.",
      required: false,
    },
    {
      id: "postmark-webhook-auth",
      label: "Postmark webhook authentication",
      description: "SDK-user-configured webhook protection such as Basic Auth, private URL routing, or gateway verification.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Postmark inbound webhooks",
      description: "Parses Postmark inbound email JSON webhooks for SDK-user-owned email flows; delivery, bounce, open, click, spam, and subscription event parsers are outside this adapter.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "postmarkInboundMessage", label: "Postmark Inbound Message" },
        { kind: "postmarkWebhook", label: "Postmark Webhook" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Postmark email",
      description: "Sends transactional email through Postmark Email API when SDK-user policy permits outbound contact.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "postmarkOutboundMessage", label: "Postmark Outbound Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Build Postmark outbound payloads",
      description: "Builds Postmark email or template payloads for SDK-user-configured approval workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "postmarkEmailDraft", label: "Postmark Email Draft" }],
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Postmark message metadata",
      description: "Associates inbound replies and outbound messages using Postmark message IDs, tags, headers, and metadata.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "postmarkMessage", label: "Postmark Message" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "attach",
      label: "Use Postmark attachments",
      description: "Accepts outbound attachments and exposes inbound attachment metadata for SDK-user-governed handling.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "postmarkAttachment", label: "Postmark Attachment" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Postmark messages, streams, and suppressions",
      description: "Reads Postmark outbound or inbound message details, message streams, and suppression records through Postmark APIs.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "postmarkMessage", label: "Postmark Message" },
        { kind: "postmarkMessageStream", label: "Postmark Message Stream" },
        { kind: "postmarkSuppression", label: "Postmark Suppression" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Postmark messages",
      description: "Searches Postmark message history with SDK-user-supplied filters and retention-aware limits.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "postmarkMessage", label: "Postmark Message" },
        { kind: "postmarkMessageStream", label: "Postmark Message Stream" },
        { kind: "postmarkSuppression", label: "Postmark Suppression" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Manage Postmark suppressions",
      description: "Creates or deletes Postmark suppression records for SDK-user-governed suppression lifecycle workflows.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "postmarkSuppression", label: "Postmark Suppression" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "Postmark email bodies, recipients, sender addresses, headers, tags, metadata, delivery events, and attachments can contain customer data.",
    "Postmark server tokens and webhook authentication material stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "The SDK user chooses streams, sender signatures, templates, inbound domains, webhook protection, retention, redaction, and outbound approval policy.",
    "Postmark message history is retention-bound; API reads may not prove historical completeness beyond the SDK user's Postmark retention settings.",
    "This package does not decide when to send, auto-reply, attach files, track opens/clicks, or expose inbound content to operators.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://postmarkapp.com/developer",
    channelCoverage: {
      fullPostmarkSwaggerApi: "generated-per-operation-functions",
      singleEmailSend: "typed-send-and-generated-full-surface",
      templateEmailSend: "typed-send-and-generated-full-surface",
      batchEmailSend: "generated-per-operation-functions",
      inboundWebhookParsing: "typed-parse",
      outboundMessages: "typed-read-search",
      inboundMessages: "typed-read-search",
      webhooks: "typed-list",
      messageStreams: "typed-list",
      suppressions: "typed-list-create-delete",
      bouncesStatsOpensClicks: "generated-per-operation-functions",
      inboundRulesServerConfiguration: "generated-per-operation-functions",
      accountServersDomainsSenderSignatures: "generated-per-operation-functions",
      accountTemplatePush: "generated-per-operation-functions",
    },
    fullProviderApiVerification: {
      provider: "postmark",
      apiVersion: POSTMARK_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/postmark-full-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/postmark-full-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/postmark-full-api-2026-06-18.functions.json",
      documentedPathCount: POSTMARK_FULL_API_PATH_COUNT,
      documentedOperationCount: POSTMARK_FULL_API_OPERATION_COUNT,
      implementedOperationCount: POSTMARK_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: POSTMARK_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
});
