// Generated endpoint chunk for AppStoreFullApi.
// Do not edit by hand; run scripts/split-generated-client-modules.mjs after updating provider specs.

import type {
  AppStoreGeneratedOperationCaller,
  AppStoreFullApiOperationArgs,
  AppStoreFullApiOperationInput,
  AppStoreFullApiPathParamValue,
} from "../../full-api-client.generated.js";
import type { AppStoreFullApiOperationResponseMap } from "../../full-api-schema-types.generated.js";

// Hardened literal operation keys for generated SDK typing.
export const AppStoreFullApiGameCenterLeaderboardSetMemberLocalizationsOperationKeys = [
  "gameCenterLeaderboardSetMemberLocalizations_createInstance",
  "gameCenterLeaderboardSetMemberLocalizations_deleteInstance",
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelated",
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelationship",
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelated",
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelationship",
  "gameCenterLeaderboardSetMemberLocalizations_getCollection",
  "gameCenterLeaderboardSetMemberLocalizations_updateInstance"
] as const;
export type AppStoreFullApiGameCenterLeaderboardSetMemberLocalizationsOperationKey = typeof AppStoreFullApiGameCenterLeaderboardSetMemberLocalizationsOperationKeys[number];
// End hardened literal operation keys.

export interface AppStoreFullApiGameCenterLeaderboardSetMemberLocalizationsOperationPathParamMap {
  "gameCenterLeaderboardSetMemberLocalizations_createInstance": {};
  "gameCenterLeaderboardSetMemberLocalizations_deleteInstance": { "id": AppStoreFullApiPathParamValue };
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelated": { "id": AppStoreFullApiPathParamValue };
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelationship": { "id": AppStoreFullApiPathParamValue };
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelated": { "id": AppStoreFullApiPathParamValue };
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelationship": { "id": AppStoreFullApiPathParamValue };
  "gameCenterLeaderboardSetMemberLocalizations_getCollection": {};
  "gameCenterLeaderboardSetMemberLocalizations_updateInstance": { "id": AppStoreFullApiPathParamValue };
}

export interface AppStoreFullApiGameCenterLeaderboardSetMemberLocalizationsOperationRequestMap {
  "gameCenterLeaderboardSetMemberLocalizations_createInstance": AppStoreFullApiOperationInput<"gameCenterLeaderboardSetMemberLocalizations_createInstance">;
  "gameCenterLeaderboardSetMemberLocalizations_deleteInstance": AppStoreFullApiOperationInput<"gameCenterLeaderboardSetMemberLocalizations_deleteInstance">;
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelated": AppStoreFullApiOperationInput<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelated">;
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelationship": AppStoreFullApiOperationInput<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelationship">;
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelated": AppStoreFullApiOperationInput<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelated">;
  "gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelationship": AppStoreFullApiOperationInput<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelationship">;
  "gameCenterLeaderboardSetMemberLocalizations_getCollection": AppStoreFullApiOperationInput<"gameCenterLeaderboardSetMemberLocalizations_getCollection">;
  "gameCenterLeaderboardSetMemberLocalizations_updateInstance": AppStoreFullApiOperationInput<"gameCenterLeaderboardSetMemberLocalizations_updateInstance">;
}

export interface AppStoreFullApiGameCenterLeaderboardSetMemberLocalizationsGeneratedClient {
  GameCenterLeaderboardSetMemberLocalizationsCreateInstance(...args: AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_createInstance">): Promise<AppStoreFullApiOperationResponseMap["gameCenterLeaderboardSetMemberLocalizations_createInstance"]>;
  GameCenterLeaderboardSetMemberLocalizationsDeleteInstance(...args: AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_deleteInstance">): Promise<AppStoreFullApiOperationResponseMap["gameCenterLeaderboardSetMemberLocalizations_deleteInstance"]>;
  GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardGetToOneRelated(...args: AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelated">): Promise<AppStoreFullApiOperationResponseMap["gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelated"]>;
  GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardGetToOneRelationship(...args: AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelationship">): Promise<AppStoreFullApiOperationResponseMap["gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelationship"]>;
  GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardSetGetToOneRelated(...args: AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelated">): Promise<AppStoreFullApiOperationResponseMap["gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelated"]>;
  GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardSetGetToOneRelationship(...args: AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelationship">): Promise<AppStoreFullApiOperationResponseMap["gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelationship"]>;
  GameCenterLeaderboardSetMemberLocalizationsGetCollection(...args: AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_getCollection">): Promise<AppStoreFullApiOperationResponseMap["gameCenterLeaderboardSetMemberLocalizations_getCollection"]>;
  GameCenterLeaderboardSetMemberLocalizationsUpdateInstance(...args: AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_updateInstance">): Promise<AppStoreFullApiOperationResponseMap["gameCenterLeaderboardSetMemberLocalizations_updateInstance"]>;
}

export const AppStoreFullApiGameCenterLeaderboardSetMemberLocalizationsGeneratedFunctionNames = [
  "GameCenterLeaderboardSetMemberLocalizationsCreateInstance",
  "GameCenterLeaderboardSetMemberLocalizationsDeleteInstance",
  "GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardGetToOneRelated",
  "GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardGetToOneRelationship",
  "GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardSetGetToOneRelated",
  "GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardSetGetToOneRelationship",
  "GameCenterLeaderboardSetMemberLocalizationsGetCollection",
  "GameCenterLeaderboardSetMemberLocalizationsUpdateInstance"
] as const satisfies readonly (keyof AppStoreFullApiGameCenterLeaderboardSetMemberLocalizationsGeneratedClient)[];

export function createAppStoreFullApiGameCenterLeaderboardSetMemberLocalizationsGeneratedClient(
  callOperation: AppStoreGeneratedOperationCaller,
): AppStoreFullApiGameCenterLeaderboardSetMemberLocalizationsGeneratedClient {
  return {
    GameCenterLeaderboardSetMemberLocalizationsCreateInstance: (...args) => callOperation("gameCenterLeaderboardSetMemberLocalizations_createInstance", ...(args as AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_createInstance">)),
    GameCenterLeaderboardSetMemberLocalizationsDeleteInstance: (...args) => callOperation("gameCenterLeaderboardSetMemberLocalizations_deleteInstance", ...(args as AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_deleteInstance">)),
    GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardGetToOneRelated: (...args) => callOperation("gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelated", ...(args as AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelated">)),
    GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardGetToOneRelationship: (...args) => callOperation("gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelationship", ...(args as AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboard_getToOneRelationship">)),
    GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardSetGetToOneRelated: (...args) => callOperation("gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelated", ...(args as AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelated">)),
    GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardSetGetToOneRelationship: (...args) => callOperation("gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelationship", ...(args as AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_gameCenterLeaderboardSet_getToOneRelationship">)),
    GameCenterLeaderboardSetMemberLocalizationsGetCollection: (...args) => callOperation("gameCenterLeaderboardSetMemberLocalizations_getCollection", ...(args as AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_getCollection">)),
    GameCenterLeaderboardSetMemberLocalizationsUpdateInstance: (...args) => callOperation("gameCenterLeaderboardSetMemberLocalizations_updateInstance", ...(args as AppStoreFullApiOperationArgs<"gameCenterLeaderboardSetMemberLocalizations_updateInstance">)),
  };
}
