import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { APPSTORE_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  APPSTORE_FULL_API_OPERATION_COUNT,
  APPSTORE_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const appStoreReviewsProviderManifest = defineProviderPackage({
  id: "review.appstore",
  name: "App Store Reviews",
  packageName: "@cognidesk/integrations",
  provider: "appstore",
  category: "review",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Apple's official App Store Connect OpenAPI specification.",
      "The package keeps typed support helpers for customer review support primitives: app review list/read pagination, customer review response create-or-update/delete, app readiness reads, and ES256 JWT creation.",
      "The SDK user owns App Store Connect roles, app scoping, localization, public-response approval, moderation, consent, redaction, and retention decisions.",
    ],
    evidence: [
      { label: "App Store Connect OpenAPI specification", url: "https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip" },
      { label: "App Store Connect API overview", url: "https://developer.apple.com/documentation/appstoreconnectapi" },
      { label: "List customer reviews for an app", url: "https://developer.apple.com/documentation/appstoreconnectapi/get-v1-apps-_id_-customerreviews" },
      { label: "Customer review responses", url: "https://developer.apple.com/documentation/appstoreconnectapi/customer-review-responses" },
      { label: "Create or update customer review response", url: "https://developer.apple.com/documentation/appstoreconnectapi/post-v1-customerreviewresponses" },
      { label: "Creating API keys for App Store Connect API", url: "https://developer.apple.com/documentation/appstoreconnectapi/creating-api-keys-for-app-store-connect-api" },
    ],
  },
  credentialRequirements: [
    {
      id: "appstore-api-key",
      label: "App Store Connect API key",
      description: "Issuer ID, key ID, and private key used to mint ES256 JWTs for App Store Connect API calls.",
      required: true,
    },
    {
      id: "appstore-app-id",
      label: "App Store Connect app ID",
      description: "App Store Connect app resource ID whose customer reviews are visible to the SDK user.",
      required: true,
    },
    {
      id: "appstore-review-response-policy",
      label: "Review response policy",
      description: "SDK-user policy controlling which review replies may be drafted, published, updated, or removed.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Read App Store reviews",
      description: "Reads App Store Connect customer reviews as support signals for SDK-user-configured review workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "appStoreCustomerReview", label: "App Store Customer Review" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Draft review responses",
      description: "Builds App Store review response payloads for SDK-user approval workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "appStoreReviewResponseDraft", label: "App Store Review Response Draft" }],
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Publish review responses",
      description: "Creates or updates App Store Connect customer review responses when SDK-user policy allows public replies.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "appStoreCustomerReviewResponse", label: "App Store Customer Review Response" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read review records",
      description: "Reads App Store review details, included relationships, and existing response resources.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "appStoreCustomerReview", label: "App Store Customer Review" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "List and filter reviews",
      description: "Lists App Store reviews with SDK-user-selected filters, includes, pagination, sorting, and locale constraints.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "appStoreCustomerReview", label: "App Store Customer Review" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update review responses",
      description: "Updates or deletes existing App Store customer review responses according to SDK-user approval policy.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "appStoreCustomerReviewResponse", label: "App Store Customer Review Response" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "App Store review text, ratings, reviewer nicknames, territories, app versions, and public response text can contain customer data.",
    "App Store Connect private keys stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "The SDK user decides review triage, sentiment classification, public-response approval, localization, escalation, and retention policy.",
    "Customer review listing is paged by App Store Connect response links; callers should follow `links.next` through the bounded `listReviewsPage` helper rather than assuming cursor shape.",
    "Creating a customer review response uses Apple's create-or-update endpoint; SDK-user policy must treat the first public reply and later edits as externally visible actions.",
    "App Store Connect API availability, rate limits, review visibility, and response moderation are controlled by Apple and the SDK user's account permissions.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://developer.apple.com/documentation/appstoreconnectapi/customer-reviews",
    channelCoverage: {
      fullAppStoreConnectApiOperations: "generated-per-operation-functions",
      customerReviews: "typed-list-read-page-and-generated-full-surface",
      reviewResponses: "typed-create-delete-and-generated-full-surface",
      appsReadiness: "typed-read-and-generated-full-surface",
      jwt: "typed-token-mint",
      buildsBetaIapAnalyticsSalesReportsSubmission: "generated-full-surface",
    },
    fullProviderApiVerification: {
      provider: "appstore",
      apiVersion: APPSTORE_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/appstore-full-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/appstore-full-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/appstore-full-api-2026-06-18.functions.json",
      documentedOperationCount: APPSTORE_FULL_API_OPERATION_COUNT,
      implementedOperationCount: APPSTORE_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: APPSTORE_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
});
