import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { AMAZON_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  AMAZON_FULL_API_MODEL_COUNT,
  AMAZON_FULL_API_OPERATION_COUNT,
  AMAZON_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const amazonMarketplaceProviderManifest = defineProviderPackage({
  id: "marketplace.amazon",
  name: "Amazon Marketplace",
  packageName: "@cognidesk/integrations",
  provider: "amazon",
  category: "marketplace",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Amazon's official Selling Partner API model repository.",
      "Typed helpers remain available for selected Amazon SP-API marketplace support primitives: LWA token refresh, optional SigV4 signing, Orders v0 order/item/buyer-info reads with RDT handling, Solicitations requests, Sellers marketplace participation, Notifications destination reads, subscription creation/read/deletion, and verified notification ingress.",
      "Orders API v2026-01-01 migration coverage includes typed searchOrders/getOrder helpers with includedData; v0 buyer-info methods still use Restricted Data Tokens because that is the legacy authorization model.",
      "Amazon deprecated Orders API v0 operations on January 28, 2026 and lists March 27, 2027 as the removal date for getOrders, getOrder, getOrderBuyerInfo, getOrderAddress, getOrderItems, and getOrderItemsBuyerInfo.",
      "Generated functions cover catalog, listings, feeds, reports, finances, FBA inventory/inbound/outbound, merchant fulfillment, pricing, product fees, services, vendor, data kiosk, transfers, application-management, and other SP-API model surfaces; SDK users still own provider roles, grantless tokens, RDT use, and regional endpoint selection.",
      "The SDK user owns SP-API roles, marketplace selection, RDT policy, notification transport, destination provisioning, grantless authorization, seller eligibility, consent, redaction, and retention decisions.",
    ],
    evidence: [
      { label: "Amazon official SP-API model repository", url: "https://github.com/amzn/selling-partner-api-models/tree/main/models" },
      { label: "Amazon SP-API Orders v0 reference", url: "https://developer-docs.amazon.com/sp-api/reference/orders-v0" },
      { label: "Amazon SP-API Orders v2026-01-01 reference", url: "https://developer-docs.amazon.com/sp-api/reference/orders-v2026-01-01" },
      { label: "Amazon SP-API Orders migration guide", url: "https://developer-docs.amazon.com/sp-api/docs/orders-api-migration-guide" },
      { label: "Amazon Orders API v2026 announcement", url: "https://developer-docs.amazon.com/sp-api/changelog/new-introducing-the-orders-api-v2026-01-01" },
      { label: "Amazon SP-API deprecation schedule", url: "https://developer-docs.amazon.com/sp-api/docs/sp-api-deprecations" },
      { label: "Amazon SP-API Restricted Data Token", url: "https://developer-docs.amazon.com/sp-api/reference/createrestricteddatatoken" },
      { label: "Amazon SP-API RDT authorization guide", url: "https://developer-docs.amazon.com/sp-api/docs/authorization-with-the-restricted-data-token" },
      { label: "Amazon SP-API Solicitations API", url: "https://developer-docs.amazon.com/sp-api/docs/solicitations-api" },
      { label: "Amazon SP-API Notifications API", url: "https://developer-docs.amazon.com/sp-api/docs/notifications-api" },
    ],
  },
  credentialRequirements: [
    {
      id: "amazon-lwa-client",
      label: "Amazon LWA client credentials",
      description: "Login with Amazon client ID and secret owned by the SDK user for SP-API token refresh.",
      required: true,
    },
    {
      id: "amazon-lwa-token",
      label: "Amazon LWA refresh or access token",
      description: "Seller-authorized refresh/access token for role-gated SP-API calls, or grantless token material for Notifications API operations.",
      required: true,
    },
    {
      id: "amazon-aws-role-region",
      label: "Amazon SP-API AWS role and region",
      description: "Optional IAM role/region and SigV4 material for SDK users who operate through legacy or gateway signing paths.",
      required: false,
    },
    {
      id: "amazon-marketplace-id",
      label: "Amazon marketplace ID",
      description: "SDK-user-selected Amazon marketplace such as ATVPDKIKX0DER or A1PA6795UKMFR9.",
      required: true,
    },
    {
      id: "amazon-notification-destination",
      label: "Amazon notification destination",
      description: "Notifications API destination, SQS/EventBridge routing, and SDK-user webhook gateway metadata.",
      required: true,
    },
    {
      id: "amazon-notification-signature",
      label: "Amazon notification verification",
      description: "SDK-user-provided verifier, shared secret, or gateway signature policy for fail-closed notification ingestion.",
      required: true,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Amazon marketplace notifications",
      description: "Parses SP-API notification payloads from SQS, EventBridge, or SDK-user webhooks after configured verification succeeds.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "amazonNotification", label: "Amazon Notification" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Amazon marketplace records",
      description: "Reads seller orders, order items, buyer information where authorized, solicitation metadata, seller participation, and notification configuration.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "amazonOrder", label: "Amazon Order" },
        { kind: "amazonOrderItem", label: "Amazon Order Item" },
        { kind: "amazonBuyerInfo", label: "Amazon Buyer Info" },
        { kind: "amazonSolicitation", label: "Amazon Solicitation" },
        { kind: "amazonSellerAccount", label: "Amazon Seller Account" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Amazon marketplace records",
      description: "Searches orders and notification resources with SDK-user-supplied marketplace, date, status, and pagination filters.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "amazonOrder", label: "Amazon Order" },
        { kind: "amazonNotificationSubscription", label: "Amazon Notification Subscription" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Amazon support actions",
      description: "Creates review/feedback solicitations and notification subscriptions only when the SDK user's marketplace policy allows outbound actions.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "amazonSolicitation", label: "Amazon Solicitation" },
        { kind: "amazonNotificationSubscription", label: "Amazon Notification Subscription" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "send",
      label: "Send Amazon buyer solicitations",
      description: "Sends supported Solicitations API review/feedback requests chosen by the SDK user's workflow.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "amazonSolicitation", label: "Amazon Solicitation" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "marketplace.notification-signature",
      label: "Validate Amazon notification ingress",
      description: "Requires a SDK-user verifier, shared secret, or gateway signature policy before returning normalized Amazon notification payloads.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "amazonVerifiedNotification", label: "Amazon Verified Notification" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      capability: "marketplace.sigv4",
      label: "Sign Amazon SP-API requests",
      description: "Optionally signs SP-API REST requests with AWS SigV4 for SDK users that still operate signed gateways or legacy authorization paths.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "amazonSignedRequest", label: "Amazon Signed Request" }],
      requiresCredential: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Amazon marketplace orders, order items, buyer information, seller account records, solicitations, and notifications can contain customer data, addresses, identifiers, and support context.",
    "LWA secrets, refresh tokens, access tokens, AWS role/signing material, notification shared secrets, and verifier logic stay server-side; Studio receives only readiness and capability metadata.",
  ],
  limitations: [
    "The SDK user chooses marketplaces, roles, restricted-data-token policy, notification topics, outbound solicitation rules, operator visibility, retention, consent, and redaction.",
    "Some SP-API operations require role approval, restricted data tokens, marketplace availability, or grantless authorization; this package exposes typed REST foundations and does not decide seller eligibility.",
    "Orders v0 remains available for existing SDK callers but Amazon lists March 27, 2027 as the removal date; SDK users should migrate order sync/read flows to the v2026-01-01 helpers and includedData where their roles support it.",
    "Amazon notification transports vary by destination; this package fails closed unless the SDK user configures a verifier, gateway signature, or shared-secret check appropriate to their ingress path.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://developer-docs.amazon.com/sp-api",
    ordersDocs: "https://developer-docs.amazon.com/sp-api/reference/orders-v0",
    notificationsDocs: "https://developer-docs.amazon.com/sp-api/docs/notifications-api",
    solicitationsDocs: "https://developer-docs.amazon.com/sp-api/docs/solicitations-api",
    channelCoverage: {
      lwaTokenRefresh: "typed-token-refresh",
      restrictedDataTokens: "typed-create",
      ordersV0: "typed-read-search",
      ordersV2026: "typed-read-search",
      buyerInfoRdt: "typed-read-restricted",
      orderItems: "typed-read",
      solicitations: "typed-read-create-send",
      sellerParticipation: "typed-read",
      notificationDestinations: "typed-read",
      notificationSubscriptions: "typed-create-read-delete",
      notificationIngress: "typed-verify-parse",
      sigv4Signing: "typed-sign",
      catalogListingsFeedsReportsFinancesFba: "generated-full-surface",
      fullSellingPartnerApiOperations: "generated-per-operation-functions",
    },
    fullProviderApiVerification: {
      provider: "amazon-spapi",
      apiVersion: AMAZON_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/amazon-spapi-full-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/amazon-spapi-full-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/amazon-spapi-full-api-2026-06-18.functions.json",
      officialModelCount: AMAZON_FULL_API_MODEL_COUNT,
      documentedOperationCount: AMAZON_FULL_API_OPERATION_COUNT,
      implementedOperationCount: AMAZON_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: AMAZON_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
});
