import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { EIGHT_BY_EIGHT_CONTACT_CENTER_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  EIGHT_BY_EIGHT_CONTACT_CENTER_API_OPERATION_COUNT,
  EIGHT_BY_EIGHT_CONTACT_CENTER_API_PATH_COUNT,
} from "./full-api-operations.generated.js";

export const eightByEightContactCenterProviderManifest = defineProviderPackage({
  id: "contactCenter.8x8",
  name: "8x8 Contact Center",
  packageName: "@cognidesk/integrations",
  provider: "8x8",
  category: "contactCenter",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    { id: "8x8-contact-center-api-base", label: "8x8 Contact Center API base URL", required: true },
    {
      id: "8x8-contact-center-api-access",
      label: "8x8 Contact Center API access",
      description: "Endpoint-specific 8x8 API access configured by the SDK app; this package does not assume an OAuth scope for generic configured paths.",
      required: true,
      metadata: {
        scopeKind: "mixed-auth-mode",
        privilegeGuidance: "8x8 APIs include OAuth-based Contact Center Chat/analytics access and bearer/API-key style access for other configured Contact Center endpoints.",
      },
    },
    { id: "8x8-contact-center-routing", label: "8x8 queue/campaign routing configuration", required: false },
  ],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage includes generated per-operation functions for 11 official machine-readable 8x8 OpenAPI specs covering Contact Center Actions/Events, Chat Gateway, public Chat API variants, campaigns, Contact Center analytics, and QMSA.",
      "The generated slice covers 135 operations across 106 documented paths from the verified official specs; duplicate public Chat API variants are represented with spec-qualified operation UIDs.",
      "This is not full 8x8 product coverage and does not claim CRM, legacy recordings/transcripts, event streaming, PDF-only, gated, support-portal-only, or prose-only surfaces without public machine-readable OpenAPI specs.",
      "The generic handoff capability describes Cognidesk escalation intent only; native outbound/call-control behavior is exposed through separate typed provider-specific methods.",
    ],
    evidence: [
      { label: "8x8 Contact Center Chat API V2 OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/actions-events/8x8_contact_center_chat_api_v2.json" },
      { label: "8x8 Contact Center Dynamic Campaigns OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/actions-events/8x8_contact_center_dynamic_campaigns.json" },
      { label: "8x8 Contact Center Campaigns API OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/actions-events/8x8_contact_center_new_campaigns.json" },
      { label: "8x8 Chapi Chat API OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/actions-events/chapi_-_chat_api.json" },
      { label: "8x8 Contact Center Chat Gateway OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/actions-events/contact-center-chat-gateway-v1.oas.yml" },
      { label: "8x8 Contact Center Call API OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/actions-events/contact_center_call_api.json" },
      { label: "8x8 Contact Center Agent Status API OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/actions-events/contact_center_agent_status_api.json" },
      { label: "8x8 Analytics for Contact Center Historical Metrics OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/analytics/8x8_analytics_for_contact_center_historical_metrics_api.json" },
      { label: "8x8 Analytics for Contact Center Real-time Metrics OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/analytics/8x8_analytics_for_contact_center_real-time_metrics_api.json" },
      { label: "8x8 Quality Management and Speech Analytics OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/analytics/quality_management_and_speech_analytics_api.json" },
      { label: "8x8 Contact Center Chat API OpenAPI", url: "https://raw.githubusercontent.com/8x8Cloud/public-developer-docs/master/docs_oas/contactcenter/8x8_contact_center_chat_api.json" },
      { label: "8x8 Contact Center Chat API V2 Reference", url: "https://developer.8x8.com/actions-events/reference/8-x-8-contact-center-chat-api-v-2/" },
      { label: "8x8 Contact Center Dynamic Campaigns Reference", url: "https://developer.8x8.com/actions-events/reference/8-x-8-contact-center-dynamic-campaigns/" },
      { label: "8x8 Contact Center Campaigns API Reference", url: "https://developer.8x8.com/actions-events/reference/contact-center-campaigns-api/" },
      { label: "8x8 Contact Center Chat Gateway Reference", url: "https://developer.8x8.com/actions-events/reference/contact-center-chat-gateway/" },
      { label: "8x8 Contact Center Call API Reference", url: "https://developer.8x8.com/actions-events/reference/8-x-8-contact-center-call-api-reference/" },
      { label: "8x8 place phone call", url: "https://developer.8x8.com/actions-events/reference/place-phone-call/" },
      { label: "8x8 add transaction codes", url: "https://developer.8x8.com/actions-events/reference/add-transaction-codes/" },
      { label: "8x8 delete phone interaction", url: "https://developer.8x8.com/actions-events/reference/delete-phone-interaction/" },
      { label: "8x8 hang up agent handling interaction", url: "https://developer.8x8.com/actions-events/reference/hangup-agent-handling-interaction/" },
      { label: "8x8 hang up agent line", url: "https://developer.8x8.com/actions-events/reference/hangup-agent-line/" },
      { label: "8x8 hang up agent lines", url: "https://developer.8x8.com/actions-events/reference/hangup-agent-lines/" },
      { label: "8x8 set agent status", url: "https://developer.8x8.com/actions-events/reference/setagentstatus/" },
      { label: "8x8 Analytics for Contact Center Real-time Metrics API", url: "https://developer.8x8.com/analytics/reference/8-x-8-analytics-for-contact-center-real-time-metrics-api/" },
      { label: "8x8 Analytics for Contact Center Historical Metrics API", url: "https://developer.8x8.com/analytics/reference/8-x-8-analytics-for-contact-center-historical-metrics-api/" },
      { label: "8x8 Quality Management and Speech Analytics API", url: "https://developer.8x8.com/analytics/reference/quality-management-and-speech-analytics-api/" },
      { label: "8x8 Contact Center Chat API", url: "https://developer.8x8.com/contactcenter/docs/contact-center-chat/" },
      { label: "8x8 Contact Center Chat Gateway", url: "https://developer.8x8.com/actions-events/docs/chat-gateway/" },
      { label: "8x8 Contact Center API overview", url: "https://support-portal.8x8.com/helpcenter/viewArticle.html?c=1_40_53_58_7561_&d=7237bf9a-1600-4eb5-8dc4-f3a5fa5533f3&hl=en" },
    ],
  },
  capabilities: [
    {
      capability: "handoff",
      label: "Create 8x8 handoff",
      description: "Creates SDK-configured 8x8 Contact Center support-workflow requests without implying typed case, queue, chat, or transfer coverage.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "eightByEightConfiguredHandoff", label: "8x8 configured handoff request" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "send",
      label: "Create 8x8 outbound phone interaction",
      description: "Creates an agent-assigned outbound phone interaction with the documented 8x8 Call API.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "eightByEightCall", label: "8x8 Call Interaction" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "contact-center.call-control",
      label: "Control 8x8 call interaction",
      description: "Ends or hangs up documented 8x8 call interactions and releases agent lines; this does not claim native transfer coverage.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "eightByEightCall", label: "8x8 Call Interaction" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
      extension: true,
    },
    {
      capability: "update-provider-object",
      label: "Update 8x8 call metadata and agent status",
      description: "Updates documented transaction codes and selected agent status through 8x8 Contact Center APIs.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "eightByEightCall", label: "8x8 Call Interaction" },
        { kind: "eightByEightAgentStatus", label: "8x8 Agent Status" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "8x8 handoffs can include customer identifiers, queue context, call/message metadata, and summaries.",
    "8x8 API credentials stay server-side and Studio only receives readiness.",
  ],
  limitations: [
    "8x8 regional endpoints, queue/campaign IDs, contact flows, and outbound eligibility are SDK-user configuration.",
  ],
  metadata: {
    channelCoverage: {
      generatedVerifiedOpenApiOperations: "generated-per-operation-functions",
      generatedCallAndAgentStatusApiOperations: "generated-per-operation-functions",
      configuredHttpHandoff: "supported",
      outboundPhoneInteraction: "generated-slice-and-typed-helper",
      callControl: "generated-slice-and-typed-helpers",
      agentStatus: "generated-slice-and-typed-helpers",
      chat: "generated-per-operation-functions",
      chatGateway: "generated-per-operation-functions",
      chatHandoff: "generated-per-operation-functions",
      callback: "provider-supported-not-typed",
      transfer: "provider-supported-not-typed",
      email: "not-covered",
      smsSocialDigital: "provider-supported-not-typed",
      campaigns: "generated-per-operation-functions",
      crm: "not-covered",
      recordings: "not-covered",
      webhooks: "generated-per-operation-functions",
      eventStreaming: "not-covered",
      realtimeMetrics: "generated-per-operation-functions",
      historicalMetrics: "generated-per-operation-functions",
      qualityManagementSpeechAnalytics: "generated-per-operation-functions",
      reporting: "generated-per-operation-functions",
    },
    generatedProviderApiSlices: {
      verifiedOfficialOpenApi: {
        provider: "8x8-contact-center-actions-events-analytics-qmsa",
        verifiedAt: "2026-06-18",
        coverageArtifact: "docs/provider-coverage/8x8-contact-center-api-2026-06-18.operations.json",
        operationCatalogArtifact: "docs/provider-coverage/8x8-contact-center-api-2026-06-18.operations.json",
        functionCatalogArtifact: "docs/provider-coverage/8x8-contact-center-api-2026-06-18.functions.json",
        documentedSpecCount: 11,
        documentedPathCount: EIGHT_BY_EIGHT_CONTACT_CENTER_API_PATH_COUNT,
        documentedOperationCount: EIGHT_BY_EIGHT_CONTACT_CENTER_API_OPERATION_COUNT,
        implementedOperationCount: EIGHT_BY_EIGHT_CONTACT_CENTER_API_OPERATION_COUNT,
        generatedFunctionCount: EIGHT_BY_EIGHT_CONTACT_CENTER_API_GENERATED_FUNCTION_COUNT,
      },
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
