import { defineProviderPackage } from "@cognidesk/core";

export const discordGatewayProviderManifest = defineProviderPackage({
  id: "community.discord.gateway",
  name: "Discord Gateway Community Support",
  packageName: "@cognidesk/integration-discord",
  provider: "discord",
  category: "community",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  credentialRequirements: [
    {
      id: "discord-bot-token",
      label: "Discord bot token",
      description: "Server-side Discord bot token used for Gateway message ingestion, thread creation, message sending, typing indicators, and reactions.",
      scopes: ["bot"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "discord-application-id",
      label: "Discord application ID",
      description: "SDK-user-owned Discord application ID used to identify the bot installation.",
      required: true,
    },
    {
      id: "discord-guild-id",
      label: "Discord guild ID",
      description: "Guild/server ID selected by SDK configuration for community support routing.",
      required: true,
    },
    {
      id: "discord-support-channel-id",
      label: "Discord support channel ID",
      description: "Guild text or announcement channel where support threads are created and resumed.",
      required: true,
    },
  ],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is scoped to Discord Gateway message handoff for Cognidesk support conversations.",
      "The package creates or reuses Discord threads, ingests customer messages through discord.js Gateway events, mirrors Cognidesk runtime messages into threads, records idempotency state, and exposes a SQLite-backed binding store.",
      "This package is the live Gateway companion to generated Discord REST/interactions helpers; it is released separately so applications do not need to own Discord infrastructure code.",
      "Discord bot installation, intents, channel permissions, moderation policy, consent, retention, deletion, and public/private reply policy remain SDK-user-owned configuration.",
    ],
    evidence: [
      { label: "Discord Gateway events", url: "https://docs.discord.com/developers/events/gateway-events" },
      { label: "Discord Gateway intents", url: "https://docs.discord.com/developers/topics/gateway#gateway-intents" },
      { label: "Discord message resource", url: "https://docs.discord.com/developers/resources/message" },
      { label: "Discord channel/thread endpoints", url: "https://docs.discord.com/developers/resources/channel" },
      { label: "Discord threads topic", url: "https://docs.discord.com/developers/topics/threads" },
    ],
  },
  capabilities: [
    {
      capability: "receive",
      label: "Receive Discord thread messages",
      description: "Consumes Discord Gateway messageCreate events from a configured guild support channel or thread.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "discordMessage", label: "Discord Message" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Mirror Cognidesk messages to Discord",
      description: "Sends assistant replies, web-origin customer messages, voice-origin transcripts, and web continuation prompts into bound Discord threads.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "discordMessage", label: "Discord Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Create and resume Discord support threads",
      description: "Creates Discord support threads for active Cognidesk conversations and resumes existing thread bindings.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "discordThread", label: "Discord Thread" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "notify",
      label: "Signal Discord handling state",
      description: "Uses typing indicators and lightweight reactions to show Discord-side turn handling progress.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "discordReaction", label: "Discord Reaction" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: false,
    },
  ],
  privacyNotes: [
    "Discord messages, user IDs, guild IDs, channel IDs, thread IDs, usernames, and runtime conversation transcripts can contain customer and moderator data.",
    "Bot tokens, guild/channel routing, consent, moderation, retention, deletion, and transcript policy stay SDK-user-owned configuration.",
  ],
  limitations: [
    "The package requires Discord Gateway access with Message Content Intent enabled when message text is mirrored into Cognidesk.",
    "Only guild text and announcement channel thread workflows are handled; Discord voice, local RPC/IPC, webhook events subscriptions, slash command registration, and broader REST administration remain outside this Gateway package.",
    "Available behavior depends on the SDK user's Discord application, bot installation, OAuth scopes, role permissions, channel permissions, thread settings, and rate limits.",
  ],
  metadata: {
    gatewayLibrary: "discord.js",
    providerPackageId: "community.discord",
    defaultSourceId: "discord-gateway",
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
