import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { AMAZON_CONNECT_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  AMAZON_CONNECT_FULL_API_MODEL_COUNT,
  AMAZON_CONNECT_FULL_API_OPERATION_COUNT,
  AMAZON_CONNECT_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const amazonConnectContactCenterProviderManifest = defineProviderPackage({
  id: "contactCenter.amazon-connect",
  name: "Amazon Connect",
  packageName: "@cognidesk/integrations",
  provider: "amazon-connect",
  category: "contactCenter",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    {
      id: "amazon-connect-instance",
      label: "Amazon Connect instance",
      description: "The SDK user's Amazon Connect instance ID and AWS region.",
      required: true,
    },
    {
      id: "amazon-connect-api-access",
      label: "Amazon Connect API access",
      description: "Server-side AWS SigV4-signed access for Amazon Connect APIs.",
      scopes: ["connect:StartTaskContact", "connect:StartChatContact", "connect:TransferContact", "connect:DescribeInstance"],
      required: true,
      metadata: {
        scopeKind: "provider-permission-labels",
        privilegeGuidance: "These strings are AWS IAM action names, not OAuth scopes.",
      },
    },
  ],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in the selected official AWS Connect-family API models bundled in aws/api-models-aws.",
      "Typed helpers remain available for Amazon Connect StartTaskContact handoffs, StartChatContact chat initiation, selected Connect Participant Service chat operations, TransferContact for documented TASK/EMAIL transfer, and DescribeInstance readiness.",
      "StartTaskContact can select a routing target such as ContactFlowId, QuickConnectId, or TaskTemplateId and can include documented task attachments by S3 URL. StartChatContact returns a ParticipantToken that must be exchanged through CreateParticipantConnection before participant SendMessage/SendEvent/GetTranscript calls.",
      "Generated functions cover StartEmailContact, StartOutboundChatContact, StartOutboundEmailContact, StartOutboundVoiceContact, StartWebRTCContact, queues, users, flows, analytics, campaigns, cases, Contact Lens, Connect Health, AppIntegrations, Customer Profiles, Q Connect, Wisdom, and full Connect Participant Service operations present in the official models.",
      "SDK users still own IAM permissions, SigV4 signing, participant bearer-token custody, regional endpoint policy, contact-flow design, outbound consent, and feature entitlement checks.",
    ],
    evidence: [
      { label: "AWS official API models for Amazon Connect family", url: "https://github.com/aws/api-models-aws/tree/main/models" },
      { label: "AWS API models announcement", url: "https://aws.amazon.com/blogs/aws/introducing-aws-api-models-and-publicly-available-resources-for-aws-api-definitions/" },
      { label: "Amazon Connect StartTaskContact", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_StartTaskContact.html" },
      { label: "Amazon Connect StartChatContact", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_StartChatContact.html" },
      { label: "Amazon Connect API operations", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_Operations_Amazon_Connect_Service.html" },
      { label: "Amazon Connect StartOutboundVoiceContact", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_StartOutboundVoiceContact.html" },
      { label: "Amazon Connect StartOutboundChatContact", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_StartOutboundChatContact.html" },
      { label: "Amazon Connect StopContact", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_StopContact.html" },
      { label: "Amazon Connect Participant Service", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_Operations_Amazon_Connect_Participant_Service.html" },
      { label: "Amazon Connect Participant SendEvent", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_connect-participant_SendEvent.html" },
      { label: "Amazon Connect Participant GetTranscript", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_connect-participant_GetTranscript.html" },
      { label: "Amazon Connect Participant StartAttachmentUpload", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_connect-participant_StartAttachmentUpload.html" },
      { label: "Amazon Connect TransferContact", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_TransferContact.html" },
      { label: "Amazon Connect DescribeInstance", url: "https://docs.aws.amazon.com/connect/latest/APIReference/API_DescribeInstance.html" },
      { label: "Amazon Connect API Reference", url: "https://docs.aws.amazon.com/connect/latest/APIReference/Welcome.html" },
      { label: "Amazon AppIntegrations API Reference", url: "https://docs.aws.amazon.com/appintegrations/latest/APIReference/Welcome.html" },
      { label: "Amazon Connect Customer Profiles API Reference", url: "https://docs.aws.amazon.com/customerprofiles/latest/APIReference/Welcome.html" },
      { label: "Amazon Q in Connect API Reference", url: "https://docs.aws.amazon.com/amazon-q-connect/latest/APIReference/Welcome.html" },
    ],
  },
  capabilities: [
    {
      capability: "handoff",
      label: "Create Amazon Connect task handoffs",
      description: "Starts Amazon Connect task contacts for SDK-user-configured human handoff queues or flows; this is not broad bidirectional voice/chat transfer.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "amazonConnectTaskContact", label: "Amazon Connect Task Contact" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "send",
      label: "Send Amazon Connect chat messages",
      description: "Starts Amazon Connect chat contacts and sends participant-service messages only with SDK-user-managed ParticipantToken/ConnectionToken flow.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "amazonConnectChatContact", label: "Amazon Connect Chat Contact" },
        { kind: "amazonConnectChatMessage", label: "Amazon Connect Chat Message" },
        { kind: "amazonConnectParticipantEvent", label: "Amazon Connect Participant Event" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "transfer",
      label: "Transfer Amazon Connect task or email contacts",
      description: "Transfers active TASK or EMAIL contacts through TransferContact when SDK configuration supplies a transfer flow and exactly one queue or user target.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "amazonConnectContactTransfer", label: "Amazon Connect Contact Transfer" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Check Amazon Connect API readiness",
      description: "Uses the configured client to verify Amazon Connect API access without exposing credentials.",
      audiences: ["internal-support"],
      providerObjects: [
        { kind: "amazonConnectInstance", label: "Amazon Connect Instance" },
        { kind: "amazonConnectChatTranscript", label: "Amazon Connect Chat Transcript" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Task contacts can contain customer identifiers, transcript summaries, references, and routing attributes.",
    "Chat contacts and participant-service calls can contain customer display names, initial messages, message content, events, connection tokens, participant tokens, and transcript records.",
    "AWS credentials or SigV4 signing material stay server-side and are represented in Studio only as readiness.",
  ],
  limitations: [
    "Exactly one of contactFlowId, quickConnectId, or taskTemplateId should be supplied unless the task template has its own flow.",
    "StartChatContact requires contactFlowId and participantDetails; clients must create the participant connection within Amazon Connect's documented timing and own WebSocket subscription behavior.",
    "TransferContact is documented for TASK and EMAIL contacts only; this package does not claim broad voice-call or chat transfer coverage.",
    "Queue selection, contact-flow design, assignment, outbound consent, participant token custody, chat transcript retention, and handoff timing remain SDK-user configuration.",
  ],
  metadata: {
    channelCoverage: {
      taskContact: "typed-create",
      chatContact: "typed-start",
      participantMessages: "typed-selected",
      participantEvents: "typed-selected",
      participantTranscript: "typed-read",
      participantAttachments: "generated-full-surface",
      taskEmailTransfer: "typed-transfer",
      fullConnectFamilyApiOperations: "generated-per-operation-functions",
      emailContact: "generated-full-surface",
      outboundChatContact: "generated-full-surface",
      outboundEmailContact: "generated-full-surface",
      outboundSmsWhatsappContact: "generated-full-surface-where-present-in-official-models",
      chatStreaming: "generated-full-surface",
      queuedCallbackStop: "generated-full-surface",
      voiceCallTransfer: "generated-full-surface-where-present-in-official-models",
      outboundVoiceContact: "generated-full-surface",
      callback: "generated-full-surface-where-present-in-official-models",
      outboundCampaigns: "generated-full-surface",
      webRtcContactLifecycle: "generated-full-surface",
      chatTransfer: "generated-full-surface-where-present-in-official-models",
      appIntegrations: "generated-full-surface",
      customerProfiles: "generated-full-surface",
      qConnect: "generated-full-surface",
      wisdom: "generated-full-surface",
    },
    fullProviderApiVerification: {
      provider: "amazon-connect-family",
      apiVersion: AMAZON_CONNECT_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-17",
      coverageArtifact: "docs/provider-coverage/amazon-connect-full-api-2026-06-17.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/amazon-connect-full-api-2026-06-17.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/amazon-connect-full-api-2026-06-17.functions.json",
      officialModelCount: AMAZON_CONNECT_FULL_API_MODEL_COUNT,
      documentedOperationCount: AMAZON_CONNECT_FULL_API_OPERATION_COUNT,
      implementedOperationCount: AMAZON_CONNECT_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: AMAZON_CONNECT_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
