import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";
import type { EbaySelectedApiOperation } from "./contracts.js";

export const EBAY_SELECTED_API_VERIFICATION_DATE = "2026-06-18";
export const EBAY_SELECTED_API_OPERATION_COUNT = 45;
export const EBAY_SELECTED_API_GENERATED_FUNCTION_COUNT = 45;
export const EBAY_SELECTED_API_PATH_COUNT = 34;

export const ebaySelectedApiSpecs = [
  {
    api: "sell.fulfillment",
    title: "Fulfillment API",
    version: "v1.20.7",
    docsUrl: "https://developer.ebay.com/develop/api/sell/fulfillment_api",
    specUrl: "https://developer.ebay.com/api-docs/master/sell/fulfillment/openapi/3/sell_fulfillment_v1_oas3.json",
    operationCount: 15,
    pathCount: 14,
  },
  {
    api: "commerce.message",
    title: "Message API",
    version: "1.0.0",
    docsUrl: "https://developer.ebay.com/api-docs/commerce/message/resources/methods",
    specUrl: "https://developer.ebay.com/api-docs/master/commerce/message/openapi/3/commerce_message_v1_oas3.json",
    operationCount: 5,
    pathCount: 5,
  },
  {
    api: "commerce.notification",
    title: "Notification API",
    version: "v1.6.7",
    docsUrl: "https://developer.ebay.com/api-docs/commerce/notification/resources/methods",
    specUrl: "https://developer.ebay.com/api-docs/master/commerce/notification/openapi/3/commerce_notification_v1_oas3.json",
    operationCount: 21,
    pathCount: 12,
  },
  {
    api: "developer.key-management",
    title: "Key Management API",
    version: "v1.0.0",
    docsUrl: "https://developer.ebay.com/api-docs/developer/key-management/resources/methods",
    specUrl: "https://developer.ebay.com/api-docs/master/developer/key-management/openapi/3/developer_key_management_v1_oas3.json",
    operationCount: 3,
    pathCount: 2,
  },
  {
    api: "commerce.identity",
    title: "Identity API",
    version: "v2.0.0",
    docsUrl: "https://developer.ebay.com/api-docs/commerce/identity/resources/user/methods/getUser",
    specUrl: "https://developer.ebay.com/api-docs/master/commerce/identity/openapi/3/commerce_identity_v1_oas3.json",
    operationCount: 1,
    pathCount: 1,
  },
] as const;

export const ebaySelectedApiOperationCatalog: readonly EbaySelectedApiOperation[] = [
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "getOrder", functionName: "getOrder", method: "GET", path: "/order/{orderId}", resource: "order" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "getOrders", functionName: "searchOrders", method: "GET", path: "/order", resource: "order" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "issueRefund", functionName: "issueRefund", method: "POST", path: "/order/{order_id}/issue_refund", resource: "order" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "createShippingFulfillment", functionName: "createShippingFulfillment", method: "POST", path: "/order/{orderId}/shipping_fulfillment", resource: "shipping_fulfillment" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "getShippingFulfillment", functionName: "getShippingFulfillment", method: "GET", path: "/order/{orderId}/shipping_fulfillment/{fulfillmentId}", resource: "shipping_fulfillment" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "getShippingFulfillments", functionName: "getShippingFulfillments", method: "GET", path: "/order/{orderId}/shipping_fulfillment", resource: "shipping_fulfillment" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "getPaymentDispute", functionName: "getPaymentDispute", method: "GET", path: "/payment_dispute/{payment_dispute_id}", resource: "payment_dispute" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "fetchEvidenceContent", functionName: "fetchPaymentDisputeEvidenceContent", method: "GET", path: "/payment_dispute/{payment_dispute_id}/fetch_evidence_content", resource: "payment_dispute" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "getActivities", functionName: "getPaymentDisputeActivities", method: "GET", path: "/payment_dispute/{payment_dispute_id}/activity", resource: "payment_dispute" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "getPaymentDisputeSummaries", functionName: "searchPaymentDisputes", method: "GET", path: "/payment_dispute_summary", resource: "payment_dispute" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "contestPaymentDispute", functionName: "contestPaymentDispute", method: "POST", path: "/payment_dispute/{payment_dispute_id}/contest", resource: "payment_dispute" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "acceptPaymentDispute", functionName: "acceptPaymentDispute", method: "POST", path: "/payment_dispute/{payment_dispute_id}/accept", resource: "payment_dispute" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "uploadEvidenceFile", functionName: "uploadPaymentDisputeEvidenceFile", method: "POST", path: "/payment_dispute/{payment_dispute_id}/upload_evidence_file", resource: "payment_dispute" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "addEvidence", functionName: "addPaymentDisputeEvidence", method: "POST", path: "/payment_dispute/{payment_dispute_id}/add_evidence", resource: "payment_dispute" },
  { api: "sell.fulfillment", specUrl: ebaySelectedApiSpecs[0].specUrl, operationId: "updateEvidence", functionName: "updatePaymentDisputeEvidence", method: "POST", path: "/payment_dispute/{payment_dispute_id}/update_evidence", resource: "payment_dispute" },
  { api: "commerce.message", specUrl: ebaySelectedApiSpecs[1].specUrl, operationId: "bulkUpdateConversation", functionName: "bulkUpdateConversations", method: "POST", path: "/bulk_update_conversation", resource: "conversation" },
  { api: "commerce.message", specUrl: ebaySelectedApiSpecs[1].specUrl, operationId: "getConversation", functionName: "getConversation", method: "GET", path: "/conversation/{conversation_id}", resource: "conversation" },
  { api: "commerce.message", specUrl: ebaySelectedApiSpecs[1].specUrl, operationId: "getConversations", functionName: "getConversations", method: "GET", path: "/conversation", resource: "conversation" },
  { api: "commerce.message", specUrl: ebaySelectedApiSpecs[1].specUrl, operationId: "sendMessage", functionName: "sendMessage", method: "POST", path: "/send_message", resource: "conversation" },
  { api: "commerce.message", specUrl: ebaySelectedApiSpecs[1].specUrl, operationId: "updateConversation", functionName: "updateConversation", method: "POST", path: "/update_conversation", resource: "conversation" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "getConfig", functionName: "getNotificationConfig", method: "GET", path: "/config", resource: "config" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "updateConfig", functionName: "updateNotificationConfig", method: "PUT", path: "/config", resource: "config" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "createDestination", functionName: "createNotificationDestination", method: "POST", path: "/destination", resource: "destination" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "deleteDestination", functionName: "deleteNotificationDestination", method: "DELETE", path: "/destination/{destination_id}", resource: "destination" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "getDestination", functionName: "getNotificationDestination", method: "GET", path: "/destination/{destination_id}", resource: "destination" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "getDestinations", functionName: "getNotificationDestinations", method: "GET", path: "/destination", resource: "destination" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "updateDestination", functionName: "updateNotificationDestination", method: "PUT", path: "/destination/{destination_id}", resource: "destination" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "getPublicKey", functionName: "getNotificationPublicKey", method: "GET", path: "/public_key/{public_key_id}", resource: "public_key" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "createSubscription", functionName: "createNotificationSubscription", method: "POST", path: "/subscription", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "createSubscriptionFilter", functionName: "createNotificationSubscriptionFilter", method: "POST", path: "/subscription/{subscription_id}/filter", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "deleteSubscription", functionName: "deleteNotificationSubscription", method: "DELETE", path: "/subscription/{subscription_id}", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "deleteSubscriptionFilter", functionName: "deleteNotificationSubscriptionFilter", method: "DELETE", path: "/subscription/{subscription_id}/filter/{filter_id}", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "disableSubscription", functionName: "disableNotificationSubscription", method: "POST", path: "/subscription/{subscription_id}/disable", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "enableSubscription", functionName: "enableNotificationSubscription", method: "POST", path: "/subscription/{subscription_id}/enable", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "getSubscription", functionName: "getNotificationSubscription", method: "GET", path: "/subscription/{subscription_id}", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "getSubscriptionFilter", functionName: "getNotificationSubscriptionFilter", method: "GET", path: "/subscription/{subscription_id}/filter/{filter_id}", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "getSubscriptions", functionName: "getNotificationSubscriptions", method: "GET", path: "/subscription", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "testSubscription", functionName: "testNotificationSubscription", method: "POST", path: "/subscription/{subscription_id}/test", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "updateSubscription", functionName: "updateNotificationSubscription", method: "PUT", path: "/subscription/{subscription_id}", resource: "subscription" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "getTopic", functionName: "getNotificationTopic", method: "GET", path: "/topic/{topic_id}", resource: "topic" },
  { api: "commerce.notification", specUrl: ebaySelectedApiSpecs[2].specUrl, operationId: "getTopics", functionName: "getNotificationTopics", method: "GET", path: "/topic", resource: "topic" },
  { api: "developer.key-management", specUrl: ebaySelectedApiSpecs[3].specUrl, operationId: "createSigningKey", functionName: "createSigningKey", method: "POST", path: "/signing_key", resource: "signing_key" },
  { api: "developer.key-management", specUrl: ebaySelectedApiSpecs[3].specUrl, operationId: "getSigningKey", functionName: "getSigningKey", method: "GET", path: "/signing_key/{signing_key_id}", resource: "signing_key" },
  { api: "developer.key-management", specUrl: ebaySelectedApiSpecs[3].specUrl, operationId: "getSigningKeys", functionName: "getSigningKeys", method: "GET", path: "/signing_key", resource: "signing_key" },
  { api: "commerce.identity", specUrl: ebaySelectedApiSpecs[4].specUrl, operationId: "getUser", functionName: "getUser", method: "GET", path: "/user/", resource: "user" },
];

export const ebaySelectedApiFunctionCatalog = ebaySelectedApiOperationCatalog.map((operation) => operation.functionName);

export function ebayMarketplaceOperationAlias(functionName: string): `ebay.${string}` {
  return `ebay.${functionName}`;
}

export const ebayMarketplaceProviderManifest = defineProviderPackage({
  id: "marketplace.ebay",
  name: "eBay Marketplace",
  packageName: "@cognidesk/integration-marketplace-ebay",
  provider: "ebay",
  category: "marketplace",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is limited to selected eBay marketplace support primitives: Sell Fulfillment order, shipping fulfillment, refund, and payment-dispute operations; Sell Commerce Message conversations; Commerce Notification destination/subscription/config/public-key operations; notification challenges; and signed notification parsing.",
      "The selected REST slice now covers every documented operation in the currently implemented Fulfillment, Commerce Message, Commerce Notification, Developer Key Management, and Commerce Identity resource groups, but does not claim full eBay platform coverage.",
      "The package does not implement full eBay API coverage for inventory/listing management, account policy breadth, marketing/promotions, analytics/reporting, taxonomy/metadata, media, translation, buy APIs, finances beyond supported fulfillment dispute routes, Negotiation/Leads/Charity/Media APIs, or Trading/Browse/Finding legacy surfaces.",
      "The Fulfillment API issueRefund path supports eBay HTTP Message Signature headers for EU/UK seller policy, but the SDK user must provide Key Management API signing material or a request signer.",
      "The SDK user owns OAuth grant/scopes, marketplace selection, notification topic and filter policy, public-key cache freshness, refund/dispute authority, outbound messaging policy, consent, redaction, and retention decisions.",
    ],
    evidence: [
      { label: "eBay Sell Fulfillment API", url: "https://developer.ebay.com/develop/api/sell/fulfillment_api" },
      { label: "eBay Digital Signatures for APIs", url: "https://developer.ebay.com/develop/guides/digital-signatures-for-apis" },
      { label: "eBay Key Management API", url: "https://developer.ebay.com/api-docs/developer/key-management/resources/methods" },
      { label: "eBay Commerce Notification API resources", url: "https://developer.ebay.com/api-docs/commerce/notification/resources/methods" },
      { label: "eBay Commerce Notification API overview", url: "https://developer.ebay.com/api-docs/commerce/notification/overview.html" },
      { label: "eBay Notification getPublicKey", url: "https://developer.ebay.com/api-docs/commerce/notification/resources/public_key/methods/getPublicKey" },
      { label: "eBay OAuth client credentials grant flow", url: "https://developer.ebay.com/develop/guides-v2/authorization#the-client-credentials-grant-flow" },
      { label: "eBay Commerce Message API", url: "https://developer.ebay.com/api-docs/commerce/message/resources/methods" },
      { label: "eBay OpenAPI specifications", url: "https://developer.ebay.com/api-docs/static/gs_take-advantage-of-openapi.html" },
      { label: "eBay Fulfillment OpenAPI 3 JSON", url: ebaySelectedApiSpecs[0].specUrl },
      { label: "eBay Commerce Message OpenAPI 3 JSON", url: ebaySelectedApiSpecs[1].specUrl },
      { label: "eBay Commerce Notification OpenAPI 3 JSON", url: ebaySelectedApiSpecs[2].specUrl },
      { label: "eBay Developer Key Management OpenAPI 3 JSON", url: ebaySelectedApiSpecs[3].specUrl },
      { label: "eBay Commerce Identity OpenAPI 3 JSON", url: ebaySelectedApiSpecs[4].specUrl },
    ],
  },
  credentialRequirements: [
    {
      id: "ebay-oauth-access-token",
      label: "eBay OAuth user access token",
      description: "Server-side OAuth user token with SDK-user-selected Sell, Commerce Message, Identity, and Notification scopes.",
      scopes: [
        "https://api.ebay.com/oauth/api_scope/sell.fulfillment",
        "https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly",
        "https://api.ebay.com/oauth/api_scope/commerce.message",
        "https://api.ebay.com/oauth/api_scope/commerce.identity.readonly",
        "https://api.ebay.com/oauth/api_scope/commerce.notification.subscription",
      ],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "ebay-application-access-token",
      label: "eBay application access token",
      description: "Client-credentials OAuth token with https://api.ebay.com/oauth/api_scope for Notification public-key retrieval.",
      scopes: ["https://api.ebay.com/oauth/api_scope"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "ebay-client-id",
      label: "eBay application client ID",
      description: "Application keyset client ID owned by the SDK user for OAuth and notification ownership metadata.",
      required: true,
    },
    {
      id: "ebay-client-secret",
      label: "eBay application client secret",
      description: "Application keyset client secret kept server-side by the SDK user for OAuth token lifecycle operations.",
      required: true,
    },
    {
      id: "ebay-marketplace-id",
      label: "eBay marketplace ID",
      description: "SDK-user-selected marketplace such as EBAY_US or EBAY_DE, forwarded through X-EBAY-C-MARKETPLACE-ID where supported.",
      required: true,
    },
    {
      id: "ebay-notification-verification-token",
      label: "eBay notification verification token",
      description: "Destination verification token used to answer eBay challenge_code requests for notification endpoints.",
      required: true,
    },
    {
      id: "ebay-digital-signature-key",
      label: "eBay digital signature keypair",
      description: "Key Management API private key and public-key JWE required for issueRefund when EU/UK seller or SDK policy requires HTTP Message Signatures.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive eBay notifications",
      description: "Validates eBay notification endpoint challenges and parses signed Notification API events for SDK-user-owned marketplace workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "ebayNotification", label: "eBay Notification" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read eBay marketplace records",
      description: "Reads eBay seller orders, shipping fulfillments, payment disputes, message conversations, account profile details, and notification destinations/subscriptions.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "ebayOrder", label: "eBay Order" },
        { kind: "ebayShippingFulfillment", label: "eBay Shipping Fulfillment" },
        { kind: "ebayPaymentDispute", label: "eBay Payment Dispute" },
        { kind: "ebayConversation", label: "eBay Conversation" },
        { kind: "ebayUser", label: "eBay User" },
        { kind: "ebayNotificationDestination", label: "eBay Notification Destination" },
        { kind: "ebayNotificationSubscription", label: "eBay Notification Subscription" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search eBay marketplace records",
      description: "Searches orders, payment disputes, and message conversations with SDK-user-supplied eBay filters and pagination.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "ebayOrder", label: "eBay Order" },
        { kind: "ebayPaymentDispute", label: "eBay Payment Dispute" },
        { kind: "ebayConversation", label: "eBay Conversation" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update eBay marketplace records",
      description: "Updates eBay conversations, payment-dispute evidence or outcomes, and notification destination/subscription lifecycle when SDK-user policy permits marketplace mutations.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "ebayConversation", label: "eBay Conversation" },
        { kind: "ebayPaymentDispute", label: "eBay Payment Dispute" },
        { kind: "ebayNotificationDestination", label: "eBay Notification Destination" },
        { kind: "ebayNotificationSubscription", label: "eBay Notification Subscription" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "delete-provider-object",
      label: "Delete eBay marketplace resources",
      description: "Deletes notification destinations, subscriptions, and filters only when the SDK user's marketplace policy allows lifecycle changes.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "ebayNotificationDestination", label: "eBay Notification Destination" },
        { kind: "ebayNotificationSubscription", label: "eBay Notification Subscription" },
      ],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      capability: "create-provider-object",
      label: "Create eBay fulfillment and message records",
      description: "Creates shipping fulfillments, buyer/seller messages, refunds, and payment-dispute actions only when SDK-user policy allows.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "ebayShippingFulfillment", label: "eBay Shipping Fulfillment" },
        { kind: "ebayMessage", label: "eBay Message" },
        { kind: "ebayRefund", label: "eBay Refund" },
        { kind: "ebayNotificationDestination", label: "eBay Notification Destination" },
        { kind: "ebayNotificationSubscription", label: "eBay Notification Subscription" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "send",
      label: "Send eBay marketplace messages",
      description: "Sends supported Commerce Message API messages to eBay conversations selected by the SDK user's workflow.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "ebayMessage", label: "eBay Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "marketplace.notification-signature",
      label: "Validate eBay notification signatures",
      description: "Decodes X-EBAY-SIGNATURE, retrieves or accepts the SDK-user-cached public key, and verifies ECDSA/SHA1 payload signatures before parsing.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "ebaySignedNotification", label: "eBay Signed Notification" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      capability: "marketplace.digital-signature",
      label: "Sign regulated eBay refund requests",
      description: "Adds Content-Digest, Signature, Signature-Input, and X-EBAY-SIGNATURE-KEY headers to issueRefund when EU/UK seller policy requires eBay HTTP Message Signatures.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "ebaySignedRequest", label: "eBay Signed Request" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
      extension: true,
    },
    {
      capability: "marketplace.notification-challenge",
      label: "Answer eBay notification challenges",
      description: "Computes the SHA-256 challengeResponse from challenge code, verification token, and endpoint URL for eBay destination setup.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "ebayNotificationChallenge", label: "eBay Notification Challenge" }],
      requiresCredential: true,
      extension: true,
    },
  ],
  operations: ebaySelectedApiOperationCatalog.map((operation) => ({
    alias: ebayMarketplaceOperationAlias(operation.functionName),
    providerOperation: `${operation.api}.${operation.operationId}`,
    capability: capabilityForEbayOperation(operation),
    providerObject: `ebay.${operation.resource}`,
    label: operation.functionName,
    description: `Selected eBay ${operation.api} support-slice operation ${operation.operationId}.`,
    extension: true,
    requiresCredential: true,
    sideEffect: operation.method !== "GET",
    exposesSensitiveData: true,
    changesWorkflow: operation.method !== "GET",
    metadata: {
      api: operation.api,
      operationId: operation.operationId,
      method: operation.method,
      path: operation.path,
      specUrl: operation.specUrl,
    },
  })),
  privacyNotes: [
    "eBay orders, buyer/seller conversations, shipping fulfillments, disputes, refunds, notifications, and account profile records can contain customer data, addresses, item details, and internal support context.",
    "OAuth tokens, keyset secrets, notification verification tokens, public-key caches, and gateway shared secrets stay server-side; Studio receives only readiness and capability metadata.",
  ],
  limitations: [
    "The SDK user chooses marketplaces, OAuth flows, scopes, notification topics, subscription filters, operator visibility, outbound messaging policy, refund/dispute rules, retention, consent, and redaction.",
    "Some eBay APIs are entitlement, marketplace, scope, topic, or sandbox limited; this package exposes typed REST foundations and does not decide whether a seller is eligible for a specific action.",
    "The issueRefund method is fail-closed when EU/UK seller or SDK policy requires digital signatures and no eBay request signer or Key Management API signing key is configured.",
    "Notification signature verification requires a valid eBay public key retrieved by key ID from the Notification API or a SDK-user-provided verifier/cache implementation.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://developer.ebay.com/api-docs",
    implementation: {
      strategy: "direct-support-slice",
      selectedApiCount: ebaySelectedApiSpecs.length,
      checkedAt: EBAY_SELECTED_API_VERIFICATION_DATE,
      officialUtilityPackagesChecked: [
        {
          package: "digital-signature-nodejs-sdk",
          version: "3.0.1",
          repository: "https://github.com/eBay/digital-signature-nodejs-sdk",
          decision: "not-adopted-current-local-signer-is-smaller",
        },
        {
          package: "event-notification-nodejs-sdk",
          version: "1.0.3",
          repository: "https://github.com/eBay/event-notification-nodejs-sdk",
          decision: "not-adopted-current-local-verifier-is-smaller",
        },
      ],
      communityPackagesChecked: [
        {
          package: "ebay-api",
          version: "9.5.2",
          repository: "https://github.com/hendt/ebay-api",
          decision: "not-adopted-community-client-not-official-default",
        },
      ],
    },
    supportSlice: {
      source: "official-ebay-openapi-selected-rest-contracts",
      verifiedAt: EBAY_SELECTED_API_VERIFICATION_DATE,
      specs: ebaySelectedApiSpecs.map((spec) => ({
        api: spec.api,
        version: spec.version,
        specUrl: spec.specUrl,
        operationCount: spec.operationCount,
        pathCount: spec.pathCount,
      })),
      allowlist: ebaySelectedApiOperationCatalog.map((operation) => ({
        alias: ebayMarketplaceOperationAlias(operation.functionName),
        api: operation.api,
        operationId: operation.operationId,
        method: operation.method,
        path: operation.path,
      })),
    },
    fulfillmentDocs: "https://developer.ebay.com/api-docs/sell/fulfillment/overview.html",
    notificationDocs: "https://developer.ebay.com/api-docs/commerce/notification/overview.html",
    channelCoverage: {
      orders: "typed-read-search",
      shippingFulfillments: "typed-create-read-list",
      refunds: "typed-create",
      paymentDisputes: "typed-read-search-update",
      paymentDisputeEvidence: "typed-read-upload-add-update",
      conversations: "typed-read-search-update",
      conversationBulkUpdate: "typed-update",
      messages: "typed-send",
      userProfile: "typed-read",
      notificationConfig: "typed-read-update",
      notificationDestinations: "typed-create-read-list-update-delete",
      notificationSubscriptions: "typed-create-read-list-update-enable-disable-test-delete",
      notificationFilters: "typed-create-read-delete",
      notificationTopics: "typed-read-list",
      notificationChallenge: "typed-response",
      notificationSignatures: "typed-verify",
      digitalSignatures: "typed-sign",
      keyManagementSigningKeys: "typed-create-read-list",
      inventoryMarketingAnalyticsBuyApis: "provider-supported-not-typed",
    },
    generatedProviderSliceVerification: {
      provider: "ebay-selected-rest",
      apiVersion: ebaySelectedApiSpecs.map((spec) => `${spec.api}:${spec.version}`).join(", "),
      verifiedAt: EBAY_SELECTED_API_VERIFICATION_DATE,
      coverageArtifact: "docs/provider-coverage/ebay-selected-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/ebay-selected-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/ebay-selected-api-2026-06-18.functions.json",
      documentedPathCount: EBAY_SELECTED_API_PATH_COUNT,
      documentedOperationCount: EBAY_SELECTED_API_OPERATION_COUNT,
      implementedOperationCount: EBAY_SELECTED_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: EBAY_SELECTED_API_GENERATED_FUNCTION_COUNT,
    },
  },
});

function capabilityForEbayOperation(operation: EbaySelectedApiOperation) {
  const searchOperations = new Set([
    "getOrders",
    "getPaymentDisputeSummaries",
    "getConversations",
    "getDestinations",
    "getSubscriptions",
    "getSigningKeys",
    "getTopics",
  ]);
  const createOperations = new Set([
    "createShippingFulfillment",
    "issueRefund",
    "createDestination",
    "createSubscription",
    "createSubscriptionFilter",
    "createSigningKey",
  ]);

  if (operation.operationId === "sendMessage") return "send";
  if (operation.method === "GET") {
    return searchOperations.has(operation.operationId) ? "search-provider-object" : "read-provider-object";
  }
  if (operation.method === "DELETE") return "delete-provider-object";
  if (createOperations.has(operation.operationId)) return "create-provider-object";
  return "update-provider-object";
}
