import { defineIntegrationProviderPackage } from "@cognidesk/integration-kit";

export const sesEmailProviderManifest = defineIntegrationProviderPackage({
  id: "email.ses",
  name: "Amazon SES",
  packageName: "@cognidesk/integration-email-ses",
  provider: "ses",
  category: "email",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is the Cognidesk normalized support-email adapter surface backed by AWS SDK v3 SES clients.",
      "The raw AWS SDK clients are exposed for SDK-user controlled advanced provider operations; Cognidesk does not re-export a generated full SES API clone.",
    ],
    evidence: [
      { label: "AWS SDK for JavaScript v3 SESv2 client", url: "https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-sesv2" },
      { label: "AWS SDK for JavaScript v3 SES classic client", url: "https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-ses" },
      { label: "Amazon SES API v2", url: "https://docs.aws.amazon.com/ses/latest/APIReference-V2/Welcome.html" },
      { label: "Amazon SES event publishing", url: "https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-activity.html" },
      { label: "Amazon SNS signature verification", url: "https://docs.aws.amazon.com/sns/latest/dg/sns-verify-signature-of-message.html" },
    ],
  },
  credentialRequirements: [
    {
      id: "aws-credentials",
      label: "AWS credentials",
      description: "AWS credentials resolved by the AWS SDK default chain or explicitly supplied by the SDK user.",
      required: true,
      scopes: ["ses:SendEmail", "ses:GetAccount", "ses:ListEmailIdentities", "ses:DeleteSuppressedDestination"],
      metadata: { scopeKind: "provider-permission-labels" },
    },
    {
      id: "aws-region",
      label: "AWS region",
      description: "AWS Region for SES operations.",
      required: true,
    },
    {
      id: "ses-sns-verification",
      label: "SNS signature verification",
      description: "Verifier used when fail-closed SNS notification verification is required.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Parse SES/SNS events",
      description: "Parses SES delivery, bounce, complaint, and receiving notifications from SNS/SQS payloads.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "sesEvent", label: "SES Event" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send SES email",
      description: "Sends support email through AWS SDK v3 SESv2.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "sesMessage", label: "SES Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read SES account resources",
      description: "Reads SES account readiness, identities, templates, configuration sets, and suppression state.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "sesAccount", label: "SES Account" },
        { kind: "sesIdentity", label: "SES Identity" },
        { kind: "sesSuppressedDestination", label: "SES Suppressed Destination" },
        { kind: "deliveryStatus", label: "Delivery Status" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Manage SES suppressions",
      description: "Deletes suppression-list entries when SDK-user policy permits.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "sesSuppressedDestination", label: "SES Suppressed Destination" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
  ],
  operations: [
    { alias: "email.send", capability: "send", providerObject: "sesMessage", sideEffect: true, exposesSensitiveData: true },
    { alias: "email.deliveryStatus.read", capability: "read-provider-object", providerObject: "deliveryStatus", exposesSensitiveData: true },
    { alias: "ses.snsNotification.receive", capability: "receive", providerObject: "sesEvent", extension: true, exposesSensitiveData: true },
    { alias: "ses.account.read", capability: "read-provider-object", providerObject: "sesAccount", extension: true },
    { alias: "ses.identities.list", capability: "read-provider-object", providerObject: "sesIdentity", extension: true },
    { alias: "ses.suppressedDestination.delete", capability: "update-provider-object", providerObject: "sesSuppressedDestination", extension: true, sideEffect: true, changesWorkflow: true },
  ],
  privacyNotes: [
    "SES email bodies, recipients, sender identities, headers, tags, templates, configuration sets, delivery events, and raw MIME content can contain customer data.",
    "AWS credentials, SNS certificates, and SQS credentials stay server-side and are represented only as readiness state.",
  ],
  limitations: [
    "SES is not a mailbox product and does not expose mailbox-style message history.",
    "The SDK user owns regions, IAM policy, sender identities, suppression policy, configuration sets, event routing, SNS verification, retention, and outbound approval.",
  ],
  metadata: {
    implementation: {
      strategy: "official-sdk",
      sdkPackages: ["@aws-sdk/client-sesv2", "@aws-sdk/client-ses"],
      sdkVersionRange: "^3.1073.0",
      verifiedPackageVersion: "3.1073.0",
      verifiedAt: "2026-06-21",
      manifestImport: "no-sdk-client-initialization",
      integrationKitStatus: "implemented",
    },
    channelCoverage: {
      sendEmail: "provider-supported-via-official-sdk",
      rawMimeSend: "provider-supported-via-official-sdk",
      accountReadiness: "provider-supported-via-official-sdk",
      identities: "provider-supported-via-official-sdk",
      suppressions: "provider-supported-via-official-sdk",
      snsEvents: "typed-parse",
      mailboxStyleRead: "not-covered",
      fullProviderApiClone: "not-covered",
    },
    rawClientEscapeHatch: "AWS SDK SESv2Client and optional SESClient exposed from createSesEmailClient().rawClients",
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
