import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const amazonMarketplaceOperationAliases = {
  refreshAccessToken: "amazon.refreshAccessToken",
  createRestrictedDataToken: "amazon.createRestrictedDataToken",
  getOrders: "amazon.getOrders",
  getOrder: "amazon.getOrder",
  getOrderBuyerInfo: "amazon.getOrderBuyerInfo",
  getOrderItems: "amazon.getOrderItems",
  getOrderItemsBuyerInfo: "amazon.getOrderItemsBuyerInfo",
  searchOrdersV2026: "amazon.searchOrdersV2026",
  getOrderV2026: "amazon.getOrderV2026",
  getSolicitationActionsForOrder: "amazon.getSolicitationActionsForOrder",
  createProductReviewAndSellerFeedbackSolicitation: "amazon.createProductReviewAndSellerFeedbackSolicitation",
  getMarketplaceParticipations: "amazon.getMarketplaceParticipations",
  getDestinations: "amazon.getDestinations",
  getDestination: "amazon.getDestination",
  createSubscription: "amazon.createSubscription",
  getSubscription: "amazon.getSubscription",
  deleteSubscription: "amazon.deleteSubscription",
  parseNotificationWebhook: "amazon.parseNotificationWebhook",
} as const;

export const amazonMarketplaceProviderManifest = defineProviderPackage({
  id: "marketplace.amazon",
  name: "Amazon Marketplace",
  packageName: "@cognidesk/marketplace-amazon",
  provider: "amazon",
  category: "marketplace",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is limited to Cognidesk marketplace support primitives, not full Amazon SP-API ownership.",
      "The official Amazon JavaScript SDK is the preferred raw-client escape hatch, but this package keeps local helpers for RDT and normalized support operations because the SDK README notes RDT requires an extra step.",
      "Manifest/runtime exports do not expose Cognidesk-generated full-provider SP-API clones.",
      "Orders v0 remains available for existing SDK callers while Amazon's removal window remains relevant; v2026 order helpers are exposed for migration flows.",
    ],
    evidence: [
      { label: "Amazon official SP-API JavaScript SDK", url: "https://github.com/amzn/selling-partner-api-sdk" },
      { label: "Amazon prebuilt JavaScript SDK tutorial", url: "https://developer-docs.amazon.com/sp-api/docs/automate-your-sp-api-calls-using-a-prebuilt-javascript-sdk" },
      { label: "Amazon SP-API Orders v0 reference", url: "https://developer-docs.amazon.com/sp-api/reference/orders-v0" },
      { label: "Amazon SP-API Orders v2026-01-01 reference", url: "https://developer-docs.amazon.com/sp-api/reference/orders-v2026-01-01" },
      { label: "Amazon SP-API Restricted Data Token", url: "https://developer-docs.amazon.com/sp-api/reference/createrestricteddatatoken" },
      { label: "Amazon SP-API Notifications API", url: "https://developer-docs.amazon.com/sp-api/docs/notifications-api" },
    ],
  },
  credentialRequirements: [
    {
      id: "amazon-lwa-client",
      label: "Amazon LWA client credentials",
      description: "Login with Amazon client ID and secret owned by the SDK user for SP-API token refresh.",
      required: true,
    },
    {
      id: "amazon-lwa-token",
      label: "Amazon LWA refresh or access token",
      description: "Seller-authorized refresh/access token for role-gated SP-API calls, or grantless token material for Notifications API operations.",
      required: true,
    },
    {
      id: "amazon-aws-role-region",
      label: "Amazon SP-API AWS role and region",
      description: "Optional IAM role/region and SigV4 material for SDK users who operate through legacy or gateway signing paths.",
      required: false,
    },
    {
      id: "amazon-marketplace-id",
      label: "Amazon marketplace ID",
      description: "SDK-user-selected Amazon marketplace such as ATVPDKIKX0DER or A1PA6795UKMFR9.",
      required: true,
    },
    {
      id: "amazon-notification-destination",
      label: "Amazon notification destination",
      description: "Notifications API destination, SQS/EventBridge routing, and SDK-user webhook gateway metadata.",
      required: true,
    },
    {
      id: "amazon-notification-signature",
      label: "Amazon notification verification",
      description: "SDK-user-provided verifier, shared secret, or gateway signature policy for fail-closed notification ingestion.",
      required: true,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Amazon marketplace notifications",
      description: "Parses SP-API notification payloads from SQS, EventBridge, or SDK-user webhooks after configured verification succeeds.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "amazonNotification", label: "Amazon Notification" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Amazon marketplace records",
      description: "Reads seller orders, order items, buyer information where authorized, solicitation metadata, seller participation, and notification configuration.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "amazonOrder", label: "Amazon Order" },
        { kind: "amazonOrderItem", label: "Amazon Order Item" },
        { kind: "amazonBuyerInfo", label: "Amazon Buyer Info" },
        { kind: "amazonSolicitation", label: "Amazon Solicitation" },
        { kind: "amazonSellerAccount", label: "Amazon Seller Account" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Amazon marketplace records",
      description: "Searches orders and notification resources with SDK-user-supplied marketplace, date, status, and pagination filters.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "amazonOrder", label: "Amazon Order" },
        { kind: "amazonNotificationSubscription", label: "Amazon Notification Subscription" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Amazon support actions",
      description: "Creates review/feedback solicitations and notification subscriptions only when the SDK user's marketplace policy allows outbound actions.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "amazonSolicitation", label: "Amazon Solicitation" },
        { kind: "amazonNotificationSubscription", label: "Amazon Notification Subscription" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "send",
      label: "Send Amazon buyer solicitations",
      description: "Sends supported Solicitations API review/feedback requests chosen by the SDK user's workflow.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "amazonSolicitation", label: "Amazon Solicitation" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "marketplace.notification-signature",
      label: "Validate Amazon notification ingress",
      description: "Requires a SDK-user verifier, shared secret, or gateway signature policy before returning normalized Amazon notification payloads.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "amazonVerifiedNotification", label: "Amazon Verified Notification" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      capability: "marketplace.sigv4",
      label: "Sign Amazon SP-API requests",
      description: "Optionally signs SP-API REST requests with AWS SigV4 for SDK users that still operate signed gateways or legacy authorization paths.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "amazonSignedRequest", label: "Amazon Signed Request" }],
      requiresCredential: true,
      extension: true,
    },
  ],
  operations: [
    { alias: amazonMarketplaceOperationAliases.refreshAccessToken, providerOperation: "lwa.refreshAccessToken", capability: "read-provider-object", label: "Refresh Amazon LWA access token", extension: true, requiresCredential: true },
    { alias: amazonMarketplaceOperationAliases.createRestrictedDataToken, providerOperation: "tokens.createRestrictedDataToken", capability: "create-provider-object", label: "Create Amazon restricted data token", extension: true, requiresCredential: true, exposesSensitiveData: true },
    { alias: amazonMarketplaceOperationAliases.getOrders, providerOperation: "ordersV0.getOrders", capability: "search-provider-object", label: "Search Amazon orders", extension: true, requiresCredential: true, exposesSensitiveData: true },
    { alias: amazonMarketplaceOperationAliases.getOrder, providerOperation: "ordersV0.getOrder", capability: "read-provider-object", label: "Read Amazon order", extension: true, requiresCredential: true, exposesSensitiveData: true },
    { alias: amazonMarketplaceOperationAliases.getOrderBuyerInfo, providerOperation: "ordersV0.getOrderBuyerInfo", capability: "read-provider-object", label: "Read Amazon order buyer info", extension: true, requiresCredential: true, exposesSensitiveData: true },
    { alias: amazonMarketplaceOperationAliases.getOrderItems, providerOperation: "ordersV0.getOrderItems", capability: "read-provider-object", label: "Read Amazon order items", extension: true, requiresCredential: true, exposesSensitiveData: true },
    { alias: amazonMarketplaceOperationAliases.getOrderItemsBuyerInfo, providerOperation: "ordersV0.getOrderItemsBuyerInfo", capability: "read-provider-object", label: "Read Amazon order item buyer info", extension: true, requiresCredential: true, exposesSensitiveData: true },
    { alias: amazonMarketplaceOperationAliases.searchOrdersV2026, providerOperation: "ordersV2026.searchOrders", capability: "search-provider-object", label: "Search Amazon Orders v2026", extension: true, requiresCredential: true, exposesSensitiveData: true },
    { alias: amazonMarketplaceOperationAliases.getOrderV2026, providerOperation: "ordersV2026.getOrder", capability: "read-provider-object", label: "Read Amazon Orders v2026 order", extension: true, requiresCredential: true, exposesSensitiveData: true },
    { alias: amazonMarketplaceOperationAliases.getSolicitationActionsForOrder, providerOperation: "solicitations.getActionsForOrder", capability: "read-provider-object", label: "Read Amazon solicitation actions", extension: true, requiresCredential: true },
    { alias: amazonMarketplaceOperationAliases.createProductReviewAndSellerFeedbackSolicitation, providerOperation: "solicitations.createProductReviewAndSellerFeedback", capability: "send", label: "Create Amazon review and seller feedback solicitation", extension: true, requiresCredential: true, sideEffect: true, changesWorkflow: true },
    { alias: amazonMarketplaceOperationAliases.getMarketplaceParticipations, providerOperation: "sellers.getMarketplaceParticipations", capability: "read-provider-object", label: "Read Amazon marketplace participations", extension: true, requiresCredential: true },
    { alias: amazonMarketplaceOperationAliases.getDestinations, providerOperation: "notifications.getDestinations", capability: "search-provider-object", label: "List Amazon notification destinations", extension: true, requiresCredential: true },
    { alias: amazonMarketplaceOperationAliases.getDestination, providerOperation: "notifications.getDestination", capability: "read-provider-object", label: "Read Amazon notification destination", extension: true, requiresCredential: true },
    { alias: amazonMarketplaceOperationAliases.createSubscription, providerOperation: "notifications.createSubscription", capability: "create-provider-object", label: "Create Amazon notification subscription", extension: true, requiresCredential: true, sideEffect: true, changesWorkflow: true },
    { alias: amazonMarketplaceOperationAliases.getSubscription, providerOperation: "notifications.getSubscription", capability: "read-provider-object", label: "Read Amazon notification subscription", extension: true, requiresCredential: true },
    { alias: amazonMarketplaceOperationAliases.deleteSubscription, providerOperation: "notifications.deleteSubscription", capability: "update-provider-object", label: "Delete Amazon notification subscription", extension: true, requiresCredential: true, sideEffect: true, changesWorkflow: true },
    { alias: amazonMarketplaceOperationAliases.parseNotificationWebhook, providerOperation: "notifications.parseWebhook", capability: "receive", label: "Parse Amazon notification webhook", extension: true, requiresCredential: true, exposesSensitiveData: true },
  ],
  privacyNotes: [
    "Amazon marketplace orders, order items, buyer information, seller account records, solicitations, and notifications can contain customer data, addresses, identifiers, and support context.",
    "LWA secrets, refresh tokens, access tokens, AWS role/signing material, notification shared secrets, and verifier logic stay server-side; Studio receives only readiness and capability metadata.",
  ],
  limitations: [
    "The SDK user chooses marketplaces, roles, restricted-data-token policy, notification topics, outbound solicitation rules, operator visibility, retention, consent, and redaction.",
    "Some SP-API operations require role approval, restricted data tokens, marketplace availability, or grantless authorization; this package exposes typed support foundations and does not decide seller eligibility.",
    "Amazon notification transports vary by destination; this package fails closed unless the SDK user configures a verifier, gateway signature, or shared-secret check appropriate to their ingress path.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    implementation: {
      strategy: "official-sdk-plus-support-slice",
      sdkPackage: "@amazon-sp-api-release/amazon-sp-api-sdk-js",
      sdkVersionChecked: "1.9.0",
      sdkModifiedAt: "2026-05-29T13:03:51.597Z",
      sdkRepository: "https://github.com/amzn/selling-partner-api-sdk",
      caveats: [
        "The npm package has no root types metadata; this package uses a local typed facade for raw SDK loading.",
        "RDT support remains local because the SDK README says some APIs need an extra RDT step.",
      ],
    },
    supportSlice: {
      source: "local-reviewed-support-operations",
      verifiedAt: "2026-06-21",
      allowlist: Object.values(amazonMarketplaceOperationAliases),
    },
    channelCoverage: {
      lwaTokenRefresh: "typed-token-refresh",
      restrictedDataTokens: "typed-create",
      ordersV0: "typed-read-search",
      ordersV2026: "typed-read-search",
      buyerInfoRdt: "typed-read-restricted",
      orderItems: "typed-read",
      solicitations: "typed-read-create-send",
      sellerParticipation: "typed-read",
      notificationDestinations: "typed-read",
      notificationSubscriptions: "typed-create-read-delete",
      notificationIngress: "typed-verify-parse",
      sigv4Signing: "typed-sign",
      rawSellingPartnerApi: "official-sdk-escape-hatch",
    },
  },
});
