import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { MAILGUN_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  MAILGUN_FULL_API_OPERATION_COUNT,
  MAILGUN_FULL_API_PATH_COUNT,
  MAILGUN_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const mailgunEmailProviderManifest = defineProviderPackage({
  id: "email.mailgun",
  name: "Mailgun",
  packageName: "@cognidesk/integrations",
  provider: "mailgun",
  category: "email",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Mailgun's official public OpenAPI 3.1 API reference.",
      "Typed convenience helpers remain available for support email workflows: sending, MIME sending, inbound route parsing, stored-message reads, legacy Events API searches, domain readiness, domain webhooks, account routes, domain templates, and suppression lookups.",
      "The generated full API surface covers Mailgun Logs, Metrics, account and domain webhooks, broad domain management, IPs/IP pools/warmup, mailing lists, tags, subaccounts, users, keys, alerts, allowlist, and suppression mutation/import endpoints from the official OpenAPI artifact.",
      "The SDK user still owns domain selection, region selection, route/webhook policy, retention, redaction, outbound approval, rate limiting, pagination, retry/backoff, and which generated operations are exposed to operators.",
    ],
    evidence: [
      { label: "Mailgun OpenAPI specification", url: "https://documentation.mailgun.com/_spec/docs/mailgun/api-reference/send/mailgun.json?download" },
      { label: "Mailgun Messages API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/messages" },
      { label: "Mailgun Events API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/events" },
      { label: "Mailgun Logs API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/logs" },
      { label: "Mailgun Metrics API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/metrics" },
      { label: "Mailgun Routes API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/routes" },
      { label: "Mailgun Domain Webhooks API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/domain-webhooks" },
      { label: "Mailgun Account Webhooks API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/account-webhooks" },
      { label: "Mailgun Domains API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/domains" },
      { label: "Mailgun Bounces API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/bounces" },
      { label: "Mailgun Receiving Messages via HTTP", url: "https://documentation.mailgun.com/docs/mailgun/user-manual/receive-forward-store/receive-http" },
    ],
  },
  credentialRequirements: [
    {
      id: "mailgun-api-key",
      label: "Mailgun API key",
      description: "Server-side Mailgun API key used for Sending, Events, Domains, and Webhooks API calls.",
      required: true,
    },
    {
      id: "mailgun-domain",
      label: "Mailgun sending domain",
      description: "SDK-user-selected Mailgun domain used for outbound email, inbound routes, and event searches.",
      required: true,
    },
    {
      id: "mailgun-webhook-signing-key",
      label: "Mailgun webhook signing key",
      description: "Webhook signing key used to verify Mailgun event callbacks with HMAC-SHA256.",
      required: false,
    },
    {
      id: "mailgun-region",
      label: "Mailgun region",
      description: "Mailgun API region selected by the SDK user, usually US or EU.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Mailgun webhooks",
      description: "Parses and verifies Mailgun inbound, delivery, engagement, and failure event callbacks.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "mailgunEvent", label: "Mailgun Event" },
        { kind: "mailgunInboundMessage", label: "Mailgun Inbound Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Mailgun email",
      description: "Sends email through Mailgun's HTTP Sending API when SDK-user policy permits outbound contact.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "mailgunMessage", label: "Mailgun Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Build Mailgun outbound payloads",
      description: "Builds Mailgun form, MIME, template, and variable payloads for SDK-user approval workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "mailgunEmailDraft", label: "Mailgun Email Draft" }],
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Mailgun message metadata",
      description: "Associates support replies using Mailgun message IDs, headers, tags, variables, and event metadata.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "mailgunThreadReference", label: "Mailgun Thread Reference" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "attach",
      label: "Send Mailgun attachments",
      description: "Supports attachment metadata and MIME sending surfaces governed by the SDK user's channel policy.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "mailgunAttachment", label: "Mailgun Attachment" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Mailgun messages and domains",
      description: "Reads stored messages, domain metadata, and webhook configuration through Mailgun APIs.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "mailgunStoredMessage", label: "Mailgun Stored Message" },
        { kind: "mailgunDomain", label: "Mailgun Domain" },
        { kind: "mailgunRoute", label: "Mailgun Route" },
        { kind: "mailgunDomainTemplate", label: "Mailgun Domain Template" },
        { kind: "mailgunWebhook", label: "Mailgun Domain Webhook" },
        { kind: "mailgunSuppressionRecord", label: "Mailgun Suppression Record" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Mailgun events",
      description: "Searches Mailgun Events API with SDK-user-supplied retention-aware filters.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "mailgunEvent", label: "Mailgun Event" },
        { kind: "mailgunRoute", label: "Mailgun Route" },
        { kind: "mailgunDomainTemplate", label: "Mailgun Domain Template" },
        { kind: "mailgunWebhook", label: "Mailgun Domain Webhook" },
        { kind: "mailgunSuppressionRecord", label: "Mailgun Suppression Record" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Mailgun email bodies, recipients, sender addresses, headers, tags, variables, event payloads, routes, and attachments can contain customer data.",
    "Mailgun API keys and webhook signing keys stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "The SDK user chooses domains, routes, templates, tracking, webhook endpoints, retention, redaction, and outbound approval policy.",
    "Mailgun stored message and event availability depends on the SDK user's plan, region, and retention settings.",
    "This package does not provide replay-cache storage for webhook deduplication; SDK users must configure storage and retention policy.",
    "This package does not decide when to send, auto-reply, attach files, track engagement, or expose inbound content to operators.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://documentation.mailgun.com/docs/mailgun",
    channelCoverage: {
      sendEmail: "typed-send",
      sendMime: "typed-send",
      inboundRouteParsing: "typed-parse",
      storedMessages: "typed-read",
      eventsApi: "typed-search-legacy",
      domains: "typed-read",
      domainWebhooks: "typed-list",
      routes: "typed-list",
      suppressions: "typed-read",
      domainTemplates: "typed-list",
      logsApi: "generated-per-operation-functions",
      metricsApi: "generated-per-operation-functions",
      webhooksMutation: "generated-per-operation-functions",
      mailingLists: "generated-per-operation-functions",
      ipPoolsAndWarmup: "generated-per-operation-functions",
      subaccountsUsersKeysAlerts: "generated-per-operation-functions",
      suppressionsMutationImport: "generated-per-operation-functions",
      fullApiOperations: "generated-per-operation-functions",
    },
    fullProviderApiVerification: {
      provider: "mailgun",
      apiVersion: MAILGUN_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/mailgun-full-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/mailgun-full-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/mailgun-full-api-2026-06-18.functions.json",
      documentedPathCount: MAILGUN_FULL_API_PATH_COUNT,
      documentedOperationCount: MAILGUN_FULL_API_OPERATION_COUNT,
      implementedOperationCount: MAILGUN_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: MAILGUN_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
});
