import { defineIntegrationProviderPackage } from "@cognidesk/integration-kit";

export const mailgunEmailProviderManifest = defineIntegrationProviderPackage({
  id: "email.mailgun",
  name: "Mailgun",
  packageName: "@cognidesk/integration-email-mailgun",
  provider: "mailgun",
  category: "email",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is the Cognidesk normalized support-email adapter surface backed by the official Mailgun SDK.",
      "The raw mailgun.js client is exposed for SDK-user controlled advanced provider operations; Cognidesk does not re-export a generated full Mailgun API clone.",
    ],
    evidence: [
      { label: "mailgun.js package", url: "https://github.com/mailgun/mailgun.js" },
      { label: "Mailgun Messages API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/messages" },
      { label: "Mailgun Events API", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/events" },
      { label: "Mailgun Webhooks", url: "https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/domain-webhooks" },
    ],
  },
  credentialRequirements: [
    {
      id: "mailgun-api-key",
      label: "Mailgun API key",
      description: "Server-side Mailgun API key used by the official mailgun.js client.",
      required: true,
    },
    {
      id: "mailgun-domain",
      label: "Mailgun sending domain",
      description: "Mailgun domain selected by the SDK user for outbound, event, and stored-message operations.",
      required: true,
    },
    {
      id: "mailgun-webhook-signing-key",
      label: "Mailgun webhook signing key",
      description: "Signing key used to verify Mailgun event callbacks.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Mailgun events",
      description: "Parses and verifies Mailgun inbound, delivery, engagement, and failure callbacks.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "mailgunEvent", label: "Mailgun Event" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Mailgun email",
      description: "Sends support email through the official Mailgun SDK.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "mailgunMessage", label: "Mailgun Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Mailgun message and domain resources",
      description: "Reads support-scoped stored messages, domain state, webhooks, and event delivery status.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "mailgunStoredMessage", label: "Mailgun Stored Message" },
        { kind: "mailgunDomain", label: "Mailgun Domain" },
        { kind: "mailgunWebhook", label: "Mailgun Webhook" },
        { kind: "deliveryStatus", label: "Delivery Status" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Mailgun events",
      description: "Searches Mailgun event history through mailgun.js for retention-aware support workflows.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "mailgunEvent", label: "Mailgun Event" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
  ],
  operations: [
    { alias: "email.receive", capability: "receive", providerObject: "emailMessage", exposesSensitiveData: true },
    { alias: "email.send", capability: "send", providerObject: "emailMessage", sideEffect: true, exposesSensitiveData: true },
    { alias: "email.reply.send", capability: "send", providerObject: "emailMessage", sideEffect: true, exposesSensitiveData: true },
    { alias: "email.deliveryStatus.read", capability: "read-provider-object", providerObject: "deliveryStatus", exposesSensitiveData: true },
    { alias: "mailgun.storedMessage.read", capability: "read-provider-object", providerObject: "mailgunStoredMessage", extension: true, exposesSensitiveData: true },
    { alias: "mailgun.domain.read", capability: "read-provider-object", providerObject: "mailgunDomain", extension: true, exposesSensitiveData: true },
    { alias: "mailgun.webhooks.list", capability: "read-provider-object", providerObject: "mailgunWebhook", extension: true },
  ],
  privacyNotes: [
    "Mailgun message bodies, recipients, sender addresses, headers, tags, variables, event payloads, routes, and attachments can contain customer data.",
    "Mailgun API keys and webhook signing keys stay server-side and are represented only as readiness state.",
  ],
  limitations: [
    "The SDK user owns domain selection, route policy, retention, redaction, replay-cache storage, outbound approval, and rate limiting.",
    "Advanced provider operations remain available through the raw mailgun.js client, not as Cognidesk-owned generated operations.",
  ],
  metadata: {
    implementation: {
      strategy: "official-sdk",
      sdkPackage: "mailgun.js",
      sdkVersionRange: "^13.2.0",
      verifiedPackageVersion: "13.2.0",
      verifiedAt: "2026-06-21",
      manifestImport: "no-sdk-client-initialization",
      integrationKitStatus: "implemented",
    },
    channelCoverage: {
      sendEmail: "provider-supported-via-official-sdk",
      sendReply: "provider-supported-via-official-sdk",
      eventSearch: "provider-supported-via-official-sdk",
      storedMessageRead: "provider-supported-via-official-sdk",
      webhooks: "provider-supported-via-official-sdk",
      fullProviderApiClone: "not-covered",
    },
    rawClientEscapeHatch: "mailgun.js IMailgunClient exposed from createMailgunEmailClient().rawClient",
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
