import { defineIntegrationProviderPackage } from "@cognidesk/integration-kit";

export const twilioVoiceProviderManifest = defineIntegrationProviderPackage({
  id: "voice.twilio",
  name: "Twilio Programmable Voice",
  packageName: "@cognidesk/integration-voice-twilio",
  provider: "twilio",
  category: "voice",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Implements normalized call-control, TwiML media stream, webhook, readiness, and raw Twilio helper-client access with the official Twilio Node helper library.",
      "Twilio Voice and Twilio SMS are separate Cognidesk category packages even though they use the same upstream helper library.",
      "Conferences, queues, recordings, transcription lifecycle, SIP trunks, Voice Insights, and ConversationRelay remain available only through raw Twilio client access or future normalized operations.",
    ],
    evidence: [
      { label: "Twilio Node helper library", url: "https://www.npmjs.com/package/twilio" },
      { label: "Twilio Programmable Voice API", url: "https://www.twilio.com/docs/voice/api" },
      { label: "Twilio Call Resource", url: "https://www.twilio.com/docs/voice/api/call-resource" },
      { label: "Twilio webhook security", url: "https://www.twilio.com/docs/usage/webhooks/webhooks-security" },
    ],
  },
  credentialRequirements: [
    {
      id: "twilio-account",
      label: "Twilio Account SID",
      description: "Server-side Twilio Account SID used by the helper library.",
      required: true,
      metadata: { scopeKind: "provider-permission" },
    },
    {
      id: "twilio-rest-api-credentials",
      label: "Twilio REST API credentials",
      description: "Twilio Auth Token or API key credentials used for Voice REST calls.",
      required: true,
      metadata: { scopeKind: "provider-permission" },
    },
    {
      id: "twilio-webhook-auth-token",
      label: "Twilio webhook Auth Token",
      description: "Primary Twilio Auth Token used to validate X-Twilio-Signature webhook requests.",
      required: false,
      metadata: { scopeKind: "provider-permission" },
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive voice webhooks",
      description: "Accepts and parses Twilio Voice webhooks for SDK-user-owned Cognidesk voice handling.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "twilioCall", label: "Twilio Call" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Create outbound calls",
      description: "Creates outbound calls through the Twilio helper library.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "twilioCall", label: "Twilio Call" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Media Stream TwiML",
      description: "Builds TwiML for Cognidesk-owned voice websocket media streams while preserving Twilio track constraints.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "twilioMediaStream", label: "Twilio Media Stream" }],
      requiresCredential: false,
    },
    {
      capability: "transfer",
      label: "Redirect or end calls",
      description: "Redirects or ends active Twilio calls through the Call resource.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "twilioCall", label: "Twilio Call" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      capability: "twilio.webhook-signature",
      label: "Validate Twilio webhooks",
      description: "Validates X-Twilio-Signature for form-encoded Twilio Voice webhooks.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "twilioWebhook", label: "Twilio Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "voice.call.answer",
      providerOperation: "twilio.validateRequest",
      capability: "receive",
      label: "Receive voice webhook",
      providerObject: "twilioCall",
      audiences: ["customer-facing"],
      exposesSensitiveData: true,
    },
    {
      alias: "voice.call.start",
      providerOperation: "calls.create",
      capability: "send",
      label: "Create outbound call",
      providerObject: "twilioCall",
      audiences: ["customer-facing"],
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    },
    {
      alias: "voice.call.redirect",
      providerOperation: "calls(sid).update",
      capability: "transfer",
      label: "Redirect call",
      providerObject: "twilioCall",
      audiences: ["internal-support"],
      sideEffect: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "Phone numbers, call metadata, webhook parameters, and Media Stream audio metadata are exchanged with Twilio.",
    "Twilio credentials stay server-side and are never issued to browsers by this package.",
  ],
  limitations: [
    "Live call readiness depends on the SDK user's Twilio account, voice-capable numbers, regions, webhooks, and account permissions.",
  ],
  metadata: {
    implementation: {
      strategy: "official-sdk",
      sdkPackage: "twilio",
      verifiedVersion: "6.0.2",
      verifiedAt: "2026-06-21",
    },
    sdkClient: {
      export: "getSdkClient",
      coverage: "deprecated-raw-client-alias",
    },
    rawClient: {
      export: "getRawClient",
      coverage: "upstream-sdk",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
