import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { TEAMS_GRAPH_API_GENERATED_FUNCTION_COUNT } from "./graph-api-client.generated.js";
import {
  TEAMS_GRAPH_API_OPERATION_COUNT,
  TEAMS_GRAPH_API_PATH_COUNT,
  TEAMS_GRAPH_API_SPEC_VERSION,
} from "./graph-api-operations.generated.js";

export const teamsWorkplaceProviderManifest = defineProviderPackage({
  id: "workplace.teams",
  name: "Microsoft Teams",
  packageName: "@cognidesk/integrations",
  provider: "teams",
  category: "workplace",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["internal-support", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage includes generated per-operation functions for the Microsoft Graph v1.0 Teams/workplace collaboration slice used by this package: Teams app catalog, chats, communications/calls, group team, joinedTeams, onlineMeetings, presence, teams/channels, teamwork, user teamwork, and subscriptions.",
      "Typed convenience helpers remain available for selected Microsoft Graph Teams support workflows: delegated channel/chat message send, delegated channel replies, channel/chat message list/get/update helpers, delegated current user readiness, change notification clientState validation, and subscription creation.",
      "Normal Teams channel/chat sends require delegated Microsoft Graph permissions; application permissions are reserved by Microsoft for migration/import flows that this package does not implement.",
      "This is not full Microsoft Graph coverage; the complete Graph v1.0 OpenAPI covers many Microsoft 365 services. Mail, files/Drive, calendar, identity, admin, security, and broader Graph resources remain outside this Teams/workplace adapter unless represented in this slice.",
    ],
    evidence: [
      { label: "Microsoft Graph OpenAPI registry", url: "https://github.com/microsoftgraph/msgraph-metadata/blob/master/apis.yaml" },
      { label: "Microsoft Graph v1.0 OpenAPI", url: "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml" },
      { label: "Microsoft Graph send channel message", url: "https://learn.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0" },
      { label: "Microsoft Graph send chat message", url: "https://learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0" },
      { label: "Microsoft Graph send channel reply", url: "https://learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0" },
      { label: "Microsoft Graph list channel messages", url: "https://learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0" },
      { label: "Microsoft Graph list channel replies", url: "https://learn.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0" },
      { label: "Microsoft Graph get chatMessage", url: "https://learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0" },
      { label: "Microsoft Graph update chatMessage", url: "https://learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0" },
      { label: "Microsoft Graph create subscription", url: "https://learn.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0" },
      { label: "Microsoft Graph webhook subscription lifecycle", url: "https://learn.microsoft.com/en-us/graph/change-notifications-delivery-webhooks" },
      { label: "Microsoft Graph cloud communications calls", url: "https://learn.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-1.0" },
      { label: "Microsoft Graph online meetings", url: "https://learn.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0" },
    ],
  },
  credentialRequirements: [
    {
      id: "microsoft-graph-oauth-access-token",
      label: "Microsoft Graph OAuth access token",
      description: "Server-side delegated Microsoft Graph OAuth access token for normal Teams chatMessage sends and /me readiness calls.",
      scopes: [
        "User.Read",
        "ChatMessage.Send",
        "ChannelMessage.Send",
        "Chat.Read",
        "Chat.ReadWrite",
        "ChannelMessage.Read.All",
        "ChannelMessage.Read.Group",
        "ChatMessage.Read.Chat",
        "ChannelMessage.ReadWrite",
      ],
      required: true,
      metadata: {
        scopeKind: "mixed-auth-mode",
        privilegeGuidance: "Normal Teams sends require delegated Microsoft Graph permissions; application permissions and resource-specific consent have narrower documented behavior and admin-consent requirements.",
      },
    },
    {
      id: "microsoft-graph-tenant",
      label: "Microsoft Entra tenant",
      description: "SDK-user-owned tenant where the Teams resources, delegated users, app registration, and consent live.",
      required: true,
    },
    {
      id: "microsoft-graph-app-registration",
      label: "Microsoft Graph app registration",
      description: "SDK-user-owned Microsoft Entra app registration with delegated or application permissions and tenant/admin consent.",
      required: true,
    },
    {
      id: "microsoft-graph-change-notification-client-state",
      label: "Graph change notification clientState",
      description: "SDK-user-owned secret used to validate Microsoft Graph change notification payloads.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Teams change notifications",
      description: "Validates Microsoft Graph change notification clientState values and parses Teams chatMessage notifications for SDK-user-owned workflows.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "teamsChangeNotification", label: "Teams Change Notification" },
        { kind: "teamsChatMessage", label: "Teams Chat Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Teams messages",
      description: "Sends channel or chat messages through Microsoft Graph chatMessage endpoints with delegated permissions when SDK-user policy permits workplace-visible output.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "teamsChatMessage", label: "Teams Chat Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "notify",
      label: "Support internal agent assist",
      description: "Posts SDK-user-routed Teams messages for internal agent-assist, supervisor review, and workplace collaboration flows.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "teamsAgentAssistMessage", label: "Teams Agent Assist Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Teams conversations",
      description: "Associates support context with Teams channel threads, replies, and chat message identifiers selected by SDK-user configuration.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "teamsChatMessage", label: "Teams Chat Message" },
        { kind: "teamsThread", label: "Teams Thread" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Teams messages",
      description: "Reads Teams channel or chat messages where Microsoft Graph permissions, resource-specific consent, and tenant policy allow access.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "teamsChatMessage", label: "Teams Chat Message" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Graph subscriptions",
      description: "Creates Microsoft Graph change-notification subscriptions for SDK-user-selected Teams resources; renewal and deletion lifecycle stays SDK-user-owned.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "teamsGraphSubscription", label: "Microsoft Graph Subscription" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Teams messages",
      description: "Updates Teams chatMessage resources through Microsoft Graph: delegated permissions can update message properties, while application permissions are limited to policyViolation updates.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "teamsChatMessage", label: "Teams Chat Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "teams.change-notification-client-state",
      label: "Validate Graph clientState",
      description: "Validates Microsoft Graph change notification clientState secrets and notification URL validation tokens.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "teamsChangeNotification", label: "Teams Change Notification" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Teams messages, channel identifiers, chat identifiers, user identifiers, mentions, attachments, reactions, hosted content references, and change notification payloads can contain internal support context and customer data.",
    "Microsoft Graph OAuth tokens, app credentials, tenant identifiers, and change notification clientState secrets stay server-side and are represented in Studio only as credential readiness.",
    "Internal visibility, agent-assist routing, transcript use, retention, legal hold, deletion, and escalation policy remain SDK-user-owned Microsoft Teams, Microsoft Purview, and Cognidesk configuration.",
  ],
  limitations: [
    "Available operations depend on the SDK user's Microsoft Entra tenant, Teams licensing, Graph OAuth scopes, delegated versus application permission mode, resource-specific consent, tenant/admin consent, channel membership, and Teams policy.",
    "Normal channel/chat message sends reject application permission mode; Microsoft documents application send permissions for migration/import scenarios, which this package does not implement.",
    "Microsoft Graph channel and chat message APIs are intended for messages people will read; this package does not use Teams as an application log or choose automation volume policy.",
    "This package provides transport, parsing, and readiness helpers only; customer/internal visibility, agent assist, approval, retention, redaction, escalation, and human handoff are SDK-user policy.",
    "Some read and update operations have Graph permission, tenant, national cloud, DLP, federation, and licensing constraints and may be unavailable for a given Teams resource.",
    "The generated Teams/workplace slice exposes Graph subscription renewal/delete/reauthorize operations, while expiration monitoring, encrypted resource data decryption, retry, and reauthorization timing remain SDK-user integration responsibilities.",
  ],
  metadata: {
    channelCoverage: {
      channelMessages: "typed-send-list-get-update",
      channelReplies: "typed-send-list",
      chatMessages: "typed-send-list-get-update",
      graphSubscriptions: "typed-create",
      changeNotifications: "typed-validate-parse",
      currentUser: "typed-read",
      graphTeamsWorkplaceSlice: "generated-per-operation-functions",
      subscriptionRenewDelete: "generated-full-slice",
      teamsChatsChannelsAppsCallsMeetingsPresence: "generated-full-slice",
      applicationMigrationSend: "provider-supported-not-typed",
    },
    generatedProviderApiVerification: {
      provider: "microsoft-graph-teams-workplace-slice",
      apiVersion: TEAMS_GRAPH_API_SPEC_VERSION,
      verifiedAt: "2026-06-17",
      coverageArtifact: "docs/provider-coverage/teams-graph-api-2026-06-17.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/teams-graph-api-2026-06-17.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/teams-graph-api-2026-06-17.functions.json",
      documentedPathCount: TEAMS_GRAPH_API_PATH_COUNT,
      documentedOperationCount: TEAMS_GRAPH_API_OPERATION_COUNT,
      implementedOperationCount: TEAMS_GRAPH_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: TEAMS_GRAPH_API_GENERATED_FUNCTION_COUNT,
      slice: "Microsoft Graph v1.0 Teams/workplace collaboration paths only; not full Microsoft Graph.",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
