import type { ProviderManifestInput } from "@cognidesk/integration-kit";
import { defineIntegrationProviderPackage } from "../../provider-manifest.js";

// Metadata-only legacy catalog input. The executable Teams adapter lives in
// integrations/workplace/teams and is not re-exported from @cognidesk/integrations.

export const teamsWorkplaceOperationAliases = {
  receive: "workplace.message.receive",
  threadRead: "workplace.thread.read",
  messageSend: "workplace.message.send",
  messageReply: "workplace.message.reply",
  messageUpdate: "workplace.message.update",
  notificationSend: "workplace.notification.send",
  userRead: "workplace.user.read",
  channelMessagesList: "teams.channelMessages.list",
  channelRepliesList: "teams.channelReplies.list",
  channelMessageGet: "teams.channelMessage.get",
  chatMessagesList: "teams.chatMessages.list",
  chatMessageGet: "teams.chatMessage.get",
  subscriptionCreate: "teams.subscription.create",
  webhookParse: "teams.webhook.parse",
  rawGraphRequest: "teams.rawGraph.request",
} as const;

export const teamsWorkplaceManifestInput = {
  id: "workplace.teams",
  name: "Microsoft Teams",
  packageName: "@cognidesk/integration-workplace-teams",
  provider: "teams",
  category: "workplace",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["internal-support", "mixed"],
  operations: [
    {
      alias: teamsWorkplaceOperationAliases.receive,
      capability: "receive",
      label: "Receive Teams change notifications",
      providerObject: "teamsChangeNotification",
      exposesSensitiveData: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.threadRead,
      capability: "thread",
      label: "Read Teams thread messages",
      providerObject: "teamsChatMessage",
      exposesSensitiveData: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.messageSend,
      capability: "send",
      label: "Send Teams message",
      providerObject: "teamsChatMessage",
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.messageReply,
      capability: "send",
      label: "Send Teams channel reply",
      providerObject: "teamsChatMessage",
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.messageUpdate,
      capability: "update-provider-object",
      label: "Update Teams message",
      providerObject: "teamsChatMessage",
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.notificationSend,
      capability: "notify",
      label: "Send internal Teams notification",
      providerObject: "teamsAgentAssistMessage",
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.userRead,
      capability: "read-provider-object",
      label: "Read current Microsoft Graph user",
      providerObject: "teamsUser",
      exposesSensitiveData: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.channelMessagesList,
      capability: "read-provider-object",
      label: "List Teams channel messages",
      providerObject: "teamsChatMessage",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.channelRepliesList,
      capability: "thread",
      label: "List Teams channel replies",
      providerObject: "teamsChatMessage",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.channelMessageGet,
      capability: "read-provider-object",
      label: "Get Teams channel message",
      providerObject: "teamsChatMessage",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.chatMessagesList,
      capability: "read-provider-object",
      label: "List Teams chat messages",
      providerObject: "teamsChatMessage",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.chatMessageGet,
      capability: "read-provider-object",
      label: "Get Teams chat message",
      providerObject: "teamsChatMessage",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.subscriptionCreate,
      capability: "create-provider-object",
      label: "Create Microsoft Graph Teams subscription",
      providerObject: "teamsGraphSubscription",
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.webhookParse,
      capability: "receive",
      label: "Parse Teams webhook",
      providerObject: "teamsChangeNotification",
      exposesSensitiveData: true,
      extension: true,
    },
    {
      alias: teamsWorkplaceOperationAliases.rawGraphRequest,
      capability: "read-provider-object",
      label: "Run raw Microsoft Graph request",
      providerObject: "teamsGraphResource",
      exposesSensitiveData: true,
      extension: true,
      metadata: { rawClientEscapeHatch: true },
    },
  ],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage includes SDK-backed Microsoft Graph Teams support workflows: channel and chat messages, channel replies, message updates, subscriptions, current-user readiness, and change notifications.",
      "The package uses @microsoft/microsoft-graph-client for Graph calls and keeps Cognidesk-normalized helper methods and operation handlers.",
      "This is not full Microsoft Graph coverage. Files/Drive, calendar, identity/admin, security, calls, meetings, app catalog breadth, and broader Graph resources remain outside this Teams adapter.",
    ],
    evidence: [
      { label: "Microsoft Graph JavaScript client", url: "https://www.npmjs.com/package/@microsoft/microsoft-graph-client" },
      { label: "Microsoft Graph send channel message", url: "https://learn.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0" },
      { label: "Microsoft Graph send chat message", url: "https://learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0" },
      { label: "Microsoft Graph send channel reply", url: "https://learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0" },
      { label: "Microsoft Graph list channel messages", url: "https://learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0" },
      { label: "Microsoft Graph list channel replies", url: "https://learn.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0" },
      { label: "Microsoft Graph get chatMessage", url: "https://learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0" },
      { label: "Microsoft Graph update chatMessage", url: "https://learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0" },
      { label: "Microsoft Graph create subscription", url: "https://learn.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0" },
      { label: "Microsoft Graph webhook subscription lifecycle", url: "https://learn.microsoft.com/en-us/graph/change-notifications-delivery-webhooks" },
    ],
  },
  credentialRequirements: [
    {
      id: "microsoft-graph-oauth-access-token",
      label: "Microsoft Graph OAuth access token",
      description: "Server-side delegated Microsoft Graph OAuth access token for normal Teams chatMessage sends and /me readiness calls.",
      scopes: [
        "User.Read",
        "ChatMessage.Send",
        "ChannelMessage.Send",
        "Chat.Read",
        "Chat.ReadWrite",
        "ChannelMessage.Read.All",
        "ChannelMessage.Read.Group",
        "ChatMessage.Read.Chat",
        "ChannelMessage.ReadWrite",
      ],
      required: true,
      metadata: {
        scopeKind: "mixed-auth-mode",
        privilegeGuidance: "Normal Teams sends require delegated Microsoft Graph permissions; application permissions and resource-specific consent have narrower documented behavior and admin-consent requirements.",
      },
    },
    {
      id: "microsoft-graph-tenant",
      label: "Microsoft Entra tenant",
      description: "SDK-user-owned tenant where the Teams resources, delegated users, app registration, and consent live.",
      required: true,
    },
    {
      id: "microsoft-graph-app-registration",
      label: "Microsoft Graph app registration",
      description: "SDK-user-owned Microsoft Entra app registration with delegated or application permissions and tenant/admin consent.",
      required: true,
    },
    {
      id: "microsoft-graph-change-notification-client-state",
      label: "Graph change notification clientState",
      description: "SDK-user-owned secret used to validate Microsoft Graph change notification payloads.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Teams change notifications",
      description: "Validates Microsoft Graph change notification clientState values and parses Teams chatMessage notifications for SDK-user-owned workflows.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "teamsChangeNotification", label: "Teams Change Notification" },
        { kind: "teamsChatMessage", label: "Teams Chat Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Teams messages",
      description: "Sends channel or chat messages through Microsoft Graph chatMessage endpoints with delegated permissions when SDK-user policy permits workplace-visible output.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "teamsChatMessage", label: "Teams Chat Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "notify",
      label: "Support internal agent assist",
      description: "Posts SDK-user-routed Teams messages for internal agent-assist, supervisor review, and workplace collaboration flows.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "teamsAgentAssistMessage", label: "Teams Agent Assist Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Teams conversations",
      description: "Associates support context with Teams channel threads, replies, and chat message identifiers selected by SDK-user configuration.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "teamsChatMessage", label: "Teams Chat Message" },
        { kind: "teamsThread", label: "Teams Thread" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Teams messages",
      description: "Reads Teams channel or chat messages where Microsoft Graph permissions, resource-specific consent, and tenant policy allow access.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "teamsChatMessage", label: "Teams Chat Message" },
        { kind: "teamsUser", label: "Microsoft Graph User" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Graph subscriptions",
      description: "Creates Microsoft Graph change-notification subscriptions for SDK-user-selected Teams resources; renewal and deletion lifecycle stays SDK-user-owned.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "teamsGraphSubscription", label: "Microsoft Graph Subscription" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Teams messages",
      description: "Updates Teams chatMessage resources through Microsoft Graph: delegated permissions can update message properties, while application permissions are limited to policyViolation updates.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "teamsChatMessage", label: "Teams Chat Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "Teams messages, channel identifiers, chat identifiers, user identifiers, mentions, attachments, reactions, hosted content references, and change notification payloads can contain internal support context and customer data.",
    "Microsoft Graph OAuth tokens, app credentials, tenant identifiers, and change notification clientState secrets stay server-side and are represented in Studio only as credential readiness.",
    "Internal visibility, agent-assist routing, transcript use, retention, legal hold, deletion, and escalation policy remain SDK-user-owned Microsoft Teams, Microsoft Purview, and Cognidesk configuration.",
  ],
  limitations: [
    "Available operations depend on the SDK user's Microsoft Entra tenant, Teams licensing, Graph OAuth scopes, delegated versus application permission mode, resource-specific consent, tenant/admin consent, channel membership, and Teams policy.",
    "Normal channel/chat message sends reject application permission mode; Microsoft documents application send permissions for migration/import scenarios, which this package does not implement.",
    "Microsoft Graph channel and chat message APIs are intended for messages people will read; this package does not use Teams as an application log or choose automation volume policy.",
    "This package provides transport, parsing, and readiness helpers only; customer/internal visibility, agent assist, approval, retention, redaction, escalation, and human handoff are SDK-user policy.",
    "Subscription renewal, deletion, reauthorization timing, encrypted resource data decryption, and retry policy remain SDK-user integration responsibilities.",
  ],
  metadata: {
    implementation: {
      strategy: "official-sdk",
      sdkPackage: "@microsoft/microsoft-graph-client",
      rawClientEscapeHatch: "rawClient",
      manifestOnlyExport: "@cognidesk/integration-workplace-teams/manifest",
    },
    channelCoverage: {
      channelMessages: "sdk-owned-send-list-get-update",
      channelReplies: "sdk-owned-send-list",
      chatMessages: "sdk-owned-send-list-get-update",
      graphSubscriptions: "sdk-owned-create",
      changeNotifications: "typed-validate-parse",
      currentUser: "sdk-owned-read",
      applicationMigrationSend: "provider-supported-not-typed",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
} as const satisfies ProviderManifestInput;

export const teamsWorkplaceProviderManifest = defineIntegrationProviderPackage(teamsWorkplaceManifestInput);
