import { defineIntegrationProviderPackage } from "@cognidesk/integration-kit";
import {
  TIKTOK_HOST_CLIENT_SUPPORT_SLICE,
  TIKTOK_SELECTED_OPERATION_COUNT,
} from "./selected-operations.js";

export const tiktokSocialProviderManifest = defineIntegrationProviderPackage({
  id: "social.tiktok",
  name: "TikTok Social",
  packageName: "@cognidesk/integration-social-tiktok",
  provider: "tiktok",
  category: "social",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  credentialRequirements: [
    {
      id: "tiktok-client-key",
      label: "TikTok client key",
      description: "TikTok for Developers app client key owned and configured by the SDK user.",
      required: true,
    },
    {
      id: "tiktok-client-secret",
      label: "TikTok client secret",
      description: "Server-side TikTok app secret used for OAuth and webhook signature validation.",
      required: true,
    },
    {
      id: "tiktok-access-token",
      label: "TikTok access token",
      description: "User or client access token used by the built-in TikTok REST adapter or an injected TikTok provider client for approved TikTok APIs.",
      scopes: ["user.info.basic", "user.info.profile", "video.list"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "tiktok-account-id",
      label: "TikTok Open ID or business account ID",
      description: "Authorized user's open_id and/or TikTok Business account ID used to scope profile, video, and comment operations.",
      required: true,
    },
    {
      id: "tiktok-webhook-signature",
      label: "Webhook signature validation",
      description: "TikTok-Signature validation with the SDK user's client secret before webhook JSON is processed.",
      required: true,
    },
    {
      id: "tiktok-webhook-callback",
      label: "TikTok webhook callback URL registration",
      description: "SDK-user-confirmed HTTPS callback URL registration for enabled TikTok webhook products.",
      required: true,
    },
    {
      id: "tiktok-scopes",
      label: "TikTok scopes and product approvals",
      description: "SDK-user-reviewed Login Kit, Display API, Research API, and/or Business API scopes needed for enabled support features; content upload/publish scopes are not used by this adapter.",
      scopes: [
        "user.info.basic",
        "user.info.profile",
        "user.info.stats",
        "video.list",
        "research.data.basic",
      ],
      required: true,
      metadata: {
        scopeKind: "mixed-auth-mode",
        oauthScopes: ["user.info.basic", "user.info.profile", "user.info.stats", "video.list", "research.data.basic"],
        privilegeGuidance: "TikTok Business API comment operations require separate Business API account/product approval; these OAuth scopes do not grant Business comment access by themselves.",
      },
    },
  ],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is limited to selected TikTok Display API user/video reads, Research API comment reads, Business API comment operations, posting-status reads, and webhook signature parsing for SDK-user-owned support/review workflows.",
      "Runtime provider calls use the built-in REST adapter when credentials are configured; hosts may inject a TikTok provider client override.",
      "The package does not implement a general TikTok direct-message inbox and does not cover the full TikTok product surface for Content Posting, Share Kit, Commercial Content, Data Portability, Shop, analytics, tester/launch, or full Business Center administration.",
    ],
    evidence: [
      { label: "TikTok Display API get started", url: "https://developers.tiktok.com/doc/display-api-get-started/" },
      { label: "TikTok user info API", url: "https://developers.tiktok.com/doc/tiktok-api-v2-get-user-info" },
      { label: "TikTok video list API", url: "https://developers.tiktok.com/doc/tiktok-api-v2-video-list" },
      { label: "TikTok Research video comments API", url: "https://developers.tiktok.com/doc/research-api-specs-query-video-comments" },
      { label: "TikTok webhooks overview", url: "https://developers.tiktok.com/doc/webhooks-overview/" },
      { label: "TikTok webhook signature verification", url: "https://developers.tiktok.com/doc/webhooks-verification" },
      { label: "TikTok Content Posting status API", url: "https://developers.tiktok.com/doc/content-posting-api-reference-get-video-status" },
    ],
  },
  capabilities: [
    {
      capability: "receive",
      label: "Receive TikTok webhooks",
      description: "Validates TikTok-Signature and parses TikTok event payloads for SDK-user-owned support workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "tiktokWebhook", label: "TikTok Webhook" },
        { kind: "tiktokEvent", label: "TikTok Event" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Build TikTok comment replies",
      description: "Builds TikTok Business comment reply payloads without deciding outbound or moderation policy.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "tiktokCommentReplyDraft", label: "TikTok Comment Reply Draft" }],
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use TikTok comments as threads",
      description: "Associates TikTok videos, comments, replies, and webhook IDs with Cognidesk conversation policy selected by SDK users.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "tiktokVideo", label: "TikTok Video" },
        { kind: "tiktokComment", label: "TikTok Comment" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read TikTok profile, videos, and comments",
      description: "Reads TikTok Display API profile/videos, Research API comments, and Business API comment resources through the configured REST adapter or provider client where approved.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "tiktokUser", label: "TikTok User" },
        { kind: "tiktokVideo", label: "TikTok Video" },
        { kind: "tiktokComment", label: "TikTok Comment" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "List TikTok videos and comments",
      description: "Lists approved TikTok videos and comments with SDK-user-supplied fields and pagination through the configured REST adapter or provider client.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "tiktokVideo", label: "TikTok Video" },
        { kind: "tiktokComment", label: "TikTok Comment" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "social.comment-reply",
      label: "Reply to TikTok Business comments",
      description: "Calls TikTok Business API comment reply primitives through the configured REST adapter or provider client only when the SDK user has the relevant Business account and approvals.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "tiktokComment", label: "TikTok Comment" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      capability: "social.webhook-signature",
      label: "Validate TikTok webhook signatures",
      description: "Validates the TikTok-Signature header using HMAC-SHA256 over timestamp and raw body.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "tiktokSignedWebhook", label: "TikTok Signed Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "TikTok open IDs, usernames, profile metadata, video IDs, captions, comments, replies, webhook IDs, and event payloads can contain customer data.",
    "Client secrets, access tokens, business account IDs, and webhook validation settings stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "TikTok's public developer APIs do not expose a general customer-service direct-message inbox; this package intentionally does not provide a generic DM send/read client.",
    "Comment reply operations require TikTok API for Business account access and approvals; Display API and Research API access are separate TikTok products with separate scopes and eligibility.",
    "Available operations depend on the SDK user's app review, regional availability, callback URL registration, scopes, product approvals, rate limits, Business account ownership, and TikTok platform policy.",
    "TikTok direct-message lead APIs are Business lead surfaces, not a generic customer-service DM inbox for this adapter.",
    "Provider API calls use the built-in REST adapter when accessToken is configured; providerClient injection remains available as an override.",
    "Consent, outbound-contact policy, conversation continuity, human escalation, moderation, retention, redaction, and deletion behavior are SDK-user configuration.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    channelCoverage: {
      displayProfileVideos: "provider-rest-adapter-read-list",
      researchVideoComments: "provider-rest-adapter-query",
      contentPostingStatus: "provider-rest-adapter-read",
      businessComments: "provider-rest-adapter-list-create-reply",
      webhooks: "typed-verify-parse",
      directMessages: "not-covered",
      contentPostingCreate: "not-covered",
      shopAnalyticsCommercialContent: "provider-supported-not-typed",
    },
    docs: [
      "https://developers.tiktok.com/doc/tiktok-api-v2-get-user-info",
      "https://developers.tiktok.com/doc/tiktok-api-v2-video-list",
      "https://developers.tiktok.com/doc/research-api-specs-query-video-comments",
      "https://developers.tiktok.com/doc/webhooks-overview",
      "https://developers.tiktok.com/doc/webhooks-verification",
      "https://business-api.tiktok.com/portal/docs/reply-to-a-comment/v1.3",
    ],
    apiCoverage: {
      ...TIKTOK_HOST_CLIENT_SUPPORT_SLICE.apiCoverage,
      generatedFromOfficialSpec: false,
      machineReadableSpecStatus: "No official public complete TikTok Developers/Business OpenAPI spec was found for this mixed selected surface during this audit.",
      selectedOperationCount: TIKTOK_SELECTED_OPERATION_COUNT,
      implementedOperationCount: TIKTOK_SELECTED_OPERATION_COUNT,
      fullProviderApi: false,
      fullTikTokPlatformCoverage: false,
    },
    implementation: TIKTOK_HOST_CLIENT_SUPPORT_SLICE,
    providerClient: {
      package: "built-in-or-host-provided",
      interface: "TikTokSocialProviderClient",
      importPolicy: "provider-client-override-supported",
      defaultClientPolicy: "provider-rest-adapter-when-configured",
    },
    providerRestAdapterException: TIKTOK_HOST_CLIENT_SUPPORT_SLICE.providerRestAdapterException,
  },
});
