import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { ZENDESK_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  ZENDESK_FULL_API_OPERATION_COUNT,
  ZENDESK_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const zendeskTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.zendesk",
  name: "Zendesk Support",
  packageName: "@cognidesk/integrations",
  provider: "zendesk",
  category: "ticketing",
  trustLevel: "official",
  directions: ["bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Zendesk's official Support API OpenAPI file.",
      "The package keeps typed support helpers for ticket create/read/update/search, ticket comments through ticket create/update/list flows, Upload Files, user and organization reads, webhook listing, current-user readiness, and Cognidesk handoff support workflows.",
    ],
    evidence: [
      { label: "Zendesk Support API OpenAPI", url: "https://developer.zendesk.com/zendesk/oas.yaml" },
      { label: "Zendesk Support Tickets API", url: "https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/" },
      { label: "Zendesk Ticket Comments API", url: "https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_comments/" },
      { label: "Zendesk Ticket Attachments API", url: "https://developer.zendesk.com/api-reference/ticketing/tickets/ticket-attachments/" },
      { label: "Zendesk Users API", url: "https://developer.zendesk.com/api-reference/ticketing/users/users/" },
      { label: "Zendesk Organizations API", url: "https://developer.zendesk.com/api-reference/ticketing/organizations/organizations/" },
      { label: "Zendesk Webhooks API", url: "https://developer.zendesk.com/api-reference/webhooks/webhooks-api/webhooks/" },
    ],
  },
  credentialRequirements: [
    {
      id: "zendesk-instance",
      label: "Zendesk Support instance URL",
      description: "The SDK user's Zendesk Support URL, for example https://example.zendesk.com.",
      required: true,
    },
    {
      id: "zendesk-api-access",
      label: "Zendesk Support API access",
      description: "Server-side OAuth bearer access or API token credentials for the Zendesk Support API. OAuth tokens use read/write scopes; API-token credentials inherit the Zendesk user/admin permissions and are not OAuth-scoped.",
      scopes: ["read", "write"],
      required: true,
      metadata: {
        scopeKind: "mixed-auth-mode",
        oauthScopes: ["read", "write"],
        privilegeGuidance: "OAuth access tokens use Zendesk read/write scopes. API token credentials are governed by the Zendesk user's role, admin settings, and Support permissions.",
      },
    },
  ],
  capabilities: [
    {
      capability: "create-provider-object",
      label: "Create Zendesk tickets",
      description: "Creates Zendesk Support tickets from SDK-user-selected handoff or ticketing workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "zendeskTicket", label: "Zendesk Ticket" }, { kind: "zendeskTicketComment", label: "Zendesk Ticket Comment" }, { kind: "zendeskUpload", label: "Zendesk Upload" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Zendesk tickets",
      description: "Reads Zendesk Support tickets by ticket ID.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "zendeskTicket", label: "Zendesk Ticket" }, { kind: "zendeskTicketComment", label: "Zendesk Ticket Comment" }, { kind: "zendeskUser", label: "Zendesk User" }, { kind: "zendeskOrganization", label: "Zendesk Organization" }, { kind: "zendeskWebhook", label: "Zendesk Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Zendesk tickets",
      description: "Updates Zendesk Support ticket fields, comments, priority, status, assignee, or custom fields.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "zendeskTicket", label: "Zendesk Ticket" }, { kind: "zendeskTicketComment", label: "Zendesk Ticket Comment" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Zendesk tickets and list webhooks",
      description: "Searches Zendesk Support tickets using SDK-user-supplied Support API search queries and lists configured Zendesk webhooks.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "zendeskTicket", label: "Zendesk Ticket" }, { kind: "zendeskWebhook", label: "Zendesk Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Attach support handoff to Zendesk",
      description: "Provides Zendesk ticket operations used by SDK-user-configured human handoff workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "zendeskTicket", label: "Zendesk Ticket" }, { kind: "zendeskTicketComment", label: "Zendesk Ticket Comment" }, { kind: "zendeskUpload", label: "Zendesk Upload" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "Zendesk tickets can contain customer messages, requester details, internal comments, tags, and workflow metadata.",
    "Zendesk API credentials stay server-side and are represented in Studio only as credential readiness.",
  ],
  limitations: [
    "Available fields, brands, forms, triggers, automations, macros, and permissions are owned by the SDK user's Zendesk account.",
    "Ticket routing, requester identity, comment visibility, handoff timing, retention, and outbound-contact policy are SDK-user configuration.",
  ],
  metadata: {
    channelCoverage: {
      fullZendeskSupportApiOperations: "generated-per-operation-functions",
      tickets: "typed-create-read-update-search-and-generated-full-surface",
      ticketComments: "typed-list-and-generated-full-surface",
      uploads: "typed-create-and-generated-full-surface",
      users: "typed-read-and-generated-full-surface",
      organizations: "typed-read-and-generated-full-surface",
      webhooks: "typed-list-and-generated-full-surface",
      currentUserReadiness: "typed-read-and-generated-full-surface",
      attachmentLifecycle: "generated-full-surface",
      sideConversationsMacrosViewsTriggers: "generated-full-surface",
      webhookMutationSigningSecrets: "generated-full-surface",
    },
    fullProviderApiVerification: {
      provider: "zendesk",
      apiVersion: ZENDESK_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-17",
      coverageArtifact: "docs/provider-coverage/zendesk-full-api-2026-06-17.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/zendesk-full-api-2026-06-17.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/zendesk-full-api-2026-06-17.functions.json",
      documentedOperationCount: ZENDESK_FULL_API_OPERATION_COUNT,
      implementedOperationCount: ZENDESK_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: ZENDESK_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
