// Generated from Discord's official HTTP API v10 OpenAPI preview spec (https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi.json).
// Do not edit by hand; run scripts/generate-discord-http-api.mjs after checking upstream docs.

export const DISCORD_HTTP_API_GENERATED_AT = "2026-06-18";
export const DISCORD_HTTP_API_SPEC_SOURCE = "https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi.json";
export const DISCORD_HTTP_API_DOCS_SOURCE = "https://docs.discord.com/developers/reference";
export const DISCORD_HTTP_API_SPEC_REPOSITORY = "https://github.com/discord/discord-api-spec";
export const DISCORD_HTTP_API_SPEC_VERSION = "10";
export const DISCORD_HTTP_API_OPENAPI_VERSION = "3.1.0";
export const DISCORD_HTTP_API_PATH_COUNT = 150;
export const DISCORD_HTTP_API_OPERATION_COUNT = 242;

export interface DiscordHttpApiOperation {
  uid: string;
  operationId: string;
  functionName: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  summary: string;
  tags: readonly string[];
}

export const DISCORD_HTTP_API_OPERATIONS = JSON.parse("[{\"uid\":\"GET /applications/@me\",\"operationId\":\"get_my_application\",\"functionName\":\"GetMyApplication\",\"method\":\"GET\",\"path\":\"/applications/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /applications/@me\",\"operationId\":\"update_my_application\",\"functionName\":\"UpdateMyApplication\",\"method\":\"PATCH\",\"path\":\"/applications/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}\",\"operationId\":\"get_application\",\"functionName\":\"GetApplication\",\"method\":\"GET\",\"path\":\"/applications/{application_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /applications/{application_id}\",\"operationId\":\"update_application\",\"functionName\":\"UpdateApplication\",\"method\":\"PATCH\",\"path\":\"/applications/{application_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/activity-instances/{instance_id}\",\"operationId\":\"applications_get_activity_instance\",\"functionName\":\"ApplicationsGetActivityInstance\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/activity-instances/{instance_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /applications/{application_id}/attachment\",\"operationId\":\"upload_application_attachment\",\"functionName\":\"UploadApplicationAttachment\",\"method\":\"POST\",\"path\":\"/applications/{application_id}/attachment\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/commands\",\"operationId\":\"list_application_commands\",\"functionName\":\"ListApplicationCommands\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/commands\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /applications/{application_id}/commands\",\"operationId\":\"bulk_set_application_commands\",\"functionName\":\"BulkSetApplicationCommands\",\"method\":\"PUT\",\"path\":\"/applications/{application_id}/commands\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /applications/{application_id}/commands\",\"operationId\":\"create_application_command\",\"functionName\":\"CreateApplicationCommand\",\"method\":\"POST\",\"path\":\"/applications/{application_id}/commands\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/commands/{command_id}\",\"operationId\":\"get_application_command\",\"functionName\":\"GetApplicationCommand\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/commands/{command_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /applications/{application_id}/commands/{command_id}\",\"operationId\":\"delete_application_command\",\"functionName\":\"DeleteApplicationCommand\",\"method\":\"DELETE\",\"path\":\"/applications/{application_id}/commands/{command_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /applications/{application_id}/commands/{command_id}\",\"operationId\":\"update_application_command\",\"functionName\":\"UpdateApplicationCommand\",\"method\":\"PATCH\",\"path\":\"/applications/{application_id}/commands/{command_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/emojis\",\"operationId\":\"list_application_emojis\",\"functionName\":\"ListApplicationEmojis\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/emojis\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /applications/{application_id}/emojis\",\"operationId\":\"create_application_emoji\",\"functionName\":\"CreateApplicationEmoji\",\"method\":\"POST\",\"path\":\"/applications/{application_id}/emojis\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/emojis/{emoji_id}\",\"operationId\":\"get_application_emoji\",\"functionName\":\"GetApplicationEmoji\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/emojis/{emoji_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /applications/{application_id}/emojis/{emoji_id}\",\"operationId\":\"delete_application_emoji\",\"functionName\":\"DeleteApplicationEmoji\",\"method\":\"DELETE\",\"path\":\"/applications/{application_id}/emojis/{emoji_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /applications/{application_id}/emojis/{emoji_id}\",\"operationId\":\"update_application_emoji\",\"functionName\":\"UpdateApplicationEmoji\",\"method\":\"PATCH\",\"path\":\"/applications/{application_id}/emojis/{emoji_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/entitlements\",\"operationId\":\"get_entitlements\",\"functionName\":\"GetEntitlements\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/entitlements\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /applications/{application_id}/entitlements\",\"operationId\":\"create_entitlement\",\"functionName\":\"CreateEntitlement\",\"method\":\"POST\",\"path\":\"/applications/{application_id}/entitlements\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/entitlements/{entitlement_id}\",\"operationId\":\"get_entitlement\",\"functionName\":\"GetEntitlement\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/entitlements/{entitlement_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /applications/{application_id}/entitlements/{entitlement_id}\",\"operationId\":\"delete_entitlement\",\"functionName\":\"DeleteEntitlement\",\"method\":\"DELETE\",\"path\":\"/applications/{application_id}/entitlements/{entitlement_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /applications/{application_id}/entitlements/{entitlement_id}/consume\",\"operationId\":\"consume_entitlement\",\"functionName\":\"ConsumeEntitlement\",\"method\":\"POST\",\"path\":\"/applications/{application_id}/entitlements/{entitlement_id}/consume\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/guilds/{guild_id}/commands\",\"operationId\":\"list_guild_application_commands\",\"functionName\":\"ListGuildApplicationCommands\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/guilds/{guild_id}/commands\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /applications/{application_id}/guilds/{guild_id}/commands\",\"operationId\":\"bulk_set_guild_application_commands\",\"functionName\":\"BulkSetGuildApplicationCommands\",\"method\":\"PUT\",\"path\":\"/applications/{application_id}/guilds/{guild_id}/commands\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /applications/{application_id}/guilds/{guild_id}/commands\",\"operationId\":\"create_guild_application_command\",\"functionName\":\"CreateGuildApplicationCommand\",\"method\":\"POST\",\"path\":\"/applications/{application_id}/guilds/{guild_id}/commands\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/guilds/{guild_id}/commands/permissions\",\"operationId\":\"list_guild_application_command_permissions\",\"functionName\":\"ListGuildApplicationCommandPermissions\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/guilds/{guild_id}/commands/permissions\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/guilds/{guild_id}/commands/{command_id}\",\"operationId\":\"get_guild_application_command\",\"functionName\":\"GetGuildApplicationCommand\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/guilds/{guild_id}/commands/{command_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /applications/{application_id}/guilds/{guild_id}/commands/{command_id}\",\"operationId\":\"delete_guild_application_command\",\"functionName\":\"DeleteGuildApplicationCommand\",\"method\":\"DELETE\",\"path\":\"/applications/{application_id}/guilds/{guild_id}/commands/{command_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /applications/{application_id}/guilds/{guild_id}/commands/{command_id}\",\"operationId\":\"update_guild_application_command\",\"functionName\":\"UpdateGuildApplicationCommand\",\"method\":\"PATCH\",\"path\":\"/applications/{application_id}/guilds/{guild_id}/commands/{command_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions\",\"operationId\":\"get_guild_application_command_permissions\",\"functionName\":\"GetGuildApplicationCommandPermissions\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions\",\"operationId\":\"set_guild_application_command_permissions\",\"functionName\":\"SetGuildApplicationCommandPermissions\",\"method\":\"PUT\",\"path\":\"/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /applications/{application_id}/role-connections/metadata\",\"operationId\":\"get_application_role_connections_metadata\",\"functionName\":\"GetApplicationRoleConnectionsMetadata\",\"method\":\"GET\",\"path\":\"/applications/{application_id}/role-connections/metadata\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /applications/{application_id}/role-connections/metadata\",\"operationId\":\"update_application_role_connections_metadata\",\"functionName\":\"UpdateApplicationRoleConnectionsMetadata\",\"method\":\"PUT\",\"path\":\"/applications/{application_id}/role-connections/metadata\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}\",\"operationId\":\"get_channel\",\"functionName\":\"GetChannel\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}\",\"operationId\":\"delete_channel\",\"functionName\":\"DeleteChannel\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /channels/{channel_id}\",\"operationId\":\"update_channel\",\"functionName\":\"UpdateChannel\",\"method\":\"PATCH\",\"path\":\"/channels/{channel_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/followers\",\"operationId\":\"follow_channel\",\"functionName\":\"FollowChannel\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/followers\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/invites\",\"operationId\":\"list_channel_invites\",\"functionName\":\"ListChannelInvites\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/invites\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/invites\",\"operationId\":\"create_channel_invite\",\"functionName\":\"CreateChannelInvite\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/invites\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/messages\",\"operationId\":\"list_messages\",\"functionName\":\"ListMessages\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/messages\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/messages\",\"operationId\":\"create_message\",\"functionName\":\"CreateMessage\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/messages\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/messages/bulk-delete\",\"operationId\":\"bulk_delete_messages\",\"functionName\":\"BulkDeleteMessages\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/messages/bulk-delete\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/messages/pins\",\"operationId\":\"list_pins\",\"functionName\":\"ListPins\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/messages/pins\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /channels/{channel_id}/messages/pins/{message_id}\",\"operationId\":\"create_pin\",\"functionName\":\"CreatePin\",\"method\":\"PUT\",\"path\":\"/channels/{channel_id}/messages/pins/{message_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/messages/pins/{message_id}\",\"operationId\":\"delete_pin\",\"functionName\":\"DeletePin\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/messages/pins/{message_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/messages/{message_id}\",\"operationId\":\"get_message\",\"functionName\":\"GetMessage\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/messages/{message_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/messages/{message_id}\",\"operationId\":\"delete_message\",\"functionName\":\"DeleteMessage\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/messages/{message_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /channels/{channel_id}/messages/{message_id}\",\"operationId\":\"update_message\",\"functionName\":\"UpdateMessage\",\"method\":\"PATCH\",\"path\":\"/channels/{channel_id}/messages/{message_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/messages/{message_id}/crosspost\",\"operationId\":\"crosspost_message\",\"functionName\":\"CrosspostMessage\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/messages/{message_id}/crosspost\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/messages/{message_id}/reactions\",\"operationId\":\"delete_all_message_reactions\",\"functionName\":\"DeleteAllMessageReactions\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/messages/{message_id}/reactions\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}\",\"operationId\":\"list_message_reactions_by_emoji\",\"functionName\":\"ListMessageReactionsByEmoji\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}\",\"operationId\":\"delete_all_message_reactions_by_emoji\",\"functionName\":\"DeleteAllMessageReactionsByEmoji\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me\",\"operationId\":\"add_my_message_reaction\",\"functionName\":\"AddMyMessageReaction\",\"method\":\"PUT\",\"path\":\"/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me\",\"operationId\":\"delete_my_message_reaction\",\"functionName\":\"DeleteMyMessageReaction\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/{user_id}\",\"operationId\":\"delete_user_message_reaction\",\"functionName\":\"DeleteUserMessageReaction\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/messages/{message_id}/threads\",\"operationId\":\"create_thread_from_message\",\"functionName\":\"CreateThreadFromMessage\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/messages/{message_id}/threads\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /channels/{channel_id}/permissions/{overwrite_id}\",\"operationId\":\"set_channel_permission_overwrite\",\"functionName\":\"SetChannelPermissionOverwrite\",\"method\":\"PUT\",\"path\":\"/channels/{channel_id}/permissions/{overwrite_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/permissions/{overwrite_id}\",\"operationId\":\"delete_channel_permission_overwrite\",\"functionName\":\"DeleteChannelPermissionOverwrite\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/permissions/{overwrite_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/pins\",\"operationId\":\"deprecated_list_pins\",\"functionName\":\"DeprecatedListPins\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/pins\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /channels/{channel_id}/pins/{message_id}\",\"operationId\":\"deprecated_create_pin\",\"functionName\":\"DeprecatedCreatePin\",\"method\":\"PUT\",\"path\":\"/channels/{channel_id}/pins/{message_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/pins/{message_id}\",\"operationId\":\"deprecated_delete_pin\",\"functionName\":\"DeprecatedDeletePin\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/pins/{message_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/polls/{message_id}/answers/{answer_id}\",\"operationId\":\"get_answer_voters\",\"functionName\":\"GetAnswerVoters\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/polls/{message_id}/answers/{answer_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/polls/{message_id}/expire\",\"operationId\":\"poll_expire\",\"functionName\":\"PollExpire\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/polls/{message_id}/expire\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /channels/{channel_id}/recipients/{user_id}\",\"operationId\":\"add_group_dm_user\",\"functionName\":\"AddGroupDmUser\",\"method\":\"PUT\",\"path\":\"/channels/{channel_id}/recipients/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/recipients/{user_id}\",\"operationId\":\"delete_group_dm_user\",\"functionName\":\"DeleteGroupDmUser\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/recipients/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/send-soundboard-sound\",\"operationId\":\"send_soundboard_sound\",\"functionName\":\"SendSoundboardSound\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/send-soundboard-sound\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/thread-members\",\"operationId\":\"list_thread_members\",\"functionName\":\"ListThreadMembers\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/thread-members\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /channels/{channel_id}/thread-members/@me\",\"operationId\":\"join_thread\",\"functionName\":\"JoinThread\",\"method\":\"PUT\",\"path\":\"/channels/{channel_id}/thread-members/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/thread-members/@me\",\"operationId\":\"leave_thread\",\"functionName\":\"LeaveThread\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/thread-members/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/thread-members/{user_id}\",\"operationId\":\"get_thread_member\",\"functionName\":\"GetThreadMember\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/thread-members/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /channels/{channel_id}/thread-members/{user_id}\",\"operationId\":\"add_thread_member\",\"functionName\":\"AddThreadMember\",\"method\":\"PUT\",\"path\":\"/channels/{channel_id}/thread-members/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /channels/{channel_id}/thread-members/{user_id}\",\"operationId\":\"delete_thread_member\",\"functionName\":\"DeleteThreadMember\",\"method\":\"DELETE\",\"path\":\"/channels/{channel_id}/thread-members/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/threads\",\"operationId\":\"create_thread\",\"functionName\":\"CreateThread\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/threads\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/threads/archived/private\",\"operationId\":\"list_private_archived_threads\",\"functionName\":\"ListPrivateArchivedThreads\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/threads/archived/private\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/threads/archived/public\",\"operationId\":\"list_public_archived_threads\",\"functionName\":\"ListPublicArchivedThreads\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/threads/archived/public\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/threads/search\",\"operationId\":\"thread_search\",\"functionName\":\"ThreadSearch\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/threads/search\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/typing\",\"operationId\":\"trigger_typing_indicator\",\"functionName\":\"TriggerTypingIndicator\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/typing\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/users/@me/threads/archived/private\",\"operationId\":\"list_my_private_archived_threads\",\"functionName\":\"ListMyPrivateArchivedThreads\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/users/@me/threads/archived/private\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /channels/{channel_id}/voice-status\",\"operationId\":\"update_voice_channel_status\",\"functionName\":\"UpdateVoiceChannelStatus\",\"method\":\"PUT\",\"path\":\"/channels/{channel_id}/voice-status\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /channels/{channel_id}/webhooks\",\"operationId\":\"list_channel_webhooks\",\"functionName\":\"ListChannelWebhooks\",\"method\":\"GET\",\"path\":\"/channels/{channel_id}/webhooks\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /channels/{channel_id}/webhooks\",\"operationId\":\"create_webhook\",\"functionName\":\"CreateWebhook\",\"method\":\"POST\",\"path\":\"/channels/{channel_id}/webhooks\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /gateway\",\"operationId\":\"get_gateway\",\"functionName\":\"GetGateway\",\"method\":\"GET\",\"path\":\"/gateway\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /gateway/bot\",\"operationId\":\"get_bot_gateway\",\"functionName\":\"GetBotGateway\",\"method\":\"GET\",\"path\":\"/gateway/bot\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/templates/{code}\",\"operationId\":\"get_guild_template\",\"functionName\":\"GetGuildTemplate\",\"method\":\"GET\",\"path\":\"/guilds/templates/{code}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}\",\"operationId\":\"get_guild\",\"functionName\":\"GetGuild\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}\",\"operationId\":\"update_guild\",\"functionName\":\"UpdateGuild\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/audit-logs\",\"operationId\":\"list_guild_audit_log_entries\",\"functionName\":\"ListGuildAuditLogEntries\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/audit-logs\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/auto-moderation/rules\",\"operationId\":\"list_auto_moderation_rules\",\"functionName\":\"ListAutoModerationRules\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/auto-moderation/rules\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/auto-moderation/rules\",\"operationId\":\"create_auto_moderation_rule\",\"functionName\":\"CreateAutoModerationRule\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/auto-moderation/rules\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/auto-moderation/rules/{rule_id}\",\"operationId\":\"get_auto_moderation_rule\",\"functionName\":\"GetAutoModerationRule\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/auto-moderation/rules/{rule_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/auto-moderation/rules/{rule_id}\",\"operationId\":\"delete_auto_moderation_rule\",\"functionName\":\"DeleteAutoModerationRule\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/auto-moderation/rules/{rule_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/auto-moderation/rules/{rule_id}\",\"operationId\":\"update_auto_moderation_rule\",\"functionName\":\"UpdateAutoModerationRule\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/auto-moderation/rules/{rule_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/bans\",\"operationId\":\"list_guild_bans\",\"functionName\":\"ListGuildBans\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/bans\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/bans/{user_id}\",\"operationId\":\"get_guild_ban\",\"functionName\":\"GetGuildBan\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/bans/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /guilds/{guild_id}/bans/{user_id}\",\"operationId\":\"ban_user_from_guild\",\"functionName\":\"BanUserFromGuild\",\"method\":\"PUT\",\"path\":\"/guilds/{guild_id}/bans/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/bans/{user_id}\",\"operationId\":\"unban_user_from_guild\",\"functionName\":\"UnbanUserFromGuild\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/bans/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/bulk-ban\",\"operationId\":\"bulk_ban_users_from_guild\",\"functionName\":\"BulkBanUsersFromGuild\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/bulk-ban\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/channels\",\"operationId\":\"list_guild_channels\",\"functionName\":\"ListGuildChannels\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/channels\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/channels\",\"operationId\":\"create_guild_channel\",\"functionName\":\"CreateGuildChannel\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/channels\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/channels\",\"operationId\":\"bulk_update_guild_channels\",\"functionName\":\"BulkUpdateGuildChannels\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/channels\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/emojis\",\"operationId\":\"list_guild_emojis\",\"functionName\":\"ListGuildEmojis\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/emojis\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/emojis\",\"operationId\":\"create_guild_emoji\",\"functionName\":\"CreateGuildEmoji\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/emojis\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/emojis/{emoji_id}\",\"operationId\":\"get_guild_emoji\",\"functionName\":\"GetGuildEmoji\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/emojis/{emoji_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/emojis/{emoji_id}\",\"operationId\":\"delete_guild_emoji\",\"functionName\":\"DeleteGuildEmoji\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/emojis/{emoji_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/emojis/{emoji_id}\",\"operationId\":\"update_guild_emoji\",\"functionName\":\"UpdateGuildEmoji\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/emojis/{emoji_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /guilds/{guild_id}/incident-actions\",\"operationId\":\"update_guild_incident_actions\",\"functionName\":\"UpdateGuildIncidentActions\",\"method\":\"PUT\",\"path\":\"/guilds/{guild_id}/incident-actions\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/integrations\",\"operationId\":\"list_guild_integrations\",\"functionName\":\"ListGuildIntegrations\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/integrations\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/integrations/{integration_id}\",\"operationId\":\"delete_guild_integration\",\"functionName\":\"DeleteGuildIntegration\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/integrations/{integration_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/invites\",\"operationId\":\"list_guild_invites\",\"functionName\":\"ListGuildInvites\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/invites\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/members\",\"operationId\":\"list_guild_members\",\"functionName\":\"ListGuildMembers\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/members\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/members/@me\",\"operationId\":\"update_my_guild_member\",\"functionName\":\"UpdateMyGuildMember\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/members/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/members/search\",\"operationId\":\"search_guild_members\",\"functionName\":\"SearchGuildMembers\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/members/search\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/members/{user_id}\",\"operationId\":\"get_guild_member\",\"functionName\":\"GetGuildMember\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/members/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /guilds/{guild_id}/members/{user_id}\",\"operationId\":\"add_guild_member\",\"functionName\":\"AddGuildMember\",\"method\":\"PUT\",\"path\":\"/guilds/{guild_id}/members/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/members/{user_id}\",\"operationId\":\"delete_guild_member\",\"functionName\":\"DeleteGuildMember\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/members/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/members/{user_id}\",\"operationId\":\"update_guild_member\",\"functionName\":\"UpdateGuildMember\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/members/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /guilds/{guild_id}/members/{user_id}/roles/{role_id}\",\"operationId\":\"add_guild_member_role\",\"functionName\":\"AddGuildMemberRole\",\"method\":\"PUT\",\"path\":\"/guilds/{guild_id}/members/{user_id}/roles/{role_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/members/{user_id}/roles/{role_id}\",\"operationId\":\"delete_guild_member_role\",\"functionName\":\"DeleteGuildMemberRole\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/members/{user_id}/roles/{role_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/messages/search\",\"operationId\":\"guild_search\",\"functionName\":\"GuildSearch\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/messages/search\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/new-member-welcome\",\"operationId\":\"get_guild_new_member_welcome\",\"functionName\":\"GetGuildNewMemberWelcome\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/new-member-welcome\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/onboarding\",\"operationId\":\"get_guilds_onboarding\",\"functionName\":\"GetGuildsOnboarding\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/onboarding\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /guilds/{guild_id}/onboarding\",\"operationId\":\"put_guilds_onboarding\",\"functionName\":\"PutGuildsOnboarding\",\"method\":\"PUT\",\"path\":\"/guilds/{guild_id}/onboarding\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/preview\",\"operationId\":\"get_guild_preview\",\"functionName\":\"GetGuildPreview\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/preview\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/prune\",\"operationId\":\"preview_prune_guild\",\"functionName\":\"PreviewPruneGuild\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/prune\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/prune\",\"operationId\":\"prune_guild\",\"functionName\":\"PruneGuild\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/prune\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/regions\",\"operationId\":\"list_guild_voice_regions\",\"functionName\":\"ListGuildVoiceRegions\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/regions\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/requests\",\"operationId\":\"get_guild_join_requests\",\"functionName\":\"GetGuildJoinRequests\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/requests\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/requests/{request_id}\",\"operationId\":\"action_guild_join_request\",\"functionName\":\"ActionGuildJoinRequest\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/requests/{request_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/roles\",\"operationId\":\"list_guild_roles\",\"functionName\":\"ListGuildRoles\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/roles\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/roles\",\"operationId\":\"create_guild_role\",\"functionName\":\"CreateGuildRole\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/roles\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/roles\",\"operationId\":\"bulk_update_guild_roles\",\"functionName\":\"BulkUpdateGuildRoles\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/roles\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/roles/member-counts\",\"operationId\":\"guild_role_member_counts\",\"functionName\":\"GuildRoleMemberCounts\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/roles/member-counts\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/roles/{role_id}\",\"operationId\":\"get_guild_role\",\"functionName\":\"GetGuildRole\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/roles/{role_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/roles/{role_id}\",\"operationId\":\"delete_guild_role\",\"functionName\":\"DeleteGuildRole\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/roles/{role_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/roles/{role_id}\",\"operationId\":\"update_guild_role\",\"functionName\":\"UpdateGuildRole\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/roles/{role_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/scheduled-events\",\"operationId\":\"list_guild_scheduled_events\",\"functionName\":\"ListGuildScheduledEvents\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/scheduled-events\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/scheduled-events\",\"operationId\":\"create_guild_scheduled_event\",\"functionName\":\"CreateGuildScheduledEvent\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/scheduled-events\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}\",\"operationId\":\"get_guild_scheduled_event\",\"functionName\":\"GetGuildScheduledEvent\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}\",\"operationId\":\"delete_guild_scheduled_event\",\"functionName\":\"DeleteGuildScheduledEvent\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}\",\"operationId\":\"update_guild_scheduled_event\",\"functionName\":\"UpdateGuildScheduledEvent\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions\",\"operationId\":\"create_guild_scheduled_event_exception\",\"functionName\":\"CreateGuildScheduledEventException\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}\",\"operationId\":\"delete_guild_scheduled_event_exception\",\"functionName\":\"DeleteGuildScheduledEventException\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}\",\"operationId\":\"update_guild_scheduled_event_exception\",\"functionName\":\"UpdateGuildScheduledEventException\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users\",\"operationId\":\"list_guild_scheduled_event_users\",\"functionName\":\"ListGuildScheduledEventUsers\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users/counts\",\"operationId\":\"count_guild_scheduled_event_users\",\"functionName\":\"CountGuildScheduledEventUsers\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users/counts\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/{guild_scheduled_event_exception_id}/users\",\"operationId\":\"list_guild_scheduled_event_exception_users\",\"functionName\":\"ListGuildScheduledEventExceptionUsers\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/{guild_scheduled_event_exception_id}/users\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/soundboard-sounds\",\"operationId\":\"list_guild_soundboard_sounds\",\"functionName\":\"ListGuildSoundboardSounds\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/soundboard-sounds\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/soundboard-sounds\",\"operationId\":\"create_guild_soundboard_sound\",\"functionName\":\"CreateGuildSoundboardSound\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/soundboard-sounds\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/soundboard-sounds/{sound_id}\",\"operationId\":\"get_guild_soundboard_sound\",\"functionName\":\"GetGuildSoundboardSound\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/soundboard-sounds/{sound_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/soundboard-sounds/{sound_id}\",\"operationId\":\"delete_guild_soundboard_sound\",\"functionName\":\"DeleteGuildSoundboardSound\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/soundboard-sounds/{sound_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/soundboard-sounds/{sound_id}\",\"operationId\":\"update_guild_soundboard_sound\",\"functionName\":\"UpdateGuildSoundboardSound\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/soundboard-sounds/{sound_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/stickers\",\"operationId\":\"list_guild_stickers\",\"functionName\":\"ListGuildStickers\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/stickers\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/stickers\",\"operationId\":\"create_guild_sticker\",\"functionName\":\"CreateGuildSticker\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/stickers\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/stickers/{sticker_id}\",\"operationId\":\"get_guild_sticker\",\"functionName\":\"GetGuildSticker\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/stickers/{sticker_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/stickers/{sticker_id}\",\"operationId\":\"delete_guild_sticker\",\"functionName\":\"DeleteGuildSticker\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/stickers/{sticker_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/stickers/{sticker_id}\",\"operationId\":\"update_guild_sticker\",\"functionName\":\"UpdateGuildSticker\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/stickers/{sticker_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/templates\",\"operationId\":\"list_guild_templates\",\"functionName\":\"ListGuildTemplates\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/templates\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /guilds/{guild_id}/templates\",\"operationId\":\"create_guild_template\",\"functionName\":\"CreateGuildTemplate\",\"method\":\"POST\",\"path\":\"/guilds/{guild_id}/templates\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /guilds/{guild_id}/templates/{code}\",\"operationId\":\"sync_guild_template\",\"functionName\":\"SyncGuildTemplate\",\"method\":\"PUT\",\"path\":\"/guilds/{guild_id}/templates/{code}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /guilds/{guild_id}/templates/{code}\",\"operationId\":\"delete_guild_template\",\"functionName\":\"DeleteGuildTemplate\",\"method\":\"DELETE\",\"path\":\"/guilds/{guild_id}/templates/{code}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/templates/{code}\",\"operationId\":\"update_guild_template\",\"functionName\":\"UpdateGuildTemplate\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/templates/{code}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/threads/active\",\"operationId\":\"get_active_guild_threads\",\"functionName\":\"GetActiveGuildThreads\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/threads/active\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/vanity-url\",\"operationId\":\"get_guild_vanity_url\",\"functionName\":\"GetGuildVanityUrl\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/vanity-url\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/voice-states/@me\",\"operationId\":\"get_self_voice_state\",\"functionName\":\"GetSelfVoiceState\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/voice-states/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/voice-states/@me\",\"operationId\":\"update_self_voice_state\",\"functionName\":\"UpdateSelfVoiceState\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/voice-states/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/voice-states/{user_id}\",\"operationId\":\"get_voice_state\",\"functionName\":\"GetVoiceState\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/voice-states/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/voice-states/{user_id}\",\"operationId\":\"update_voice_state\",\"functionName\":\"UpdateVoiceState\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/voice-states/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/webhooks\",\"operationId\":\"get_guild_webhooks\",\"functionName\":\"GetGuildWebhooks\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/webhooks\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/welcome-screen\",\"operationId\":\"get_guild_welcome_screen\",\"functionName\":\"GetGuildWelcomeScreen\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/welcome-screen\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/welcome-screen\",\"operationId\":\"update_guild_welcome_screen\",\"functionName\":\"UpdateGuildWelcomeScreen\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/welcome-screen\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/widget\",\"operationId\":\"get_guild_widget_settings\",\"functionName\":\"GetGuildWidgetSettings\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/widget\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /guilds/{guild_id}/widget\",\"operationId\":\"update_guild_widget_settings\",\"functionName\":\"UpdateGuildWidgetSettings\",\"method\":\"PATCH\",\"path\":\"/guilds/{guild_id}/widget\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/widget.json\",\"operationId\":\"get_guild_widget\",\"functionName\":\"GetGuildWidget\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/widget.json\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /guilds/{guild_id}/widget.png\",\"operationId\":\"get_guild_widget_png\",\"functionName\":\"GetGuildWidgetPng\",\"method\":\"GET\",\"path\":\"/guilds/{guild_id}/widget.png\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /interactions/{interaction_id}/{interaction_token}/callback\",\"operationId\":\"create_interaction_response\",\"functionName\":\"CreateInteractionResponse\",\"method\":\"POST\",\"path\":\"/interactions/{interaction_id}/{interaction_token}/callback\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /invites/{code}\",\"operationId\":\"invite_resolve\",\"functionName\":\"InviteResolve\",\"method\":\"GET\",\"path\":\"/invites/{code}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /invites/{code}\",\"operationId\":\"invite_revoke\",\"functionName\":\"InviteRevoke\",\"method\":\"DELETE\",\"path\":\"/invites/{code}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /invites/{code}/target-users\",\"operationId\":\"get_invite_target_users\",\"functionName\":\"GetInviteTargetUsers\",\"method\":\"GET\",\"path\":\"/invites/{code}/target-users\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /invites/{code}/target-users\",\"operationId\":\"update_invite_target_users\",\"functionName\":\"UpdateInviteTargetUsers\",\"method\":\"PUT\",\"path\":\"/invites/{code}/target-users\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /invites/{code}/target-users/job-status\",\"operationId\":\"get_invite_target_users_job_status\",\"functionName\":\"GetInviteTargetUsersJobStatus\",\"method\":\"GET\",\"path\":\"/invites/{code}/target-users/job-status\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /lobbies\",\"operationId\":\"create_or_join_lobby\",\"functionName\":\"CreateOrJoinLobby\",\"method\":\"PUT\",\"path\":\"/lobbies\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /lobbies\",\"operationId\":\"create_lobby\",\"functionName\":\"CreateLobby\",\"method\":\"POST\",\"path\":\"/lobbies\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /lobbies/{lobby_id}\",\"operationId\":\"get_lobby\",\"functionName\":\"GetLobby\",\"method\":\"GET\",\"path\":\"/lobbies/{lobby_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /lobbies/{lobby_id}\",\"operationId\":\"delete_lobby\",\"functionName\":\"DeleteLobby\",\"method\":\"DELETE\",\"path\":\"/lobbies/{lobby_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /lobbies/{lobby_id}\",\"operationId\":\"edit_lobby\",\"functionName\":\"EditLobby\",\"method\":\"PATCH\",\"path\":\"/lobbies/{lobby_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /lobbies/{lobby_id}/channel-linking\",\"operationId\":\"edit_lobby_channel_link\",\"functionName\":\"EditLobbyChannelLink\",\"method\":\"PATCH\",\"path\":\"/lobbies/{lobby_id}/channel-linking\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /lobbies/{lobby_id}/members/@me\",\"operationId\":\"leave_lobby\",\"functionName\":\"LeaveLobby\",\"method\":\"DELETE\",\"path\":\"/lobbies/{lobby_id}/members/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /lobbies/{lobby_id}/members/@me/invites\",\"operationId\":\"create_linked_lobby_guild_invite_for_self\",\"functionName\":\"CreateLinkedLobbyGuildInviteForSelf\",\"method\":\"POST\",\"path\":\"/lobbies/{lobby_id}/members/@me/invites\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /lobbies/{lobby_id}/members/bulk\",\"operationId\":\"bulk_update_lobby_members\",\"functionName\":\"BulkUpdateLobbyMembers\",\"method\":\"POST\",\"path\":\"/lobbies/{lobby_id}/members/bulk\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /lobbies/{lobby_id}/members/{user_id}\",\"operationId\":\"add_lobby_member\",\"functionName\":\"AddLobbyMember\",\"method\":\"PUT\",\"path\":\"/lobbies/{lobby_id}/members/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /lobbies/{lobby_id}/members/{user_id}\",\"operationId\":\"delete_lobby_member\",\"functionName\":\"DeleteLobbyMember\",\"method\":\"DELETE\",\"path\":\"/lobbies/{lobby_id}/members/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /lobbies/{lobby_id}/members/{user_id}/invites\",\"operationId\":\"create_linked_lobby_guild_invite_for_user\",\"functionName\":\"CreateLinkedLobbyGuildInviteForUser\",\"method\":\"POST\",\"path\":\"/lobbies/{lobby_id}/members/{user_id}/invites\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /lobbies/{lobby_id}/messages\",\"operationId\":\"get_lobby_messages\",\"functionName\":\"GetLobbyMessages\",\"method\":\"GET\",\"path\":\"/lobbies/{lobby_id}/messages\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /lobbies/{lobby_id}/messages\",\"operationId\":\"create_lobby_message\",\"functionName\":\"CreateLobbyMessage\",\"method\":\"POST\",\"path\":\"/lobbies/{lobby_id}/messages\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /lobbies/{lobby_id}/messages/{message_id}/moderation-metadata\",\"operationId\":\"update_lobby_message_external_moderation_metadata\",\"functionName\":\"UpdateLobbyMessageExternalModerationMetadata\",\"method\":\"PUT\",\"path\":\"/lobbies/{lobby_id}/messages/{message_id}/moderation-metadata\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /oauth2/@me\",\"operationId\":\"get_my_oauth2_authorization\",\"functionName\":\"GetMyOauth2Authorization\",\"method\":\"GET\",\"path\":\"/oauth2/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /oauth2/applications/@me\",\"operationId\":\"get_my_oauth2_application\",\"functionName\":\"GetMyOauth2Application\",\"method\":\"GET\",\"path\":\"/oauth2/applications/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /oauth2/keys\",\"operationId\":\"get_public_keys\",\"functionName\":\"GetPublicKeys\",\"method\":\"GET\",\"path\":\"/oauth2/keys\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /oauth2/userinfo\",\"operationId\":\"get_openid_connect_userinfo\",\"functionName\":\"GetOpenidConnectUserinfo\",\"method\":\"GET\",\"path\":\"/oauth2/userinfo\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /partner-sdk/dms/{user_id_1}/{user_id_2}/messages/{message_id}/moderation-metadata\",\"operationId\":\"update_user_message_external_moderation_metadata\",\"functionName\":\"UpdateUserMessageExternalModerationMetadata\",\"method\":\"PUT\",\"path\":\"/partner-sdk/dms/{user_id_1}/{user_id_2}/messages/{message_id}/moderation-metadata\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /partner-sdk/provisional-accounts/unmerge\",\"operationId\":\"partner_sdk_unmerge_provisional_account\",\"functionName\":\"PartnerSdkUnmergeProvisionalAccount\",\"method\":\"POST\",\"path\":\"/partner-sdk/provisional-accounts/unmerge\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /partner-sdk/provisional-accounts/unmerge/bot\",\"operationId\":\"bot_partner_sdk_unmerge_provisional_account\",\"functionName\":\"BotPartnerSdkUnmergeProvisionalAccount\",\"method\":\"POST\",\"path\":\"/partner-sdk/provisional-accounts/unmerge/bot\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /partner-sdk/token\",\"operationId\":\"partner_sdk_token\",\"functionName\":\"PartnerSdkToken\",\"method\":\"POST\",\"path\":\"/partner-sdk/token\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /partner-sdk/token/bot\",\"operationId\":\"bot_partner_sdk_token\",\"functionName\":\"BotPartnerSdkToken\",\"method\":\"POST\",\"path\":\"/partner-sdk/token/bot\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /skus/{sku_id}/subscriptions\",\"operationId\":\"get_sku_subscriptions\",\"functionName\":\"GetSkuSubscriptions\",\"method\":\"GET\",\"path\":\"/skus/{sku_id}/subscriptions\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /skus/{sku_id}/subscriptions/{subscription_id}\",\"operationId\":\"get_sku_subscription\",\"functionName\":\"GetSkuSubscription\",\"method\":\"GET\",\"path\":\"/skus/{sku_id}/subscriptions/{subscription_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /soundboard-default-sounds\",\"operationId\":\"get_soundboard_default_sounds\",\"functionName\":\"GetSoundboardDefaultSounds\",\"method\":\"GET\",\"path\":\"/soundboard-default-sounds\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /stage-instances\",\"operationId\":\"create_stage_instance\",\"functionName\":\"CreateStageInstance\",\"method\":\"POST\",\"path\":\"/stage-instances\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /stage-instances/{channel_id}\",\"operationId\":\"get_stage_instance\",\"functionName\":\"GetStageInstance\",\"method\":\"GET\",\"path\":\"/stage-instances/{channel_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /stage-instances/{channel_id}\",\"operationId\":\"delete_stage_instance\",\"functionName\":\"DeleteStageInstance\",\"method\":\"DELETE\",\"path\":\"/stage-instances/{channel_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /stage-instances/{channel_id}\",\"operationId\":\"update_stage_instance\",\"functionName\":\"UpdateStageInstance\",\"method\":\"PATCH\",\"path\":\"/stage-instances/{channel_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /sticker-packs\",\"operationId\":\"list_sticker_packs\",\"functionName\":\"ListStickerPacks\",\"method\":\"GET\",\"path\":\"/sticker-packs\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /sticker-packs/{pack_id}\",\"operationId\":\"get_sticker_pack\",\"functionName\":\"GetStickerPack\",\"method\":\"GET\",\"path\":\"/sticker-packs/{pack_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /stickers/{sticker_id}\",\"operationId\":\"get_sticker\",\"functionName\":\"GetSticker\",\"method\":\"GET\",\"path\":\"/stickers/{sticker_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /users/@me\",\"operationId\":\"get_my_user\",\"functionName\":\"GetMyUser\",\"method\":\"GET\",\"path\":\"/users/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /users/@me\",\"operationId\":\"update_my_user\",\"functionName\":\"UpdateMyUser\",\"method\":\"PATCH\",\"path\":\"/users/@me\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /users/@me/applications/{application_id}/entitlements\",\"operationId\":\"get_current_user_application_entitlements\",\"functionName\":\"GetCurrentUserApplicationEntitlements\",\"method\":\"GET\",\"path\":\"/users/@me/applications/{application_id}/entitlements\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /users/@me/applications/{application_id}/role-connection\",\"operationId\":\"get_application_user_role_connection\",\"functionName\":\"GetApplicationUserRoleConnection\",\"method\":\"GET\",\"path\":\"/users/@me/applications/{application_id}/role-connection\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PUT /users/@me/applications/{application_id}/role-connection\",\"operationId\":\"update_application_user_role_connection\",\"functionName\":\"UpdateApplicationUserRoleConnection\",\"method\":\"PUT\",\"path\":\"/users/@me/applications/{application_id}/role-connection\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /users/@me/applications/{application_id}/role-connection\",\"operationId\":\"delete_application_user_role_connection\",\"functionName\":\"DeleteApplicationUserRoleConnection\",\"method\":\"DELETE\",\"path\":\"/users/@me/applications/{application_id}/role-connection\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /users/@me/channels\",\"operationId\":\"create_dm\",\"functionName\":\"CreateDm\",\"method\":\"POST\",\"path\":\"/users/@me/channels\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /users/@me/connections\",\"operationId\":\"list_my_connections\",\"functionName\":\"ListMyConnections\",\"method\":\"GET\",\"path\":\"/users/@me/connections\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /users/@me/guilds\",\"operationId\":\"list_my_guilds\",\"functionName\":\"ListMyGuilds\",\"method\":\"GET\",\"path\":\"/users/@me/guilds\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /users/@me/guilds/{guild_id}\",\"operationId\":\"leave_guild\",\"functionName\":\"LeaveGuild\",\"method\":\"DELETE\",\"path\":\"/users/@me/guilds/{guild_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /users/@me/guilds/{guild_id}/member\",\"operationId\":\"get_my_guild_member\",\"functionName\":\"GetMyGuildMember\",\"method\":\"GET\",\"path\":\"/users/@me/guilds/{guild_id}/member\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /users/{user_id}\",\"operationId\":\"get_user\",\"functionName\":\"GetUser\",\"method\":\"GET\",\"path\":\"/users/{user_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /voice/regions\",\"operationId\":\"list_voice_regions\",\"functionName\":\"ListVoiceRegions\",\"method\":\"GET\",\"path\":\"/voice/regions\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /webhooks/{webhook_id}\",\"operationId\":\"get_webhook\",\"functionName\":\"GetWebhook\",\"method\":\"GET\",\"path\":\"/webhooks/{webhook_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /webhooks/{webhook_id}\",\"operationId\":\"delete_webhook\",\"functionName\":\"DeleteWebhook\",\"method\":\"DELETE\",\"path\":\"/webhooks/{webhook_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /webhooks/{webhook_id}\",\"operationId\":\"update_webhook\",\"functionName\":\"UpdateWebhook\",\"method\":\"PATCH\",\"path\":\"/webhooks/{webhook_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /webhooks/{webhook_id}/{webhook_token}\",\"operationId\":\"get_webhook_by_token\",\"functionName\":\"GetWebhookByToken\",\"method\":\"GET\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /webhooks/{webhook_id}/{webhook_token}\",\"operationId\":\"execute_webhook\",\"functionName\":\"ExecuteWebhook\",\"method\":\"POST\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /webhooks/{webhook_id}/{webhook_token}\",\"operationId\":\"delete_webhook_by_token\",\"functionName\":\"DeleteWebhookByToken\",\"method\":\"DELETE\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /webhooks/{webhook_id}/{webhook_token}\",\"operationId\":\"update_webhook_by_token\",\"functionName\":\"UpdateWebhookByToken\",\"method\":\"PATCH\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /webhooks/{webhook_id}/{webhook_token}/github\",\"operationId\":\"execute_github_compatible_webhook\",\"functionName\":\"ExecuteGithubCompatibleWebhook\",\"method\":\"POST\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}/github\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /webhooks/{webhook_id}/{webhook_token}/messages/@original\",\"operationId\":\"get_original_webhook_message\",\"functionName\":\"GetOriginalWebhookMessage\",\"method\":\"GET\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}/messages/@original\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /webhooks/{webhook_id}/{webhook_token}/messages/@original\",\"operationId\":\"delete_original_webhook_message\",\"functionName\":\"DeleteOriginalWebhookMessage\",\"method\":\"DELETE\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}/messages/@original\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /webhooks/{webhook_id}/{webhook_token}/messages/@original\",\"operationId\":\"update_original_webhook_message\",\"functionName\":\"UpdateOriginalWebhookMessage\",\"method\":\"PATCH\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}/messages/@original\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"GET /webhooks/{webhook_id}/{webhook_token}/messages/{message_id}\",\"operationId\":\"get_webhook_message\",\"functionName\":\"GetWebhookMessage\",\"method\":\"GET\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"DELETE /webhooks/{webhook_id}/{webhook_token}/messages/{message_id}\",\"operationId\":\"delete_webhook_message\",\"functionName\":\"DeleteWebhookMessage\",\"method\":\"DELETE\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"PATCH /webhooks/{webhook_id}/{webhook_token}/messages/{message_id}\",\"operationId\":\"update_webhook_message\",\"functionName\":\"UpdateWebhookMessage\",\"method\":\"PATCH\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}\",\"summary\":\"\",\"tags\":[]},{\"uid\":\"POST /webhooks/{webhook_id}/{webhook_token}/slack\",\"operationId\":\"execute_slack_compatible_webhook\",\"functionName\":\"ExecuteSlackCompatibleWebhook\",\"method\":\"POST\",\"path\":\"/webhooks/{webhook_id}/{webhook_token}/slack\",\"summary\":\"\",\"tags\":[]}]") as readonly DiscordHttpApiOperation[];

// Hardened literal operation keys for generated SDK typing.
export const DISCORD_HTTP_API_OPERATION_IDS = [
  "get_my_application",
  "update_my_application",
  "get_application",
  "update_application",
  "applications_get_activity_instance",
  "upload_application_attachment",
  "list_application_commands",
  "bulk_set_application_commands",
  "create_application_command",
  "get_application_command",
  "delete_application_command",
  "update_application_command",
  "list_application_emojis",
  "create_application_emoji",
  "get_application_emoji",
  "delete_application_emoji",
  "update_application_emoji",
  "get_entitlements",
  "create_entitlement",
  "get_entitlement",
  "delete_entitlement",
  "consume_entitlement",
  "list_guild_application_commands",
  "bulk_set_guild_application_commands",
  "create_guild_application_command",
  "list_guild_application_command_permissions",
  "get_guild_application_command",
  "delete_guild_application_command",
  "update_guild_application_command",
  "get_guild_application_command_permissions",
  "set_guild_application_command_permissions",
  "get_application_role_connections_metadata",
  "update_application_role_connections_metadata",
  "get_channel",
  "delete_channel",
  "update_channel",
  "follow_channel",
  "list_channel_invites",
  "create_channel_invite",
  "list_messages",
  "create_message",
  "bulk_delete_messages",
  "list_pins",
  "create_pin",
  "delete_pin",
  "get_message",
  "delete_message",
  "update_message",
  "crosspost_message",
  "delete_all_message_reactions",
  "list_message_reactions_by_emoji",
  "delete_all_message_reactions_by_emoji",
  "add_my_message_reaction",
  "delete_my_message_reaction",
  "delete_user_message_reaction",
  "create_thread_from_message",
  "set_channel_permission_overwrite",
  "delete_channel_permission_overwrite",
  "deprecated_list_pins",
  "deprecated_create_pin",
  "deprecated_delete_pin",
  "get_answer_voters",
  "poll_expire",
  "add_group_dm_user",
  "delete_group_dm_user",
  "send_soundboard_sound",
  "list_thread_members",
  "join_thread",
  "leave_thread",
  "get_thread_member",
  "add_thread_member",
  "delete_thread_member",
  "create_thread",
  "list_private_archived_threads",
  "list_public_archived_threads",
  "thread_search",
  "trigger_typing_indicator",
  "list_my_private_archived_threads",
  "update_voice_channel_status",
  "list_channel_webhooks",
  "create_webhook",
  "get_gateway",
  "get_bot_gateway",
  "get_guild_template",
  "get_guild",
  "update_guild",
  "list_guild_audit_log_entries",
  "list_auto_moderation_rules",
  "create_auto_moderation_rule",
  "get_auto_moderation_rule",
  "delete_auto_moderation_rule",
  "update_auto_moderation_rule",
  "list_guild_bans",
  "get_guild_ban",
  "ban_user_from_guild",
  "unban_user_from_guild",
  "bulk_ban_users_from_guild",
  "list_guild_channels",
  "create_guild_channel",
  "bulk_update_guild_channels",
  "list_guild_emojis",
  "create_guild_emoji",
  "get_guild_emoji",
  "delete_guild_emoji",
  "update_guild_emoji",
  "update_guild_incident_actions",
  "list_guild_integrations",
  "delete_guild_integration",
  "list_guild_invites",
  "list_guild_members",
  "update_my_guild_member",
  "search_guild_members",
  "get_guild_member",
  "add_guild_member",
  "delete_guild_member",
  "update_guild_member",
  "add_guild_member_role",
  "delete_guild_member_role",
  "guild_search",
  "get_guild_new_member_welcome",
  "get_guilds_onboarding",
  "put_guilds_onboarding",
  "get_guild_preview",
  "preview_prune_guild",
  "prune_guild",
  "list_guild_voice_regions",
  "get_guild_join_requests",
  "action_guild_join_request",
  "list_guild_roles",
  "create_guild_role",
  "bulk_update_guild_roles",
  "guild_role_member_counts",
  "get_guild_role",
  "delete_guild_role",
  "update_guild_role",
  "list_guild_scheduled_events",
  "create_guild_scheduled_event",
  "get_guild_scheduled_event",
  "delete_guild_scheduled_event",
  "update_guild_scheduled_event",
  "create_guild_scheduled_event_exception",
  "delete_guild_scheduled_event_exception",
  "update_guild_scheduled_event_exception",
  "list_guild_scheduled_event_users",
  "count_guild_scheduled_event_users",
  "list_guild_scheduled_event_exception_users",
  "list_guild_soundboard_sounds",
  "create_guild_soundboard_sound",
  "get_guild_soundboard_sound",
  "delete_guild_soundboard_sound",
  "update_guild_soundboard_sound",
  "list_guild_stickers",
  "create_guild_sticker",
  "get_guild_sticker",
  "delete_guild_sticker",
  "update_guild_sticker",
  "list_guild_templates",
  "create_guild_template",
  "sync_guild_template",
  "delete_guild_template",
  "update_guild_template",
  "get_active_guild_threads",
  "get_guild_vanity_url",
  "get_self_voice_state",
  "update_self_voice_state",
  "get_voice_state",
  "update_voice_state",
  "get_guild_webhooks",
  "get_guild_welcome_screen",
  "update_guild_welcome_screen",
  "get_guild_widget_settings",
  "update_guild_widget_settings",
  "get_guild_widget",
  "get_guild_widget_png",
  "create_interaction_response",
  "invite_resolve",
  "invite_revoke",
  "get_invite_target_users",
  "update_invite_target_users",
  "get_invite_target_users_job_status",
  "create_or_join_lobby",
  "create_lobby",
  "get_lobby",
  "delete_lobby",
  "edit_lobby",
  "edit_lobby_channel_link",
  "leave_lobby",
  "create_linked_lobby_guild_invite_for_self",
  "bulk_update_lobby_members",
  "add_lobby_member",
  "delete_lobby_member",
  "create_linked_lobby_guild_invite_for_user",
  "get_lobby_messages",
  "create_lobby_message",
  "update_lobby_message_external_moderation_metadata",
  "get_my_oauth2_authorization",
  "get_my_oauth2_application",
  "get_public_keys",
  "get_openid_connect_userinfo",
  "update_user_message_external_moderation_metadata",
  "partner_sdk_unmerge_provisional_account",
  "bot_partner_sdk_unmerge_provisional_account",
  "partner_sdk_token",
  "bot_partner_sdk_token",
  "get_sku_subscriptions",
  "get_sku_subscription",
  "get_soundboard_default_sounds",
  "create_stage_instance",
  "get_stage_instance",
  "delete_stage_instance",
  "update_stage_instance",
  "list_sticker_packs",
  "get_sticker_pack",
  "get_sticker",
  "get_my_user",
  "update_my_user",
  "get_current_user_application_entitlements",
  "get_application_user_role_connection",
  "update_application_user_role_connection",
  "delete_application_user_role_connection",
  "create_dm",
  "list_my_connections",
  "list_my_guilds",
  "leave_guild",
  "get_my_guild_member",
  "get_user",
  "list_voice_regions",
  "get_webhook",
  "delete_webhook",
  "update_webhook",
  "get_webhook_by_token",
  "execute_webhook",
  "delete_webhook_by_token",
  "update_webhook_by_token",
  "execute_github_compatible_webhook",
  "get_original_webhook_message",
  "delete_original_webhook_message",
  "update_original_webhook_message",
  "get_webhook_message",
  "delete_webhook_message",
  "update_webhook_message",
  "execute_slack_compatible_webhook"
] as const;
export const DISCORD_HTTP_API_OPERATION_OPERATION_IDS = [
  "get_my_application",
  "update_my_application",
  "get_application",
  "update_application",
  "applications_get_activity_instance",
  "upload_application_attachment",
  "list_application_commands",
  "bulk_set_application_commands",
  "create_application_command",
  "get_application_command",
  "delete_application_command",
  "update_application_command",
  "list_application_emojis",
  "create_application_emoji",
  "get_application_emoji",
  "delete_application_emoji",
  "update_application_emoji",
  "get_entitlements",
  "create_entitlement",
  "get_entitlement",
  "delete_entitlement",
  "consume_entitlement",
  "list_guild_application_commands",
  "bulk_set_guild_application_commands",
  "create_guild_application_command",
  "list_guild_application_command_permissions",
  "get_guild_application_command",
  "delete_guild_application_command",
  "update_guild_application_command",
  "get_guild_application_command_permissions",
  "set_guild_application_command_permissions",
  "get_application_role_connections_metadata",
  "update_application_role_connections_metadata",
  "get_channel",
  "delete_channel",
  "update_channel",
  "follow_channel",
  "list_channel_invites",
  "create_channel_invite",
  "list_messages",
  "create_message",
  "bulk_delete_messages",
  "list_pins",
  "create_pin",
  "delete_pin",
  "get_message",
  "delete_message",
  "update_message",
  "crosspost_message",
  "delete_all_message_reactions",
  "list_message_reactions_by_emoji",
  "delete_all_message_reactions_by_emoji",
  "add_my_message_reaction",
  "delete_my_message_reaction",
  "delete_user_message_reaction",
  "create_thread_from_message",
  "set_channel_permission_overwrite",
  "delete_channel_permission_overwrite",
  "deprecated_list_pins",
  "deprecated_create_pin",
  "deprecated_delete_pin",
  "get_answer_voters",
  "poll_expire",
  "add_group_dm_user",
  "delete_group_dm_user",
  "send_soundboard_sound",
  "list_thread_members",
  "join_thread",
  "leave_thread",
  "get_thread_member",
  "add_thread_member",
  "delete_thread_member",
  "create_thread",
  "list_private_archived_threads",
  "list_public_archived_threads",
  "thread_search",
  "trigger_typing_indicator",
  "list_my_private_archived_threads",
  "update_voice_channel_status",
  "list_channel_webhooks",
  "create_webhook",
  "get_gateway",
  "get_bot_gateway",
  "get_guild_template",
  "get_guild",
  "update_guild",
  "list_guild_audit_log_entries",
  "list_auto_moderation_rules",
  "create_auto_moderation_rule",
  "get_auto_moderation_rule",
  "delete_auto_moderation_rule",
  "update_auto_moderation_rule",
  "list_guild_bans",
  "get_guild_ban",
  "ban_user_from_guild",
  "unban_user_from_guild",
  "bulk_ban_users_from_guild",
  "list_guild_channels",
  "create_guild_channel",
  "bulk_update_guild_channels",
  "list_guild_emojis",
  "create_guild_emoji",
  "get_guild_emoji",
  "delete_guild_emoji",
  "update_guild_emoji",
  "update_guild_incident_actions",
  "list_guild_integrations",
  "delete_guild_integration",
  "list_guild_invites",
  "list_guild_members",
  "update_my_guild_member",
  "search_guild_members",
  "get_guild_member",
  "add_guild_member",
  "delete_guild_member",
  "update_guild_member",
  "add_guild_member_role",
  "delete_guild_member_role",
  "guild_search",
  "get_guild_new_member_welcome",
  "get_guilds_onboarding",
  "put_guilds_onboarding",
  "get_guild_preview",
  "preview_prune_guild",
  "prune_guild",
  "list_guild_voice_regions",
  "get_guild_join_requests",
  "action_guild_join_request",
  "list_guild_roles",
  "create_guild_role",
  "bulk_update_guild_roles",
  "guild_role_member_counts",
  "get_guild_role",
  "delete_guild_role",
  "update_guild_role",
  "list_guild_scheduled_events",
  "create_guild_scheduled_event",
  "get_guild_scheduled_event",
  "delete_guild_scheduled_event",
  "update_guild_scheduled_event",
  "create_guild_scheduled_event_exception",
  "delete_guild_scheduled_event_exception",
  "update_guild_scheduled_event_exception",
  "list_guild_scheduled_event_users",
  "count_guild_scheduled_event_users",
  "list_guild_scheduled_event_exception_users",
  "list_guild_soundboard_sounds",
  "create_guild_soundboard_sound",
  "get_guild_soundboard_sound",
  "delete_guild_soundboard_sound",
  "update_guild_soundboard_sound",
  "list_guild_stickers",
  "create_guild_sticker",
  "get_guild_sticker",
  "delete_guild_sticker",
  "update_guild_sticker",
  "list_guild_templates",
  "create_guild_template",
  "sync_guild_template",
  "delete_guild_template",
  "update_guild_template",
  "get_active_guild_threads",
  "get_guild_vanity_url",
  "get_self_voice_state",
  "update_self_voice_state",
  "get_voice_state",
  "update_voice_state",
  "get_guild_webhooks",
  "get_guild_welcome_screen",
  "update_guild_welcome_screen",
  "get_guild_widget_settings",
  "update_guild_widget_settings",
  "get_guild_widget",
  "get_guild_widget_png",
  "create_interaction_response",
  "invite_resolve",
  "invite_revoke",
  "get_invite_target_users",
  "update_invite_target_users",
  "get_invite_target_users_job_status",
  "create_or_join_lobby",
  "create_lobby",
  "get_lobby",
  "delete_lobby",
  "edit_lobby",
  "edit_lobby_channel_link",
  "leave_lobby",
  "create_linked_lobby_guild_invite_for_self",
  "bulk_update_lobby_members",
  "add_lobby_member",
  "delete_lobby_member",
  "create_linked_lobby_guild_invite_for_user",
  "get_lobby_messages",
  "create_lobby_message",
  "update_lobby_message_external_moderation_metadata",
  "get_my_oauth2_authorization",
  "get_my_oauth2_application",
  "get_public_keys",
  "get_openid_connect_userinfo",
  "update_user_message_external_moderation_metadata",
  "partner_sdk_unmerge_provisional_account",
  "bot_partner_sdk_unmerge_provisional_account",
  "partner_sdk_token",
  "bot_partner_sdk_token",
  "get_sku_subscriptions",
  "get_sku_subscription",
  "get_soundboard_default_sounds",
  "create_stage_instance",
  "get_stage_instance",
  "delete_stage_instance",
  "update_stage_instance",
  "list_sticker_packs",
  "get_sticker_pack",
  "get_sticker",
  "get_my_user",
  "update_my_user",
  "get_current_user_application_entitlements",
  "get_application_user_role_connection",
  "update_application_user_role_connection",
  "delete_application_user_role_connection",
  "create_dm",
  "list_my_connections",
  "list_my_guilds",
  "leave_guild",
  "get_my_guild_member",
  "get_user",
  "list_voice_regions",
  "get_webhook",
  "delete_webhook",
  "update_webhook",
  "get_webhook_by_token",
  "execute_webhook",
  "delete_webhook_by_token",
  "update_webhook_by_token",
  "execute_github_compatible_webhook",
  "get_original_webhook_message",
  "delete_original_webhook_message",
  "update_original_webhook_message",
  "get_webhook_message",
  "delete_webhook_message",
  "update_webhook_message",
  "execute_slack_compatible_webhook"
] as const;
export const DISCORD_HTTP_API_OPERATION_UIDS = [
  "GET /applications/@me",
  "PATCH /applications/@me",
  "GET /applications/{application_id}",
  "PATCH /applications/{application_id}",
  "GET /applications/{application_id}/activity-instances/{instance_id}",
  "POST /applications/{application_id}/attachment",
  "GET /applications/{application_id}/commands",
  "PUT /applications/{application_id}/commands",
  "POST /applications/{application_id}/commands",
  "GET /applications/{application_id}/commands/{command_id}",
  "DELETE /applications/{application_id}/commands/{command_id}",
  "PATCH /applications/{application_id}/commands/{command_id}",
  "GET /applications/{application_id}/emojis",
  "POST /applications/{application_id}/emojis",
  "GET /applications/{application_id}/emojis/{emoji_id}",
  "DELETE /applications/{application_id}/emojis/{emoji_id}",
  "PATCH /applications/{application_id}/emojis/{emoji_id}",
  "GET /applications/{application_id}/entitlements",
  "POST /applications/{application_id}/entitlements",
  "GET /applications/{application_id}/entitlements/{entitlement_id}",
  "DELETE /applications/{application_id}/entitlements/{entitlement_id}",
  "POST /applications/{application_id}/entitlements/{entitlement_id}/consume",
  "GET /applications/{application_id}/guilds/{guild_id}/commands",
  "PUT /applications/{application_id}/guilds/{guild_id}/commands",
  "POST /applications/{application_id}/guilds/{guild_id}/commands",
  "GET /applications/{application_id}/guilds/{guild_id}/commands/permissions",
  "GET /applications/{application_id}/guilds/{guild_id}/commands/{command_id}",
  "DELETE /applications/{application_id}/guilds/{guild_id}/commands/{command_id}",
  "PATCH /applications/{application_id}/guilds/{guild_id}/commands/{command_id}",
  "GET /applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions",
  "PUT /applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions",
  "GET /applications/{application_id}/role-connections/metadata",
  "PUT /applications/{application_id}/role-connections/metadata",
  "GET /channels/{channel_id}",
  "DELETE /channels/{channel_id}",
  "PATCH /channels/{channel_id}",
  "POST /channels/{channel_id}/followers",
  "GET /channels/{channel_id}/invites",
  "POST /channels/{channel_id}/invites",
  "GET /channels/{channel_id}/messages",
  "POST /channels/{channel_id}/messages",
  "POST /channels/{channel_id}/messages/bulk-delete",
  "GET /channels/{channel_id}/messages/pins",
  "PUT /channels/{channel_id}/messages/pins/{message_id}",
  "DELETE /channels/{channel_id}/messages/pins/{message_id}",
  "GET /channels/{channel_id}/messages/{message_id}",
  "DELETE /channels/{channel_id}/messages/{message_id}",
  "PATCH /channels/{channel_id}/messages/{message_id}",
  "POST /channels/{channel_id}/messages/{message_id}/crosspost",
  "DELETE /channels/{channel_id}/messages/{message_id}/reactions",
  "GET /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}",
  "DELETE /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}",
  "PUT /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me",
  "DELETE /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/@me",
  "DELETE /channels/{channel_id}/messages/{message_id}/reactions/{emoji_name}/{user_id}",
  "POST /channels/{channel_id}/messages/{message_id}/threads",
  "PUT /channels/{channel_id}/permissions/{overwrite_id}",
  "DELETE /channels/{channel_id}/permissions/{overwrite_id}",
  "GET /channels/{channel_id}/pins",
  "PUT /channels/{channel_id}/pins/{message_id}",
  "DELETE /channels/{channel_id}/pins/{message_id}",
  "GET /channels/{channel_id}/polls/{message_id}/answers/{answer_id}",
  "POST /channels/{channel_id}/polls/{message_id}/expire",
  "PUT /channels/{channel_id}/recipients/{user_id}",
  "DELETE /channels/{channel_id}/recipients/{user_id}",
  "POST /channels/{channel_id}/send-soundboard-sound",
  "GET /channels/{channel_id}/thread-members",
  "PUT /channels/{channel_id}/thread-members/@me",
  "DELETE /channels/{channel_id}/thread-members/@me",
  "GET /channels/{channel_id}/thread-members/{user_id}",
  "PUT /channels/{channel_id}/thread-members/{user_id}",
  "DELETE /channels/{channel_id}/thread-members/{user_id}",
  "POST /channels/{channel_id}/threads",
  "GET /channels/{channel_id}/threads/archived/private",
  "GET /channels/{channel_id}/threads/archived/public",
  "GET /channels/{channel_id}/threads/search",
  "POST /channels/{channel_id}/typing",
  "GET /channels/{channel_id}/users/@me/threads/archived/private",
  "PUT /channels/{channel_id}/voice-status",
  "GET /channels/{channel_id}/webhooks",
  "POST /channels/{channel_id}/webhooks",
  "GET /gateway",
  "GET /gateway/bot",
  "GET /guilds/templates/{code}",
  "GET /guilds/{guild_id}",
  "PATCH /guilds/{guild_id}",
  "GET /guilds/{guild_id}/audit-logs",
  "GET /guilds/{guild_id}/auto-moderation/rules",
  "POST /guilds/{guild_id}/auto-moderation/rules",
  "GET /guilds/{guild_id}/auto-moderation/rules/{rule_id}",
  "DELETE /guilds/{guild_id}/auto-moderation/rules/{rule_id}",
  "PATCH /guilds/{guild_id}/auto-moderation/rules/{rule_id}",
  "GET /guilds/{guild_id}/bans",
  "GET /guilds/{guild_id}/bans/{user_id}",
  "PUT /guilds/{guild_id}/bans/{user_id}",
  "DELETE /guilds/{guild_id}/bans/{user_id}",
  "POST /guilds/{guild_id}/bulk-ban",
  "GET /guilds/{guild_id}/channels",
  "POST /guilds/{guild_id}/channels",
  "PATCH /guilds/{guild_id}/channels",
  "GET /guilds/{guild_id}/emojis",
  "POST /guilds/{guild_id}/emojis",
  "GET /guilds/{guild_id}/emojis/{emoji_id}",
  "DELETE /guilds/{guild_id}/emojis/{emoji_id}",
  "PATCH /guilds/{guild_id}/emojis/{emoji_id}",
  "PUT /guilds/{guild_id}/incident-actions",
  "GET /guilds/{guild_id}/integrations",
  "DELETE /guilds/{guild_id}/integrations/{integration_id}",
  "GET /guilds/{guild_id}/invites",
  "GET /guilds/{guild_id}/members",
  "PATCH /guilds/{guild_id}/members/@me",
  "GET /guilds/{guild_id}/members/search",
  "GET /guilds/{guild_id}/members/{user_id}",
  "PUT /guilds/{guild_id}/members/{user_id}",
  "DELETE /guilds/{guild_id}/members/{user_id}",
  "PATCH /guilds/{guild_id}/members/{user_id}",
  "PUT /guilds/{guild_id}/members/{user_id}/roles/{role_id}",
  "DELETE /guilds/{guild_id}/members/{user_id}/roles/{role_id}",
  "GET /guilds/{guild_id}/messages/search",
  "GET /guilds/{guild_id}/new-member-welcome",
  "GET /guilds/{guild_id}/onboarding",
  "PUT /guilds/{guild_id}/onboarding",
  "GET /guilds/{guild_id}/preview",
  "GET /guilds/{guild_id}/prune",
  "POST /guilds/{guild_id}/prune",
  "GET /guilds/{guild_id}/regions",
  "GET /guilds/{guild_id}/requests",
  "PATCH /guilds/{guild_id}/requests/{request_id}",
  "GET /guilds/{guild_id}/roles",
  "POST /guilds/{guild_id}/roles",
  "PATCH /guilds/{guild_id}/roles",
  "GET /guilds/{guild_id}/roles/member-counts",
  "GET /guilds/{guild_id}/roles/{role_id}",
  "DELETE /guilds/{guild_id}/roles/{role_id}",
  "PATCH /guilds/{guild_id}/roles/{role_id}",
  "GET /guilds/{guild_id}/scheduled-events",
  "POST /guilds/{guild_id}/scheduled-events",
  "GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}",
  "DELETE /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}",
  "PATCH /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}",
  "POST /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions",
  "DELETE /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}",
  "PATCH /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/exceptions/{exception_id}",
  "GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users",
  "GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users/counts",
  "GET /guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/{guild_scheduled_event_exception_id}/users",
  "GET /guilds/{guild_id}/soundboard-sounds",
  "POST /guilds/{guild_id}/soundboard-sounds",
  "GET /guilds/{guild_id}/soundboard-sounds/{sound_id}",
  "DELETE /guilds/{guild_id}/soundboard-sounds/{sound_id}",
  "PATCH /guilds/{guild_id}/soundboard-sounds/{sound_id}",
  "GET /guilds/{guild_id}/stickers",
  "POST /guilds/{guild_id}/stickers",
  "GET /guilds/{guild_id}/stickers/{sticker_id}",
  "DELETE /guilds/{guild_id}/stickers/{sticker_id}",
  "PATCH /guilds/{guild_id}/stickers/{sticker_id}",
  "GET /guilds/{guild_id}/templates",
  "POST /guilds/{guild_id}/templates",
  "PUT /guilds/{guild_id}/templates/{code}",
  "DELETE /guilds/{guild_id}/templates/{code}",
  "PATCH /guilds/{guild_id}/templates/{code}",
  "GET /guilds/{guild_id}/threads/active",
  "GET /guilds/{guild_id}/vanity-url",
  "GET /guilds/{guild_id}/voice-states/@me",
  "PATCH /guilds/{guild_id}/voice-states/@me",
  "GET /guilds/{guild_id}/voice-states/{user_id}",
  "PATCH /guilds/{guild_id}/voice-states/{user_id}",
  "GET /guilds/{guild_id}/webhooks",
  "GET /guilds/{guild_id}/welcome-screen",
  "PATCH /guilds/{guild_id}/welcome-screen",
  "GET /guilds/{guild_id}/widget",
  "PATCH /guilds/{guild_id}/widget",
  "GET /guilds/{guild_id}/widget.json",
  "GET /guilds/{guild_id}/widget.png",
  "POST /interactions/{interaction_id}/{interaction_token}/callback",
  "GET /invites/{code}",
  "DELETE /invites/{code}",
  "GET /invites/{code}/target-users",
  "PUT /invites/{code}/target-users",
  "GET /invites/{code}/target-users/job-status",
  "PUT /lobbies",
  "POST /lobbies",
  "GET /lobbies/{lobby_id}",
  "DELETE /lobbies/{lobby_id}",
  "PATCH /lobbies/{lobby_id}",
  "PATCH /lobbies/{lobby_id}/channel-linking",
  "DELETE /lobbies/{lobby_id}/members/@me",
  "POST /lobbies/{lobby_id}/members/@me/invites",
  "POST /lobbies/{lobby_id}/members/bulk",
  "PUT /lobbies/{lobby_id}/members/{user_id}",
  "DELETE /lobbies/{lobby_id}/members/{user_id}",
  "POST /lobbies/{lobby_id}/members/{user_id}/invites",
  "GET /lobbies/{lobby_id}/messages",
  "POST /lobbies/{lobby_id}/messages",
  "PUT /lobbies/{lobby_id}/messages/{message_id}/moderation-metadata",
  "GET /oauth2/@me",
  "GET /oauth2/applications/@me",
  "GET /oauth2/keys",
  "GET /oauth2/userinfo",
  "PUT /partner-sdk/dms/{user_id_1}/{user_id_2}/messages/{message_id}/moderation-metadata",
  "POST /partner-sdk/provisional-accounts/unmerge",
  "POST /partner-sdk/provisional-accounts/unmerge/bot",
  "POST /partner-sdk/token",
  "POST /partner-sdk/token/bot",
  "GET /skus/{sku_id}/subscriptions",
  "GET /skus/{sku_id}/subscriptions/{subscription_id}",
  "GET /soundboard-default-sounds",
  "POST /stage-instances",
  "GET /stage-instances/{channel_id}",
  "DELETE /stage-instances/{channel_id}",
  "PATCH /stage-instances/{channel_id}",
  "GET /sticker-packs",
  "GET /sticker-packs/{pack_id}",
  "GET /stickers/{sticker_id}",
  "GET /users/@me",
  "PATCH /users/@me",
  "GET /users/@me/applications/{application_id}/entitlements",
  "GET /users/@me/applications/{application_id}/role-connection",
  "PUT /users/@me/applications/{application_id}/role-connection",
  "DELETE /users/@me/applications/{application_id}/role-connection",
  "POST /users/@me/channels",
  "GET /users/@me/connections",
  "GET /users/@me/guilds",
  "DELETE /users/@me/guilds/{guild_id}",
  "GET /users/@me/guilds/{guild_id}/member",
  "GET /users/{user_id}",
  "GET /voice/regions",
  "GET /webhooks/{webhook_id}",
  "DELETE /webhooks/{webhook_id}",
  "PATCH /webhooks/{webhook_id}",
  "GET /webhooks/{webhook_id}/{webhook_token}",
  "POST /webhooks/{webhook_id}/{webhook_token}",
  "DELETE /webhooks/{webhook_id}/{webhook_token}",
  "PATCH /webhooks/{webhook_id}/{webhook_token}",
  "POST /webhooks/{webhook_id}/{webhook_token}/github",
  "GET /webhooks/{webhook_id}/{webhook_token}/messages/@original",
  "DELETE /webhooks/{webhook_id}/{webhook_token}/messages/@original",
  "PATCH /webhooks/{webhook_id}/{webhook_token}/messages/@original",
  "GET /webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
  "DELETE /webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
  "PATCH /webhooks/{webhook_id}/{webhook_token}/messages/{message_id}",
  "POST /webhooks/{webhook_id}/{webhook_token}/slack"
] as const;
// End hardened literal operation keys.
export const DISCORD_HTTP_API_OPERATION_BY_UID = new Map(DISCORD_HTTP_API_OPERATIONS.map((operation) => [operation.uid, operation]));
export const DISCORD_HTTP_API_OPERATION_BY_ID = new Map<string, DiscordHttpApiOperation>();
for (const operation of DISCORD_HTTP_API_OPERATIONS) {
  if (!DISCORD_HTTP_API_OPERATION_BY_ID.has(operation.operationId)) {
    DISCORD_HTTP_API_OPERATION_BY_ID.set(operation.operationId, operation);
  }
}

export type DiscordHttpApiOperationUid = typeof DISCORD_HTTP_API_OPERATION_UIDS[number];
