import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { DISCORD_HTTP_API_GENERATED_FUNCTION_COUNT } from "./http-api-client.generated.js";
import {
  DISCORD_HTTP_API_OPERATION_COUNT,
  DISCORD_HTTP_API_PATH_COUNT,
  DISCORD_HTTP_API_SPEC_VERSION,
} from "./http-api-operations.generated.js";

export const discordCommunityProviderManifest = defineProviderPackage({
  id: "community.discord",
  name: "Discord Community Support",
  packageName: "@cognidesk/integrations",
  provider: "discord",
  category: "community",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  credentialRequirements: [
    {
      id: "discord-bot-token",
      label: "Discord bot token",
      description: "Server-side Discord bot token used for REST channel, guild, and bot/application readiness calls.",
      scopes: ["bot", "applications.commands"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "discord-application-id",
      label: "Discord application ID",
      description: "SDK-user-owned Discord application ID used to identify commands, interactions, and installation readiness.",
      required: true,
    },
    {
      id: "discord-public-key",
      label: "Discord interaction public key",
      description: "Ed25519 public key from the Discord Developer Portal for validating interaction endpoint requests.",
      required: true,
    },
    {
      id: "discord-guild-id",
      label: "Discord guild ID",
      description: "Guild/server ID selected by SDK configuration for community support routing and live checks.",
      required: false,
    },
    {
      id: "discord-channel-id",
      label: "Discord channel or forum ID",
      description: "Channel, forum, or media channel ID selected by SDK configuration for message and thread operations.",
      required: false,
    },
    {
      id: "discord-webhook-url",
      label: "Discord webhook URL",
      description: "Optional SDK-user-owned webhook URL for Discord webhook delivery or webhook-based outbound messages.",
      required: false,
    },
  ],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Discord's official HTTP API v10 OpenAPI preview spec.",
      "Typed convenience helpers remain available for selected Discord community support workflows: channel messages, text/forum/media-channel threads, webhook execution, selected bot/application/guild/channel reads, channel message listing, and Ed25519 interaction signature verification.",
      "Discord marks the OpenAPI spec as a public preview and says the docs take precedence over spec discrepancies; the generated HTTP API surface is a cataloged transport slice, not a claim that Discord's full platform is covered.",
      "Receive coverage is the Discord Interactions Endpoint URL/outgoing-webhook path only; Discord Gateway ingestion and Discord Webhook Events subscriptions are outside this package.",
      "Non-HTTP Discord surfaces remain unsupported here: Gateway WebSocket sessions/events/intents, Voice Gateway/media transport, local RPC/IPC, Social SDK client features, CDN asset transformation semantics beyond HTTP calls, and Webhook Events subscription delivery.",
    ],
    evidence: [
      { label: "Discord official OpenAPI v10 spec", url: "https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi.json" },
      { label: "Discord official OpenAPI repository", url: "https://github.com/discord/discord-api-spec" },
      { label: "Discord API reference", url: "https://docs.discord.com/developers/reference" },
      { label: "Discord message resource", url: "https://docs.discord.com/developers/resources/message" },
      { label: "Discord channel/thread endpoints", url: "https://docs.discord.com/developers/resources/channel" },
      { label: "Discord threads topic", url: "https://docs.discord.com/developers/topics/threads" },
      { label: "Discord receiving and responding to interactions", url: "https://docs.discord.com/developers/interactions/receiving-and-responding" },
      { label: "Discord Gateway events", url: "https://docs.discord.com/developers/events/gateway" },
      { label: "Discord Voice connections", url: "https://docs.discord.com/developers/topics/voice-connections" },
      { label: "Discord RPC", url: "https://docs.discord.com/developers/topics/rpc" },
      { label: "Discord Webhook Events", url: "https://docs.discord.com/developers/events/webhook-events" },
      { label: "Discord rate limits", url: "https://docs.discord.com/developers/topics/rate-limits" },
    ],
  },
  capabilities: [
    {
      capability: "receive",
      label: "Receive Discord interactions",
      description: "Validates Ed25519-signed Discord outgoing-webhook interaction requests; does not subscribe to Gateway message events.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "discordInteraction", label: "Discord Interaction" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Discord channel messages",
      description: "Sends bot-token-authenticated Discord channel messages when SDK-user policy permits public or private community replies.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "discordMessage", label: "Discord Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Create Discord support threads",
      description: "Creates Discord text-channel threads or forum/media channel posts selected by SDK configuration.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "discordThread", label: "Discord Thread" },
        { kind: "discordForumPost", label: "Discord Forum Post" },
        { kind: "discordMediaPost", label: "Discord Media Channel Post" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Discord channels and messages",
      description: "Reads Discord channel metadata and recent channel messages where bot permissions allow access.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "discordChannel", label: "Discord Channel" },
        { kind: "discordMessage", label: "Discord Message" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "notify",
      label: "Notify Discord moderators",
      description: "Uses SDK-user-selected Discord channels, threads, or Discord webhook URLs for moderator notification and community escalation workflows.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "discordMessage", label: "Discord Message" },
        { kind: "discordWebhookMessage", label: "Discord Webhook Message" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "discord.interaction-signature",
      label: "Validate Discord interaction signatures",
      description: "Validates X-Signature-Ed25519 and X-Signature-Timestamp headers with the SDK user's Discord application public key.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "discordSignedInteraction", label: "Discord Signed Interaction" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Discord messages, user IDs, guild IDs, channel IDs, thread IDs, usernames, attachments, embeds, and interaction payloads can contain customer and moderator data.",
    "Discord bot tokens, public keys, application IDs, guild/channel routing, webhook URLs, consent, moderation, retention, and transcript policy stay SDK-user-owned configuration.",
  ],
  limitations: [
    "Available REST operations depend on the SDK user's Discord application, bot installation, OAuth scopes, role permissions, channel permissions, forum settings, and rate limits.",
    "Gateway intents are required only for SDK-user-owned Gateway integrations outside this package; this package does not ingest Gateway events or Discord Webhook Events subscriptions.",
    "Discord rate limits use per-route and global buckets with Retry-After/retry_after details; SDK users own retry and backoff policy.",
    "This package provides transport, readiness, and parsing helpers only; moderation policy, consent, public/private reply policy, escalation, retention, deletion, and human handoff are SDK-user configuration.",
    "Discord interaction endpoint requests must fail closed when signature verification is required but the public key or signature headers are missing or invalid.",
  ],
  metadata: {
    apiBaseUrl: "https://discord.com/api",
    defaultApiVersion: "v10",
    interactionSignatureHeaders: ["x-signature-ed25519", "x-signature-timestamp"],
    channelCoverage: {
      httpApiV10: "generated-per-operation-functions",
      channelMessages: "typed-send-list",
      threads: "typed-create",
      forumPosts: "typed-create",
      mediaPosts: "typed-create",
      webhookExecution: "typed-send",
      interactionsEndpoint: "typed-verify-parse",
      botApplicationGuildChannelReads: "typed-read",
      gatewayEvents: "provider-supported-not-typed",
      webhookEventsSubscriptions: "provider-supported-not-typed",
      voiceGatewayAndRpc: "provider-supported-not-typed",
      moderationScheduledEventsCommandsLifecycle: "generated-http-functions",
    },
    generatedProviderSliceVerification: {
      provider: "discord-http-api-v10-preview-openapi",
      apiVersion: DISCORD_HTTP_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/discord-http-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/discord-http-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/discord-http-api-2026-06-18.functions.json",
      documentedPathCount: DISCORD_HTTP_API_PATH_COUNT,
      documentedOperationCount: DISCORD_HTTP_API_OPERATION_COUNT,
      implementedOperationCount: DISCORD_HTTP_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: DISCORD_HTTP_API_GENERATED_FUNCTION_COUNT,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
