import { defineIntegrationProviderPackage } from "@cognidesk/integration-kit";

export const twilioSmsProviderManifest = defineIntegrationProviderPackage({
  id: "sms.twilio",
  name: "Twilio Programmable Messaging",
  packageName: "@cognidesk/integration-sms-twilio",
  provider: "twilio",
  category: "sms",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Implements normalized SMS/MMS send, read, list, cancel, readiness, webhook, and Twilio SDK client access with the official Twilio Node helper library.",
      "Twilio SMS and Twilio Voice are separate Cognidesk category packages even though they use the same upstream helper library.",
      "Messaging Services administration, Verify, Conversations, Content, Studio, toll-free/A2P compliance, pricing, and carrier policy remain available only through raw Twilio client access or future normalized operations.",
    ],
    evidence: [
      { label: "Twilio Node helper library", url: "https://www.npmjs.com/package/twilio" },
      { label: "Twilio Messaging API overview", url: "https://www.twilio.com/docs/messaging/api" },
      { label: "Twilio Message resource", url: "https://www.twilio.com/docs/messaging/api/message-resource" },
      { label: "Twilio webhook security", url: "https://www.twilio.com/docs/usage/webhooks/webhooks-security" },
    ],
  },
  credentialRequirements: [
    {
      id: "twilio-account",
      label: "Twilio Account SID and Auth Token",
      description: "Server-side Twilio account credentials used for Messaging REST API calls and webhook signature validation.",
      required: true,
      metadata: { scopeKind: "provider-permission" },
    },
    {
      id: "twilio-sms-sender",
      label: "Twilio SMS/MMS-capable sender",
      description: "A Twilio SMS/MMS-capable phone number or Messaging Service configured by the SDK user.",
      required: true,
      metadata: { scopeKind: "internal-capability" },
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive inbound SMS/MMS",
      description: "Validates and parses Twilio Messaging webhooks for SDK-user-owned SMS/MMS handling.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send SMS/MMS messages",
      description: "Creates outbound SMS or MMS messages through the Twilio helper library.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "schedule",
      label: "Schedule SMS/MMS messages",
      description: "Schedules outbound messages through Twilio's Message Scheduling fields when a Messaging Service SID, SendAt, and ScheduleType are supplied.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Twilio messages",
      description: "Reads Twilio Message resources by Message SID.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "List Twilio messages",
      description: "Lists Twilio Message resources with SDK-user-supplied filters.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "twilioMessage", label: "Twilio Message" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "twilio.webhook-signature",
      label: "Validate Twilio webhooks",
      description: "Validates X-Twilio-Signature for form-encoded Twilio Messaging webhooks and status callbacks.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "twilioWebhook", label: "Twilio Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "sms.message.receive",
      providerOperation: "parseWebhook",
      capability: "receive",
      label: "Receive SMS",
      providerObject: "smsMessage",
      audiences: ["customer-facing"],
      exposesSensitiveData: true,
    },
    {
      alias: "sms.message.send",
      providerOperation: "sendMessage",
      capability: "send",
      label: "Send SMS",
      providerObject: "smsMessage",
      audiences: ["customer-facing"],
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    },
    {
      alias: "sms.message.read",
      providerOperation: "fetchMessage",
      capability: "read-provider-object",
      label: "Read SMS",
      providerObject: "smsMessage",
      audiences: ["customer-facing", "internal-support"],
      exposesSensitiveData: true,
    },
    {
      alias: "sms.message.search",
      providerOperation: "listMessages",
      capability: "search-provider-object",
      label: "Search SMS",
      providerObject: "smsMessage",
      audiences: ["customer-facing", "internal-support"],
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Phone numbers, message bodies, message metadata, webhook parameters, delivery status, and media URLs can contain customer data and are exchanged with Twilio.",
    "Twilio credentials stay server-side and are never issued to browsers by this package.",
    "Outbound SMS consent, opt-in/opt-out handling, quiet hours, campaign registration, content policy, retention, and regional compliance are SDK-user-owned responsibilities.",
  ],
  limitations: [
    "Live SMS readiness depends on the SDK user's Twilio account, SMS-capable sender, Messaging Service configuration, phone-number capabilities, regions, carrier registration, webhooks, and account permissions.",
  ],
  metadata: {
    implementation: {
      strategy: "official-sdk",
      sdkPackage: "twilio",
      verifiedVersion: "6.0.2",
      verifiedAt: "2026-06-21",
    },
    sdkClient: {
      export: "getSdkClient",
      coverage: "deprecated-raw-client-alias",
    },
    rawClient: {
      export: "getRawClient",
      coverage: "upstream-sdk",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
