import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { GMAIL_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  GMAIL_FULL_API_OPERATION_COUNT,
  GMAIL_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const gmailEmailProviderManifest = defineProviderPackage({
  id: "email.gmail",
  name: "Gmail",
  packageName: "@cognidesk/integrations",
  provider: "gmail",
  category: "email",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-method functions for every method in the official Gmail API Discovery document.",
      "The package keeps typed helpers for selected Gmail support workflows: message list/get, draft creation, message send, label modify, profile readiness, watch/history sync foundations, attachment fetch, and label listing.",
      "Gmail OAuth permissions are operation-specific alternatives, not one required bundle; SDK users may choose narrower scopes such as gmail.metadata where the selected Gmail method supports it.",
      "Receive coverage is Gmail API read/watch/history foundation only; Google Cloud Pub/Sub push notification parsing, Pub/Sub authentication, and webhook hosting are SDK-user integration responsibilities.",
    ],
    evidence: [
      { label: "Gmail API Discovery document", url: "https://gmail.googleapis.com/$discovery/rest?version=v1" },
      { label: "Gmail messages list", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/list" },
      { label: "Gmail users getProfile", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users/getProfile" },
      { label: "Gmail drafts create", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.drafts/create" },
      { label: "Gmail messages send", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/send" },
      { label: "Gmail messages modify", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/modify" },
      { label: "Gmail watch", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users/watch" },
      { label: "Gmail history list", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.history/list" },
      { label: "Gmail push notifications", url: "https://developers.google.com/workspace/gmail/api/guides/push" },
      { label: "Gmail attachment get", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages.attachments/get" },
      { label: "Gmail labels list", url: "https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.labels/list" },
    ],
  },
  credentialRequirements: [
    {
      id: "google-oauth-access-token",
      label: "Google OAuth access token",
      description: "Server-side OAuth access token for the Gmail API.",
      scopes: [
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.send",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.metadata",
      ],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Read Gmail messages",
      description: "Lists and reads Gmail message metadata, payloads, raw messages, or thread context.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "gmailMessage", label: "Gmail Message" },
        { kind: "gmailThread", label: "Gmail Thread" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Create Gmail drafts",
      description: "Creates Gmail draft messages for SDK-user-configured approval workflows.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "gmailDraft", label: "Gmail Draft" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Gmail messages",
      description: "Sends Gmail messages or existing drafts when SDK-user policy permits outbound contact.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "gmailMessage", label: "Gmail Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use Gmail threads",
      description: "Associates messages and drafts with Gmail thread IDs selected by SDK configuration.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "gmailThread", label: "Gmail Thread" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "attach",
      label: "Read Gmail attachment content",
      description: "Reads Gmail message payload parts and attachment bodies for SDK-user-governed attachment handling.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "gmailAttachment", label: "Gmail Attachment" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Modify Gmail labels",
      description: "Adds or removes Gmail labels, such as marking a message read, when SDK-user policy permits mutation.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "gmailMessage", label: "Gmail Message" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "Gmail messages can contain customer content, attachments, addresses, labels, and thread history.",
    "OAuth tokens stay server-side and are represented in Studio only as credential readiness.",
  ],
  limitations: [
    "Available operations depend on the OAuth scopes, Google Workspace policy, delegated user, and mailbox state configured by the SDK user.",
    "Gmail watch notifications require an SDK-user-managed Google Cloud Pub/Sub topic, subscription, webhook/worker, and history synchronization strategy.",
    "Draft approval, auto-send, retention, redaction, and outbound-contact policy are SDK-user configuration.",
  ],
  metadata: {
    channelCoverage: {
      fullGmailRestApiMethods: "generated-per-operation-functions",
      gmailMessages: "typed-list-get-send-modify-and-generated-full-surface",
      gmailDrafts: "typed-create-send-and-generated-full-surface",
      gmailThreads: "typed-reference-read-and-generated-full-surface",
      gmailAttachments: "typed-read-and-generated-full-surface",
      gmailLabels: "typed-list-modify-on-message-and-generated-full-surface",
      gmailSettingsFiltersDelegatesSendAsSmime: "generated-full-surface",
      gmailWatchHistory: "typed-watch-history-foundation-and-generated-full-surface",
      pubSubPushDelivery: "sdk-owned-not-covered",
    },
    fullProviderApiVerification: {
      provider: "gmail",
      apiVersion: GMAIL_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-17",
      coverageArtifact: "docs/provider-coverage/gmail-full-api-2026-06-17.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/gmail-full-api-2026-06-17.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/gmail-full-api-2026-06-17.functions.json",
      documentedOperationCount: GMAIL_FULL_API_OPERATION_COUNT,
      implementedOperationCount: GMAIL_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: GMAIL_FULL_API_GENERATED_FUNCTION_COUNT,
    },
    scopeAlternatives: {
      profile: [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.metadata",
      ],
      watch: [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.metadata",
      ],
      send: [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.send",
      ],
      metadataOnlyCaveat: "Gmail metadata-only scopes support profile/watch/read metadata surfaces, but SDK users must avoid query-dependent message listing where the Gmail API disallows q with gmail.metadata.",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
