// Generated from Deepgram official OpenAPI (https://developers.deepgram.com/openapi.json).
// Do not edit by hand; run scripts/generate-speech-provider-apis.mjs after checking upstream docs.

import type { DeepgramSpeechOperationRequestInput } from "./index.js";
import type {
  DeepgramSpeechFullApiOperationQueryMap,
  DeepgramSpeechFullApiOperationQueryRequiredMap,
  DeepgramSpeechFullApiOperationRequestBodyMap,
  DeepgramSpeechFullApiOperationRequestBodyRequiredMap,
  DeepgramSpeechFullApiOperationResponseMap,
} from "./full-api-schema-types.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageAgentSubpackageAgentV1SubpackageAgentV1SettingsSubpackageAgentV1SettingsThinkSubpackageAgentV1SettingsThinkModelsGeneratedClient,
  DeepgramSpeechFullApiSubpackageAgentSubpackageAgentV1SubpackageAgentV1SettingsSubpackageAgentV1SettingsThinkSubpackageAgentV1SettingsThinkModelsGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageAgentSubpackageAgentV1SubpackageAgentV1SettingsSubpackageAgentV1SettingsThinkSubpackageAgentV1SettingsThinkModelsGeneratedClient,
  type DeepgramSpeechFullApiSubpackageAgentSubpackageAgentV1SubpackageAgentV1SettingsSubpackageAgentV1SettingsThinkSubpackageAgentV1SettingsThinkModelsOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageAgentSubpackageAgentV1SubpackageAgentV1SettingsSubpackageAgentV1SettingsThinkSubpackageAgentV1SettingsThinkModelsOperationRequestMap,
} from "./full-api.generated/client/subpackage-agent-subpackage-agent-v1-subpackage-agent-v1-settings-subpackage-agent-v1-settings-think-subpackage-agent-v1-settings-think-models-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageAuthSubpackageAuthV1SubpackageAuthV1TokensGeneratedClient,
  DeepgramSpeechFullApiSubpackageAuthSubpackageAuthV1SubpackageAuthV1TokensGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageAuthSubpackageAuthV1SubpackageAuthV1TokensGeneratedClient,
  type DeepgramSpeechFullApiSubpackageAuthSubpackageAuthV1SubpackageAuthV1TokensOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageAuthSubpackageAuthV1SubpackageAuthV1TokensOperationRequestMap,
} from "./full-api.generated/client/subpackage-auth-subpackage-auth-v1-subpackage-auth-v1-tokens-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageListenSubpackageListenV1SubpackageListenV1MediaGeneratedClient,
  DeepgramSpeechFullApiSubpackageListenSubpackageListenV1SubpackageListenV1MediaGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageListenSubpackageListenV1SubpackageListenV1MediaGeneratedClient,
  type DeepgramSpeechFullApiSubpackageListenSubpackageListenV1SubpackageListenV1MediaOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageListenSubpackageListenV1SubpackageListenV1MediaOperationRequestMap,
} from "./full-api.generated/client/subpackage-listen-subpackage-listen-v1-subpackage-listen-v1-media-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ModelsGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ModelsGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ModelsGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ModelsOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ModelsOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-models-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBalancesGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBalancesGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBalancesGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBalancesOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBalancesOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-billing-subpackage-manage-v1-projects-billing-balances-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBreakdownGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBreakdownGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBreakdownGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBreakdownOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBreakdownOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-billing-subpackage-manage-v1-projects-billing-breakdown-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingFieldsGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingFieldsGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingFieldsGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingFieldsOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingFieldsOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-billing-subpackage-manage-v1-projects-billing-fields-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingPurchasesGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingPurchasesGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingPurchasesGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingPurchasesOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingPurchasesOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-billing-subpackage-manage-v1-projects-billing-purchases-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsKeysGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsKeysGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsKeysGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsKeysOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsKeysOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-keys-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-members-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersInvitesGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersInvitesGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersInvitesGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersInvitesOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersInvitesOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-members-subpackage-manage-v1-projects-members-invites-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersScopesGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersScopesGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersScopesGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersScopesOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersScopesOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-members-subpackage-manage-v1-projects-members-scopes-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsModelsGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsModelsGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsModelsGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsModelsOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsModelsOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-models-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsRequestsGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsRequestsGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsRequestsGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsRequestsOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsRequestsOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-requests-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-usage-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageBreakdownGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageBreakdownGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageBreakdownGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageBreakdownOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageBreakdownOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-usage-subpackage-manage-v1-projects-usage-breakdown-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageFieldsGeneratedClient,
  DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageFieldsGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageFieldsGeneratedClient,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageFieldsOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageFieldsOperationRequestMap,
} from "./full-api.generated/client/subpackage-manage-subpackage-manage-v1-subpackage-manage-v1-projects-subpackage-manage-v1-projects-usage-subpackage-manage-v1-projects-usage-fields-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageReadSubpackageReadV1SubpackageReadV1TextGeneratedClient,
  DeepgramSpeechFullApiSubpackageReadSubpackageReadV1SubpackageReadV1TextGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageReadSubpackageReadV1SubpackageReadV1TextGeneratedClient,
  type DeepgramSpeechFullApiSubpackageReadSubpackageReadV1SubpackageReadV1TextOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageReadSubpackageReadV1SubpackageReadV1TextOperationRequestMap,
} from "./full-api.generated/client/subpackage-read-subpackage-read-v1-subpackage-read-v1-text-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageSelfHostedSubpackageSelfHostedV1SubpackageSelfHostedV1DistributionCredentialsGeneratedClient,
  DeepgramSpeechFullApiSubpackageSelfHostedSubpackageSelfHostedV1SubpackageSelfHostedV1DistributionCredentialsGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageSelfHostedSubpackageSelfHostedV1SubpackageSelfHostedV1DistributionCredentialsGeneratedClient,
  type DeepgramSpeechFullApiSubpackageSelfHostedSubpackageSelfHostedV1SubpackageSelfHostedV1DistributionCredentialsOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageSelfHostedSubpackageSelfHostedV1SubpackageSelfHostedV1DistributionCredentialsOperationRequestMap,
} from "./full-api.generated/client/subpackage-self-hosted-subpackage-self-hosted-v1-subpackage-self-hosted-v1-distribution-credentials-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageSpeakSubpackageSpeakV1SubpackageSpeakV1AudioGeneratedClient,
  DeepgramSpeechFullApiSubpackageSpeakSubpackageSpeakV1SubpackageSpeakV1AudioGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageSpeakSubpackageSpeakV1SubpackageSpeakV1AudioGeneratedClient,
  type DeepgramSpeechFullApiSubpackageSpeakSubpackageSpeakV1SubpackageSpeakV1AudioOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageSpeakSubpackageSpeakV1SubpackageSpeakV1AudioOperationRequestMap,
} from "./full-api.generated/client/subpackage-speak-subpackage-speak-v1-subpackage-speak-v1-audio-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentConfigurationsGeneratedClient,
  DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentConfigurationsGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentConfigurationsGeneratedClient,
  type DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentConfigurationsOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentConfigurationsOperationRequestMap,
} from "./full-api.generated/client/subpackage-voice-agent-subpackage-voice-agent-configurations-chunk.generated.js";
import {
  createDeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentVariablesGeneratedClient,
  DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentVariablesGeneratedFunctionNames,
  type DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentVariablesGeneratedClient,
  type DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentVariablesOperationPathParamMap,
  type DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentVariablesOperationRequestMap,
} from "./full-api.generated/client/subpackage-voice-agent-subpackage-voice-agent-variables-chunk.generated.js";

export type DeepgramSpeechFullApiPathParamValue = string | number;
export interface DeepgramSpeechFullApiOperationPathParamMap extends DeepgramSpeechFullApiSubpackageAgentSubpackageAgentV1SubpackageAgentV1SettingsSubpackageAgentV1SettingsThinkSubpackageAgentV1SettingsThinkModelsOperationPathParamMap, DeepgramSpeechFullApiSubpackageAuthSubpackageAuthV1SubpackageAuthV1TokensOperationPathParamMap, DeepgramSpeechFullApiSubpackageListenSubpackageListenV1SubpackageListenV1MediaOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ModelsOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBalancesOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBreakdownOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingFieldsOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingPurchasesOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsKeysOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersInvitesOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersScopesOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsModelsOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsRequestsOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageBreakdownOperationPathParamMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageFieldsOperationPathParamMap, DeepgramSpeechFullApiSubpackageReadSubpackageReadV1SubpackageReadV1TextOperationPathParamMap, DeepgramSpeechFullApiSubpackageSelfHostedSubpackageSelfHostedV1SubpackageSelfHostedV1DistributionCredentialsOperationPathParamMap, DeepgramSpeechFullApiSubpackageSpeakSubpackageSpeakV1SubpackageSpeakV1AudioOperationPathParamMap, DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentConfigurationsOperationPathParamMap, DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentVariablesOperationPathParamMap {}

export type DeepgramSpeechFullApiOperationKey = keyof DeepgramSpeechFullApiOperationPathParamMap & string;

export type DeepgramSpeechFullApiOperationQueryInput<OperationKey extends DeepgramSpeechFullApiOperationKey> =
  DeepgramSpeechFullApiOperationQueryRequiredMap[OperationKey] extends true
    ? { query: DeepgramSpeechFullApiOperationQueryMap[OperationKey] }
    : { query?: DeepgramSpeechFullApiOperationQueryMap[OperationKey] };

export type DeepgramSpeechFullApiOperationBodyInput<OperationKey extends DeepgramSpeechFullApiOperationKey> =
  [DeepgramSpeechFullApiOperationRequestBodyMap[OperationKey]] extends [never]
    ? { body?: never }
    : DeepgramSpeechFullApiOperationRequestBodyRequiredMap[OperationKey] extends true
      ? { body: DeepgramSpeechFullApiOperationRequestBodyMap[OperationKey] }
      : { body?: DeepgramSpeechFullApiOperationRequestBodyMap[OperationKey] };

export type DeepgramSpeechFullApiOperationInput<OperationKey extends DeepgramSpeechFullApiOperationKey> = Omit<DeepgramSpeechOperationRequestInput, "pathParams" | "query" | "body"> & (
  {} extends DeepgramSpeechFullApiOperationPathParamMap[OperationKey]
    ? { pathParams?: never }
    : { pathParams: DeepgramSpeechFullApiOperationPathParamMap[OperationKey] }
) & DeepgramSpeechFullApiOperationQueryInput<OperationKey> & DeepgramSpeechFullApiOperationBodyInput<OperationKey>;

export interface DeepgramSpeechFullApiOperationRequestMap extends DeepgramSpeechFullApiSubpackageAgentSubpackageAgentV1SubpackageAgentV1SettingsSubpackageAgentV1SettingsThinkSubpackageAgentV1SettingsThinkModelsOperationRequestMap, DeepgramSpeechFullApiSubpackageAuthSubpackageAuthV1SubpackageAuthV1TokensOperationRequestMap, DeepgramSpeechFullApiSubpackageListenSubpackageListenV1SubpackageListenV1MediaOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ModelsOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBalancesOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBreakdownOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingFieldsOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingPurchasesOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsKeysOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersInvitesOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersScopesOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsModelsOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsRequestsOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageBreakdownOperationRequestMap, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageFieldsOperationRequestMap, DeepgramSpeechFullApiSubpackageReadSubpackageReadV1SubpackageReadV1TextOperationRequestMap, DeepgramSpeechFullApiSubpackageSelfHostedSubpackageSelfHostedV1SubpackageSelfHostedV1DistributionCredentialsOperationRequestMap, DeepgramSpeechFullApiSubpackageSpeakSubpackageSpeakV1SubpackageSpeakV1AudioOperationRequestMap, DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentConfigurationsOperationRequestMap, DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentVariablesOperationRequestMap {}

export type DeepgramSpeechFullApiOperationArgs<OperationKey extends DeepgramSpeechFullApiOperationKey> = {} extends DeepgramSpeechFullApiOperationPathParamMap[OperationKey]
  ? [input?: DeepgramSpeechFullApiOperationRequestMap[OperationKey]]
  : [input: DeepgramSpeechFullApiOperationRequestMap[OperationKey]];

export type DeepgramSpeechGeneratedOperationCaller = <OperationKey extends DeepgramSpeechFullApiOperationKey>(
  operationKey: OperationKey,
  ...args: DeepgramSpeechFullApiOperationArgs<OperationKey>
) => Promise<DeepgramSpeechFullApiOperationResponseMap[OperationKey]>;

export interface DeepgramSpeechFullApiGeneratedClient extends DeepgramSpeechFullApiSubpackageAgentSubpackageAgentV1SubpackageAgentV1SettingsSubpackageAgentV1SettingsThinkSubpackageAgentV1SettingsThinkModelsGeneratedClient, DeepgramSpeechFullApiSubpackageAuthSubpackageAuthV1SubpackageAuthV1TokensGeneratedClient, DeepgramSpeechFullApiSubpackageListenSubpackageListenV1SubpackageListenV1MediaGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ModelsGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBalancesGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBreakdownGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingFieldsGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingPurchasesGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsKeysGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersInvitesGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersScopesGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsModelsGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsRequestsGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageBreakdownGeneratedClient, DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageFieldsGeneratedClient, DeepgramSpeechFullApiSubpackageReadSubpackageReadV1SubpackageReadV1TextGeneratedClient, DeepgramSpeechFullApiSubpackageSelfHostedSubpackageSelfHostedV1SubpackageSelfHostedV1DistributionCredentialsGeneratedClient, DeepgramSpeechFullApiSubpackageSpeakSubpackageSpeakV1SubpackageSpeakV1AudioGeneratedClient, DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentConfigurationsGeneratedClient, DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentVariablesGeneratedClient {}

export const DEEPGRAM_SPEECH_FULL_API_GENERATED_FUNCTION_COUNT = 49 as const;
export const DEEPGRAM_SPEECH_FULL_API_GENERATED_FUNCTION_NAMES = [
  ...DeepgramSpeechFullApiSubpackageAgentSubpackageAgentV1SubpackageAgentV1SettingsSubpackageAgentV1SettingsThinkSubpackageAgentV1SettingsThinkModelsGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageAuthSubpackageAuthV1SubpackageAuthV1TokensGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageListenSubpackageListenV1SubpackageListenV1MediaGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ModelsGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBalancesGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBreakdownGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingFieldsGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingPurchasesGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsKeysGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersInvitesGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersScopesGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsModelsGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsRequestsGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageBreakdownGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageFieldsGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageReadSubpackageReadV1SubpackageReadV1TextGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageSelfHostedSubpackageSelfHostedV1SubpackageSelfHostedV1DistributionCredentialsGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageSpeakSubpackageSpeakV1SubpackageSpeakV1AudioGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentConfigurationsGeneratedFunctionNames,
  ...DeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentVariablesGeneratedFunctionNames,
] as const satisfies readonly (keyof DeepgramSpeechFullApiGeneratedClient)[];

export function createDeepgramSpeechFullApiGeneratedClient(
  callOperation: DeepgramSpeechGeneratedOperationCaller,
): DeepgramSpeechFullApiGeneratedClient {
  return Object.assign(
    {},
    createDeepgramSpeechFullApiSubpackageAgentSubpackageAgentV1SubpackageAgentV1SettingsSubpackageAgentV1SettingsThinkSubpackageAgentV1SettingsThinkModelsGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageAuthSubpackageAuthV1SubpackageAuthV1TokensGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageListenSubpackageListenV1SubpackageListenV1MediaGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ModelsGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBalancesGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingBreakdownGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingFieldsGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsBillingSubpackageManageV1ProjectsBillingPurchasesGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsKeysGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersInvitesGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsMembersSubpackageManageV1ProjectsMembersScopesGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsModelsGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsRequestsGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageBreakdownGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageManageSubpackageManageV1SubpackageManageV1ProjectsSubpackageManageV1ProjectsUsageSubpackageManageV1ProjectsUsageFieldsGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageReadSubpackageReadV1SubpackageReadV1TextGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageSelfHostedSubpackageSelfHostedV1SubpackageSelfHostedV1DistributionCredentialsGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageSpeakSubpackageSpeakV1SubpackageSpeakV1AudioGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentConfigurationsGeneratedClient(callOperation),
    createDeepgramSpeechFullApiSubpackageVoiceAgentSubpackageVoiceAgentVariablesGeneratedClient(callOperation),
  ) as DeepgramSpeechFullApiGeneratedClient;
}
