import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { ELEVENLABS_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  ELEVENLABS_FULL_API_OPERATION_COUNT,
  ELEVENLABS_FULL_API_PATH_COUNT,
  ELEVENLABS_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const elevenLabsVoiceProviderManifest = defineProviderPackage({
  id: "voice.elevenlabs",
  name: "ElevenLabs Voice",
  packageName: "@cognidesk/integrations",
  provider: "elevenlabs",
  category: "voice",
  trustLevel: "official",
  directions: ["send-only", "receive-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in ElevenLabs' official public REST OpenAPI 3.1 specification.",
      "Typed convenience helpers remain available for Cognidesk support workflows: Text to Speech create/stream/timing, Speech to Text create/get, voice/model lookup, Conversational AI signed URLs, conversation list/detail/audio retrieval, history, user/subscription, single-use tokens, selected media transforms, and WebSocket URL builders.",
      "The generated REST surface covers agents, phone numbers, SIP trunk outbound call, Twilio/Exotel/WhatsApp outbound calls, batch calling, knowledge base, tools, workspace webhooks, service-account API keys, audit logs, voices, models, history, dubbing, studio, music, sound generation, audio isolation, and pronunciation dictionaries from the official OpenAPI artifact.",
      "The generic send and media capabilities mean ElevenLabs speech/audio generation, transcription, and conversation media objects only; they do not mean telephony carrier ownership, call-center routing, Studio configuration, workspace administration, or provider setup policy.",
      "Realtime WebSocket protocol behavior is not represented as REST OpenAPI operations; this package keeps WebSocket URL builders and single-use token helpers, while SDK users own browser/session transport behavior.",
    ],
    evidence: [
      { label: "ElevenLabs REST OpenAPI specification", url: "https://api.elevenlabs.io/openapi.json" },
      { label: "ElevenLabs API reference", url: "https://elevenlabs.io/docs/api-reference" },
      { label: "ElevenLabs API authentication", url: "https://elevenlabs.io/docs/api-reference/authentication" },
      { label: "ElevenLabs Text to Speech create speech", url: "https://elevenlabs.io/docs/api-reference/text-to-speech/convert" },
      { label: "ElevenLabs Text to Speech stream speech", url: "https://elevenlabs.io/docs/api-reference/text-to-speech/stream" },
      { label: "ElevenLabs Text to Speech WebSocket", url: "https://elevenlabs.io/docs/api-reference/text-to-speech/v-1-text-to-speech-voice-id-stream-input" },
      { label: "ElevenLabs Speech to Text create transcript", url: "https://elevenlabs.io/docs/api-reference/speech-to-text/convert" },
      { label: "ElevenLabs Speech to Text get transcript", url: "https://elevenlabs.io/docs/api-reference/speech-to-text/get" },
      { label: "ElevenLabs Speech to Text webhooks", url: "https://elevenlabs.io/docs/eleven-api/guides/how-to/speech-to-text/batch/webhooks" },
      { label: "ElevenLabs Conversations signed URL", url: "https://elevenlabs.io/docs/api-reference/conversations/get-signed-url" },
      { label: "ElevenLabs Conversations list", url: "https://elevenlabs.io/docs/api-reference/conversations/list" },
      { label: "ElevenLabs Conversations get details", url: "https://elevenlabs.io/docs/api-reference/conversations/get" },
      { label: "ElevenLabs Conversations get audio", url: "https://elevenlabs.io/docs/api-reference/conversations/get-audio" },
      { label: "ElevenLabs Voices list", url: "https://elevenlabs.io/docs/api-reference/voices/search" },
      { label: "ElevenLabs Models list", url: "https://elevenlabs.io/docs/api-reference/models/list" },
      { label: "ElevenLabs Phone Numbers API", url: "https://elevenlabs.io/docs/api-reference/phone-numbers" },
      { label: "ElevenLabs Batch Calling API", url: "https://elevenlabs.io/docs/api-reference/batch-calling" },
      { label: "ElevenLabs Workspace Webhooks API", url: "https://elevenlabs.io/docs/api-reference/workspace/webhooks" },
    ],
  },
  credentialRequirements: [
    {
      id: "elevenlabs-api-key",
      label: "ElevenLabs API key",
      description: "Server-side ElevenLabs credential sent through the xi-api-key header for voice API requests.",
      required: true,
      metadata: {
        scopeModel: "elevenlabs-api-key-permissions",
        minimumAccess: ["text-to-speech", "speech-to-text", "conversations", "voices:read", "models:read"],
        supportsEndpointRestrictions: true,
      },
    },
  ],
  capabilities: [
    {
      capability: "send",
      label: "Create speech audio",
      description: "Creates or streams speech audio with ElevenLabs Text to Speech.",
      audiences: ["customer-facing"],
      providerObjects: [
        { kind: "elevenlabsVoice", label: "ElevenLabs Voice" },
        { kind: "elevenlabsSpeechGeneration", label: "ElevenLabs Speech Generation" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "receive",
      label: "Receive conversational voice",
      description: "Creates signed URLs for authorized ElevenLabs Conversational AI sessions and reads conversation transcripts.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "elevenlabsConversation", label: "ElevenLabs Conversation" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Voice media and transcripts",
      description: "Reads generated audio streams, conversation audio, speech timing alignments, and speech-to-text transcript resources.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [
        { kind: "elevenlabsAudio", label: "ElevenLabs Audio" },
        { kind: "elevenlabsTranscript", label: "ElevenLabs Transcript" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "elevenlabs.conversation-signed-url",
      label: "Create conversation signed URL",
      description: "Creates a signed URL for an authorized ElevenLabs Conversational AI agent session.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "elevenlabsConversation", label: "ElevenLabs Conversation" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      capability: "elevenlabs.speech-to-text",
      label: "Transcribe audio",
      description: "Creates and retrieves ElevenLabs Speech to Text transcript resources.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "elevenlabsTranscript", label: "ElevenLabs Transcript" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Text prompts, generated speech, uploaded audio/video, transcript text, conversation IDs, and conversation audio can contain personal data and are sent to or read from ElevenLabs.",
    "ElevenLabs API keys must remain server-side. Use signed URLs or single-use tokens for browser/client conversation startup instead of exposing the API key.",
  ],
  limitations: [
    "The generated full-provider claim is limited to ElevenLabs REST OpenAPI operations verified on 2026-06-18; realtime WebSocket transport behavior remains a separate protocol surface.",
    "Telephony numbers, SIP trunking, WhatsApp setup, batch calling, call recording policy, consent, retention, and live agent routing remain SDK-user/provider configuration even when the underlying REST operations are callable.",
    "Zero-retention and tier-gated output formats depend on the SDK user's ElevenLabs plan and API-key permissions.",
  ],
  metadata: {
    channelCoverage: {
      fullRestApiOperations: "generated-per-operation-functions",
      textToSpeech: "typed-create-stream",
      speechToText: "typed-create-read",
      conversationalAiSignedUrl: "typed-create",
      conversationReadAudio: "typed-read",
      phoneNumbers: "generated-per-operation-functions",
      sipTrunk: "generated-per-operation-functions",
      twilioIntegration: "generated-per-operation-functions",
      exotelIntegration: "generated-per-operation-functions",
      whatsapp: "generated-per-operation-functions",
      batchCalling: "generated-per-operation-functions",
      agentsKnowledgeToolsWorkspace: "generated-per-operation-functions",
      realtimeWebSocketProtocol: "typed-url-builder",
      liveAgentTransfer: "provider-supported-not-typed",
    },
    fullProviderApiVerification: {
      provider: "elevenlabs-rest-openapi",
      apiVersion: ELEVENLABS_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/elevenlabs-full-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/elevenlabs-full-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/elevenlabs-full-api-2026-06-18.functions.json",
      documentedPathCount: ELEVENLABS_FULL_API_PATH_COUNT,
      documentedOperationCount: ELEVENLABS_FULL_API_OPERATION_COUNT,
      implementedOperationCount: ELEVENLABS_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: ELEVENLABS_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
