export {
  contactCenterCategoryProfile,
  contactCenterOperationAliasMap,
  ecommerceCategoryProfile,
  ecommerceOperationAliasMap,
  emailCategoryProfile,
  emailOperationAliasMap,
  getIntegrationCategoryProfile,
  handoffCategoryProfile,
  integrationCategoryOperationAliasMaps,
  integrationCategoryProfiles,
  integrationCategoryProfilesByCategory,
  messagingCategoryProfile,
  requireIntegrationCategoryProfile,
  smsCategoryProfile,
  smsOperationAliasMap,
  ticketingCategoryProfile,
  ticketingOperationAliasMap,
  voiceCategoryProfile,
  voiceOperationAliasMap,
  workplaceCategoryProfile,
  workplaceOperationAliasMap,
} from "@cognidesk/integration-kit/category-profiles";
export {
  categoryOperationAliasMap,
  categoryOperationAliases,
  categoryProfilesCoreIntegrationNote,
  defineIntegrationCategoryProfile,
  deriveProviderCapabilityCoverage,
  findCategoryOperation,
  operation,
} from "@cognidesk/integration-kit/category-profiles";
export type {
  CategoryCoverageLevel,
  CategoryOperationAliasMap,
  ContactCenterOperationAlias,
  EcommerceOperationAlias,
  EmailOperationAlias,
  IntegrationCategoryProfile,
  IntegrationCategoryProfileId,
  OperationSchemaDescriptor,
  ProviderCapabilityCoverage,
  SmsOperationAlias,
  TicketingOperationAlias,
  VoiceOperationAlias,
  WorkplaceOperationAlias,
} from "@cognidesk/integration-kit/category-profiles";
