import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";

export const genesysPureConnectContactCenterProviderManifest = defineProviderPackage({
  id: "contactCenter.genesys-pureconnect",
  name: "Genesys PureConnect / ICWS",
  packageName: "@cognidesk/integrations",
  provider: "genesys-pureconnect",
  category: "contactCenter",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    { id: "genesys-pureconnect-icws-base-url", label: "PureConnect ICWS base URL", required: true },
    { id: "genesys-pureconnect-session", label: "PureConnect ICWS session/authentication", required: false },
    { id: "genesys-pureconnect-routing", label: "PureConnect Interaction Web Tools routing configuration", required: false },
  ],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage introduces Genesys PureConnect as a separate deployment/provider mode from Genesys Cloud and Genesys Engage/GMS.",
      "Coverage includes a typed ICWS connection creation helper, session-aware ICWS request helpers, typed wrappers for selected documented interaction create/read/update/conference/consult endpoints, messaging message polling and interaction subscriptions, recording export URI, and configuration-user read endpoints, plus SDK-configured PureConnect handoff/readiness paths for deployment-specific Interaction Web Tools, web chat, or callback plumbing.",
      "Readiness requires an SDK-configured GET path such as a deployment health endpoint or documented ICWS metadata endpoint; the package does not assume `GET /icws/connection` because the documented connection endpoint creates sessions with POST.",
      "The checked endpoint inventory is `docs/provider-coverage/genesys-pureconnect-icws-api-2026-06-18.checked-inventory.json`; ICWS events are represented by message polling/EventSource and selected subscriptions, while no official webhook subscription endpoint catalog was found in the checked ICWS/Interaction Web Tools docs.",
      "The package does not claim the full PureConnect ICWS API or Interaction Web Tools chat/callback lifecycle. Broader queue control, recordings beyond export URI, statistics beyond subscription transport, directory, status, and administration APIs remain outside this scoped surface unless called through the generic request helper.",
    ],
    evidence: [
      { label: "Genesys APIs by Service", url: "https://all.docs.genesys.com/Developer/APIbyService" },
      { label: "PureConnect ICWS connection", url: "https://help.genesys.com/developer/cic/docs/icws/webhelp/icws/connection/index.htm" },
      { label: "PureConnect ICWS interactions", url: "https://help.genesys.com/staging/developer/root/cic/docs/icws/webhelp/icws/%28sessionId%29/interactions/Interactions.htm" },
      { label: "PureConnect ICWS messages", url: "https://help.genesys.com/developer/cic/docs/icws/webhelp/icws/%28sessionId%29/messaging/messages/index.htm" },
      { label: "PureConnect ICWS recording export URI", url: "https://help.genesys.com/developer/cic/docs/icws/webhelp/icws/%28sessionId%29/recordings/%28recordingId%29/export-uri/index.htm" },
      { label: "PureConnect Interaction Web Tools", url: "https://help.genesys.com/pureconnect/mergedprojects/wh_tr/mergedprojects/wh_tr_installation_and_configuration/desktop/interaction_web_tools.htm" },
      { label: "PureConnect chat features", url: "https://help.genesys.com/pureconnect/desktop/chat_features_landing.htm" },
    ],
  },
  capabilities: [
    {
      capability: "handoff",
      label: "Create PureConnect configured handoff",
      description: "Creates SDK-configured PureConnect/ICWS or Interaction Web Tools handoff requests without claiming typed web chat, callback, or interaction-control lifecycle coverage.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "genesysPureConnectConfiguredWebChatHandoff", label: "PureConnect configured web chat handoff" },
        { kind: "genesysPureConnectConfiguredCallbackHandoff", label: "PureConnect configured callback handoff" },
        { kind: "genesysPureConnectConfiguredHandoff", label: "PureConnect configured handoff" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "contact-center.pureconnect-session",
      label: "Create PureConnect ICWS session",
      description: "Creates a documented ICWS connection/session representation against `/icws/connection` and exposes session-scoped ICWS request helpers.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "genesysPureConnectIcwsConnection", label: "PureConnect ICWS connection" },
        { kind: "genesysPureConnectIcwsInteraction", label: "PureConnect ICWS interaction" },
        { kind: "genesysPureConnectIcwsMessagingSubscription", label: "PureConnect ICWS messaging subscription" },
        { kind: "genesysPureConnectIcwsRecording", label: "PureConnect ICWS recording" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "PureConnect handoffs can include caller identifiers, callback/chat context, queue targets, transcript references, and deployment-specific user data.",
    "PureConnect ICWS credentials, session IDs, and on-premises network details stay server-side; Studio receives only configuration/readiness state.",
  ],
  limitations: [
    "PureConnect CIC topology, ICWS version, reverse proxy/base path, authentication, Interaction Web Tools handlers, chat forms, callback forms, and routing targets are SDK-user configuration.",
    "Interaction Web Tools web chat and callback require deployment-specific web-server plumbing and routing configuration before they can be exposed to Cognidesk.",
    "Interaction Web Tools web chat/callback widget lifecycle and high-level transfer policy remain deployment-specific; low-level ICWS paths can be called through the typed request helpers when the SDK user supplies the session, CSRF token, cookie, permissions, and payload.",
  ],
  metadata: {
    deploymentMode: "genesys-pureconnect-icws",
    checkedInventoryArtifact: "docs/provider-coverage/genesys-pureconnect-icws-api-2026-06-18.checked-inventory.json",
    checkedEndpointEntries: 22,
    officialMachineReadableSpec: "not-found",
    checkedWebhookCatalog: "not-found-in-checked-icws-interaction-web-tools-docs",
    channelCoverage: {
      icwsConnection: "typed-create",
      icwsSessionRequest: "typed-generic-request",
      icwsInteractionSelectedActions: "typed-create-get-update-conference-consult",
      icwsInteractionSubscriptions: "typed-subscribe-unsubscribe",
      icwsMessagingMessages: "typed-poll-messages",
      icwsRecordingExportUri: "typed-read",
      icwsConfigurationUserRead: "typed-read",
      icwsDirectory: "provider-supported-not-typed",
      icwsStatistics: "provider-supported-not-typed",
      icwsStatus: "provider-supported-not-typed",
      icwsAdministration: "provider-supported-not-typed",
      configuredHttpHandoff: "supported",
      interactionWebToolsWebChat: "provider-supported-configured-http-only",
      interactionWebToolsCallback: "provider-supported-configured-http-only",
      interactionWebToolsChatLifecycle: "provider-supported-not-typed",
      interactionWebToolsCallbackLifecycle: "provider-supported-not-typed",
      pureConnectChatTransfer: "provider-supported-not-typed",
      interactionControl: "provider-supported-low-level-icws-request",
      typedTransfer: "not-covered",
      events: "provider-supported-not-typed",
      webhooks: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
