import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const ORACLE_SERVICE_DEFAULT_API_VERSION = "11.13.18.05";

export const oracleServiceProviderClientOperationTargets = [
  { alias: "ticket.create", target: "providerClient.createServiceRequest" },
  { alias: "ticket.read", target: "providerClient.getServiceRequest" },
  { alias: "ticket.update", target: "providerClient.updateServiceRequest" },
  { alias: "ticket.search", target: "providerClient.searchServiceRequests" },
  {
    alias: "oracle-service.serviceRequestMessage.create",
    target: "providerClient.createServiceRequestMessage",
  },
] as const;

export const oracleServiceRejectedProviderSdkCandidates = [
  {
    packageName: "oci-fusionapps",
    version: "2.135.1",
    source: "npm",
    result: "not-used-as-runtime-ticketing-sdk",
    reason: "Oracle-maintained OCI SDK package for Fusion Apps Service administration, not a typed Oracle Fusion Service serviceRequests or B2C Service incident data client.",
  },
  {
    packageName: "oci-sdk",
    version: "2.135.1",
    source: "npm",
    result: "not-used-as-runtime-ticketing-sdk",
    reason: "Oracle-maintained OCI SDK aggregate, but it does not expose the Oracle Fusion Service serviceRequests or Oracle B2C Service incident ticketing runtime surface used by this package.",
  },
  {
    packageName: "osvc_node",
    version: "1.0.0",
    source: "npm",
    result: "rejected-unofficial-stale-wrapper",
    reason: "Unofficial Oracle Service Cloud REST wrapper last published years ago, not a maintained Oracle runtime SDK suitable for Cognidesk provider-client ownership.",
  },
] as const;

export const oracleServiceTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.oracle-service",
  name: "Oracle Service",
  packageName: "@cognidesk/integration-ticketing-oracle-service",
  provider: "oracle-service",
  category: "ticketing",
  trustLevel: "official",
  directions: ["bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is typed for Oracle Fusion Service serviceRequests create, read by SrNumber, patch, collection search, child message creation, and readiness checks used by Cognidesk support workflows.",
      "Runtime provider operations use the built-in Oracle Fusion Service REST adapter when baseUrl/instanceUrl plus access credentials are provided; a host-injected OracleServiceTicketingProviderClient remains available as an override.",
      "This is not full Oracle Fusion Service API coverage; service request child resources such as activities, attachments, contacts, message attachment/channel-communication lifecycle, milestones, resources, smart actions, tags, LOV/metadata behavior, workflow rules, queues, privileges, and broader Fusion CX APIs remain outside this adapter.",
    ],
    evidence: [
      { label: "Oracle Fusion Service serviceRequests overview", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/api-internal-service-requests.html" },
      { label: "Oracle Fusion Service create service request", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/op-servicerequests-post.html" },
      { label: "Oracle Fusion Service get all service requests", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/op-servicerequests-get.html" },
      { label: "Oracle Fusion Service get service request", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/op-servicerequests-srnumber-get.html" },
      { label: "Oracle Fusion Service update service request", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/op-servicerequests-srnumber-patch.html" },
      { label: "Oracle Fusion Service create service request message", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/op-servicerequests-srnumber-child-messages-post.html" },
    ],
  },
  credentialRequirements: [
    {
      id: "oracle-service-provider-client",
      label: "Optional host-provided Oracle Service provider client",
      description: "Optional SDK-user-owned provider client implementing OracleServiceTicketingProviderClient. When omitted, the package uses its built-in Oracle Fusion Service REST adapter.",
      required: false,
      metadata: {
        interface: "OracleServiceTicketingProviderClient",
        importPolicy: "optional-host-override",
        defaultClientPolicy: "built-in-provider-rest-adapter",
      },
    },
    {
      id: "oracle-service-instance",
      label: "Oracle Fusion Service instance URL",
      description: "The Oracle Fusion Service base URL, for example https://example.fa.oraclecloud.com, used by the built-in REST adapter or supplied by a host provider client override.",
      required: false,
      metadata: {
        requiredWhen: "built-in-provider-rest-adapter",
      },
    },
    {
      id: "oracle-service-api-access",
      label: "Oracle Fusion Service API access",
      description: "Server-side Oracle Fusion Service access for serviceRequests and child messages, supplied as accessToken, basic auth, auth headers, or encapsulated in a host provider client.",
      scopes: ["serviceRequests:read", "serviceRequests:write"],
      required: false,
      metadata: {
        requiredWhen: "built-in-provider-rest-adapter",
        scopeKind: "internal-capability-labels",
        privilegeGuidance: "These strings are Cognidesk capability labels, not official Oracle OAuth scope names. Oracle access depends on Fusion Service roles and privileges for service request read/create/update/search and message creation.",
      },
    },
  ],
  capabilities: [
    {
      capability: "create-provider-object",
      label: "Create Oracle service requests",
      description: "Creates Oracle Fusion Service serviceRequests records from SDK-user-selected support workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "oracleServiceRequest", label: "Oracle Service Request", schemaName: "serviceRequests" },
        { kind: "oracleServiceRequestMessage", label: "Oracle Service Request Message", schemaName: "serviceRequests.child.messages" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Oracle service requests",
      description: "Reads Oracle Fusion Service service request records by SrNumber.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "oracleServiceRequest", label: "Oracle Service Request", schemaName: "serviceRequests" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Oracle service requests",
      description: "Updates Oracle Fusion Service service request status, queue, assignee, resolution, or custom fields.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "oracleServiceRequest", label: "Oracle Service Request", schemaName: "serviceRequests" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Oracle service requests",
      description: "Queries Oracle Fusion Service service requests with SDK-user-supplied q, finder, fields, and paging controls.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "oracleServiceRequest", label: "Oracle Service Request", schemaName: "serviceRequests" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Attach handoff to Oracle Service",
      description: "Provides Oracle service request operations for SDK-user-configured human handoff workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "oracleServiceRequest", label: "Oracle Service Request", schemaName: "serviceRequests" },
        { kind: "oracleServiceRequestMessage", label: "Oracle Service Request Message", schemaName: "serviceRequests.child.messages" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  operations: [
    {
      alias: "ticket.create",
      capability: "create-provider-object",
      providerObject: "oracleServiceRequest",
      audiences: ["customer-facing", "internal-support", "mixed"],
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.read",
      capability: "read-provider-object",
      providerObject: "oracleServiceRequest",
      audiences: ["customer-facing", "internal-support", "mixed"],
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.update",
      capability: "update-provider-object",
      providerObject: "oracleServiceRequest",
      audiences: ["internal-support", "mixed"],
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.search",
      capability: "search-provider-object",
      providerObject: "oracleServiceRequest",
      audiences: ["customer-facing", "internal-support", "mixed"],
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "oracle-service.serviceRequestMessage.create",
      capability: "create-provider-object",
      providerObject: "oracleServiceRequestMessage",
      audiences: ["customer-facing", "internal-support", "mixed"],
      extension: true,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
  ],
  privacyNotes: [
    "Oracle service requests can contain customer identity, problem descriptions, service profile data, queue and assignee details, and internal resolution notes.",
    "Oracle credentials stay server-side and are represented in Studio only as credential readiness and scope status.",
  ],
  limitations: [
    "Oracle Service categories, required fields, queues, assignment rules, milestones, extensions, and privileges are owned by the SDK user's Fusion Service environment.",
    "SDK users own handoff timing, field mapping, customer identity matching, visibility, consent, notification policy, retry/rate-limit behavior, and retention before calling Oracle APIs.",
    "The built-in adapter covers selected serviceRequests REST operations only; hosts can still inject an approved Oracle Service provider client for custom authentication, retries, or API-version policy.",
  ],
  metadata: {
    implementation: {
      strategy: "provider-rest-adapter",
      adapterKind: "no-official-sdk-rest-adapter",
      defaultClient: "built-in-oracle-fusion-service-rest-adapter",
      providerClientOverride: true,
      apiVersion: ORACLE_SERVICE_DEFAULT_API_VERSION,
    },
    implementationStrategy: {
      strategy: "no-official-sdk-rest-adapter",
      result: "no-suitable-maintained-runtime-provider-sdk",
      exception: "provider-rest-adapter",
      reason: "No suitable maintained npm runtime SDK was verified for Oracle Fusion Service serviceRequests or Oracle Service Cloud/B2C Service incidents; Oracle documents these ticketing surfaces as REST APIs, while the official OCI TypeScript/JavaScript SDK manages OCI resources including Fusion Apps as a Service rather than service request records.",
      checkedAt: "2026-06-25",
      rejectedLibraries: oracleServiceRejectedProviderSdkCandidates,
    },
    sdkDecision: {
      result: "provider-rest-adapter-exception",
      providerRestAdapterException: true,
      viableMaintainedRuntimeProviderSdk: false,
      acceptedRuntimeProviderSdk: null,
      checkedAt: "2026-06-25",
      checkedSources: [
        "Oracle Fusion Service serviceRequests REST API documentation",
        "Oracle B2C Service incidents REST API documentation",
        "npm registry package metadata and search results",
      ],
      rejectedLibraries: oracleServiceRejectedProviderSdkCandidates,
    },
    providerClient: {
      package: "optional-host-provided",
      interface: "OracleServiceTicketingProviderClient",
      importPolicy: "optional-host-override",
      defaultClientPolicy: "built-in-provider-rest-adapter",
      operationTargets: oracleServiceProviderClientOperationTargets,
    },
    providerRestAdapterOperationSlice: {
      sourceKind: "provider-rest-adapter",
      adapterKind: "no-official-sdk-rest-adapter",
      sourceVersion: ORACLE_SERVICE_DEFAULT_API_VERSION,
      checkedAt: "2026-06-25",
      operations: oracleServiceProviderClientOperationTargets,
    },
    checkedProviderApiCoverage: {
      verifiedAt: "2026-06-18",
      sourceKind: "checked-endpoint-family-inventory",
      coverageArtifact: "docs/provider-coverage/oracle-service-checked-service-requests-2026-06-18.inventory.json",
      checkedFamilyCount: 5,
      implementedFamilyCount: 3,
      gapFamilyCount: 2,
      implementedOperationCount: 5,
    },
    channelCoverage: {
      serviceRequests: "typed-create-read-update-search",
      serviceRequestMessages: "typed-create",
      readinessSearch: "typed-search",
      attachments: "provider-supported-not-typed",
      activitiesContactsMilestones: "provider-supported-not-typed",
      queuesSmartActionsWorkflowRules: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
