import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const ORACLE_SERVICE_DEFAULT_API_VERSION = "11.13.18.05";

export const oracleServiceSupportOperationAllowlist = [
  { alias: "ticket.create", method: "POST", path: "/crmRestApi/resources/{apiVersion}/serviceRequests" },
  { alias: "ticket.read", method: "GET", path: "/crmRestApi/resources/{apiVersion}/serviceRequests/{SrNumber}" },
  { alias: "ticket.update", method: "PATCH", path: "/crmRestApi/resources/{apiVersion}/serviceRequests/{SrNumber}" },
  { alias: "ticket.search", method: "GET", path: "/crmRestApi/resources/{apiVersion}/serviceRequests" },
  {
    alias: "oracle-service.serviceRequestMessage.create",
    method: "POST",
    path: "/crmRestApi/resources/{apiVersion}/serviceRequests/{SrNumber}/child/messages",
  },
] as const;

export const oracleServiceTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.oracle-service",
  name: "Oracle Service",
  packageName: "@cognidesk/integration-ticketing-oracle-service",
  provider: "oracle-service",
  category: "ticketing",
  trustLevel: "official",
  directions: ["bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is typed for Oracle Fusion Service serviceRequests create, read by SrNumber, patch, collection search, child message creation, and readiness checks used by Cognidesk support workflows.",
      "This is not full Oracle Fusion Service API coverage; service request child resources such as activities, attachments, contacts, message attachment/channel-communication lifecycle, milestones, resources, smart actions, tags, LOV/metadata behavior, workflow rules, queues, privileges, and broader Fusion CX APIs remain outside this adapter.",
    ],
    evidence: [
      { label: "Oracle Fusion Service serviceRequests overview", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/api-internal-service-requests.html" },
      { label: "Oracle Fusion Service create service request", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/op-servicerequests-post.html" },
      { label: "Oracle Fusion Service get all service requests", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/op-servicerequests-get.html" },
      { label: "Oracle Fusion Service get service request", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/op-servicerequests-srnumber-get.html" },
      { label: "Oracle Fusion Service update service request", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/op-servicerequests-srnumber-patch.html" },
      { label: "Oracle Fusion Service create service request message", url: "https://docs.oracle.com/en/cloud/saas/sales/faaps/op-servicerequests-srnumber-child-messages-post.html" },
    ],
  },
  credentialRequirements: [
    {
      id: "oracle-service-instance",
      label: "Oracle Fusion Service instance URL",
      description: "The SDK user's Oracle Fusion Service host, for example https://example.fa.oraclecloud.com.",
      required: true,
    },
    {
      id: "oracle-service-api-access",
      label: "Oracle Fusion Service REST API access",
      description: "Server-side OAuth bearer access or Basic Auth credentials for Oracle Fusion Service REST APIs with service roles and privileges for serviceRequests and child messages.",
      scopes: ["serviceRequests:read", "serviceRequests:write"],
      required: true,
      metadata: {
        scopeKind: "internal-capability-labels",
        privilegeGuidance: "These strings are Cognidesk capability labels, not official Oracle OAuth scope names. Oracle access depends on Fusion Service roles and privileges for service request read/create/update/search and message creation.",
      },
    },
  ],
  capabilities: [
    {
      capability: "create-provider-object",
      label: "Create Oracle service requests",
      description: "Creates Oracle Fusion Service serviceRequests records from SDK-user-selected support workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "oracleServiceRequest", label: "Oracle Service Request", schemaName: "serviceRequests" },
        { kind: "oracleServiceRequestMessage", label: "Oracle Service Request Message", schemaName: "serviceRequests.child.messages" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Oracle service requests",
      description: "Reads Oracle Fusion Service service request records by SrNumber.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "oracleServiceRequest", label: "Oracle Service Request", schemaName: "serviceRequests" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Oracle service requests",
      description: "Updates Oracle Fusion Service service request status, queue, assignee, resolution, or custom fields.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "oracleServiceRequest", label: "Oracle Service Request", schemaName: "serviceRequests" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Oracle service requests",
      description: "Queries Oracle Fusion Service service requests with SDK-user-supplied q, finder, fields, and paging controls.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "oracleServiceRequest", label: "Oracle Service Request", schemaName: "serviceRequests" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Attach handoff to Oracle Service",
      description: "Provides Oracle service request operations for SDK-user-configured human handoff workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "oracleServiceRequest", label: "Oracle Service Request", schemaName: "serviceRequests" },
        { kind: "oracleServiceRequestMessage", label: "Oracle Service Request Message", schemaName: "serviceRequests.child.messages" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  operations: [
    {
      alias: "ticket.create",
      capability: "create-provider-object",
      providerObject: "oracleServiceRequest",
      audiences: ["customer-facing", "internal-support", "mixed"],
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.read",
      capability: "read-provider-object",
      providerObject: "oracleServiceRequest",
      audiences: ["customer-facing", "internal-support", "mixed"],
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.update",
      capability: "update-provider-object",
      providerObject: "oracleServiceRequest",
      audiences: ["internal-support", "mixed"],
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.search",
      capability: "search-provider-object",
      providerObject: "oracleServiceRequest",
      audiences: ["customer-facing", "internal-support", "mixed"],
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "oracle-service.serviceRequestMessage.create",
      capability: "create-provider-object",
      providerObject: "oracleServiceRequestMessage",
      audiences: ["customer-facing", "internal-support", "mixed"],
      extension: true,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
  ],
  privacyNotes: [
    "Oracle service requests can contain customer identity, problem descriptions, service profile data, queue and assignee details, and internal resolution notes.",
    "Oracle credentials stay server-side and are represented in Studio only as credential readiness and scope status.",
  ],
  limitations: [
    "Oracle Service categories, required fields, queues, assignment rules, milestones, extensions, and privileges are owned by the SDK user's Fusion Service environment.",
    "SDK users own handoff timing, field mapping, customer identity matching, visibility, consent, notification policy, and retention before calling Oracle APIs.",
  ],
  metadata: {
    implementation: {
      strategy: "direct-http-support-slice",
    },
    implementationStrategy: {
      strategy: "direct-support-slice",
      reason: "No suitable official JavaScript SDK was found for Oracle Fusion Service serviceRequests; oci-fusionapps targets OCI Fusion Apps Service resource management, not this REST surface.",
      checkedAt: "2026-06-21",
      rejectedLibraries: [
        {
          packageName: "oci-fusionapps",
          version: "2.135.0",
          integrity: "sha512-L0mF2w4tYeVBM1DXEDVuufuKysTQqhvS65GCN7meubjWzxUNMRDO9P/EM1ouSguyjJio7NeCr4hQWSP5AEe46Q==",
          reason: "Official Oracle-maintained OCI SDK package, but not a Fusion Service service request client.",
        },
      ],
    },
    supportOperationSlice: {
      sourceKind: "official-docs-reviewed-slice",
      sourceVersion: ORACLE_SERVICE_DEFAULT_API_VERSION,
      checkedAt: "2026-06-21",
      allowlistSha256: "5f3ff8ea4febec8a1f5e4c9d881124c9f215a7b97ebb3ae7a92d7e3f98b370f5",
      operations: oracleServiceSupportOperationAllowlist,
    },
    checkedProviderApiCoverage: {
      verifiedAt: "2026-06-18",
      sourceKind: "checked-endpoint-family-inventory",
      coverageArtifact: "docs/provider-coverage/oracle-service-checked-service-requests-2026-06-18.inventory.json",
      checkedFamilyCount: 5,
      implementedFamilyCount: 3,
      gapFamilyCount: 2,
      implementedOperationCount: 5,
    },
    channelCoverage: {
      serviceRequests: "typed-create-read-update-search",
      serviceRequestMessages: "typed-create",
      readinessSearch: "typed-search",
      attachments: "provider-supported-not-typed",
      activitiesContactsMilestones: "provider-supported-not-typed",
      queuesSmartActionsWorkflowRules: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
