import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { GOOGLEPLAY_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  GOOGLEPLAY_FULL_API_OPERATION_COUNT,
  GOOGLEPLAY_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const googlePlayReviewsProviderManifest = defineProviderPackage({
  id: "review.googleplay",
  name: "Google Play Reviews",
  packageName: "@cognidesk/integrations",
  provider: "googleplay",
  category: "review",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-method functions for every method in the official Google Play Android Publisher v3 Discovery document.",
      "The package keeps typed support helpers for review primitives: Android Publisher reviews list/get/reply and OAuth access-token or service-account JWT bearer token minting.",
      "The SDK user owns Play Console permissions, package ownership, review polling policy, review reply approval, localization, consent, redaction, and retention decisions.",
    ],
    evidence: [
      { label: "Google Play Android Publisher Discovery document", url: "https://androidpublisher.googleapis.com/$discovery/rest?version=v3" },
      { label: "Google Play Android Publisher reviews resource", url: "https://developers.google.com/android-publisher/api-ref/rest/v3/reviews" },
      { label: "Google Play Reply to Reviews guide", url: "https://developers.google.com/android-publisher/reply-to-reviews" },
      { label: "Google service account OAuth 2.0 guide", url: "https://developers.google.com/identity/protocols/oauth2/service-account" },
      { label: "Google Play real-time developer notifications", url: "https://developer.android.com/google/play/billing/rtdn-reference" },
    ],
  },
  credentialRequirements: [
    {
      id: "googleplay-service-account",
      label: "Google Play service account",
      description: "SDK-user-owned Google service account with Google Play Console Reply to reviews permission.",
      scopes: ["https://www.googleapis.com/auth/androidpublisher"],
      required: false,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "googleplay-access-token",
      label: "Google Play API auth",
      description: "Server-side OAuth access token, token supplier, or service-account token minting for Android Publisher API requests.",
      scopes: ["https://www.googleapis.com/auth/androidpublisher"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "googleplay-package-name",
      label: "Android package name",
      description: "Fully-qualified Android application package name such as com.example.app.",
      required: true,
    },
  ],
  capabilities: [
    {
      capability: "read-provider-object",
      label: "Read Google Play reviews",
      description: "Lists recent reviews and reads individual Android app reviews through the Android Publisher API.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "googlePlayReview", label: "Google Play Review", schemaName: "reviews" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Page through Google Play reviews",
      description: "Uses Android Publisher review pagination and translation parameters controlled by SDK-user policy.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "googlePlayReview", label: "Google Play Review", schemaName: "reviews" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Reply to Google Play reviews",
      description: "Replies to or updates an existing developer reply for a review when SDK-user policy and Play permissions allow it.",
      audiences: ["customer-facing"],
      providerObjects: [
        { kind: "googlePlayReview", label: "Google Play Review", schemaName: "reviews" },
        { kind: "googlePlayDeveloperReply", label: "Google Play Developer Reply" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "draft",
      label: "Prepare Google Play review replies",
      description: "Builds reply payloads for SDK-user-configured approval, moderation, locale, and consent flows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "googlePlayDeveloperReplyDraft", label: "Google Play Developer Reply Draft" }],
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Google Play review text, author names, device metadata, ratings, language, app version, and developer replies can contain customer data.",
    "OAuth tokens and service-account material stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "The Google Play Reply to Reviews API exposes production app reviews with comments; rating-only feedback and non-production feedback are not exposed through this API.",
    "Developer replies are limited to 350 characters by the Android Publisher Reply to Reviews API.",
    "Google Play review API quotas, Reply to reviews permission, package ownership, translation behavior, reply moderation, and reply timing are owned by the SDK user's Play Console setup.",
    "Google Play Real-time developer notifications are purchase-state notifications for subscriptions, one-time products, voided purchases, and test notifications; they are not a review-ingestion surface for this package.",
    "SDK users own consent, retention, redaction, language policy, outbound reply approval, escalation, and operator visibility before review data or replies are used.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    docs: "https://developers.google.com/android-publisher/api-ref/rest/v3/reviews",
    channelCoverage: {
      fullAndroidPublisherApiMethods: "generated-per-operation-functions",
      reviews: "typed-list-read-and-generated-full-surface",
      developerReplies: "typed-send-update-and-generated-full-surface",
      replyDrafts: "sdk-owned",
      serviceAccountJwt: "typed-token-mint",
      realTimeDeveloperNotifications: "provider-supported-not-review-surface",
      editsTracksPurchasesMonetizationReports: "generated-full-surface",
    },
    fullProviderApiVerification: {
      provider: "googleplay",
      apiVersion: GOOGLEPLAY_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/googleplay-full-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/googleplay-full-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/googleplay-full-api-2026-06-18.functions.json",
      documentedOperationCount: GOOGLEPLAY_FULL_API_OPERATION_COUNT,
      implementedOperationCount: GOOGLEPLAY_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: GOOGLEPLAY_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
});
