import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";
import { serviceNowTicketingProviderOperations } from "./operations.js";

export const serviceNowTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.servicenow",
  name: "ServiceNow Ticketing",
  packageName: "@cognidesk/integration-ticketing-servicenow",
  provider: "servicenow",
  category: "ticketing",
  trustLevel: "official",
  directions: ["bidirectional"],
  channelAudiences: ["internal-support", "mixed"],
  operations: serviceNowTicketingProviderOperations,
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is limited to ServiceNow Table API record create/read/update/search, incident creation, Attachment API upload/list, Import Set insert/read, and readiness checks used by Cognidesk support workflows.",
      "Implementation uses the official @servicenow/sdk-api Connector when instanceUrl/baseUrl and OAuth bearer credentials are configured, with ServiceNowRawClient injection as an override for host-owned transports.",
      "Generic Table API helpers accept SDK-user-selected table names and fields, but they are not customer-specific generated schema coverage for arbitrary tables, custom fields, ACLs, business rules, or plugins.",
      "This is not full ServiceNow platform API coverage for Service Catalog/cart, journal-field semantics, attachment download/delete, transform-map lifecycle, scripted REST APIs, workflow APIs, or broader platform administration.",
    ],
    evidence: [
      { label: "ServiceNow Table API", url: "https://www.servicenow.com/docs/r/washingtondc/api-reference/rest-apis/c_TableAPI.html" },
      { label: "ServiceNow Attachment API", url: "https://www.servicenow.com/docs/r/washingtondc/api-reference/rest-apis/c_AttachmentAPI.html" },
      { label: "ServiceNow Import Set API", url: "https://www.servicenow.com/docs/r/washingtondc/api-reference/rest-apis/c_ImportSetAPI.html" },
      { label: "ServiceNow Virtual Agent API", url: "https://www.servicenow.com/docs/r/conversational-interfaces/virtual-agent/virtual-agent-api-landing-page.html" },
      { label: "ServiceNow Virtual Agent Bot Integration API", url: "https://www.servicenow.com/docs/r/washingtondc/api-reference/rest-apis/bot-api.html" },
      { label: "ServiceNow Virtual Agent API features", url: "https://www.servicenow.com/docs/r/yokohama/conversational-interfaces/virtual-agent/va-api-features.html" },
    ],
  },
  credentialRequirements: [
    {
      id: "servicenow-instance",
      label: "ServiceNow instance URL",
      description: "The SDK user's ServiceNow instance URL for the built-in official @servicenow/sdk-api Connector transport, for example https://example.service-now.com. Not required when the host injects a ServiceNowRawClient.",
      required: false,
      metadata: {
        requiredWhen: "built-in-servicenow-sdk-connector",
      },
    },
    {
      id: "servicenow-api-access",
      label: "ServiceNow API access",
      description: "Server-side OAuth bearer access for the built-in official @servicenow/sdk-api Connector transport; effective access is governed by ServiceNow roles, ACLs, table access, and any tenant REST API Auth Scopes. Use ServiceNowRawClient injection for other tenant-auth transports.",
      scopes: ["table_api"],
      required: false,
      metadata: {
        requiredWhen: "built-in-servicenow-sdk-connector",
        scopeKind: "internal-capability-labels",
        privilegeGuidance: "The table_api value is Cognidesk capability guidance, not a universal ServiceNow OAuth scope. The credential must be authorized for Table API, Attachment API, Import Set API, and configured target tables.",
      },
    },
    {
      id: "servicenow-raw-client",
      label: "Host-provided ServiceNow raw client",
      description: "Optional ServiceNowRawClient override supplied by the host application. When configured, Cognidesk delegates operations to that client instead of constructing the built-in @servicenow/sdk-api Connector transport.",
      required: false,
      metadata: {
        credentialKind: "host-client-override",
        clientInterface: "ServiceNowRawClient",
        satisfies: ["servicenow-instance", "servicenow-api-access"],
      },
    },
  ],
  capabilities: [
    {
      capability: "create-provider-object",
      label: "Create ServiceNow records",
      description: "Creates SDK-user-selected ServiceNow Table API records such as incidents or cases; generic table names are SDK-owned schema plumbing, not generated per-table coverage.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "servicenowRecord", label: "ServiceNow Record" },
        { kind: "servicenowIncident", label: "ServiceNow Incident", schemaName: "incident" },
        { kind: "servicenowAttachment", label: "ServiceNow Attachment" },
        { kind: "servicenowImportSetRecord", label: "ServiceNow Import Set Record" },
      ],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read ServiceNow records",
      description: "Reads ServiceNow Table API records by table and sys_id.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "servicenowRecord", label: "ServiceNow Record" }, { kind: "servicenowAttachment", label: "ServiceNow Attachment" }, { kind: "servicenowImportSetRecord", label: "ServiceNow Import Set Record" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update ServiceNow records",
      description: "Updates ServiceNow Table API records such as incidents, comments, state, or assignment fields.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "servicenowRecord", label: "ServiceNow Record" }, { kind: "servicenowIncident", label: "ServiceNow Incident", schemaName: "incident" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search ServiceNow records",
      description: "Queries ServiceNow Table API records with SDK-user-supplied sysparm_query and field constraints.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "servicenowRecord", label: "ServiceNow Record" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send customer-visible updates",
      description: "Posts customer-visible comments to ServiceNow incident records.",
      audiences: ["mixed"],
      providerObjects: [{ kind: "servicenowIncident", label: "ServiceNow Incident", schemaName: "incident" }],
      requiresCredential: true,
      sideEffect: true,
      externallyVisible: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Create internal notes",
      description: "Creates internal work notes on ServiceNow incident records.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "servicenowIncident", label: "ServiceNow Incident", schemaName: "incident" }],
      requiresCredential: true,
      sideEffect: true,
      externallyVisible: false,
      changesWorkflow: true,
      exposesSensitiveData: true,
    },
    {
      capability: "attach",
      label: "Attach files to ServiceNow records",
      description: "Uploads attachments to ServiceNow records.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "servicenowAttachment", label: "ServiceNow Attachment" }],
      requiresCredential: true,
      sideEffect: true,
      externallyVisible: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Attach record handoff to ServiceNow",
      description: "Provides Table API incident, attachment, and import-set operations used by SDK-user-configured record handoff workflows; this is not native Virtual Agent or Live Agent Chat transfer coverage.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "servicenowIncident", label: "ServiceNow Incident", schemaName: "incident" }, { kind: "servicenowAttachment", label: "ServiceNow Attachment" }, { kind: "servicenowImportSetRecord", label: "ServiceNow Import Set Record" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "ServiceNow records can contain customer data, support notes, internal assignment data, and attached workflow context.",
    "ServiceNow credentials stay server-side and are never exposed through Studio credential status.",
  ],
  limitations: [
    "Available tables, fields, ACLs, business rules, and mandatory fields are owned by the SDK user's ServiceNow instance.",
    "Handoff timing, approval, field mapping, assignment, and customer visibility are SDK-user configuration.",
  ],
  metadata: {
    implementation: {
      strategy: "official-sdk-connector",
      runtimePackage: "@cognidesk/integration-ticketing-servicenow",
      rawClientEscapeHatch: "ServiceNowTicketingClient.rawClient",
      sdkPackage: "@servicenow/sdk-api",
      sdkRuntimeSurface: "Connector.fetch and Connector.queryTable",
      manifestImport: "no-sdk-client-initialization",
      defaultClientPolicy: "use-official-servicenow-sdk-api-connector-for-oauth-runtime-transport; require ServiceNowRawClient injection for non-OAuth tenant-auth transports",
      rawClientOverride: true,
      packageOwnedRestClient: false,
    },
    sdkDecision: {
      checkedAt: "2026-06-25",
      package: "@servicenow/sdk-api",
      checkedVersion: "4.8.0",
      license: "MIT",
      result: "official-sdk-runtime-connector-not-ticketing-client",
      reason: "The official ServiceNow SDK API exports Connector.fetch and Connector.queryTable as runtime instance transport. It does not provide a ticketing-specific Table/Attachment/Import Set client, so Cognidesk translates ticketing operations into the official connector transport and retains typed rawClient injection for host-owned clients.",
    },
    checkedProviderSdk: {
      package: "@servicenow/sdk-api",
      checkedVersion: "4.8.0",
      license: "MIT",
      result: "used-as-runtime-connector",
      reason: "OAuth default runtime uses Connector.fetch for create/read/update/attachment/import-set calls and Connector.queryTable for compatible table search calls. Non-OAuth tenant-auth transports must be supplied through ServiceNowRawClient injection instead of a package-owned REST fallback.",
    },
    checkedProviderApiCoverage: {
      verifiedAt: "2026-06-18",
      sourceKind: "checked-endpoint-family-inventory",
      coverageArtifact: "docs/provider-coverage/servicenow-checked-table-attachment-importset-2026-06-18.inventory.json",
      familyCount: 4,
      implementedFamilyCount: 3,
      gapFamilyCount: 1,
      implementedOperationCount: 11,
      fullCoverageExportRequirement: "Full instance-specific ServiceNow coverage requires REST API Explorer/OpenAPI export for enabled APIs, table dictionary export, plugin/product inventory, ACL/role evidence, and scripted REST definitions from the SDK user's instance.",
    },
    channelCoverage: {
      tableRecords: "typed-json-create-read-update-search",
      genericTableApi: "sdk-owned-classified-endpoint",
      incidents: "typed-create-comment-worknote",
      attachments: "typed-upload-list",
      importSets: "typed-json-create-read",
      readinessSearch: "typed-search",
      csmCaseApi: "provider-supported-not-typed",
      virtualAgentApi: "provider-supported-not-typed",
      virtualAgentBotIntegrationApi: "provider-supported-not-typed",
      liveAgentTransfer: "provider-supported-not-typed",
      connectConversationScopedApi: "provider-supported-not-typed",
      taskTableRecords: "provider-supported-not-typed",
      cccifCustomChatIntegration: "provider-supported-not-typed",
      catalogWorkflowScriptedRest: "provider-supported-not-implemented",
      attachmentDownloadDelete: "provider-supported-not-implemented",
      arbitraryTableTyping: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
