import type { ProviderOperationDeclarationInput } from "@cognidesk/core";

export const serviceNowTicketingProviderOperations = [
  {
    alias: "ticket.create",
    providerOperation: "Table API incident create",
    capability: "create-provider-object",
    label: "Create ServiceNow incident",
    description: "Creates a ServiceNow incident record through the configured Table API client.",
    providerObject: "ticket",
    audiences: ["internal-support", "mixed"],
    requiresCredential: true,
    sideEffect: true,
    changesWorkflow: true,
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.read",
    providerOperation: "Table API record read",
    capability: "read-provider-object",
    label: "Read ServiceNow ticket record",
    description: "Reads an incident or SDK-user-selected ServiceNow table record by sys_id.",
    providerObject: "ticket",
    audiences: ["internal-support", "mixed"],
    requiresCredential: true,
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.update",
    providerOperation: "Table API record update",
    capability: "update-provider-object",
    label: "Update ServiceNow ticket record",
    description: "Updates an incident or SDK-user-selected ServiceNow table record by sys_id.",
    providerObject: "ticket",
    audiences: ["internal-support", "mixed"],
    requiresCredential: true,
    sideEffect: true,
    changesWorkflow: true,
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.search",
    providerOperation: "Table API record search",
    capability: "search-provider-object",
    label: "Search ServiceNow ticket records",
    description: "Searches incident or SDK-user-selected ServiceNow table records with sysparm query controls.",
    providerObject: "ticket",
    audiences: ["internal-support", "mixed"],
    requiresCredential: true,
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.comment.create",
    providerOperation: "Table API incident comments update",
    capability: "send",
    label: "Create ServiceNow incident comment",
    description: "Adds a customer-visible incident comment through a Table API update.",
    providerObject: "ticketComment",
    audiences: ["mixed"],
    requiresCredential: true,
    requiresApproval: true,
    sideEffect: true,
    externallyVisible: true,
    changesWorkflow: true,
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.internalNote.create",
    providerOperation: "Table API incident work_notes update",
    capability: "draft",
    label: "Create ServiceNow incident work note",
    description: "Adds an internal incident work note through a Table API update.",
    providerObject: "internalNote",
    audiences: ["internal-support", "mixed"],
    requiresCredential: true,
    sideEffect: true,
    externallyVisible: false,
    changesWorkflow: true,
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.attachments.add",
    providerOperation: "Attachment API file upload",
    capability: "attach",
    label: "Upload ServiceNow ticket attachment",
    description: "Uploads an attachment for an incident or SDK-user-selected table record.",
    providerObject: "attachment",
    audiences: ["internal-support", "mixed"],
    requiresCredential: true,
    sideEffect: true,
    externallyVisible: true,
    exposesSensitiveData: true,
  },
  {
    alias: "ticket.attachments.list",
    providerOperation: "Attachment API list",
    capability: "read-provider-object",
    label: "List ServiceNow ticket attachments",
    description: "Lists attachments through ServiceNow Attachment API query controls.",
    providerObject: "attachment",
    audiences: ["internal-support", "mixed"],
    requiresCredential: true,
    exposesSensitiveData: true,
  },
  {
    alias: "servicenow.record.create",
    providerOperation: "Table API generic record create",
    capability: "create-provider-object",
    label: "Create ServiceNow table record",
    description: "Creates a record in an SDK-user-selected ServiceNow table.",
    providerObject: "servicenowRecord",
    audiences: ["internal-support", "mixed"],
    requiresCredential: true,
    sideEffect: true,
    changesWorkflow: true,
    exposesSensitiveData: true,
    extension: true,
  },
  {
    alias: "servicenow.importSet.insert",
    providerOperation: "Import Set API insert",
    capability: "create-provider-object",
    label: "Insert ServiceNow import set row",
    description: "Inserts a row into an SDK-user-selected Import Set staging table.",
    providerObject: "servicenowImportSetRecord",
    audiences: ["internal-support", "mixed"],
    requiresCredential: true,
    sideEffect: true,
    changesWorkflow: true,
    exposesSensitiveData: true,
    extension: true,
  },
  {
    alias: "servicenow.importSet.result.read",
    providerOperation: "Import Set API result read",
    capability: "read-provider-object",
    label: "Read ServiceNow import set result",
    description: "Reads the Import Set API result for an inserted staging table row.",
    providerObject: "servicenowImportSetRecord",
    audiences: ["internal-support", "mixed"],
    requiresCredential: true,
    exposesSensitiveData: true,
    extension: true,
  },
] satisfies ProviderOperationDeclarationInput[];

export type ServiceNowTicketingOperationAlias =
  typeof serviceNowTicketingProviderOperations[number]["alias"];
