import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";

export const salesforceTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.salesforce",
  name: "Salesforce Service Cloud",
  packageName: "@cognidesk/integrations",
  provider: "salesforce",
  category: "ticketing",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage is limited to selected Salesforce REST API and Service Cloud support primitives: Case create/read/update/search, sObject describe, assignment-rule header opt-in, CaseComment, FeedItem, Contact/Account SOQL search, user/org readiness, and SDK-user inbound event relay parsing.",
      "The generic SOQL `query()` helper is SDK-user-owned endpoint plumbing and does not prove generated broader sObject, custom-object, relationship, or Service Cloud coverage.",
      "This is not full Salesforce REST, Service Cloud, metadata, composite, Bulk, Pub/Sub, Streaming, Platform Event, EmailMessage, ContentVersion/file, assignment-rule discovery, or broader sObject API coverage.",
    ],
    evidence: [
      { label: "Salesforce REST API resources", url: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_list.htm" },
      { label: "Salesforce sObject Describe", url: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_describe.htm" },
      { label: "Salesforce Assignment Rule header", url: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_autoassign.htm" },
      { label: "Salesforce Case object reference", url: "https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_case.htm" },
      { label: "Salesforce CaseComment object reference", url: "https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_casecomment.htm" },
      { label: "Salesforce FeedItem object reference", url: "https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_feeditem.htm" },
      { label: "Salesforce Platform Events Developer Guide", url: "https://developer.salesforce.com/docs/atlas.en-us.platform_events.meta/platform_events/platform_events_intro.htm" },
      { label: "Salesforce Streaming API overview", url: "https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/intro_stream.htm" },
      { label: "Salesforce Outbound Messaging setup", url: "https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_om_outboundmessaging_setting_up.htm" },
      { label: "Salesforce Enhanced Chat API", url: "https://developer.salesforce.com/docs/service/messaging-api/overview" },
      { label: "Salesforce Conversation Entries Connect REST API", url: "https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_resources_conversation_entries.htm" },
      { label: "Salesforce MessagingSession object reference", url: "https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_messagingsession.htm" },
      { label: "Salesforce Conversation Toolkit API", url: "https://developer.salesforce.com/docs/platform/lightning-component-reference/guide/lightning-conversation-toolkit-api.html" },
    ],
  },
  credentialRequirements: [
    {
      id: "salesforce-instance",
      label: "Salesforce instance URL",
      description: "The SDK user's Salesforce org instance URL, for example https://example.my.salesforce.com.",
      required: true,
    },
    {
      id: "salesforce-oauth-access",
      label: "Salesforce OAuth access token",
      description: "Server-side OAuth bearer token with SDK-user-selected Salesforce REST API access.",
      scopes: ["api", "refresh_token", "openid"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "salesforce-webhook-secret",
      label: "Salesforce webhook shared secret or verifier",
      description: "SDK-user-configured secret or verifier used before accepting Platform Event, Outbound Message, or webhook relay payloads.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Parse Salesforce event relay payloads",
      description: "Validates and parses SDK-user-configured Salesforce Platform Event, Outbound Message, or webhook relay HTTP payloads; it does not subscribe to Pub/Sub, Streaming API, or SOAP outbound messages.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "salesforceEvent", label: "Salesforce Event" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Salesforce cases and comments",
      description: "Creates Salesforce Service Cloud Case, CaseComment, and FeedItem records when SDK-user policy permits.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "salesforceCase", label: "Salesforce Case", schemaName: "Case" },
        { kind: "salesforceCaseComment", label: "Salesforce Case Comment", schemaName: "CaseComment" },
        { kind: "salesforceFeedItem", label: "Salesforce Feed Item", schemaName: "FeedItem" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Salesforce cases and org identity",
      description: "Reads Salesforce cases, comments, feed items, contacts, accounts, current user info, and organization readiness details.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "salesforceCase", label: "Salesforce Case", schemaName: "Case" },
        { kind: "salesforceCaseComment", label: "Salesforce Case Comment", schemaName: "CaseComment" },
        { kind: "salesforceFeedItem", label: "Salesforce Feed Item", schemaName: "FeedItem" },
        { kind: "salesforceContact", label: "Salesforce Contact", schemaName: "Contact" },
        { kind: "salesforceAccount", label: "Salesforce Account", schemaName: "Account" },
        { kind: "salesforceOrganization", label: "Salesforce Organization", schemaName: "Organization" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Salesforce cases",
      description: "Updates Salesforce Case fields such as status, priority, owner, contact, account, or SDK-user-configured custom fields.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "salesforceCase", label: "Salesforce Case", schemaName: "Case" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Salesforce records",
      description: "Searches Salesforce cases, contacts, and accounts with bounded helpers; the generic SOQL query helper is an SDK-user-owned escape hatch and not generated broader Salesforce object coverage.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "salesforceCase", label: "Salesforce Case", schemaName: "Case" },
        { kind: "salesforceContact", label: "Salesforce Contact", schemaName: "Contact" },
        { kind: "salesforceAccount", label: "Salesforce Account", schemaName: "Account" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Attach case handoff to Salesforce",
      description: "Provides Case creation/update plus configurable comment and feed-item foundations for SDK-user-owned record handoff workflows; this is not native Enhanced Chat, Live Agent, Messaging, or Voice transfer coverage.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "salesforceCase", label: "Salesforce Case", schemaName: "Case" },
        { kind: "salesforceCaseComment", label: "Salesforce Case Comment", schemaName: "CaseComment" },
        { kind: "salesforceFeedItem", label: "Salesforce Feed Item", schemaName: "FeedItem" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "salesforce.webhook-verifier",
      label: "Validate Salesforce webhook payloads",
      description: "Requires a configured shared secret or verifier before parsing Salesforce event relay, Platform Event, or Outbound Message payloads.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "salesforceWebhookRequest", label: "Salesforce Webhook Request" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Salesforce cases, comments, feed items, contacts, accounts, platform events, and outbound messages can contain customer data and internal support context.",
    "Salesforce OAuth tokens and webhook secrets stay server-side and are represented in Studio only as readiness and scope status.",
  ],
  limitations: [
    "Salesforce Case record types, required fields, queues, owners, entitlements, assignment rules, triggers, Flow automation, field-level security, and Service Cloud licenses are owned by the SDK user's org.",
    "SOQL filters, field mappings, webhook relay shape, Platform Event schema, Outbound Message configuration, and event subscription delivery are SDK-user configuration.",
    "SDK users own handoff timing, customer identity matching, case visibility, comment/feed visibility, consent, retention, redaction, and outbound notification policy before calling Salesforce APIs.",
  ],
  metadata: {
    checkedProviderApiCoverage: {
      verifiedAt: "2026-06-18",
      sourceKind: "checked-endpoint-family-inventory",
      coverageArtifact: "docs/provider-coverage/salesforce-checked-rest-service-cloud-2026-06-18.inventory.json",
      familyCount: 5,
      implementedFamilyCount: 4,
      gapFamilyCount: 1,
      implementedOperationCount: 16,
      fullCoverageExportRequirement: "Full org-specific Salesforce coverage requires sObject describe/metadata exports, enabled Service Cloud product evidence, event schemas, connected-app scopes, permission sets, and object/field-level security evidence from the SDK user's org.",
    },
    channelCoverage: {
      cases: "typed-create-read-update-search",
      caseComments: "typed-create-read",
      feedItems: "typed-create-read",
      contactsAccounts: "typed-read-search",
      genericSoqlQuery: "sdk-owned-classified-endpoint",
      organizationReadiness: "typed-read",
      sObjectDescribe: "typed-read",
      eventRelay: "typed-verify-parse-only",
      platformEventsOutboundMessages: "typed-parse-relay-only",
      enhancedChatApi: "provider-supported-not-typed",
      messagingSessions: "provider-supported-not-typed",
      conversationDataGetApi: "provider-supported-not-typed",
      conversationEntriesConnectRest: "provider-supported-not-typed",
      liveAgentChatRestApi: "provider-supported-not-typed",
      tasks: "provider-supported-not-typed",
      voiceCallsTranscripts: "provider-supported-not-typed",
      emailMessage: "provider-supported-not-implemented",
      filesContentVersion: "provider-supported-not-implemented",
      streamingPubSubSubscriptions: "provider-supported-not-implemented",
      compositeBulkMetadataCrud: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
