import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import { HUBSPOT_FULL_API_GENERATED_FUNCTION_COUNT } from "./full-api-client.generated.js";
import {
  HUBSPOT_FULL_API_OPERATION_COUNT,
  HUBSPOT_FULL_API_SPEC_COUNT,
  HUBSPOT_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const hubSpotTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.hubspot",
  name: "HubSpot Service Hub",
  packageName: "@cognidesk/integrations",
  provider: "hubspot",
  category: "ticketing",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every selected current API entry in HubSpot's official public spec index.",
      "Typed convenience helpers remain available for HubSpot CRM v3 ticket/contact/company read-write records, note create/update records, selected associations, CRM search, properties, owners, ticket pipelines, account readiness, webhook payload parsing, and v3 request-signature validation used by Cognidesk support workflows.",
      "Generated functions cover HubSpot's date-versioned 2026-03 surfaces where they are the current public spec, including broader CRM objects, pipeline/stage mutation, owner reads, properties CRUD, conversations and custom channels, files, timeline events, webhooks, CMS, marketing, automation, and account APIs. SDK users still own HubSpot app scopes, entitlements, portal-specific configuration, and private-app/OAuth credential policy.",
    ],
    evidence: [
      { label: "HubSpot public OpenAPI spec index", url: "https://api.hubapi.com/public/api/spec/v1/specs" },
      { label: "HubSpot CRM Tickets API guide", url: "https://developers.hubspot.com/docs/api-reference/legacy/crm/objects/tickets/guide" },
      { label: "HubSpot CRM Notes API guide", url: "https://developers.hubspot.com/docs/api-reference/legacy/crm/activities/notes/guide" },
      { label: "HubSpot CRM search guide", url: "https://developers.hubspot.com/docs/api-reference/latest/crm/search-the-crm" },
      { label: "HubSpot CRM properties guide", url: "https://developers.hubspot.com/docs/api-reference/legacy/crm/properties/guide" },
      { label: "HubSpot CRM owners guide", url: "https://developers.hubspot.com/docs/api-reference/legacy/crm/owners/guide" },
      { label: "HubSpot CRM pipelines guide", url: "https://developers.hubspot.com/docs/api-reference/legacy/crm/pipelines/guide" },
      { label: "HubSpot account information details", url: "https://developers.hubspot.com/docs/api-reference/legacy/account/account-information/get-account-details" },
      { label: "HubSpot request validation", url: "https://developers.hubspot.com/docs/apps/legacy-apps/authentication/validating-requests" },
    ],
  },
  credentialRequirements: [
    {
      id: "hubspot-private-app-token",
      label: "HubSpot private app token",
      description: "Server-side private app access token for HubSpot CRM and Service Hub APIs.",
      scopes: [
        "tickets",
        "crm.objects.contacts.read",
        "crm.objects.contacts.write",
        "crm.objects.companies.read",
        "crm.objects.companies.write",
        "crm.objects.owners.read",
      ],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "hubspot-portal",
      label: "HubSpot portal",
      description: "The SDK user's HubSpot portal ID, used for readiness, routing, and webhook ownership checks.",
      required: true,
    },
    {
      id: "hubspot-app",
      label: "HubSpot app",
      description: "The HubSpot app or private app identifier that owns webhook subscriptions and API credentials.",
      required: false,
    },
    {
      id: "hubspot-webhook-secret",
      label: "HubSpot webhook client secret",
      description: "Server-side app client secret used to validate X-HubSpot-Signature-v3 webhook requests.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive HubSpot webhooks",
      description: "Validates and parses HubSpot CRM webhook events for SDK-user-owned ticketing workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "hubspotWebhookEvent", label: "HubSpot Webhook Event" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create HubSpot CRM records",
      description: "Creates HubSpot tickets, contacts, companies, notes, and SDK-user-selected associations.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "hubspotTicket", label: "HubSpot Ticket", schemaName: "tickets" },
        { kind: "hubspotContact", label: "HubSpot Contact", schemaName: "contacts" },
        { kind: "hubspotCompany", label: "HubSpot Company", schemaName: "companies" },
        { kind: "hubspotNote", label: "HubSpot Note", schemaName: "notes" },
        { kind: "hubspotAssociation", label: "HubSpot Association", schemaName: "associations" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read HubSpot CRM records",
      description: "Reads HubSpot tickets, contacts, companies, association labels, and account readiness details.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "hubspotTicket", label: "HubSpot Ticket", schemaName: "tickets" },
        { kind: "hubspotContact", label: "HubSpot Contact", schemaName: "contacts" },
        { kind: "hubspotCompany", label: "HubSpot Company", schemaName: "companies" },
        { kind: "hubspotAssociationLabel", label: "HubSpot Association Label", schemaName: "associations/labels" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update HubSpot CRM records",
      description: "Updates HubSpot ticket, contact, company, note, pinned activity, assignment, pipeline, and custom fields when SDK-user policy permits.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "hubspotTicket", label: "HubSpot Ticket", schemaName: "tickets" },
        { kind: "hubspotContact", label: "HubSpot Contact", schemaName: "contacts" },
        { kind: "hubspotCompany", label: "HubSpot Company", schemaName: "companies" },
        { kind: "hubspotNote", label: "HubSpot Note", schemaName: "notes" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search HubSpot CRM records",
      description: "Searches HubSpot tickets, contacts, and companies using SDK-user-supplied CRM Search API filters, sorts, properties, and pagination.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "hubspotTicket", label: "HubSpot Ticket", schemaName: "tickets" },
        { kind: "hubspotContact", label: "HubSpot Contact", schemaName: "contacts" },
        { kind: "hubspotCompany", label: "HubSpot Company", schemaName: "companies" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Attach support handoff to HubSpot",
      description: "Provides ticket creation/update, contact/company lookup, and configurable internal handoff notes that can associate existing HubSpot file IDs.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "hubspotTicket", label: "HubSpot Ticket", schemaName: "tickets" },
        { kind: "hubspotNote", label: "HubSpot Note", schemaName: "notes" },
        { kind: "hubspotAssociation", label: "HubSpot Association", schemaName: "associations" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "hubspot.request-signature-v3",
      label: "Validate HubSpot v3 request signatures",
      description: "Validates X-HubSpot-Signature-v3 using method, URI, raw body, timestamp, and app client secret before parsing webhook JSON.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "hubspotSignedRequest", label: "HubSpot Signed Request" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "HubSpot tickets, notes, contacts, companies, webhook events, owners, associations, and custom properties can contain customer data and internal support context.",
    "HubSpot access tokens and webhook secrets stay server-side and are represented in Studio only as readiness and scope status.",
  ],
  limitations: [
    "Ticket pipelines, pipeline stages, priorities, owners, custom properties, association labels, webhook subscriptions, private app scopes, and Service Hub entitlements are owned by the SDK user's HubSpot portal.",
    "HubSpot association labels are directional; SDK users must configure the correct associationTypeId values for their portal and handoff flow.",
    "SDK-user-owned configuration controls handoff timing, contact/company matching, portal routing, note visibility, consent, retention, redaction, and outbound notification policy before calling HubSpot APIs.",
  ],
  metadata: {
    channelCoverage: {
      tickets: "typed-create-read-update-search",
      contacts: "typed-create-read-update-search",
      companies: "typed-create-read-update-search",
      notes: "typed-create-update-handoff",
      associations: "typed-create-read-labels",
      propertiesOwnersPipelines: "typed-read",
      webhooks: "typed-verify-parse-only",
      accountReadiness: "typed-read",
      fullHubSpotPublicApiOperations: "generated-per-operation-functions",
      conversationsInbox: "generated-full-surface",
      filesTimelineEvents: "generated-full-surface",
      webhookSubscriptionLifecycle: "generated-full-surface",
      dateVersioned2026Api: "generated-full-surface",
    },
    fullProviderApiVerification: {
      provider: "hubspot",
      apiVersion: HUBSPOT_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-17",
      coverageArtifact: "docs/provider-coverage/hubspot-full-api-2026-06-17.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/hubspot-full-api-2026-06-17.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/hubspot-full-api-2026-06-17.functions.json",
      documentedSpecCount: HUBSPOT_FULL_API_SPEC_COUNT,
      documentedOperationCount: HUBSPOT_FULL_API_OPERATION_COUNT,
      implementedOperationCount: HUBSPOT_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: HUBSPOT_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
