// Generated from official @cognidesk/integrations API documentation.
// Do not edit by hand; run scripts/generate-ticketing-provider-coverage.mjs after checking upstream docs.

export type GorgiasFullApiOperationMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface GorgiasFullApiSpec {
  title: string;
  version: string;
  openapi: string;
  sourceUrl: string;
  pathCount: number;
  documentedOperationCount: number;
}

export interface GorgiasFullApiOperation {
  id: string;
  operationId: string;
  functionName: string;
  method: GorgiasFullApiOperationMethod;
  path: string;
  tags: readonly string[];
  summary: string;
  sourceUrl: string;
}

export const GORGIAS_FULL_API_GENERATED_AT = "2026-06-18" as const;
export const GORGIAS_FULL_API_SPEC_SOURCE = "https://developers.gorgias.com/llms.txt" as const;
export const GORGIAS_FULL_API_SPEC_VERSION = "gorgias-2026-06-18" as const;
export const GORGIAS_FULL_API_OPERATION_COUNT = 113 as const;

export const GORGIAS_FULL_API_SPEC: GorgiasFullApiSpec = {
  "title": "Gorgias REST API",
  "version": "1.0.0",
  "openapi": "per-endpoint OpenAPI JSON blocks",
  "sourceUrl": "https://developers.gorgias.com/llms.txt",
  "pathCount": 60,
  "documentedOperationCount": 113
};

export const GORGIAS_FULL_API_OPERATIONS = JSON.parse("[{\"id\":\"download-file\",\"operationId\":\"download-file\",\"method\":\"GET\",\"path\":\"/api/{file_type}/download/{domain_hash}/{resource_name}\",\"tags\":[\"Files\"],\"summary\":\"Download a file\",\"sourceUrl\":\"https://developers.gorgias.com/reference/download-file.md\",\"functionName\":\"gorgiasDownloadFile\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-account\",\"operationId\":\"get-account\",\"method\":\"GET\",\"path\":\"/api/account\",\"tags\":[\"Account\"],\"summary\":\"Retrieve your account\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-account.md\",\"functionName\":\"gorgiasGetAccount\",\"implementationStatus\":\"support-helper-and-generated\",\"implementedBy\":\"readiness\"},{\"id\":\"list-account-settings\",\"operationId\":\"list-account-settings\",\"method\":\"GET\",\"path\":\"/api/account/settings\",\"tags\":[\"Account\"],\"summary\":\"List settings\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-account-settings.md\",\"functionName\":\"gorgiasListAccountSettings\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-account-setting\",\"operationId\":\"create-account-setting\",\"method\":\"POST\",\"path\":\"/api/account/settings\",\"tags\":[\"Account\"],\"summary\":\"Create a setting\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-account-setting.md\",\"functionName\":\"gorgiasCreateAccountSetting\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-account-setting\",\"operationId\":\"update-account-setting\",\"method\":\"PUT\",\"path\":\"/api/account/settings/{id}\",\"tags\":[\"Account\"],\"summary\":\"Update a setting\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-account-setting.md\",\"functionName\":\"gorgiasUpdateAccountSetting\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-custom-fields\",\"operationId\":\"list-custom-fields\",\"method\":\"GET\",\"path\":\"/api/custom-fields\",\"tags\":[\"Custom Fields\"],\"summary\":\"List custom fields\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-custom-fields.md\",\"functionName\":\"gorgiasListCustomFields\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-custom-field\",\"operationId\":\"create-custom-field\",\"method\":\"POST\",\"path\":\"/api/custom-fields\",\"tags\":[\"Custom Fields\"],\"summary\":\"Create a custom field\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-custom-field.md\",\"functionName\":\"gorgiasCreateCustomField\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-custom-fields\",\"operationId\":\"update-custom-fields\",\"method\":\"PUT\",\"path\":\"/api/custom-fields\",\"tags\":[\"Custom Fields\"],\"summary\":\"Bulk update a list of custom fields\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-custom-fields.md\",\"functionName\":\"gorgiasUpdateCustomFields\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-custom-field\",\"operationId\":\"get-custom-field\",\"method\":\"GET\",\"path\":\"/api/custom-fields/{id}\",\"tags\":[\"Custom Fields\"],\"summary\":\"Retrieve a custom field\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-custom-field.md\",\"functionName\":\"gorgiasGetCustomField\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-custom-field\",\"operationId\":\"update-custom-field\",\"method\":\"PUT\",\"path\":\"/api/custom-fields/{id}\",\"tags\":[\"Custom Fields\"],\"summary\":\"Update a custom field\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-custom-field.md\",\"functionName\":\"gorgiasUpdateCustomField\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-customers\",\"operationId\":\"delete-customers\",\"method\":\"DELETE\",\"path\":\"/api/customers\",\"tags\":[\"Customers\"],\"summary\":\"Delete customers\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-customers.md\",\"functionName\":\"gorgiasDeleteCustomers\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-customers\",\"operationId\":\"list-customers\",\"method\":\"GET\",\"path\":\"/api/customers\",\"tags\":[\"Customers\"],\"summary\":\"List customers\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-customers.md\",\"functionName\":\"gorgiasListCustomers\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-customer\",\"operationId\":\"create-customer\",\"method\":\"POST\",\"path\":\"/api/customers\",\"tags\":[\"Customers\"],\"summary\":\"Create a customer\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-customer.md\",\"functionName\":\"gorgiasCreateCustomer\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-customer-custom-fields-values\",\"operationId\":\"list-customer-custom-fields-values\",\"method\":\"GET\",\"path\":\"/api/customers/{customer_id}/custom-fields\",\"tags\":[\"Customers\"],\"summary\":\"List customer field values\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-customer-custom-fields-values.md\",\"functionName\":\"gorgiasListCustomerCustomFieldsValues\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-customer-custom-field-values\",\"operationId\":\"update-customer-custom-field-values\",\"method\":\"PUT\",\"path\":\"/api/customers/{customer_id}/custom-fields\",\"tags\":[\"Customers\"],\"summary\":\"Update customer fields values\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-customer-custom-field-values.md\",\"functionName\":\"gorgiasUpdateCustomerCustomFieldValues\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-customer-custom-field-value\",\"operationId\":\"delete-customer-custom-field-value\",\"method\":\"DELETE\",\"path\":\"/api/customers/{customer_id}/custom-fields/{id}\",\"tags\":[\"Customers\"],\"summary\":\"Delete customer field value\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-customer-custom-field-value.md\",\"functionName\":\"gorgiasDeleteCustomerCustomFieldValue\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-customer-custom-field-value\",\"operationId\":\"update-customer-custom-field-value\",\"method\":\"PUT\",\"path\":\"/api/customers/{customer_id}/custom-fields/{id}\",\"tags\":[\"Customers\"],\"summary\":\"Update customer field value\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-customer-custom-field-value.md\",\"functionName\":\"gorgiasUpdateCustomerCustomFieldValue\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-customer-data\",\"operationId\":\"update-customer-data\",\"method\":\"PUT\",\"path\":\"/api/customers/{customer_id}/data\",\"tags\":[\"Customers\"],\"summary\":\"Set customer data\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-customer-data.md\",\"functionName\":\"gorgiasUpdateCustomerData\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-customer\",\"operationId\":\"delete-customer\",\"method\":\"DELETE\",\"path\":\"/api/customers/{id}\",\"tags\":[\"Customers\"],\"summary\":\"Delete a customer\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-customer.md\",\"functionName\":\"gorgiasDeleteCustomer\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-customer\",\"operationId\":\"get-customer\",\"method\":\"GET\",\"path\":\"/api/customers/{id}\",\"tags\":[\"Customers\"],\"summary\":\"Retrieve a customer\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-customer.md\",\"functionName\":\"gorgiasGetCustomer\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-customer\",\"operationId\":\"update-customer\",\"method\":\"PUT\",\"path\":\"/api/customers/{id}\",\"tags\":[\"Customers\"],\"summary\":\"Update a customer\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-customer.md\",\"functionName\":\"gorgiasUpdateCustomer\",\"implementationStatus\":\"generated-only\"},{\"id\":\"merge-customers\",\"operationId\":\"merge-customers\",\"method\":\"PUT\",\"path\":\"/api/customers/merge\",\"tags\":[\"Customers\"],\"summary\":\"Merge two customers\",\"sourceUrl\":\"https://developers.gorgias.com/reference/merge-customers.md\",\"functionName\":\"gorgiasMergeCustomers\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-events\",\"operationId\":\"list-events\",\"method\":\"GET\",\"path\":\"/api/events\",\"tags\":[\"Events\"],\"summary\":\"List events\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-events.md\",\"functionName\":\"gorgiasListEvents\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-event\",\"operationId\":\"get-event\",\"method\":\"GET\",\"path\":\"/api/events/{id}\",\"tags\":[\"Events\"],\"summary\":\"Retrieve an event\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-event.md\",\"functionName\":\"gorgiasGetEvent\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-integrations\",\"operationId\":\"list-integrations\",\"method\":\"GET\",\"path\":\"/api/integrations\",\"tags\":[\"Integrations\"],\"summary\":\"List integrations\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-integrations.md\",\"functionName\":\"gorgiasListIntegrations\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-integration\",\"operationId\":\"create-integration\",\"method\":\"POST\",\"path\":\"/api/integrations\",\"tags\":[\"Integrations\"],\"summary\":\"Create an integration\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-integration.md\",\"functionName\":\"gorgiasCreateIntegration\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-integration\",\"operationId\":\"delete-integration\",\"method\":\"DELETE\",\"path\":\"/api/integrations/{id}\",\"tags\":[\"Integrations\"],\"summary\":\"Delete an integration\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-integration.md\",\"functionName\":\"gorgiasDeleteIntegration\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-integration\",\"operationId\":\"get-integration\",\"method\":\"GET\",\"path\":\"/api/integrations/{id}\",\"tags\":[\"Integrations\"],\"summary\":\"Retrieve an integration\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-integration.md\",\"functionName\":\"gorgiasGetIntegration\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-integration\",\"operationId\":\"update-integration\",\"method\":\"PUT\",\"path\":\"/api/integrations/{id}\",\"tags\":[\"Integrations\"],\"summary\":\"Update an integration\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-integration.md\",\"functionName\":\"gorgiasUpdateIntegration\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-jobs\",\"operationId\":\"list-jobs\",\"method\":\"GET\",\"path\":\"/api/jobs\",\"tags\":[\"Jobs\"],\"summary\":\"List jobs\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-jobs.md\",\"functionName\":\"gorgiasListJobs\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-job\",\"operationId\":\"create-job\",\"method\":\"POST\",\"path\":\"/api/jobs\",\"tags\":[\"Jobs\"],\"summary\":\"Create a job\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-job.md\",\"functionName\":\"gorgiasCreateJob\",\"implementationStatus\":\"generated-only\"},{\"id\":\"cancel-job\",\"operationId\":\"cancel-job\",\"method\":\"DELETE\",\"path\":\"/api/jobs/{id}\",\"tags\":[\"Jobs\"],\"summary\":\"Cancel a job\",\"sourceUrl\":\"https://developers.gorgias.com/reference/cancel-job.md\",\"functionName\":\"gorgiasCancelJob\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-job\",\"operationId\":\"get-job\",\"method\":\"GET\",\"path\":\"/api/jobs/{id}\",\"tags\":[\"Jobs\"],\"summary\":\"Retrieve a job\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-job.md\",\"functionName\":\"gorgiasGetJob\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-job\",\"operationId\":\"update-job\",\"method\":\"PUT\",\"path\":\"/api/jobs/{id}\",\"tags\":[\"Jobs\"],\"summary\":\"Update a job\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-job.md\",\"functionName\":\"gorgiasUpdateJob\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-macros\",\"operationId\":\"list-macros\",\"method\":\"GET\",\"path\":\"/api/macros\",\"tags\":[\"Macros\"],\"summary\":\"List macros\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-macros.md\",\"functionName\":\"gorgiasListMacros\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-macro\",\"operationId\":\"create-macro\",\"method\":\"POST\",\"path\":\"/api/macros\",\"tags\":[\"Macros\"],\"summary\":\"Create a macro\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-macro.md\",\"functionName\":\"gorgiasCreateMacro\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-macro\",\"operationId\":\"delete-macro\",\"method\":\"DELETE\",\"path\":\"/api/macros/{id}\",\"tags\":[\"Macros\"],\"summary\":\"Delete a macro\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-macro.md\",\"functionName\":\"gorgiasDeleteMacro\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-macro\",\"operationId\":\"get-macro\",\"method\":\"GET\",\"path\":\"/api/macros/{id}\",\"tags\":[\"Macros\"],\"summary\":\"Retrieve a macro\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-macro.md\",\"functionName\":\"gorgiasGetMacro\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-macro\",\"operationId\":\"update-macro\",\"method\":\"PUT\",\"path\":\"/api/macros/{id}\",\"tags\":[\"Macros\"],\"summary\":\"Update a macro\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-macro.md\",\"functionName\":\"gorgiasUpdateMacro\",\"implementationStatus\":\"generated-only\"},{\"id\":\"bulk-archive-macros\",\"operationId\":\"bulk-archive-macros\",\"method\":\"PUT\",\"path\":\"/api/macros/archive\",\"tags\":[\"Macros\"],\"summary\":\"Archive macros\",\"sourceUrl\":\"https://developers.gorgias.com/reference/bulk-archive-macros.md\",\"functionName\":\"gorgiasBulkArchiveMacros\",\"implementationStatus\":\"generated-only\"},{\"id\":\"bulk-unarchive-macros\",\"operationId\":\"bulk-unarchive-macros\",\"method\":\"PUT\",\"path\":\"/api/macros/unarchive\",\"tags\":[\"Macros\"],\"summary\":\"Unarchive macros\",\"sourceUrl\":\"https://developers.gorgias.com/reference/bulk-unarchive-macros.md\",\"functionName\":\"gorgiasBulkUnarchiveMacros\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-messages\",\"operationId\":\"list-messages\",\"method\":\"GET\",\"path\":\"/api/messages\",\"tags\":[\"Ticket Messages\"],\"summary\":\"List messages\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-messages.md\",\"functionName\":\"gorgiasListMessages\",\"implementationStatus\":\"support-helper-and-generated\",\"implementedBy\":\"listMessages\"},{\"id\":\"search-metric-cards\",\"operationId\":\"search-metric-cards\",\"method\":\"GET\",\"path\":\"/api/metric-cards\",\"tags\":[\"Metric Cards\"],\"summary\":\"Search metric cards\",\"sourceUrl\":\"https://developers.gorgias.com/reference/search-metric-cards.md\",\"functionName\":\"gorgiasSearchMetricCards\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-metric-card\",\"operationId\":\"get-metric-card\",\"method\":\"GET\",\"path\":\"/api/metric-cards/{slug}\",\"tags\":[\"Metric Cards\"],\"summary\":\"Retrieve a metric card by slug\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-metric-card.md\",\"functionName\":\"gorgiasGetMetricCard\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-voice-call-events\",\"operationId\":\"list-voice-call-events\",\"method\":\"GET\",\"path\":\"/api/phone/voice-call-events\",\"tags\":[\"Voice Call Events\"],\"summary\":\"List voice call events\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-voice-call-events.md\",\"functionName\":\"gorgiasListVoiceCallEvents\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-voice-call-event\",\"operationId\":\"get-voice-call-event\",\"method\":\"GET\",\"path\":\"/api/phone/voice-call-events/{id}\",\"tags\":[\"Voice Call Events\"],\"summary\":\"Retrieve a voice call event\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-voice-call-event.md\",\"functionName\":\"gorgiasGetVoiceCallEvent\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-voice-call-recordings\",\"operationId\":\"list-voice-call-recordings\",\"method\":\"GET\",\"path\":\"/api/phone/voice-call-recordings\",\"tags\":[\"Voice Call Recordings\"],\"summary\":\"List voice call recordings\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-voice-call-recordings.md\",\"functionName\":\"gorgiasListVoiceCallRecordings\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-voice-call-recording\",\"operationId\":\"delete-voice-call-recording\",\"method\":\"DELETE\",\"path\":\"/api/phone/voice-call-recordings/{id}\",\"tags\":[\"Voice Call Recordings\"],\"summary\":\"Delete a voice call recording\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-voice-call-recording.md\",\"functionName\":\"gorgiasDeleteVoiceCallRecording\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-voice-call-recording\",\"operationId\":\"get-voice-call-recording\",\"method\":\"GET\",\"path\":\"/api/phone/voice-call-recordings/{id}\",\"tags\":[\"Voice Call Recordings\"],\"summary\":\"Retrieve a voice call recording\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-voice-call-recording.md\",\"functionName\":\"gorgiasGetVoiceCallRecording\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-voice-calls\",\"operationId\":\"list-voice-calls\",\"method\":\"GET\",\"path\":\"/api/phone/voice-calls\",\"tags\":[\"Voice Calls\"],\"summary\":\"List voice calls\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-voice-calls.md\",\"functionName\":\"gorgiasListVoiceCalls\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-voice-call\",\"operationId\":\"get-voice-call\",\"method\":\"GET\",\"path\":\"/api/phone/voice-calls/{id}\",\"tags\":[\"Voice Calls\"],\"summary\":\"Retrieve a voice call\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-voice-call.md\",\"functionName\":\"gorgiasGetVoiceCall\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-statistic\",\"operationId\":\"get-statistic\",\"method\":\"POST\",\"path\":\"/api/reporting/stats\",\"tags\":[\"Reporting Statistics\"],\"summary\":\"Retrieve a statistic\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-statistic.md\",\"functionName\":\"gorgiasGetStatistic\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-rules\",\"operationId\":\"list-rules\",\"method\":\"GET\",\"path\":\"/api/rules\",\"tags\":[\"Rules\"],\"summary\":\"List rules\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-rules.md\",\"functionName\":\"gorgiasListRules\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-rule\",\"operationId\":\"create-rule\",\"method\":\"POST\",\"path\":\"/api/rules\",\"tags\":[\"Rules\"],\"summary\":\"Create a rule\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-rule.md\",\"functionName\":\"gorgiasCreateRule\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-rule\",\"operationId\":\"delete-rule\",\"method\":\"DELETE\",\"path\":\"/api/rules/{id}\",\"tags\":[\"Rules\"],\"summary\":\"Delete a rule\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-rule.md\",\"functionName\":\"gorgiasDeleteRule\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-rule\",\"operationId\":\"get-rule\",\"method\":\"GET\",\"path\":\"/api/rules/{id}\",\"tags\":[\"Rules\"],\"summary\":\"Retrieve a rule\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-rule.md\",\"functionName\":\"gorgiasGetRule\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-rule\",\"operationId\":\"update-rule\",\"method\":\"PUT\",\"path\":\"/api/rules/{id}\",\"tags\":[\"Rules\"],\"summary\":\"Update a rule\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-rule.md\",\"functionName\":\"gorgiasUpdateRule\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-rules-priorities\",\"operationId\":\"update-rules-priorities\",\"method\":\"POST\",\"path\":\"/api/rules/priorities\",\"tags\":[\"Rules\"],\"summary\":\"Update rules' priorities\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-rules-priorities.md\",\"functionName\":\"gorgiasUpdateRulesPriorities\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-satisfaction-surveys\",\"operationId\":\"list-satisfaction-surveys\",\"method\":\"GET\",\"path\":\"/api/satisfaction-surveys\",\"tags\":[\"Satisfaction Surveys\"],\"summary\":\"List surveys\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-satisfaction-surveys.md\",\"functionName\":\"gorgiasListSatisfactionSurveys\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-satisfaction-survey\",\"operationId\":\"create-satisfaction-survey\",\"method\":\"POST\",\"path\":\"/api/satisfaction-surveys\",\"tags\":[\"Satisfaction Surveys\"],\"summary\":\"Create a survey\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-satisfaction-survey.md\",\"functionName\":\"gorgiasCreateSatisfactionSurvey\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-satisfaction-survey\",\"operationId\":\"get-satisfaction-survey\",\"method\":\"GET\",\"path\":\"/api/satisfaction-surveys/{id}\",\"tags\":[\"Satisfaction Surveys\"],\"summary\":\"Retrieve a survey\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-satisfaction-survey.md\",\"functionName\":\"gorgiasGetSatisfactionSurvey\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-satisfaction-survey\",\"operationId\":\"update-satisfaction-survey\",\"method\":\"PUT\",\"path\":\"/api/satisfaction-surveys/{id}\",\"tags\":[\"Satisfaction Surveys\"],\"summary\":\"Update a survey\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-satisfaction-survey.md\",\"functionName\":\"gorgiasUpdateSatisfactionSurvey\",\"implementationStatus\":\"generated-only\"},{\"id\":\"search\",\"operationId\":\"search\",\"method\":\"POST\",\"path\":\"/api/search\",\"tags\":[\"Search\"],\"summary\":\"Search for resources\",\"sourceUrl\":\"https://developers.gorgias.com/reference/search-1.md\",\"functionName\":\"gorgiasSearch\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-legacy-statistic\",\"operationId\":\"get-legacy-statistic\",\"method\":\"POST\",\"path\":\"/api/stats/{name}\",\"tags\":[\"Statistics\"],\"summary\":\"Retrieve a statistic\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-legacy-statistic.md\",\"functionName\":\"gorgiasGetLegacyStatistic\",\"implementationStatus\":\"generated-only\"},{\"id\":\"download-legacy-statistic\",\"operationId\":\"download-legacy-statistic\",\"method\":\"POST\",\"path\":\"/api/stats/{name}/download\",\"tags\":[\"Statistics\"],\"summary\":\"Download a statistic\",\"sourceUrl\":\"https://developers.gorgias.com/reference/download-legacy-statistic.md\",\"functionName\":\"gorgiasDownloadLegacyStatistic\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-tags\",\"operationId\":\"delete-tags\",\"method\":\"DELETE\",\"path\":\"/api/tags\",\"tags\":[\"Tags\"],\"summary\":\"Delete tags\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-tags.md\",\"functionName\":\"gorgiasDeleteTags\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-tags\",\"operationId\":\"list-tags\",\"method\":\"GET\",\"path\":\"/api/tags\",\"tags\":[\"Tags\"],\"summary\":\"List tags\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-tags.md\",\"functionName\":\"gorgiasListTags\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-tag\",\"operationId\":\"create-tag\",\"method\":\"POST\",\"path\":\"/api/tags\",\"tags\":[\"Tags\"],\"summary\":\"Create a tag\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-tag.md\",\"functionName\":\"gorgiasCreateTag\",\"implementationStatus\":\"generated-only\"},{\"id\":\"merge-tags\",\"operationId\":\"merge-tags\",\"method\":\"PUT\",\"path\":\"/api/tags/{destination_tag_id}/merge\",\"tags\":[\"Tags\"],\"summary\":\"Merge tags\",\"sourceUrl\":\"https://developers.gorgias.com/reference/merge-tags.md\",\"functionName\":\"gorgiasMergeTags\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-tag\",\"operationId\":\"delete-tag\",\"method\":\"DELETE\",\"path\":\"/api/tags/{id}\",\"tags\":[\"Tags\"],\"summary\":\"Delete a tag\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-tag.md\",\"functionName\":\"gorgiasDeleteTag\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-tag\",\"operationId\":\"get-tag\",\"method\":\"GET\",\"path\":\"/api/tags/{id}\",\"tags\":[\"Tags\"],\"summary\":\"Retrieve a tag\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-tag.md\",\"functionName\":\"gorgiasGetTag\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-tag\",\"operationId\":\"update-tag\",\"method\":\"PUT\",\"path\":\"/api/tags/{id}\",\"tags\":[\"Tags\"],\"summary\":\"Update a tag\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-tag.md\",\"functionName\":\"gorgiasUpdateTag\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-teams\",\"operationId\":\"list-teams\",\"method\":\"GET\",\"path\":\"/api/teams\",\"tags\":[\"Teams\"],\"summary\":\"List teams\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-teams.md\",\"functionName\":\"gorgiasListTeams\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-team\",\"operationId\":\"create-team\",\"method\":\"POST\",\"path\":\"/api/teams\",\"tags\":[\"Teams\"],\"summary\":\"Create a team\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-team.md\",\"functionName\":\"gorgiasCreateTeam\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-team\",\"operationId\":\"delete-team\",\"method\":\"DELETE\",\"path\":\"/api/teams/{id}\",\"tags\":[\"Teams\"],\"summary\":\"Delete a team\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-team.md\",\"functionName\":\"gorgiasDeleteTeam\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-team\",\"operationId\":\"get-team\",\"method\":\"GET\",\"path\":\"/api/teams/{id}\",\"tags\":[\"Teams\"],\"summary\":\"Retrieve a team\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-team.md\",\"functionName\":\"gorgiasGetTeam\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-team\",\"operationId\":\"update-team\",\"method\":\"PUT\",\"path\":\"/api/teams/{id}\",\"tags\":[\"Teams\"],\"summary\":\"Update a team\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-team.md\",\"functionName\":\"gorgiasUpdateTeam\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-tickets\",\"operationId\":\"list-tickets\",\"method\":\"GET\",\"path\":\"/api/tickets\",\"tags\":[\"Tickets\"],\"summary\":\"List tickets\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-tickets.md\",\"functionName\":\"gorgiasListTickets\",\"implementationStatus\":\"support-helper-and-generated\",\"implementedBy\":\"listTickets\"},{\"id\":\"create-ticket\",\"operationId\":\"create-ticket\",\"method\":\"POST\",\"path\":\"/api/tickets\",\"tags\":[\"Tickets\"],\"summary\":\"Create a ticket\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-ticket.md\",\"functionName\":\"gorgiasCreateTicket\",\"implementationStatus\":\"support-helper-and-generated\",\"implementedBy\":\"createTicket\"},{\"id\":\"delete-ticket\",\"operationId\":\"delete-ticket\",\"method\":\"DELETE\",\"path\":\"/api/tickets/{id}\",\"tags\":[\"Tickets\"],\"summary\":\"Delete a ticket\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-ticket.md\",\"functionName\":\"gorgiasDeleteTicket\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-ticket\",\"operationId\":\"get-ticket\",\"method\":\"GET\",\"path\":\"/api/tickets/{id}\",\"tags\":[\"Tickets\"],\"summary\":\"Retrieve a ticket\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-ticket.md\",\"functionName\":\"gorgiasGetTicket\",\"implementationStatus\":\"support-helper-and-generated\",\"implementedBy\":\"getTicket\"},{\"id\":\"update-ticket\",\"operationId\":\"update-ticket\",\"method\":\"PUT\",\"path\":\"/api/tickets/{id}\",\"tags\":[\"Tickets\"],\"summary\":\"Update a ticket\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-ticket.md\",\"functionName\":\"gorgiasUpdateTicket\",\"implementationStatus\":\"support-helper-and-generated\",\"implementedBy\":\"updateTicket\"},{\"id\":\"list-ticket-custom-fields\",\"operationId\":\"list-ticket-custom-fields\",\"method\":\"GET\",\"path\":\"/api/tickets/{ticket_id}/custom-fields\",\"tags\":[\"Tickets\"],\"summary\":\"List ticket field values\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-ticket-custom-fields.md\",\"functionName\":\"gorgiasListTicketCustomFields\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-ticket-custom-fields\",\"operationId\":\"update-ticket-custom-fields\",\"method\":\"PUT\",\"path\":\"/api/tickets/{ticket_id}/custom-fields\",\"tags\":[\"Tickets\"],\"summary\":\"Update ticket fields values\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-ticket-custom-fields.md\",\"functionName\":\"gorgiasUpdateTicketCustomFields\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-ticket-custom-field\",\"operationId\":\"delete-ticket-custom-field\",\"method\":\"DELETE\",\"path\":\"/api/tickets/{ticket_id}/custom-fields/{id}\",\"tags\":[\"Tickets\"],\"summary\":\"Delete ticket field value\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-ticket-custom-field.md\",\"functionName\":\"gorgiasDeleteTicketCustomField\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-ticket-custom-field\",\"operationId\":\"update-ticket-custom-field\",\"method\":\"PUT\",\"path\":\"/api/tickets/{ticket_id}/custom-fields/{id}\",\"tags\":[\"Tickets\"],\"summary\":\"Update ticket field value\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-ticket-custom-field.md\",\"functionName\":\"gorgiasUpdateTicketCustomField\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-ticket-messages\",\"operationId\":\"list-ticket-messages\",\"method\":\"GET\",\"path\":\"/api/tickets/{ticket_id}/messages\",\"tags\":[\"Ticket Messages\"],\"summary\":\"List messages of a ticket\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-ticket-messages.md\",\"functionName\":\"gorgiasListTicketMessages\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-ticket-message\",\"operationId\":\"create-ticket-message\",\"method\":\"POST\",\"path\":\"/api/tickets/{ticket_id}/messages\",\"tags\":[\"Ticket Messages\"],\"summary\":\"Create a message\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-ticket-message.md\",\"functionName\":\"gorgiasCreateTicketMessage\",\"implementationStatus\":\"support-helper-and-generated\",\"implementedBy\":\"createTicketMessage\"},{\"id\":\"delete-ticket-message\",\"operationId\":\"delete-ticket-message\",\"method\":\"DELETE\",\"path\":\"/api/tickets/{ticket_id}/messages/{id}\",\"tags\":[\"Ticket Messages\"],\"summary\":\"Delete a message\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-ticket-message.md\",\"functionName\":\"gorgiasDeleteTicketMessage\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-ticket-message\",\"operationId\":\"get-ticket-message\",\"method\":\"GET\",\"path\":\"/api/tickets/{ticket_id}/messages/{id}\",\"tags\":[\"Ticket Messages\"],\"summary\":\"Retrieve a message\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-ticket-message.md\",\"functionName\":\"gorgiasGetTicketMessage\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-ticket-message\",\"operationId\":\"update-ticket-message\",\"method\":\"PUT\",\"path\":\"/api/tickets/{ticket_id}/messages/{id}\",\"tags\":[\"Ticket Messages\"],\"summary\":\"Update a message\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-ticket-message.md\",\"functionName\":\"gorgiasUpdateTicketMessage\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-ticket-tags\",\"operationId\":\"delete-ticket-tags\",\"method\":\"DELETE\",\"path\":\"/api/tickets/{ticket_id}/tags\",\"tags\":[\"Tickets\"],\"summary\":\"Remove ticket tags\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-ticket-tags.md\",\"functionName\":\"gorgiasDeleteTicketTags\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-ticket-tags\",\"operationId\":\"list-ticket-tags\",\"method\":\"GET\",\"path\":\"/api/tickets/{ticket_id}/tags\",\"tags\":[\"Tickets\"],\"summary\":\"List ticket tags\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-ticket-tags.md\",\"functionName\":\"gorgiasListTicketTags\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-ticket-tags\",\"operationId\":\"create-ticket-tags\",\"method\":\"POST\",\"path\":\"/api/tickets/{ticket_id}/tags\",\"tags\":[\"Tickets\"],\"summary\":\"Add ticket tags\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-ticket-tags.md\",\"functionName\":\"gorgiasCreateTicketTags\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-ticket-tags\",\"operationId\":\"update-ticket-tags\",\"method\":\"PUT\",\"path\":\"/api/tickets/{ticket_id}/tags\",\"tags\":[\"Tickets\"],\"summary\":\"Set ticket tags\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-ticket-tags.md\",\"functionName\":\"gorgiasUpdateTicketTags\",\"implementationStatus\":\"generated-only\"},{\"id\":\"post_/api/upload\",\"operationId\":\"post_/api/upload\",\"method\":\"POST\",\"path\":\"/api/upload\",\"tags\":[\"Files\"],\"summary\":\"Upload files\",\"sourceUrl\":\"https://developers.gorgias.com/reference/post_api-upload.md\",\"functionName\":\"gorgiasPostApiUpload\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-users\",\"operationId\":\"list-users\",\"method\":\"GET\",\"path\":\"/api/users\",\"tags\":[\"Users\"],\"summary\":\"List users\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-users.md\",\"functionName\":\"gorgiasListUsers\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-user\",\"operationId\":\"create-user\",\"method\":\"POST\",\"path\":\"/api/users\",\"tags\":[\"Users\"],\"summary\":\"Create a user\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-user.md\",\"functionName\":\"gorgiasCreateUser\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-user\",\"operationId\":\"delete-user\",\"method\":\"DELETE\",\"path\":\"/api/users/{id}\",\"tags\":[\"Users\"],\"summary\":\"Delete a user\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-user.md\",\"functionName\":\"gorgiasDeleteUser\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-user\",\"operationId\":\"get-user\",\"method\":\"GET\",\"path\":\"/api/users/{id}\",\"tags\":[\"Users\"],\"summary\":\"Retrieve a user\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-user.md\",\"functionName\":\"gorgiasGetUser\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-user\",\"operationId\":\"update-user\",\"method\":\"PUT\",\"path\":\"/api/users/{id}\",\"tags\":[\"Users\"],\"summary\":\"Update a user\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-user.md\",\"functionName\":\"gorgiasUpdateUser\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-views\",\"operationId\":\"list-views\",\"method\":\"GET\",\"path\":\"/api/views\",\"tags\":[\"Views\"],\"summary\":\"List views\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-views.md\",\"functionName\":\"gorgiasListViews\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-view\",\"operationId\":\"create-view\",\"method\":\"POST\",\"path\":\"/api/views\",\"tags\":[\"Views\"],\"summary\":\"Create a view\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-view.md\",\"functionName\":\"gorgiasCreateView\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-view\",\"operationId\":\"delete-view\",\"method\":\"DELETE\",\"path\":\"/api/views/{id}\",\"tags\":[\"Views\"],\"summary\":\"Delete a view\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-view.md\",\"functionName\":\"gorgiasDeleteView\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-view\",\"operationId\":\"get-view\",\"method\":\"GET\",\"path\":\"/api/views/{id}\",\"tags\":[\"Views\"],\"summary\":\"Retrieve a view\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-view.md\",\"functionName\":\"gorgiasGetView\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-view\",\"operationId\":\"update-view\",\"method\":\"PUT\",\"path\":\"/api/views/{id}\",\"tags\":[\"Views\"],\"summary\":\"Update a view\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-view.md\",\"functionName\":\"gorgiasUpdateView\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-view-items\",\"operationId\":\"list-view-items\",\"method\":\"GET\",\"path\":\"/api/views/{view_id}/items\",\"tags\":[\"Views\"],\"summary\":\"List view's items\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-view-items.md\",\"functionName\":\"gorgiasListViewItems\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-view-items\",\"operationId\":\"update-view-items\",\"method\":\"PUT\",\"path\":\"/api/views/{view_id}/items\",\"tags\":[\"Views\"],\"summary\":\"Search for view's items\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-view-items.md\",\"functionName\":\"gorgiasUpdateViewItems\",\"implementationStatus\":\"generated-only\"},{\"id\":\"list-widgets\",\"operationId\":\"list-widgets\",\"method\":\"GET\",\"path\":\"/api/widgets\",\"tags\":[\"Widgets\"],\"summary\":\"List widgets\",\"sourceUrl\":\"https://developers.gorgias.com/reference/list-widgets.md\",\"functionName\":\"gorgiasListWidgets\",\"implementationStatus\":\"generated-only\"},{\"id\":\"create-widget\",\"operationId\":\"create-widget\",\"method\":\"POST\",\"path\":\"/api/widgets\",\"tags\":[\"Widgets\"],\"summary\":\"Create a widget\",\"sourceUrl\":\"https://developers.gorgias.com/reference/create-widget.md\",\"functionName\":\"gorgiasCreateWidget\",\"implementationStatus\":\"generated-only\"},{\"id\":\"delete-widget\",\"operationId\":\"delete-widget\",\"method\":\"DELETE\",\"path\":\"/api/widgets/{id}\",\"tags\":[\"Widgets\"],\"summary\":\"Delete a widget\",\"sourceUrl\":\"https://developers.gorgias.com/reference/delete-widget.md\",\"functionName\":\"gorgiasDeleteWidget\",\"implementationStatus\":\"generated-only\"},{\"id\":\"get-widget\",\"operationId\":\"get-widget\",\"method\":\"GET\",\"path\":\"/api/widgets/{id}\",\"tags\":[\"Widgets\"],\"summary\":\"Retrieve a widget\",\"sourceUrl\":\"https://developers.gorgias.com/reference/get-widget.md\",\"functionName\":\"gorgiasGetWidget\",\"implementationStatus\":\"generated-only\"},{\"id\":\"update-widget\",\"operationId\":\"update-widget\",\"method\":\"PUT\",\"path\":\"/api/widgets/{id}\",\"tags\":[\"Widgets\"],\"summary\":\"Update a widget\",\"sourceUrl\":\"https://developers.gorgias.com/reference/update-widget.md\",\"functionName\":\"gorgiasUpdateWidget\",\"implementationStatus\":\"generated-only\"}]") as readonly GorgiasFullApiOperation[];

// Hardened literal operation keys for generated SDK typing.
export const GORGIAS_FULL_API_OPERATION_IDS = [
  "download-file",
  "get-account",
  "list-account-settings",
  "create-account-setting",
  "update-account-setting",
  "list-custom-fields",
  "create-custom-field",
  "update-custom-fields",
  "get-custom-field",
  "update-custom-field",
  "delete-customers",
  "list-customers",
  "create-customer",
  "list-customer-custom-fields-values",
  "update-customer-custom-field-values",
  "delete-customer-custom-field-value",
  "update-customer-custom-field-value",
  "update-customer-data",
  "delete-customer",
  "get-customer",
  "update-customer",
  "merge-customers",
  "list-events",
  "get-event",
  "list-integrations",
  "create-integration",
  "delete-integration",
  "get-integration",
  "update-integration",
  "list-jobs",
  "create-job",
  "cancel-job",
  "get-job",
  "update-job",
  "list-macros",
  "create-macro",
  "delete-macro",
  "get-macro",
  "update-macro",
  "bulk-archive-macros",
  "bulk-unarchive-macros",
  "list-messages",
  "search-metric-cards",
  "get-metric-card",
  "list-voice-call-events",
  "get-voice-call-event",
  "list-voice-call-recordings",
  "delete-voice-call-recording",
  "get-voice-call-recording",
  "list-voice-calls",
  "get-voice-call",
  "get-statistic",
  "list-rules",
  "create-rule",
  "delete-rule",
  "get-rule",
  "update-rule",
  "update-rules-priorities",
  "list-satisfaction-surveys",
  "create-satisfaction-survey",
  "get-satisfaction-survey",
  "update-satisfaction-survey",
  "search",
  "get-legacy-statistic",
  "download-legacy-statistic",
  "delete-tags",
  "list-tags",
  "create-tag",
  "merge-tags",
  "delete-tag",
  "get-tag",
  "update-tag",
  "list-teams",
  "create-team",
  "delete-team",
  "get-team",
  "update-team",
  "list-tickets",
  "create-ticket",
  "delete-ticket",
  "get-ticket",
  "update-ticket",
  "list-ticket-custom-fields",
  "update-ticket-custom-fields",
  "delete-ticket-custom-field",
  "update-ticket-custom-field",
  "list-ticket-messages",
  "create-ticket-message",
  "delete-ticket-message",
  "get-ticket-message",
  "update-ticket-message",
  "delete-ticket-tags",
  "list-ticket-tags",
  "create-ticket-tags",
  "update-ticket-tags",
  "post_/api/upload",
  "list-users",
  "create-user",
  "delete-user",
  "get-user",
  "update-user",
  "list-views",
  "create-view",
  "delete-view",
  "get-view",
  "update-view",
  "list-view-items",
  "update-view-items",
  "list-widgets",
  "create-widget",
  "delete-widget",
  "get-widget",
  "update-widget"
] as const;
export const GORGIAS_FULL_API_OPERATION_OPERATION_IDS = [
  "download-file",
  "get-account",
  "list-account-settings",
  "create-account-setting",
  "update-account-setting",
  "list-custom-fields",
  "create-custom-field",
  "update-custom-fields",
  "get-custom-field",
  "update-custom-field",
  "delete-customers",
  "list-customers",
  "create-customer",
  "list-customer-custom-fields-values",
  "update-customer-custom-field-values",
  "delete-customer-custom-field-value",
  "update-customer-custom-field-value",
  "update-customer-data",
  "delete-customer",
  "get-customer",
  "update-customer",
  "merge-customers",
  "list-events",
  "get-event",
  "list-integrations",
  "create-integration",
  "delete-integration",
  "get-integration",
  "update-integration",
  "list-jobs",
  "create-job",
  "cancel-job",
  "get-job",
  "update-job",
  "list-macros",
  "create-macro",
  "delete-macro",
  "get-macro",
  "update-macro",
  "bulk-archive-macros",
  "bulk-unarchive-macros",
  "list-messages",
  "search-metric-cards",
  "get-metric-card",
  "list-voice-call-events",
  "get-voice-call-event",
  "list-voice-call-recordings",
  "delete-voice-call-recording",
  "get-voice-call-recording",
  "list-voice-calls",
  "get-voice-call",
  "get-statistic",
  "list-rules",
  "create-rule",
  "delete-rule",
  "get-rule",
  "update-rule",
  "update-rules-priorities",
  "list-satisfaction-surveys",
  "create-satisfaction-survey",
  "get-satisfaction-survey",
  "update-satisfaction-survey",
  "search",
  "get-legacy-statistic",
  "download-legacy-statistic",
  "delete-tags",
  "list-tags",
  "create-tag",
  "merge-tags",
  "delete-tag",
  "get-tag",
  "update-tag",
  "list-teams",
  "create-team",
  "delete-team",
  "get-team",
  "update-team",
  "list-tickets",
  "create-ticket",
  "delete-ticket",
  "get-ticket",
  "update-ticket",
  "list-ticket-custom-fields",
  "update-ticket-custom-fields",
  "delete-ticket-custom-field",
  "update-ticket-custom-field",
  "list-ticket-messages",
  "create-ticket-message",
  "delete-ticket-message",
  "get-ticket-message",
  "update-ticket-message",
  "delete-ticket-tags",
  "list-ticket-tags",
  "create-ticket-tags",
  "update-ticket-tags",
  "post_/api/upload",
  "list-users",
  "create-user",
  "delete-user",
  "get-user",
  "update-user",
  "list-views",
  "create-view",
  "delete-view",
  "get-view",
  "update-view",
  "list-view-items",
  "update-view-items",
  "list-widgets",
  "create-widget",
  "delete-widget",
  "get-widget",
  "update-widget"
] as const;
// End hardened literal operation keys.

export type GorgiasFullApiOperationId = typeof GORGIAS_FULL_API_OPERATION_OPERATION_IDS[number];

export const GORGIAS_FULL_API_OPERATION_BY_ID = new Map<string, GorgiasFullApiOperation>(
  GORGIAS_FULL_API_OPERATIONS.map((operation) => [operation.id, operation]),
);
