import { defineIntegrationProviderPackage } from "@cognidesk/integration-kit";
import {
  RCS_HOST_CLIENT_METADATA,
  RCS_SELECTED_OPERATION_COUNT,
} from "./selected-operations.js";

export const rcsMessagingProviderManifest = defineIntegrationProviderPackage({
  id: "messaging.rcs",
  name: "Google RCS for Business",
  packageName: "@cognidesk/integration-messaging-rcs",
  provider: "rcs",
  category: "messaging",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Runtime coverage uses the official @google/rcsbusinessmessaging SDK for selected RCS for Business support workflows: agentMessages text/media/card sends, agent events, phone capability checks, and file create/upload helpers.",
      "Agent readiness, launch, and verification coverage is read-only via the Business Communications REST API because @google/rcsbusinessmessaging does not expose the brands.agents API.",
      "This package accepts accessToken, tokenProvider, serviceAccount, baseUrl, messagingApiBaseUrl, and managementApiBaseUrl options; hosts may still provide an injected provider client backed by an approved SDK or runtime.",
      "This is not full RCS for Business API coverage; brand/agent lifecycle management, launch and verification mutation workflows, tester management, integrations, analytics, user batch APIs, Dialogflow messages, revoke/delete breadth, and broader event catalogs remain outside this adapter.",
    ],
    evidence: [
      { label: "RCS agentMessages create", url: "https://developers.google.com/business-communications/rcs-business-messaging/reference/rest/v1/phones.agentMessages/create" },
      { label: "RCS agentEvents create", url: "https://developers.google.com/business-communications/rcs-business-messaging/reference/rest/v1/phones.agentEvents/create" },
      { label: "RCS webhooks", url: "https://developers.google.com/business-communications/rcs-business-messaging/guides/integrate/webhooks" },
      { label: "RCS files create", url: "https://developers.google.com/business-communications/rcs-business-messaging/reference/rest/v1/files/create" },
      { label: "RCS agent launch read", url: "https://developers.google.com/business-communications/rcs-business-messaging/reference/business-communications/rest/v1/brands.agents/getLaunch" },
      { label: "RCS agent verification read", url: "https://developers.google.com/business-communications/rcs-business-messaging/reference/business-communications/rest/v1/brands.agents/getVerification" },
    ],
  },
  credentialRequirements: [
    {
      id: "rcs-agent",
      label: "RCS for Business agent identity",
      description: "SDK-user-owned RBM agentId and, for management checks, brands/*/agents/* resource name.",
      required: true,
    },
    {
      id: "rcs-provider-client",
      label: "RCS provider transport",
      description: "Built-in Google RCS SDK/Business Communications REST credentials or host-owned RcsMessagingProviderClient that encapsulates Google SDK/provider transport, token refresh, retries, and regional endpoint configuration.",
      scopes: [
        "https://www.googleapis.com/auth/rcsbusinessmessaging",
        "https://www.googleapis.com/auth/businesscommunications",
      ],
      required: true,
      metadata: {
        scopeKind: "provider-oauth-scopes",
        injectionInterface: "RcsMessagingProviderClient",
        credentialOwnership: "sdk-user-or-host-managed",
        defaultClientPolicy: "provider-rest-adapter-when-configured",
      },
    },
    {
      id: "rcs-webhook-client-token",
      label: "RCS webhook client token",
      description: "Client token configured in the RCS for Business Developer Console and used for X-Goog-Signature validation.",
      required: true,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive RCS webhooks",
      description: "Validates and parses RCS for Business webhook messages, delivery receipts, and user events.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "rcsUserMessage", label: "RCS User Message" },
        { kind: "rcsUserEvent", label: "RCS User Event" },
        { kind: "rcsPlatformEvent", label: "RCS Platform Event" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send RCS messages",
      description: "Sends text, rich-card, and media messages through RCS Business Messaging agentMessages.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "rcsAgentMessage", label: "RCS Agent Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Build RCS message payloads",
      description: "Builds RBM-compatible message request payloads for SDK-user-owned approval and policy workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "rcsMessageDraft", label: "RCS Message Draft" }],
      requiresCredential: false,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "Send RCS media",
      description: "References uploaded RCS files or externally hosted media URLs in outbound messages and rich cards.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "rcsMedia", label: "RCS Media" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read RCS agent readiness",
      description: "Reads RBM agent, launch, verification, and phone capability resources for Studio-visible readiness.",
      audiences: ["internal-support"],
      providerObjects: [
        { kind: "rcsAgent", label: "RCS Agent" },
        { kind: "rcsAgentLaunch", label: "RCS Agent Launch" },
        { kind: "rcsAgentVerification", label: "RCS Agent Verification" },
        { kind: "rcsCapabilities", label: "RCS Phone Capabilities" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "rcs.agent-events",
      label: "Send RCS read and typing events",
      description: "Sends READ receipts and IS_TYPING indicators when the RBM API and recipient support them.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "rcsAgentEvent", label: "RCS Agent Event" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      extension: true,
    },
    {
      capability: "rcs.webhook-signature",
      label: "Validate RCS webhook signatures",
      description: "Validates X-Goog-Signature over the decoded webhook message body with the SDK user's client token.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "rcsSignedWebhook", label: "RCS Signed Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "RCS messages, phone numbers, media metadata, suggested replies/actions, delivery receipts, subscription events, and webhook payloads can contain customer data.",
    "OAuth tokens, Google credential material, SDK clients, webhook client tokens, and shared secrets stay server-side and are represented in Studio only as credential/provider transport readiness.",
    "Unsubscribe, resubscribe, STOP/START fallback handling, outbound-contact policy, consent, fallback routing, retention, and deletion are SDK-user-owned responsibilities.",
  ],
  limitations: [
    "RCS for Business access, agent creation, brand verification, carrier launch, tester setup, webhook configuration, and production throughput require the SDK user's Google RBM partner or provider approval.",
    "Recipient reachability and feature support depend on the user's device, carrier, region, agent launch state, tester status, and capability checks; unsupported recipients or features may return NOT_FOUND or INVALID_ARGUMENT.",
    "Host applications may inject an RcsMessagingProviderClient backed by an approved SDK, provider package, or host-owned transport.",
    "The built-in Google RCS SDK/Business Communications REST adapter requires accessToken, tokenProvider, serviceAccount, or providerClient plus agent identifiers; API key-only transport is rejected because Google RCS for Business documents service-account/OAuth authentication for RBM APIs.",
    "Media upload behavior is delegated to the host provider client; callers must satisfy Google-hosted/external media, file-size, caching, and approval requirements for their deployment.",
  ],
  metadata: {
    channelCoverage: {
      agentMessages: "typed-send-text-media-card",
      agentEvents: "typed-send",
      files: "typed-create-upload",
      phoneCapabilities: "typed-read",
      agentReadiness: "typed-read",
      launchVerification: "typed-read",
      webhooks: "typed-challenge-verify-parse",
      brandAgentLifecycle: "provider-supported-not-typed",
    },
    apiCoverage: {
      ...RCS_HOST_CLIENT_METADATA.apiCoverage,
      generatedFromOfficialSpec: false,
      machineReadableSpecStatus: "Google documents Discovery URLs for rcsbusinessmessaging.v1 and businesscommunications.v1, but anonymous fetches returned 403 during this audit.",
      documentedOperationCount: 38,
      selectedOperationCount: RCS_SELECTED_OPERATION_COUNT,
      implementedOperationCount: RCS_SELECTED_OPERATION_COUNT,
      fullProviderApi: false,
    },
    implementationStrategy: "provider-sdk-hybrid",
    implementation: {
      ...RCS_HOST_CLIENT_METADATA,
      providerClientInterface: "RcsMessagingProviderClient",
      defaultProviderSdk: "@google/rcsbusinessmessaging",
      defaultHttpClient: "providerJsonRequest",
      defaultFetchClient: "businesscommunications-rest-adapter",
      failClosedWithoutProviderClient: false,
      failClosedWithoutCredentialedTransport: true,
      acceptedAuthModes: ["accessToken", "tokenProvider", "serviceAccount", "providerClient"],
      rejectedAuthModes: ["apiKey-only"],
      manifestImport: "no-client-initialization",
    },
    providerClient: {
      interface: "RcsMessagingProviderClient",
      injectionPolicy: "override-supported",
      importPolicy: "provider-client-override-supported",
      defaultClient: "google-rcsbusinessmessaging-sdk-when-configured",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
