import { defineIntegrationProviderPackage, type ProviderManifestInput } from "@cognidesk/integration-kit";

export const appStoreConnectReviewedOperationAllowlist = [
  {
    method: "GET",
    path: "/v1/apps/{id}/customerReviews",
    aliases: ["appstore.reviews.list"],
    clientMethods: ["listReviews"],
  },
  {
    method: "GET",
    path: "/v1/apps/{id}/customerReviews",
    aliases: ["appstore.reviews.page"],
    clientMethods: ["listReviewsPage"],
    source: "links.next for the configured app customerReviews collection",
  },
  {
    method: "GET",
    path: "/v1/customerReviews/{id}",
    aliases: ["appstore.reviews.get"],
    clientMethods: ["getReview"],
  },
  {
    method: "POST",
    path: "/v1/customerReviewResponses",
    aliases: ["appstore.reviewResponses.createOrUpdate"],
    clientMethods: ["createOrUpdateReviewResponse"],
  },
  {
    method: "DELETE",
    path: "/v1/customerReviewResponses/{id}",
    aliases: ["appstore.reviewResponses.delete"],
    clientMethods: ["deleteReviewResponse"],
  },
  {
    method: "GET",
    path: "/v1/apps/{id}",
    aliases: [],
    clientMethods: ["getApp", "rawClient.request"],
    purpose: "configured app check and reviewed raw-client escape hatch",
  },
] as const;

export const appStoreReviewsProviderManifestInput = {
  id: "review.appstore",
  name: "App Store Reviews",
  packageName: "@cognidesk/integration-review-appstore",
  provider: "appstore",
  category: "review",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Cognidesk adapter coverage is scoped to App Store Connect customer review list/read/response workflows.",
      "No official Apple JavaScript or TypeScript SDK for App Store Connect customer reviews was found on 2026-06-21; this package uses a constrained direct REST support slice with ES256 JWT auth.",
      "Apple's official @apple/app-store-server-library Node package targets App Store Server APIs, not App Store Connect customer review resources.",
    ],
    evidence: [
      { label: "App Store Connect API overview", url: "https://developer.apple.com/documentation/appstoreconnectapi" },
      {
        label: "App Store Connect OpenAPI specification (openapi.oas.json sha256:352ccca83f6460761bc513b87ed667974afb1347649d49b7cd98cd9041236bec)",
        url: "https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip",
      },
      { label: "App Store Connect JWT tokens", url: "https://developer.apple.com/documentation/appstoreconnectapi/generating-tokens-for-api-requests" },
      { label: "Apple App Store Server Node.js Library", url: "https://github.com/apple/app-store-server-library-node" },
    ],
  },
  credentialRequirements: [
    {
      id: "appstore-api-key",
      label: "App Store Connect API key",
      description: "Issuer ID, key ID, and private key used to mint ES256 JWTs for App Store Connect API calls.",
      required: true,
    },
    {
      id: "appstore-app-id",
      label: "App Store Connect app ID",
      description: "App Store Connect app resource ID whose customer reviews are visible to the SDK user.",
      required: true,
    },
    {
      id: "appstore-review-response-policy",
      label: "Review response policy",
      description: "SDK-user policy controlling which review replies may be drafted, published, updated, or removed.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Read App Store reviews",
      description: "Reads App Store Connect customer reviews as support signals for SDK-user-configured review workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "appStoreCustomerReview", label: "App Store Customer Review" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Draft review responses",
      description: "Builds App Store review response payloads for SDK-user approval workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "appStoreReviewResponseDraft", label: "App Store Review Response Draft" }],
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Publish review responses",
      description: "Creates or updates App Store Connect customer review responses when SDK-user policy allows public replies.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "appStoreCustomerReviewResponse", label: "App Store Customer Review Response" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read review records",
      description: "Reads App Store review details, included relationships, and existing response resources.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "appStoreCustomerReview", label: "App Store Customer Review" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "List and filter reviews",
      description: "Lists App Store reviews with SDK-user-selected filters, includes, pagination, sorting, and locale constraints.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "appStoreCustomerReview", label: "App Store Customer Review" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "delete-provider-object",
      label: "Delete review responses",
      description: "Deletes existing App Store customer review responses according to SDK-user approval policy.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "appStoreCustomerReviewResponse", label: "App Store Customer Review Response" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  operations: [
    {
      alias: "appstore.reviews.list",
      capability: "search-provider-object",
      label: "List App Store reviews",
      providerObject: "appStoreCustomerReview",
      providerOperation: "GET /v1/apps/{id}/customerReviews",
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "appstore.reviews.page",
      capability: "search-provider-object",
      label: "Follow App Store review page",
      providerObject: "appStoreCustomerReview",
      providerOperation: "links.next for /v1/apps/{id}/customerReviews",
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "appstore.reviews.get",
      capability: "read-provider-object",
      label: "Get App Store review",
      providerObject: "appStoreCustomerReview",
      providerOperation: "GET /v1/customerReviews/{id}",
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "appstore.reviewResponses.createOrUpdate",
      capability: "send",
      label: "Create or update App Store review response",
      providerObject: "appStoreCustomerReviewResponse",
      providerOperation: "POST /v1/customerReviewResponses",
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "appstore.reviewResponses.delete",
      capability: "delete-provider-object",
      label: "Delete App Store review response",
      providerObject: "appStoreCustomerReviewResponse",
      providerOperation: "DELETE /v1/customerReviewResponses/{id}",
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
  ],
  privacyNotes: [
    "App Store review text, ratings, reviewer nicknames, territories, app versions, and public response text can contain customer data.",
    "App Store Connect private keys stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "The SDK user decides review triage, sentiment classification, public-response approval, localization, escalation, and retention policy.",
    "Customer review listing is paged by App Store Connect response links; callers should follow `links.next` through the bounded `listReviewsPage` helper.",
    "Creating a customer review response uses Apple's create-or-update endpoint; SDK-user policy must treat the first public reply and later edits as externally visible actions.",
    "App Store Connect API availability, rate limits, review visibility, and response moderation are controlled by Apple and the SDK user's account permissions.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    implementation: {
      strategy: "direct-http-support-slice",
      officialJsSdkAvailable: false,
      verifiedAt: "2026-06-21",
      runtimePackage: "@cognidesk/integration-review-appstore/runtime",
      rawClientExport: "AppStoreReviewsClient.rawClient.request",
    },
    reviewedSource: {
      source: "Apple App Store Connect OpenAPI specification",
      sourceUrl: "https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip",
      version: "4.4",
      artifact: "openapi.oas.json",
      checksum: "sha256:352ccca83f6460761bc513b87ed667974afb1347649d49b7cd98cd9041236bec",
      archiveChecksum: "sha256:18d2e448db9ebac9f6fb183e786342f67dfaa0c515995d782694a776e26c2dfd",
      reviewedAt: "2026-06-21",
      operationAllowlist: appStoreConnectReviewedOperationAllowlist,
      selectedOperations: [
        "GET /v1/apps/{id}/customerReviews",
        "GET /v1/customerReviews/{id}",
        "POST /v1/customerReviewResponses",
        "DELETE /v1/customerReviewResponses/{id}",
        "GET /v1/apps/{id}",
      ],
    },
    adapterCoverage: {
      normalizedOperations: [
        "appstore.reviews.list",
        "appstore.reviews.page",
        "appstore.reviews.get",
        "appstore.reviewResponses.createOrUpdate",
        "appstore.reviewResponses.delete",
      ],
    },
  },
} as const;

export const appStoreReviewsProviderManifest = defineIntegrationProviderPackage(
  appStoreReviewsProviderManifestInput as unknown as ProviderManifestInput,
);
