import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";

export const sipVoiceProviderManifest = defineProviderPackage({
  id: "voice.sip",
  name: "Generic SIP Voice Connection",
  packageName: "@cognidesk/integrations",
  provider: "sip",
  category: "voice",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "local-protocol",
    notes: [
      "Defines a Cognidesk SIP stack gateway contract and callback normalizer for SDK-user-owned SIP/SBC/BYOC infrastructure.",
      "Does not implement a SIP transaction/dialog stack, registrar, SBC, RTP/SRTP media engine, or any specific provider's SIP/Voice REST API.",
      "Provider-specific SIP registration, INVITE/REFER/re-INVITE execution, media anchoring, recording, transcription, routing, consent, and retention remain SDK-user/provider gateway responsibilities.",
    ],
    evidence: [],
  },
  credentialRequirements: [
    {
      id: "sip-registrar",
      label: "SIP registrar",
      description: "Registrar URI used by the SDK user's SIP stack to register or authenticate the endpoint.",
      required: true,
    },
    {
      id: "sip-proxy",
      label: "SIP proxy",
      description: "Outbound proxy URI or SBC target used for INVITE, transfer, and call-control signaling.",
      required: false,
    },
    {
      id: "sip-domain",
      label: "SIP domain",
      description: "SIP realm/domain used to construct and validate address-of-record values.",
      required: true,
    },
    {
      id: "sip-auth",
      label: "SIP authentication",
      description: "Auth username and password/secret supplied to the SDK user's chosen SIP stack.",
      required: true,
    },
    {
      id: "sip-tls",
      label: "SIP over TLS",
      description: "TLS must be enabled when the deployment requires encrypted SIP signaling.",
      required: true,
    },
    {
      id: "sip-srtp",
      label: "SRTP media",
      description: "SRTP must be enabled when the deployment requires encrypted RTP media.",
      required: true,
    },
    {
      id: "sip-webhook-callback",
      label: "SIP event callback",
      description: "Public callback URL plus shared-secret or HMAC validation for call, transfer, recording, and transcription events.",
      required: true,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive SIP calls",
      description: "Accepts inbound SIP call events bridged from the SDK user's SIP stack into Cognidesk voice handling.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "sipCall", label: "SIP Call" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Place SIP calls",
      description: "Defines outbound INVITE contracts for BYOC SIP providers and SDK-user-owned SIP stacks.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "sipInvite", label: "SIP INVITE" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "SDP media negotiation",
      description: "Carries SDP offer/answer data and TLS/SRTP readiness metadata for the SDK user's SIP/RTP bridge.",
      audiences: ["customer-facing"],
      providerObjects: [
        { kind: "sipDialog", label: "SIP Dialog" },
        { kind: "sdpSessionDescription", label: "SDP Session Description" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "transfer",
      label: "SIP call transfer",
      description: "Exposes REFER/re-INVITE style transfer contracts while leaving transfer policy to SDK configuration.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "sipTransfer", label: "SIP Transfer" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      capability: "recording",
      label: "Recording callbacks",
      description: "Normalizes recording lifecycle callbacks emitted by the SDK user's SIP media stack.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "sipRecording", label: "SIP Recording" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "transcription",
      label: "Transcription callbacks",
      description: "Normalizes transcription callbacks emitted by the SDK user's SIP media or ASR stack.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "sipTranscription", label: "SIP Transcription" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "sip.webhook-signature",
      label: "Validate SIP callbacks",
      description: "Validates configurable shared-secret and HMAC headers before parsing generic SIP callback payloads.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "sipWebhook", label: "SIP Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "SIP addresses, call metadata, SDP media descriptions, recordings, and transcripts can contain personal data.",
    "This package does not implement a SIP stack or expose SIP credentials to browsers; SDK users supply and operate the SIP/SBC bridge.",
  ],
  limitations: [
    "A full SIP transaction/dialog stack is intentionally out of scope for this package.",
    "SDK users must bridge these contracts to their chosen SIP stack, SBC, PBX, or BYOC voice provider.",
    "Conversation routing, consent, recording policy, retention, and handoff remain SDK-user configuration.",
  ],
  metadata: {
    bridgeContract: "sip-stack-gateway",
    secureMedia: ["tls", "srtp"],
    webhookEvents: ["call.status", "call.transfer", "recording", "transcription"],
    channelCoverage: {
      sipGatewayContract: "sdk-owned-local-protocol",
      inboundInviteEvents: "sdk-owned-bridge-contract",
      outboundInvite: "sdk-owned-bridge-contract",
      sdpMedia: "sdk-owned-bridge-contract",
      transfer: "sdk-owned-bridge-contract",
      recordingCallbacks: "sdk-owned-bridge-contract",
      transcriptionCallbacks: "sdk-owned-bridge-contract",
      sipStack: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
