import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const PEGA_CUSTOMER_SERVICE_DEFAULT_API_BASE_PATH = "/api/v1";

export const pegaCustomerServiceSupportOperationAllowlist = [
  { alias: "ticket.create", method: "POST", path: "{apiBasePath}/cases" },
  { alias: "ticket.read", method: "GET", path: "{apiBasePath}/cases/{ID}" },
  { alias: "ticket.update", method: "PUT", path: "{apiBasePath}/cases/{ID}" },
  { alias: "ticket.search", method: "GET", path: "{apiBasePath}/cases" },
  { alias: "pega-customer-service.caseTypes.list", method: "GET", path: "{apiBasePath}/casetypes" },
  {
    alias: "pega-customer-service.assignmentAction.submit",
    method: "PATCH",
    path: "{apiBasePath}/assignments/{assignmentID}/actions/{actionID}",
  },
] as const;

export const pegaCustomerServiceTicketingProviderManifest = defineProviderPackage({
  id: "ticketing.pega-customer-service",
  name: "Pega Customer Service",
  packageName: "@cognidesk/integration-ticketing-pega-customer-service",
  provider: "pega-customer-service",
  category: "ticketing",
  trustLevel: "official",
  directions: ["bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Coverage is typed for Pega DX API case creation, case read/update, case search/listing, case-type listing, assignment action submission, and readiness checks used by Cognidesk support workflows.",
      "This is not full Pega Customer Service or Pega Platform API coverage; broader assignments/actions lifecycle, stages/process navigation, attachments, data views/pages, bulk actions, views, refresh/validation flows, security rules, and broader application administration remain outside this adapter.",
    ],
    evidence: [
      { label: "Pega DX API overview", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/dx-api-overview.html" },
      { label: "Pega DX API cases endpoints", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/managing-cases-dx-api.html" },
      { label: "Pega DX API POST /cases", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-post-cases.html" },
      { label: "Pega DX API GET /cases", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-get-cases.html" },
      { label: "Pega DX API GET /cases/{ID}", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-get-cases-id.html" },
      { label: "Pega DX API PUT /cases/{ID}", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-put-cases-id.html" },
      { label: "Pega DX API GET /casetypes", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-get-casetypes_0.html" },
      { label: "Pega DX API PATCH /assignments/{assignmentID}/actions/{actionID}", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-patch-assignments-assignmentid-actions-actionid.html" },
    ],
  },
  credentialRequirements: [
    {
      id: "pega-customer-service-instance",
      label: "Pega Customer Service instance URL",
      description: "The SDK user's Pega Platform or Pega Customer Service application URL.",
      required: true,
    },
    {
      id: "pega-customer-service-api-access",
      label: "Pega DX API access",
      description: "Server-side OAuth bearer access or Basic Auth credentials for Pega DX API endpoints with operator/client privileges for cases, case types, and assignment actions.",
      scopes: ["cases:read", "cases:write", "casetypes:read"],
      required: true,
      metadata: {
        scopeKind: "internal-capability-labels",
        privilegeGuidance: "These strings are Cognidesk capability labels, not proven official Pega OAuth scopes. Pega access depends on the operator/client access group and privileges for case list/read/create/update, case type read, and assignment action submission.",
      },
    },
  ],
  capabilities: [
    {
      capability: "create-provider-object",
      label: "Create Pega cases",
      description: "Creates Pega Customer Service cases with the Pega DX API from SDK-user-selected workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "pegaCase", label: "Pega Case", schemaName: "Pega-API-CaseManagement-Case" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Pega cases",
      description: "Reads Pega cases and case type metadata through the Pega DX API.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "pegaCase", label: "Pega Case", schemaName: "Pega-API-CaseManagement-Case" },
        { kind: "pegaCaseType", label: "Pega Case Type", schemaName: "Pega-API-CaseManagement-CaseType" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Pega cases",
      description: "Updates Pega cases with SDK-user-supplied case data through the Pega DX API.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "pegaCase", label: "Pega Case", schemaName: "Pega-API-CaseManagement-Case" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Pega cases",
      description: "Queries Pega cases with SDK-user-supplied case type, status, assignment, and pagination controls.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "pegaCase", label: "Pega Case", schemaName: "Pega-API-CaseManagement-Case" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Run Pega case handoff action",
      description: "Submits SDK-user-configured Pega DX assignment actions or case operations for human handoff workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "pegaCase", label: "Pega Case", schemaName: "Pega-API-CaseManagement-Case" },
        { kind: "pegaAssignmentAction", label: "Pega Assignment Action", schemaName: "Pega-API-CaseManagement-AssignmentAction" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  operations: [
    {
      alias: "ticket.create",
      capability: "create-provider-object",
      providerObject: "pegaCase",
      audiences: ["customer-facing", "internal-support", "mixed"],
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.read",
      capability: "read-provider-object",
      providerObject: "pegaCase",
      audiences: ["customer-facing", "internal-support", "mixed"],
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.update",
      capability: "update-provider-object",
      providerObject: "pegaCase",
      audiences: ["internal-support", "mixed"],
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.search",
      capability: "search-provider-object",
      providerObject: "pegaCase",
      audiences: ["customer-facing", "internal-support", "mixed"],
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "pega-customer-service.caseTypes.list",
      capability: "read-provider-object",
      providerObject: "pegaCaseType",
      audiences: ["internal-support", "mixed"],
      extension: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "pega-customer-service.assignmentAction.submit",
      capability: "handoff",
      providerObject: "pegaAssignmentAction",
      audiences: ["internal-support", "mixed"],
      extension: true,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
  ],
  privacyNotes: [
    "Pega cases can contain customer identity, interaction details, assignments, statuses, case data, attachments metadata, and internal workflow context.",
    "Pega API credentials stay server-side and Studio receives only readiness and scope status.",
  ],
  limitations: [
    "Case types, starting processes, field requirements, assignment routing, security rules, data pages, and stage transitions are owned by the SDK user's Pega application.",
    "SDK users own case-type selection, field mapping, handoff timing, customer identity matching, notification policy, and retention before calling Pega APIs.",
  ],
  metadata: {
    implementation: {
      strategy: "direct-http-support-slice",
    },
    implementationStrategy: {
      strategy: "direct-support-slice",
      reason: "No suitable maintained server-side JavaScript SDK was found for Pega Customer Service/DX API case operations; current Pega JavaScript packages are Constellation UI/client orchestration assets.",
      checkedAt: "2026-06-21",
      rejectedLibraries: [
        {
          packageName: "@pega/constellationjs",
          version: "25.1.3",
          integrity: "sha512-dPPo+e/ADjMwabHfQ5s9DX2P8IeJiSg6NPXFRLFkFZm1OFbkDevf3YoSpf5/XzWD3IqcBo0dx8NzV7tLjp4EJw==",
          reason: "Pega-maintained package, but it provides ConstellationJS engine files rather than a server-side DX API case client.",
        },
      ],
    },
    supportOperationSlice: {
      sourceKind: "official-docs-reviewed-slice",
      sourceVersion: PEGA_CUSTOMER_SERVICE_DEFAULT_API_BASE_PATH,
      checkedAt: "2026-06-21",
      allowlistSha256: "6b4e3eb1f0a9b371002d8a3be22827c473680c7ce1335a0faf9d990e94cd32fd",
      operations: pegaCustomerServiceSupportOperationAllowlist,
    },
    checkedProviderApiCoverage: {
      verifiedAt: "2026-06-18",
      sourceKind: "checked-endpoint-family-inventory",
      coverageArtifact: "docs/provider-coverage/pega-customer-service-checked-dx-api-2026-06-18.inventory.json",
      checkedFamilyCount: 4,
      implementedFamilyCount: 3,
      gapFamilyCount: 1,
      implementedOperationCount: 6,
    },
    channelCoverage: {
      cases: "typed-create-read-update-search",
      assignmentActions: "typed-submit",
      caseTypes: "typed-list",
      readiness: "typed-list",
      attachmentsDataPages: "provider-supported-not-typed",
      stageLifecycleActions: "provider-supported-not-typed",
      broaderCaseManagementAdmin: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
