import {
  defineIntegrationProviderPackage as defineProviderPackage,
  type ProviderManifestInput,
} from "@cognidesk/integration-kit";

export const pegaCustomerServiceDelegatedOperationAllowlist = [
  { alias: "ticket.create", providerClientMethod: "createCase" },
  { alias: "ticket.read", providerClientMethod: "getCase" },
  { alias: "ticket.update", providerClientMethod: "updateCase" },
  { alias: "ticket.search", providerClientMethod: "searchCases" },
  { alias: "pega-customer-service.caseTypes.list", providerClientMethod: "listCaseTypes" },
  { alias: "pega-customer-service.assignmentAction.submit", providerClientMethod: "performAssignmentAction" },
] as const;

export const pegaCustomerServiceTicketingProviderManifestInput = {
  id: "ticketing.pega-customer-service",
  name: "Pega Customer Service",
  packageName: "@cognidesk/integration-ticketing-pega-customer-service",
  provider: "pega-customer-service",
  category: "ticketing",
  trustLevel: "official",
  directions: ["bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      "Runtime coverage uses the built-in Pega DX REST adapter when baseUrl plus access credentials are provided; a host-injected PegaCustomerServiceProviderClient remains available as an override.",
      "Coverage is typed for Pega Customer Service case creation, case read/update, case search/listing, case-type listing, assignment action submission, and readiness checks used by Cognidesk support workflows.",
      "This is not full Pega Customer Service or Pega Platform API coverage; broader assignments/actions lifecycle, stages/process navigation, attachments, data views/pages, bulk actions, views, refresh/validation flows, security rules, and broader application administration remain outside this adapter.",
    ],
    evidence: [
      { label: "Pega DX API overview", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/dx-api-overview.html" },
      { label: "Pega DX API cases endpoints", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/managing-cases-dx-api.html" },
      { label: "Pega DX API POST /cases", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-post-cases.html" },
      { label: "Pega DX API GET /cases", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-get-cases.html" },
      { label: "Pega DX API GET /cases/{ID}", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-get-cases-id.html" },
      { label: "Pega DX API PUT /cases/{ID}", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-put-cases-id.html" },
      { label: "Pega DX API GET /casetypes", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-get-casetypes_0.html" },
      { label: "Pega DX API PATCH /assignments/{assignmentID}/actions/{actionID}", url: "https://docs.pega.com/bundle/dx-api/page/platform/dx-api/endpoint-patch-assignments-assignmentid-actions-actionid.html" },
      { label: "Pega React SDK", url: "https://github.com/pegasystems/react-sdk" },
      { label: "@pega/constellationjs package", url: "https://www.npmjs.com/package/@pega/constellationjs" },
      { label: "@pega/auth package", url: "https://www.npmjs.com/package/@pega/auth" },
    ],
  },
  credentialRequirements: [
    {
      id: "pega-customer-service-provider-client",
      label: "Optional Pega Customer Service provider client override",
      description: "Optional host runtime override implementing PegaCustomerServiceProviderClient. When omitted, the package uses its built-in Pega DX REST adapter.",
      required: false,
      metadata: {
        injectionInterface: "PegaCustomerServiceProviderClient",
        credentialOwnership: "host-managed-override",
        defaultHttpClient: "built-in-fetch",
        defaultFetchClient: "built-in-provider-rest-adapter",
        defaultClientPolicy: "built-in-dx-rest-adapter",
      },
    },
    {
      id: "pega-customer-service-instance",
      label: "Pega Customer Service base URL",
      description: "Pega application base URL used by the built-in DX REST adapter, or supplied by a host provider client override.",
      required: false,
      metadata: {
        requiredWhen: "built-in-dx-rest-adapter",
      },
    },
    {
      id: "pega-customer-service-api-access",
      label: "Pega Customer Service DX API access",
      description: "Server-side Pega DX API access supplied as accessToken, auth headers, or encapsulated in a host provider client override.",
      scopes: ["cases:read", "cases:write", "assignments:write"],
      required: false,
      metadata: {
        requiredWhen: "built-in-dx-rest-adapter",
        scopeKind: "internal-capability-labels",
        privilegeGuidance: "These strings are Cognidesk capability labels, not official Pega OAuth scope names. Pega access depends on application OAuth/client configuration, roles, privileges, and case security.",
      },
    },
  ],
  capabilities: [
    {
      capability: "create-provider-object",
      label: "Create Pega cases",
      description: "Creates Pega Customer Service cases through the built-in DX REST adapter or provider client override from SDK-user-selected workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "pegaCase", label: "Pega Case", schemaName: "Pega-API-CaseManagement-Case" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Pega cases",
      description: "Reads Pega cases and case type metadata through the built-in DX REST adapter or provider client override.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "pegaCase", label: "Pega Case", schemaName: "Pega-API-CaseManagement-Case" },
        { kind: "pegaCaseType", label: "Pega Case Type", schemaName: "Pega-API-CaseManagement-CaseType" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Pega cases",
      description: "Updates Pega cases with SDK-user-supplied case data through the built-in DX REST adapter or provider client override.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "pegaCase", label: "Pega Case", schemaName: "Pega-API-CaseManagement-Case" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Pega cases",
      description: "Queries Pega cases with SDK-user-supplied case type, status, assignment, and pagination controls.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "pegaCase", label: "Pega Case", schemaName: "Pega-API-CaseManagement-Case" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "handoff",
      label: "Run Pega case handoff action",
      description: "Submits SDK-user-configured Pega DX assignment actions or case operations for human handoff workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "pegaCase", label: "Pega Case", schemaName: "Pega-API-CaseManagement-Case" },
        { kind: "pegaAssignmentAction", label: "Pega Assignment Action", schemaName: "Pega-API-CaseManagement-AssignmentAction" },
      ],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  operations: [
    {
      alias: "ticket.create",
      capability: "create-provider-object",
      providerObject: "pegaCase",
      audiences: ["customer-facing", "internal-support", "mixed"],
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.read",
      capability: "read-provider-object",
      providerObject: "pegaCase",
      audiences: ["customer-facing", "internal-support", "mixed"],
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.update",
      capability: "update-provider-object",
      providerObject: "pegaCase",
      audiences: ["internal-support", "mixed"],
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "ticket.search",
      capability: "search-provider-object",
      providerObject: "pegaCase",
      audiences: ["customer-facing", "internal-support", "mixed"],
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "pega-customer-service.caseTypes.list",
      capability: "read-provider-object",
      providerObject: "pegaCaseType",
      audiences: ["internal-support", "mixed"],
      extension: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
    {
      alias: "pega-customer-service.assignmentAction.submit",
      capability: "handoff",
      providerObject: "pegaAssignmentAction",
      audiences: ["internal-support", "mixed"],
      extension: true,
      sideEffect: true,
      changesWorkflow: true,
      exposesSensitiveData: true,
      requiresCredential: true,
    },
  ],
  privacyNotes: [
    "Pega cases can contain customer identity, interaction details, assignments, statuses, case data, attachments metadata, and internal workflow context.",
    "Pega API credentials stay server-side and Studio receives only readiness and scope status.",
  ],
  limitations: [
    "The built-in adapter covers selected Pega DX case and assignment-action operations only; hosts can still inject a PegaCustomerServiceProviderClient for custom authentication, retries, or endpoint policy.",
    "Case types, starting processes, field requirements, assignment routing, security rules, data pages, and stage transitions are owned by the SDK user's Pega application and injected provider client.",
    "SDK users own case-type selection, field mapping, handoff timing, customer identity matching, notification policy, and retention before invoking Pega provider operations.",
  ],
  metadata: {
    implementation: {
      strategy: "provider-rest-adapter",
      adapterKind: "no-official-sdk-rest-adapter",
      providerClientInterface: "PegaCustomerServiceProviderClient",
      defaultHttpClient: "built-in-fetch",
      defaultFetchClient: "built-in-provider-rest-adapter",
      providerClientOverride: true,
      manifestImport: "no-client-initialization",
    },
    implementationStrategy: {
      strategy: "no-official-sdk-rest-adapter",
      reason: "No suitable official server-side JavaScript SDK was found for Pega Customer Service case operations; current Pega JavaScript SDK surfaces are Constellation UI/client orchestration assets, while DX API remains documented as REST endpoints.",
      checkedAt: "2026-06-25",
      rejectedLibraries: [
        {
          packageName: "@pega/constellationjs",
          result: "not-used-as-package-default",
          reason: "Pega-maintained package, but it delivers ConstellationJS engine files rather than a server-side Customer Service case client.",
        },
        {
          packageName: "@pega/auth",
          result: "not-used-as-package-default",
          reason: "Pega-maintained OAuth client infrastructure for Infinity and Launchpad, but not a typed Customer Service or DX case operations client.",
        },
        {
          packageName: "pegasystems/react-sdk",
          result: "not-used-as-package-default",
          reason: "Pega-maintained React SDK for Constellation DX components and alternative UI integration, not a backend ticketing provider client for Cognidesk operations.",
        },
      ],
    },
    providerClient: {
      interface: "PegaCustomerServiceProviderClient",
      injectionPolicy: "optional-runtime-override",
      importPolicy: "optional-host-override",
      defaultClient: "built-in-dx-rest-adapter",
    },
    providerRestAdapterSupportSurface: {
      source: "Built-in Pega DX REST adapter",
      adapterKind: "no-official-sdk-rest-adapter",
      checkedAt: "2026-06-25",
      operations: pegaCustomerServiceDelegatedOperationAllowlist,
    },
    checkedProviderApiCoverage: {
      verifiedAt: "2026-06-18",
      sourceKind: "checked-endpoint-family-inventory",
      coverageArtifact: "docs/provider-coverage/pega-customer-service-checked-dx-api-2026-06-18.inventory.json",
      checkedFamilyCount: 4,
      implementedFamilyCount: 3,
      gapFamilyCount: 1,
      implementedOperationCount: 6,
      implementationOwnership: "built-in-provider-rest-adapter",
    },
    channelCoverage: {
      cases: "typed-rest-adapter-create-read-update-search",
      assignmentActions: "typed-rest-adapter-submit",
      caseTypes: "typed-rest-adapter-list",
      readiness: "typed-rest-adapter-list",
      attachmentsDataPages: "provider-supported-not-typed",
      stageLifecycleActions: "provider-supported-not-typed",
      broaderCaseManagementAdmin: "not-covered",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
} as const satisfies ProviderManifestInput;

export const pegaCustomerServiceTicketingProviderManifest = defineProviderPackage(
  pegaCustomerServiceTicketingProviderManifestInput,
);
