import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import {
  ZOOM_MEETINGS_API_GENERATED_FUNCTION_COUNT,
} from "./meetings-api-client.generated.js";
import {
  ZOOM_MEETINGS_API_OPERATION_COUNT,
  ZOOM_MEETINGS_API_PATH_COUNT,
  ZOOM_MEETINGS_API_SPEC_VERSION,
} from "./meetings-api-operations.generated.js";

export const zoomVideoProviderManifest = defineProviderPackage({
  id: "video.zoom",
  name: "Zoom Meetings",
  packageName: "@cognidesk/integrations",
  provider: "zoom",
  category: "video",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Coverage includes generated per-operation functions for every operation in Zoom's official Meetings API Hub OpenAPI spec.",
      "Typed convenience helpers remain available for meetings create/list/read/update/delete, current-user readiness, webhook URL-validation handling, and x-zm-signature verification.",
      "This package is a generated Zoom Meetings API domain slice, not full Zoom platform coverage. Zoom Phone, Contact Center, Team Chat, Rooms, Marketplace app management outside the Meetings API Hub, account administration beyond this spec, and full webhook/event catalogs remain separate Zoom surfaces.",
      "The SDK user owns OAuth scopes, host delegation, account plan/admin settings, meeting lifecycle policy, recording/transcript consent, retention, deletion, and participant disclosure decisions.",
    ],
    evidence: [
      { label: "Zoom Meetings API Hub OpenAPI", url: "https://developers.zoom.us/api-hub/meetings/methods/endpoints.json" },
      { label: "Zoom Meetings API reference", url: "https://developers.zoom.us/docs/api/meetings/" },
      { label: "Zoom webhooks reference", url: "https://developers.zoom.us/docs/api/rest/webhook-reference/" },
      { label: "Zoom webhook validation", url: "https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint" },
    ],
  },
  credentialRequirements: [
    {
      id: "zoom-oauth-access-token",
      label: "Zoom OAuth access token",
      description: "Server-side OAuth access token for Zoom REST API meeting and user endpoints.",
      scopes: [
        "meeting:write",
        "meeting:read",
        "user:read",
        "meeting:write:meeting",
        "meeting:read:list_meetings",
        "meeting:read:meeting",
        "meeting:update:meeting",
        "meeting:delete:meeting",
        "user:read:user",
      ],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "zoom-webhook-secret-token",
      label: "Zoom webhook secret token",
      description: "Server-side secret token used to validate Zoom webhook request signatures.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "schedule",
      label: "Schedule Zoom meetings",
      description: "Creates Zoom meetings through SDK-user-selected scheduling or escalation workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "zoomMeeting", label: "Zoom Meeting" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Zoom meetings",
      description: "Creates Zoom meeting resources with SDK-user-supplied topic, timing, recurrence, and settings.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "zoomMeeting", label: "Zoom Meeting" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Zoom meetings",
      description: "Lists Zoom meetings and reads meeting details by meeting ID.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "zoomMeeting", label: "Zoom Meeting" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "delete-provider-object",
      label: "Delete Zoom meetings",
      description: "Deletes Zoom meetings when SDK-user lifecycle or retention policy permits deletion.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "zoomMeeting", label: "Zoom Meeting" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "update-provider-object",
      label: "Update Zoom meetings",
      description: "Updates Zoom meeting fields, recurrence, tracking fields, or settings when SDK-user policy permits mutation.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "zoomMeeting", label: "Zoom Meeting" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "receive",
      label: "Receive Zoom webhooks",
      description: "Validates and parses Zoom webhook payloads for SDK-user-owned meeting lifecycle workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "zoomWebhookEvent", label: "Zoom Webhook Event" },
        { kind: "zoomMeeting", label: "Zoom Meeting" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "zoom.request-signature",
      label: "Validate Zoom webhook signatures",
      description: "Validates Zoom x-zm-signature and x-zm-request-timestamp values and supports endpoint URL validation challenges.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "zoomSignedRequest", label: "Zoom Signed Request" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Zoom meetings and webhooks can contain participant identifiers, host details, invite links, meeting metadata, chat-capable workflow context, and recording-related event metadata.",
    "Zoom OAuth access tokens and webhook secret tokens stay server-side and are represented in Studio only as credential readiness.",
    "User consent, meeting disclosure, recording enablement, transcript use, retention, and deletion are owned by the SDK user's Zoom account configuration and application policy.",
  ],
  limitations: [
    "Available meeting operations depend on the SDK user's Zoom OAuth scopes, account plan, account-level settings, admin policy, and delegated host permissions.",
    "This package does not choose whether a video workflow is inbound, outbound, customer-facing, internal, recorded, retained, or escalated; those decisions remain SDK-user configuration.",
    "Live meeting media transport, captions, cloud recording retrieval, and telephony dial-out are outside this package's REST and webhook foundation.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    channelCoverage: {
      meetingsApiHub: "generated-per-operation-functions",
      meetings: "typed-create-list-read-update-delete",
      meetingsRecordingsRegistrantsReportsDevicesTspWebinars: "generated-full-surface-where-present-in-meetings-api-hub",
      currentUser: "typed-read",
      webhooks: "typed-validate-parse",
      webhookUrlValidation: "typed-response",
      zoomPhoneContactCenterTeamChatRoomsCalendar: "provider-supported-not-typed-separate-surface",
    },
    generatedProviderSliceVerification: {
      provider: "zoom-meetings-api-hub",
      apiVersion: ZOOM_MEETINGS_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/zoom-meetings-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/zoom-meetings-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/zoom-meetings-api-2026-06-18.functions.json",
      documentedPathCount: ZOOM_MEETINGS_API_PATH_COUNT,
      documentedOperationCount: ZOOM_MEETINGS_API_OPERATION_COUNT,
      implementedOperationCount: ZOOM_MEETINGS_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: ZOOM_MEETINGS_API_GENERATED_FUNCTION_COUNT,
    },
  },
});
