import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import {
  SES_FULL_API_GENERATED_FUNCTION_COUNT,
} from "./full-api-client.generated.js";
import {
  SES_FULL_API_MODEL_COUNT,
  SES_FULL_API_OPERATION_COUNT,
  SES_FULL_API_SPEC_VERSION,
} from "./full-api-operations.generated.js";

export const sesEmailProviderManifest = defineProviderPackage({
  id: "email.ses",
  name: "Amazon SES",
  packageName: "@cognidesk/integrations",
  provider: "ses",
  category: "email",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "full-provider-api",
    notes: [
      "Coverage includes generated per-operation functions for every operation in the official AWS SESv2 and classic SES API models.",
      "Typed convenience helpers remain available for support email workflows: SESv2 SendEmail/raw MIME send, account readiness, identities, templates, configuration sets, event destinations, suppression list reads, suppression removal, and SES/SNS notification parsing.",
      "The generated full API surface covers SESv2 identities/DKIM, contact lists, import/export jobs, reputation entities, tenants, dedicated IP pools, configuration-set mutation, plus classic SES receiving/control-plane actions such as receipt rules/rule sets/filters and custom verification templates.",
      "SNS/SQS topics, queues, subscriptions, S3 buckets, Lambda actions, HTTP webhook hosting, certificate fetching, retry/backoff, and event replay storage are separate AWS infrastructure surfaces owned by the SDK user.",
    ],
    evidence: [
      { label: "AWS official SESv2 API model", url: "https://github.com/aws/api-models-aws/blob/main/models/sesv2/service/2019-09-27/sesv2-2019-09-27.json" },
      { label: "AWS official classic SES API model", url: "https://github.com/aws/api-models-aws/blob/main/models/ses/service/2010-12-01/ses-2010-12-01.json" },
      { label: "AWS SDK SESv2 client API reference", url: "https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sesv2/" },
      { label: "AWS SDK classic SES client API reference", url: "https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ses/" },
      { label: "Amazon SES v2 SendEmail", url: "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html" },
      { label: "Amazon SES v2 GetAccount", url: "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetAccount.html" },
      { label: "Amazon SES v2 ListEmailIdentities", url: "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListEmailIdentities.html" },
      { label: "Amazon SES v2 ListEmailTemplates", url: "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListEmailTemplates.html" },
      { label: "Amazon SES v2 ListConfigurationSets", url: "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListConfigurationSets.html" },
      { label: "Amazon SES v2 ListSuppressedDestinations", url: "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListSuppressedDestinations.html" },
      { label: "Amazon SES v2 DeleteSuppressedDestination", url: "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteSuppressedDestination.html" },
      { label: "Amazon SES v2 GetConfigurationSetEventDestinations", url: "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetConfigurationSetEventDestinations.html" },
      { label: "Amazon SES email receiving", url: "https://docs.aws.amazon.com/ses/latest/dg/receiving-email.html" },
      { label: "Amazon SES receiving notification contents", url: "https://docs.aws.amazon.com/ses/latest/dg/receiving-email-notifications-contents.html" },
      { label: "Amazon SNS signature verification", url: "https://docs.aws.amazon.com/sns/latest/dg/sns-verify-signature-of-message.html" },
    ],
  },
  credentialRequirements: [
    {
      id: "aws-access-key-id",
      label: "AWS access key ID",
      description: "Server-side AWS access key ID scoped by the SDK user for Amazon SES v2 API calls.",
      scopes: [
        "ses:SendEmail",
        "ses:GetAccount",
        "ses:ListEmailIdentities",
        "ses:ListEmailTemplates",
        "ses:ListConfigurationSets",
        "ses:GetConfigurationSetEventDestinations",
        "ses:ListSuppressedDestinations",
        "ses:GetSuppressedDestination",
        "ses:DeleteSuppressedDestination",
        "ses:CreateReceiptRule",
        "ses:DescribeReceiptRuleSet",
        "ses:SetActiveReceiptRuleSet",
      ],
      required: true,
      metadata: {
        scopeKind: "provider-permission-labels",
        privilegeGuidance: "These strings are AWS IAM action names for SES v2, not OAuth scopes.",
      },
    },
    {
      id: "aws-secret-access-key",
      label: "AWS secret access key",
      description: "Server-side AWS secret access key used only for AWS Signature Version 4 request signing.",
      required: true,
    },
    {
      id: "aws-region",
      label: "AWS Region",
      description: "SDK-user-selected AWS Region where Amazon SES identities, templates, and configuration sets live.",
      required: true,
    },
    {
      id: "ses-sender-identity",
      label: "SES sender identity",
      description: "Verified SES sender email address or domain selected by the SDK user for outbound email.",
      required: false,
    },
    {
      id: "ses-event-ingestion",
      label: "SES event ingestion",
      description: "SDK-user-configured SNS/SQS/HTTP path and signature verification policy for SES delivery events.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Parse SES/SNS email notifications",
      description: "Parses SES sending and receiving notifications delivered to an SDK-user-operated SNS/SQS/HTTP ingestion path; does not fetch mailbox contents or S3-stored raw messages.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [
        { kind: "sesEvent", label: "SES Event" },
        { kind: "snsNotification", label: "SNS Notification" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Send Amazon SES email",
      description: "Sends simple, templated, or raw email through the Amazon SES v2 SendEmail API when SDK-user policy allows outbound contact.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "sesOutboundEmail", label: "SES Outbound Email" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "draft",
      label: "Build Amazon SES outbound payloads",
      description: "Builds simple, templated, or raw SES email payloads for SDK-user-owned approval and channel workflows.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "sesEmailDraft", label: "SES Email Draft" }],
      exposesSensitiveData: true,
    },
    {
      capability: "thread",
      label: "Use SES message metadata",
      description: "Associates outbound messages and SES events using message IDs, headers, tags, configuration sets, and SDK-user metadata.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "sesMessage", label: "SES Message" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "attach",
      label: "Use raw MIME attachments",
      description: "Supports raw MIME sending for SDK-user-governed attachments and advanced email composition.",
      audiences: ["customer-facing", "mixed"],
      providerObjects: [{ kind: "sesRawMessage", label: "SES Raw Message" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read SES account and identities",
      description: "Reads Amazon SES account readiness, verified identities, configuration sets, and templates for Studio-visible provider readiness.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "sesAccount", label: "SES Account" },
        { kind: "sesIdentity", label: "SES Identity" },
        { kind: "sesConfigurationSet", label: "SES Configuration Set" },
        { kind: "sesTemplate", label: "SES Template" },
        { kind: "sesSuppressedDestination", label: "SES Suppressed Destination" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "List SES provider resources",
      description: "Lists SES identities, configuration sets, and templates with SDK-user-supplied pagination.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "sesIdentity", label: "SES Identity" },
        { kind: "sesConfigurationSet", label: "SES Configuration Set" },
        { kind: "sesTemplate", label: "SES Template" },
        { kind: "sesSuppressedDestination", label: "SES Suppressed Destination" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "update-provider-object",
      label: "Delete SES suppressed destinations",
      description: "Deletes Amazon SES suppression-list entries when SDK-user policy permits suppression lifecycle changes.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "sesSuppressedDestination", label: "SES Suppressed Destination" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "SES email bodies, recipients, sender identities, headers, tags, templates, configuration sets, delivery events, and raw MIME content can contain customer data.",
    "AWS access keys, secret keys, session tokens, webhook secrets, SNS certificates, and SQS credentials stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "The SDK user chooses regions, IAM policy, sender identities, suppression policy, configuration sets, templates, event routing, webhook verification, retention, and outbound approval policy.",
    "Amazon SES does not expose a mailbox-style read/search API for sent message bodies; this package reads provider resources and parses delivery events rather than reconstructing complete message history.",
    "SNS X.509 signature validation requires a verifier hook or AWS SDK/user infrastructure; requiring verification without a verifier fails closed.",
  ],
  metadata: {
    docs: "https://docs.aws.amazon.com/ses/latest/APIReference-V2/Welcome.html",
    snsSignatureDocs: "https://docs.aws.amazon.com/sns/latest/dg/sns-verify-signature-of-message.html",
    channelCoverage: {
      fullSesV2AndClassicApiModels: "generated-per-operation-functions",
      sendEmail: "typed-send-and-generated-full-surface",
      rawMimeSend: "typed-send-and-generated-full-surface",
      sesSnsNotifications: "typed-parse",
      accountReadiness: "typed-read",
      identities: "typed-list",
      templates: "typed-list",
      configurationSets: "typed-list-read",
      suppressions: "typed-list-read-delete",
      identityLifecycleDkimPolicies: "generated-per-operation-functions",
      contactListsImportExportJobs: "generated-per-operation-functions",
      reputationTenantsDedicatedIpPools: "generated-per-operation-functions",
      classicReceivingReceiptRules: "generated-per-operation-functions",
      classicCustomVerificationAndNotificationAttributes: "generated-per-operation-functions",
      mailboxStyleMessageRead: "not-covered",
    },
    iamActions: [
      "ses:SendEmail",
      "ses:GetAccount",
      "ses:ListEmailIdentities",
      "ses:ListEmailTemplates",
      "ses:ListConfigurationSets",
      "ses:GetConfigurationSetEventDestinations",
      "ses:ListSuppressedDestinations",
      "ses:GetSuppressedDestination",
      "ses:DeleteSuppressedDestination",
      "ses:CreateReceiptRule",
      "ses:DescribeReceiptRuleSet",
      "ses:SetActiveReceiptRuleSet",
    ],
    fullProviderApiVerification: {
      provider: "ses",
      apiVersion: SES_FULL_API_SPEC_VERSION,
      verifiedAt: "2026-06-18",
      coverageArtifact: "docs/provider-coverage/ses-full-api-2026-06-18.operations.json",
      operationCatalogArtifact: "docs/provider-coverage/ses-full-api-2026-06-18.operations.json",
      functionCatalogArtifact: "docs/provider-coverage/ses-full-api-2026-06-18.functions.json",
      documentedModelCount: SES_FULL_API_MODEL_COUNT,
      documentedOperationCount: SES_FULL_API_OPERATION_COUNT,
      implementedOperationCount: SES_FULL_API_OPERATION_COUNT,
      unimplementedOperationCount: 0,
      generatedFunctionCount: SES_FULL_API_GENERATED_FUNCTION_COUNT,
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
