import { defineIntegrationProviderPackage } from "@cognidesk/integration-kit";

export const vonageVoiceProviderManifest = defineIntegrationProviderPackage({
  id: "voice.vonage",
  name: "Vonage Voice",
  packageName: "@cognidesk/integration-voice-vonage",
  provider: "vonage",
  category: "voice",
  trustLevel: "official",
  directions: ["inbound-only", "outbound-only", "bidirectional"],
  channelAudiences: ["customer-facing", "mixed"],
  coverage: {
    scope: "provider-api-subset",
    notes: [
      "Implements normalized Vonage Voice call-control, NCCO, webhook, readiness, and raw SDK access with the official Vonage server SDK.",
      "Raw Vonage SDK access is exposed as an escape hatch; this package does not re-export the whole SDK as Cognidesk-owned API coverage.",
      "Broader Vonage platform products, Client SDK behavior, consent, retention, and telephony policy remain SDK-user/provider configuration.",
    ],
    evidence: [
      { label: "Vonage Server SDK package", url: "https://www.npmjs.com/package/@vonage/server-sdk" },
      { label: "Vonage Voice API reference", url: "https://developer.vonage.com/en/api/voice" },
      { label: "Vonage Voice webhooks", url: "https://developer.vonage.com/en/voice/voice-api/webhook-reference" },
      { label: "Vonage NCCO reference", url: "https://developer.vonage.com/en/voice/voice-api/ncco-reference" },
    ],
  },
  credentialRequirements: [
    {
      id: "vonage-application",
      label: "Vonage application credentials",
      description: "Vonage Application ID and private key/JWT credentials used by the official SDK.",
      required: true,
      metadata: { scopeKind: "provider-permission" },
    },
    {
      id: "vonage-webhook-signature",
      label: "Vonage webhook signature secret",
      description: "Optional signature secret or JWT verification setup for signed Vonage callbacks.",
      required: false,
      metadata: { scopeKind: "provider-permission" },
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive voice webhooks",
      description: "Parses Vonage answer, event, and fallback callbacks.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "vonageCall", label: "Vonage Call" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "send",
      label: "Create outbound calls",
      description: "Creates outbound calls through the Vonage Voice SDK.",
      audiences: ["customer-facing"],
      providerObjects: [{ kind: "vonageCall", label: "Vonage Call" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
    },
    {
      capability: "media",
      label: "NCCO voice media",
      description: "Builds NCCO websocket/talk actions for Cognidesk voice sessions.",
      audiences: ["customer-facing", "internal-support"],
      providerObjects: [{ kind: "vonageNcco", label: "Vonage NCCO" }],
      requiresCredential: false,
    },
    {
      capability: "transfer",
      label: "Transfer active calls",
      description: "Transfers active calls through Vonage's documented modify-call action.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "vonageCall", label: "Vonage Call" }],
      requiresCredential: true,
      sideEffect: true,
      changesWorkflow: true,
    },
    {
      capability: "voice.webhook-signature",
      label: "Validate Vonage webhooks",
      description: "Validates signed Vonage callbacks when configured by the SDK user.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "vonageWebhook", label: "Vonage Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "voice.call.answer",
      providerOperation: "parseWebhook",
      capability: "receive",
      label: "Receive voice webhook",
      providerObject: "vonageCall",
      audiences: ["customer-facing"],
      exposesSensitiveData: true,
    },
    {
      alias: "voice.call.start",
      providerOperation: "createOutboundCall",
      capability: "send",
      label: "Create outbound call",
      providerObject: "vonageCall",
      audiences: ["customer-facing"],
      sideEffect: true,
      externallyVisible: true,
      requiresApproval: true,
      exposesSensitiveData: true,
    },
    {
      alias: "voice.call.transfer",
      providerOperation: "updateCall",
      capability: "transfer",
      label: "Transfer call",
      providerObject: "vonageCall",
      audiences: ["internal-support"],
      sideEffect: true,
      changesWorkflow: true,
    },
  ],
  privacyNotes: [
    "Phone numbers, call metadata, webhook parameters, NCCO URLs, and conversation identifiers can contain customer data and are exchanged with Vonage.",
    "Vonage credentials stay server-side and are never issued to browsers by this package.",
  ],
  limitations: [
    "Live call readiness depends on the SDK user's Vonage application, numbers, webhook URLs, regions, and account permissions.",
  ],
  metadata: {
    implementation: {
      strategy: "official-sdk",
      sdkPackage: "@vonage/server-sdk",
      verifiedVersion: "3.27.0",
      verifiedAt: "2026-06-21",
      dependencyCaveat: "The server SDK includes multiple Vonage product modules; reassess service-specific packages before tightening dependency budgets.",
    },
    rawClient: {
      export: "getRawClient",
      coverage: "upstream-sdk",
    },
  },
  maintainers: [{ name: "Cognidesk", type: "official" }],
});
