import { defineIntegrationProviderPackage as defineProviderPackage } from "../../provider-manifest.js";
import {
  SHOPIFY_ADMIN_GRAPHQL_API_VERSION,
  SHOPIFY_ADMIN_GRAPHQL_CATALOG_SOURCE,
  SHOPIFY_ADMIN_GRAPHQL_GENERATED_PER_ROOT_FIELD_WRAPPER_COUNT,
  SHOPIFY_ADMIN_GRAPHQL_HELPER_CATALOG_ENTRY_COUNT,
  SHOPIFY_ADMIN_GRAPHQL_MUTATION_FIELD_COUNT,
  SHOPIFY_ADMIN_GRAPHQL_QUERY_ROOT_FIELD_COUNT,
  SHOPIFY_ADMIN_GRAPHQL_ROOT_FIELD_COUNT,
  SHOPIFY_ADMIN_GRAPHQL_SCHEMA_CATALOG_GENERATED_AT,
  SHOPIFY_ADMIN_GRAPHQL_SELECTED_TYPED_HELPER_COUNT,
  SHOPIFY_ADMIN_GRAPHQL_SELECTED_TYPED_ROOT_FIELD_COUNT,
  SHOPIFY_PLATFORM_GAPS,
} from "./admin-graphql-inventory.generated.js";

export const shopifyEcommerceProviderManifest = defineProviderPackage({
  id: "ecommerce.shopify",
  name: "Shopify",
  packageName: "@cognidesk/integrations",
  provider: "shopify",
  category: "ecommerce",
  trustLevel: "official",
  directions: ["receive-only", "send-only", "bidirectional"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  coverage: {
    scope: "support-workflow-subset",
    notes: [
      `Official Shopify Admin GraphQL ${SHOPIFY_ADMIN_GRAPHQL_API_VERSION} docs are inventoried as ${SHOPIFY_ADMIN_GRAPHQL_ROOT_FIELD_COUNT} root fields (${SHOPIFY_ADMIN_GRAPHQL_QUERY_ROOT_FIELD_COUNT} QueryRoot, ${SHOPIFY_ADMIN_GRAPHQL_MUTATION_FIELD_COUNT} Mutation), but this package implements only selected typed helpers plus a raw Admin GraphQL escape hatch.`,
      "Coverage is limited to selected Shopify Admin GraphQL support primitives: shop, order, customer, and product reads/searches; draft order creation; explicit raw Admin GraphQL escape-hatch execution; and webhook HMAC parsing.",
      "The package does not implement generated per-root-field Admin GraphQL wrappers, full Shopify Admin API coverage, Storefront, Functions, Payments, Markets, Fulfillment, Inventory, Billing, Checkout, Online Store, REST Admin, or app-management API coverage.",
      "The SDK user owns Admin API version selection, app scopes, webhook topic registration, commerce mutation policy, privacy, consent, and retention decisions.",
    ],
    evidence: [
      { label: "Shopify Admin GraphQL API reference", url: "https://shopify.dev/docs/api/admin-graphql/latest" },
      { label: "Shopify Admin GraphQL QueryRoot 2026-04 catalog", url: "https://shopify.dev/docs/api/admin-graphql/2026-04/objects/QueryRoot" },
      { label: "Shopify Admin GraphQL Mutation 2026-04 catalog", url: "https://shopify.dev/docs/api/admin-graphql/2026-04/objects/Mutation" },
      { label: "Shopify Admin GraphQL products query", url: "https://shopify.dev/docs/api/admin-graphql/latest/queries/products" },
      { label: "Shopify webhook HMAC validation", url: "https://shopify.dev/docs/apps/build/webhooks/subscribe/https#step-5-verify-the-webhook" },
      { label: "Shopify Storefront API reference", url: "https://shopify.dev/docs/api/storefront/latest" },
      { label: "Shopify Functions API reference", url: "https://shopify.dev/docs/api/functions/latest" },
      { label: "Shopify payments extensions", url: "https://shopify.dev/docs/apps/build/payments" },
    ],
  },
  credentialRequirements: [
    {
      id: "shopify-shop-domain",
      label: "Shopify shop domain",
      description: "The SDK user's Shopify admin shop domain, for example example.myshopify.com.",
      required: true,
    },
    {
      id: "shopify-admin-access",
      label: "Shopify Admin API access",
      description: "Server-side Admin API access token with SDK-user-selected scopes.",
      scopes: ["read_orders", "read_customers", "read_products", "write_draft_orders"],
      required: true,
      metadata: { scopeKind: "provider-oauth-scopes" },
    },
    {
      id: "shopify-webhook-secret",
      label: "Shopify webhook secret",
      description: "Server-side secret used to validate Shopify webhook HMAC signatures.",
      required: false,
    },
  ],
  capabilities: [
    {
      capability: "receive",
      label: "Receive Shopify webhooks",
      description: "Validates and parses Shopify webhooks for SDK-user-owned commerce support workflows.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "shopifyWebhook", label: "Shopify Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "read-provider-object",
      label: "Read Shopify records",
      description: "Reads Shopify Admin GraphQL records such as shop, order, customer, product, and draft order nodes.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [
        { kind: "shopifyShop", label: "Shopify Shop" },
        { kind: "shopifyOrder", label: "Shopify Order" },
        { kind: "shopifyCustomer", label: "Shopify Customer" },
        { kind: "shopifyProduct", label: "Shopify Product" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search Shopify records",
      description: "Searches Shopify orders, customers, and products with SDK-user-supplied Admin GraphQL queries.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [
        { kind: "shopifyOrder", label: "Shopify Order" },
        { kind: "shopifyCustomer", label: "Shopify Customer" },
        { kind: "shopifyProduct", label: "Shopify Product" },
      ],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "create-provider-object",
      label: "Create Shopify draft orders",
      description: "Creates Shopify draft orders through Admin GraphQL when SDK-user policy permits commerce mutations.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "shopifyDraftOrder", label: "Shopify Draft Order" }],
      requiresCredential: true,
      sideEffect: true,
      exposesSensitiveData: true,
      changesWorkflow: true,
    },
    {
      capability: "ecommerce.graphql",
      label: "Run Shopify Admin GraphQL",
      description: "Runs SDK-user-selected raw Admin GraphQL operations against the configured Shopify shop as an explicit escape hatch; this does not imply full-provider API coverage.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "shopifyGraphqlResult", label: "Shopify GraphQL Result" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  privacyNotes: [
    "Shopify records can include customer contact data, order contents, payment state, fulfillment state, addresses, discounts, and commerce workflow metadata.",
    "Admin API tokens and webhook secrets stay server-side; Studio receives only readiness status and policy-visible capability metadata.",
  ],
  limitations: [
    "The SDK user chooses Admin API version, scopes, webhook topics, customer visibility, fulfillment behavior, consent rules, and retention policy.",
    "This package provides API foundations and signature checks; it does not decide when to create draft orders, contact customers, issue discounts, refund orders, or expose commerce data.",
    "Available fields and mutations depend on the SDK user's Shopify plan, app scopes, shop settings, installed apps, and selected Admin API version.",
    "The generated Admin GraphQL inventory is a root-field catalog from official docs, not a public static introspection schema and not generated callable coverage for every root field.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    defaultGraphqlAdminApiVersion: SHOPIFY_ADMIN_GRAPHQL_API_VERSION,
    docs: "https://shopify.dev/docs/api/admin-graphql/latest",
    channelCoverage: {
      shop: "typed-read",
      orders: "typed-read-search",
      customers: "typed-read-search",
      products: "typed-read-search",
      draftOrders: "typed-read-create",
      webhooks: "typed-validate-parse",
      adminGraphqlEscapeHatch: "typed-raw-graphql-escape-hatch",
      adminGraphqlRootFieldCatalog: "generated-inventory-not-generated-wrappers",
      storefrontFunctionsPaymentsRestAdminAppSurfaces: "provider-supported-not-implemented",
      checkoutFulfillmentInventoryMarketsBillingOnlineStore: "provider-supported-not-typed",
    },
    adminGraphqlSchemaCatalog: {
      apiVersion: SHOPIFY_ADMIN_GRAPHQL_API_VERSION,
      generatedAt: SHOPIFY_ADMIN_GRAPHQL_SCHEMA_CATALOG_GENERATED_AT,
      docs: SHOPIFY_ADMIN_GRAPHQL_CATALOG_SOURCE.docs,
      versionedDocs: SHOPIFY_ADMIN_GRAPHQL_CATALOG_SOURCE.versionedDocs,
      queryRoot: SHOPIFY_ADMIN_GRAPHQL_CATALOG_SOURCE.queryRoot,
      mutation: SHOPIFY_ADMIN_GRAPHQL_CATALOG_SOURCE.mutation,
      rootFieldCatalogArtifact: "docs/provider-coverage/shopify-admin-graphql-2026-04-2026-06-18.root-fields.json",
      functionCatalogArtifact: "docs/provider-coverage/shopify-admin-graphql-2026-04-2026-06-18.functions.json",
      queryRootFieldCount: SHOPIFY_ADMIN_GRAPHQL_QUERY_ROOT_FIELD_COUNT,
      mutationFieldCount: SHOPIFY_ADMIN_GRAPHQL_MUTATION_FIELD_COUNT,
      rootFieldCount: SHOPIFY_ADMIN_GRAPHQL_ROOT_FIELD_COUNT,
      selectedTypedHelperCount: SHOPIFY_ADMIN_GRAPHQL_SELECTED_TYPED_HELPER_COUNT,
      helperCatalogEntryCount: SHOPIFY_ADMIN_GRAPHQL_HELPER_CATALOG_ENTRY_COUNT,
      selectedTypedRootFieldCount: SHOPIFY_ADMIN_GRAPHQL_SELECTED_TYPED_ROOT_FIELD_COUNT,
      generatedPerRootFieldWrapperCount: SHOPIFY_ADMIN_GRAPHQL_GENERATED_PER_ROOT_FIELD_WRAPPER_COUNT,
      rawAdminGraphqlEscapeHatch: true,
      fullShopifyPlatformCoverage: false,
      publicStaticSchemaAvailability: SHOPIFY_ADMIN_GRAPHQL_CATALOG_SOURCE.publicStaticSchemaAvailability,
      platformGaps: SHOPIFY_PLATFORM_GAPS,
    },
    rawProviderRequest: {
      capability: "ecommerce.graphql",
      acknowledgementRequired: true,
      coverage: "escape-hatch-not-full-provider-api",
    },
  },
});
