import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const cognideskHelpCenterProviderManifest = defineProviderPackage({
  id: "help-center.cognidesk",
  name: "Cognidesk Help Center",
  packageName: "@cognidesk/integration-help-center-cognidesk",
  provider: "cognidesk",
  category: "help-center",
  trustLevel: "official",
  directions: ["receive-only", "inbound-only"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    {
      id: "help-center-source",
      label: "Help center source",
      description: "SDK-user-configured local content source, HTTP source, or remote help center provider client override.",
      required: true,
    },
    {
      id: "help-center-webhook-secret",
      label: "Help center webhook secret",
      description: "Shared HMAC secret used to verify help center content webhooks.",
      required: false,
    },
  ],
  coverage: {
    scope: "local-protocol",
    notes: [
      "Coverage is limited to Cognidesk local help-center source search/fetch/readiness, built-in HTTP source adapters, remote HelpCenterClient overrides, and Cognidesk HMAC webhook normalization.",
      "The package does not implement a named external help-center provider API or broader article/category/section/versioning/locale/permission/webhook administration clients; SDK users can configure generic HTTP sources or wrap provider-specific APIs behind a HelpCenter provider client.",
    ],
    evidence: [],
  },
  capabilities: [
    {
      capability: "read-provider-object",
      label: "Fetch help center articles",
      description: "Fetches articles from SDK-user-configured local sources, HTTP sources, or a HelpCenter provider client override.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "help-center-article", label: "Help Center Article" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search help center articles",
      description: "Searches local help center articles, HTTP sources, or a HelpCenter provider client override.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "help-center-article", label: "Help Center Article" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "receive",
      label: "Receive help center content events",
      description: "Validates signed content webhooks and normalizes article ingestion events.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "help-center-webhook", label: "Help Center Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "help-center.webhook-signature",
      label: "Validate help center webhook signatures",
      description: "Validates HMAC-SHA256 signatures for generic help center content webhooks.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "signed-help-center-webhook", label: "Signed Help Center Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "cognidesk.help-center.article.search",
      capability: "search-provider-object",
      label: "Search help center articles",
      providerObject: "help-center-article",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "cognidesk.help-center.article.fetch",
      capability: "read-provider-object",
      label: "Fetch help center article",
      providerObject: "help-center-article",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "cognidesk.help-center.webhook.parse",
      capability: "help-center.webhook-signature",
      label: "Parse help center webhook",
      providerObject: "signed-help-center-webhook",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Help center content can include public support guidance, draft metadata, author data, locale data, and SDK-user-defined source metadata.",
    "Remote provider credentials, HTTP headers, access tokens, and webhook secrets stay in the host runtime and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "Remote provider transport, source selection, article visibility, indexing cadence, ranking, retention, locale fallback, and answer policy are owned by SDK user configuration.",
    "Local search is explicit lexical filtering; semantic ranking belongs in a configured search provider or evaluator.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    implementation: {
      strategy: "local-protocol",
      sdkPackage: "@cognidesk/integration-help-center-cognidesk",
      runtimePackage: "@cognidesk/integration-help-center-cognidesk",
      protocolSource: "Cognidesk local help-center source protocol",
      manifestImport: "no-sdk-client-initialization",
      integrationKitStatus: "implemented",
      externalProviderSdk: "not-applicable-internal-provider",
      checkedAt: "2026-06-25",
      providerSdkDecision: "internal-provider/local-runtime/no-provider-SDK",
      defaultClientPolicy: "built-in-http-source-when-base-url-configured",
      typedClientOverride: "HelpCenterProviderClient",
      reason: "Cognidesk Help Center is an internal local/HTTP-source protocol and host-client adapter rather than a named external help-center provider SDK.",
      rejectedSdkPackages: [],
    },
    channelCoverage: {
      articles: "typed-read-search",
      readiness: "typed-local-or-http-source-readiness-or-provider-client-delegation",
      contentWebhooks: "typed-validate-parse",
      providerSpecificAdminLocalePermissionVersioning: "not-covered",
    },
    importPolicy: "local-source-http-source-or-provider-client",
    defaultClientPolicy: "built-in-http-source-when-base-url-configured",
  },
});
