import { defineIntegrationProviderPackage as defineProviderPackage } from "@cognidesk/integration-kit";

export const cognideskHelpCenterProviderManifest = defineProviderPackage({
  id: "helpcenter.cognidesk",
  name: "Cognidesk Help Center",
  packageName: "@cognidesk/integration-help-center-cognidesk",
  provider: "cognidesk",
  category: "helpCenter",
  trustLevel: "official",
  directions: ["receive-only", "inbound-only"],
  channelAudiences: ["customer-facing", "internal-support", "mixed"],
  credentialRequirements: [
    {
      id: "helpcenter-source",
      label: "Help center source",
      description: "SDK-user-configured local or HTTP help center content source.",
      required: true,
    },
    {
      id: "helpcenter-webhook-secret",
      label: "Help center webhook secret",
      description: "Shared HMAC secret used to verify help center content webhooks.",
      required: false,
    },
  ],
  coverage: {
    scope: "local-protocol",
    notes: [
      "Coverage is limited to Cognidesk local or generic HTTP help-center source search/fetch/readiness plus Cognidesk HMAC webhook normalization.",
      "The package does not implement a named external help-center provider API for article/category/section/versioning/locale/permission/webhook administration; SDK users must wrap provider-specific APIs behind the configured source endpoints.",
    ],
    evidence: [],
  },
  capabilities: [
    {
      capability: "read-provider-object",
      label: "Fetch help center articles",
      description: "Fetches articles from SDK-user-configured local or generic HTTP help center sources.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "helpCenterArticle", label: "Help Center Article" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "search-provider-object",
      label: "Search help center articles",
      description: "Searches configured help center article sources using explicit source search parameters.",
      audiences: ["customer-facing", "internal-support", "mixed"],
      providerObjects: [{ kind: "helpCenterArticle", label: "Help Center Article" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "receive",
      label: "Receive help center content events",
      description: "Validates signed content webhooks and normalizes article ingestion events.",
      audiences: ["internal-support", "mixed"],
      providerObjects: [{ kind: "helpCenterWebhook", label: "Help Center Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      capability: "helpCenter.webhook-signature",
      label: "Validate help center webhook signatures",
      description: "Validates HMAC-SHA256 signatures for generic help center content webhooks.",
      audiences: ["internal-support"],
      providerObjects: [{ kind: "signedHelpCenterWebhook", label: "Signed Help Center Webhook" }],
      requiresCredential: true,
      exposesSensitiveData: true,
      extension: true,
    },
  ],
  operations: [
    {
      alias: "cognidesk.helpCenter.article.search",
      capability: "search-provider-object",
      label: "Search help center articles",
      providerObject: "helpCenterArticle",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "cognidesk.helpCenter.article.fetch",
      capability: "read-provider-object",
      label: "Fetch help center article",
      providerObject: "helpCenterArticle",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
    {
      alias: "cognidesk.helpCenter.webhook.parse",
      capability: "helpCenter.webhook-signature",
      label: "Parse help center webhook",
      providerObject: "signedHelpCenterWebhook",
      extension: true,
      requiresCredential: true,
      exposesSensitiveData: true,
    },
  ],
  privacyNotes: [
    "Help center content can include public support guidance, draft metadata, author data, locale data, and SDK-user-defined source metadata.",
    "HTTP headers, access tokens, and webhook secrets stay server-side and are represented in Studio only as readiness state.",
  ],
  limitations: [
    "Source selection, article visibility, indexing cadence, ranking, retention, locale fallback, and answer policy are owned by SDK user configuration.",
    "Local search is explicit lexical filtering; semantic ranking belongs in a configured search provider or evaluator.",
  ],
  maintainers: [{ name: "Cognidesk", type: "official" }],
  metadata: {
    channelCoverage: {
      articles: "typed-read-search",
      readiness: "typed-readiness",
      contentWebhooks: "typed-validate-parse",
      providerSpecificAdminLocalePermissionVersioning: "not-covered",
    },
  },
});
